### ISSUE TITLE
[BUG] : changing DB Password, error 1045 even after changing config files

### ISSUE THREAD

**Issue by christianlx** [OCSInventory-NG/OCSInventory-ocsreports#1001]
**OCS Inventory version**
Version : 2.7 installed on a Centos8 Server. Repo used : rpm.ocsinventory-ng.org/ocsinventory-release-latest.el8.ocs.noarch.rpm

**Describe the bug**
Error SQL 1045 after changing the ocs/ocs account in MariaDB

**To Reproduce**
Clean install from RPM. 
Installation wizard OK
I change the password of the default ocs/ocs account in Mariabd
Update the following config files : ocs-inventory-server.conf in httpd/conf.d and dbconfig.inc.php in /usr/share/ocsinventory-reports/ocsreports. I Also find the password in ipdiscover-util.pl
Restart httpd
Error 1045

**Additional context**
The password seems to be hard coded in another config file

**Comment by gillesdubois** [comment]
Hi @christianlx, 

The right dbconfig.inc.php file is located in /var/lib/ocsinventory-reports/config/

Regards,
Gilles Dubois.

**Comment by christianlx** [comment]
Thanks Gilles, I hadn't though of searching the dbconfig elsewhere. Anyway, your solution isn't correct on Centos, I found the good file in /etc/ocsinventory/ocsinventory-reports/
