### ISSUE TITLE
Save "Show  X entries" per user

### ISSUE THREAD

**Issue by MyTheValentinus** [OCSInventory-NG/OCSInventory-ocsreports#101]
Proposition de zufflaur sur le chat IRC.
Save le nombre d'entrées à afficher pour chaque utilisateur.

**Comment by zufflaur** [comment]
En fait, sauvegarder les paramètres d'affichage global (en tout cas pour la page All Computers)
THX

**Comment by gillesdubois** [comment]
https://github.com/OCSInventory-NG/OCSInventory-ocsreports/issues/63
