### ISSUE TITLE
Could you go back to the previous report where the operating system versions were shown?

### ISSUE THREAD

**Issue by sasousuke** [OCSInventory-NG/OCSInventory-ocsreports#1012]
When using an older version of OCS the current release of the system is sent to the server, for example "Ubuntu 18.04.1 LTS". In the current one, only the distribution that is used is sent, not the release. Attached image of shipping statistics by both agents.
![Screenshot_2020-08-17 OCS Inventory](https://user-images.githubusercontent.com/11823498/90399273-b3717800-e068-11ea-8252-2a8eb6152556.png)

**Comment by charleneauger** [comment]
Hi @sasousuke ,

The release number has been added on Unix Agent with this [PR](https://github.com/OCSInventory-NG/UnixAgent/pull/294).

Best regards,
Charlene Auger
