### ISSUE TITLE
[BUG] OCSInventory-ocsreports Software category no show any software by criteria

### ISSUE THREAD

**Issue by sasousuke** [OCSInventory-NG/OCSInventory-ocsreports#1013]
**OCS Inventory version**
Version : OCSInventory-ocsreports 2.7

**Describe the bug**
Following the directions on the [site](https://wiki.ocsinventory-ng.org/04.Management-console-and-its-advanced-features/Using-Software-Categorization/) for creating software categories, one is created with the name "WebBroser" and specified in the name of the software "firefox", no results are obtained. However, when filtering the list of software installed on inventoried computers, their existence is reflected.

**Screenshots**

*Category created*
![Screenshot_2020-08-26 OCS Inventory(2)](https://user-images.githubusercontent.com/11823498/91325844-a9025d00-e791-11ea-99e2-365f5008363d.png)
*List of software with firefox filter*
![Screenshot_2020-08-26 OCS Inventory(5)](https://user-images.githubusercontent.com/11823498/91325936-c1727780-e791-11ea-9f17-20f945ccd574.png)
*Result in WebBrowser Category*
![Screenshot_2020-08-26 OCS Inventory(4)](https://user-images.githubusercontent.com/11823498/91325966-c9cab280-e791-11ea-9cdd-8903bbf47618.png)

**Comment by charleneauger** [comment]
Hi @sasousuke ,

To update a software category entries, you need to wait or trigger an agent's inventory. Have the inventories been reported since the creation ?

Best regards,
Charlene Auger

**Comment by sasousuke** [comment]
After 12 hours in which at least 3 PCs must have sent the inventory report, I see that it only shows the results of the Ubuntu computer, not the Windows one from which I do the tests. I even force resend the data from it and get the same results. I think maybe it is the regular expression that I try to capture the data with.

*Configuration of WebBrowser Category*
![Screenshot_2020-08-27 OCS Inventory](https://user-images.githubusercontent.com/11823498/91450882-ccd5a980-e84a-11ea-8c9f-03f1445d3706.png)

*PC with Windows OS*
![Screenshot_2020-08-27 OCS Inventory(2)](https://user-images.githubusercontent.com/11823498/91451080-0a3a3700-e84b-11ea-878f-e09df0c43171.png)

*Software Mozilla Firefox in PC with Windows OS*
![Screenshot_2020-08-27 OCS Inventory(1)](https://user-images.githubusercontent.com/11823498/91451141-1cb47080-e84b-11ea-86ad-8482b327551e.png)

**Comment by charleneauger** [comment]
@sasousuke ,

I tested with the same configuration and after my Windows inventory Mozilla is correctly report on my category.

![image](https://user-images.githubusercontent.com/28924550/91453350-e513eb80-e87f-11ea-8793-a299e0b13529.png)

It's good for you ?

Regards,
Charlene Auger

**Comment by sasousuke** [comment]
@charleneauger

I have created another category named DICOM Viewer and the Ubuntu mode identifies me well but not Windows. I'm going to try putting exactly the name of the installed software just as the auto-completion of the form recommends.

**Comment by charleneauger** [comment]
Hi @sasousuke 

Can you try with the latest server version ? Between 2.7 and 2.8.1, a lot of fix has been committed.

Best regards,
Charlene

**Comment by charleneauger** [comment]
Hi,

Since there is no anwser, I'll now close the issue.

Regards,
Charlene
