### ISSUE TITLE
No software sent to OCS Server

### ISSUE THREAD

**Issue by windshaman** [OCSInventory-NG/OCSInventory-ocsreports#1019]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General information
Operating system :  Windows 10 Pro

### OCS Inventory information
Windows agent version : 2.7.0.1

### Problem's description
Installed software are found on computers but are not listed in OCS reports GUI. 

### Inventory log file
https://pastebin.com/KXQgLYHf

**Comment by windshaman** [comment]
Thank you @charleneauger . So, the issue is still here and I'm unable to find what's going on. Do you need further logs ?

**Comment by charleneauger** [comment]
@windshaman , the software structure has been recently reworked. As I can see with this php warning you have 2.7 release version of the server. Can you try with a [nightly version](http://download.ocsinventory-ng.org/nightly/)  (more recent and with many fix bug) ?

Best regards,
Charlene

**Comment by windshaman** [comment]
@charleneauger Thank you, it works with 2.7-nightly-2020-08-31

Best regards
