### ISSUE TITLE
VISU search display blank page at OCSreport version 2.7

### ISSUE THREAD

**Issue by maulananoor** [OCSInventory-NG/OCSInventory-ocsreports#1021]
the function "Search with various criteria" in the menu does not display any results
only blank result. 

![image](https://user-images.githubusercontent.com/25914408/92438448-68680200-f1db-11ea-8a8f-48775da6d2c3.png)

![image](https://user-images.githubusercontent.com/25914408/92438363-3f477180-f1db-11ea-8726-b8cdf2b1bdcc.png)

**Comment by alacn1** [comment]
Hello. Post your apache error log of this page access. It may contain what caused this problem.

**Comment by charleneauger** [comment]
Hi @maulananoor ,

OCS Inventory use PHP 5.5 and higher as you can see on the [documentation](http://wiki.ocsinventory-ng.org/01.Prerequisites/Libraries-version/).

Best regards,
Charlene Auger
