### ISSUE TITLE
CVE don't work

### ISSUE THREAD

**Issue by mattoussaint** [OCSInventory-NG/OCSInventory-ocsreports#1024]
**OCS Inventory version**
Version : 2.8 server from scratch

**Describe the bug**
CVE execution result is always "0 CVE has been added to database". Problem already observed on 2.7 OCS version

**To Reproduce**
1. Install an OCS server
2. Execute inventories of machines in order to populate the database (1297 softwares in my case, some of which are intentionally obsoletes)
3. Activate and configure the CVE function in OCS
4. as root, run php cron_cve.php under /usr/share/ocsinventory-reports/ocsreports/crontab/

**Expected behavior**
Viewing CVE / CVSS in OCS / Inventory / CVE reports

**Additional context**
Running the script seems to have a problem at :
**Processing Python Software Foundation softwares ...
PHP Warning:  preg_match(): Unknown modifier 'T' in /usr/share/ocsinventory-reports/ocsreports/require/cve/Cve.php on line 267**

**Comment by gillesdubois** [comment]
Hi,

`PHP Warning: preg_match(): Unknown modifier 'T' in /usr/share/ocsinventory-reports/ocsreports/require/cve/Cve.php on line 267`

Judging by the error you sent, I think you configured some matching regex : http://wiki.ocsinventory-ng.org/04.Management-console-and-its-advanced-features/CVE-Search-match-regex/

One of them seem wrong and thus is generating a warning.

Please note that software name inside OCS might differ with CVE software definition and thus might lead to CVE being not inventoried (see the link I send above for more information)

Regards,
Gilles.

**Comment by mattoussaint** [comment]
Hi @gillesdubois ,

you are right, each error in line 267 of the cve.php file corresponds to a specific regex that I created in order to identify a vulnerability (for example the 2.0.5 obsolete version of VLC).

> It could be interesting that instead of this error a message returns when running in verbose mode...

Unfortunately, it does not go back better with or without Regex, I still have "**0 CVE has been added to database**"

Regards, Mat.

**Comment by jorgeag68** [comment]
Same problem here. After upgrading from OCSNG 2.6 to 2.8 . Being the main goal to get the new CVE functionality..
I always get ""0 CVE has been added to database"

**Comment by gillesdubois** [comment]
Hi,

We published the 2.8.1 server containing fix on regex management on the CVE scan.
Your problem will most likely be fixed by upgrading.

Regards,
Gilles.

**Comment by mostafarezvani** [comment]
Hi,

I installed the 2.8.1 Docker version. I used  both repository "https://cve.circl.lu" and "CVE Search" but I always get "0 CVE has been added to database"

Regards,
Mostafa Rezvani

**Comment by fourstepper** [comment]
me too. this doesn't seem to fixed in 2.8.x

**Comment by jsalgado78** [comment]
The service has been disabled by"cve.circl.lu":
https://ask.ocsinventory-ng.org/12457/cve-database-0-cve-has-been-added-to-databas

**Comment by DaniKawaii** [comment]
Hello, I have OCS in 2.9 Docker version and CVE Search in Docker too, I've configured CVE Reporting in the GUI, but I don't know how to run the crontab file that's inside the container, when I reach http://www.myocs.com/ocsreports/crontab/cron_cve.php I only get back this line: #!/usr/bin/php (not the complete script), do you know how can I execute it?

Thank you!
