### ISSUE TITLE
[BUG] Unknown column 's.TAG' in 'where clause

### ISSUE THREAD

**Issue by Bevito** [OCSInventory-NG/OCSInventory-ocsreports#1026]
**OCS Inventory version**
Version : 2.8.0

**Describe the bug**
Après avoir mis à jour OCSInventory de la version 2.7 à la version 2.8, lorsque je me connecte sur l'interface web en 'admin', j'obtiens l'erreur suviante : 

Unknown column 's.TAG' in 'where clause

Le ou les scripts s'arrêtent avec cette erreur

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Log file (optional)**
Apache error log : 

[Wed Sep 16 08:56:57.171741 2020] [proxy_fcgi:error] [pid 8295:tid 140612457150208] [client 109.190.253.16:49788] AH01071: Got error 'PHP message: PHP Warning:  mysqli_real_escape_string(): Couldn't fetch mysqli in /usr/share/ocsinventory-reports/ocsreports/require/function_commun.php on line 67PHP message: PHP Warning:  mysqli_query(): Couldn't fetch mysqli in /usr/share/ocsinventory-reports/ocsreports/require/function_commun.php on line 104PHP message: PHP Warning:  mysqli_fetch_object() expects parameter 1 to be mysqli_result, bool given in /usr/share/ocsinventory-reports/ocsreports/require/function_commun.php on line 38'
[Wed Sep 16 08:57:44.397306 2020] [proxy_fcgi:error] [pid 8295:tid 140612155012864] [client 109.190.253.16:49800] AH01071: Got error 'PHP message: PHP Warning:  mysqli_real_escape_string(): Couldn't fetch mysqli in /usr/share/ocsinventory-reports/ocsreports/require/function_commun.php on line 67PHP message: PHP Warning:  mysqli_query(): Couldn't fetch mysqli in /usr/share/ocsinventory-reports/ocsreports/require/function_commun.php on line 104PHP message: PHP Warning:  mysqli_fetch_object() expects parameter 1 to be mysqli_result, bool given in /usr/share/ocsinventory-reports/ocsreports/require/function_commun.php on line 38', referer: https://dlpkg.iut-orsay.fr/ocsreports/

**Comment by charleneauger** [comment]
Bonjour @Bevito,

Pouvez-vous exécuter la commande requête suivante sur votre Base de données : 

`DESCRIBE subnet;`
`DESCRIBE netmap;`

Une colonne TAG devrait être présente.

Dans le cas contraire, exécuter en BDD :

UNLOCK TABLES;
ALTER TABLE `netmap` ADD COLUMN `TAG` VARCHAR(255) DEFAULT NULL;
ALTER TABLE `subnet` ADD COLUMN `TAG` VARCHAR(255) DEFAULT NULL;
ALTER TABLE `subnet` DROP PRIMARY KEY;

Cordialement,
Charlène

**Comment by Bevito** [comment]
Bonjour Charlène, 

Merci beaucoup pour les commandes SQL.
Les tables 'subnet' et 'netmap' ne contenaient pas le champ 'TAG'.
Le problème est résolu.

Merci.

Bonne journée.
