### ISSUE TITLE
[BUG] Search with various criteria - Dynamic Groups

### ISSUE THREAD

**Issue by rayzilt** [OCSInventory-NG/OCSInventory-ocsreports#1027]
**OCS Inventory version**
Version : 2.8

**Describe the bug**
Search with various criteria shows incorrect data.

Searching for specific software installed gives the correct result. Saving those results into a dynamic group and search again with the filter "Group: Name -> DON'T BELONG TO [groupname]" gives a incorrect result.

Currently we have 47 Windows machines present in OCS. The first search if for example "Microsoft Edge" is installed, gives 4 machines back, which is correct. Saving it to a dynamic group and search again for computers not present in this group gives a result of 20 machines. That's a total of 24 machines, where are the other 23?

Total Machines:
![image](https://user-images.githubusercontent.com/3105311/93453125-8fa88880-f8d9-11ea-854c-f76b05cc151e.png)

First search:
![image](https://user-images.githubusercontent.com/3105311/93453624-2ecd8000-f8da-11ea-9392-302d7f021e5e.png)

Create Dynamic Group:
![image](https://user-images.githubusercontent.com/3105311/93453673-4278e680-f8da-11ea-880d-2f0387271202.png)

Second search, missing 23 machines
![image](https://user-images.githubusercontent.com/3105311/93453946-95eb3480-f8da-11ea-9fc5-d3579c97e147.png)

**To Reproduce**
Please see section "Describe the bug". If still needed, please let me know.

**Expected behavior**
The results in the second search should contain all machines not present in the dynamic group created by the first search

Server information:
![image](https://user-images.githubusercontent.com/3105311/93455048-18282880-f8dc-11ea-84f4-d04980efa5d4.png)

**Comment by charleneauger** [comment]
Hi @rayzilt ,

This issue has been fixed by the PR #1047 

Best regards,
Charlene Auger
