### ISSUE TITLE
[FEATURE] Removing GROUP BY CONCAT from queries

### ISSUE THREAD

**Issue by Benoitsob** [OCSInventory-NG/OCSInventory-ocsreports#1029]
**Is your feature request related to a problem? Please describe.**
Software search is slow.
I'm using : Server version: 10.3.22-MariaDB-1ubuntu1 Ubuntu 20.04

**Describe the solution you'd like**
When searching, the sql query use GROUP BY with CONCAT(s.NAME_ID,'_', s.VERSION_ID). This operation takes extra time. 
Would it be feasible to use GROUP BY s.NAME_ID, s.VERSION_ID instead ?

**Describe alternatives you've considered**
None considered.

**Additional context**
For example when searching for "cambri" with the query provided by the debug, when running directly on mysql CLI : 

`SELECT SQL_CALC_FOUND_ROWS *, count(CONCAT(s.NAME_ID,"_", s.VERSION_ID)) as nb, CONCAT(n.NAME,";", v.VERSION) id, sc.CATEGORY_NAME, v.VERSION, n.NAME, p.PUBLISHER FROM software s LEFT JOIN software_name n ON s.NAME_ID = n.ID LEFT JOIN software_publisher p ON s.PUBLISHER_ID = p.ID LEFT JOIN software_version v ON s.VERSION_ID = v.ID LEFT JOIN software_categories sc ON n.CATEGORY = sc.ID GROUP BY CONCAT(s.NAME_ID,'_', s.VERSION_ID) HAVING (( n.NAME LIKE '%%cambri%%' ) OR ( v.VERSION LIKE '%%cambri%%' ) ) order by n.NAME asc limit 0 , 10;`
For 7 rows takes 8~9 sec

With : 
`SELECT SQL_CALC_FOUND_ROWS *, count(CONCAT(s.NAME_ID,"_", s.VERSION_ID)) as nb, CONCAT(n.NAME,";", v.VERSION) id, sc.CATEGORY_NAME, v.VERSION, n.NAME, p.PUBLISHER FROM software s LEFT JOIN software_name n ON s.NAME_ID = n.ID LEFT JOIN software_publisher p ON s.PUBLISHER_ID = p.ID LEFT JOIN software_version v ON s.VERSION_ID = v.ID LEFT JOIN software_categories sc ON n.CATEGORY = sc.ID GROUP BY s.NAME_ID, s.VERSION_ID HAVING (( n.NAME LIKE '%%cambri%%' ) OR ( v.VERSION LIKE '%%cambri%%' ) ) order by n.NAME asc limit 0 , 10;`
It takes 4~5 sec

Thanks,

**Comment by Breakedin** [comment]
Great 👍
