### ISSUE TITLE
[HELP]How to make the deployment work?

### ISSUE THREAD

**Issue by ping5422034** [OCSInventory-NG/OCSInventory-ocsreports#1031]
I put the cacer.pem under the folder OCS Inventory Agent，then I deployed a file  ,but it's never sucess. 
Is there something wrong?
array_key_exists() expects parameter 2 to be array, null given in /var/www/html/ocsreports/require/search/Search.php on line 1043, referer: https://***/ocsreports/index.php?first

array_key_exists() expects parameter 2 to be array, null given in /var/www/html/ocsreports/require/function_ipdiscover.php on line 262, referer: https://****/ocsreports/?function=show_ipdiscover

**Comment by charleneauger** [comment]
Hi @ping5422034 ,

Can you give your download.log and Ocsinventory.log of your Agent ?

Regards,
Charlene Auger

**Comment by ping5422034** [comment]
Hi @charleneauger ，thank u so much!
Tue Sep 22 08:25:39 2020;8976;322;FMHW6LRNB7CQ9F2-2020-08-11-12-39-31;172.16.3.10;OCS-NG_WINDOWS_AGENT_v2.7.0.1;notify;IP
Tue Sep 22 08:25:39 2020;8976;323;FMHW6LRNB7CQ9F2-2020-08-11-12-39-31;172.16.3.10;OCS-NG_WINDOWS_AGENT_v2.7.0.1;notify;98:EE:CB:57:F7:FF<172.16.3.10>
Tue Sep 22 08:50:12 2020;8965;114;zypdeMacBook-Pro-2020-09-21-11-10-49;172.16.254.254;OCS-NG_unified_unix_agent_v2.6.1;inventory;no_session
Tue Sep 22 08:54:28 2020;11983;322;LENOVO-PC-2020-08-11-13-37-05;172.16.3.4;OCS-NG_WINDOWS_AGENT_v2.7.0.1;notify;IP
Tue Sep 22 08:54:28 2020;11983;324;LENOVO-PC-2020-08-11-13-37-05;172.16.3.4;OCS-NG_WINDOWS_AGENT_v2.7.0.1;notify;98:EE:CB:57:F7:A4
Tue Sep 22 08:54:28 2020;11983;324;LENOVO-PC-2020-08-11-13-37-05;172.16.3.4;OCS-NG_WINDOWS_AGENT_v2.7.0.1;notify;58:00:E3:B2:0B:57
Tue Sep 22 09:50:53 2020;11983;322;FMHW6LRNB7CQ9F2-2020-08-11-12-39-31;172.16.3.10;OCS-NG_WINDOWS_AGENT_v2.7.0.1;notify;IP
Tue Sep 22 09:50:53 2020;11983;323;FMHW6LRNB7CQ9F2-2020-08-11-12-39-31;172.16.3.10;OCS-NG_WINDOWS_AGENT_v2.7.0.1;notify;98:EE:CB:57:F7:FF<172.16.3.10>
Tue Sep 22 10:00:47 2020;8965;114;PC-20161031WTFU-2020-08-11-14-54-08;172.16.3.183;OCS-NG_WINDOWS_AGENT_v2.7.0.1;inventory;no_session
Tue Sep 22 12:22:08 2020;8976;322;PC-20161031WTFU-2020-08-11-14-54-08;172.16.3.183;OCS-NG_WINDOWS_AGENT_v2.7.0.1;notify;IP
Tue Sep 22 12:22:08 2020;8976;324;PC-20161031WTFU-2020-08-11-14-54-08;172.16.3.183;OCS-NG_WINDOWS_AGENT_v2.7.0.1;notify;00:25:AB:8E:72:AF
Tue Sep 22 12:22:08 2020;8976;324;PC-20161031WTFU-2020-08-11-14-54-08;172.16.3.183;OCS-NG_WINDOWS_AGENT_v2.7.0.1;notify;00:50:56:C0:00:01
Tue Sep 22 12:22:08 2020;8976;324;PC-20161031WTFU-2020-08-11-14-54-08;172.16.3.183;OCS-NG_WINDOWS_AGENT_v2.7.0.1;notify;00:50:56:C0:00:02
Tue Sep 22 13:09:19 2020;8966;322;FMHW6LRNB7CQ9F2-2020-08-11-12-39-31;172.16.3.10;OCS-NG_WINDOWS_AGENT_v2.7.0.1;notify;IP
Tue Sep 22 13:09:19 2020;8966;323;FMHW6LRNB7CQ9F2-2020-08-11-12-39-31;172.16.3.10;OCS-NG_WINDOWS_AGENT_v2.7.0.1;notify;98:EE:CB:57:F7:FF<172.16.3.10>
Tue Sep 22 13:22:36 2020;872;322;YN-20180412QA-2020-09-14-08-54-02;172.16.3.75;OCS-NG_WINDOWS_AGENT_v2.7.0.1;notify;IP
Tue Sep 22 13:22:36 2020;872;324;YN-20180412QA-2020-09-14-08-54-02;172.16.3.75;OCS-NG_WINDOWS_AGENT_v2.7.0.1;notify;98:EE:CB:65:EA:56
Tue Sep 22 13:22:36 2020;872;324;YN-20180412QA-2020-09-14-08-54-02;172.16.3.75;OCS-NG_WINDOWS_AGENT_v2.7.0.1;notify;58:00:E3:B2:9F:AF
Tue Sep 22 13:23:58 2020;11981;322;YN-20180412QA-2020-09-14-08-54-02;172.16.3.75;OCS-NG_WINDOWS_AGENT_v2.7.0.1;notify;IP
Tue Sep 22 13:23:58 2020;11981;324;YN-20180412QA-2020-09-14-08-54-02;172.16.3.75;OCS-NG_WINDOWS_AGENT_v2.7.0.1;notify;98:EE:CB:65:EA:56
Tue Sep 22 13:23:58 2020;11981;324;YN-20180412QA-2020-09-14-08-54-02;172.16.3.75;OCS-NG_WINDOWS_AGENT_v2.7.0.1;notify;58:00:E3:B2:9F:AF
Tue Sep 22 13:28:58 2020;871;322;YLMF-1907170844-2020-08-19-09-09-31;172.16.3.8;OCS-NG_WINDOWS_AGENT_v2.7.0.1;notify;IP
Tue Sep 22 13:28:58 2020;871;323;YLMF-1907170844-2020-08-19-09-09-31;172.16.3.8;OCS-NG_WINDOWS_AGENT_v2.7.0.1;notify;90:CD:B6:57:DE:87<192.168.250.55>
Tue Sep 22 13:29:16 2020;8967;114;YLMF-1907170844-2020-08-19-09-09-31;172.16.3.8;OCS-NG_WINDOWS_AGENT_v2.7.0.1;inventory;no_session
Tue Sep 22 15:15:38 2020;8976;322;FMHW6LRNB7CQ9F2-2020-08-11-12-39-31;172.16.3.10;OCS-NG_WINDOWS_AGENT_v2.7.0.1;notify;IP
Tue Sep 22 15:15:38 2020;8976;323;FMHW6LRNB7CQ9F2-2020-08-11-12-39-31;172.16.3.10;OCS-NG_WINDOWS_AGENT_v2.7.0.1;notify;98:EE:CB:57:F7:FF<172.16.3.10>
Tue Sep 22 15:37:17 2020;8966;114;WIN10-ZYP1-2020-09-21-16-00-01;172.16.254.254;OCS-NG_WINDOWS_AGENT_v2.7.0.1;inventory;no_session
Tue Sep 22 15:40:38 2020;869;114;WIN10-ZYP1-2020-09-21-16-00-01;172.16.254.254;OCS-NG_WINDOWS_AGENT_v2.7.0.1;inventory;no_session
Tue Sep 22 15:40:56 2020;8965;114;WIN10-ZYP1-2020-09-21-16-00-01;172.16.254.254;OCS-NG_WINDOWS_AGENT_v2.7.0.1;inventory;no_session
Tue Sep 22 15:41:15 2020;869;114;WIN10-ZYP1-2020-09-21-16-00-01;172.16.254.254;OCS-NG_WINDOWS_AGENT_v2.7.0.1;inventory;no_session
Tue Sep 22 15:42:51 2020;11981;114;WIN10-ZYP1-2020-09-21-16-00-01;172.16.254.254;OCS-NG_WINDOWS_AGENT_v2.7.0.1;inventory;no_session
Tue Sep 22 15:44:58 2020;869;322;WIN10-ZYP1-2020-09-21-16-00-01;172.16.254.254;OCS-NG_WINDOWS_AGENT_v2.7.0.1;notify;IP
Tue Sep 22 15:44:58 2020;869;323;WIN10-ZYP1-2020-09-21-16-00-01;172.16.254.254;OCS-NG_WINDOWS_AGENT_v2.7.0.1;notify;98:FA:9B:71:AD:0E<172.16.3.186>
Tue Sep 22 15:46:06 2020;8965;114;WIN10-ZYP1-2020-09-21-16-00-01;172.16.254.254;OCS-NG_WINDOWS_AGENT_v2.7.0.1;inventory;no_session
Tue Sep 22 15:54:16 2020;11981;114;WIN10-ZYP1-2020-09-21-16-00-01;172.16.254.254;OCS-NG_WINDOWS_AGENT_v2.7.0.1;inventory;no_session
Tue Sep 22 16:03:48 2020;11981;322;FMHW6LRNB7CQ9F2-2020-08-11-12-39-31;172.16.3.10;OCS-NG_WINDOWS_AGENT_v2.7.0.1;notify;IP
Tue Sep 22 16:03:48 2020;11981;323;FMHW6LRNB7CQ9F2-2020-08-11-12-39-31;172.16.3.10;OCS-NG_WINDOWS_AGENT_v2.7.0.1;notify;98:EE:CB:57:F7:FF<172.16.3.10>

**Comment by charleneauger** [comment]
Hi @ping5422034 ,

No. The Download.log and the Ocsinventory.log are on ProgramData/OCS Inventory NG/Agent on the computer with the Windows Agent installed. :-) 

Regards,
Charlene

**Comment by ping5422034** [comment]
Hi @charleneauger ，

I got the one! 

Starting OCS Inventory Agent on Tuesday, September 22, 2020 22:59:01.
AGENT => Running OCS Inventory Agent Version 2.7.0.1
AGENT => Using OCS Inventory FrameWork Version 2.7.0.1
AGENT => Loading plug-in(s)
	DLL PLUGIN => Searching for Plug-in DLL(s) in folder <C:\Program Files\OCS Inventory Agent\plugins>
	DLL PLUGIN => 0 DLL Plug-in(s) successfully loaded on 0 DLL(s) found
AGENT => Using network connection with Communication Server
	COM PROVIDER => Loading Communication Provider <C:\Program Files\OCS Inventory Agent\ComHTTP.dll>
AGENT => Using Communication Provider <OCS Inventory cURL Communication Provider> Version <2.7.0.1>
AGENT => Sending Prolog
	DID_CHECK => Read DeviceID <WIN10-ZYP1-2020-09-21-16-00-01> and MACs <98:FA:9B:71:AD:0E00:FF:6C:42:**:16> in file <ocsinventory.dat>
	COM SERVER => Initializing cURL library for sendRequest
	COM SERVER => Using cURL with server authentication
	COM SERVER => Disabling cURL proxy support
	COM SERVER => Enabling cURL SSL server validation support using CA Bundle <C:\ProgramData\OCS Inventory NG\Agent\cacert.pem>
	COM SERVER => Sending HTTP Post request to URL <https://**.com/ocsinventory>
	WARNING *** COM SERVER => Failed to send HTTP Post request <Problem with the SSL CA cert (path? access rights?)>
	COM SERVER => Cleaning cURL library
ERROR *** AGENT => Failed to send Prolog <Problem with the SSL CA cert (path? access rights?)>
AGENT => Unloading communication provider
AGENT => Unloading plug-in(s)
AGENT => Execution duration: 00:00:01.

**Comment by ping5422034** [comment]
Hi again @charleneauger ,
Dose this cacert.pem is the Domain ssl?

**Comment by charleneauger** [comment]
@ping5422034 ,

As you can see, the SSL certificate is the problem. Maybe your certificate isn't valid.
Verify : 
* Your certificate is the same as your server certificate
* Certificate is on ProgramData/OCS Inventory NG/Agent
* SSL=1 and CA={name of your certificate} on ocsinventory.ini (ProgramData/OCS Inventory NG/Agent)

Regards,
Charlene

**Comment by ping5422034** [comment]
@charleneauger ,

Ok, I will try to fix it following your verification.
Thanks again.
Have a good day!

**Comment by ping5422034** [comment]
Hi @charleneauger ,
 On the server, will I can put the  Certificate on /conf? 
And when I install the Agent , the server URL must be https:// **/ocsinventory or http://172.**/ocsinventory

**Comment by charleneauger** [comment]
Hi,

I close this issue because it's solved.

Regards,
Charlene
