### ISSUE TITLE
[BUG] impossible to display success statistics for deployments.

### ISSUE THREAD

**Issue by o71** [OCSInventory-NG/OCSInventory-ocsreports#1034]
**OCS Inventory version**

Version : 2.8 (not having used this function in previous versions, the bug may not be new)

**Describe the bug**

It is impossible to display success statistics for deployments.
I have a blank screen when the package has been successfully deployed to at least two machines. And the following error message when it was deployed to only one machine :
	"THE DATA DOESN'T EXIST. THE STATES HOURS CAN NOT BE FOUND IN DATABASE FOR THIS PACKAGE"

**To Reproduce**

1. First, you must have successfully deployed a package on one or two machines.
2. Go to Deployment>Activate
3. click on the statistic icon of the package (url format: ...index.php?function=tele_stat&head=1&stat=.....)
4. In the new page, click on the statistic icon of the success package (url format : ...index.php?function=stat_speed&head=1&ta=SUCCESS&stat=...)
5. See error

Thanks a lot

**Comment by fpotier** [comment]
Hi, I have the same kind of issue but no error message on 2.9.
When I watch a package deployment statistics, I can see the number of success etc.
However if I click on "SUCESS" -> "Statistics", a blank page appears.

No error is logged server side but I get some JS errors : 
```
Uncaught TypeError: document.getElementById(...) is null
    onload https://server/ocsreports/index.php?function=stat_speed&head=1&ta=SUCCESS&stat=1624979360:110
```
```
Uncaught TypeError: document.getElementById(...) is null
    onload https://server/ocsreports/index.php?function=stat_speed&head=1&ta=SUCCESS&stat=1624979360:110
```

And here is the faulty function :
```
        window.onload = function() {
            var ctx = document.getElementById("teledeploy_speed").getContext("2d");
            window.myLine = new Chart(ctx, config);
        };
