### ISSUE TITLE
[BUG] REPORT BLANK

### ISSUE THREAD

**Issue by wmeneses** [OCSInventory-NG/OCSInventory-ocsreports#1041]
**OCS Inventory version**
Version : 2.8
PHP 7.4
MYSQL 5.7 GCP google service

**Describe the bug**
Computers are reported as blank

**To Reproduce**

**Expected behavior**

**Screenshots**
![Captura de pantalla 2020-10-02 124014](https://user-images.githubusercontent.com/5956910/94953251-d509b000-04ac-11eb-9473-71c317f4aeab.png)

**Log file (optional)**
Apache / PHP / System log if needed
No errors in activity

**Comment by wmeneses** [comment]
definitely does not work with google mysql 5.7, if the database is local with mariadb, it works, :(

**Comment by gillesdubois** [comment]
Hi @wmeneses 

I'm not really an expert of Google Services.
Maybe it is only a configuration subject ?

Sorry but to me its more related to google services than to OCS.

I'll be closing this issue.

Regards,
Gilles.
