### ISSUE TITLE
Unknown column 'HARDWARE_ID' in 'field list'

### ISSUE THREAD

**Issue by edsonsf** [OCSInventory-NG/OCSInventory-ocsreports#1042]
When I do a search to show computers that do not have a certain software, I do not receive any response, regardless of the search software. Via debug I see that the error is:

Unknown column 'HARDWARE_ID' in 'field list'

Unknown column 'software_name.HARDWARE_ID' in 'where clause'

You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ')' at line 3

When I do a search to show computers that do not have a certain software, I do not receive any response, regardless of the search software. Via debug I see that the error is:

Select:

SELECT DISTINCT hardware.ID FROM hardware INNER JOIN software on hardware.id = software.hardware_id LEFT JOIN software_name on software_name.id = software.name_id LEFT JOIN software_publisher on software_publisher.id = software.publisher_id LEFT JOIN software_version on software_version.id = software.version_id WHERE software_name.HARDWARE_ID NOT IN (0) GROUP BY hardware.id

Servidor CentOS 8.1.1911

MariaDB 10.3
OCS Server 2.7-nightly-2020-09-07 and after upgrade 2.8 too.

PHP 7.3.22

How can I solve this problem?

**Comment by gillesdubois** [comment]
Hi,

A lot of fix has been made since you created this issue.
2.8 version had some issues with the software database model.

What I can recommend you is to recreated all the software_* tables according to the ocsbase.sql file present in the repository.

Regards,
Gilles.
