### ISSUE TITLE
[BUG] Inventoried host not visible on WebGUI

### ISSUE THREAD

**Issue by mariaczi** [OCSInventory-NG/OCSInventory-ocsreports#1048]
**OCS Inventory version**
Version : 2.6

**Describe the bug**
Host send all required data correctly to the server and is visible in database but couldn't be find on web interface.

**To Reproduce**
I don't known how to reproduce this problem. After my investigation I found that agent (v2.6.0) not inventoried network interfaces. I don't known why. Interfaces are not visible in agent log file in XML structure.

After enabling DEBUG mode on WebGUI I found that if we remove 'AND n.STATUS = 'up' ` from the "All computers" query we will see this machine.
```
SELECT SQL_CALC_FOUND_ROWS h.DEVICEID, a.TAG, h.lastdate, h.name, h.ID, h.userid, h.osname, h.memory as capa, h.processors, h.workgroup, h.osversion, h.oscomments, h.processort, h.processorn, h.swap, h.lastcome, h.quality, h.fidelity, h.description, h.wincompany, h.winowner, h.useragent, e.smanufacturer, e.bmanufacturer, e.ssn, e.smodel, e.bversion, GROUP_CONCAT(DISTINCT CASE WHEN n.ipaddress != 0x20 THEN n.ipaddress ELSE NULL END SEPARATOR 0x2D) as ipaddress, h.userdomain, h.ARCH, e.bdate, v.name as vname, ac.category_name, n.macaddr, n.ipmask, n.ipgateway, n.ipsubnet from hardware h LEFT JOIN accountinfo a ON a.hardware_id=h.id LEFT JOIN networks n ON n.hardware_id=h.id LEFT JOIN bios e ON e.hardware_id=h.id LEFT JOIN memories m ON m.hardware_id=h.id LEFT JOIN assets_categories ac ON ac.ID = h.CATEGORY_ID LEFT JOIN videos v ON v.hardware_id=h.id where deviceid<>'_SYSTEMGROUP_' AND deviceid<>'_DOWNLOADGROUP_' group by h.id order by h.ID desc limit 0 , 10;
```

I tested this SQL query directly on ocs database.

**Comment by mariaczi** [comment]
After reinstall required perl modules agent found network devices but i think it is not good way to not show servers with disabled network interface :/

**Comment by gillesdubois** [comment]
Hi @mariaczi 

In the first place I recommend you to update to the 2.8.
This problem has been adressed in 2.7 and most likely won't appear in 2.8.

Regards,
Gilles.
