### ISSUE TITLE
[BUG] cannot use single quotes in deployment command

### ISSUE THREAD

**Issue by StCyr** [OCSInventory-NG/OCSInventory-ocsreports#1057]
**OCS Inventory version**
Version : 2.8

**Describe the bug**
Cannot use single quotes in deployment command. See reproduction steps hereunder.

**To Reproduce**
1. Go to Deployment > Build
2. In field "Command", type `wmic product where "name like 'Java _ Update%%'" call uninstall /nointeractive`
3. Proceed with package creation
4. Log into your server via SSH and open the info file of the package created
5. Confirm that command has been translated to `"wmic product where &quot;name like`

**Comment by gillesdubois** [comment]
Hi,

We are currently reworking the deployment system for the 2.9
This problem is well knwon and will be adressed :)

Thanks for your feedback.

Regards,
Gilles.

**Comment by charleneauger** [comment]
Hi @StCyr ,

This bug has been fixed on 2.9 version with the new version of the deployment feature.

Best regards,
Charlene
