### ISSUE TITLE
[BUG] CVE List - links wrong

### ISSUE THREAD

**Issue by LMS235** [OCSInventory-NG/OCSInventory-ocsreports#1058]
**OCS Inventory version**
Version : 2.8

**Describe the bug**
The links in the CVE reports do not work. They keep pointing to the OCS itself instead of the displayed link

![image](https://user-images.githubusercontent.com/8693550/97669033-863b4000-1a83-11eb-9420-34bf884768d5.png)

**Expected behavior**
It should also point to the link that is displayed. And preferably be opened in a new TAB.

**Screenshots**
see above

**Comment by gillesdubois** [comment]
Hi @LMS235 

Indeed, a pull request is available to fix this :) 
An other team member will review it asap.

Thanks for your contribution.

Regards,
Gilles.
