### ISSUE TITLE
Search in Dictionary not working

### ISSUE THREAD

**Issue by Marx1st** [OCSInventory-NG/OCSInventory-ocsreports#106]
Hi,

in OCSInventory 2.2.x searching in the software dictionary is not working. This is not a local problem as is doesn't work in your demo either:

http://demo.ocsinventory-ng.org/?function=admin_dico

Just choose "New" from the menu on the left and now display all entries with "Microsoft" in it's title. It's just not possible. Regardless if you use the search field top right or the one at the bottom. There just is no result...

Regards,
Tobias

**Comment by MyTheValentinus** [comment]
Hello @Marx1st,
Thank for your report.
