### ISSUE TITLE
[BUG] It's possible to delete yourself and make searches with the deleted user

### ISSUE THREAD

**Issue by netoeuler** [OCSInventory-NG/OCSInventory-ocsreports#1061]
**OCS Inventory version**
Version : 2.8

**Describe the bug**
It's possible to delete yourself and make searches with the deleted user

**To Reproduce**
1. Create a new user
2. Log-in with the user
3. Go to 'All computers' (or any other screen with a search field)
4. Type something to search, open Developer Tools and in Network tab right-click the request and select Copy > Copy as cURL
5. Paste the command in some terminal and execute the command
6. In OCS-Reports, go to Configuration > Users
7. Delete the user you that you are logged in
8. Execute again the command of step 5
9. You will able to still make searches with a deleted user

**Expected behavior**
It would not be possible to delete yourself and still be logged and can utilize the credentials to make searches after the user is deleted.

**Screenshots**

**Log file (optional)**
Apache / PHP / System log if needed

**Comment by fbomj** [comment]
Logoff before running the command. Is the problem still present ?

**Comment by netoeuler** [comment]
> Logoff before running the command. Is the problem still present ?

I did this steps in a browser in private mode, so I closed the browser and lost the session but the command of step 5 still works.
