### ISSUE TITLE
Monitor info report

### ISSUE THREAD

**Issue by rohittuteja053** [OCSInventory-NG/OCSInventory-ocsreports#1067]
Hi,

I need to be able to get a list of all PCs with usernames.

Monitor's and monitor model and serial numbers are not available in the view list, is there any way to do this?

Centos 7.6-64bit
![ocs](https://user-images.githubusercontent.com/65939113/98444566-64ebeb00-2138-11eb-9847-df704ca59bc2.jpg)

OCS-agent = 2.8
OCSserver = 2.8

**Comment by charleneauger** [comment]
Hi @rohittuteja053 

I'm sorry but I don't understand your issue.
Can you explain ?

Regards,
Charlene Auger

**Comment by charleneauger** [comment]
Hi,

Since I didn't receive any anwser from you, I'll now be closing this issue.

Regards,
Charlene Auger
