### ISSUE TITLE
Customizing the Dashboard

### ISSUE THREAD

**Issue by PSBalu** [OCSInventory-NG/OCSInventory-ocsreports#1068]
How can you customize the dashboard?

**Comment by rohittuteja053** [comment]
no

**Comment by steph78630** [comment]
> How can you customize the dashboard?

Under GUI > Configuration > General configuration > Interface > Custom theme (change for "MYTHEME")

Note : Before that you must have created a new theme in / ocsreports / themes / mytheme

**Comment by charleneauger** [comment]
Hi @PSBalu ,

It's not possible to customize the dashboard. Howerver you can create a personal theme.
Here the documentation : [How to create a theme](http://wiki.ocsinventory-ng.org/12.Developers/HOWTO-create-theme/)

Best regards,
Charlene Auger

**Comment by PSBalu** [comment]
Hi, 
Thanks for your reply.
I am not asking for changing the Theme. Want to customize the dashboard elements. Like the field/data currently available for the Admin logon.
