### ISSUE TITLE
[BUG] CONEX_LDAP_CHECK_FIELD2_ROLE users cant login after 2.8 upgrade

### ISSUE THREAD

**Issue by nwildner** [OCSInventory-NG/OCSInventory-ocsreports#1070]
**OCS Inventory version**
Version : 2.8

**Describe the bug**
After upgrading from 2.7 to 2.8, users fitered with **CONEX_LDAP_CHECK_FIELD2_VALUE** and **CONEX_LDAP_CHECK_FIELD2_ROLE**(default OCS RO) cant login. Those are already existing logins(some of them are as old as the first 2.0 install), and creating new ones with those FIELD2 values and setting the respective LDAP group will generate the **''You are not allowed to connect''** message during login

Users that are members of the Administrators profile (CONEX_LDAP_CHECK_FIELD1_VALUE and CONEX_LDAP_CHECK_FIELD1_ROLE) are still able to login.

No changes were made on our AD/LDAP server. Also, CONEX_LDAP_CHECK_DEFAULT_ROLE is empty(always was).

**To Reproduce**
1. Upgrade to 2.8
2. Try to login with any account that is CONEX_LDAP_CHECK_FIELD2_ROLE and RO profile configured to that secondary role.

**Expected behavior**
Users of the secondary ldap field should be allowed to login

**Screenshots**
![image](https://user-images.githubusercontent.com/11742211/99064964-73e1fb80-2585-11eb-9281-0858e04e9e20.png)
pt_BR "You are not allowed to connect" message.

**Additional info**
This is an old install and it's being our inventory workhorse since v2.0 and it's upgraded constantly. Maybe i'm missing something like a new role permission that needs to be set for login.

After the 2.8 install i took care to handle all the ldap configuration to `var.php` with `define('AUTH_TYPE', 3);`

If you need any additional log please let me know.

**Comment by gillesdubois** [comment]
Hi @nwildner 

I fixed a lot of issues concerning LDAP synchronization could you try with the 2.9 ?

Regards,
Gilles.

**Comment by nwildner** [comment]
> Hi @nwildner
> 
> I fixed a lot of issues concerning LDAP synchronization could you try with the 2.9 ?
> 
> Regards,
> Gilles.

Hi Gilles. Sorry for the late answer.

Starting this year I've changed jobs so, i will no longer be able to access that environment to test this out :(

All The Best,
nwildner

**Comment by charleneauger** [comment]
Hi @nwildner ,

We wish you all the best for your new job. However, without your tests we can't do anything more.

Best regards,
Charlene
