### ISSUE TITLE
[BUG] chrome loads constantly and doesn't work

### ISSUE THREAD

**Issue by Gum97** [OCSInventory-NG/OCSInventory-ocsreports#1075]
**OCS Inventory version**
Version : 2.8
Hi All 
I'm install OCS in centos, but i type address with ip in chrome, it is normal, but i type with domain in chrome ocs reloads continuously and cannot be operated.This doesn't happen on firefox
![image](https://user-images.githubusercontent.com/21122797/99610535-9a4fdd00-2a44-11eb-9938-237ce8124cb5.png)
![image](https://user-images.githubusercontent.com/21122797/99610551-a20f8180-2a44-11eb-9162-2bb03d02cf87.png)

**Comment by Gum97** [comment]
![image](https://user-images.githubusercontent.com/21122797/99618052-3aacfe00-2a53-11eb-805a-9852bba0b639.png)

**Comment by gillesdubois** [comment]
Hi @Gum97 

I'm sorry but I never encountered this issue with OCS.
Could you try to re-install a fresh copy of the 2.8.1 server on an other server and check if the problem still happen ?

Regards,
Gilles.

**Comment by jsalgado78** [comment]
Hi,

I've same issue running OCS Inventory 2.7.0 with Chrome and Chromium: 
Request URL: http://ocsdomain/ocsreports/ajax.php?&no_header=true&no_footer=true
Status Code: 401 Unauthorized

Regards,
Jose Antonio

**Comment by gillesdubois** [comment]
Hi,

This issue is a bit old.
THe 2.9 had some improvement with the default apache config.

If you still have this issue please reopen.

Regards,
Gilles.
