### ISSUE TITLE
ocsreports newsfeed contains non-https embedded images

### ISSUE THREAD

**Issue by hertell** [OCSInventory-NG/OCSInventory-ocsreports#1076]
When running ocsreports on ssl, firefox warns that the site is not secure. This is because the newsfeed contains embedded images served from a http-server (http://cdn.ocsinventory-ng.org/common/logo-ocs.jpg).
This should be an easy task to update the image to be served instead from https://cdn.ocsinventory-ng.org/common/logo-ocs.jpg

<img width="125" alt="Screen Shot 2020-11-20 at 09 31 59" src="https://user-images.githubusercontent.com/92610/99772372-4fe96180-2b13-11eb-9f6f-afbb59c7c2e5.png">

<img width="399" alt="Screen Shot 2020-11-20 at 09 07 02" src="https://user-images.githubusercontent.com/92610/99772229-0c8ef300-2b13-11eb-8b37-945017e4d305.png">

**Comment by gillesdubois** [comment]
Hi,

This has been fixed our CDN is now reached in HTTPS instead of HTTP.
If you still encounter this problem, please try to reset you browser cache / log-out & login again in the web console.

Regards,
Gilles.
