### ISSUE TITLE
problem with ipdiscovery

### ISSUE THREAD

**Issue by AntonS915** [OCSInventory-NG/OCSInventory-ocsreports#1077]
**OCS Inventory version**
Version : 2.8

**Describe the bug**
I don't see any non-inventory computers in the subnet. the problem is only observed with the unix agent. windows agent in a different subnet works fine and I can see the results of ipdiscovery

**Log file (optional)**
No errors in server, agent logs.

But in server activity.log:

Thu Nov 19 16:01:02 2020;48937;100;inventory-2020-11-18-16-06-39;192.168.1.108;OCS-NG_unified_unix_agent_v2.8.0;prolog;accepted

Thu Nov 19 16:01:02 2020;48937;311;inventory-2020-11-18-16-06-39;192.168.1.108;OCS-NG_unified_unix_agent_v2.8.0;session;started

Thu Nov 19 16:01:11 2020;49087;319;inventory-2020-11-18-16-06-39;192.168.1.108;OCS-NG_unified_unix_agent_v2.8.0;session;found

Thu Nov 19 16:01:11 2020;49087;104;inventory-2020-11-18-16-06-39;192.168.1.108;OCS-NG_unified_unix_agent_v2.8.0;inventory;incoming

Thu Nov 19 16:01:12 2020;49087;113;inventory-2020-11-18-16-06-39;192.168.1.108;OCS-NG_unified_unix_agent_v2.8.0;inventory;u:drives

Thu Nov 19 16:01:12 2020;49087;113;inventory-2020-11-18-16-06-39;192.168.1.108;OCS-NG_unified_unix_agent_v2.8.0;inventory;u:repository

Thu Nov 19 16:01:12 2020;49087;1001;inventory-2020-11-18-16-06-39;192.168.1.108;OCS-NG_unified_unix_agent_v2.8.0;ipdiscover;elected(192.168.1.0)

Thu Nov 19 16:01:13 2020;49087;320;inventory-2020-11-18-16-06-39;192.168.1.108;OCS-NG_unified_unix_agent_v2.8.0;session;end

Thu Nov 19 16:01:13 2020;49087;101;inventory-2020-11-18-16-06-39;192.168.1.108;OCS-NG_unified_unix_agent_v2.8.0;inventory;transmitted

Thu Nov 19 17:01:02 2020;857;1004;inventory-2020-11-18-16-06-39;192.168.1.108;OCS-NG_unified_unix_agent_v2.8.0;ipdiscover;incoming

Thu Nov 19 17:01:02 2020;857;100;inventory-2020-11-18-16-06-39;192.168.1.108;OCS-NG_unified_unix_agent_v2.8.0;prolog;accepted

Thu Nov 19 17:01:02 2020;857;311;inventory-2020-11-18-16-06-39;192.168.1.108;OCS-NG_unified_unix_agent_v2.8.0;session;started

Thu Nov 19 17:01:13 2020;858;319;inventory-2020-11-18-16-06-39;192.168.1.108;OCS-NG_unified_unix_agent_v2.8.0;session;found

Thu Nov 19 17:01:13 2020;858;104;inventory-2020-11-18-16-06-39;192.168.1.108;OCS-NG_unified_unix_agent_v2.8.0;inventory;incoming

Thu Nov 19 17:01:14 2020;858;113;inventory-2020-11-18-16-06-39;192.168.1.108;OCS-NG_unified_unix_agent_v2.8.0;inventory;u:drives

Thu Nov 19 17:01:14 2020;858;113;inventory-2020-11-18-16-06-39;192.168.1.108;OCS-NG_unified_unix_agent_v2.8.0;inventory;u:repository

Thu Nov 19 17:01:14 2020;858;1002;inventory-2020-11-18-16-06-39;192.168.1.108;OCS-NG_unified_unix_agent_v2.8.0;ipdiscover;removed

Thu Nov 19 17:01:15 2020;858;320;inventory-2020-11-18-16-06-39;192.168.1.108;OCS-NG_unified_unix_agent_v2.8.0;session;end

Thu Nov 19 17:01:15 2020;858;101;inventory-2020-11-18-16-06-39;192.168.1.108;OCS-NG_unified_unix_agent_v2.8.0;inventory;transmitted

-------------------------

Why removed?

Thu Nov 19 17:01:14 2020;858;1002;inventory-2020-11-18-16-06-39;192.168.1.108;OCS-NG_unified_unix_agent_v2.8.0;ipdiscover;removed

**Comment by Djily90** [comment]
Hello @AntonS915 

Could you update your server to the latest version 2.9 ? We improved many feature about the Ipdiscover. 

Regards, 
Djily.

**Comment by charleneauger** [comment]
Hi,

Since there is no anwser, I'll now close the issue.

Regards,
Charlene.
