### ISSUE TITLE
Passwords are displayed in plain text

### ISSUE THREAD

**Issue by cb58** [OCSInventory-NG/OCSInventory-ocsreports#108]
Hi,

The passwords are displayed in plain text in "My account" and in "Update user" (Config, Users).
A patch is attached to replace the html input text field with a html password field. 

Regards

**Comment by cb58** [comment]
[function_users.php.diff.txt](https://github.com/OCSInventory-NG/OCSInventory-ocsreports/files/397228/function_users.php.diff.txt)

**Comment by gillesdubois** [comment]
Fixed by this commit, https://github.com/OCSInventory-NG/OCSInventory-ocsreports/commit/a0f78c9533990b19a84850c60c971d4a5ac75a45 
I just inverted the commit number with your other issue.
