### ISSUE TITLE
Background image only login page

### ISSUE THREAD

**Issue by lexcorp** [OCSInventory-NG/OCSInventory-ocsreports#1081]
Hi, I'm trying to add a background image to the login page, but when adding the background-image property through css, the image is displayed on all pages.

Background image on login page.
![ocsinv](https://user-images.githubusercontent.com/5751288/100570262-fe20a400-3295-11eb-8211-71871df4e2a1.png)

But the image shows on all pages :/
![ocsinv2](https://user-images.githubusercontent.com/5751288/100570307-1d1f3600-3296-11eb-840a-84161493b37a.png)

**Comment by gillesdubois** [comment]
Hi @lexcorp 

Unfortunately the login page CSS is the same as the one used on every other page.
At the moment, apart from modifying the login page code you won't be able to separate it using only CSS.

Altrough it would be a nice addition to our theme system.
If you are lucky it could come with the next 2.9 version :) 

Regards,
Gilles.
