### ISSUE TITLE
[BUG] False duplicates computers in MAC address + Serial number

### ISSUE THREAD

**Issue by ChandlerBing82** [OCSInventory-NG/OCSInventory-ocsreports#1084]
**OCS Inventory version**
Version : 2.8

**Describe the bug**
Hello,

Since my upgrade to version 2.8 of OCSNG server I have some computers that are tagged as duplicates in my administrative console only in mac + serial duplicates.

If I check serial only or mac only, I have no duplicates computers.

When I check the duplicates computer in mac + serial, obviously they are no duplicate computers.

In version 2.7 I didn't have this problem. I alreay deleted all the computer in OCS NG and I dropped the database to start on a fresh one but I still have the problem.

My server is a linux one and the false duplicates computers are Windows 10 ones. I only have few linux computers.

Can you tell me if I did anything wrong please?

Thank you.

**Comment by ChandlerBing82** [comment]
Same problem with the 2.8.1 version.

**Comment by gillesdubois** [comment]
Hi @ChandlerBing82 

Te be honest with you we didn't focus on duplicates management during the release but more on SNMP and IPDiscover.

We are aware that our duplicate management is not really accurate at the moment, we do plan on reworking it with the 2.9 which will most likely come in Q1 2021.

Thanks for your report, we'll keep you updated on this subject.

Gilles.

**Comment by cirvent** [comment]
Hi all,

Same problem with the 2.9 version.

**Comment by gillesdubois** [comment]
Hi @cirvent 

Since we reworked the duplicate. I would like to get more informations if possible.
Could you share some example with us ?

Thanks.

Regards,
Gilles.

**Comment by cirvent** [comment]
Hi Gilles,

One picture will speak more than words.

<img width="640" alt="no_item" src="https://user-images.githubusercontent.com/16097158/123486958-5130be80-d60d-11eb-9a5a-100cb8f788d9.PNG">

<img width="640" alt="no_item" src="https://user-images.githubusercontent.com/16097158/123487125-a53ba300-d60d-11eb-9235-0774e7f452ce.PNG">

Thanks,
Regards,
Cirvent

**Comment by cirvent** [comment]
I have this error in the logs:

[Mon Jun 28 08:50:17.947116 2021] [:error] [pid 65779] [client 10.10.204.46:58950] PHP Fatal error:  Call to undefined function mysqli_fetch_all() in /usr/share/ocsinventory-reports/ocsreports/plugins/main_sections/ms_doubles/ms_doubles.php on line 317, referer: https://ocsinventory/index.php?function=admin_double

Regards,
Cirvent

**Comment by ChandlerBing82** [comment]
To update this issue I still have the same problem here.
When I check "Duplicates by : MAC address + Serial number"

I have 33 on the counter.
all the 33 are alone. Usually for duplicates we have 2 or more computers. For this duplicates they are all alone.

Here is a screenshot :
![image](https://user-images.githubusercontent.com/22145618/123940882-e7603e00-d999-11eb-8a93-b2b40f0d326d.png)
