### ISSUE TITLE
[BUG] setup.sh does not create upload/download folders

### ISSUE THREAD

**Issue by nmaas87** [OCSInventory-NG/OCSInventory-ocsreports#1089]
**OCS Inventory version**
Version : 2.8

**Describe the bug**
The setup.sh tries to chown the upload/download folders which seem to be necessary for uploading .ocs files - however, these folder do not exist in the copied folder structure and are neither created, so the chown fails.
https://github.com/OCSInventory-NG/OCSInventory-Server/blob/26ebae56175189156ddc68b54b5ea9350e2edca9/setup.sh#L1512-L1513

Idea to fix the bug: 
integrate
````
mkdir -p $ADM_SERVER_STATIC_DIR/$ADM_SERVER_STATIC_REPORTS_DIR/download
mkdir -p $ADM_SERVER_STATIC_DIR/$ADM_SERVER_STATIC_REPORTS_DIR/upload
````
at, i.e. line 1502 https://github.com/OCSInventory-NG/OCSInventory-Server/blob/26ebae56175189156ddc68b54b5ea9350e2edca9/setup.sh#L1502 in the setup.sh file

**To Reproduce**
1. Try to install 2.8 with setup.sh, the error log will show the failed chown

**Expected behavior**
correct install

**Screenshots**
-

**Log file (optional)**
-

**Comment by gillesdubois** [comment]
Hi @nmaas87 

In 2.8 there is no such directory as download and upload inside the webconsole.
The Chown is most likely a remanent from the older versions.

These directory were used by the old plugin engine which no longer exist.

Regards,
Gilles.
