### ISSUE TITLE
crontab_cve.php is not deleting old CVE

### ISSUE THREAD

**Issue by andrei-miron** [OCSInventory-NG/OCSInventory-ocsreports#1090]
**OCS Inventory version**
Version : 2.8

**Describe the bug**
crontab_cve.php is not deleting old CVE

**To Reproduce**
1. Go to '/usr/share/ocsinventory-reports/ocsreports/'
2. Run php crontab/cront_cve.php

Hi,

crontab_cve.php is showing a tons of lines with warning:
PHP Warning: strpos(): Empty needle in /usr/share/ocsinventory-reports/ocsreports/require/cve/Cve.php on line 315
In order to remove it I modified in function search_by_version line 315 with this:
                $execute_search = false;
                if (isset($vuln_conf))
                        if(strpos($vuln, (string)$vuln_conf) !== false)
                                $execute_search = true;
                if (isset($vuln_conf_all))
                        if (strpos($vuln, (string)$vuln_conf_all) !== false)
                                $execute_search = true;
// if((strpos($vuln, (string)$vuln_conf) !== false) || (strpos($vuln, (string)$vuln_conf_all) !== false)){
                if ($execute_search) {

Now when I run crontab_cve.php I see this warning:
Processing Adobe softwares ...
PHP Warning: mysqli_fetch_array() expects parameter 1 to be mysqli_result, string given in /usr/share/ocsinventory-reports/ocsreports/require/cve/Cve.php on line 367
Processing Adobe Systems Inc. softwares ...

This is generating by the function clean_cve at line:

while ($item_cve = mysqli_fetch_array($result)) {

but the problem is that variable $result it is reused in the while. So the first iteration of while is working good (with $result as a mysqli_result object) but after that $result is becoming the result of the curl.
So the correect block is:
    $curl = curl_init();
    while ($item_cve = mysqli_fetch_array($result, MYSQLI_ASSOC)) {
      $url = $this->CVE_SEARCH_URL."/api/cve/".$item_cve["cve"];
      curl_setopt($curl, CURLOPT_URL, $url);
      curl_setopt ($curl, CURLOPT_RETURNTRANSFER, 1);
      $result_curl = curl_exec ($curl);
      $vars = json_decode($result_curl, true);
      if(empty($vars)){
        $sql_clean = "DELETE FROM cve_search WHERE cve = '%s'";
        $sql_arg = array($item_cve["cve"]);
        $result_verif = mysql2_query_secure($sql_clean, $_SESSION['OCS']["writeServer"], $arg_sql);
      }
    }
    curl_close ($curl) ;

I also took out from close the curl_close$$curl) otherwise curl it was not working after the first iteration.

Best regards,
Andrei
**Expected behavior**

**Screenshots**

**Log file (optional)**
Apache / PHP / System log if needed

**Comment by bilin61** [comment]
When I implemented Fix cve bugs #1085 ( https://github.com/OCSInventory-NG/OCSInventory-ocsreports/commit/e8905819d9165aeba6507e10d90a242ea7d3bd74) I resave warning: 
PHP Warning:  mysqli_fetch_array() expects parameter 1 to be mysqli_result, string given in /usr/share/ocsinventory-reports/ocsreports/require/cve/Cve.php on line 359

**Comment by gillesdubois** [comment]
Hi,

You need to be in crontab directory and not in ocsreports.

1. Go to '/usr/share/ocsinventory-reports/ocsreports/crontab/'
2. Run php cron_cve.php

Regards,
Gilles.
