### ISSUE TITLE
[BUG] Modyfing a package doesn't work

### ISSUE THREAD

**Issue by StCyr** [OCSInventory-NG/OCSInventory-ocsreports#1095]
**OCS Inventory version**
Version : 2,8

**Describe the bug**
Trying to modify a package doesn't work

**To Reproduce**
0. Take not of a package's info file
1. Go to Deployement\Activate
2. Choose to edit the package mentioned at step 0
3. Modify filename
4. Click Update
5. Click Send
6. See that the package's info file hasn't changed

**Expected behavior**
The package's info file should have changed: its NAME property should have been updated

**Comment by charleneauger** [comment]
Hi @StCyr ,

With the 2.9 we removed the editing capabilities as it was causing too much problem.
The new wizard being lighter than the old one, recreating package is way faster now.

Best regards,
Charlene
