### ISSUE TITLE
[BUG] CVEs don't work on 2.8.1

### ISSUE THREAD

**Issue by mattoussaint** [OCSInventory-NG/OCSInventory-ocsreports#1096]
**OCS Inventory version**
Version : 2.8.1 from scratch

**Describe the bug**
My OCS server has just been installed with the latest release...
Many same error message ( ~800 000) when running cron_cve.php : 

PHP Warning:  strpos(): Empty needle in /usr/share/ocsinventory-reports/ocsreports/require/cve/Cve.php on line 316

0 CVE has been added to database.

My config : 
Debian 9 amd64 (from scratch)

**Comment by gillesdubois** [comment]
Hi,

Please post your configuration and put CVE in verbose mode.

Regards,
Gilles.

**Comment by mattoussaint** [comment]
Debian 9 amd64

CVE is already in verbose mode, this is how I got the error message

**Comment by anderson-infront** [comment]
Hello,
have the same problem here.

Debian 10.7 amd64
php Version is 7.3.

Regards
Harald
