### ISSUE TITLE
Data Export issu

### ISSUE THREAD

**Issue by patidarashok** [OCSInventory-NG/OCSInventory-ocsreports#110]
Hello Support Team,
Yesterday i was installed latest version of OCS, i have some basic query please resolve.
1. How can i export all computers data in standard excel format with TAB.
2. Can i take the asset/computer age from OCS
3. When i click the the asset i can view everything but in exported file.csv unable to find Storage and more required information. 

Pls resolve my query.
thanks
Ashok Patidar
DBCL - Indore, India

**Comment by mmainardi** [comment]
Hi,
  I fixed column data loss. Modify SQL in All Computers, the data will appears in export .

                                //if (strtolower($key) == strtolower($field)) {
                                if (strtolower($key) == strtolower(**preg_replace("/.*\./", "", $field)**)) {
                                        if (($field == 'TAG' or substr($field,0,7) == 'fields_')

**Comment by patidarashok** [comment]
Hi,

If possible can you please share step by Step process, as i don't have
perfect hand on database.

Thnks

Regadrs
Ashok Patidar

**Comment by mmainardi** [comment]
Hi,

Maybe extract the data from mysql.

SELECT 
  h.lastdate, h.name, SUM(DISKSIZE) as TotalLUN, sum(TOTAL) as TotalDisk, sum(FREE) as FreeDisk
FROM 
  hardware    h LEFT JOIN
  storages    s on s.hardware_id=h.id LEFT JOIN
  drives      d on d.hardware_id=h.id 
group by 
  h.lastdate, h.name
order by h.name;
