### ISSUE TITLE
[BUG] SSO doesn't work

### ISSUE THREAD

**Issue by dit-aix** [OCSInventory-NG/OCSInventory-ocsreports#1105]
**OCS Inventory version**
Version : 2.8.1

First of all, my installation works perfectly in local, LDAPS, LDAPS + LOCAL

My apache server is able to authenticate my user with mod_kerberos (AD backend)

So a got  $_SERVER['REMOTE_USER'] populated with my samaccountname which is strictly identical as my OCS account.

When i switch AUTH_TYPE to 4 in var.php, i'm automaticaly connected BUT i'm stuck on an empty page without any links, text …
In the menu, only "My account" but it doesn't work.

When i open the session file on my server : 
loggeduser exist and is well populated
lvluser doesn't exist (i think this is why i'm connected but stuck on a page without anything)
cnx_origine exist but is empty

**Comment by Lea9250** [comment]
Hi @dit-aix,

Do you have anything in your logs when facing this issue ?

Regards,
Léa

**Comment by charleneauger** [comment]
Hi,

Since there is no anwser, I'll now close the issue.

Regards,
Charlene.

**Comment by bontiv** [comment]
Hi,

L've the same issue. When we log with SSO, access rights is not applied. See this line :
https://github.com/OCSInventory-NG/OCSInventory-ocsreports/blob/7a159d97f815072a53a28a4793ecb136d276bfb5/backend/identity/methode/ldap.php#L53

LDAP identity is skipped if cnx_origine is not "LDAP". In case of SSO login, the AUTH method is always_ok.php but it doesn't define any cnx_origine.
