### ISSUE TITLE
[BUG] Missing Network Cards in Web interface

### ISSUE THREAD

**Issue by tsmr** [OCSInventory-NG/OCSInventory-ocsreports#1111]
**OCS Inventory version**
Version : 2.8.0 / Agent .8.0

**Describe the bug**
Some Network Cards are missing in the OCS Web interface. The cards are not displayed into the XML link from the computer form

The agent having these cards : 
![image](https://user-images.githubusercontent.com/13178158/104814701-b4255a80-5810-11eb-8fa0-1933363e687d.png)

Examples : 

Marvell AVASTAR Wireless-AC Network Controller (IPV6) 
Other (see MIB) 
Radio Spread Spectrum (802.11) 
585 Mb/s 
70:BC:10:5C:9E:69 
Up
..
 
Marvell AVASTAR Wireless-AC Network Controller 
Other (see MIB) 
Radio Spread Spectrum (802.11) 
585 Mb/s 
70:BC:10:5C:9E:69 
Up 
192.168.1.18 
255.255.255.0 
192.168.1.254 
192.168.1.0 
192.168.1.254  

There are into the OCSInventory.xml file on the agent : 

```
<NETWORKS>
            <DESCRIPTION>Marvell AVASTAR Wireless-AC Network Controller (IPV6)</DESCRIPTION>
            <TYPE>Other (see MIB)</TYPE>
            <TYPEMIB>Radio Spread Spectrum (802.11)</TYPEMIB>
            <SPEED>585 Mb/s</SPEED>
            <MACADDR>70:BC:10:5C:9E:69</MACADDR>
            <STATUS>Up</STATUS>
            <IPADDRESS>2a01:e0a:44d:2f0:58a5:c95c:eaa:8c15</IPADDRESS>
            <IPMASK>64</IPMASK>
            <IPGATEWAY>fe80::3627:92ff:fe65:a938</IPGATEWAY>
            <IPSUBNET>2a01:e0a:44d:2f0::</IPSUBNET>
            <IPDHCP />
            <MTU />
        </NETWORKS>
```

**Comment by tsmr** [comment]
Now the network card is on interface. I don't understand why the card disappear ?

**Comment by gillesdubois** [comment]
Hi @tsmr 

`Now the network card is on interface. I don't understand why the card disappear ?`

Does this card goes in some kind of disabled / disconnected mode ? If that the case OCS might not see it during inventory.

I would like you to try the following things : 
- On your OCS Server, edit the z-ocsinventory-server.conf and set OCS_OPT_DBI_PRINT_ERROR to 1
- Restart your apache service and send an inventory

Now, apache error_log should show more infos.

IMO, its not related to the server but who knows it could be a random SQL error that make the network table empty.

Regards,
Gilles.

**Comment by tsmr** [comment]
DBI_PRINT_ERROR has been on for a long time :) no errors in error_log :(

I have the problem on another computer.
His network card is the same as me : Marvell AVASTAR wireless AC network controller.
It is activated all the time (it is our main WIFI card)

The computer did its inventory this morning. And the network card was not present on the web interface. But its client was 2.6.0 - I upgraded it and now I see its network card. weird

i will check random SQL errors

**Comment by tsmr** [comment]
And now his network card disappeared from the interface again.
I don't understand why a physical network card can added and removed from interface..

**Comment by tsmr** [comment]
The agent found 34 Network Adapter(s)
And into the interface we have 33 Network Adapter(s)
![image](https://user-images.githubusercontent.com/13178158/105067731-4e3f0a00-5a80-11eb-9b87-50d190f146fe.png)

**Comment by gillesdubois** [comment]
Hi @tsmr 

Could you try to install our agent latest release candidate ? 
We changed a lot of things in the inventory process it could impact network cards inventory : https://github.com/OCSInventory-NG/WindowsAgent/releases/tag/2.8.0.1-RC

Regards,
Gilles.

**Comment by gillesdubois** [comment]
Hi @tsmr 

Up.

Regards,
Gilles.

**Comment by charleneauger** [comment]
Hi,

Since there is no anwser, I'll now close the issue.

Regards,
Charlene
