### ISSUE TITLE
[BUG] Deploy from ocs server 2.8 to Windows Agent 2.7.0.1

### ISSUE THREAD

**Issue by fgendorf** [OCSInventory-NG/OCSInventory-ocsreports#1113]
**OCS Inventory version**
Version : Version OCSReports: 2.8.1

**Describe the bug**
Deployment from 2.8 server to windows Agent 2.7.0.1 always fail with:

DOWNLOAD => High priority 0 package found, removing lower priority package from queue
	DOWNLOAD => Processing packages for cycle 1 on Tuesday, January 26, 2021 12:50:54
ERROR *** DOWNLOAD => Will not register package <1610976873> in history: result <ERR_BAD_DIGEST> not a success
DOWNLOAD => Sending result code <ERR_BAD_DIGEST> for package <1610976873>
	DID_CHECK => Read DeviceID <FLNB008-2020-11-03-20-25-52> and MACs <00:FF:63:E3:68:D7D4:BE:D9:2D:1A:64> in file <ocsinventory.dat>

it seems seed CRC betwwen Windows agent and OCS server are different.
On Windows Agent 2.8.0.0 it works normal

**To Reproduce**
Create a new deploy package on 2.8 server, try deploy on Windows Agent 2.7.0.1

**Expected behavior**
Deploy normally on 2.7.0.1 and I can Update Agent from 2.7.0.1 to 2.8.0.0 by OCS server

**Comment by charleneauger** [comment]
Hi @fgendorf ,

This bug only appear on Windows Agent 2.7.0.1 and has been fixed on Windows Agent 2.8.
As you can see on Windows Agent 2.8 release : `Minor fix on registry keys during install

Update Windows Agent from the server with this version is not recommended. We advise you to uninstall the agent completely and reinstall it from scratch.

Best regards,
Charlene Auger

**Comment by fgendorf** [comment]
well done, now imagine i had to uninstall and reinstall from scratch the
version 2.7.0.1 in almost 200 machines...
_________________________
Frederico Gendorf

**Comment by gillesdubois** [comment]
Hi @fgendorf,

We are sorry for the trouble you are encountering.
But you have to keep in mind that a software (closed source / open source) will most likely have bugs in it during its developpment.

In the case you don't have any way to redeploy automatically (trough GPO for exemple), I recommend you to wait a few months before updating to a new agent. You can also try out a new version only on a few agents and test if everything is alright before deploying to all your assets.

If you don't want to manage OCS and these kind of problem, you still can subscribe to our professional offer.

Regards,
Gilles.

**Comment by fgendorf** [comment]
Hi @gillesdubois
<https://github.com/OCSInventory-NG/OCSInventory-ocsreports/commits?author=gillesdubois>
Thank
you for your response.
I know softwares can have bugs, sorry by the words.
_ ________________________
Frederico Gendorf
