### ISSUE TITLE
Search with dates don't work

### ISSUE THREAD

**Issue by cb58** [OCSInventory-NG/OCSInventory-ocsreports#112]
Hi,

With Fix #102, search with dates don't work :
1. Number of agents that didn't send inventory since at least X day(s)
2. Machines not seen in more than Y day(s)
3. Search with various criteria

I have reviewed the management of dates by OCS.

```
grep 1270 `find plugins/language -type f`|sort
plugins/language/brazilian_portuguese/brazilian_portuguese.txt:1270 DDMMYYYY
plugins/language/english/english.txt:1270 MMDDYYYY
plugins/language/french/french.txt:1270 DDMMYYYY
plugins/language/german/german.txt:1270 TTMMJJJJ   => bad format for js/datetimepicker.js
plugins/language/hungarian/hungarian.txt:1270 DDMMYYYY  
plugins/language/italian/italian.txt:1270 DDMMYYYY
plugins/language/polish/polish.txt:1270 DDMMYYYY
plugins/language/portuguese/portuguese.txt:1270 DDMMYYYY
plugins/language/russian/russian.txt:1270 DDMMYYYY
plugins/language/slovenian/slovenian.txt:1270 DDMMYYYY
plugins/language/spanish/spanish.txt:1270 DDMMYYYY
plugins/language/turkish/turkish.txt:1270 DDMMYYYY
```

```
grep ^269 `find plugins/language -type f`|sort
plugins/language/brazilian_portuguese/brazilian_portuguese.txt:269 %d/%m/%Y
plugins/language/english/english.txt:269 %m/%d/%Y
plugins/language/french/french.txt:269 %d/%m/%Y
plugins/language/german/german.txt:269 %d/%m/%Y => bad format vs g(1270). Official format is %Y/%m/%d since 1996, but %d/%m/%Y is allowed again. See https://en.wikipedia.org/wiki/Date_format_by_country.
plugins/language/hungarian/hungarian.txt:269 %Y/%m/%d => bad format vs g(1270). Official format is %Y/%m/%d, but need rewrite NewCal and FormatDate in js/datetimepicker.js. Use %d/%m/%Y as g(1270) until somebody do it.
plugins/language/italian/italian.txt:269 %d/%m/%Y
plugins/language/polish/polish.txt:269 %m/%d/%R  => bad format. See https://en.wikipedia.org/wiki/Date_and_time_notation_in_Poland  => %d/%m/%Y
plugins/language/portuguese/portuguese.txt:269 %d/%m/%Y
plugins/language/russian/russian.txt:269 %m/%d/%Y => bad format vs g(1270)  => %d/%m/%Y
plugins/language/slovenian/slovenian.txt:269 %d/%m/%Y
plugins/language/spanish/spanish.txt:269 %d/%m/%Y
plugins/language/turkish/turkish.txt:269 %m/%d/%Y => bad format vs g(1270). See https://en.wikipedia.org/wiki/Date_and_time_notation_in_Turkey => %d/%m/%Y
```
[turkish.txt.diff.txt](https://github.com/OCSInventory-NG/OCSInventory-ocsreports/files/422788/turkish.txt.diff.txt)
[russian.txt.diff.txt](https://github.com/OCSInventory-NG/OCSInventory-ocsreports/files/422785/russian.txt.diff.txt)
[polish.txt.diff.txt](https://github.com/OCSInventory-NG/OCSInventory-ocsreports/files/422787/polish.txt.diff.txt)
[hungarian.txt.diff.txt](https://github.com/OCSInventory-NG/OCSInventory-ocsreports/files/422789/hungarian.txt.diff.txt)
[german.txt.diff.txt](https://github.com/OCSInventory-NG/OCSInventory-ocsreports/files/422786/german.txt.diff.txt)

The function compair_with_date() in function_search.php assume :
1. date separator is -
2. local date format is same mysql date format.

[function_search.php.diff.txt](https://github.com/OCSInventory-NG/OCSInventory-ocsreports/files/422791/function_search.php.diff.txt)

 
dateOnClick() and datePick() assume that there are only two formats dates.

[function_table_html.php.diff.txt](https://github.com/OCSInventory-NG/OCSInventory-ocsreports/files/422793/function_table_html.php.diff.txt)

dateTimeFromMysql() and dateToMysql() assume :
1. local date format is same mysql date format ;
2. only two dates formats.

dateToMysql() is not used => remove it. 

[function_commun.php.diff.txt](https://github.com/OCSInventory-NG/OCSInventory-ocsreports/files/422795/function_commun.php.diff.txt)

		 
In ms_custom_pack.php, add %Y/%m/%d format :

[ms_custom_pack.php.diff.txt](https://github.com/OCSInventory-NG/OCSInventory-ocsreports/files/422796/ms_custom_pack.php.diff.txt)

In ms_all_computers.php, add a comment to understand the date format :

[ms_all_computers.php.diff.txt](https://github.com/OCSInventory-NG/OCSInventory-ocsreports/files/422798/ms_all_computers.php.diff.txt)

TODO : Do not use YYYYMMDD format until rewrite NewCal() and FormatDate() in js/datetimepicker.js. 

The patches has been validated with OCS in English and French.

Regards,

**Comment by gillesdubois** [comment]
Hi,

This bug has been identified, thx for providing us a fix.
We will merge it with the master branch as soon as possible.

Thank you for your support !
Regards, Gilles Dubois.

**Comment by gillesdubois** [comment]
Hi,

All tests has been made look good for me i will commit today and merge your modifications.
Language tested : 
- German 
- French
- English
- Russian

Regards,
Gilles Dubois.
