### ISSUE TITLE
[BUG] Unix Agent: SNMP inventory not working: 500 internal server error

### ISSUE THREAD

**Issue by jackburton79** [OCSInventory-NG/OCSInventory-ocsreports#1120]
Version : 2.8.1

I've upgraded OCSINventory server/inventory to version 2.8.1, and unix agents to version 2.8.1.
Everything works correctly, except snmp scanning/uploading from agents.
I've configured snmp in ocsinventory server, and I have 2 agents (192.168.22.28 and 192.168.100.28) doing snmp scanning. They succesfully scan their respective networks, then log this:

[Mon Feb  8 17:45:03 2021][error] Cannot establish communication : 500 Internal Server Error
[Mon Feb  8 17:45:03 2021][debug] [snmp] End snmp_end_handler :)

Server side I get this in apache logs:
[Mon Feb 08 17:45:03.089542 2021] [perl:error] [pid 20836] [client 192.168.22.28:45164] \nnot well-formed (invalid token) at line 7643, column 18, byte 227208 at /usr/lib/perl5/vendor_perl/5.26.1/x86_64-linux-thread-multi/XML/Parser.pm line 187.\nXML::Simple called at /usr/lib/perl5/site_perl/5.26.1/Apache/Ocsinventory.pm line 218.\n
[Tue Feb 09 06:14:04.649540 2021] [perl:error] [pid 50217] [client 192.168.100.28:57388] \nnot well-formed (invalid token) at line 3658, column 18, byte 115187 at /usr/lib/perl5/vendor_perl/5.26.1/x86_64-linux-thread-multi/XML/Parser.pm line 187.\nXML::Simple called at /usr/lib/perl5/site_perl/5.26.1/Apache/Ocsinventory.pm line 218.\n

**Comment by charleneauger** [comment]
Hi @jackburton79 ,

Can you clean your unix agent log, send an inventory with debug at 1 and give your agent log ?

Best regards,
Charlene Auger

**Comment by jackburton79** [comment]
The log contains many informations about our internal network hosts, I'd prefer to strip it down a bit, at least removing the hosts information.
Which information do you need, in particular ?

**Comment by charleneauger** [comment]
Hi @jackburton79 ,

I need the XML SNMP structure which is sent to the server. After doing some search of the perl error mentionned, it seems to be that the XML tag aren't correctly formatted.

Regards,
Charlene

**Comment by jackburton79** [comment]
Could I send it to you privately in some way ?
Since there is switch IP address and firmware version information in it, I think it would not be completely safe to post it here.

**Comment by charleneauger** [comment]
Hi @jackburton79 ,

Can you tell me what is your agent module configuration in /etc/ocsinventory-agent/modules.conf?
I saw in your log file that the wrong SNMP module is called.
I think when you're installed the last Unix agent, the old module file hasn't been replaced by the new.

Regards,
Charlene

**Comment by jackburton79** [comment]
Here's the content of that file:

# this list of module will be load by the at run time
# to check its syntax do:
# #perl modules.conf
# You must have NO error. Else the content will be ignored
# This mechanism goal is to launch agent extension modules

use Ocsinventory::Agent::Modules::Download;
use Ocsinventory::Agent::Modules::Snmp;

# DO NOT REMOVE THE 1;
1;

**Comment by charleneauger** [comment]
@jackburton79 ,
 
Ok, normally the modules.conf for the Unix Agent 2.8.1 looks like that : 

<pre>
# this list of module will be load by the at run time
# to check its syntax do:
# #perl modules.conf
# You must have NO error. Else the content will be ignored
# This mechanism goal is to launch agent extension modules

use Ocsinventory::Agent::Modules::Download;
use Ocsinventory::Agent::Modules::SnmpScan;

# DO NOT REMOVE THE 1;
1;
</pre>
Reinstall the Unix agent and set yes to this question : 
<pre>
Should I remove the old unix_agent
Please enter 'y' or 'n'?> [n] y
</pre>

Regards,
Charlene

**Comment by jackburton79** [comment]
That worked. FYI also just changing the perl module name works as well. No more errors now, the server receives the snmp inventory, but I still cant see anything in snmp, although I think I need ti configure it differently.
Thanks!

**Comment by charleneauger** [comment]
Hi,

Good ! I close this issue :) 

Regards,
Charlene
