### ISSUE TITLE
All hardware fields are blank

### ISSUE THREAD

**Issue by fbattistin** [OCSInventory-NG/OCSInventory-ocsreports#1121]
**OCS Inventory version**
Version : 2.8.1 

**Describe the bug**
New installation without error. Agent install without error. The agent version 2.8.0 collect all the data and transfer to server without error, all general information and installed software are displayed, but all hardware data field are blank; the record are created, but all the fileds are blank in the batabase.
As example i checked the "Controller table"; the agent discover 6 contollers; I see 6 records empty in the database

Environment:
![ocs1](https://user-images.githubusercontent.com/26302494/107370586-7819a880-6ae3-11eb-9242-0b263485e6ea.png)

Screenshot:
![Screenshot at 2021-02-09 14-24-03](https://user-images.githubusercontent.com/26302494/107370335-22dd9700-6ae3-11eb-8cc5-abd0ff7c9d3e.png)
![ocs](https://user-images.githubusercontent.com/26302494/107370374-2cff9580-6ae3-11eb-8a5d-86f8cd1bc68b.png)

**Comment by charleneauger** [comment]
Hi @fbattistin ,

This bug has been fixed on Server with the PR [301](https://github.com/OCSInventory-NG/OCSInventory-Server/pull/301).
After apply this fix, remove all the collected info who are broken and send a new inventory.

Best regards,
Charlene Auger
