### ISSUE TITLE
[BUG] OCS 2.8 Links not populate

### ISSUE THREAD

**Issue by AllendeJavier** [OCSInventory-NG/OCSInventory-ocsreports#1122]
**OCS Inventory version**
Version : 2.8

**Describe the bug**

**To Reproduce**
![image](https://user-images.githubusercontent.com/36576667/107403554-88427f80-6b05-11eb-92ed-bfda16abf919.png)
If i click in the http:///ocsreports/?function=visu_computers appears empyt

![image](https://user-images.githubusercontent.com/36576667/107403616-9f816d00-6b05-11eb-97d6-993c4f04ad72.png)

ocsreports/index.php?function=visu_search&fields=HARDWARE-LASTCOME&comp=tall&values=02/09/21&values2=all&type_field=

![image](https://user-images.githubusercontent.com/36576667/107403731-c3dd4980-6b05-11eb-87e5-746cd0d904ef.png)

 Using this url http://<url>ocsreports/index.php?function=visu_search&fields=HARDWARE-LASTCOME&comp=tall&values2=all&type_field= appears all the elements
![image](https://user-images.githubusercontent.com/36576667/107403841-e66f6280-6b05-11eb-968d-8c9b4f3546d1.png)

**Log file (optional)**
Apache / PHP / System log if needed

no logs that shows this error

But doesnt appears any error in /var/log/apache2/error.log or /var/log/apache2/access.log

any idea?

**Comment by charleneauger** [comment]
Hi @AllendeJavier 

Can you check if you are missing the 'archive' column inside the hardware table ?
Most of the time when these kind of behavior appear, it mean that this columns hasn't been added properly during update.

Regards,
Charlene Auger

**Comment by AllendeJavier** [comment]
hi @charleneauger 

thanks for your response but review the database

![image](https://user-images.githubusercontent.com/36576667/107484182-5e7b6e00-6b82-11eb-87ba-a22e7cb27fea.png)

the table contains this columns.

regards

**Comment by charleneauger** [comment]
@AllendeJavier ,

For your third image with this url ocsreports/index.php?function=visu_search&fields=HARDWARE-LASTCOME&comp=tall&values=02/09/21&values2=all&type_field= , this is due to a translation bug. 
I fixed it here #1123 

But for your tab All computers, can you tell me what are your profile's rights ? I see you haven't all tab on your nav bar.

Regards,
Charlene

**Comment by AllendeJavier** [comment]
HI,

mi user is sadmin . The problem is in the module of language. It not working ok

regards
