### ISSUE TITLE
Search for Login Connected user does not work [BUG]

### ISSUE THREAD

**Issue by sokatra** [OCSInventory-NG/OCSInventory-ocsreports#1129]
**OCS Inventory version**
Version : 2.8.1

**Describe the bug**
I habe installed al completly new server with version 2.8.1
Agents are 2.0.5 
I see every computer , and i can see the field connected user with correct usernames 
But when i search trough login - connected user
like or equal or .. username .. no computer was found 

**To Reproduce**
1. Go to '...' Inventory
2. Click on '....'search with various criteria
3. choose login ... choose connected user 
4. choose like 
5. type in username

**Expected behavior**
a computer with the connect user should be found.. but nothing is found 

**Screenshots**
![image](https://user-images.githubusercontent.com/17703360/108230684-5357ad80-7141-11eb-9b02-c98101d10bdb.png)

**Log file (optional)**
Apache / PHP / System log if needed

**Comment by sokatra** [comment]
when i search with various criteria .. "computer -- connected user " the search give me results .. so the question is what is the difference between
Login: connected user ...and
Computer: connected user ?
Kind regards

Sokatra

**Comment by RudyLaurent** [comment]
Hi @sokatra,

The login table is not supposed to be here. 
I created a PR to remove it from the search with various criteria.

Regards,
Rudy Laurent
