### ISSUE TITLE
Undefined MYSQL_ASSOC issue in many more plugins than #96 notes.

### ISSUE THREAD

**Issue by kejones999** [OCSInventory-NG/OCSInventory-ocsreports#113]
Hi Folks,

 I've got a really experimental setup running on PHP7 and Debian SID, so I'll hope you'll pardon me for not offering diffs directly :-).

  Whilst I was hand-applying patches and edits today, I saw the same calls noted in #96 in a lot of the other plugins. I thought I'd better post a pseudo-grep-ish list of the other files that will have the same problem. Hope it helps!

```
./ocsreports/plugins/main_sections/ms_groups/ms_group_show.php:486:
./ocsreports/plugins/main_sections/ms_doubles/ms_doubles.php:48:
./ocsreports/plugins/main_sections/ms_export/ms_csv.php:86: 
./ocsreports/plugins/main_sections/ms_export/ms_csv.php:114: 
./ocsreports/plugins/main_sections/ms_search_soft/require/fonction.inc.php:40:
./ocsreports/plugins/main_sections/ms_search_soft/ms_options.php:17:
./ocsreports/plugins/computer_detail/cd_configuration/cd_configuration.php:129:
./ocsreports/plugins/computer_detail/cd_comments/cd_comments.php:119: 
``` 

Best Regards,

Keith

PS:  I'm presuming you've already noted that the bug in #96 was just that the constant was misspelled now that mysql has renamed their php library. It should have been MYSQL**I**_ASSOC. Not that it actually matters seeing as it's the default value and could just be deleted anyway :-)

**Comment by gillesdubois** [comment]
Hi,

A fix will be pushed in the next minutes.
php7 should be fine but some things can be forgotten thx for helping our software to be more compliant with php7

Regards,
Gilles Dubois.
