### ISSUE TITLE
memory capacity search [BUG]

### ISSUE THREAD

**Issue by sokatra** [OCSInventory-NG/OCSInventory-ocsreports#1130]
**OCS Inventory version**
Version : 2.8.1

**Describe the bug**
i searched for memory capacity.. regardless how big i choose my memory search number .. many computers are found. but they don't have tons of memory 

**To Reproduce**

![image](https://user-images.githubusercontent.com/17703360/108240051-c3b6fc80-714a-11eb-8c1c-7c2d91ba3640.png)

**Expected behavior**
only computers with more memory as my search parameter should be found
i don't know if the search field should contain MB oder GB

**Comment by RudyLaurent** [comment]
Hi @sokatra,

This data can't be changed because it can cause trouble with specific OS.
If you search the total memory capacity, you can use "Computer->RAM (MB)".

Regards
Rudy
