### ISSUE TITLE
seach for Bios Date [BUG]

### ISSUE THREAD

**Issue by sokatra** [OCSInventory-NG/OCSInventory-ocsreports#1131]
**OCS Inventory version**
Version : 2.8.1

**Describe the bug**
I searched for Bios Date less than .. and typed in 2010

computers found with Bios date like 09/25/2020

**To Reproduce**
Search with various criteria for 
![image](https://user-images.githubusercontent.com/17703360/108241312-fa414700-714b-11eb-9a76-48251c95b685.png)

**Expected behavior**
only computers with Bios date before 2010 should be found

**Screenshots**

**Log file (optional)**
Apache / PHP / System log if needed

**Comment by Lea9250** [comment]
Hi @sokatra,
Thank you for your report, unfortunately bios date format is not universal among systems, therefore we currently cannot provide any fix for this and do not intend to at the time.
Regards, 
Léa

**Comment by Cejvik** [comment]
HI, try using direct SQL query to sort or find. The same on my side, i need sort colum by date not like string.
