### ISSUE TITLE
how to manually add computers ? [FEATURE]

### ISSUE THREAD

**Issue by sokatra** [OCSInventory-NG/OCSInventory-ocsreports#1132]
**Is your feature request related to a problem? Please describe.**
I used many time the feature to import offline computers .. because we have some computers with no network connection for security reasons
I have a inventory DVD to create the inventory.ocs or xml .. afterwards i edit the xml to the right OS system.
For example Vmware or some other storage Machines which runs a locked Linux .. but i can boot the dvd..  i am not able to install the official agent there.
This is needed to capture all the hardware data..like serial or cpu network card etc.  
With 2.8.1 this isn't possible anymore . :-(

**Describe the solution you'd like**
I should be able to import offline computers like in previous versions.. 

**Describe alternatives you've considered**
i don't know what i can do with version 2.8.1 to import offline computers from other departments

**Comment by charleneauger** [comment]
Hi @sokatra ,

Local import is still available by using the perl and the newly released powershell injector. We just removed the web interface.

You can add with the script ocsinventory-injector.pl or with the script ocsinventory-powershell-injector.ps1. This scripts are availables on the OCS Inventory Server release folder in binutils.

Best regards,
Charlene Auger
