### ISSUE TITLE
Demo isn't working[BUG]

### ISSUE THREAD

**Issue by sokatra** [OCSInventory-NG/OCSInventory-ocsreports#1133]
**OCS Inventory version**
Version :  2.8.1

**Describe the bug**
the demo isn't working for over a year .. 
for me it is sad because i can't explain some bug's using the online demo.
I haven't always the time to install my own server .. but often i do this ( install a server)  i found some bugs in minutes. I am sure that an online demo helps to mitigate some bugs before a new release will be published
So i think a online demo helps to mitigate bug and advancing the project.

**To Reproduce**
https://demo.ocsinventory-ng.org/

**Expected behavior**
Demo should work or should completly taken offline because new user are frustrated for sure
The demo should also contains all features .. like radiobuttons .text in administrative data .. ... and some groups (dynamic AND static groups)
because in the past i had some issues to make a various criteria search with some AND and OR operations. 
With a working online demo i can explain problems much easier.

**Log file (optional)**
Apache / PHP / System log if needed

**Comment by coelhu** [comment]
Please add SNMP and IP discovery configuration in the demo to use as example.

**Comment by charleneauger** [comment]
Hi @sokatra ,

Thanks for your report, the demo site is up again.

@coelhu, you can see the documentation with many examples to know how to configure IpDiscover and SNMP features : 
http://wiki.ocsinventory-ng.org/06.Network-Discovery-with-OCS-Inventory-NG/Using-IP-discovery-feature/
http://wiki.ocsinventory-ng.org/06.Network-Discovery-with-OCS-Inventory-NG/Using-SNMP-scan-feature/
http://wiki.ocsinventory-ng.org/06.Network-Discovery-with-OCS-Inventory-NG/Managing-and-using-SNMP-feature/ 

Best regards,
Charlene
