### ISSUE TITLE
administrative data checkbox or radiobutton [BUG]

### ISSUE THREAD

**Issue by sokatra** [OCSInventory-NG/OCSInventory-ocsreports#1136]
**OCS Inventory version**
Version : 2.7 on centos 7
2.8.1 under Debian 10

**Describe the bug**
I can't see radio buttons or checkboxes under administraive data .. i just see a white backround
screenshot form version 2.7
![image](https://user-images.githubusercontent.com/17703360/108381933-97fa4c00-7208-11eb-9046-2cf3605c8015.png)

under 2.8.1 it is the same .. i think it has something to to with a perl dependency .. but installation from tar was successfull 

**To Reproduce**
go to manage - administrative data - click on new data 
type in "New Field" name
type in Caption 
select field type checkbox or radiobutton
select tab Tag

click send

goto "all computers" -select one computer 

on debian 10 i installed the following
sudo apt install libapache2-mod-php libapache2-mod-perl2 libapache-dbi-perl libapache-db-perl
sudo apt install php-soap php-curl php-json php-xml php-mbstring php-gd php-pclzip php-xmlrpc

**Expected behavior**
I should see checkboxes and radio buttons

**Screenshots**

**Log file (optional)**
Apache / PHP / System log if needed

**Comment by sokatra** [comment]
verified it with another browser (new edge) and firefox esr .. and version 2.8 ocs-inventory server ... now installed via rpm under centos 7.. also no radio button .. i really liked the buttons in version 2.1.2.. it is important for many peopel i think.
What i am doing wrong ? can this be solved prior to version 2.9 
Kind regards sokatra  and thanks for the great project

**Comment by charleneauger** [comment]
Hi @sokatra ,

After created checkbox and radio button, you should click on the parameters button next to the admin data form : 

![image](https://user-images.githubusercontent.com/28924550/120478458-299f5b00-c3ad-11eb-988b-960d3abcf5d4.png)

Next click on the plus button and added a new data : 

![image](https://user-images.githubusercontent.com/28924550/120478654-60757100-c3ad-11eb-8b67-52ebb2c967eb.png)

The checkbox and radio button appeared only if a datas are available for.

Regards,
Charlene

**Comment by charleneauger** [comment]
Hi @sokatra ,

Any news on this issue ?

Regards,
Charlene

**Comment by charleneauger** [comment]
Hi,

Since there is no anwser, I'll now close the issue.

Regards,
Charlene.
