### ISSUE TITLE
search for checkbox or radio button[BUG]

### ISSUE THREAD

**Issue by sokatra** [OCSInventory-NG/OCSInventory-ocsreports#1139]
**OCS Inventory version**
Version : 2.8.1

**Describe the bug**
When i do a search for an administrative checkbox radio button .. i can't do that .. because the second search dialog can't be selected
![image](https://user-images.githubusercontent.com/17703360/108686403-a771e180-74f5-11eb-916f-755d80073567.png)

**To Reproduce**
Go to search with various criteria .. select "account info" -... select Add
the choose having .. the second search parameter can't be selected ... perhaps it is by design .. but because i can't check radiobuttons or checkboxes .. because of this bug 
https://github.com/OCSInventory-NG/OCSInventory-ocsreports/issues/1136

**Expected behavior**
I should be able to create check-boxes and radio-buttons in administrative data .. and should be able to search for specific values afterwards

Kind regards
Sokatra

**Log file (optional)**
Apache / PHP / System log if needed

**Comment by charleneauger** [comment]
Hi @sokatra ,

Please, see my answer of your issue #1136  
After created data for checkbox and radio button, the datas should appear on the multicriteria

Best regards,
Charlene
