### ISSUE TITLE
Search for free capacity [FEATURE] [BUG]

### ISSUE THREAD

**Issue by sokatra** [OCSInventory-NG/OCSInventory-ocsreports#1140]
**Is your feature request related to a problem? Please describe.**
In computer details .. i can see the used capacity by percent
![image](https://user-images.githubusercontent.com/17703360/108687910-91fdb700-74f7-11eb-876f-739979c9b3cd.png)

**Describe the solution you'd like**
I haven't found a way to search for "used capacity" by percentage .. only by Megabytes  .. but this search does not work ..it is the same like this bug .
https://github.com/OCSInventory-NG/OCSInventory-ocsreports/issues/1130
but with disk capacity .. the result is the same .. independent what i use as the search number 
It will give me any computer in my database 
 
![image](https://user-images.githubusercontent.com/17703360/108688381-20723880-74f8-11eb-956b-57535e6d082e.png)

**Describe alternatives you've considered**
The search for free % of disk space should be possible OR at least the search for free disk space in MB should work .. what it does not
Kind regards

**Comment by Lea9250** [comment]
Hi @sokatra,
As you mentioned, you should be able to search on free disk space in mb (used capacity is not actually stored but calculated). Is it still not working for you ? It seems to work fine on the 2.9. version here.

Regards,
Léa

**Comment by charleneauger** [comment]
Hi,

Since there is no anwser, I'll now close the issue.

Regards,
Charlene.
