### ISSUE TITLE
[BUG] SOAP interface not working

### ISSUE THREAD

**Issue by PPetky** [OCSInventory-NG/OCSInventory-ocsreports#1141]
**OCS Inventory version**
Version : 2.8.1

**Describe the bug**
After update/upgrade to version 2.8 or 2.8.1 SOAP interface broken and became unusable 
on asking INVENTORY not META (with checksum 131071) and after updating DB version from 7028 to version 7039

**To Reproduce**
1. just use binutils/soap-client.pl with with parameters to point the OCSInventory server
2. See error:

==Bad request==
SQL:SELECT DISTINCT dico_soft.FORMATTED AS FORMAT FROM softwares,dico_soft WHERE HARDWARE_ID=? AND EXTRACTED=NAME
DATAS:22> <

This request goes from /usr/local/share/perl/5.xx.x/Apache/Ocsinventory/Interface/Inventory.pm 

**Expected behavior**
Give XML with all sections including "SOFTWARES" sections.

**Screenshots**

**Log file (optional)**
[error.log](https://github.com/OCSInventory-NG/OCSInventory-ocsreports/files/6021111/error.log)
[access.log](https://github.com/OCSInventory-NG/OCSInventory-ocsreports/files/6021112/access.log)

**Comment by gillesdubois** [comment]
Hi @PPetky 

SOAP interface is not supported anymore, please use the REST API.
http://wiki.ocsinventory-ng.org/11.Rest-API/Introduction/

Regards,
Gilles.
