### ISSUE TITLE
Search for software source [BUG]

### ISSUE THREAD

**Issue by sokatra** [OCSInventory-NG/OCSInventory-ocsreports#1142]
**OCS Inventory version**
Version : 2.8.1
as agent i tried 2.05 and 2.8.0.1RC

**Describe the bug**
when i use the various criteria search to search for a software source .. i will only get the option to get a numeric value
I should get a text field i think when "source" in ocsinventory is the same like source in windows add / remove menu

**To Reproduce**
Go to Inventory -- search with various criteria  - select All Software -select source -- select add
![image](https://user-images.githubusercontent.com/17703360/108713596-be75fb00-7518-11eb-841d-41f554157717.png)

**Expected behavior**
i should be able to the the source path like in add -remove software in windows
if you extend the tabs to sources .. you will get the source path tab .. some programs reports here the source path
![image](https://user-images.githubusercontent.com/17703360/108713843-13197600-7519-11eb-8bd1-2ef6ec6aba7a.png)
in windows 7 Dialog you have the option to get this information (windows 10 is similar)
![image](https://user-images.githubusercontent.com/17703360/108713947-33e1cb80-7519-11eb-97c2-c3a3bb7a9518.png)
![image](https://user-images.githubusercontent.com/17703360/108714009-4b20b900-7519-11eb-89eb-cdc6ebd432e7.png)

i also do not have the option to display the source in computer detail-- i only have these options
![image](https://user-images.githubusercontent.com/17703360/108714390-c5e9d400-7519-11eb-86dc-ae66cc802c28.png)

Kind regards
Sokatra

**Comment by Lea9250** [comment]
Hi @sokatra,

Search on install paths can be done through the 'Folder' field, the 'Source' field doesn't store this kind of information.
If the search on this field returns 'no data available', please apply the .patch file I attached.
[1218.patch.txt](https://github.com/OCSInventory-NG/OCSInventory-ocsreports/files/6726924/1218.patch.txt)
You'll have to download this into your ocsreports folder, get rid of the .txt extension and then execute `git apply 1218.patch`.

Hope this helps,
Léa
