### ISSUE TITLE
[BUG] The search for the total amount of memory is not performed correctly

### ISSUE THREAD

**Issue by kvolk2git** [OCSInventory-NG/OCSInventory-ocsreports#1147]
**OCS Inventory version**
Версия PHP : 7.4.3
Веб Сервер : Apache/2.4.41 (Ubuntu)
Сервер баз данных : Ubuntu 20.04 version 10.3.25-MariaDB-0ubuntu0.20.04.1
Версия OCSReports: 2.8.1

For example, the computer has 2 memory bars, such as 1024 MB and 2048 MB. If I need to find computers with more than 2048 Mb of memory, then these computers will not be included in the list.

1) Inventory -> Search with various criteria ->Memory - > Capacity  and press "Add"
2) Memory: Capacity -> More than -> 2048 and press "Send"

As a result, I will see only those computers that have one memory bar greater than 2048 MB. The search should sum up the amount of all installed memory, not the amount of one of the memory bars.

![01](https://user-images.githubusercontent.com/78740198/109060047-fab28280-76f5-11eb-90c4-4eb1cbbc069e.jpg)

![02](https://user-images.githubusercontent.com/78740198/109060135-1ae24180-76f6-11eb-9c06-b6a46a5d95bf.jpg)

**Comment by RudyLaurent** [comment]
Hi @kvolk2git,

When you search the memory's capacity, OCS will return the capacity by memory slot.
If you want to search with the amount of memory, you can use "Computer->RAM (MB)".

Regards,
Rudy
