### ISSUE TITLE
[BUG] - Section NEW of Dictionary not grouped alphabetically

### ISSUE THREAD

**Issue by onasiis** [OCSInventory-NG/OCSInventory-ocsreports#1149]
**OCS Inventory version**
Version OCSReports: 2.8.1
PHP Version: 7.4.15
Web Server: Apache/2.4.41 (Ubuntu)
Database Server: MySQL Community Server (GPL) version 5.7.33

**Describe the bug**
Section NEW of Dictionary not grouped alphabetically. All of new software appears together, and does not matter which letter you click, you always see the same.

**To Reproduce**
To reproduce the behaviour I just have to wait until new software appears in the list.

**Expected behavior**
The expected behaviour is to see each software in their letter group.

**Screenshots**
Please, have a look to the screenshots to understand the problem. 

Thanks.

![Dictionary_P](https://user-images.githubusercontent.com/62186680/109667419-67070900-7b70-11eb-89b6-e08641603d3f.png)
![Dictionary_G](https://user-images.githubusercontent.com/62186680/109667423-679f9f80-7b70-11eb-8faa-841724256d5f.png)

**Comment by onasiis** [comment]
Hi, thanks for your effort Lea9250. 
I just updated OCS Reports and OCS Inventory but I got the same issue. Dictionary unsorted.
Another thing that I just see is that the letters that I can see are the same that last time **G M P S U**, but as new software there are another letters as well. Have a look to the attached screenshot. Thanks.

![unsorted dictionary_2](https://user-images.githubusercontent.com/62186680/111304620-3afe8400-8656-11eb-8388-83920bae6930.png)

**Comment by onasiis** [comment]
Do you need more information? Logs? etc

**Comment by Lea9250** [comment]
Hi @onasiis, I am still looking into this. Mysql query logs could be useful if available, could you also switch to debug mode in web console parameters ? You should be able to see the last sql query made when accessing NEW section.
Thanks,
Léa

**Comment by onasiis** [comment]
Hi, sorry for the delay. Here is the screenshot:
![MYSQL_Query_OCS](https://user-images.githubusercontent.com/62186680/113882112-52481180-97bd-11eb-987f-4c399d681661.png)


[DEBUG]TABLE REQUEST[DEBUG]
LAST REQUEST:
SELECT SQL_CALC_FOUND_ROWS NAME, count(NAME) as QTE,ID from software_name where name != '' and name not in (select extracted name from dico_soft) and name not in (select extracted name from dico_ignored) group by name limit 0 , 25


DEBUG]REQUEST MADE => [DEBUG]

SELECT TYPE FROM accountinfo_config
select NAME,IVALUE,TVALUE,COMMENTS from config where NAME in ( 'CUSTOM_THEME' )
SELECT * FROM `extensions`
select NAME,IVALUE,TVALUE,COMMENTS from config where NAME in ( 'WARN_UPDATE' )
SELECT id,user_group FROM operators WHERE id='admin' and passwd ='gsdgsdfgsdgfsdfgsfdg'


Thanks!
