### ISSUE TITLE
[BUG] does not display the devices

### ISSUE THREAD

**Issue by xElmerp** [OCSInventory-NG/OCSInventory-ocsreports#1158]
**OCS Inventory version**
Version : 2.8.1

**Describe the bug**
I do not see the equipment

**To Reproduce**

I have added a pc
![image](https://user-images.githubusercontent.com/81328599/112375109-43d80100-8cb9-11eb-9a8e-6e1856bc6433.png)

when I go to all the teams I do not see anything
![image](https://user-images.githubusercontent.com/81328599/112375255-741f9f80-8cb9-11eb-9849-9a09b46f9ba9.png)

**Log file (optional)**
Apache:2.4.37 / PHP:7.2.24 / System log if needed

**Comment by gillesdubois** [comment]
Hi,

Could you provide more information such as the apache / mysql log file and the javascript console network output ?

Regards,
Gilles.

**Comment by charleneauger** [comment]
Hi,

Since there is no anwser, I'll now close the issue.

Regards,
Charlene.
