### ISSUE TITLE
Windows 8.1 Pro WINPRODKEY does not match

### ISSUE THREAD

**Issue by zxtury** [OCSInventory-NG/OCSInventory-ocsreports#116]
Hi..!!

I just realize that the Windows 8.1 (maybe Windows 8 too) license does not match with the license I entered when Windows was installed.

As you can see, as particial license, OCS gave me **VH4W3** when my original license ends with **D3VPQ**

![2016-08-22_15-15-40](https://cloud.githubusercontent.com/assets/19822966/17873973/7a150d4a-687d-11e6-8aae-71fb65fc30a9.png)

PS. Sorry for my poor english skills!! =)

**Comment by MyTheValentinus** [comment]
Hello @zxtury,
Yes from Windows 8 to 10, ocs agent retrieve only the oem licence.
We patched next release of OCS agent for windows. 
Thank for your contribution and see you soon.

**Comment by zxtury** [comment]
Thanks for your reply!

**Comment by gillesdubois** [comment]
Hi,

As long as it's a windows agent problem, i re-opened the issue in the right repository.

Regards,
Gilles Dubois.
