### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ssalle-git** [OCSInventory-NG/OCSInventory-ocsreports#1161]
**OCS Inventory version**
Version : 2.8

**Describe the bug**
After OCS Migration of 2.4 to 2.8, passing by each versions, i have a display issue between main page "computer per tag" and the page for a particular tag.

For example, on main page for a tag i have 39 computers, if i clic on this same tag, the page with the computers list  concerning this tag opens, but i have only 38 computers.

If i request the database by sql, i have 38 computers in database.

**To Reproduce**
1. Go to page 'Computers per Tag'
2. You have all tags with the number computers, for example MON TAG i have 236 computers
3. Click on 'a tag (MON for example)'
4. result is 229 computers

**Expected behavior**
Have the same number between page "computer per tag" and the result in the specific TAG.

**Screenshots**
![Screenshot1](https://user-images.githubusercontent.com/80680126/113007177-45e90680-9176-11eb-903e-4ee451296fef.png)
![Screenshot2](https://user-images.githubusercontent.com/80680126/113007195-497c8d80-9176-11eb-8a95-6cf5d4d39450.png)

**Log file (optional)**
No error in log file

**Comment by charleneauger** [comment]
Hi @ssalle-git ,

This bug has been fixed on 2.9 version. 

Best regards,
Charlene
