### ISSUE TITLE
[BUG] Number of computer by software and number of software is false

### ISSUE THREAD

**Issue by alexandremilo** [OCSInventory-NG/OCSInventory-ocsreports#1169]
**OCS Inventory version**
Version : 2.8.1

**Describe the bug**
When looking at the software list the number of computers and the number of computers on the software page itself is wrong. It happens after removing a computer from the hardware list. 
To give an example we had 20 computers which were supposed to have chrome with a given version while when we clicked on this software we only got 7 computers which truly had it.

**To Reproduce**
1. Remove one computer from the inventory with a specific software version(there must still be other computers with the same software)
2. Go to Inventory>All Software and search for it
3. Click on the Count for the software and the computer doesn't appear anymore

**Expected behavior**
After having removed the computer the number of software should have been decreased

**Comment**
The bug comes from the fact that the software list still have the entries for the removed computers

**Comment by Goldtool** [comment]
Hello,

I have the same issue.
Some softwares have for example 50 installations when I have only 20 computers in my computer list.
If I click on the count, I can see the real number of installation.

**Comment by krovaxpc** [comment]
I have version 2.9 and same problem:

Microsoft Report Viewer 2012 Runtime 833
On list PC with this software: 702 Result(s)

even after manual runnning script:
cd /usr/share/ocsinventory-reports/ocsreports/crontab/ && php cron_all_software.php

If i delete some old PC a run script again show: number of software: 825

maybe after upgrades, some leftovers in DB.

**Comment by gillesdubois** [comment]
Hi @krovaxpc 

You guess is the right one I think, there must be some leftover in the database that make the difference.
In that case you will have to clean the database from old / ghost entries.

Regards,
Gilles.

**Comment by rayzilt** [comment]
@gillesdubois And how do we do that?

**Comment by rayzilt** [comment]
We have the same problem, so please could you tell us how we can clear the database?

![Picture-1](https://user-images.githubusercontent.com/3105311/120464750-901c7d00-c39d-11eb-9c86-d712191be633.png)

![Picture-2](https://user-images.githubusercontent.com/3105311/120464770-94e13100-c39d-11eb-80b2-71d8289bf43d.png)

**Comment by alexandremilo** [comment]
Hi @rayzilt here is what i used to clean this, it doesn't remove all of the leftovers but it at least resolve the problem.
Just send this request to your database
DELETE FROM software WHERE software.HARDWARE_ID NOT IN(SELECT hardware.ID FROM hardware )

**Comment by rayzilt** [comment]
Hi @alexandremilo Thanks! I will try this.

But in my opinion this is a bug and should be resolved by the OCS team, or this is a kind of feature that I don't understand :-)
So somehow it's weird that this issue has been closed by them.
