### ISSUE TITLE
After delete one or more computers the stats are not updated

### ISSUE THREAD

**Issue by saep-es** [OCSInventory-NG/OCSInventory-ocsreports#117]
In a volatile enviroment this issue could be a real problem. I am talking about stats on the first page: Machines in DB, Machines Inventoried, Machines contacted today, etc.

**Comment by gillesdubois** [comment]
Hi,

These stats are cached on login and are static (They don't update on page reload)
If you log-out / log-in again these stats will update

Regards,
Gilles Dubois.
