### ISSUE TITLE
[BUG] Cyrillic symbols in REST API answer is in wrong encoding

### ISSUE THREAD

**Issue by igoriilla-projects** [OCSInventory-NG/OCSInventory-ocsreports#1171]
**OCS Inventory version**
Version :  2.8.1

**Describe the bug**
Cyrillic symbols in REST API answer is in wrong encoding

api request: curl http://SERVER_IP/ocsapi/v1/computer/2 |  jq -c '.[].softwares|.[].NAME'

Answer:
...
...
...
"Security Update KB4601395"
"Security Update KB5001028"
"NVIDIA ÐÑÐ°ÑÐ¸ÑÐµÑÐºÐ¸Ð¹ Ð´ÑÐ°Ð¹Ð²ÐµÑ 456.71"  - must be -> "NVIDIA Графический драйвер 456.71"
"ÐÐ°Ð¹ÐºÑÐ¾ÑÐ¾ÑÑ Windows 10 Pro"  - must be -> "Майкрософт Windows 10 Pro"

Screenshot from firefox: 
<img width="264" alt="1" src="https://user-images.githubusercontent.com/61516126/115522352-77e91680-a2a5-11eb-9740-192c8a0ecddd.png">

**Comment by gillesdubois** [comment]
Hi @igoriilla-projects 

Unfortunately we don't have alot of system with Cyrillic symbol to test.
Could you generate a XML file of one of your machine and send it to us ?

You have to execute ocsinventory.exe /XML from the install directory.
The file will be generated in program data.

Regards,
Gilles.

**Comment by igoriilla-projects** [comment]
Hello, link to report.xml -> https://yadi.sk/d/6jfzP-6zoevA4Q
github don't allow attach *.xml files.

**Comment by charleneauger** [comment]
Hi @igoriilla-projects ,

This issue has been fixed with the mentioned PR :-)

Best regards,
Charlene

**Comment by igoriilla-projects** [comment]
Thank you!
