### ISSUE TITLE
IP Discover Error

### ISSUE THREAD

**Issue by automotorcanarias** [OCSInventory-NG/OCSInventory-ocsreports#1172]
Hi, I'm received a error log with the ip discover

Invalid options. Abort..
[Thu Apr 22 08:00:18.592956 2021] [php7:warn] [pid 54073] [client 130.10.2.136:60355] PHP Warning:  Invalid argument supplied for foreach() in /usr/share/ocsinventory-reports/ocsreports/plugins/main_sections/ms_ipdiscover/ms_ipdiscover_analyse.php on line 61, referer: http://130.10.2.128/ocsreports/index.php?function=ipdiscover_info&head=1&prov=inv&value=130.10.0.0
[Thu Apr 22 08:00:18.593097 2021] [php7:warn] [pid 54073] [client 130.10.2.136:60355] PHP Warning:  Invalid argument supplied for foreach() in /usr/share/ocsinventory-reports/ocsreports/plugins/main_sections/ms_ipdiscover/ms_ipdiscover_analyse.php on line 61, referer: http://130.10.2.128/ocsreports/index.php?function=ipdiscover_info&head=1&prov=inv&value=130.10.0.0
[Thu Apr 22 08:00:18.593126 2021] [php7:warn] [pid 54073] [client 130.10.2.136:60355] PHP Warning:  Invalid argument supplied for foreach() in /usr/share/ocsinventory-reports/ocsreports/plugins/main_sections/ms_ipdiscover/ms_ipdiscover_analyse.php on line 61, referer: http://130.10.2.128/ocsreports/index.php?function=ipdiscover_info&head=1&prov=inv&value=130.10.0.0
[Thu Apr 22 08:00:18.593148 2021] [php7:warn] [pid 54073] [client 130.10.2.136:60355] PHP Warning:  Invalid argument supplied for foreach() in /usr/share/ocsinventory-reports/ocsreports/plugins/main_sections/ms_ipdiscover/ms_ipdiscover_analyse.php on line 61, referer: http://130.10.2.128/ocsreports/index.php?function=ipdiscover_info&head=1&prov=inv&value=130.10.0.0
[Thu Apr 22 08:00:18.593170 2021] [php7:warn] [pid 54073] [client 130.10.2.136:60355] PHP Warning:  Invalid argument supplied for foreach() in /usr/share/ocsinventory-reports/ocsreports/plugins/main_sections/ms_ipdiscover/ms_ipdiscover_analyse.php on line 61, referer: http://130.10.2.128/ocsreports/index.php?function=ipdiscover_info&head=1&prov=inv&value=130.10.0.0
[Thu Apr 22 08:00:18.593192 2021] [php7:warn] [pid 54073] [client 130.10.2.136:60355] PHP Warning:  Invalid argument supplied for foreach() in /usr/share/ocsinventory-reports/ocsreports/plugins/main_sections/ms_ipdiscover/ms_ipdiscover_analyse.php on line 61, referer: http://130.10.2.128/ocsreports/index.php?function=ipdiscover_info&head=1&prov=inv&value=130.10.0.0
[Thu Apr 22 08:00:18.593214 2021] [php7:warn] [pid 54073] [client 130.10.2.136:60355] PHP Warning:  Invalid argument supplied for foreach() in /usr/share/ocsinventory-reports/ocsreports/plugins/main_sections/ms_ipdiscover/ms_ipdiscover_analyse.php on line 61, referer: http://130.10.2.128/ocsreports/index.php?function=ipdiscover_info&head=1&prov=inv&value=130.10.0.0
[Thu Apr 22 08:00:18.593236 2021] [php7:warn] [pid 54073] [client 130.10.2.136:60355] PHP Warning:  Invalid argument supplied for foreach() in /usr/share/ocsinventory-reports/ocsreports/plugins/main_sections/ms_ipdiscover/ms_ipdiscover_analyse.php on line 61, referer: http://130.10.2.128/ocsreports/index.php?function=ipdiscover_info&head=1&prov=inv&value=130.10.0.0
Invalid options. Abort..
[Thu Apr 22 08:00:18.796148 2021] [php7:warn] [pid 54073] [client 130.10.2.136:60355] PHP Warning:  Invalid argument supplied for foreach() in /usr/share/ocsinventory-reports/ocsreports/plugins/main_sections/ms_ipdiscover/ms_ipdiscover_analyse.php on line 61, referer: http://130.10.2.128/ocsreports/index.php?function=ipdiscover_analyse&head=1&rzo=130.10.0.0
[Thu Apr 22 08:00:18.796183 2021] [php7:warn] [pid 54073] [client 130.10.2.136:60355] PHP Warning:  Invalid argument supplied for foreach() in /usr/share/ocsinventory-reports/ocsreports/plugins/main_sections/ms_ipdiscover/ms_ipdiscover_analyse.php on line 61, referer: http://130.10.2.128/ocsreports/index.php?function=ipdiscover_analyse&head=1&rzo=130.10.0.0
[Thu Apr 22 08:00:18.796194 2021] [php7:warn] [pid 54073] [client 130.10.2.136:60355] PHP Warning:  Invalid argument supplied for foreach() in /usr/share/ocsinventory-reports/ocsreports/plugins/main_sections/ms_ipdiscover/ms_ipdiscover_analyse.php on line 61, referer: http://130.10.2.128/ocsreports/index.php?function=ipdiscover_analyse&head=1&rzo=130.10.0.0
[Thu Apr 22 08:00:18.796213 2021] [php7:warn] [pid 54073] [client 130.10.2.136:60355] PHP Warning:  Invalid argument supplied for foreach() in /usr/share/ocsinventory-reports/ocsreports/plugins/main_sections/ms_ipdiscover/ms_ipdiscover_analyse.php on line 61, referer: http://130.10.2.128/ocsreports/index.php?function=ipdiscover_analyse&head=1&rzo=130.10.0.0
[Thu Apr 22 08:00:18.796218 2021] [php7:warn] [pid 54073] [client 130.10.2.136:60355] PHP Warning:  Invalid argument supplied for foreach() in /usr/share/ocsinventory-reports/ocsreports/plugins/main_sections/ms_ipdiscover/ms_ipdiscover_analyse.php on line 61, referer: http://130.10.2.128/ocsreports/index.php?function=ipdiscover_analyse&head=1&rzo=130.10.0.0
[Thu Apr 22 08:00:18.796224 2021] [php7:warn] [pid 54073] [client 130.10.2.136:60355] PHP Warning:  Invalid argument supplied for foreach() in /usr/share/ocsinventory-reports/ocsreports/plugins/main_sections/ms_ipdiscover/ms_ipdiscover_analyse.php on line 61, referer: http://130.10.2.128/ocsreports/index.php?function=ipdiscover_analyse&head=1&rzo=130.10.0.0
[Thu Apr 22 08:00:18.796229 2021] [php7:warn] [pid 54073] [client 130.10.2.136:60355] PHP Warning:  Invalid argument supplied for foreach() in /usr/share/ocsinventory-reports/ocsreports/plugins/main_sections/ms_ipdiscover/ms_ipdiscover_analyse.php on line 61, referer: http://130.10.2.128/ocsreports/index.php?function=ipdiscover_analyse&head=1&rzo=130.10.0.0
[Thu Apr 22 08:00:18.796234 2021] [php7:warn] [pid 54073] [client 130.10.2.136:60355] PHP Warning:  Invalid argument supplied for foreach() in /usr/share/ocsinventory-reports/ocsreports/plugins/main_sections/ms_ipdiscover/ms_ipdiscover_analyse.php on line 61, referer: http://130.10.2.128/ocsreports/index.php?function=ipdiscover_analyse&head=1&rzo=130.10.0.0

Can somebody help me?

**Comment by Lea9250** [comment]
Hi @automotorcanarias,

There's a few useful information that seem to be missing from your issue. Could you complete the issue template provided when creating a new issue ? It would be easier to understand what you are trying to achieve here and why these logs did show up.

Thanks,
Léa
