### ISSUE TITLE
[BUG] - CVE matching rules not work

### ISSUE THREAD

**Issue by somzoli** [OCSInventory-NG/OCSInventory-ocsreports#1173]
**OCS Inventory version**
Version : 2.8.1

**Describe the bug**
CVE inventory matching regexp not works as expected. I tried to check Microsoft Office products query with Matching rules, because publisher and software name not matched with CVE server entries. 
After run cve cron_cve.php, it snot show Microsoft results. 
The CVE server is own installed CIRCL cve server. 

**To Reproduce**
Software name: Microsoft Office 2016 
Publisher need: microsoft
Name result: office

**Expected behavior**
Query for microsoft (and other softwares) CVE's.

Can you help with this? 

Z

**Comment by somzoli** [comment]
In version 2.9 the regex matching rules seems to be working. But the sotware versions seems not correct

**Comment by charleneauger** [comment]
Hi @somzoli ,

This issue has been fixed with the PR #1212 

Regards,
Charlene
