### ISSUE TITLE
[BUG] All software: “No data available in table”

### ISSUE THREAD

**Issue by coelhu** [OCSInventory-NG/OCSInventory-ocsreports#1177]
**OCS Inventory version**
- Distribution : openSUSE Leap 15.2
- PHP Version : 7.4.6
- Database Server : MariaDB package version 10.4.17-MariaDB
- Version OCSReports: 2.8.1
- Agent Version: 2.8.1
- Ocs Server/Agent/ocsreports installed from source 

**Describe the bug**
Menu: Inventory -> All software: “No data available in table”, but there are 3 hosts in inventory and all three have software inventoried.

**To Reproduce**
Add some hosts to the inventory and go to the "Menu: Inventory -> All software" 

**Expected behavior**
"Menu: Inventory -> All software" 
A compilation of all software should appear, but the table is empty, in previous versions this was working.

**More Details**

**Version 2.8 installed from repository on CentOS-8 is working** (_dnf -y install https://rpm.ocsinventory-ng.org/ocsinventory-release-latest.el8.ocs.noarch.rpm_)

The demo version is not working too: https://demo.ocsinventory-ng.org/?function=visu_all_soft

On Ubuntu 20.04 / SLES 15.4 has the same problem using version 2.8.1 installed from source

In the “All Software” page this SQL command is called but looks like it is not working:

```
MariaDB [ocsweb]> SELECT SQL_CALC_FOUND_ROWS n.NAME, p.PUBLISHER, v.VERSION, sl.IDENTIFIER as id, sc.CATEGORY_NAME, sl.COUNT as nb FROM software_link sl LEFT JOIN software_name n ON sl.NAME_ID = n.ID LEFT JOIN software_publisher p ON sl.PUBLISHER_ID = p.ID LEFT JOIN software_version v ON sl.VERSION_ID = v.ID LEFT JOIN software_categories sc ON sl.CATEGORY_ID = sc.ID order by nb desc limit 0 , 10;

Empty set (0.000 sec)
```

**Screenshots**
All software empty: https://postimg.cc/rztjXy0Y

Host with software: https://postimg.cc/ftP87J3Y

**Comment by charleneauger** [comment]
Hi @coelhu ,

To improve software query speed, all software page is now populated by crontab. Just execute `php cron_all_software` in ocsreports crontab folder. 

Best regards,
Charlene Auger

**Comment by coelhu** [comment]
Worked, Thanks!

**Comment by KazimierzSyncron** [comment]
If I want it updated automatically, shall I just run all .php scripts in crontab directory? I added below script to /etc/cron.hourly/ dir
```
#!/bin/bash
cd /usr/share/ocsinventory-reports/ocsreports/crontab
for f in *.php; do
        /usr/bin/php7.4 -f $f
done
```
