### ISSUE TITLE
On the debug page for some user modes it is necessary to click on OK button twice

### ISSUE THREAD

**Issue by saep-es** [OCSInventory-NG/OCSInventory-ocsreports#118]
For MAINTENANCE just one click is enough. For NORMAL or LANGUAGE one click is not.

**Comment by gillesdubois** [comment]
Hi,

Sorry but improving this page is not in our roadmap / priority.
Debug page is not used by a lot of people as long as it's more developer / contributors oriented feature.
However, if you want you can improve it by yourself and i will be glad to merge your contribution.

Thanks for your support.
Regards,
Gilles Dubois.
