### ISSUE TITLE
[BUG] OCS2.9 can't edit deployment packages

### ISSUE THREAD

**Issue by ajavor** [OCSInventory-NG/OCSInventory-ocsreports#1182]
**OCS Inventory version**
Version : 2.9

**Describe the bug**
In version 2.8.1, the first editable icon was visible in the Actions column, in version 2.9 the icon is missing .

**To Reproduce**
Go to menu "Deployment" > "Activate" > "Available packages"

**Expected behavior**
The icon is not displayed or maybe this option has been removed in the latest version of OCS?

**Screenshots**
OCS2.8.1
![obraz](https://user-images.githubusercontent.com/32665748/117170543-671ec180-adca-11eb-8d6e-f87a2fda7c84.png)

OCS2.9
![obraz](https://user-images.githubusercontent.com/32665748/117169914-d2b45f00-adc9-11eb-8f9e-8aa190be31e8.png)

**Comment by gillesdubois** [comment]
Hi,

This feature has been removed since the new deployment system is not compliant with editing.

Regards,
Gilles.
