### ISSUE TITLE
[BUG] 2.9 software list is empty, restapi isn't working

### ISSUE THREAD

**Issue by kost1993** [OCSInventory-NG/OCSInventory-ocsreports#1184]
**OCS Inventory version**
Version :  2.9

**Describe the bug**
Since upgrading the server to 2.9 from 2.7 all software tab (inventory -> "All software")  show nothing.
And there are a lot (like millions) of error messages in apache2 error log like that one:
Use of uninitialized value in pattern match (m//) at /usr/local/share/perl/5.28.1/Apache/Ocsinventory/Server/Inventory/Software.pm line 179.

And that restapi isn't working
https://wiki.ocsinventory-ng.org/11.Rest-API/GET-Routes/#list-one-computer-details
In apache2 error log:
DBD::mysql::db selectall_arrayref failed: Unknown column 'n.CATEGORY' in 'on clause' at /usr/local/share/perl/5.28.1/Api/Ocsinventory/Restapi/ApiCommon.pm line 158.
[2021-05-13 12:41:49.46177] [1627] [error] DBD::mysql::db selectall_arrayref failed: Unknown column 'n.CATEGORY' in 'on clause' at /usr/local/share/perl/5.28.1/Api/Ocsinventory/Restapi/ApiCommon.pm line 158.

**To Reproduce**
1. Login to OCS Inventory 2.9 after upgrade from 2.7
2. Click on 'Inventory' -> "All software"
3. See empty list

**Expected behavior**
See list of all software

**Screenshots**

**Log file (optional)**
Apache / PHP / System log if needed
Addintional warnings
[Thu May 13 12:55:14.126492 2021] [php7:warn] [pid 1551] [client ] PHP Warning:  implode(): Invalid arguments passed in /usr/share/ocsinventory-reports/ocsreports/require/softwares/SoftwareCategory.php on line 252, referer: https://ocs/ocsreports/index.php?function=computer&head=1&systemid=184972&cat=software
[Thu May 13 12:55:14.126579 2021] [php7:warn] [pid 1551] [client ] PHP Warning:  Invalid argument supplied for foreach() in /usr/share/ocsinventory-reports/ocsreports/require/softwares/SoftwareCategory.php on line 233, referer: https://ocs/ocsreports/index.php?function=computer&head=1&systemid=184972&cat=software

**Comment by Goldtool** [comment]
Hello, 

Same issue for me after upgrade to 2.7->2.9
I had a lot of softwares, and nothing now, after the upgrade.

**Comment by somzoli** [comment]
Hello,

Me too. After upgrade softwares empty.

**Comment by charleneauger** [comment]
Hi @kost1993 @Goldtool @somzoli ,

Since 2.9 version, the All software page is populated by the crontab cron_all_software.php in ocsreports/crontab folder.

With reference to the error `Use of uninitialized value in pattern match (m//)`, you can find below the link to the fix :
https://github.com/OCSInventory-NG/OCSInventory-Server/pull/323/files

And for the API error : 
https://github.com/OCSInventory-NG/OCSInventory-Server/pull/324/files

Best regards,
Charlene Auger
