### ISSUE TITLE
[BUG] Identified devices don't show up in the "identified peripherals list" page

### ISSUE THREAD

**Issue by StCyr** [OCSInventory-NG/OCSInventory-ocsreports#1185]
**OCS Inventory version**
Version : 2.8.1

**Describe the bug**
Not all identified devices show up in the "Identified peripherals list" page.

Apparently, the query to get the identified devices is:

`SELECT SQL_CALC_FOUND_ROWS n.ID,n.TYPE,n.DESCRIPTION,a.IP,a.MAC,a.MASK,a.NETID,a.NAME,a.date,n.USER FROM network_devices n LEFT JOIN netmap a ON a.mac=n.macaddr WHERE netid = '<network>'`

Which means identified devices must also be in the `netmap` table to show up here. If I understand it correctly, the `netmap` page is populated by ipdiscover.

When I look at those tables on my instance, I can find all the identified devices in the `network_devices` table, but there is no corresponding entries in the `netmap` table for the identified devices that don't show up in the "identified peripherals list".

What's the reason why identified devices must also be in the netmap table to show up in the "identified peripherals list" page? I mean: When I identify a device I want to find it back whenever I like until I decide to delete it from the database. I don't want it to disappear when, for wathever reason, ipdiscover removes it from the netmap table.

**Expected behavior**
All identified devices should show up in the 'Identified peripherals list' page regardless of whether they are in the netmap table or not

**Comment by gillesdubois** [comment]
Hi @StCyr 

Is this issue still revelant if you try with the 2.9 ?

Regards,
Gilles.
