### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by xxedgexx** [OCSInventory-NG/OCSInventory-ocsreports#1189]
**OCS Inventory version**
Version : 2.9

**Describe the bug**
PHP Fatal error:  Uncaught Error: Call to undefined function simplexml_load_string() in /usr/share/ocsinventory-reports/ocsreports/require/config/XMLUrlsSerializer.php:54\nStack trace:\n#0 /usr/share/ocsinventory-reports/ocsreports/require/header.php(222): XMLUrlsSerializer->unserialize('<?xml version="...')\n#1 /usr/share/ocsinventory-reports/ocsreports/index.php(44): require('/usr/share/ocsi...')\n#2 {main}\n  thrown in /usr/share/ocsinventory-reports/ocsreports/require/config/XMLUrlsSerializer.php on line 54, referer: https://opendcim.netman.la1.clx.corp/ocsreports/index.php

**To Reproduce**
1. After installation and the initialization of the database config, I receive this error in my logs.

PHP **7.2.24** on a vanilla CentOS 8 distro.

**Comment by gillesdubois** [comment]
Hi,

You are missing php-xml on your distribution.
Install it and restart apache.

Regards,
Gilles.
