### ISSUE TITLE
[BUG]Number of computer by software and number of software is false still not resolved

### ISSUE THREAD

**Issue by alexandremilo** [OCSInventory-NG/OCSInventory-ocsreports#1194]
**OCS Inventory version**
Version : 2.8.1, 2.9

**Describe the bug**
When looking at the software list the number of computers and the number of computers on the software page itself is wrong. It happens after removing a computer from the hardware list.
To give an example we had 20 computers which were supposed to have chrome with a given version while when we clicked on this software we only got 7 computers which truly had it.

**To Reproduce**
Remove one computer from the inventory with a specific software version(there must still be other computers with the same software)
Go to Inventory>All Software and search for it
Click on the Count for the software and the computer doesn't appear anymore
Expected behavior
After having removed the computer the number of software should have been decreased

**Expected behavior**
The bug comes from the fact that the software list still have the entries for the removed computers

**Comment by Lea9250** [comment]
Hi @alexandremilo,

Did you execute the cron_all_software.php script after removing these computers ? This needs to be scheduled to keep the all softwares sections up to date.
Just to make sure, could you execute this query `SELECT * FROM software LEFT JOIN software_name sn ON NAME_ID = sn.ID WHERE sn.NAME like '%chrome%' order by HARDWARE_ID;` on your database ? It would help understanding why these duplicates appear.

Thanks,
Léa

**Comment by alexandremilo** [comment]
These duplicates came from the fact that softwares aren't deleted when a computer is removed from OCS

**Comment by Lea9250** [comment]
That's why you need to run the cron_all_softwares.php regularly, if you don't the All Software section will not display software counts accurately.

Regards,
Léa

**Comment by rayzilt** [comment]
I experience the same issue, even after running cron_all_softwares.php manually (I run it every 3 hours through cron) the entry still exists. See screenshots;

![image](https://user-images.githubusercontent.com/3105311/123471734-88e03c00-d5f6-11eb-8ecc-8101e942cd17.png)

Result after clicking on "1".

![image](https://user-images.githubusercontent.com/3105311/123471857-b331f980-d5f6-11eb-9c28-cbd1304234c4.png)

**Comment by Lea9250** [comment]
Hi,

What version of OCS are you using ? 
Could you run this query : `SELECT software.HARDWARE_ID, COUNT(software.ID) FROM software LEFT JOIN hardware ON software.HARDWARE_ID = hardware.ID WHERE hardware.ID IS NULL GROUP BY software.HARDWARE_ID;`
This will identify removed devices still present in the software table and return their hardware IDs and software counts. 
Did you delete them manually or using the webconsole ?

Regards,
Léa

**Comment by rayzilt** [comment]
I'm running version 2.9
![image](https://user-images.githubusercontent.com/3105311/123694853-24bdb200-d85a-11eb-84fb-611032d2bede.png)

Output of the query:
![image](https://user-images.githubusercontent.com/3105311/123695149-7f570e00-d85a-11eb-97dd-540cce1f869b.png)

I've never removed/deleted devices manually or by using the webconsole. We do sometimes reinstall devices and based on "Serial" and "Macaddress" auto merge. Maybe there is something happening?

**Comment by Lea9250** [comment]
This may happen if merges were done while tables were locked (e.g. during updates), do you confirm that these devices are not present in the webconsole all computers section ? 

If they are not, you can run this query `SELECT CONCAT('DELETE FROM ',TABLE_NAME," WHERE hardware_id  IN ('hID1', hID2, hID3);") FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = 'ocsdb' AND COLUMN_NAME='hardware_id';`
Replace `('hID1', hID2, hID3)` with hardware ids returned on your previous screenshot,  and `ocsdb` with your database name.
This will return a set of queries that you can copy/paste to clean all tables from these entries. 

Let me know if the software counts still do not match then,
Léa

**Comment by rayzilt** [comment]
I can confirm that these hardware ids don't exist in the webconsole section. After running the deletes generated from your query and running the cron_all_software.php resolves the issue.

I'm curious if these queries also resolves the issue for @alexandremilo

Are these queries become a part of cron_all_software.php?

**Comment by Lea9250** [comment]
Ok, glad it worked. And yes, it will be added to the cron_all_softwares.php to avoid similar situations.
I'll wait for confirmation from @alexandremilo that this solution worked for them too.

Thanks for you feedback,
Léa

**Comment by alexandremilo** [comment]
I did resolve the problem so i can't really tell if cron_all_softwares.php does answer the problem. If it does correct the problem for other then it should be ok. Thank you for your answer.

**Comment by Lea9250** [comment]
Glad you sorted it out, I'll close this issue now.

Regards,
Léa
