### ISSUE TITLE
[BUG] No CVE are being added by cron_cve.php

### ISSUE THREAD

**Issue by alexandremilo** [OCSInventory-NG/OCSInventory-ocsreports#1195]
**OCS Inventory version**Version : 2.9

**Describe the bug**
I'm running a local instance of cve search and when using the php cron_cve.php command i get the result "0 cve have been added".

**To Reproduce**
Start the local instance of cve search
Use the command php cron_cve.php

**Expected behavior**
The cve should have been added to ocs database

**Screenshots**
<img width="328" alt="no result" src="https://user-images.githubusercontent.com/80517093/120652341-fb3e8000-c47f-11eb-881e-741f3f0e8d80.PNG">

 Here is my ocs config for cve search
<img width="682" alt="config" src="https://user-images.githubusercontent.com/80517093/120653507-06de7680-c481-11eb-8e2c-4cba69174bcd.PNG">

**Comment by charleneauger** [comment]
Hi @alexandremilo ,

We advise you to configure matching CVE regex with CVE Inventory feature. You can find the documentation here : [CVE Matching expressions](http://wiki.ocsinventory-ng.org/04.Management-console-and-its-advanced-features/CVE-Search-match-regex/)

This feature makes it possible to better match the names or publishers present in OCS with those of CVE Search.

Best regards,
Charlene

**Comment by liedekef** [comment]
While regex pattern matching might be a solution in exceptions, it can't be the generic way to go. I've just set up a cve search server too, and OCSI doesn't even match a single CVE. Meaning that in fact there's no working integration with cvesearch as advertised. If pattern matching is the way to go, can a base file be given to import in OCSI?

**Comment by msx008** [comment]
hello, check if the **software_link** table is filled otherwise run this https://ask.ocsinventory-ng.org/13117/ocs-2-9-software-total-display-0-issue and then run **cron_cve.php**

**Comment by ThomboSupergott** [comment]
Hello msx008,

thanky for your answer. it really seems that i have an issue with the software_link table.
However, OCS does display software in the web-Gui, but  there is an error when running the "cron_all_software.php"

the package 'php-mysql' is installed. OS is debian.

`root@ocsserver:/usr/share/ocsinventory-reports/ocsreports/crontab# php cron_all_software.php
Please wait, software processing is in progress. It could take a few minutes ...
PHP Warning:  mysqli_query() expects parameter 1 to be mysqli, string given in /usr/share/ocsinventory-reports/ocsreports/require/function_commun.php on line 104
PHP Warning:  mysqli_fetch_array() expects parameter 1 to be mysqli_result, null given in /usr/share/ocsinventory-reports/ocsreports/require/softwares/AllSoftware.php on line 126
PHP Warning:  mysqli_query() expects parameter 1 to be mysqli, string given in /usr/share/ocsinventory-reports/ocsreports/require/function_commun.php on line 104
PHP Warning:  mysqli_query() expects parameter 1 to be mysqli, string given in /usr/share/ocsinventory-reports/ocsreports/require/function_commun.php on line 104
PHP Warning:  mysqli_query() expects parameter 1 to be mysqli, string given in /usr/share/ocsinventory-reports/ocsreports/require/function_commun.php on line 104
root@ocsserver:/usr/share/ocsinventory-reports/ocsreports/crontab#
`

Any ideas how to solve this issue ?

**Comment by msx008** [comment]
>  mysqli_query() expects parameter 1 to be mysqli

hello no sorry, 
maybe php version
mine = PHP 7.3.29-1~deb10u1

**Comment by ThomboSupergott** [comment]
Hello msx008, 

thank you for your answer. I have the same php version

> PHP 7.3.29-1~deb10u1 (cli)

**Comment by Math2222** [comment]
Hello, 

For me even if I have my software_link full of softwares my cron_cve.php don't process anything....

/usr/share/ocsinventory-reports/ocsreports/crontab# php7.3 cron_cve.php
Get software publisher ...
Software publisher OK ...
CVE treatment started ...
Please wait, CVE processing is in progress. It could take a few hours
0 CVE has been added to database

**Comment by Math2222** [comment]
Hello again,
I managed to fix my problem, (VULN_CVE_EXPIRE_TIME with wrong value)

**Comment by LMS235** [comment]
Hello,

meanwhile on OCS 2.10.0 and cve-search v4.2.1 but always:

> Get software publisher ...
Software publisher OK ...
CVE treatment started ...
Please wait, CVE processing is in progress. It could take a few hours
0 CVE has been added to database

also if I reset the value of VULN_CVE_EXPIRE_TIME  to 1 hour it makes times 1 - 5 software provider but also with 0 Result (although there are very well CVE here):

> Get software publisher ...
Software publisher OK ...
CVE treatment started ...
Please wait, CVE processing is in progress. It could take a few hours
Processing Adobe softwares ...
Processing Adobe Systems Incorporated softwares ...
Processing Citrix Systems, Inc softwares ...
Processing Citrix Systems, Inc. softwares ...
Processing Fortinet Technologies Inc softwares ...
Processing Mobatek softwares ...
Processing SAP softwares ...
Processing SAP AG softwares ...
Processing SAP SE softwares ...
Processing SoftMaker Software GmbH softwares ...
Processing VMware, Inc. softwares ...
Processing Wondershare softwares ...
0 CVE has been added to database

Currently, the CVE feature is more or less useless. Unfortunately, nowhere is a log written about what the problem actually is.

When i access the CVE server local --> Showing 1 to 50 of 1,247 entries for SAP AG and Showing 1 to 50 of 2,165 entries for SAP SE

Or EXACTLY one software that we use " Citrix Workspace" --> Showing 1 to 50 of 465 entries

means the CVE server works without problems, only OCS can not access it cleanly.

**Comment by LMS235** [comment]
@gillesdubois can you please take a look?

**Comment by LMS235** [comment]
Ping @gillesdubois @damienbelliard @RudyLaurent @charleneauger

**Comment by decoudam2** [comment]
After installing version 2.12, the problem remains the same :

**Comment by LMS235** [comment]
Unfortunately the 2.12.0 is full of bugs, see my messages. I hope here comes as soon as possible a 2.12.1 to fix all this.  

But if you're also already on 2.12.0, can you reproduce this? https://github.com/OCSInventory-NG/OCSInventory-ocsreports/issues/1544

**Comment by decoudam2** [comment]
Hello !

Yes, I'm already on 2.12.0 since yesterday (but still have 2.11.1 in a snapshot).
I'll first try #1519 on 2.12.0 (or 2.11.1) : I need this working.

Then I'll try #1544 and let you know...
Cheers,
Damien
