### ISSUE TITLE
Confused confirmation message when you delete a category of software

### ISSUE THREAD

**Issue by saep-es** [OCSInventory-NG/OCSInventory-ocsreports#120]
The message is "Do you really want to delete?" It is not clear what is going to be deleted. It would be nice to identify exactly what is going to be deleted.

**Comment by MyTheValentinus** [comment]
Hello,
Thank for your contribution.
Have nice day

**Comment by MyTheValentinus** [comment]
Hi,
Dictionnary is deprecated and will be updated, look at https://github.com/OCSInventory-NG/OCSInventory-ocsreports/issues/106
Thanks
