### ISSUE TITLE
[Security] Malware found from Sophos Intercept X (Windows MSI)

### ISSUE THREAD

**Issue by stetze88** [OCSInventory-NG/OCSInventory-ocsreports#1203]
**OCS Inventory version**
Version : 2.9
PHP Version :
Web Server :
Database Server :
Version OCSReports: 7.2.34
Apache/2.4.37 (centos) OpenSSL/1.1.1g mod_perl/2.0.11 Perl/v5.26.3
MariaDB Server version 10.3.28-MariaDB

**Describe the bug**
After upload and Activate the MSI Deployment, our Sophos Intercept X founds malware (Malware detected: 'Mal/Generic-R') in this new package.

If i scan the MSI Package before upload, everything is clean.

**To Reproduce**
I create an MSI Paket with the new Feature.
Deployment -> Build -> Windows -> Install / Uninstall -> Install MSI application

**Expected behavior**
How can this happen? Is this an false positve?
Why are the hashes of the install files on different computers not the same?

**Screenshots**
![Screenshot 2021-06-14 125106](https://user-images.githubusercontent.com/73733823/121881832-0f9c3b80-cd10-11eb-87dc-0c4b037d56a7.jpg)
![Screenshot_2](https://user-images.githubusercontent.com/73733823/121881835-1034d200-cd10-11eb-8f34-a978aa0279dc.jpg)
![Screenshot_3](https://user-images.githubusercontent.com/73733823/121881838-1034d200-cd10-11eb-9675-18d757ee9ff0.jpg)
![Screenshot 2021-06-14 125502](https://user-images.githubusercontent.com/73733823/121881839-1034d200-cd10-11eb-984b-5106f25e8cec.jpg)
![Screenshot 2021-06-14 125602](https://user-images.githubusercontent.com/73733823/121881840-10cd6880-cd10-11eb-84cc-1f6f1566b97c.jpg)

**Log file (optional)**
Apache / PHP / System log if needed

**Comment by gillesdubois** [comment]
Hi @stetze88 

The packager "re-package" the application and add a file named info. Adding this file to the archive will most likely change the checksum of the initial uploaded file. You can get the package by going on your server in : "/var/lib/ocsinventory-reports/download/<packagetimestamp>"

To be honest, the only thing I see is a false positive. It could come from the fact that we archive / fragment the package and could be interpreted as a FUD attempt.

I would like to try on my side, is the MSI you try to install easily findable on internet or is that some kind of enterprise package ?

Regards,
Gilles.

**Comment by stetze88** [comment]
Hi @gillesdubois 

it's a Custom MSI from our AnyDesk Enterprise Account.
Via virustotal the MSI direct from AnyDesk is clean. 
The Zip Version from OCS Inventory is flagged as malicious. -> Only from Sophos.

Should I send the file to Sophos for checking?
https://support.sophos.com/support/s/filesubmission?language=en_US

![Screenshot 2021-06-14 150658](https://user-images.githubusercontent.com/73733823/121897026-3ebba880-cd22-11eb-8659-93ed4ae55fe3.jpg)
![Screenshot 2021-06-14 150719](https://user-images.githubusercontent.com/73733823/121897031-3f543f00-cd22-11eb-870b-86c79bef4ea7.jpg)

**Comment by gillesdubois** [comment]
I think that sending it to Sophos could be a nice thing indeed.
If the detection rate was abose 15-20/60 we would have checked the source but it seems like a realy isolated detection.

If you have a feedback from Sophos, we'll be glad to discuss about it with you :) 

Regards,
Gilles.

**Comment by stetze88** [comment]
I'll be in touch.
