### ISSUE TITLE
[BUG] RPM package OCS Inventory is not signed 

### ISSUE THREAD

**Issue by fourstepper** [OCSInventory-NG/OCSInventory-ocsreports#1207]
When trying to upgrade via yum on CentOS 7, I get the following error:

![image](https://user-images.githubusercontent.com/49439044/122763755-fe6aa600-d29e-11eb-9909-ec5affed199f.png)

Thought you would like to know

**Comment by kapouik** [comment]
I have re upload the RPM with the correct signature. 

It may work correctly now.

**Comment by fourstepper** [comment]
Thanks for the fast response.
