### ISSUE TITLE
Show/hide the SUP column on the cadegories table doesn't work

### ISSUE THREAD

**Issue by saep-es** [OCSInventory-NG/OCSInventory-ocsreports#121]
The page is on Manage>Dictionary>Categories. When you try to show/hide the SUP column, actually the ID column is showed/hidden.

**Comment by gillesdubois** [comment]
Hi,

Check this issue, the dictionary feature is not updated anymore and will be renewed in the near future.

https://github.com/OCSInventory-NG/OCSInventory-ocsreports/issues/106

Regards,
Gilles Dubois.
