### ISSUE TITLE
[BUG] OCSinvetory 2.0.9 don't show all softwares table 

### ISSUE THREAD

**Issue by ITTechSintel** [OCSInventory-NG/OCSInventory-ocsreports#1213]
**OCS Inventory version**
Version : 2.0.9
![image](https://user-images.githubusercontent.com/86322625/122986334-b23e6500-d375-11eb-801e-19675bfdc777.png)

**Describe the bug**
We update our server to 2.0.9 version, after that out machines won't shows table about "ALL SOFTWARE"

**To Reproduce**
1. Go to 'OCS inventory home.'
2. Click on 'Inventory'
3. Select 'All Softwares'

**Expected behavior**
All software need to be show

**Screenshots**
![image](https://user-images.githubusercontent.com/86322625/122986389-c5513500-d375-11eb-9c69-fe2e7be7a246.png)

**Log file (optional)**
If need i can attach it after.

**Comment by charleneauger** [comment]
Hi @ITTechSintel ,

Since version 2.9, the all software page is populated by the crontab cron_all_software.php in ocsreports/crontab folder. 
Just run `php cron_all_software.php`.

Best regards,
Charlene
