### ISSUE TITLE
[BUG] agent version 2.9 too recent for server 2.9

### ISSUE THREAD

**Issue by matix42** [OCSInventory-NG/OCSInventory-ocsreports#1215]
**OCS Inventory version**
Version : 2.9

**Describe the bug**
When using agent windows 2.9 (x86 and x64) : message in the activity.log on the server : 
Bad agent or agent version too recent for server !!

It's works fine with agent version 2.8

**Log file (optional)**
activity.log : 
Wed Jun 23 16:40:44 2021;22455;515;HOST;192.168.XXX.XXX;OCS-NG_WINDOWS_AGENT_v2.9.0.0;end;bad_request
Wed Jun 23 16:42:50 2021;22455;400;HOST;192.168.XXX.XXX;OCS-NG_WINDOWS_AGENT_v2.9.0.0;useragent;Bad agent or agent version too recent for server !!
Wed Jun 23 16:42:50 2021;22455;106;HOST;192.168.XXX.XXX;OCS-NG_WINDOWS_AGENT_v2.9.0.0;prolog;stopped by module
Wed Jun 23 16:42:50 2021;22455;515;HOST;192.168.XXX.XXX;OCS-NG_WINDOWS_AGENT_v2.9.0.0;end;bad_request

Agent log : 
ERROR *** AGENT => Failed to send Prolog <HTTP Status Code #400>

**Comment by matix42** [comment]
![image](https://user-images.githubusercontent.com/79908641/123119343-b933a900-d443-11eb-830e-b0e9a5e0d45b.png)

**Comment by charleneauger** [comment]
Hi @matix42 ,

I think your server didn't update correctly. Can you verify the server version in the following file line 42 : `/usr/local/share/perl/5.30.0/Apache/Ocsinventory.pm` ?

Regards,
Charlene

**Comment by matix42** [comment]
Hi, 
Actualy, I found the file in that path : /usr/share/perl5/vendor_perl/Apache/Ocsinventory.pm

I've got that at line 42 :
$Apache::Ocsinventory::VERSION = '2.9';

The update was done using the repo : 
name=OCS Inventory NG repository for Enterprise Linux 8 - $basearch
baseurl=http://rpm.ocsinventory-ng.org/enterprise/8/$basearch/

**Comment by charleneauger** [comment]
Hi @matix42 ,

Could you try to restart apache service ? 

Regards,
Charlene

**Comment by matix42** [comment]
Hi Charlène,

I restarted Apache, but unfortunately the issue is still there (The server has been rebooted as well).

Where is stored the client version compatibily on the server ? so I can check if the version is correct.

Thanks for your help

**Comment by matix42** [comment]
I found files in two differents paths :
- /usr/local/share/perl5/Apache/Ocsinventory : contains old files but are used
- /usr/share/perl5/vendor_perl/Apache/Ocsinventory : contains new files but aren't used

Now, for test purpose, I moved new files in the used path, and it works

I didn't find where can I change the path in a config files.

Ocs inventory was installed and updated everytime using the repo...

**Comment by charleneauger** [comment]
Hi @matix42 ,

RPM repositories has been updated with the latest OCS Inventory version. Please update.

Best regards,
Charlene
