### ISSUE TITLE
Hardcoded message when you delete a computer

### ISSUE THREAD

**Issue by saep-es** [OCSInventory-NG/OCSInventory-ocsreports#122]
We get the following message: "name_of_machine?". As this message is in the sourcecode, we can't translate it.

**Comment by MyTheValentinus** [comment]
Hello @saep-es,
Thank for your contribution.

**Comment by gillesdubois** [comment]
Hi @saep-es ,

Thx for your report, a fix is now available.

Regards,
Gilles Dubois.
