### ISSUE TITLE
[BUG] Failed to send Inventory <HTTP Status Code #500>

### ISSUE THREAD

**Issue by vacand** [OCSInventory-NG/OCSInventory-ocsreports#1224]
**OCS Inventory version**
Version : 3.10.0-862.9.1.el7.x86_64

**Describe the bug**
After Upgrade of OCS Server some Windows agents are not sending anymore the inventory with the following error:

Failed to send Inventory <HTTP Status Code #500>

Others are working fine.
Agent Version: 2.3.1.0

Can you please help me to solve this issue?

Already check httpd error log and the recursive error that i can find is the following:

DBD::mysql::db do failed: Table 'ocsweb.softwares' doesn't exist at /usr/local/share/perl5/Apache/Ocsinventory/Server/Inventory/Cache.pm line 79.

Thanks!

**Comment by vacand** [comment]
Please.. still have this issue

**Comment by gillesdubois** [comment]
Hi,

Can you send me the content of the following file ? /usr/local/share/perl5/Apache/Ocsinventory.pm
Imo, your server didn't fully update and you are still on the all communication server code base.

Regards,
Gilles.

**Comment by vacand** [comment]
Hi Gilles,
thanks for your feedback, in attach requested file.
[Ocsinventory.zip](https://github.com/OCSInventory-NG/OCSInventory-ocsreports/files/6765267/Ocsinventory.zip)

Let me know if u need something else 

Thanks!!!

**Comment by gillesdubois** [comment]
Hi,

The communication server didn't upgrade properly : 
```
$Apache::Ocsinventory::VERSION = '2.3';
```

If you performed the update to the latest version you should be in the 2.9.

I recommend you to check your installation and try to reapply the 2.9 update.

Regards,
Gilles.

**Comment by vacand** [comment]
Hi,
just tried to re-apply the 2.9 versione, nothing changed, in that file i can see always the sam version $Apache::Ocsinventory::VERSION = '2.3'; , and the issue is still active.
I can see that the update was OK from the log lines.

**Comment by gillesdubois** [comment]
The communication server should also update.

Could you run the following command and give me the output ? 

find / -type f -name Ocsinventory.pm

I suspect that you have more than one communication server installation on the same server.
If you see multiple result from this command it'll mean the update process failed to get the old version path.

Thanks,
Gilles.

**Comment by vacand** [comment]
Here you can find the output of the command, it seems like you told... how can i solve it?


[root@pmhqocs02 ~]# find / -type f -name Ocsinventory.pm
find: ‘/proc/28173’: No such file or directory
find: ‘/proc/28233’: No such file or directory
/root/perl5/lib/perl5/Apache/Ocsinventory.pm
/root/OCSNG_UNIX_SERVER_2.5/Apache/Ocsinventory.pm
/root/OCSNG_UNIX_SERVER_2.5/Apache/blib/lib/Apache/Ocsinventory.pm
/usr/local/share/perl5/Apache/Ocsinventory.pm
/home/OCSNG_UNIX_SERVER_2.8/Apache/Ocsinventory.pm
/home/OCSNG_UNIX_SERVER_2.8/Apache/blib/lib/Apache/Ocsinventory.pm
[root@pmhqocs02 ~]#

**Comment by gillesdubois** [comment]
If you check there two file : 
/root/perl5/lib/perl5/Apache/Ocsinventory.pm
/usr/local/share/perl5/Apache/Ocsinventory.pm

One of them should be marked as the 2.8 version.

Regards,
Gilles.

**Comment by vacand** [comment]
Yes i can confirm that in /root/perl5/lib/Apache/Ocsinventory.pm I can see 

$Apache::Ocsinventory::VERSION = '2.8';
$Apache::Ocsinventory::BUILD_VERSION = '760';
$XML::Simple::PREFERRED_PARSER = 'XML::Parser';

What can i do to delete the old one?

**Comment by gillesdubois** [comment]
Imo if you try to update again you'll face the same issue.

Could you move the Ocsinventory.pm with the old version alongside the Ocsinventory folder that is present in the same directory ? Then restart apache and make sure everything is alright.

Thanks.

Regards,
Gilles.

**Comment by vacand** [comment]
Hi,
just tried but Apache is not able to start now:

[root@pmhqocs02 ~]# sudo service httpd start
Redirecting to /bin/systemctl start httpd.service
Job for httpd.service failed because the control process exited with error code.                                                                                                                                                              See "systemctl status httpd.service" and "journalctl -xe" for details.
[root@pmhqocs02 ~]# systemctl status httpd.service
● httpd.service - The Apache HTTP Server
   Loaded: loaded (/usr/lib/systemd/system/httpd.service; enabled; vendor preset                                                                                                                                                             : disabled)
   Active: failed (Result: exit-code) since Thu 2021-07-08 06:43:09 CEST; 19s ag                                                                                                                                                             o
     Docs: man:httpd(8)
           man:apachectl(8)
  Process: 30862 ExecStop=/bin/kill -WINCH ${MAINPID} (code=exited, status=1/FAI                                                                                                                                                             LURE)
  Process: 30448 ExecReload=/usr/sbin/httpd $OPTIONS -k graceful (code=exited, s                                                                                                                                                             tatus=0/SUCCESS)
  Process: 30859 ExecStart=/usr/sbin/httpd $OPTIONS -DFOREGROUND (code=exited, s                                                                                                                                                             tatus=1/FAILURE)
 Main PID: 30859 (code=exited, status=1/FAILURE)

Jul 08 06:43:09 pmhqocs02.hq.corp.percassi.com systemd[1]: Starting The Apach...
Jul 08 06:43:09 pmhqocs02.hq.corp.percassi.com httpd[30859]: [Thu Jul 08 06:4...
Jul 08 06:43:09 pmhqocs02.hq.corp.percassi.com httpd[30859]: [Thu Jul 08 06:4...
Jul 08 06:43:09 pmhqocs02.hq.corp.percassi.com httpd[30859]: [Thu Jul 08 06:4...
Jul 08 06:43:09 pmhqocs02.hq.corp.percassi.com systemd[1]: httpd.service: mai...
Jul 08 06:43:09 pmhqocs02.hq.corp.percassi.com kill[30862]: kill: cannot find...
Jul 08 06:43:09 pmhqocs02.hq.corp.percassi.com systemd[1]: httpd.service: con...
Jul 08 06:43:09 pmhqocs02.hq.corp.percassi.com systemd[1]: Failed to start Th...
Jul 08 06:43:09 pmhqocs02.hq.corp.percassi.com systemd[1]: Unit httpd.service...
Jul 08 06:43:09 pmhqocs02.hq.corp.percassi.com systemd[1]: httpd.service failed.
Hint: Some lines were ellipsized, use -l to show in full.
[root@pmhqocs02 ~]#
[root@pmhqocs02 ~]#
[root@pmhqocs02 ~]# systemctl status httpd.service
● httpd.service - The Apache HTTP Server
   Loaded: loaded (/usr/lib/systemd/system/httpd.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Thu 2021-07-08 06:43:09 CEST; 24s ago
     Docs: man:httpd(8)
           man:apachectl(8)
  Process: 30862 ExecStop=/bin/kill -WINCH ${MAINPID} (code=exited, status=1/FAILURE)
  Process: 30448 ExecReload=/usr/sbin/httpd $OPTIONS -k graceful (code=exited, status=0/SUCCESS)
  Process: 30859 ExecStart=/usr/sbin/httpd $OPTIONS -DFOREGROUND (code=exited, status=1/FAILURE)
 Main PID: 30859 (code=exited, status=1/FAILURE)

Jul 08 06:43:09 pmhqocs02.hq.corp.percassi.com systemd[1]: Starting The Apache HTTP Server...
Jul 08 06:43:09 pmhqocs02.hq.corp.percassi.com httpd[30859]: [Thu Jul 08 06:43:09.400210 2021] [alias:warn] [pid 30859] AH00671: The Alias directive in /etc/httpd/conf.d/ocsinventory-reports.conf at line 23 will probabl... earlier Alias.
Jul 08 06:43:09 pmhqocs02.hq.corp.percassi.com httpd[30859]: [Thu Jul 08 06:43:09.400473 2021] [alias:warn] [pid 30859] AH00671: The Alias directive in /etc/httpd/conf.d/ocsinventory-reports.conf at line 102 will probab... earlier Alias.
Jul 08 06:43:09 pmhqocs02.hq.corp.percassi.com httpd[30859]: [Thu Jul 08 06:43:09.400496 2021] [alias:warn] [pid 30859] AH00671: The Alias directive in /etc/httpd/conf.d/ocsinventory-reports.conf at line 120 will probab... earlier Alias.
Jul 08 06:43:09 pmhqocs02.hq.corp.percassi.com systemd[1]: httpd.service: main process exited, code=exited, status=1/FAILURE
Jul 08 06:43:09 pmhqocs02.hq.corp.percassi.com kill[30862]: kill: cannot find process ""
Jul 08 06:43:09 pmhqocs02.hq.corp.percassi.com systemd[1]: httpd.service: control process exited, code=exited status=1
Jul 08 06:43:09 pmhqocs02.hq.corp.percassi.com systemd[1]: Failed to start The Apache HTTP Server.
Jul 08 06:43:09 pmhqocs02.hq.corp.percassi.com systemd[1]: Unit httpd.service entered failed state.
Jul 08 06:43:09 pmhqocs02.hq.corp.percassi.com systemd[1]: httpd.service failed.
Hint: Some lines were ellipsized, use -l to show in full.

**Comment by vacand** [comment]
Hi, 
SOLVED
were missing PERL SWITCH Module, after install that it worked after the re-configuration of zocsinventory.conf
