### ISSUE TITLE
Active Directory authentication (CONEX_ROOT_DN password lenght)

### ISSUE THREAD

**Issue by tontonrico** [OCSInventory-NG/OCSInventory-ocsreports#1225]
**OCS Inventory version**
Version : 2.8.1

it seems the password used in CONEX_ROOT_PW is limited in number of characters. The password is 25 characters and there is an error in the authentication. 
![image](https://user-images.githubusercontent.com/15142726/124117915-fc5bd080-da70-11eb-84fb-8c30f2885013.png)

If I use another account (mine for example) in CONEX_ROOT_DN with my password (less characters) the authentication works correctly.

How many characters are allowed in the CONEX_ROOT_PW ? 
How to change it if possible ?

Edit : maybe the problem is the characters used in the CONEX_ROOT_PW password are not allowed (mine contains some % and other specials characters). 

Could you tell me if there are unallowed characters for the CONEX_ROOT_PW password ?

**Comment by Lea9250** [comment]
Hi @tontonrico,
CONEX_ROOT_PW max length is 200 chars and special chars will get encoded as html entities in database, which is most likely the reason why this error shows up. If possible, give it a try without special chars (such as & or quote symbols for example).

Regards,
Léa

**Comment by tontonrico** [comment]
thanks for the reply. I changed the password which contained some specials chars, it works correctly now.
