### ISSUE TITLE
[BUG]Deployment not work in 2.9

### ISSUE THREAD

**Issue by nameci65** [OCSInventory-NG/OCSInventory-ocsreports#1226]
Hi all, I have installed ocs server 2.9-nightly-2021-05-21. The deployment function has stop to work. I lost many time to search into log without success and finaly I have looked at mysql table download_enable and I saw that fields INFO_LOC and PACK_LOC were not initialize. I have update manualy and all began to run correctly. I don't know if this is the right place to post my comment.
Regards
 Roberto

**Comment by charleneauger** [comment]
Hi @nameci65 ,

Thank you for your report. This bug has been fixed with this PR #1193 .
Install the latest nightly version to fix it ;-)

Best regards,
Charlene
