### ISSUE TITLE
CAS Error

### ISSUE THREAD

**Issue by LANFDETROY** [OCSInventory-NG/OCSInventory-ocsreports#1229]
Since the migration from OCs 2.7 to 2.9, CAS authentication no longer works.
I have modified the cas.config.php file? I have installed phpcas
Is there anything else to do?
In the var.php file I can not find the type of authentication by CAS except SSO or LDAP ?

**Comment by charleneauger** [comment]
Hi @LANFDETROY ,

Recently, a PR has been merged regarding the CAS authentication.
https://github.com/OCSInventory-NG/OCSInventory-ocsreports/pull/1348

You can installed a nightly version to have the fix.

Best regards,
Charlene
