### ISSUE TITLE
TAG fields overwritten when adding a "note"

### ISSUE THREAD

**Issue by zxtury** [OCSInventory-NG/OCSInventory-ocsreports#123]
Hi..!!

Basically as the title sais, everytime I write a "Note", my "TAG fields" got overwritten whit some data.

AFTER
![2016-08-23_10-14-02](https://cloud.githubusercontent.com/assets/19822966/17906920/25dfe090-692e-11e6-8b34-e18d3b00fde0.png)

BEFORE
![2016-08-23_10-18-59](https://cloud.githubusercontent.com/assets/19822966/17906924/2d19cf38-692e-11e6-890b-080ea4befd7a.png)

Even if theres a previous data, also it gets overwritten.

PS. Sorry for my english skills..! =)

**Comment by gillesdubois** [comment]
Hi,

I will reproduce this bug as soon as possible.
You will be notified on this issue if a fix is available.

Regards,
Gilles Dubois.
