### ISSUE TITLE
[BUG] Duplicate Page Blank 2.9

### ISSUE THREAD

**Issue by cirvent** [OCSInventory-NG/OCSInventory-ocsreports#1231]
**OCS Inventory version**
Version : 2.9

**Describe the bug**
I have this error in the apache2 logs: 

[Tue Jul 06 21:52:09.628266 2021] [:error] [pid 49072] [client 10.10.204.46:64717] PHP Fatal error:  Call to undefined function mysqli_fetch_all() in /usr/share/ocsinventory-reports/ocsreports/plugins/main_sections/ms_doubles/ms_doubles.php on line 317, referer: https://ocsinventory.domain.biz/index.php?function=admin_double

which causes a blank page

**To Reproduce**
Go to Manage menu and Duplicate sub-menu

**Screenshots**
![image](https://user-images.githubusercontent.com/16097158/124671956-8d3e0c00-deb6-11eb-8ee1-eaca94ff3edc.png)

![image](https://user-images.githubusercontent.com/16097158/124672055-b2cb1580-deb6-11eb-9481-d3f336228d0c.png)

**Comment by cirvent** [comment]
I find the problem:
mysqli_fetch_all is only available if mysqli is compiled to use mysqlnd instead of libmysql (see its doc).

A correction would be to add this code:
`if (!function_exists('mysqli_fetch_all')) {
    function mysqli_fetch_all(mysqli_result $result) {
        $rows = [];
        while ($row = mysqli_fetch_assoc($result)) {
            $rows[] = $row;
        }
        return $rows;
    }
}`

result:
![image](https://user-images.githubusercontent.com/16097158/125135841-f5d0f700-e109-11eb-9a75-e9d2fcdf7467.png)

now I have another problem, the 709 false duplicates! 

Cirvent

**Comment by charleneauger** [comment]
Hi @cirvent ,

The false duplicate entries has been fixed recently with the PR #1228 

Best regards,
Charlene
