### ISSUE TITLE
[BUG] Wrong Count under the list of all software

### ISSUE THREAD

**Issue by 90er** [OCSInventory-NG/OCSInventory-ocsreports#1233]
**OCS Inventory version**
Version : 2.9

**Describe the bug**
The count under the list of all software (https://<Server>/ocsreports/index.php?function=visu_all_soft) displays wrong values.
It seems that the clearing of old software versions / installations stopped working.

**To Reproduce**
1. Go to https://<Server>/ocsreports/index.php?function=visu_all_soft
2. Search for an often used software like Google Chrome
3. Now i can see very much rows (versions i already updated a long time ago) and the column "Count" also shows very much clients.

**Expected behavior**
The expected behavior is, that i only see the current state (maybe Google Chrome installed in 3 versions and the sum of the entrys at the "Count" column has to be the overall sum).

**Hint**
- I have a overall of 61 computers with Google Chrome.
- The Linux root user has the following cronjob: `30 * * * * cd /usr/share/ocsinventory-reports/ocsreports/crontab/ && php cron_all_software.php`
-  Running this cronjob manually ends up with no error after a few seconds: `Please wait, software processing is in progress. It could take a few minutes ...`

**Screenshots**
![2021-07-16_13h16_52](https://user-images.githubusercontent.com/17730136/125939596-f7ff4e80-684f-4157-9314-940be39ae9f6.png)

(any many more rows)

**Log file (optional)**
Apache / PHP / System log if needed

**Comment by charleneauger** [comment]
Hi @90er ,

This bug has been fixed with PR #1223.

Best regards,
Charlene

**Comment by 90er** [comment]
> Hi @90er ,
> 
> This bug has been fixed with PR #1223.
> 
> Best regards,
> Charlene

Hi @charleneauger,

thanks for your message.

I patched my files as you mentioned above (https://github.com/OCSInventory-NG/OCSInventory-ocsreports/pull/1223/files) but it didn't work.

I manually ran the cronjob `cd /usr/share/ocsinventory-reports/ocsreports/crontab/ && php cron_all_software.php` but nothing happened. Restarting the webserver also didn't work.

Thanks for your help.

**Comment by 90er** [comment]
> > Hi @90er ,
> > This bug has been fixed with PR #1223.
> > Best regards,
> > Charlene
> 
> Hi @charleneauger,
> 
> thanks for your message.
> 
> I patched my files as you mentioned above (https://github.com/OCSInventory-NG/OCSInventory-ocsreports/pull/1223/files) but it didn't work.
> 
> I manually ran the cronjob `cd /usr/share/ocsinventory-reports/ocsreports/crontab/ && php cron_all_software.php` but nothing happened. Restarting the webserver also didn't work.
> 
> Thanks for your help.

I manually ran the cleanup query, but it's an empty result.
There should be approximately 40 installations of Google Chrome (as an example).

```sql
MariaDB [ocsweb]> SELECT software.HARDWARE_ID FROM `software` LEFT JOIN `hardware` ON software.HARDWARE_ID = hardware.ID WHERE hardware.ID IS NULL GROUP BY software.HARDWARE_ID;
Empty set (0.02 sec)
```

![image](https://user-images.githubusercontent.com/17730136/126129046-a663f5a1-1f1e-410a-a971-88e93f234d8e.png)

**Comment by charleneauger** [comment]
@90er , OK. If you click on the count number, do you have the correct result displayed on the multisearch ? 

I think you still have old ghost versions of Google Chrome present on your computers (maybe the registry keys still present). Suddenly, the windows agent returns them as software installed when they are no longer.
Because during the inventory, all the software of the machine is deleted before being reinjected.

Regards,
Charlene

**Comment by 90er** [comment]
> @90er , OK. If you click on the count number, do you have the correct result displayed on the multisearch ?
> 
> I think you still have old ghost versions of Google Chrome present on your computers (maybe the registry keys still present). Suddenly, the windows agent returns them as software installed when they are no longer.
> Because during the inventory, all the software of the machine is deleted before being reinjected.
> 
> Regards,
> Charlene

Thanks for your reply.

You're right, in the computer details e. g. Google Chrome is listed multiple times.
In Windows 10 Apps and Features Google Chrome is only listed with the current version.

I have nothing special configured so i will check the self configured OCS Inventory Agent (2.6)  and will do some tests.

**Comment by Lea9250** [comment]
Hi @90er,
Do you have any update on this matter ?

Regards,
Léa

**Comment by charleneauger** [comment]
Hi,

Since there is no anwser, I'll now close the issue.

Regards,
Charlene.

**Comment by raulids90** [comment]
Minha contagem de software não estava sendo apresentada, e o comando resolveu o meu problema. Obrigado à todos!! OCS Inventory 2.9.1

 cd /usr/share/ocsinventory-reports/ocsreports/crontab/ && php cron_all_software.php
