### ISSUE TITLE
"Error check your internet connection" when create profile

### ISSUE THREAD

**Issue by cb58** [OCSInventory-NG/OCSInventory-ocsreports#124]
Hi,

Create profile screenshot : 

![2016-08-24 14_47_36-ocs inventory](https://cloud.githubusercontent.com/assets/20222556/17931487/0c8df76a-6a0c-11e6-8bcb-d20faa97017f.png)

Apache error.log :
> Wed Aug 24 14:16:57.606315 2016] [:error] [pid 9550] [client xx.xx.xx.xx:60393] PHP Fatal error:  **Call to a member function g() on null** in /usr/share/ocsinventory-reports/ocsreports/plugins/main_sections/ms_users/lib/profile_functions.php on line 15, referer: https://ocsserver/ocsreports/index.php?function=admin_add_profile

A patch is attached :
[profile_functions.php.diff.txt](https://github.com/OCSInventory-NG/OCSInventory-ocsreports/files/434728/profile_functions.php.diff.txt)

Same screenshot with this patch :
![2016-08-24 14_48_05-ocs inventory](https://cloud.githubusercontent.com/assets/20222556/17931610/a11e1cac-6a0c-11e6-8e57-92aeffc6c7df.png)

Regards

**Comment by gillesdubois** [comment]
Hi,

A commit will be made asap on the master branch.
Thanks for your report and your fix 👍 

Regards,
Gilles Dubois.
