### ISSUE TITLE
[BUG] validate package error 408

### ISSUE THREAD

**Issue by ronacher** [OCSInventory-NG/OCSInventory-ocsreports#1243]
**OCS Inventory version**
Version : 2.9.1

I have recently updated to version 2.9.1
I've been uploading packages for a few days and hadn't had any problems so far. The only thing I've done since it worked until now is install the dependencies for cve-search and mongodb.
When I go to validate the package it hangs and does nothing. In log it gives an error 408

![image](https://user-images.githubusercontent.com/88554890/128549545-3676dabd-baec-4bbd-a642-d2e575470179.png)

![image](https://user-images.githubusercontent.com/88554890/128549579-9220f7c1-bc9f-4c39-ad14-1a0e9beb6924.png)

Thanks a lot.

**Comment by ronacher** [comment]
the problem is not in the validation, but in the activation. If I disable automatic activation and do it manually it works fine.

![image](https://user-images.githubusercontent.com/88554890/128554145-2e8b1609-acec-4f26-9501-ca62709c02ac.png)

**Comment by Lea9250** [comment]
Hi @ronacher,
Is there anything in your apache error log file ?

Regards,
Léa
