### ISSUE TITLE
[BUG] All computers page is empty (again?)

### ISSUE THREAD

**Issue by neves01** [OCSInventory-NG/OCSInventory-ocsreports#1244]
**OCS Inventory version**
Version : 2.9

**Describe the bug**
The option "All computers" is empty, even with the addition of the archive column in the hardware table (https://github.com/OCSInventory-NG/OCSInventory-ocsreports/issues/1119).

**To Reproduce**

1. Login to OCS Inventory
2. Click "All computers"
3. See empty list

**Expected behavior**
All computers page should show all computers

**Screenshots**
![ocs_bug](https://user-images.githubusercontent.com/7121222/128560913-b68fc4c9-b1c5-4d1b-a44f-818e6166d9a6.png)

**Comment by pchamo** [comment]
I don't have that issue.

**Comment by Lea9250** [comment]
Hi @neves01,
If the archive field was missing at first, did you have any trouble adding it ?
Do you get any errors on your apache log file ?

Regards,
Léa
