### ISSUE TITLE
ipdiscover-util.pl changed

### ISSUE THREAD

**Issue by coelhu** [OCSInventory-NG/OCSInventory-ocsreports#1251]
I would like to discover devices on various networks that don’t have an active OCS agent

The wiki says that it is possible to use **ipdiscover-util.pl** like this to scan and add devices to the OCS database:

`perl ipdiscover-util.pl -network=10.1.1.0/24 -scantype=ping`

But the current version 2.9 **ipdiscover-util.pl** does not have these options (scantype, network)

Is there another way to discovery devices in various networks that don't have an OCS  agent?

[wiki reference](https://wiki.ocsinventory-ng.org/06.Network-Discovery-with-OCS-Inventory-NG/Using-IP-discovery-feature/)

**Comment by StCyr** [comment]
I think it's back in version 2.9.1

**Comment by charleneauger** [comment]
Hi @coelhu ,

The options has been added on 2.9.1.

Best regards,
Charlene
