### ISSUE TITLE
Log Apache2 - Perl

### ISSUE THREAD

**Issue by k7NoName** [OCSInventory-NG/OCSInventory-ocsreports#126]
Hi,
Error
Wide character in print at /usr/local/share/perl/5.20.2/Apache/Ocsinventory/Server/System.pm line 252.
day 10 to 50 times
With what it can be connected ?

**Comment by k7NoName** [comment]
[My manual settings](http://iqadm.ru/blog/unix/10.html) and Version server, agent =)

**Comment by gillesdubois** [comment]
Hi,

This is message come from this line of code which just print in log : 
`print $LOG localtime().";$$;$code;$DeviceID;$ipaddress;".&_get_http_header('User-agent',$Apache::Ocsinventory::CURRENT_CONTEXT{'APACHE_OBJECT'}).";$phase;".($comment?$comment:"")."\n";`

The file handle for log has not been declared to accommodate sent data
This warning can come from specials characters in your computer infos which are used on this line.

Anyway, that won't impact your server / inventory.
The next ocs server version added a lot of control for these warnings.

Regards,
Gilles Dubois.

**Comment by k7NoName** [comment]
Thank you!
