### ISSUE TITLE
[BUG] OCS unable to submit inventories to remote DB

### ISSUE THREAD

**Issue by hgpit** [OCSInventory-NG/OCSInventory-ocsreports#1262]
**OCS Inventory version**
Version : 2.91

**Describe the bug**
OCS inventories are not being submitted to the DB when it is not on the localhost (the log appears to show OCS is trying to connect to the MariaDB server on a local socket?).

**To Reproduce**
1. Move DB to a separate server

**Expected behavior**
OCS should be using the credentials configured in '**/etc/httpd/conf.d/z-ocsinventory-server.conf**' and/or '**/usr/share/ocsinventory-reports/ocsreports/dbconfig.inc.php**' to connect to the external database.

**Log file (optional)**
Error reported in activity.log:
Tue Sep 28 14:13:59 2021;6028;521;NA;10.11.36.142;OCS-NG_WINDOWS_AGENT_v2.9.0.0;database_connect;Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)
Tue Sep 28 14:13:59 2021;6028;505;NA;10.11.36.142;OCS-NG_WINDOWS_AGENT_v2.9.0.0;handler;Database connection
Tue Sep 28 14:14:41 2021;2688;521;NA;10.11.13.105;OCS-NG_WINDOWS_AGENT_v2.9.0.0;database_connect;Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)
Tue Sep 28 14:14:41 2021;2688;505;NA;10.11.13.105;OCS-NG_WINDOWS_AGENT_v2.9.0.0;handler;Database connection
Tue Sep 28 14:14:43 2021;6028;521;NA;10.11.22.126;OCS-NG_WINDOWS_AGENT_v2.9.0.0;database_connect;Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)
Tue Sep 28 14:14:43 2021;6028;505;NA;10.11.22.126;OCS-NG_WINDOWS_AGENT_v2.9.0.0;handler;Database connection

Please can someone explain what I am doing wrong?

This server/setup is fine when the DB is located/hosted on the localhost, but I need to offload it to another DB server.
Also, the GLPI OCS plugin can speak to the DB server successfully and the OCSreports web GUI also is fine. It's just the actual submission of received inventories which appear to fail.

Thanks

**Comment by hgpit** [comment]
Typical, I spend hours trying to fix it - decide to raise a ticket, then fix it myself :)

It appears that '**zz-ocsinventory-restapi.conf**' also needs editing with the DB credentials.
In my defence, there is no mention of this config file here: https://ask.ocsinventory-ng.org/8241/cant-write-in-directory-on-dbconfig-inc-php

May I suggest the guide is updated with this information?

Thanks.

**Comment by charleneauger** [comment]
Hi @hgpit ,

Thanks for your reports, the `zz-ocsinventory-restapi.conf` is mentionned on the REST API documentation : [Rest API - Configuration](http://wiki.ocsinventory-ng.org/11.Rest-API/Configuration/)

Best regards,
Charlene
