### ISSUE TITLE
[BUG] security issues

### ISSUE THREAD

**Issue by Mayfly277** [OCSInventory-NG/OCSInventory-ocsreports#1267]
Hello,
I found some security issue on the OCSInventory report product.
Where should i put the information about theses issues ? Do you have an email contact or i just open an issue on github ?
regards

**Comment by gillesdubois** [comment]
Hi @Mayfly277 

Thanks for your report.

Could you send a mail to contact@ocsinventory-ng.org with the information ?
We will continue this discussion by mail :)

Regards,
Gilles.

**Comment by Mayfly277** [comment]
Hello, a week pass and i have no answer to my mails. 
The mail come back with this information : 

"This is the mail system at host ocs.ocsinventory-ng.org.

I'm sorry to have to inform you that your message could not be delivered to one or more recipients. It's attached below.

For further assistance, please send mail to postmaster.

If you do so, please include this problem report. You can delete your own text from the attached returned message.

                   The mail system

<*redacted*> (expanded from <contact@ocsinventory-ng.org>): host
    mx02.cloud.vadesecure.com[*redacted*] said: 550 5.7.1 spf policy
    (FAILED) (in reply to RCPT TO command)

<*redacted*> (expanded from <contact@ocsinventory-ng.org>): host
    mx02.cloud.vadesecure.com[*redacted*] said: 550 5.7.1 spf policy
    (FAILED) (in reply to RCPT TO command)
"

i hope the other people in the list get the issues :)

**Comment by gillesdubois** [comment]
Hey @Mayfly277 

I don't have any ideas on my side why its not working. Could you send an email to gilles@factorfx.com ?
Please let me know when you sent the mail so I can remove my mail from the comment :)

Regards,
Gilles.
