### ISSUE TITLE
[BUG] Unusual behavior when deploying to groups 

### ISSUE THREAD

**Issue by thenextuser** [OCSInventory-NG/OCSInventory-ocsreports#1270]
**OCS Inventory version**
Version : 2.9 (another user had this with version 2.8.1)

**Describe the bug**
When I want to do a deploy on a group, the package is not deployed as desired.
It says "1 computer successfully assigned" but it is not finally assigned to any member of the group.
(This is the case with both static and dynamic groups)
If I select multiple computers in the search and deploy to the selection then it goes normally to all computers of the selection.
So the problem concerns only the groups.
Earlier it worked in any case already on this way of the group. It must now have been damaged by some update.

**To Reproduce**
1. Go to 'Inventory'
2. Click on 'Groups'
3. Select any group
4. Click on 'Add packege'
5. Choose any package
6. Click on 'Add selected package'

**Optional**
Since I thought it was a bug in my installation at first, I had posted it on the forum first. ( https://ask.ocsinventory-ng.org/13506/unusual-behavior-when-deploying-to-groups )
But there other users had the same problem. I am told I should post a bug report here. I have done so with this :)

**Comment by charleneauger** [comment]
Hi @thenextuser ,

When you create a group, it will registered like a machine on the hardware table. So when you assign a package to this group, it says "1 computer successfully assigned" because the group it's considered as a machine. 
However, the package will be deployed on all the machines in this group.

Regards,
Charlene Auger

**Comment by thenextuser** [comment]
Hi @charleneauger ,

That's the problem with it, unfortunately a deployment doesn't take place at all when I assign the package via the groups function.
In fact, it is not found in any overview of the respective computers (under the menu item 'Deployment').

The same problem is described in the forum by another user (see link above).
Do you have any more idea here where the error could be or where I can look for the problem?

Thanks and many greetings

**Comment by Lea9250** [comment]
Hi @thenextuser,

Just tested this with a static group and dynamic one. After assigning a package to your group, you should be able to see it under 'activated packages' at the bottom of the group detail page. 
The package will appear on each computer 'Deployment' section when the machine is notified (i.e. when the machine sends its inventory and gets notified of a new package to download). 
The deployment was successful on these two groups.

Regards,
Léa

**Comment by thenextuser** [comment]
Hi @Lea9250 ,

now I see it too.
I assumed that the package is entered directly under the corresponding machines as soon as the deploy is started.
However, it is only listed when a machine logs on to OCS. Until then it can be found in the respective group under 'activated packages'.
You are absolutely right, no bug, everything is correct. I just assumed something wrong.

Thank you very much for your help. Great work. Sorry for the disturbance.

I will describe this on the forum accordingly, so that one knows there.

Many greetings.
