### ISSUE TITLE
[BUG] Duplicated computers

### ISSUE THREAD

**Issue by imponimassacri** [OCSInventory-NG/OCSInventory-ocsreports#1273]
**OCS Inventory version**
Version : 2.9.1

**Describe the bug**
Some computers are duplicated, even several times a day. I tried any configuration of AUTO_DUPLICATE_LVL and to install last version of agent on pcs, but with no effects.
The problem started to occur after updating the operating system (to Ubuntu 20.04) and mysql version (to 8.0), so I suspect it may be a MySql problem.
Below an example.
![Duplicate](https://user-images.githubusercontent.com/61516867/137451064-b2c88989-b90b-4610-9f5a-0e2e09e84553.PNG)

**Comment by imponimassacri** [comment]
Hi Léa,
I am attaching the log (in debug mode) of an agent that this morning presented itself as a duplicate on the console.
This line seems interesting to me: DID_CHECK => MAC Address changed new:<C8:D3:FF:9F:38:14C8:21:58:11:3E:01> old:<C8:D3:FF:9F:38:14C8:21:58:11:3E:01CA:21:58:11:3E:01C8:21:58:11:3E:02>
Why is the old mac address seen as a concatenation of the mac addresses of two different network cards?

I also attach a stamp from which you can see the list of network cards.

The problem occurs with both version 2.3 and 2.9 of the agent.

[OCSInventory.log](https://github.com/OCSInventory-NG/OCSInventory-ocsreports/files/7473215/OCSInventory.log)
![SchedeDiRete](https://user-images.githubusercontent.com/61516867/140279898-01bce7d8-a98b-4e48-af70-063c75e69884.png)

**Comment by imponimassacri** [comment]
Hi @charleneauger 
I confirm that the error duplicate;replacing_error is present in log file.

**Comment by imponimassacri** [comment]
Hi @charleneauger 
I applied the PR.
This is an extract of the activity.log, from which you can see a duplicated pc:
Thu Nov 18 02:04:12 2021;4171203;319;SRVAPP05-2021-11-18-02-03-19;172.17.100.65;OCS-NG_WINDOWS_AGENT_v2.3.0.0;session;found
Thu Nov 18 02:04:12 2021;4171203;104;SRVAPP05-2021-11-18-02-03-19;172.17.100.65;OCS-NG_WINDOWS_AGENT_v2.3.0.0;inventory;incoming
Thu Nov 18 02:04:12 2021;4171203;320;SRVAPP05-2021-11-18-02-03-19;172.17.100.65;OCS-NG_WINDOWS_AGENT_v2.3.0.0;session;end
Thu Nov 18 02:04:12 2021;4171203;300;SRVAPP05-2021-11-18-02-03-19;172.17.100.65;OCS-NG_WINDOWS_AGENT_v2.3.0.0;duplicate;9763 => 9777
Thu Nov 18 02:04:12 2021;4171203;101;SRVAPP05-2021-11-18-02-03-19;172.17.100.65;OCS-NG_WINDOWS_AGENT_v2.3.0.0;inventory;transmitted

**Comment by Lea9250** [comment]
Hi @imponimassacri,

Is the `duplicate;replacing_error` still appearing in your logs ? Do you see any entries like `duplicate;error to delete hardware_id from tablename` ? This would indicate that a plugin wasn't uninstalled properly, causing the duplicate error.
It would be nice to have a sample of your logs, including a `duplicate;replacing_error`, if you don't mind.

Thanks,
Léa

**Comment by imponimassacri** [comment]
Hi @Lea9250,
I apologize for the delay, but I wanted to make sure I have updated data to provide you.
The situation has clearly improved: there are very few duplicates left, and in the logs there aren't errors  like duplicate;replacing_error or duplicate;error to delete hardware_id from tablename
However, I attach the log file and a stamp with the data of a duplicate PC, so that you can carry out the necessary checks.
Thank you
[log.zip](https://github.com/OCSInventory-NG/OCSInventory-ocsreports/files/7666062/log.zip)

**Comment by Lea9250** [comment]
Hi @imponimassacri,
Try merging the duplicates manually if you have any left, a few duplicated devices isn't uncommon. Everything seems to be working fine according to your log file. 
Let me know if I can close this issue,
Léa

**Comment by imponimassacri** [comment]
Hi @Lea9250 ,
today I verified the list of duplicated pcs, and I can confirm that the problem is solved, so you can close the issue.
Thank you very much for your intervention.
Massimo
