### ISSUE TITLE
[BUG] Dynamic group not updating as espected

### ISSUE THREAD

**Issue by aramilialon** [OCSInventory-NG/OCSInventory-ocsreports#1278]
**OCS Inventory version**
Version : 2.9.1

**Describe the bug**
The cache of dynamic groups does not follow the parameters GROUPS_CACHE_OFFSET and GROUPS_CACHE_REVALIDATE

**To Reproduce**
1. Leaving all the parameters as default, create a new dynamic group based on a TAG search
2. Change the parameters related to the cache to 1 second each
3. Look to the _Cache generated on :_ data into the dynamic group, you will see that the group won't update even in 20 minutes

**Expected behavior**
The cache group should be updating every second, but it does not

**Screenshots**
<img width="1680" alt="immagine" src="https://user-images.githubusercontent.com/938951/138868760-c375da3c-e87c-4bd3-b604-047c3cebea49.png">
<img width="1680" alt="immagine" src="https://user-images.githubusercontent.com/938951/138868809-dc97fae5-543e-4c1d-946c-d10ab78022a0.png">

**Log file (optional)**
No log are found

**Comment by charleneauger** [comment]
Hi @aramilialon ,

The group cache is updated by the server when the machines present in this group are inventoried. Except if you have machines in this group which do an inventory every second otherwise the group will not really update every second. 

Best regards,
Charlene Auger
