### ISSUE TITLE
ERROR after Update

### ISSUE THREAD

**Issue by zxtury** [OCSInventory-NG/OCSInventory-ocsreports#128]
I updated Reports today, and after that i have the following error in every page:

Warning: file_get_contents(http://www.ocsinventory-ng.org/update.json) [function.file-get-contents]: failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found in C:\xampp\htdocs\ocsreports\require\function_commun.php on line 413

**Comment by gillesdubois** [comment]
Hi,

We have introduced a new functionality which can check for ocs software update but the server side thing is not fully done that why you've got this 404 each page. ( This file doesn't exist http://www.ocsinventory-ng.org/update.json at the moment)

If you are using ocsinventory on a production environement you should wait a little before update with the master branch on git hub. This revision can be very instable.

Regards,
Gilles Dubois.
