### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by perceval57** [OCSInventory-NG/OCSInventory-ocsreports#1289]
**OCS Inventory version**
Version : 2.9.1

**Describe the bug**

the duplicate function does not display the table correctly following the switch from version 2.6 to 2.9.1.
only the name appears and you cannot change the page

**To Reproduce**
update from OCS 2.6 to 2.9.1

**Expected behavior**
a table like the other function, with more information

**Screenshots**
![image](https://user-images.githubusercontent.com/94376311/141795312-c158716e-8b58-409a-8ac1-e49cc30a0813.png)

**Comment by charleneauger** [comment]
Hi @perceval57 ,

What is your php version please ?

Regards,
Charlene Auger

**Comment by charleneauger** [comment]
Hi @perceval57 ,

Do you have any error in your javascript console or in your apache log ?

Regards,
Charlene

**Comment by perceval57** [comment]
hi @charleneauger 
I don't have some javascript console, and there is no error when i do that :
tail -f /var/log/httpd/error_log.

I'm sorry but i think i only just used the last version too much. 
i see more things when i click on on link.

It's just a new interface.
Thanks a lot

**Comment by perceval57** [comment]
hi @charleneauger 
I don't have some javascript console, and there is no error when i do that :
tail -f /var/log/httpd/error_log.

I'm sorry but i think i only just used the last version too much. 
i see more things when i click on on link.

It's just a new interface.
Thanks a lot
