### ISSUE TITLE
[BUG] Inventory > Computers per tag show incorrect count

### ISSUE THREAD

**Issue by sblaisot** [OCSInventory-NG/OCSInventory-ocsreports#1290]
**OCS Inventory version**
Version : 2.8.1 as shipped with debian bullseye (debian package from debian)

**Describe the bug**
Each computer sends inventory with a tag corresponding to environment they belong to (dev, int, staging, prod).
When I query computer list on a given tag with inventory->search with various criteria with "Account Info : Tag' I can manually countall computers with a given value for tag.
I count 24 computers with tag value `dev` and `22` with tag value `int` for example.
I double-checked, by manually counting computers based on tag value in the "All computers" page and these numbers are correct.

However, on Inventory > computers per tag, it shows me the following table with wrong count:

| tag | count |
|---|---|
| dev | 45 |
| int | 26 |

**To Reproduce**
1. send inventory data for 20 computers, 10 with tag value "dev" and 10 with tag value 'int"
2. Go to Inventory > computers per tag. You should get 10 and 10 in count
3. See error

**Expected behavior**
Computer count in Inventory > computers per tag are correct

**Screenshots**
![image](https://user-images.githubusercontent.com/2768193/142861107-f3fe96bb-a20d-44f2-811b-464692625ba7.png)

![image](https://user-images.githubusercontent.com/2768193/142861147-f3602044-2314-437d-b538-337d723ade63.png)

**Comment by sblaisot** [comment]
Looking at database I see I have some entries in hardware table that are all-null entries and are counted under Inventory > Computers per tag. I think they should be filtered when counting.

```
*************************** 21. row ***************************
   HARDWARE_ID: 27
           TAG: Dev
            ID: NULL
      DEVICEID: NULL
          NAME: NULL
     WORKGROUP: NULL
    USERDOMAIN: NULL
        OSNAME: NULL
     OSVERSION: NULL
    OSCOMMENTS: NULL
    PROCESSORT: NULL
    PROCESSORS: NULL
    PROCESSORN: NULL
        MEMORY: NULL
          SWAP: NULL
        IPADDR: NULL
           DNS: NULL
DEFAULTGATEWAY: NULL
         ETIME: NULL
      LASTDATE: NULL
      LASTCOME: NULL
       QUALITY: NULL
      FIDELITY: NULL
        USERID: NULL
          TYPE: NULL
   DESCRIPTION: NULL
    WINCOMPANY: NULL
      WINOWNER: NULL
     WINPRODID: NULL
    WINPRODKEY: NULL
     USERAGENT: NULL
      CHECKSUM: NULL
        SSTATE: NULL
         IPSRC: NULL
          UUID: NULL
          ARCH: NULL
   CATEGORY_ID: NULL
       ARCHIVE: NULL
```

**Comment by sblaisot** [comment]
```
MariaDB [ocs]> SELECT HARDWARE_ID FROM accountinfo WHERE HARDWARE_ID NOT IN (SELECT ID FROM hardware);
+-------------+
| HARDWARE_ID |
+-------------+
|           9 |
|          10 |
|          11 |
|          12 |
|          13 |
|          14 |
|          16 |
|          17 |
|          18 |
|          19 |
|          20 |
|          21 |
|          22 |
|          23 |
|          24 |
|          25 |
|          26 |
|          27 |
|          28 |
|          29 |
|          30 |
|          53 |
|          57 |
|          66 |
|          74 |
+-------------+
25 rows in set (0.001 sec)

MariaDB [ocs]> SELECT ID FROM hardware WHERE ID=9;
Empty set (0.001 sec)
```

**Comment by sblaisot** [comment]
I fixed the issue on my server with
```
MariaDB [ocs]> DELETE FROM accountinfo WHERE HARDWARE_ID NOT IN (SELECT ID FROM hardware);
Query OK, 25 rows affected (0.021 sec)
```

But we should find how this triggered to fix it at the source.

**Comment by Lea9250** [comment]
Hi @sblaisot,

Seeing that you managed to fix this on your own I'll close this issue. A lot of changes have been made since the 2.8.1 version and improvements were made to delete hardware_ids from all tables if a device is removed/merged.

Regards,
Léa
