### ISSUE TITLE
[BUG] Microsoft vulnerabilities are not recognized in the CVE Reporting

### ISSUE THREAD

**Issue by CyberAbwehr** [OCSInventory-NG/OCSInventory-ocsreports#1291]
**OCS Inventory version**
PHP Version :     7.4.3
Web Server : Apache/2.4.41 (Ubuntu)
Database Server : (Ubuntu) version 8.0.27-0ubuntu0.20.04.1
Version OCSReports:   2.9.1
CIRCL CVE Search: v4.1.0.dev213
Windows Agent: OCS Inventory NG Agent 2.9.0.0

**Describe the bug**
Microsoft vulnerabilities are not recognized in the CVE Reporting.

**To Reproduce**
I am running following scripts.
1. cron_all_software.php
2. cron_cve.php
3. cron_cve_computer.php

List of my Microsoft Operations Systems in the inventory.
Microsoft Windows 10 Enterprise
Microsoft Windows Server 2012 R2 Standard
Microsoft Windows Server 2016 Standard
Microsoft Windows Server 2019 Standard
Microsoft Windows Server 2008 R2 Enterprise
Microsoft Windows Server 2012 Standard
Microsoft Windows Server 2008 R2 Standard
Microsoft Windows Storage Server 2012 R2 Standard
Microsoft Windows Server 2012 R2 Datacenter
Microsoft Windows 8.1 Enterprise
and many Microsoft applications (Office, Visual Tools, etc.)
If I search the CVE search database i can find a lot of vulnerabilies and
if I use as example OpenVas, i get the OS vulnerabilities.

**Expected behavior**
Find all vulnerabilities if a CVE match.

best regards

**Comment by Minikea** [comment]
I can confirm the behavior in OCS 2.9.1, even if I add some regex in Manage→CVE Inventory
![image](https://user-images.githubusercontent.com/731225/144032811-29adeeba-9a37-439d-b3ab-1e5272c34e24.png)
![image](https://user-images.githubusercontent.com/731225/144033004-db74aaa7-ee2b-4e2e-96fb-f412c7f13746.png)

**Comment by CyberAbwehr** [comment]
Hello,

It there a way to support you to fix the problem?

best regards

**Comment by kayapo** [comment]
I have same issue

**OCS Inventory version**
PHP Version : 7.4.3
Web Server : Apache/2.4.41 (Ubuntu)
Database Server : mariadb  Ver 15.1 Distrib 10.3.32-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
Version OCSReports: 2.9.2
CIRCL CVE Search:  v4.1.0.dev285
Windows Agent: OCS Inventory NG Agent 2.9.0.0

**Comment by Minikea** [comment]
Still present in 2.11.1
    PHP Version : 7.4.33
    Web Server : Apache/2.4.54 (Debian)
    Database Server : Debian 11 version 10.5.18-MariaDB-0+deb11u1
    Version OCSReports: 2.11.1

is there a fix for this problem?

**Comment by Cubitus06** [comment]
A L'attention de Gilles DUBOIS : 

J'ai refait une installation complète d'un ALMALINUX 9.1 US avec : 
- Php 8.0.20
- MariaDB 11.0.1
- Apache : 2.4.53
- OCSNG_UNIX_SERVER-2.11.1.tar.gz

J'ai exactement le même problème. Il ne trouve qu'un seul CVE sur une machine windows7 qui devraient en remonter une centaine. J'ai fait une documentation en Word que je peux vous donner avec toute l'installation complète.

Cela fonctionnait parfaitement en 2.7 et 2.8, mais plus en 2.9.

Pouvez-vous svp prendre contact avec moi pour débuguer cette fonctionnalité svp ?

Vous êtes, a priori la seule personne qui saurait nous aiguiller sur la solution,
On compte sur vous, pitié :=)

Merci par avance
