### ISSUE TITLE
Problème Merge redundant computer inactif

### ISSUE THREAD

**Issue by ChandlerBing82** [OCSInventory-NG/OCSInventory-ocsreports#130]
Bonjour,

Depuis la mise à jour vers la version 2.2.1 de OCSInventory sur Unix, nous ne pouvons plus gérer les ordinateurs dupliqués.

Nous sélectionnons 2 PC à merge et nous cliquons sur Merge Redundant computers et il ne se passe rien.

J'ai déja essayé de réinstaller l'application OCS sur le serveur j'ai même supprimer complètement le répertoire OCSInventory pour repartir sur une installation propre et malgré cela le bouton reste inactif.

Version OCSInventory : 2.2.1

OS: Ubuntu 16.04

Apache version 2

php version 7

mysql version 5.7

J'ai regardé dans les logs Apache du serveur et j'ai trouvé des erreurs quand on clique sur le bouton Merge Redundant computers:

```
[Mon Sep 12 09:19:28.953935 2016] [:error] [pid 6218] [client IP_MACHINE:40799] PHP Warning:  mysqli_fetch_array() expects parameter 2 to be integer, string given in /usr/share/ocsinventory-reports/ocsreports/plugins/main_sections/ms_doubles/ms_doubles.php on line 48, referer: http://NOM_SERVEUR/ocsreports/?function=admin_double
[Mon Sep 12 09:19:28.954266 2016] [:error] [pid 6218] [client IP_MACHINE:40799] PHP Warning:  mysqli_fetch_array() expects parameter 2 to be integer, string given in /usr/share/ocsinventory-reports/ocsreports/plugins/main_sections/ms_doubles/ms_doubles.php on line 48, referer: http://NOM_SERVEURocsreports/?function=admin_double
[Mon Sep 12 09:19:28.954544 2016] [:error] [pid 6218] [client IP_MACHINE:40799] PHP Warning:  mktime() expects parameter 1 to be integer, string given in /usr/share/ocsinventory-reports/ocsreports/require/function_computers.php on line 168, referer: http://NOM_SERVEUR/ocsreports/?function=admin_double
[Mon Sep 12 09:19:28.954576 2016] [:error] [pid 6218] [client IP_MACHINE:40799] PHP Warning:  mktime() expects parameter 1 to be integer, string given in /usr/share/ocsinventory-reports/ocsreports/require/function_computers.php on line 168, referer: http://NOM_SERVEUR/ocsreports/?function=admin_double
[Mon Sep 12 09:19:29.134872 2016] [:error] [pid 6218] [client IP_MACHINE:40799] PHP Warning:  mysqli_fetch_array() expects parameter 2 to be integer, string given in /usr/share/ocsinventory-reports/ocsreports/plugins/main_sections/ms_doubles/ms_doubles.php on line 48, referer: http://NOM_SERVEUR/ocsreports/?function=admin_double
[Mon Sep 12 09:19:29.135212 2016] [:error] [pid 6218] [client IP_MACHINE:40799] PHP Warning:  mysqli_fetch_array() expects parameter 2 to be integer, string given in /usr/share/ocsinventory-reports/ocsreports/plugins/main_sections/ms_doubles/ms_doubles.php on line 48, referer: http://NOM_SERVEUR/ocsreports/?function=admin_double
[Mon Sep 12 09:19:29.135465 2016] [:error] [pid 6218] [client IP_MACHINE:40799] PHP Warning:  mktime() expects parameter 1 to be integer, string given in /usr/share/ocsinventory-reports/ocsreports/require/function_computers.php on line 168, referer: http://NOM_SERVEUR/ocsreports/?function=admin_double
[Mon Sep 12 09:19:29.135502 2016] [:error] [pid 6218] [client IP_MACHINE:40799] PHP Warning:  mktime() expects parameter 1 to be integer, string given in /usr/share/ocsinventory-reports/ocsreports/require/function_computers.php on line 168, referer: http://NOM_SERVEUR/ocsreports/?function=admin_double
```

Merci à vous.

**Comment by gillesdubois** [comment]
Bonjour,

Votre demande a bien été pris en compte.
Nous allons tenter de reproduire le problème que vous rencontrez et commit un fix si le bug est reconnu.

Cordialement,
Gilles Dubois.

**Comment by MyTheValentinus** [comment]
Bonjour @ChandlerBing82,
Je n'ai pas réussi à reproduire ce bug sur la version actuelle du repo.
Sous ubuntu 16.04 et PHP7.
Peut-être ceci à été corrigé lors d'un dev ultérieur à la release.
Merci

**Comment by ChandlerBing82** [comment]
Je ne comprends pas bien votre test.
Juste pour information, je n'ai pas installé OCSInventory server a partir des dépots Ubuntu.
J'ai téléchargé et installé ocsinventory depuis votre dépot Github (version 2.2.1) et en suivant les instructions pour l'installation (sachant que nous avons OCSInventory depuis la vers 1.02 de souvenir).

Si besoin je peux tester un dev ultérieur si vous me dites ou je peux la télécharger.

Merci à vous.

**Comment by gillesdubois** [comment]
Bonjour,

Les tests réalisé par @MyTheValentinus ont été effectué sur la version de développement. ( https://github.com/OCSInventory-NG/OCSInventory-ocsreports ) 

Note : Le mot "repo" est utilisé pour dire "repo github" et non pas repo d'une distribution linux.

j'ai donc refait quelques tests de mon côté, votre bug est belle et bien présent sur la 2.2.1 avec ubuntu 16.04 mais a été fixé dans la branche de développement.

Vous pourrez bénéficier de ce fix lors de la prochaine mise a jour.

Cordialement,
Gilles Dubois.
