### ISSUE TITLE
Local Import missing after upgrade

### ISSUE THREAD

**Issue by anjoze** [OCSInventory-NG/OCSInventory-ocsreports#1303]
**OCS Inventory version**
Version :  2.9.1

**Describe the bug**
After upgrading the option Local Import is missing

**To Reproduce**
1. Go to Menu: Manage
No Local Import available

**Expected behavior**
Local Import option
https://wiki.ocsinventory-ng.org/03.Basic-documentation/Administration-of-OCS-Inventory-NG/#importing-inventory-for-non-network-connected-computers

**Screenshots**
![Local_import](https://user-images.githubusercontent.com/11679993/144610047-74fef4e4-bf7f-48e6-b43d-76d5ce1d12f2.png)

**Comment by charleneauger** [comment]
Hi @anjoze ,

The local import has been removed from version 2.9.0 but will be reintegrated into version 2.9.2 in the Manage menu.

Best regards,
Charlene Auger
