### ISSUE TITLE
[BUG] Post installation mysqli error

### ISSUE THREAD

**Issue by EdenCore** [OCSInventory-NG/OCSInventory-ocsreports#1307]
Hello everybody ! First of, you are doing a great job with OCS as it is a very nice tool !

I've implemented the communication and deployment server on a unique standard VM (as well as the database server), and I encountered the following issue:

### Problem's description

`PHP Fatal error:  Uncaught TypeError: mysqli_fetch_object(): Argument #1 ($result) must be of type mysqli_result, bool given in /usr/share/ocsinventory-reports/ocsreports/install.php:138\nStack trace:\n#0 /usr/share/ocsinventory-reports/ocsreports/install.php(138): mysqli_fetch_object()\n#1 /usr/share/ocsinventory-reports/ocsreports/require/header.php(91): require('...')\n#2 /usr/share/ocsinventory-reports/ocsreports/index.php(44): require('...')\n#3 {main}\n  thrown in /usr/share/ocsinventory-reports/ocsreports/install.php on line 138,`

### Context:

Database and user are created and privileges are set.
Right after the setup.sh is finished, I launched /ocsreport/install.php and got to the menu. Then I entered the correct infos and I selected "NO" for SSL. After I validated the form I got a blank page, and I got the error from apache logs.

It appears that the the database couldn't be filled up with the mysqli request, but I get no error in the mariadb logs.

However, when I use the command line `mysql -f -hlocalhost -uroot -p DBNAME < ocsbase.sql >log.log` It does work and I can go to the index page with the database correctly set up.
Thank you for your reply.

### General informations
Operating system :  Debian 10
All prerequisites are OK and no problem during setup.sh from the .tar.gz package.

### Server informations
Perl version :  v5.28.1
Mariadbversion : 10.3.31
PHP version: 8.0 (also tested on 8.1)

### OCS Inventory informations
Ocs server version :  2.9.2

**Comment by charleneauger** [comment]
Hi @EdenCore ,

Unfortunately, OCS isn't yet compatible with PHP 8.
We recommend installing PHP 7 to use OCS.

Best regards,
Charlene
