### ISSUE TITLE
[BUG] Package activation empty in NOT en_GB Language (e.g. de_DE)

### ISSUE THREAD

**Issue by LMS235** [OCSInventory-NG/OCSInventory-ocsreports#1308]
After updating from 2.9.1 to 2.9.2, the software packages are no longer displayed in German. In English they are still available.

**OCS Inventory version**
Version : 2.9.2

**Describe the bug**
Behavior in language English: 
Deployment --> Activate --> List is OK (all Packages visible)

Behavior in language German: 
Softwareverteilung --> Aktivieren --> List is EMPTY (no Package visible)

EN:
![image](https://user-images.githubusercontent.com/8693550/146177152-3fdc66b5-1bb8-4d2e-9fb7-18534df30076.png)

DE:
![image](https://user-images.githubusercontent.com/8693550/146177024-387c5bac-f518-46a8-b03d-dbea53b1c4f8.png)

**To Reproduce**
Behavior in language English: 
Deployment --> Activate --> List is OK (all Packages visible)

Behavior in language German: 
Softwareverteilung --> Aktivieren --> List is EMPTY (no Package visible)

**Expected behavior**
The language should not affect the result

**Screenshots**
see above

**Log file (optional)**
should something be necessary, please report

**Comment by ajavor** [comment]
Same symptom for other languages ​​other than English.

**Comment by LMS235** [comment]
Updated Title

**Comment by jackburton79** [comment]
It seems this problem resurfaced on OCSInventory 2.9.2.
I checked the code and its, in fact, still wrong

 ```
  foreach ($list_fields as $key => $value) {
        if ($key != 'Creation date' && $key != 'Total size KB') {
            $querypack .= $value . ',';
        }
        if ($key == 'Creation date') {
            $querypack .= ' CAST(from_unixtime(FILEID) AS DATETIME) as ' . $value . ',';
        }
        if ($key == 'Total size KB') {
            $querypack .= ' round(SIZE/1024,2) as ' . $value . ',';
        }
```
