### ISSUE TITLE
[BUG]OCS-NG Inventory Installation,  don't continue

### ISSUE THREAD

**Issue by FelipeSilveiraL** [OCSInventory-NG/OCSInventory-ocsreports#1309]
**OCS Inventory version**
Version : 2.9.2

**Describe the bug**
after entering the database information, I click "SEND", and nothing else happens.

**To Reproduce**

**Expected behavior**
go to login screen

**Screenshots**
![image](https://user-images.githubusercontent.com/82624468/146192392-0340842e-c40c-4899-8c0a-3e314a86351e.png)

**Comment by Lea9250** [comment]
hi @FelipeSilveiraL,

Do you have any errors showing up in the apache logs after validating the database information ? Is this a first install ? 

Regards,
Léa

**Comment by charleneauger** [comment]
Hi,

Since there is no anwser, I'll now close the issue.

Regards,
Charlene.
