### ISSUE TITLE
Wrong delete popup message 

### ISSUE THREAD

**Issue by ameurou** [OCSInventory-NG/OCSInventory-ocsreports#131]
Hi,

On "all computers" view, the delete popup message string is name_of_machine instead of do you really want to delete Computer

![bug](https://cloud.githubusercontent.com/assets/11721263/18553142/ac14a8ec-7b5f-11e6-9441-67ef236d8bfb.JPG)

**Comment by gillesdubois** [comment]
Hi,

This bug has already been fixed on the ocsreports master branch.
Take a look at this issue for more information : https://github.com/OCSInventory-NG/OCSInventory-ocsreports/issues/122
Basically it was just a naming mistake.

Regards,
Gilles Dubois.

**Comment by ameurou** [comment]
Oups, not see this...  :-) 

I think there is an other case in ms_multi_search.php see #132
