### ISSUE TITLE
The memory capacity unit is displayed incorrectly,  ‘’GB” is displayed as “MB”

### ISSUE THREAD

**Issue by sgysz** [OCSInventory-NG/OCSInventory-ocsreports#1311]
My OCSInventory Server got the wrong unit of memory capacity of some server equipment, please give me some advice, thank you. It should show GB instead of MB. As a result, GLPI is synchronized to the wrong unit.

![1](https://user-images.githubusercontent.com/24391480/146668273-056f6e0f-d79e-4c45-9f0e-28841f546ade.jpg)

What the actual agent gets:
<MEMORY>128385</MEMORY>

The actual server:
![2](https://user-images.githubusercontent.com/24391480/146668309-0f0e7896-90f5-413c-9311-bf3c605a30fa.jpg)

Thank you very much！

**Comment by Lea9250** [comment]
Hi @sgysz,

What OS is the device having this issue running ? It does not seem to be a OCS reports/server issue for the moment. The memory unit is intended to be MB.

Regards,
Léa

**Comment by sgysz** [comment]
The OCS server OS version is Centos7.4.
The number of OCS agent nodes is 3000.
There are many operating system versions, most of which are Centos7.4\7.9.
The first picture is seen by the OCS SERVER display
The second picture is the result of the system command: cat /proc/meminfo
The problem now is that the actual memory capacity unit seen by the OCS SERVER is MB, but it should actually be GB.
thanks!

**Comment by sgysz** [comment]
> The OCS server OS version is Centos7.4.
> The number of OCS agent nodes is 3000.
> There are many operating system versions, most of which are Centos7.4\7.9.
> The first picture is seen by the OCS SERVER display
> The second picture is the result of the system command: cat /proc/meminfo
> The problem now is that the actual memory capacity unit seen by the OCS SERVER is MB, but it should actually be GB.
> thanks!



> Hi @sgysz,
> 
> What OS is the device having this issue running ? It does not seem to be a OCS reports/server issue for the moment. The memory unit is intended to be MB.
> 
> Regards, Léa



The OCS server OS version is Centos7.4.
The number of OCS agent nodes is 3000.
There are many operating system versions, most of which are Centos7.4\7.9.
The first picture is seen by the OCS SERVER display
The second picture is the result of the system command: cat /proc/meminfo
The problem now is that the actual memory capacity unit seen by the OCS SERVER is MB, but it should actually be GB.
thanks!

**Comment by sgysz** [comment]
> Hi @sgysz,
> 
> What OS is the device having this issue running ? It does not seem to be a OCS reports/server issue for the moment. The memory unit is intended to be MB.
> 
> Regards, Léa

hi @Lea9250 
The OCS server OS version is Centos7.4.
The number of OCS agent nodes is 3000.
There are many operating system versions, most of which are Centos7.4\7.9.
The first picture is seen by the OCS SERVER display
The second picture is the result of the system command: cat /proc/meminfo
The problem now is that the actual memory capacity unit seen by the OCS SERVER is MB, but it should actually be GB.
thanks!

**Comment by Lea9250** [comment]
The memory total is retrieved with `cat /proc/meminfo`, but the table you are looking at displays data from the output of `dmidecode -t 17` (or `dmidecode -t 6`). The agent is then supposed to process this data and return the memory size in MB to the server. 
Could you try executing the dmidecode command I mentioned and sharing the results here ?

Regards,
Léa

**Comment by charleneauger** [comment]
Hi,

Since there is no anwser, I'll now close the issue.

Regards,
Charlene.
