### ISSUE TITLE
[BUG] "All computers (replay)" doesn't work

### ISSUE THREAD

**Issue by beegospl** [OCSInventory-NG/OCSInventory-ocsreports#1329]
Version : 2.9.1 and 2.9.2

I noticed that after upgrade to 2.9.1 or 2.9.2 the option "All computers (replay)" for dynamic groups returns an empty table.

**Comment by rayzilt** [comment]
Hi OCS Team,

Is this bug under your attention? I like to use dynamic groups again for software deployment.

**Comment by Laurent-1971** [comment]
Hello,

Same problem here. Not about when it started but the issue is still here in 2.9.10

PHP Version : 7.4.30
Web Server : Apache/2.4.37 (AlmaLinux) OpenSSL/1.1.1k mod_perl/2.0.12 Perl/v5.26.3
Database Server : MariaDB Server version 10.3.32-MariaDB
Version OCSReports: 2.10.0

**Comment by gillesdubois** [comment]
Hi,

Indeed we saw the issue on the 2.10.0.
We are going to fix in asap.

Regards,
Gilles.

**Comment by beegospl** [comment]
It started in 2.9.1
