### ISSUE TITLE
bug static / dynamic groups

### ISSUE THREAD

**Issue by gitmais** [OCSInventory-NG/OCSInventory-ocsreports#133]
Ubuntu 16.04.2 / PHP 7.0.8 /  OCS 2.2.1

Hello,
 When i "click" on a dynamic or a static group, everything seems fine but i have a message error in my apache error.log : 

`[:error] [pid 28319] [client :XXX.XXX.XXX.XXX:41003] PHP Warning:  mysqli_fetch_array() expects parameter 2 to be integer, string given in /usr/share/ocsinventory-reports/ocsreports/plugins/main_sections/ms_groups/ms_group_show.php on line 486, referer: http://srvocs.domain.intra/ocsreports/index.php?function=group_show&head=1&systemid=5&option=Traitements+personnalis%C3%A9s`

The 489 line of ms_group_show.php: 

`while($item=mysqli_fetch_array($resultDetails,MYSQL_ASSOC)) {`

 Maybe i'm not alone ?

**Comment by gillesdubois** [comment]
Hi,

This error has been fixed on the master branch and will be available in the new version.

For a quick fix : 
Replace "MYSQL_ASSOC" with "MYSQLI_ASSOC" and the error should disappear.

Thanks for your time.
Regards, Gilles Dubois
