### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by cruzope** [OCSInventory-NG/OCSInventory-ocsreports#1331]
**OCS Inventory version**
Version : 2.9.1

**Describe the bug**
Hello, we have the problem that for some machines the logged on user can´t be reported back to the inventory, we use the same agent for all clients (2.9.0.0). The computers are all Windows 10 Pro. Is there anything we have to do in our Windows environment for the reporting to work properly?

Thanks you in advance.

Kind regards
Cruz

**Comment by cruzope** [comment]
@charleneauger @damienbelliard @gillesdubois @RudyLaurent 

Hello,

can you tell me something about this bug?

Kind regards
Cruz

**Comment by Lea9250** [comment]
Hi @cruzope,

If the inventory is sent while nobody is connected on the device, the connected user field will be empty. 

Hope this helps,
Léa

**Comment by cruzope** [comment]
@Lea9250 
Hello Léa,

the problem is that the field is also empty on devices where a user is logged on.

Kind regards
Léa

**Comment by cruzope** [comment]
@Lea9250 
Hey Léa,

maybe you could help me with another question. I startet collecting last logged on users via registry. Do you know is there a way I can edit the shown fields, so I can have a seperate column for the registry key values in the computers view?

Thanks in advance
Cruz

**Comment by Lea9250** [comment]
Hi @cruzope,

Unfortunately there is no way to add the registry entries to the all computers view. You could try using the search with various criteria to show the corresponding field, maybe even use the saved searches feature. 
Are you users still not reported ? The plugin winusers might be helpful : https://github.com/PluginsOCSInventory-NG/winusers

Regards,
Léa

**Comment by Lea9250** [comment]
HI @cruzope,

Any update about this ? Did you try using the winusers plugin ?

Regards,
Léa

**Comment by cruzope** [comment]
Hey @Lea9250,

all machines now report the lastuser loged on on the computer back to oce, we settled on the option we that we see the user on the start page of the specific machine.

Kind regarda,
Cruz
