### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by mileswebster2** [OCSInventory-NG/OCSInventory-ocsreports#1333]
**Is your feature request related to a problem? Please describe.**
z/VM based virtual machines are identified as "physical" systems.
Also these systems do not get a serial number allocated to them.  dmidecode does not produces valid results as there is no BIOS to query in z/VM.

**Describe the solution you'd like**
I would like OCS Inventory to properly identify "z/VM" Linux installations as virtual machines.
Additionally a "serial number" is needed for "iTop/OCS" data connector to sync correctly.

**Comment by gillesdubois** [comment]
Hi,

Your issue quite old now. Could you confirm that your problem is still relevant ? 
Please note that we don't have any z/VM based VM, you'll have to provide the informations retrieved by the agent (such as a XML) in order for us to look at your issue.

Regards,
Gilles.
