### ISSUE TITLE
[BUG] Problème de duplicata

### ISSUE THREAD

**Issue by thenamelessthing** [OCSInventory-NG/OCSInventory-ocsreports#1335]
![image](https://user-images.githubusercontent.com/10235448/153056912-2d5d3998-a7b3-4893-94e9-e81413986fcf.png)

**Describe the bug**
Nous avons des ordinateurs en double qui sont répertorié dans OCS malgré le fait que nous avons bien défini le paramètres pour gérer les doublons.

Nous utilisons également l'agent 2.9.0 x64 avec quelques plugins.

**Screenshots**
Notre configuration
![image](https://user-images.githubusercontent.com/10235448/153057362-a920d8a9-917b-4bbe-a82e-e39f8a311617.png)

**Log file (optional)**
Apache / PHP / System log if needed

Suite à la lecture d'anciens bug report, nous avons activé certaines options (https://github.com/OCSInventory-NG/OCSInventory-Server/pull/358/files) et nous obtenons maintenant ce genre de message dans les log:

```
Tue Feb 8 09:11:53 2022;14322;322;L-GMA-18-002456-2021-12-07-11-30-58;10.191.112.192;OCS-NG_WINDOWS_AGENT_v2.9.0.0;notify;IP
Tue Feb 8 09:11:53 2022;14322;323;L-GMA-18-002456-2021-12-07-11-30-58;10.191.112.192;OCS-NG_WINDOWS_AGENT_v2.9.0.0;notify;00:09:0F:AA:00:01<10.191.112.192>
Tue Feb 8 09:11:53 2022;14322;323;L-GMA-18-002456-2021-12-07-11-30-58;10.191.112.192;OCS-NG_WINDOWS_AGENT_v2.9.0.0;notify;F4:8C:50:E8:24:CA<192.168.1.112>
Tue Feb 8 09:28:38 2022;6052;2001;L-GMA-18-002456-2021-12-07-11-30-58;10.191.112.192;OCS-NG_WINDOWS_AGENT_v2.9.0.0;download;1644264546(SUCCESS)
Tue Feb 8 13:50:07 2022;14345;322;L-GMA-18-002456-2021-12-07-11-30-58;10.191.113.21;OCS-NG_WINDOWS_AGENT_v2.9.0.0;notify;IP
Tue Feb 8 13:50:07 2022;14345;323;L-GMA-18-002456-2021-12-07-11-30-58;10.191.113.21;OCS-NG_WINDOWS_AGENT_v2.9.0.0;notify;00:09:0F:AA:00:01<10.191.113.21>
Tue Feb 8 13:50:07 2022;14345;323;L-GMA-18-002456-2021-12-07-11-30-58;10.191.113.21;OCS-NG_WINDOWS_AGENT_v2.9.0.0;notify;F4:8C:50:E8:24:CA<192.168.1.112>
Tue Feb 8 13:50:08 2022;14346;100;L-GMA-18-002456-2021-12-07-11-30-58;10.191.113.21;OCS-NG_WINDOWS_AGENT_v2.9.0.0;prolog;accepted
Tue Feb 8 13:50:08 2022;14346;311;L-GMA-18-002456-2021-12-07-11-30-58;10.191.113.21;OCS-NG_WINDOWS_AGENT_v2.9.0.0;session;started
Tue Feb 8 13:51:33 2022;14400;319;L-GMA-18-002456-2021-12-07-11-30-58;10.191.113.21;OCS-NG_WINDOWS_AGENT_v2.9.0.0;session;found
Tue Feb 8 13:51:33 2022;14400;104;L-GMA-18-002456-2021-12-07-11-30-58;10.191.113.21;OCS-NG_WINDOWS_AGENT_v2.9.0.0;inventory;incoming
Tue Feb 8 13:51:33 2022;14400;113;L-GMA-18-002456-2021-12-07-11-30-58;10.191.113.21;OCS-NG_WINDOWS_AGENT_v2.9.0.0;inventory;u:securitycenter
Tue Feb 8 13:51:33 2022;14400;113;L-GMA-18-002456-2021-12-07-11-30-58;10.191.113.21;OCS-NG_WINDOWS_AGENT_v2.9.0.0;inventory;u:listprinters
Tue Feb 8 13:51:33 2022;14400;113;L-GMA-18-002456-2021-12-07-11-30-58;10.191.113.21;OCS-NG_WINDOWS_AGENT_v2.9.0.0;inventory;u:checkfiles
Tue Feb 8 13:51:33 2022;14400;113;L-GMA-18-002456-2021-12-07-11-30-58;10.191.113.21;OCS-NG_WINDOWS_AGENT_v2.9.0.0;inventory;u:bitlockerstatus
Tue Feb 8 13:51:33 2022;14400;113;L-GMA-18-002456-2021-12-07-11-30-58;10.191.113.21;OCS-NG_WINDOWS_AGENT_v2.9.0.0;inventory;u:drives
Tue Feb 8 13:51:33 2022;14400;113;L-GMA-18-002456-2021-12-07-11-30-58;10.191.113.21;OCS-NG_WINDOWS_AGENT_v2.9.0.0;inventory;u:officepack
Tue Feb 8 13:51:33 2022;14400;113;L-GMA-18-002456-2021-12-07-11-30-58;10.191.113.21;OCS-NG_WINDOWS_AGENT_v2.9.0.0;inventory;u:service
Tue Feb 8 13:51:34 2022;14400;113;L-GMA-18-002456-2021-12-07-11-30-58;10.191.113.21;OCS-NG_WINDOWS_AGENT_v2.9.0.0;inventory;u:customapp
Tue Feb 8 13:51:34 2022;14400;320;L-GMA-18-002456-2021-12-07-11-30-58;10.191.113.21;OCS-NG_WINDOWS_AGENT_v2.9.0.0;session;end
Tue Feb 8 13:51:34 2022;14400;517;L-GMA-18-002456-2021-12-07-11-30-58;10.191.113.21;OCS-NG_WINDOWS_AGENT_v2.9.0.0;duplicate;replacing_error
Tue Feb 8 13:51:34 2022;14400;517;L-GMA-18-002456-2021-12-07-11-30-58;10.191.113.21;OCS-NG_WINDOWS_AGENT_v2.9.0.0;duplicate;replacing_error
Tue Feb 8 13:51:34 2022;14400;101;L-GMA-18-002456-2021-12-07-11-30-58;10.191.113.21;OCS-NG_WINDOWS_AGENT_v2.9.0.0;inventory;transmitted
```

Pour les log au niveau de l'agent:

`Starting OCS Inventory Agent on Tuesday, February 08, 2022 14:07:01.
AGENT => Running OCS Inventory Agent Version 2.9.0.0
AGENT => Using OCS Inventory FrameWork Version 2.9.0.0
AGENT => Loading plug-in(s)
	DLL PLUGIN => Searching for Plug-in DLL(s) in folder <C:\Program Files\OCS Inventory Agent\plugins>
	DLL PLUGIN => 0 DLL Plug-in(s) successfully loaded on 0 DLL(s) found
AGENT => Using network connection with Communication Server
	COM PROVIDER => Loading Communication Provider <C:\Program Files\OCS Inventory Agent\ComHTTP.dll>
AGENT => Using Communication Provider <OCS Inventory cURL Communication Provider> Version <2.9.0.0>
AGENT => Sending Prolog
	DID_CHECK => Read DeviceID <L-SSO-19-006034-2022-02-03-12-05-56> and MACs <0A:00:27:00:00:0800:09:0F:FE:00:0100:09:0F:AA:00:0148:2A:E3:2F:91:A4D4:3B:04:9E:42:A0> in file <ocsinventory.dat>
	COM SERVER => Initializing cURL library for sendRequest
	COM SERVER => Using cURL without server authentication
	COM SERVER => Disabling cURL proxy support
	COM SERVER => Enabling cURL SSL server validation support using CA Bundle <ocsinventory.pem>
	COM SERVER => Sending HTTP Post request to URL <https://ocsinventory.xxxxxxxxx.com/ocsinventory>
	COM SERVER => HTTP Post response received <HTTP Status Code #200>
	COM SERVER => Cleaning cURL library
AGENT => Prolog successfully sent
	AGENT => Prolog Frequency set to 1 hour(s)
	AGENT => Inventory on startup option set to 1 
AGENT => Inventory required
AGENT => Launching hardware and software checks
	INVENTORY => Loading Download history
	INVENTORY => Adding Download Package <1617809715> to report
	INVENTORY => Adding Download Package <1623166772> to report
	INVENTORY => Adding Download Package <1633093697> to report
	INVENTORY => Adding Download Package <1634918199> to report
	INVENTORY => Adding Download Package <1636993932> to report
	INVENTORY => Adding Download Package <1638324397> to report
	INVENTORY => Adding Download Package <1643308371> to report
	INVENTORY => Adding Download Package <1627333936> to report
	INVENTORY => Adding Download Package <1619120761> to report
	INVENTORY => Adding Download Package <1619122249> to report
	INVENTORY => Adding Download Package <1643990284> to report
	INVENTORY => Adding Download Package <1644002951> to report
	INVENTORY => Adding Download Package <1644009341> to report
	INVENTORY => Adding Download Package <1644264546> to report
	INVENTORY => Logged on user ID is <patgag>
	INVENTORY => Operating System is <Microsoft Windows 10 Professionnel 10.0.19044 >, description <>
	INVENTORY => Operating System uses 64 bits memory address width
	INVENTORY => Computer domain or workgroup is <xxxxxxxxx.local>
	INVENTORY => User domain is <>
	INVENTORY => System Manufacturer <LENOVO>, System Model <20LAS33A00>, System S/N <R90T44ZL>, Bios Manufacturer <LENOVO>, Bios Date <13/05/2021>, Bios Version <N27ET42W (1.28 )>, Motherboard Manufacturer <LENOVO>, Motherboard Model <>, Motherboard S/N <W1KS921109K>
	INVENTORY => 1 processor(s) Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz [4 core(s) x86_64] at 1800 MHz
	INVENTORY => OS Memory 16243 MB, OS Swap size 31091 MB
	INVENTORY => 2 memory slot(s) found
	INVENTORY => 5 input device(s) found
	INVENTORY => 13 system port(s) found
	INVENTORY => 2 system slot(s) found
	INVENTORY => 4 system controller(s) found
	INVENTORY => 1 storage peripheral(s) found
	INVENTORY => 5 sound device(s) found
	WARNING *** INVENTORY => Failed to retrieve modems
	INVENTORY => 41 network adapter(s) found
	INVENTORY => 10 system printer(s) found
	INVENTORY => 1 video adapter(s) found
	INVENTORY => 2 system monitor(s) found
	INVENTORY => Default IPv4 address is <192.168.56.1>
	INVENTORY => Registered company <>, registered owner <>, Product ID <00330-51...>
	INVENTORY => Product key <NY6H8-Y8...>
	INVENTORY => 182 software found
	INVENTORY => Computer/VM UUID is <8D8FD84C-2A0D-11B2-A85C-8B1692D63A71>
	INVENTORY => Computer seems to be Microsoft virtual host
	INVENTORY => System Memory set to 16384 (instead of 16243)
	INVENTORY => Reading last inventory state
AGENT =>  Communication Server asks for Registry Query
	REGISTRY => Executing query asked by server
	REGISTRY => 3 query successfully executed
	EXECUTABLE PLUGIN => Searching for VBS script(s) in folder <C:\Program Files\OCS Inventory Agent\plugins>
	EXECUTABLE PLUGIN => Found executable plugin <bitlockerstatus.vbs>
	EXECUTABLE PLUGIN => Plugin <bitlockerstatus.vbs> executed successfully
	EXECUTABLE PLUGIN => Found executable plugin <checkFiles.vbs>
	EXECUTABLE PLUGIN => Plugin <checkFiles.vbs> executed successfully
	EXECUTABLE PLUGIN => Found executable plugin <customapp.vbs>
	EXECUTABLE PLUGIN => Plugin <customapp.vbs> executed successfully
	EXECUTABLE PLUGIN => Found executable plugin <listprinters.vbs>
	EXECUTABLE PLUGIN => Plugin <listprinters.vbs> executed successfully
	EXECUTABLE PLUGIN => Found executable plugin <msofficekey.vbs>
	EXECUTABLE PLUGIN => Plugin <msofficekey.vbs> executed successfully
	EXECUTABLE PLUGIN => Found executable plugin <security.vbs>
	EXECUTABLE PLUGIN => Plugin <security.vbs> executed successfully
	EXECUTABLE PLUGIN => Found executable plugin <teamviewer.vbs>
	EXECUTABLE PLUGIN => Plugin <teamviewer.vbs> executed successfully
	EXECUTABLE PLUGIN => Searching for PS1 script(s) in folder <C:\Program Files\OCS Inventory Agent\plugins>
	EXECUTABLE PLUGIN => Found executable plugin <Saas.ps1>
	WARNING *** EXECUTABLE PLUGIN => Plugin <C:\Program Files\OCS Inventory Agent\plugins\Saas.ps1> does not produce any output
	EXECUTABLE PLUGIN => Found executable plugin <services.ps1>
	EXECUTABLE PLUGIN => Plugin <services.ps1> executed successfully
	EXECUTABLE PLUGIN => Found executable plugin <winusers.ps1>
	EXECUTABLE PLUGIN => Plugin <winusers.ps1> executed successfully
AGENT => Sending Inventory
	INVENTORY => Checking last inventory state
	INVENTORY => Logical drives inventory state changed
INVENTORY => Inventory changed since last run
	INVENTORY => Generating XML document with Device properties
	INVENTORY => XML Update BIOS
	INVENTORY => XML Update 1 CPU(s)
	INVENTORY => XML Update 2 Memory Slot(s)
	INVENTORY => XML Update 5 Input Device(s)
	INVENTORY => XML Update 13 System Port(s)
	INVENTORY => XML Update 4 System Controller(s)
	INVENTORY => XML Update 2 System Slot(s)
	INVENTORY => XML Update 5 Sound Device(s)
	INVENTORY => XML Update 1 Storage Peripheral(s)
	INVENTORY => XML Update 2 Logical Drive(s)
	INVENTORY => XML Update 0 Modem(s)
	INVENTORY => XML Update 41 Network Adapter(s)
	INVENTORY => XML Update 1 Video Adapter(s)
	INVENTORY => XML Update 2 Monitor(s)
	INVENTORY => XML Update 10 Printer(s)
	INVENTORY => XML Update 183 Software
	INVENTORY => XML Update 1 Registry Value(s)
	INVENTORY => XML Update Administrative Information(s)
	INVENTORY => XML Update common Device properties
	COM SERVER => Initializing cURL library for sendRequest
	COM SERVER => Using cURL without server authentication
	COM SERVER => Disabling cURL proxy support
	COM SERVER => Enabling cURL SSL server validation support using CA Bundle <ocsinventory.pem>
	COM SERVER => Sending HTTP Post request to URL <https://ocsinventory.xxxxxxxx.com/ocsinventory>
	COM SERVER => HTTP Post response received <HTTP Status Code #200>
	COM SERVER => Cleaning cURL library
AGENT => Inventory successfully sent
	INVENTORY => Writing new inventory state
AGENT =>  Communication Server asked for Package Download
	DOWNLOAD => Package history file successfully cleaned for duplicate IDs
DOWNLOAD => Download and setup tool successfully started
AGENT => Unloading communication provider
AGENT => Unloading plug-in(s)
AGENT => Execution duration: 00:02:59.

`

**Comment by thenamelessthing** [comment]
Nous avons effectué vendredi dernier la mise à niveau vers la dernière version (2.9.2) et même comportement. 

Nous remarquons également que lorsque nous nous connectons dans ocsreports, le CPU du serveur top à 100% jusqu'à ce que l'ouverture de session soit complété.

**Comment by thenamelessthing** [comment]
Bon, nous avons réglé le problème de login dont le CPU atteignait 100%, en activant 

![image](https://user-images.githubusercontent.com/10235448/160133444-3dc4bbaf-b881-4cb7-8f45-4e6ae9db52c9.png)


Il ne reste que la gestion des duplicata qui ne semble pas fonctionner..

**Comment by charleneauger** [comment]
Bonjour,

La version 2.9.2 possède plus de logs concernant les erreurs de dupliqué. Pouvez-vous me fournir à nouveau vos logs présents dans activity.log ?

Cordialement,
Charlène

**Comment by thenamelessthing** [comment]
Voici quelques extrait:

![image](https://user-images.githubusercontent.com/10235448/160905770-351ccb59-0d6d-49b0-a259-d2f620b17f9e.png)


![image](https://user-images.githubusercontent.com/10235448/160905413-f99395f7-481f-4fda-a392-05694bae4f1e.png)

![image](https://user-images.githubusercontent.com/10235448/160908219-f475491f-8440-4015-aa2a-6d39be28f181.png)

**Comment by thenamelessthing** [comment]
Bonjour @charleneauger , est-ce que l'extrait que je vous ai fourni vous aide à comprendre ce qui se passe? Merci

**Comment by thenamelessthing** [comment]
> 

> Bonjour @thenamelessthing ,
> 
> Je suis désolée pour le délais. Comme vous pouvez le voir dans les logs, cette ligne nous intéresse : `error to delete hardware_id from uptime`
> 
> Pouvez-vous vérifier que le plugin uptime est bien désinstallé de votre serveur ? Si il est désinstallé de votre console d'administration (ocsreports), il faut vérifier que les fichiers côté serveur soient aussi enlevés (/etc/ocsinventory-server)
> 
> Cordialement, Charlène

Merci pour le retour et pour le délais, je dirais que vaut mieux tard que jamais!

Je viens d'effacer le fichier .conf dans /etc/ocsinventory-server/plugins

Je vous ferez savoir si cela résout le problème d'ici quelques jours.

**Comment by thenamelessthing** [comment]
Par curiosité, pourquoi le fait de laisser un fichier de plugin inutilisé dans le dossier plugin peut provoquer ce genre de comportement?

**Comment by thenamelessthing** [comment]
@charleneauger , je confirme que cela semble avoir corrigé le problème! 

Je remarque que j'ai quelques cas dont le no de série ne semble pas correctement récupéré par l'agent:

![image](https://user-images.githubusercontent.com/10235448/170049802-b3bc9185-a417-4e75-bd7c-130bbd9df34a.png)


Il y a quelque chose que je peux faire pour corriger cela on c'est plus un bug?

**Comment by charleneauger** [comment]
Bonjour @thenamelessthing ,

Le serveur OCS va récupérer les fichiers de conf des plugins lors d'un inventaire. Si le plugin est désinstallé en webconsole, la table MYSQL correspondant à ce plugin n'existe plus. Sauf que pour le serveur si. Et donc dans le cas d'un duplicata, au moment du merge entre les deux machines, le serveur va aller supprimer l'id de l'ancienne machine dans la table plugin qui n'existe plus et engendrer une erreur.

Concernant le problème de numéro de série, nous avons déjà rencontré ce problème. Afin de pallier à ça, modifiez votre fichier Map.pm dans /usr/local/share/perl/version_perl/Apache/Ocsinventory.  Pour la partie `bios` passez la valeur du `mask` à 0. Sauvegardez et redémarrez Apache.
Une PR sera faite prochainement pour ce problème :-)

Cordialement,
Charlène
