### ISSUE TITLE
[BUG] sso - kerberos 

### ISSUE THREAD

**Issue by sborion** [OCSInventory-NG/OCSInventory-ocsreports#1339]
**OCS Inventory version**
Version : 2.9.1

**Describe the bug**
same as issue 1105 :  https://github.com/OCSInventory-NG/OCSInventory-ocsreports/issues/1105  (closed because no answer) 

When active mode SSO ( define('AUTH_TYPE', 4); ), we get an empty page 

The $_SESSION['OCS']['cnx_origine']   is null 

Then in backend/identity/methode/ldap.php
we can’t pass the line : 
```
if ($_SESSION['OCS']['cnx_origine'] != "LDAP") {
   return false;
}
```
If i comment this line. It’s work.

**Comment by sborion** [comment]
In SSO mode, for the auth, it use the AUTH/methode/always_ok.php and not the AUTH/methode/ldap.php.
Because the ldap.php do the authentification on ldap (and it doesnt work in sso because no passwd) , but also do the synchronisiation ldap...
If you want, i can propose some change tomorrow, by a pull request for this issue .

**Comment by Lea9250** [comment]
Hi @sborion,

Since you've already made a PR for this, I'll close the issue and we'll continue the discussion on #1341 .

Regards,
Léa
