### ISSUE TITLE
Dynamic Groups not working as expected

### ISSUE THREAD

**Issue by gnalawade** [OCSInventory-NG/OCSInventory-ocsreports#134]
CentOS 7.2 / PHP 5.4.16 / OCS 2.2.1

Using "Search with various criteria" created dynamic group without any issue but don't see any group created under group tab.  Also I am see errors in the apache logs

[Thu Sep 22 13:14:34.261957 2016] [:error] [pid 33634] [client 172.29.230.71:53889] PHP Warning:  mysqli_fetch_array() expects parameter 1 to be mysqli_result, boolean given in /usr/share/ocsinventory-reports/ocsreports/plugins/computer_detail/cd_configuration/cd_configuration.php on line 279, referer: http://inventory.testdomain.com/ocsreports/index.php?function=computer&head=1&systemid=513
[Thu Sep 22 13:14:51.718100 2016] [:error] [pid 33895] [client 172.29.230.71:53899] PHP Warning:  mysqli_fetch_array() expects parameter 1 to be mysqli_result, boolean given in /usr/share/ocsinventory-reports/ocsreports/plugins/computer_detail/cd_configuration/cd_configuration.php on line 279, referer: http://inventory.testdomain.com/ocsreports/index.php?function=computer&head=1&systemid=512
[Thu Sep 22 13:15:10.833074 2016] [:error] [pid 34008] [client 172.29.230.71:53912] PHP Warning:  mysqli_fetch_array() expects parameter 1 to be mysqli_result, boolean given in /usr/share/ocsinventory-reports/ocsreports/plugins/computer_detail/cd_configuration/cd_configuration.php on line 279, referer: http://inventory.testdomain.com/ocsreports/index.php?function=computer&head=1&systemid=257&option=cd_configuration&grp=1866&actgrp=0
[Thu Sep 22 13:25:59.956492 2016] [:error] [pid 33949] [client 172.29.230.71:54207] PHP Warning:  mysqli_fetch_array() expects parameter 1 to be mysqli_result, boolean given in /usr/share/ocsinventory-reports/ocsreports/require/function_groups.php on line 40, referer: http://inventory.testdomain.com/ocsreports/index.php?function=visu_search
[Thu Sep 22 13:26:04.944220 2016] [:error] [pid 33949] [client 172.29.230.71:54207] PHP Warning:  mysqli_fetch_array() expects parameter 1 to be mysqli_result, boolean given in /usr/share/ocsinventory-reports/ocsreports/require/function_groups.php on line 40, referer: http://inventory.testdomain.com/ocsreports/index.php?function=groups_search&head=1&idchecked=1736,1653,1652,1723,1519,1555,1760,1227,1620,1040,1330,1101,1233,1212,1696,1606,1675,1665,1608,1220,1719,1631,1398,1448,1706,1762,1637,1735,1500,1734,1229,1669,1305,1692,1671,1624,1717,1743,1695,1718,1015,1728,1677,1741,1371,1709,1501,1699,1684,1324,968,1690,1658,1293,1682,1449,1746,1152,1563,1761,1730,1732,1235,1383,1753,1649,1335,1056,1655,1754,1205,1615,1702,1722,1739,1454,1280,1090,1749,1729,1044,1672,970,1712,1745,1524,1096,1705,1697,994,1731,1651,1681,1750,1203,1685,1698,1047,1679,1701,1403,1678,1332,1738,1322,1670,1666,1146,1601,981,1184,1700,1703,1752,1260,1727,1319,1372,1683,1560,1027,1756,1204,1051,1776,1423,1388,1483,1744,1556,1328,1545,1477,1584,1139,1309,1716,1270,1714,1711,1314,944,1708,1713,1587,1520,1381,1221,1119,1135,1693,1375,1450,1686,1130,1777,1020,1578,1688,1226,983,1667,1342,1168,1759,1632,1114,1724,1160,1180,1747,1616,1115,956,1726,1721,1740,1733,1034,1757,1106,1366,1764,1725,992,1674,1434,1109,965,1673,1737,1680,1571,1511,973,1373,1676,1435,1742,1755,1268,1099,1704,1525,1660,957,1302,1026,1715,1539,1349,1222,1117,1694,1763,1758,1527,1468,1689,1574,1654,1190

Now, it is showing below errors in apache error logs

DBD::mysql::st execute failed: Table 'ocsweb.groups' doesn't exist at /usr/local/share/perl5/Apache/Ocsinventory/Server/Groups.pm line 60.
DBD::mysql::st execute failed: Table 'ocsweb.groups' doesn't exist at /usr/local/share/perl5/Apache/Ocsinventory/Server/Groups.pm line 60.

**Comment by gillesdubois** [comment]
Hi,

Can you check if the groups table exist in your ocs database ?
Look like this one is missing.

Regards,
Gilles Dubois.

**Comment by gnalawade** [comment]
Hello,
I don't think groups is created but only I see groups_cache is created. I tried manually copy groups_cache to groups but that did not help either, which throws different errors 

DBD::mysql::st execute failed: Unknown column 'REVALIDATE_FROM' in 'where clause' at /usr/local/share/perl5/Apache/Ocsinventory/Server/Groups.pm line 60.
DBD::mysql::st execute failed: Unknown column 'REVALIDATE_FROM' in 'where clause' at /usr/local/share/perl5/Apache/Ocsinventory/Server/Groups.pm line 60.
DBD::mysql::st execute failed: Unknown column 'REVALIDATE_FROM' in 'where clause' at /usr/local/share/perl5/Apache/Ocsinventory/Server/G

**Comment by gillesdubois** [comment]
Hi,

This bug has been fixed in the 2.3 version, you should update your ocsinventory server and try again :)

Regards,
Gilles Dubois.
