### ISSUE TITLE
[BUG] Inventory works but without the plugins informations

### ISSUE THREAD

**Issue by jaimepaslespubs** [OCSInventory-NG/OCSInventory-ocsreports#1340]
**OCS Inventory version**
Version : 2.9.2

**Describe the bug**
The inventories work correctly, but if we add "official" plugins, the inventory goes back to the server, but not the information collected by the plugins.
When doing a local inventory, we can see the XML tags with the data expected from the plugins.
This bug is not present in an earlier version, 2.9.0 or 2.9.1

**To Reproduce**
Add a plugin (example: Scheduled Tasks) in the directory /usr/share/ocsinventory-reports/ocsreports/extensions, unpack it.
Add the plugin via the web interface Extensions > Extentions manager
Add the plugin in the agent (vbs file)
Launch the inventory and check on the web interface if the data appear (not present in the database). Check the XML file in local inventory to see if the information is presented to the server
The problem can be reproduced for a Unix agent

**Expected behavior**
Informations from plugin

**Log file (optional)**
No message in log file

**Comment by charleneauger** [comment]
Hi @jaimepaslespubs ,

I think you are missing part of your plugin installation.
Please read the part of the [Using extension engine](http://wiki.ocsinventory-ng.org/10.Plugin-engine/Using-plugins-installer/) documentation : `Scripted communication server installation` or `Server installation without script`.

Best regards,
Charlene Auger
