### ISSUE TITLE
After login nothing can be done for restricted user

### ISSUE THREAD

**Issue by sreerajp** [OCSInventory-NG/OCSInventory-ocsreports#1345]
**OCS Inventory version**
Version : 2.9.2

**Describe the bug**
When a restricted user is created with Computer restrictions to some TAG user can't do anything after login. The message "Column 'netid' in order clause is ambiguous" is coming.

**To Reproduce**
Create a user with following profile values
Computer Restrictions to YES
Package Activation Restrictions to YES
Pages allowed are account_config, admin_double, admin_values, computer, console, export_csv, export_soft, ms_comparedevices, search_soft_option, server_infos, show_ipdiscover, tag_search, visu_all_soft, visu_computers, visu_repart_tag and visu_search
2. Create a TAG and assign the TAG to the user
3. Login as the user

![image](https://user-images.githubusercontent.com/26023313/155313760-43f1d354-9588-4db8-ad6c-ec5d9d8359b1.png)

![image](https://user-images.githubusercontent.com/26023313/155313927-742281ca-ab92-480a-a5df-8f0b62ef4664.png)

**Comment by sreerajp** [comment]
Anybody planning to check this as we can't use OCSInventory due to this

**Comment by Mimosa693** [comment]
Hi,

In this file : /usr/share/ocsinventory-reports/ocsreports/backend/ipdiscover/methode/local.php
You can replace this line : 
`$req .= " and " . $_SESSION['OCS']["mesmachines"] . " order by netid";`
with : 
`$req .= " and " . $_SESSION['OCS']["mesmachines"] . " order by n.netid";`

**Comment by charleneauger** [comment]
Hi @sreerajp ,

This bug has been fix with the PR #1320.

Best regards,
Charlene
