### ISSUE TITLE
IPdiscover tab shows every IP as different subnet

### ISSUE THREAD

**Issue by gnalawade** [OCSInventory-NG/OCSInventory-ocsreports#135]
CentOS 7.2 / PHP 5.4.16 / OCS 2.2.1

Some of Subnets shows each server IP address in network section which is wierd. 

Please refer attached screenshot
![screen shot 2016-09-26 at 3 21 20 pm](https://cloud.githubusercontent.com/assets/6558408/18854028/75050dc8-83fd-11e6-8695-a5fd1cfb7610.png)

**Comment by gillesdubois** [comment]
Hi,

Can you provide more informations ?
- How many networks encounter this problem ?
- Which network types encounter this problem ?
- Agents on these networks ?

Regards,
Gilles Dubois.

**Comment by gnalawade** [comment]
Hello Gilles,

here are my comments

**How many networks encounter this problem ?**
These are observed for different networks/vlan
**Which network types encounter this problem ?**
There is no specific network have this issue. it is for most of network are production LAN class A
**Agents on these networks ?**
10-20% servers have ocsagents installed with ipdiscover agent enabled for 2 only

Thanks,
Ganesh

**Comment by gillesdubois** [comment]
Hi,

Sorry for the delay.
Your problem doesn't occur on your dev environnement.
What mask are you using ?

Did you try to update to 2.3RC ? IPDiscover got a little rework so it could have fixed your problem.

Regards,
Gilles Dubois.

**Comment by gnalawade** [comment]
Thank you. I will test it
