### ISSUE TITLE
[BUG] LDAP authentication not working / User not registered

### ISSUE THREAD

**Issue by Erlum** [OCSInventory-NG/OCSInventory-ocsreports#1350]
[Environment]

OCS 2.9.2 / Rocky (RHEL) 8.5 / Active Directory as LDAP

[Bug Description]

Hi,

I've set up a brand new OCS Server on a Rocky (RHEL compatible) 8.5 using DNF and the official repos.
I have configured LDAP the same way it was on another OCS server, and adapted the configuration for the new "CONEX_LDAP_FILTER" fields. I changed var.php so that AUTH_TYPE is defined to 2.

When I try to connect using my AD user, I get the following error : "User not registered".

I have looked at the logs and found one wrong path for /plugins in a HTTPd conf file which generated an AH01630 error.
I fixed the path (it targeted /var/lib and not /usr/share) and I don't have any errors anymore, only HTTP 200 codes.

Some further analysis with tcpdump revealed a very strange behaviour : the whole HTTP request is closed without any LDAP communication occuring between OCS and AD. Sometimes there is some trafic on port 389, but it happens several seconds after the page has been sent back to client ; and sometimes there is absolutely no trafic.

What I have tried in parallel : disabling SELinux and FirewallD, trying 3 and 4 for AUTH_TYPE.

Is there some breaking change on this version that I am not aware about ?

Regards

**Comment by Erlum** [comment]
Hi, has anyone been able to take a look at this ?
Regards

**Comment by charleneauger** [comment]
Hi @Erlum ,

Some fix has been made on LDAP feature since the 2.9.2 release. Can you install a nightly version and tell me if the problem persist ?

Best regards,
Charlene

**Comment by Erlum** [comment]
Hi again ? 
Is there a new release planned ? Or a way to install the nightly with the repos ?
Regards

**Comment by charleneauger** [comment]
Hi @Erlum 

Sorry for the delay. 

I didn't see that your server was in RPM.
Unfortunately, it is not possible to install a nightly in RPM.
A version 2.9.3 is planned for the middle of the year.

Regards,
Charlene

**Comment by Erlum** [comment]
Hi,

No problem. This is not a business critical issue so we'll wait until the next release to patch.
Thank you very much for your answer.

Regards

**Comment by Erlum** [comment]
Hi @charleneauger 

I updated our instance to 2.10 and it is still not working.

In var.php, AUTH_TYPE is set to 2 but I don't see any traffic on part 389. I also tried to set it to 3 without any impact.

All I get client-side is a "No user provided" message.

Regards

**Comment by Erlum** [comment]
I'll try to take some time to spin up a new instance and see if I can produce the bug again.

**Comment by Erlum** [comment]
Hi @charleneauger 

Did not have to spin up another instance in the end.

The problem was nested groups... I commented on this issue regarding this : https://github.com/OCSInventory-NG/OCSInventory-ocsreports/issues/177

Do you think it would be possible to add this feature ?

Regards

**Comment by Erlum** [comment]
OK I found a fix for that. You can use a more specific "memberOf" attribute that checks for nested groups : https://confluence.atlassian.com/crowdkb/active-directory-user-filter-does-not-search-nested-groups-715130424.html

In the end my filter looks like this : &(memberOf:1.2.840.113556.1.4.1941:=CN=OCS,OU=GROUPES,DC=Blabla,DC=org)
Works like a charm

Regards

**Comment by gillesdubois** [comment]
Hi @Erlum 

Indeed using memberOf nested group should be managed / processed properly.
I'm glad you managed to fix your issue :)

I'll now close your issue.

Regards,
Gilles.
