### ISSUE TITLE
Microsoft Defender Plugin

### ISSUE THREAD

**Issue by sokatra** [OCSInventory-NG/OCSInventory-ocsreports#1355]
**Is your feature request related to a problem? Please describe.**
I have no information about the Microsoft defender status from all the endpoint computers.

**Describe the solution you'd like**
I wonder if it is possible to create a Microsoft Defender plugin. It is so easy to get the antivirus status via powershell.
For example you gen get the last threat via this command
get-mpthreat

![image](https://user-images.githubusercontent.com/17703360/158788645-1637a099-8044-4b44-ad76-b57fd2c3418e.png)

https://www.powershellcenter.com/2021/07/21/windows-defender-powershell/

**Describe alternatives you've considered**
perhaps a universal module which can equipped with specific powershell commands .. and in the "module" just visualizes the return of the command in some way. You can customize which return field should be visualized and you can customize the powershell command. 
Think of it like the registry function in ocs-inventory .. just with powershell commands

**Comment by sokatra** [comment]
they have a plugin which reports the stats of defender
https://github.com/kevintijssen/check_mk/blob/master/Windows/Defender/agents/plugins/win_defender.ps1

**Comment by gillesdubois** [comment]
Hi,

Since @Fish-dev2 seems to have provided a answer, I'll now be closing the issue.

Please note that the security plugin is also able to give security information on security defence systems.

Regards,
Gilles.
