### ISSUE TITLE
Windows Events Plugin

### ISSUE THREAD

**Issue by sokatra** [OCSInventory-NG/OCSInventory-ocsreports#1356]
**Is your feature request related to a problem? Please describe.**
It would be nice if i can see specific events from every client.

**Describe the solution you'd like**
I need a plugin where i can configure which events i want to see from client.
For example event id 6008 from "system events" which reports a unexpected shutdown
or event id 1007 from 
Applications and Services Logs, then Microsoft, then Windows, then Windows Defender when a virus was found.
It should be configurable for every event from every specific event source.

https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/troubleshoot-microsoft-defender-antivirus?view=o365-worldwide

**Describe alternatives you've considered**
Create a script (in a deployment package) which gets the event via powersehell an report the event id back to ocs-inventory server via errorcode.
I had already done this .. but this is annoying

**Comment by sokatra** [comment]
Get-WinEvent -LogName "Microsoft-Windows-Windows Defender/Operational"|select -First 10
to get last 10 defender events

**Comment by gillesdubois** [comment]
Hey,

A new plugin allow you to retrieve windows event log.
Link : https://github.com/PluginsOCSInventory-NG/eventlogs/

Regards,
Gilles.
