### ISSUE TITLE
[BUG] conditions recherche multi-critères cassé

### ISSUE THREAD

**Issue by thenamelessthing** [OCSInventory-NG/OCSInventory-ocsreports#1357]
**OCS Inventory version**
Version : 2.9.2

**Describe the bug**
Lorsque j'effectue une recherche multicritères avec certaines "conditions" le résultats affiché n'est pas correct.

**To Reproduce**
Je veux par exemple n'afficher que les ordinateurs n'ayant pas comme valeur (20H2 et 21H2) dans le registre pour la clé de registre qui se nomme "Windows10_Build". 

J'effectue donc une recherche de ces clés mais en indiquant comme opérateur "doesn't contain". Voir capture d'écran plus-bas.
J'ai également essayé avec l'opérateur "different" avec le même résultat.

**Expected behavior**
Il faudrait que le résultat ne contienne pas les valeurs que j'exclus dans ma recherche.

**Screenshots**
![image](https://user-images.githubusercontent.com/10235448/159540856-195a775a-e849-43e0-9425-ac97a6f353ed.png)

**Log file (optional)**
Apache / PHP / System log if needed

**Comment by Minikea** [comment]
problème de logique, il faut un AND, pas un OR

**Comment by thenamelessthing** [comment]
Effectivement, je viens de comprendre mon erreur! Mes excuses!

**Comment by thenamelessthing** [comment]
Je viens d'essayer et toujours le même résultat...

![image](https://user-images.githubusercontent.com/10235448/159697090-3f4e35ac-9501-42e8-aa2a-ec0c5421903c.png)

**Comment by thenamelessthing** [comment]
Autre problème plutôt étrange possiblement relié. Si je fait la requête suivante et qu'a partir de cette requête je crée un groupe dynamique. Le groupe ne contient pas les 14 résultat de ma requête mais plutôt 205 ordinateurs!

La requête: 

![image](https://user-images.githubusercontent.com/10235448/159699836-c2de1956-ae05-41bd-8a0e-0c8ea72c6811.png)


Voici ce que ça donne:

![msedge_2022-03-23_08-29-37](https://user-images.githubusercontent.com/10235448/159699517-63e36eec-f233-4865-ae80-d034bef0dedf.gif)

**Comment by Minikea** [comment]
> Je viens d'essayer et toujours le même résultat...
> 
> ![image](https://user-images.githubusercontent.com/10235448/159697090-3f4e35ac-9501-42e8-aa2a-ec0c5421903c.png)

et avec NOT LIKE à la place de DOESN'T CONTAIN ?

**Comment by thenamelessthing** [comment]
@Minikea je n'ai pas "not like" à proprement parler dans les choix. Mais plutôt "DIFFERENT" comme choix ou encore "DOESN'T CONTAIN". Voici ce que ca donne, toujours la même chose..

![image](https://user-images.githubusercontent.com/10235448/159712109-f6f4de42-a548-4018-8499-3d1ac7eecc68.png)
