### ISSUE TITLE
IPdiscover don't show progress in percentage

### ISSUE THREAD

**Issue by gnalawade** [OCSInventory-NG/OCSInventory-ocsreports#136]
IPdiscover infact shows discovered inventory but doesn't show percentage. 

Refer attached screenshot -

![screen shot 2016-09-28 at 11 57 23 am](https://cloud.githubusercontent.com/assets/6558408/18928025/38ded17c-8573-11e6-8ef0-b9442d75416f.png)

**Comment by gillesdubois** [comment]
Hi,

Your bug has been fixed.
Here is the ipdiscover percentage behavior : 
- If there is no IPDiscover data and no Identified data = 100 %
- If there is no Identified data percentage is done between Inventoried and Non-Inventoried
- If there is Identified data percentage is done using this math : ( Inventoried + Identified ) * 100 / Non-Inventoried

Thanks for your report.

Regards,
Gilles Dubois.

**Comment by proyectotau** [comment]
### General informations
OS Name : Linux x86_64
Version : 3.10.0-693.el7.x86_64
Distribution : Red Hat Enterprise Linux Server 7.4 (Maipo)

### Server installation method ( Only one choice )
- [ ] RPM Package
- [X] Install SH
- [ ] Manual installation

### Server informations
PHP Version : 5.4.16
Web Server : Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips PHP/5.4.16 mod_perl/2.0.10 Perl/v5.16.3
Database Server : MySQL Enterprise Server - Advanced Edition (Commercial) version 5.7.18-enterprise-commercial-advanced

### OCS Inventory informations
Ocsreports version : 2.4.1

### Problem's description

This still fails ;-(

This is in my current version:
![screenshot before fix](https://user-images.githubusercontent.com/24544980/51257955-1c829c80-19a9-11e9-96bd-1db427e6290c.png)

This one, with my fix:
![screenshot after fix](https://user-images.githubusercontent.com/24544980/51258048-4e93fe80-19a9-11e9-9cd0-042a185f0bd5.png)

### My proposal is

> CASE WHEN ipdiscover.c IS NULL or non_ident.c IS NULL THEN 100
> WHEN ident.c IS NULL THEN round(inv.c * 100 / (inv.c + non_ident.c),1)
> ELSE round((inv.c + ident.c) * 100 / (inv.c + ident.c + non_ident.c),1) END as 'pourcentage'

Thanks in advance!

**Comment by proyectotau** [comment]
Hi @gillesdubois 

Do I have to send you a PR or you merge it on your own?

If do I, which version must I use to merge on?

Thanks in advance!

**Comment by proyectotau** [comment]
Thanks!

I can see in master that my contribution is substantially the same than that fixed in #595 by @alacn1

Sorry for the noise!
