### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Escanor81** [OCSInventory-NG/OCSInventory-ocsreports#1360]
Hi,

**OCS Inventory version**
Version : 2.9.2

**Describe the bug**

When updating from version 2.9.1 to 2.9.2 we have stopped being able to access the OCS console.
Neither locally nor by LDAP. When accessing using a local password, the following message appears:
''User not registered''
By LDAP:
''No rights level defined to your profile, please contact your administrator''
A standard installation was carried out and only the access data to the database has been modified.

**Screenshots**

![ocs1](https://user-images.githubusercontent.com/103119286/161975193-f33ff403-76f5-4b55-9bd4-783d1eceebcc.JPG)
![ocs2](https://user-images.githubusercontent.com/103119286/161975343-04d8c25e-e848-424f-b262-e62ced6db7f8.JPG)

Thanks for the help

**Comment by gillesdubois** [comment]
Hi,

LDAP fitlers have changed with the 2.9.2.
Please see : https://wiki.ocsinventory-ng.org/04.Management-console-and-its-advanced-features/Synchronization-between-OCS-and-LDAP/#manage-authentification-with-ldap

Regards,
Gilles.

**Comment by Escanor81** [comment]
Hello
This article has already been reviewed.
It does not seem likely that it is a failure of the LDAP filters, since access with local users also fails. Even with the user ''Admin''.

Greetings

**Comment by gillesdubois** [comment]
Did you change the AUTH_TYPE in the var.php ? this file is overrided at each update.

Regards,
Gilles.

**Comment by Escanor81** [comment]
Hello
If you make a backup of all the configuration files of version 2.9.1
With the var.php file, I have tried using options 1 and 3 and they give me the same problem.
It is not possible to access with any account.
