### ISSUE TITLE
[FEATURE] Email notification when unknown devices are discovered

### ISSUE THREAD

**Issue by imponimassacri** [OCSInventory-NG/OCSInventory-ocsreports#1363]
**Is your feature request related to a problem? Please describe.**
The Italian IT security legislation requires to keep an inventory of the resources that are present on the network, in order to notice when unknown devices are connected. With Ip Discover feature it's possible to keep track of non-inventoried devices discovered, but it is necessary to carry out periodic checks manually

**Describe the solution you'd like**
The problem of manual checks could be solved by sending an email notification whenever an unknown device is discovered

**Describe alternatives you've considered**
The sending of the e-mail could be scheduled at regular intervals, if the notification in real time were difficult to implement

**Comment by gillesdubois** [comment]
Hi,

OCS is a Inventory tool and not a monitoring tool thus, our data model is not made in a way that allow to track changes / modification in the IP Discovery tables.

Imo, this type of alert / actions are more specific to security oriented softwares or monitoring services.

Regards,
Gilles.
