### ISSUE TITLE
network printers not displayed

### ISSUE THREAD

**Issue by gitmais** [OCSInventory-NG/OCSInventory-ocsreports#137]
server OCS 2.2.1  / client  2.1.1.3

When I right click on the icon "systray "/ view inventory information, I see only my local printers in the ocs agent popup. On my server too, i see only my local printers.

But when i execute a : "ocsinventory.exe /xml", i see in the xml generated file my network printers (names begin with "\\\") After executing this command, i also see them on the server ! 

Maybe a bug with "\\\" ?

**Comment by gillesdubois** [comment]
https://github.com/OCSInventory-NG/WindowsAgent/issues/11

**Comment by gitmais** [comment]
Hi,
J'ai déjà jeté un coup d'oeil, car si tu regardes plus attentivement, tu verras que j'ai répondu sur ce thread.
Aller vers un plugin ne va pas résoudre le problème que j'ai signalé.
