### ISSUE TITLE
[BUG] scheduledupdateagent.ps1 does not work

### ISSUE THREAD

**Issue by Laurent-1971** [OCSInventory-NG/OCSInventory-ocsreports#1371]
**OCS Inventory version**
Version : 2.9.2

**Describe the bug**

Upgrade of Windows agent using "Build / Windows / Install / Update Agent" does not work

When the package is downloaded on the agent machine, 3 files arrive on "C:\Windows\Temp\<package_number>.OCS" directory : 
the 2 powershell scripts and ocsupdate.exe
But ocsupdate.exe arrives with the hidden flag

```
Répertoire : C:\WINDOWS\TEMP\1651663578.OCS

Mode                 LastWriteTime         Length Name                                                                 
----                 -------------         ------ ----                                                                 
-a----        04/05/2022     16:45             10 OCSNG-Windows-Agent-PackageID                                        
-a-h--        04/05/2022     13:26        5959803 ocsupdate.exe                                                        
------        12/01/2022     20:18           2461 removeupdateagent.ps1                                                
-a----        04/05/2022     13:00           1700 scheduledupdateagent.ps1
```

So the "Move-Item "$location\\*.exe" -Destination "$path\ocsupdate.exe"" in scheduledupdateagent.ps1 ignores the file

**Comment by brizao** [comment]
Hi Laurent, I'm still struggling with it, since I updated to OCS server 2.9.x, I can't update Windows agents.

The new deployment update agent uninstalls the current agent but it doesn't install the new one (created through OCSPackager), the log shows the error: "No package found, exiting".

If I try the "old" way, using custom package, it happens the same as here: https://github.com/OCSInventory-NG/WindowsAgent/issues/241
Even if I omit the /UPGRADE parameter... so I don't know what to do...

**Comment by Laurent-1971** [comment]
Hi Brizao,
I have modified "/usr/share/ocsinventory-reports/ocsreports/config/teledeploy/script/scheduledupdateagent.ps1"
Line 15
From
**Move-Item "$location\*.exe" -Destination "$path\ocsupdate.exe"**
To
**Move-Item "$location\ocsupdate.exe" -Destination "$path\ocsupdate.exe"**

**Comment by brizao** [comment]
It really worked! Thanks!

**Comment by charleneauger** [comment]
Thanks to @LMS235 for fixing this issue. :-)
I close your issue.

Best regards,
Charlene

**Comment by mtbadi39** [comment]
Hi,
The bug still existe : Upgrade of Windows agent using "Build / Windows / Install / Update Agent" does not work, the ocsupdate.exe arrives with the hidden flag.
OCS Reports 2.11.1 on Ubuntu 22.04.1 LTS / Windows-Agent-2.10.0.0_x64
