### ISSUE TITLE
[BUG] - Saved Searches, cant save search

### ISSUE THREAD

**Issue by somzoli** [OCSInventory-NG/OCSInventory-ocsreports#1372]
**OCS Inventory version**
Version : 2.9.2

**Describe the bug**
When i save my search, after doesn't show in "saved searches".

**To Reproduce**
Just save a search (all users permission)

**Expected behavior**
Save searches

**Comment by gillesdubois** [comment]
Hi @somzoli 

Could you try to update to the 2.10.0 version ?
We applied a few patches on the saved searches on this version.

Regards,
Gilles.

**Comment by somzoli** [comment]
Hi.

thank you for reply. Yes, the latest server version solved this problem. its closable :)

BR,
Z
