### ISSUE TITLE
Problem with duplicates devices

### ISSUE THREAD

**Issue by cearanda** [OCSInventory-NG/OCSInventory-ocsreports#1375]
**OCS Inventory version**
Version : 2.9.1

**Describe the bug**
We have problems with duplicated devices. There are some computers that they duplicate always (every contact server create 1 new device). I don't understand that.

we also have a problem with devices fusion. We have configured the auto_duplicate_lvl with "Serial, macaddress and AssetTag". It means that if i have two computers with the same serial, macaddress and assettag they must be to fusion, but it isn't work.

Behind, with the 2.1.2 version it was work. With 2.8 version and 2.9 version we don't fix that.

Thank you very much.

**Expected behavior**
I undestand that something it is wrong. It isn't normal that a devices create a new device every day. I think also that with the same problem, if auto_duplicate_lvl setting work, they must be to fusion in one device only.

**Screenshots**

![image](https://user-images.githubusercontent.com/103171257/171021833-62382d40-3f49-42da-aab7-cf3ea6e7504e.png)
![image](https://user-images.githubusercontent.com/103171257/171022193-ba462889-b18d-4e29-b337-fc43ba21dc80.png)

**Log file (optional)**
We have could to check that every device that duplicate en OCS, in /var/log/ocsinventory-server/activity.log show with "no_server" parameter.

**Comment by charleneauger** [comment]
Hi @cearanda ,

Can you check in /var/log/ocsinventory-server/activity.log if you have an error like `duplicate_error` for the duplicate machines ?
It may be due to a badly installed / uninstalled plugin on your server that causes the problem.

Best regards,
Charlene

**Comment by Lea9250** [comment]
Hi @cearanda,

Any update on this matter ? 

Regards,
Léa

**Comment by charleneauger** [comment]
Hi,

Since there is no answer, I close this issue.

Regards,
Charlene
