### ISSUE TITLE
[BUG] No packages visible in language other then English

### ISSUE THREAD

**Issue by rydel137** [OCSInventory-NG/OCSInventory-ocsreports#1376]
**OCS Inventory version**
Version :  2.9.2

**Describe the bug**

if someone uses a language other than English no packages are visible in  Deployment->Activate tab.

**To Reproduce**

1. Build and Activate any package
2. Change language to different then English
3. Login to OCS and goto Deployment->Activate tab.

I found problem in :  /ocsreports/plugins/main_sections/ms_teledeploy/ms_tele_activate.php
I am enclosing a solution in the patch file.

[ms_tele_activate.patch.txt](https://github.com/OCSInventory-NG/OCSInventory-ocsreports/files/8830843/ms_tele_activate.patch.txt)

**Comment by charleneauger** [comment]
Hi @rydel137 ,

Thanks for your report. This bug has been fixed by the next PR :  https://github.com/OCSInventory-NG/OCSInventory-ocsreports/pull/1316

Best regards,
Charlene
