### ISSUE TITLE
[BUG] NO IPDISCOVER DATA - 2.9.2

### ISSUE THREAD

**Issue by FelipeSilveiraL** [OCSInventory-NG/OCSInventory-ocsreports#1378]
**OCS Inventory version**
Version : 2.9.2

**Describe the bug**
My OCS cannot find IP on my network.

**To Reproduce**
1. Go to 'Inventory and IpDiscover'
4. See error - NO IPDISCOVER DATA 

**Expected behavior**
I looked in several places on the internet, but everyone says that the result shows automatically. In my case no :-(.

**Screenshots**
![image](https://user-images.githubusercontent.com/82624468/172364643-1e055c99-dc58-4440-8eea-c344fddf930a.png)

**Log file (optional)**
Apache:
![image](https://user-images.githubusercontent.com/82624468/172364847-76690533-13f8-4af7-a8d6-e7994d7a9100.png)

PHP:
![image](https://user-images.githubusercontent.com/82624468/172364948-8d965cf4-2d24-4190-b1fa-7657aa9d4948.png)

**Comment by gillesdubois** [comment]
Hi,

Could you try to upgrade to the 2.10 version ?

Thanks.
Gilles.

**Comment by Lea9250** [comment]
Hi @FelipeSilveiraL,

Since there was no answer, I'll close the issue. Feel free to re open if needed.

Regards,
Léa
