### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by jonathanabrantes** [OCSInventory-NG/OCSInventory-ocsreports#1381]
**OCS Inventory version**
Version : 2.9.2

**Describe the bug**
Error when export the users data do a .csv file - ERROR, the requested doesn't exists.

**To Reproduce**
1. Go to 'Users'
2. Click on 'Download'
3. See error

**Expected behavior**
When opening the feature "users" and trying to use the "download" functionality, we have a problem when OCS try to export the data to a .csv file.

**Screenshots**

![1](https://user-images.githubusercontent.com/54941941/173128772-c39f7df5-3dbf-420c-872f-483aaa01c888.png)

![2](https://user-images.githubusercontent.com/54941941/173128793-11d2d21d-a637-4b3e-9df2-6ff41878e6f3.png)

**Log file (optional)**

172.18.0.4 - - [10/Jun/2022:20:34:23 +0200] "GET /ocsreports/index.php?first HTTP/1.0" 200 7464 "http://172.27.11.10/ocsreports/index.php?function=export_csv&no_header=1&tablename=TAB_ACCESSLVL&nolimit=true&base=" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.61 Safari/537.36"
172.18.0.4 - - [10/Jun/2022:20:34:24 +0200] "POST /ocsreports/ajax.php?first&no_header=true&no_footer=true HTTP/1.0" 200 360 "http://172.27.11.10/ocsreports/index.php?first" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.61 Safari/537.36"
172.18.0.4 - - [10/Jun/2022:20:34:24 +0200] "GET /ocsreports/libraries/datatable/media/images/sort_asc.png HTTP/1.0" 304 144 "http://172.27.11.10/ocsreports/css/dataTables-custom.css" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.61 Safari/537.36"
172.18.0.4 - - [10/Jun/2022:20:34:27 +0200] "GET /ocsreports/index.php?function=admin_user HTTP/1.0" 200 6011 "http://172.27.11.10/ocsreports/index.php?first" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.61 Safari/537.36"
172.18.0.4 - - [10/Jun/2022:20:34:28 +0200] "POST /ocsreports/ajax.php?function=admin_user&no_header=true&no_footer=true HTTP/1.0" 200 813 "http://172.27.11.10/ocsreports/index.php?function=admin_user" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.61 Safari/537.36"
172.18.0.4 - - [10/Jun/2022:20:34:29 +0200] "GET /ocsreports/index.php?function=export_csv&no_header=1&tablename=TAB_ACCESSLVL&nolimit=true&base= HTTP/1.0" 200 2413 "http://172.27.11.10/ocsreports/index.php?function=admin_user" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.61 Safari/537.36"

Apache / PHP / System log if needed

**Comment by charleneauger** [comment]
Hi @jonathanabrantes ,

I can't reproduce your issue. Can you provide your Apache error log and your php version please ?

Best regards,
Charlene

**Comment by jonathanabrantes** [comment]
Hi @charleneauger ,

PHP 7.2.24-0ubuntu0.18.04.12 (cli) (built: Jun 13 2022 13:41:53) ( NTS )

access.log when try to reproduce the bug
172.27.11.1 - - [21/Jun/2022:16:30:59 +0000] "GET /ocsreports/index.php?function=admin_user HTTP/1.1" 200 6098 "http://172.27.11.10/ocsreports/index.php?function=export_csv&no_header=1&tablename=TAB_ACCESSLVL&nolimit=true&base=" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.115 Safari/537.36"
172.27.11.1 - - [21/Jun/2022:16:31:00 +0000] "POST /ocsreports/ajax.php?function=admin_user&no_header=true&no_footer=true HTTP/1.1" 200 849 "http://172.27.11.10/ocsreports/index.php?function=admin_user" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.115 Safari/537.36"
172.27.11.1 - - [21/Jun/2022:16:31:04 +0000] "GET /ocsreports/index.php?function=export_csv&no_header=1&tablename=TAB_ACCESSLVL&nolimit=true&base= HTTP/1.1" 200 2494 "http://172.27.11.10/ocsreports/index.php?function=admin_user" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.115 Safari/537.36"
[error.log](https://github.com/OCSInventory-NG/OCSInventory-ocsreports/files/8950760/error.log)

Error Log Attached

[error.log](https://github.com/OCSInventory-NG/OCSInventory-ocsreports/files/8950764/error.log)

**Comment by jonathanabrantes** [comment]
Hi @charleneauger, doing the same with the Docker Image 2.9.2 the problem persists.

ocsinventory-server container php version:
Php version PHP 7.4.3 (cli) (built: Mar  2 2022 15:36:52) ( NTS )

Logs of the containers 
[ocsinventory-db.txt](https://github.com/OCSInventory-NG/OCSInventory-ocsreports/files/8950963/ocsinventory-db.txt)
[ocsinventory-server.txt](https://github.com/OCSInventory-NG/OCSInventory-ocsreports/files/8950964/ocsinventory-server.txt)
[ocsinventory-proxy.txt](https://github.com/OCSInventory-NG/OCSInventory-ocsreports/files/8950965/ocsinventory-proxy.txt)
attached

**Comment by jonathanabrantes** [comment]
Problem solved using version 2.10
