### ISSUE TITLE
OCS cant get pcs data

### ISSUE THREAD

**Issue by edsonorm** [OCSInventory-NG/OCSInventory-ocsreports#1384]
192.168.1.15 - - [14/Jun/2022:12:33:15 +0000] "POST /ocsreports/ajax.php?&no_header=true&no_footer=true HTTP/1.1" 200 396 "http://192.168.1.24/ocsreports/index.php" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:101.0) Gecko/20100101 Firefox/101.0"
192.168.1.15 - - [14/Jun/2022:12:33:17 +0000] "GET /ocsreports/index.php?function=visu_computers HTTP/1.1" 200 7520 "http://192.168.1.24/ocsreports/index.php" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:101.0) Gecko/20100101 Firefox/101.0"
192.168.1.15 - - [14/Jun/2022:12:33:18 +0000] "POST /ocsreports/ajax.php?function=visu_computers&no_header=true&no_footer=true HTTP/1.1" 200 396 "http://192.168.1.24/ocsreports/index.php?function=visu_computers" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:101.0) Gecko/20100101 Firefox/101.0"
192.168.4.25 - - [14/Jun/2022:12:33:25 +0000] "POST /ocsinventory HTTP/1.1" 404 435 "-" "OCS-NG_WINDOWS_AGENT_v2.9.0.0"
192.168.1.15 - - [14/Jun/2022:12:33:29 +0000] "GET /ocsreports/index.php?function=visu_computers HTTP/1.1" 200 7514 "http://192.168.1.24/ocsreports/index.php" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:101.0) Gecko/20100101 Firefox/101.0"
192.168.1.15 - - [14/Jun/2022:12:33:30 +0000] "POST /ocsreports/ajax.php?function=visu_computers&no_header=true&no_footer=true HTTP/1.1" 200 396 "http://192.168.1.24/ocsreports/index.php?function=visu_computers" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:101.0) Gecko/20100101 Firefox/101.0"
192.168.1.15 - - [14/Jun/2022:12:33:32 +0000] "POST /ocsreports/index.php?function=visu_computers HTTP/1.1" 200 7648 "http://192.168.1.24/ocsreports/index.php?function=visu_computers" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:101.0) Gecko/20100101 Firefox/101.0"
192.168.1.15 - - [14/Jun/2022:12:33:32 +0000] "POST /ocsreports/ajax.php?function=visu_computers&no_header=true&no_footer=true HTTP/1.1" 200 396 "http://192.168.1.24/ocsreports/index.php?function=visu_computers" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:101.0) Gecko/20100101 Firefox/101.0"
192.168.1.15 - - [14/Jun/2022:12:33:32 +0000] "POST /ocsreports/index.php?function=visu_computers HTTP/1.1" 200 7629 "http://192.168.1.24/ocsreports/index.php?function=visu_computers" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:101.0) Gecko/20100101 Firefox/101.0"
192.168.1.15 - - [14/Jun/2022:12:33:33 +0000] "POST /ocsreports/ajax.php?function=visu_computers&no_header=true&no_footer=true HTTP/1.1" 200 396 "http://192.168.1.24/ocsreports/index.php?function=visu_computers" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:101.0) Gecko/20100101 Firefox/101.0"

**Comment by charleneauger** [comment]
Hi, please follow the template issue and open a new issue. Thanks
