### ISSUE TITLE
[BUG] OCS server version 2.10 not working at login "User not provided"

### ISSUE THREAD

**Issue by FloBro94** [OCSInventory-NG/OCSInventory-ocsreports#1387]
**OCS Inventory version**
Version : 2.10

Hi,
After update the OCS server 2.10, i can't connect at login because i have a error message "User not provided"
I had to rollback ocs version 2.9.2

Would you know why?
(PS : I specify that I followed the documentation : https://wiki.ocsinventory-ng.org/03.Basic-documentation/Updating-the-server/)
Thanks,
Best Regards,

**Comment by charleneauger** [comment]
Hi @FloBro94 ,

Can you provide me with the following informations :

- php version
- type of connection (LDAP/CAS/Local)
- Apache error_log (if any)

I think your error message is "User not registered" and not "User not provided" because we don't have any error message like that.

Best regards,
Charlene

**Comment by FloBro94** [comment]
Hi,
I resolv my issue :)

I can now connect AD account with 2.10 version 
My configurations had disappeared following the update
For those who want to link ocs with ad accounts

Add "2" in files var.php (/usr/share/ocsinventory-reports/ocsreports) and auth.php (/usr/share/ocsinventory-reports/ocsreports/backend/AUTH)

var.php :

`/**
 * Define the auth type :
 * - 1 : Local Only
 * - 2 : Local and LDAP
 * - 3 : LDAP Only
 * - 4 : LDAP with SSO
 * - 5 : Always OK, won't ask for user and password
 * - 6 : CAS authentication
 * 
 * If LDAP / SSO Basic auth is configured, please configure the LDAP Authentication
 */
define('AUTH_TYPE', 2);

auth.php : 

`// You don't have to change these variables anymore, see var.php
$affich_method = get_affiche_methode();
$list_methode = get_list_methode(2);
$limitAttempt = false;

`


Thanks for your help,
Best Regards,
