### ISSUE TITLE
[BUG] Error message Your logs directory (by default : /var/lib/ocsinventory-reports/logs) is not writable

### ISSUE THREAD

**Issue by FloBro94** [OCSInventory-NG/OCSInventory-ocsreports#1388]
**OCS Inventory version**
Version : 2.10.0

Hi,
Since my first installation (2.9.2), i have a error message Your logs directory (by default : /var/lib/ocsinventory-reports/logs) is not writable
I have testing a new installation but the error is still there.

Would you know why?
Thanks,
Best Regards,

**Comment by charleneauger** [comment]
Hi @FloBro94 ,

Just set the apache rights on this repository.

Regards,
Charlene

**Comment by FloBro94** [comment]
HI @charleneauger 
He already has the rights.
drwxrwxr-x  2 www-data www-data 4,0K avril 22 11:20 logs

Maybe there is something else to do?
Thanks for help
