### ISSUE TITLE
Deploying and Certificate

### ISSUE THREAD

**Issue by zxtury** [OCSInventory-NG/OCSInventory-ocsreports#139]
Hello...!!

is there anyway to deploy software without using certificate? im using OCS under 450+ machines, no domain (AD).. nothing!

now when i try to deply software i cant do it because i dont have a certificate..

i know i can fix this changin SSL=1 to SSL=0 in "ocsinventory.ini" but like a said, im under 450+ machines and thats not an option..

this is my setup about SSL
![2016-10-07_16-31-35](https://cloud.githubusercontent.com/assets/19822966/19208257/f019ed8c-8cac-11e6-99ca-baf4b9601af3.png)

**Comment by MyTheValentinus** [comment]
Hello @zxtury,
Is not possible to deploy without certificate. Please read the doc of teleploy.
Thanks
