### ISSUE TITLE
[BUG]ocs 2.10 no user visible in config

### ISSUE THREAD

**Issue by Blank-Vcf** [OCSInventory-NG/OCSInventory-ocsreports#1393]
**OCS Inventory version**
Informations du serveur
Systeme

    Nom du système :
    Version :
    RAM totale :
    RAM disponible :
    CPU :
    Distribution :

    Linux x86_64
    4.19.0-18-amd64
    5962 Mo
    4388 Mo
    Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz
    Debian GNU/Linux 10 (buster)

Logiciel

    Version de PHP :
    Serveur Web :
    Serveur SQL :
    Version OCSReports:

    7.3.31
    Apache
    Debian 10 version 10.3.31-MariaDB-0+deb10u1
    2.10.0

I have upgraded ocs 2.8 to 2.10 with no issue because i can't add local user with md5 deprecation.
Now when i'm going in usr it doesn't show any users
![image](https://user-images.githubusercontent.com/16317786/177940239-007da8f7-e013-418b-9148-5734909cab97.png)
i can add user, and log to ocs with it
problem is the same with:
truncate operator tables;
debug on > no errors
switch to other language

there's no error in apache log
auth type is set to define('AUTH_TYPE', 2); can log with local and ldap account

**Comment by Blank-Vcf** [comment]
it's ok with the patch!

regards

**Comment by charleneauger** [comment]
Perfect :-)
