### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by keyone78** [OCSInventory-NG/OCSInventory-ocsreports#1401]
![image](https://user-images.githubusercontent.com/8408374/179723115-82d1bf83-c12a-4174-b91e-caad90d67d54.png)

File 
backend/identity/methode/ldap.php

Will be good not to set default Role  as normal when upgrade will have the existing AccessLvl.

**Comment by charleneauger** [comment]
Hi,

Since there was no answer, I'll close this issue now.

Regards,
Charlene
