### ISSUE TITLE
[BUG] Filtering by date does not work

### ISSUE THREAD

**Issue by Kirych95** [OCSInventory-NG/OCSInventory-ocsreports#1406]
**OCS Inventory version**
Version : 2.10.0

**Describe the bug**
The query in mysql is executed correctly, requesting a date in the format Day Month Year, and by default the OCS calendar gives the format on the contrary, Month Day Year, because of this, a mysql error occurs and the desired values are not output.

**To Reproduce**
1. Go to main screen
2. Click on "Connected today" -> "Total"
3. With "DEBUG" see error

**Expected behavior**
List of computers for the period

**Screenshots**
![image](https://user-images.githubusercontent.com/39302273/180794583-18e9853b-3511-40de-9398-6688fd8b6b90.png)

**Comment by Minikea** [comment]
if you leave OCS in English, the request works. this is a localized bug with your language.

**Comment by Kirych95** [comment]
> if you leave OCS in English, the request works. this is a localized bug with your language.

Thanks for the hint, I didn't think that the parameter was taken from the txt localization, I corrected it and everything worked 👍

**Comment by charleneauger** [comment]
Hi @Kirych95,

Thanks for your report.
A fix is available here #1468.

Best regards,
Charlene
