### ISSUE TITLE
After updating it only shows the message ''No user provide''

### ISSUE THREAD

**Issue by Escanor81** [OCSInventory-NG/OCSInventory-ocsreports#1413]
**OCS Stock Version**
Version : 2.10

**Describe the error**
After upgrading to version 2.10 it is not possible to access the OCS via LADP.
The files ''var.php'' and ''dbconfig.php'' have been modified and the same error continues.

**Play**

**Expected behavior**
Access via LADP

**Screenshots**
![image](https://user-images.githubusercontent.com/103119286/183913378-e60709be-0134-411a-8010-d04eb537e185.png)

**Log file (optional)**
Apache / PHP / System log if needed

**Comment by gillesdubois** [comment]
Hi @Escanor81 

Depending on the version you are coming from LDAP Fitlers have en reworked.
See : https://wiki.ocsinventory-ng.org/04.Management-console-and-its-advanced-features/Synchronization-between-OCS-and-LDAP/#manage-authentification-with-ldap (especially the filters)

Regards,
Gilles.

**Comment by Escanor81** [comment]
Hi, @gillesdubois 
the previous version was version 2.9.1
I'm looking at the filter issue.

Thank you

**Comment by Escanor81** [comment]
hi, @gillesdubois 
I solved the problem.
As you commented, the filters for the LDAP accounts and their roles within the application had been misconfigured and did not allow access.

Thanks for your help.
