### ISSUE TITLE
[BUG] Unable to search if fieldname is DATE

### ISSUE THREAD

**Issue by keyone78** [OCSInventory-NG/OCSInventory-ocsreports#1417]
**OCS Inventory version**
Version :  2.10.0

**Describe the bug**

**To Reproduce**
Refer to url  :   ?function=admin_logs 
search will fail,  refer to query
SELECT SQL_CALC_FOUND_ROWS  * from z_view_logs WHERE DATE >= NOW()-INTERVAL 365 DAY HAVING  (( ADACCOUNT LIKE '%%s%%' )  OR  ( USER LIKE '%%s%%' )  OR  ( DATE LIKE '%%s%%' )  OR  ( FUNCTION LIKE '%%s%%' )  OR  ( ACTION LIKE '%%s%%' )  OR  ( IP_ADDRESS LIKE '%%s%%' ) )  order by USER desc limit 0 , 100 

Why ? : due to DATE  reserved words

---------------------------------------------------
fix in function_table_html.php
goto **function**

function ajaxfiltre($queryDetails,$tab_options){)

add `  for all column name  in ajaxfiltre Fn
example
 $filtertxt =  " HAVING (( `".$name."` LIKE '%%".$search."%%' ) ";
...
$ft_queryDetails1 .= " WHERE ( `".$cname."` LIKE '%%$search%%')";
....

Hope it helps.

**Comment by keyone78** [comment]
ya in english version

**Comment by keyone78** [comment]
![image](https://user-images.githubusercontent.com/8408374/195488958-bd977deb-23b7-44c3-af82-73e415905acc.png)
added -
f( strpos($cname, '.' ) !== false ){
  2688 ¦---¦---¦---¦---¦---¦---¦---// found
  2689 ¦---¦---¦---¦---¦---¦---}else {
  2690 ¦---¦---¦---¦---¦---¦---¦---$cname = "`".$cname."`";     
  2691 ¦---¦---¦---¦---¦---¦---}
  2692
if detected is using dynamic query ( h.fieldname)  skip  , fix fieldname use enclosed with ` `

**Comment by charleneauger** [comment]
Hi @keyone78,

I don't understand where the request you attached to us comes from. `z_view_logs` is not an OCS table.

If I go to the `Log visualization` page (?function=admin_logs) I have the following query :

`SELECT SQL_CALC_FOUND_ROWS 'log.csv' as name,'26 Dec 2022 11:16:00' as date_create,'26 Dec 2022 11:16:00' as date_modif,'870.432 KB' as size order by name asc limit 0 , 10`

This table is not part of OCS, I close this issue.

Regards,
Charlene
