### ISSUE TITLE
[BUG] LDAP filters problem No access LDAP

### ISSUE THREAD

**Issue by Escanor81** [OCSInventory-NG/OCSInventory-ocsreports#1419]
**OCS Inventory version**
Version : 2.10 

**Describe the bug**
Access via LDAP is not possible.
The credentials are fine and I have followed the manual as directed https://wiki.ocsinventory-ng.org/04.Management-console-and-its-advanced-features/Synchronization-between-OCS-and-LDAP/
It can only be accessed locally.
I have observed that when I modify the number of filters, nothing changes and the filters appear only as ''*FILTER4'' and ''*FILTER5''
Even if you modify the number of filters, nothing is modified.

Logs apache:
[Tue Aug 23 12:33:05.381766 2022] [php7:warn] [pid 3681] [client 172.XXX.XX.XXX:57448] PHP Warning:  ldap_bind(): Unable to bind to server: Invalid credentials in /usr/share/ocsinventory-reports/ocsreports/backend/AUTH/methode/ldap.php on line 143, referer: http:/server.ent/ocsreports/index.php
[Tue Aug 23 12:33:05.381899 2022] [php7:warn] [pid 3681] [client 172.XXX.XX.XXX:57448] PHP Warning:  ldap_search(): supplied argument is not a valid ldap link resource in /usr/share/ocsinventory-reports/ocsreports/backend/AUTH/methode/ldap.php on line 83, referer: http:/server.ent/ocsreports/index.php
[Tue Aug 23 12:33:05.381910 2022] [php7:warn] [pid 3681] [client 172.XXX.XX.XXX:57448] PHP Warning:  ldap_count_entries() expects parameter 1 to be resource, bool given in /usr/share/ocsinventory-reports/ocsreports/backend/AUTH/methode/ldap.php on line 84, referer: http:/server.ent/ocsreports/index.php
[Tue Aug 23 12:33:05.381939 2022] [php7:warn] [pid 3681] [client 172.XXX.XX.XXX:57448] PHP Warning:  ldap_get_entries() expects parameter 1 to be resource, bool given in /usr/share/ocsinventory-reports/ocsreports/backend/AUTH/methode/ldap.php on line 85, referer: http:/server.ent/ocsreports/index.php
[Tue Aug 23 12:33:05.381948 2022] [php7:warn] [pid 3681] [client 172.XXX.XX.XXX:57448] PHP Warning:  ldap_close() expects parameter 1 to be resource, bool given in /usr/share/ocsinventory-reports/ocsreports/backend/AUTH/methode/ldap.php on line 86, referer: http:/server.ent/ocsreports/index.php

Screenshots:
![image](https://user-images.githubusercontent.com/103119286/186150971-ca2498be-9d8b-42f7-8dc7-e6dc7de61b1d.png)

**Comment by Lea9250** [comment]
Hi @Escanor81,

We are aware of the issue regarding the number of filters, PR #1416 shoud solve the problem. You can already apply the patch to your server if you are willing to test it out.
If you are not able to connect using filter 4 and 5, please check your LDAP credentials and configuration as the `Unable to bind to server: Invalid credentials` suggests.

Regards,
Léa

**Comment by Escanor81** [comment]
Good evening

We have applied the patch and still the same.
There has been no change.
We continue with the same behavior, the logs say the same thing and filters 4 and 5 continue to appear.

thanks for the help

**Comment by Lea9250** [comment]
HI @Escanor81,

The PR was updated to delete existing LDAP filters and recreate the correct ones by default (filter 1 and 2). If you still are having the issue, could you either reapply the changes or update to the 2.11.0 version and see if it fixes the problem for you ?
Please note that as mentioned previously, the invalid credentials error message also suggests you are not using correct information to connect through LDAP.

Regards,
Léa

**Comment by Lea9250** [comment]
Since there has been no answer and the LDAP filters issue has been fixed already, I'll close this issue.

Best regards,
Léa
