### ISSUE TITLE
[BUG] Issue with LDAP

### ISSUE THREAD

**Issue by killmasta93** [OCSInventory-NG/OCSInventory-ocsreports#1422]
**OCS Inventory version**
Version : 
![image](https://user-images.githubusercontent.com/13953629/187087759-26ddea1d-3d76-42fa-85de-3908873d64df.png)

**Describe the bug**
Hi Trying to configure LDAP but keeps showing user not registered .

**To Reproduce**
Configured the ldap on the webGUI 
```
CONEX_LDAP_SERVEUR ldap://192.168.7.200
CONEX_ROOT_DN CN=ldap,CN=Users,DC=domain,DC=local
CONEX_ROOT_PW mypass CONEX_LDAP_PORT 389 
CONEX_DN_BASE_LDAP CN=Users,DC=domain,DC=local
CONEX_LOGIN_FIELD sAMAccountName 
CONEX_LDAP_PROTOCOL_VERSION 3 
CONEX_LDAP_FILTER1 (&(memberOf=CN=Users,DC=domain,DC=local)(sAMAccountName=user.login)) CONEX_LDAP_FILTER1_ROLE administrators 
CONEX_LDAP_CHECK_DEFAULT_ROLE administrators
```

Then went to var.php configured 
`
define('AUTH_TYPE', 2);`

Restarted OCS inventory 

Thank you

**Comment by gillesdubois** [comment]
Hi,

Your filter should be `&(memberOf=CN=Users,DC=domain,DC=local)`
The `(sAMAccountName=user.login)` part is managed by ocs itself it shoudn't be part of your filter.

Regards,
Gilles.

**Comment by killmasta93** [comment]
Hi @gillesdubois thank for the reply, 
would it be something like this ?

![image](https://user-images.githubusercontent.com/13953629/191875088-f2e90b1f-c0a2-44e1-803a-1d4719b550fe.png)

**Comment by killmasta93** [comment]
hi @gillesdubois so i removed the ldap filters and still cant seem to login with LDAP, i tried adding the user first on OCS  to see if thats the issue, i was trying to check the logs could not find the logs to see what could be the issue
