### ISSUE TITLE
[BUG] - When doing a query  for SOFTWARE  / ALL SOFTWARE NAME using LIKE operand it just shows a blank screen.

### ISSUE THREAD

**Issue by ryanrudolfoba** [OCSInventory-NG/OCSInventory-ocsreports#1426]
**OCS Inventory version**
Version : 2.9.2

**Describe the bug**
When doing a query  for SOFTWARE  / ALL SOFTWARE NAME using LIKE operand it just shows a blank screen. But if using EQUAL operand it works.

**To Reproduce**
1. Go to Inventory > Search with Various Criteria.
2. Set the filter to ACCOUNT INFO: TAG and ALL SOFTWARE: NAME
3. Set the values for the TAG and SOFTWARE field accordingly.
4. When the SOFTWARE is set to EQUAL it works, but if it is set to LIKE it just shows blank screen.

**Expected behavior**
It should show the results when using LIKE operand.

**Screenshots**
Please see attached screenshot. First screenshot is the expected behavior it works when using the EQUAL operand.
Second screenshot it doesnt work when using LIKE operand.

**Log file (optional)**
Apache / PHP / System log if needed

![image](https://user-images.githubusercontent.com/98122529/189950275-7ab27fc6-50d4-4469-861c-bcf0a4095317.png)

![image](https://user-images.githubusercontent.com/98122529/189950870-12b73490-45df-4332-bfa2-d34a4a565c51.png)

**Comment by gillesdubois** [comment]
Hi,

Could you try to update to the latest version please ? Thx.

Regards,
Gilles.

**Comment by ryanrudolfoba** [comment]
i've updated to latest OCS 2.10.0 but I am still getting the same behavior.

**Comment by Lea9250** [comment]
Hi @ryanrudolfoba,

Tested this behaviour on a 2.11.1 version and it seems fixed. Sorry to ask again but would you mind updating ? Let us know if it solves the issue.

Regards,
Léa
