### ISSUE TITLE
scroll bar displayed on all tables

### ISSUE THREAD

**Issue by AnaelMobilia** [OCSInventory-NG/OCSInventory-ocsreports#143]
Hi,
The scroll bar is always displayed on all table, as it isn't required to have a scroll bar.
Appears to have some few pixels... too much.
![capture](https://cloud.githubusercontent.com/assets/6187125/19415713/f3179fc0-9378-11e6-8e99-c4aa101e1187.PNG)

As tables are made "dynamically", couldn't find where to fix that.

**Comment by gillesdubois** [comment]
Hi,

You're right these tables are generated dynamically the only way to fix this bug is to use a bigger resolution screen or to hide columns on tables.

Regards,
Gilles Dubois.

**Comment by AnaelMobilia** [comment]
Probably linked to datatables (jquery plugin).
Can be fixed by css on static files, but crash with all these ... js after

**Comment by gillesdubois** [comment]
This problem has been fixed has been fixed in the trunk.
Thanks for your report.

Regards,
Gilles Dubois.
