### ISSUE TITLE
[BUG] Bad request with Windows agent v2.9.2 and server 2.10

### ISSUE THREAD

**Issue by akrivulya** [OCSInventory-NG/OCSInventory-ocsreports#1430]
Using windows agent version 2.9.2 with freshly installed OCS server 2.10 (FreeBSD ports) there are some errors in activity.log:

> Mon Sep 19 12:23:53 2022;13281;400;DESKTOP-G3QVND1-2022-09-13-14-59-56;10.2.1.50;OCS-NG_WINDOWS_AGENT_v2.9.2.0;useragent;Bad agent or agent version too recent for server !!
> Mon Sep 19 12:23:53 2022;13281;106;DESKTOP-G3QVND1-2022-09-13-14-59-56;10.2.1.50;OCS-NG_WINDOWS_AGENT_v2.9.2.0;prolog;stopped by module
> Mon Sep 19 12:23:53 2022;13281;515;DESKTOP-G3QVND1-2022-09-13-14-59-56;10.2.1.50;OCS-NG_WINDOWS_AGENT_v2.9.2.0;end;bad_request

I have seen previous posts with similar problem and check Ocsinventory.pm files, all of them contains $Apache::Ocsinventory::VERSION = '2.10.0'
![зображення](https://user-images.githubusercontent.com/60314384/191022163-47ff4149-1610-46e0-a47f-dbfb7f4b9150.png)

**Comment by gillesdubois** [comment]
Hi @akrivulya 

This issue is really weird since your Ocsinventory::VERSION is set to the right one.
Could you try to install one of our nightly on a test server ? http://download.ocsinventory-ng.org/nightly/
(you can take the latest).

Regards,
Gilles.

**Comment by akrivulya** [comment]
With OCSNG_UNIX_SERVER_2.10.0-nightly-2022-09-20.tar.gz all works. Thank you.
