### ISSUE TITLE
Change graph render tools (elycharts)

### ISSUE THREAD

**Issue by AnaelMobilia** [OCSInventory-NG/OCSInventory-ocsreports#144]
Elycharts is used to render graphics on the information -> Stats screen.
It isn't compatible with a HTML5 doctype (as using bootstrap & co, it's like a pre-requisite...)

Time to thinks to change the tools ?
The latests version on github doesn't work either
https://github.com/voidlabs/elycharts/releases

**Comment by AnaelMobilia** [comment]
- plugins/main_sections/ms_stats/ms_stats_connexion.php
  - plugins/main_sections/ms_stats/ms_stats_top.php
  - plugins/main_sections/ms_teledeploy/ms_speed_stat.php
  - plugins/main_sections/ms_teledeploy/ms_tele_stats.php
  - require/function_commun.php

**Comment by gillesdubois** [comment]
Hi,

I don't think this will be fixed for the new version but it's planned.

Great idea ! 👍 

Regards,
Gilles Dubois.

**Comment by gillesdubois** [comment]
ping @AnaelMobilia 

Changing the graphics lib is not a big deal. Do you have some idea on which lib to use ?
We are planning on using charts.js which is bootstrap / html5 compliant.

Regards,
Gilles Dubois.

**Comment by gillesdubois** [comment]
Done : https://github.com/OCSInventory-NG/OCSInventory-ocsreports/commit/5ef2ee82ea2787cce4852b56f48679a85f2822f3

**Comment by AnaelMobilia** [comment]
@gillesdubois nice job.
Just for memories, I suggested highcharts on comments on my previous PR ;-)
