### ISSUE TITLE
[BUG] False duplicates computers in MAC address

### ISSUE THREAD

**Issue by szaszg** [OCSInventory-NG/OCSInventory-ocsreports#1440]
**OCS Inventory version**
Version : 2.11.0

**Describe the bug**
In the "Manage->Duplicates" menu (/ocsreports/index.php?function=admin_double) we found some duplicates (e.g. MAC only), where OCS inventory use the bluetooth adapter's MAC address instead of the Ethernet adapter's. (I don't know why have the same MAC address of several bluetooth adapters.)

**Expected behavior**
Better if OCS inventory does not use MAC from bluetooth or USB adapters. (May concantenate all 'fix' MAC addresses of a machine)

**"Screenshots"**
E.g.
Duplicates:

TAG : LOST
MACADDR : **00:1A:7D:DA:71:0A**
SSN : System Serial Number
ID : 444674
LASTDATE : 2022-10-20 10:42:24
NAME : TBANYA-W10-135
WORKGROUP : TBANYA
OSNAME : Microsoft Windows 10 Pro
USERID : felhasznalo
MEMORY : 4096
PROCESSORS : 3900
IPADDR : 10.20.40.135
DESCRIPTION : 100-400
FIDELITY : 3309
LASTCOME : 2022-10-20 10:42:24
PROCESSORN : 1
PROCESSORT : Intel(R) Core(TM) i3-7100 CPU @ 3.90GHz [2 core(s) x86_64]
USERAGENT : OCS-NG_WINDOWS_AGENT_v2.8.0.0
SWAP : 4666

TAG : Szerológia
MACADDR : **00:1A:7D:DA:71:0A**
SSN : To be filled by O.E.M.
ID : 445314
LASTDATE : 2022-10-20 11:39:37
NAME : OVSZ-KGAZD-10
WORKGROUP : OVSZ
OSNAME : Microsoft Windows 10 Pro
USERID : kasza_karola
MEMORY : 4096
PROCESSORS : 3700
IPADDR : 10.1.80.10
DESCRIPTION : 100-297
FIDELITY : 1734
LASTCOME : 2022-10-20 11:39:37
PROCESSORN : 1
PROCESSORT : Intel(R) Core(TM) i3-4170 CPU @ 3.70GHz [2 core(s) x86_64]
USERAGENT : OCS-NG_WINDOWS_AGENT_v2.8.0.0
SWAP : 5190

Network "tab":
Computer 1:

Bluetooth Device (Personal Area Network) #2 | Ethernet | 3 Mb/s |   | **00:1A:7D:DA:71:0A** | Down |   |   |   |   |  
Realtek PCIe GBE Family Controller #3 | Ethernet | 100 Mb/s |   | 10:7B:44:53:5C:76 | Up | 10.20.40.135 | 255.255.255.0 | 10.20.40.254 | 10.20.40.0 |  
WAN Miniport (IKEv2) | Other (see MIB) | 0 b/s |   | 00:00:00:00:00:00 | Down |   |   |   |   |  
WAN Miniport (L2TP) | Other (see MIB) | 0 b/s |   | 00:00:00:00:00:00 | Down |   |   |   |   |  
WAN Miniport (PPPOE) | Dialup | 0 b/s |   | 00:00:00:00:00:00 | Down |   |   |   |   |  
WAN Miniport (PPTP) | Other (see MIB) | 0 b/s |   | 00:00:00:00:00:00 | Down |   |   |   |   |  
WAN Miniport (SSTP) | Other (see MIB) | 0 b/s |   | 00:00:00:00:00:00 | Down |   |   |   |   |  

Computer 2:

Bluetooth Device (Personal Area Network) #2 | Ethernet | 3 Mb/s |   | **00:1A:7D:DA:71:0A** | Down |   |   |   |   |  
Realtek PCIe GBE Family Controller #2 | Ethernet | 1 Gb/s |   | 4C:CC:6A:B4:5D:44 | Up | 10.1.80.10 | 255.255.0.0 | 10.1.255.254 | 10.1.0.0 |  
WAN Miniport (IKEv2) | Other (see MIB) | 0 b/s |   | 00:00:00:00:00:00 | Down |   |   |   |   |  
WAN Miniport (L2TP) | Other (see MIB) | 0 b/s |   | 00:00:00:00:00:00 | Down |   |   |   |   |  
WAN Miniport (PPPOE) | Dialup | 0 b/s |   | 00:00:00:00:00:00 | Down |   |   |   |   |  
WAN Miniport (PPTP) | Other (see MIB) | 0 b/s |   | 00:00:00:00:00:00 | Down |   |   |   |   |  
WAN Miniport (SSTP) | Other (see MIB) | 0 b/s |   | 00:00:00:00:00:00 | Down |   |   |   |   |

**Comment by gillesdubois** [comment]
Hi @szaszg 

The "Mac Only" duplicate reconciliation is not something that is aware of the type of the network (bluetooth / wifi / ethernet). That's the way this feature is intended to work.

I recommend to use others duplicate merge criterias such as "Mac + Hostname" / "Mac + Serial number".

Regards,
Gilles.
