### ISSUE TITLE
OCS Inventory 2.11.0 and Ubuntu ubuntu-22.04.1-server with PHP 8.1 plugins not working [BUG]

### ISSUE THREAD

**Issue by szymonn81** [OCSInventory-NG/OCSInventory-ocsreports#1442]
OCS Inventory version
Version : 2.11.0

Describe the bug
Clean system installation ubuntu-22.04.1-server (with php 8.1)-default 
Plugins install, however, does not work, for example Officepack, installation according to the documentation - performed without any problems, plugin  shows in the add-ons manager that it is installed, but the Office key Managament menu does not appear in the system.

![office1](https://user-images.githubusercontent.com/43672586/197335650-f9fd6e98-7ab7-4b34-b34f-4079e66ead6f.jpg)

Installation process  (Clean Ubuntu + OCS)
apt get-update
apt get-upgrade
reboot

apt-get install -y apache2 build-essential libapache2-mod-php libapache-dbi-perl libarchive-zip-perl libdbd-mysql-perl libdbi-perl libmojolicious-perl libswitch-perl libnet-ip-perl libplack-handler-anyevent-fcgi-perl libsoap-lite-perl libxml-simple-perl make mariadb-client mariadb-server php php-apcu php-bz2 php-cas php-curl php-curl php-gd php-iconv php-imagick php-imap php-intl php-json php-ldap php-mbstring php-memcache php-mysql php-pclzip php-pear php-pspell php-soap php-tidy php-xml php-xmlrpc php-xsl php-zip libcompress-zlib-perl libio-compress-perl libapache2-mod-perl2 libapache2-mod-perl2-dev

apt-get install net-tools
apt install php-mbstring
apt install python3-scp

perl -MCPAN -e 'install Apache2::SOAP'
perl -MCPAN -e 'install XML::Entities'
perl -MCPAN -e 'install Net::IP'
perl -MCPAN -e 'install Apache::DBI'
perl -MCPAN -e 'install Mojolicious'
perl -MCPAN -e 'install Switch'
perl -MCPAN -e 'install Plack::Handler'

wget https://github.com/OCSInventory-NG/OCSInventory-ocsreports/releases/download/2.11.0/OCSNG_UNIX_SERVER-2.11.0.tar.gz

tar -xfv OCSNG_UNIX_SERVER-2.11.0.tar.gz
	
./setup.sh
ALL default (yes for all )

systemctl enable mariadb && systemctl start mariadb

	
mysql -u root -p
create database ocsweb;
CREATE USER 'ocssa'@'localhost' IDENTIFIED BY 'Password12345';
GRANT ALL PRIVILEGES ON ocsweb. * TO 'ocssa'@'localhost' IDENTIFIED BY 'Password12345';
flush privileges;
exit

vim /etc/php/8.1/apache2/php.ini
post_max_size = 50M
upload_max_filesize = 50M
max_execution_time = 300
max_input_time = 300
memory_limit = 256M

vim /etc/apache2/conf-available/z-ocsinventory-server.conf
# Name of database
PerlSetEnv OCS_DB_NAME ocsweb
PerlSetEnv OCS_DB_LOCAL ocsweb
# User allowed to connect to database
PerlSetEnv OCS_DB_USER ocssa
# Password for user
PerlSetVar OCS_DB_PWD Password12345

vim /etc/apache2/conf-available/zz-ocsinventory-restapi.conf
# Name of database
     $ENV{OCS_DB_LOCAL} = 'ocsweb';
# User allowed to connect to database
     $ENV{OCS_DB_USER} = 'ocssa';
# Password for user
     $ENV{OCS_DB_PWD} = 'Password12345';

ln -s /etc/apache2/conf-available/ocsinventory-reports.conf /etc/apache2/conf-enabled/ocsinventory-reports.conf
ln -s /etc/apache2/conf-available/z-ocsinventory-server.conf /etc/apache2/conf-enabled/z-ocsinventory-server.conf
ln -s /etc/apache2/conf-available/zz-ocsinventory-restapi.conf /etc/apache2/conf-enabled/zz-ocsinventory-restapi.conf

chown -R www-data:www-data /var/lib/ocsinventory-reports
systemctl restart apache2 && systemctl enable apache2
-------------------------------------------------------------------------

Plugin Installation - https://wiki.ocsinventory-ng.org/10.Plugin-engine/Using-plugins-installer/ (without any problem)

PHP errror log

[Sat Oct 22 10:56:31.955586 2022] [php:warn] [pid 863] [client 192.168.8.30:1154] PHP Warning:  Trying to access array offset on value of type null in /usr/share/ocsinventory-reports/ocsreports/require/config/include.php on line 133, referer: http://192.168.8.29/ocsreports/
[Sat Oct 22 10:56:31.959710 2022] [php:warn] [pid 863] [client 192.168.8.30:1154] PHP Warning:  Trying to access array offset on value of type null in /usr/share/ocsinventory-reports/ocsreports/plugins/main_sections/ms_console/ms_console.php on line 268, referer: http://192.168.8.29/ocsreports/

**Comment by Lea9250** [comment]
HI @szymonn81,

Did you update your profiles permissions to access the extension page ? The success message displayed after a plugin install on the GUI should contain something like "You may need to update profiles permissions to access the extension page.". Could you check that your profile has the necessary rights on the extension's page (ms_officepack) ?

Regards,
Léa

**Comment by szymonn81** [comment]
Hi @Lea9250  I did it but not for the sysadmin account - that was my mistake now it works . Thanks . 
This problem can be closed
