### ISSUE TITLE
[BUG] No data available in table with plugins

### ISSUE THREAD

**Issue by inferno66** [OCSInventory-NG/OCSInventory-ocsreports#1446]
**OCS Inventory version**

Install done with RPM
PHP Version :7.4.24
Web Server : Apache/2.4.6 (Red Hat Enterprise Linux) OpenSSL/1.0.2k-fips PHP/7.4.24 mod_perl/2.0.11 Perl/v5.16.3
Database Server : MariaDB Server version 5.5.68-MariaDB
Version OCSReports: 2.11.0
OS Name :  Linux x86_64
Version : 3.10.0-1062.el7.x86_64

**Describe the bug**
I'm unable to get data from pluging. Always show "No data available in table"

**To Reproduce**
Example with scheduledtasks Plugin : 
Zip unziped to /var/lib/ocsinventory-reports/extensions/scheduledtasks
Install done from the OCS Extension manager ==> OK
Install done with python3 install_plugin.py

After that HTTPD is unable to start : 
Oct 25 12:06:24 lx1313 httpd[2543]: AH00526: Syntax error on line 275 of /etc/httpd/sites.d/ocsinventory-server.conf:
Oct 25 12:06:24 lx1313 httpd[2543]: $s->add_config() has failed: Can't locate Apache/Ocsinventory/Plugins/Scheduledtasks/Map.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 . /etc/httpd) at (eval 2) line 2.\nCompilation failed in require at (eval 15) line 2.\n
Oct 25 12:06:24 lx1313 systemd[1]: httpd.service: main process exited, code=exited, status=1/FAILURE
Oct 25 12:06:24 lx1313 kill[2545]: kill: cannot find process ""
..

I'm able to start HTTPD if I copy Scheduledtasks/Map.pm from etc/ocsinventory/ocsinventory-server/perl/Apache/Ocsinventory/Plugins/Scheduledtasks to /usr/share/perl5/vendor_perl/Apache/Ocsinventory/Plugins/Scheduledtasks 

Of course the powerhsell script is on the plugin folder of the client (and I can see the XML generated on the client, which contains data).

But the table never get populated (and same result with other plugins tested)

Regards

**Comment by Lea9250** [comment]
Hi @inferno66,

If an inventory of the computer is triggered, is there any error in the apache logs ? Can you try checking the scheduledtasks table in database, see if there is any data in it ? 

Regards,
Léa

**Comment by charleneauger** [comment]
Hi,

Since there was no answer, I'll close this issue now.

Regards,
Charlene
