### ISSUE TITLE
[BUG] White Page after Update from 2.8 to 2.11.1

### ISSUE THREAD

**Issue by Klauserus** [OCSInventory-NG/OCSInventory-ocsreports#1448]
**OCS Inventory version**
Version :  2.11.1

It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.
General informations

Docker host's operating system : I think the docker must have been there before. I don't know anything about this and the update instructions didn't say anything about docker.

Mysql Server version : 15.1
Docker informations

Docker compose version : unknown
Docker version : unknown
Problem's description

after execute the setup.sh and right managements, setup was succesfully finished. after that i copy the old z-XX configs back into the directorys. But i only see a white page. here is my error.log

PHP Warning: Module 'ldap' already loaded in Unknown on line 0 [Wed Oct 26 00:00:03.030188 2022] [mpm_prefork:notice] [pid 988] AH00163: Apache/2.4.41 (Ubuntu) OpenSSL/1.1.1f mod_perl/2.0.11 Perl/v5.30.0 configured -- resuming normal operations [Wed Oct 26 00:00:03.030204 2022] [core:notice] [pid 988] AH00094: Command line: '/usr/sbin/apache2' [Wed Oct 26 08:00:42.226387 2022] [mpm_prefork:notice] [pid 988] AH00169: caught SIGTERM, shutting down PHP Warning: Module 'ldap' already loaded in Unknown on line 0 [Wed Oct 26 09:12:37.574971 2022] [mpm_prefork:notice] [pid 2565525] AH00163: Apache/2.4.41 (Ubuntu) OpenSSL/1.1.1f mod_perl/2.0.11 Perl/v5.30.0 configured -- resuming normal operations [Wed Oct 26 09:12:37.575248 2022] [core:notice] [pid 2565525] AH00094: Command line: '/usr/sbin/apache2' [Wed Oct 26 09:12:45.116750 2022] [php7:warn] [pid 2565530] [client 172.28.7.2 ] PHP Warning: require(install.php): failed to open stream: No such file or directory in /usr/share/ocsinventory-reports/ocsreports/require/header.php on line 91 [Wed Oct 26 09:12:45.116789 2022] [php7:error] [pid 2565530] [client 172.28.7.2 ] PHP Fatal error: require(): Failed opening required 'install.php' (include_path='.:/usr/share/php') in /usr/share/ocsinventory-reports/ocsreports/require/header.php on line 91 [Wed Oct 26 09:12:49.767834 2022] [php7:warn] [pid 2565526] [client 172.28.7.2 ] PHP Warning: require(install.php): failed to open stream: No such file or directory in /usr/share/ocsinventory-reports/ocsreports/require/header.php on line 91 [Wed Oct 26 09:12:49.767865 2022] [php7:error] [pid 2565526] [client 172.28.7.2 ] PHP Fatal error: require(): Failed opening required 'install.php' (include_path='.:/usr/share/php') in /usr/share/ocsinventory-reports/ocsreports/require/header.php on line 91 [Wed Oct 26 09:13:17.326661 2022] [php7:warn] [pid 2565527] [client 172.28.7.2 ] PHP Warning: require(install.php): failed to open stream: No such file or directory in /usr/share/ocsinventory-reports/ocsreports/require/header.php on line 91 [Wed Oct 26 09:13:17.326743 2022] [php7:error] [pid 2565527] [client 172.28.7.2 ] PHP Fatal error: require(): Failed opening required 'install.php' (include_path='.:/usr/share/php') in /usr/share/ocsinventory-reports/ocsreports/require/header.php on line 91 [Wed Oct 26 09:13:19.045605 2022] [php7:warn] [pid 2565528] [client 172.28.7.2 ] PHP Warning: require(install.php): failed to open stream: No such file or directory in /usr/share/ocsinventory-reports/ocsreports/require/header.php on line 91 [Wed Oct 26 09:13:19.045641 2022] [php7:error] [pid 2565528] [client 172.28.7.2 ] PHP Fatal error: require(): Failed opening required 'install.php' (include_path='.:/usr/share/php') in /usr/share/ocsinventory-reports/ocsreports/require/header.php on line 91 [Wed Oct 26 09:13:20.380565 2022] [php7:warn] [pid 2565529] [client 172.28.7.2 ] PHP Warning: require(install.php): failed to open stream: No such file or directory in /usr/share/ocsinventory-reports/ocsreports/require/header.php on line 91 [Wed Oct 26 09:13:20.380632 2022] [php7:error] [pid 2565529] [client 172.28.7.2 ] PHP Fatal error: require(): Failed opening required 'install.php' (include_path='.:/usr/share/php') in /usr/share/ocsinventory-reports/ocsreports/require/header.php on line 91 [Wed Oct 26 09:13:35.423430 2022] [perl:error] [pid 2565530] [client 192.168.1. ] Can't call method "rollback" on an undefined value at /usr/local/share/perl/5.30.0/Apache/Ocsinventory/Server/System.pm line 312.\n [Wed Oct 26 09:13:39.831843 2022] [php7:warn] [pid 2565526] [client 172.28.7.2 ] PHP Warning: require(install.php): failed to open stream: No such file or directory in /usr/share/ocsinventory-reports/ocsreports/require/header.php on line 91 [Wed Oct 26 09:13:39.831876 2022] [php7:error] [pid 2565526] [client 172.28.7.2 ] PHP Fatal error: require(): Failed opening required 'install.php' (include_path='.:/usr/share/php') in /usr/share/ocsinventory-reports/ocsreports/require/header.php on line 91 [Wed Oct 26 09:13:39.842659 2022] [perl:error] [pid 2565534] [client 192.168.1. ] Can't call method "rollback" on an undefined value at /usr/local/share/perl/5.30.0/Apache/Ocsinventory/Server/System.pm line 312.\n [Wed Oct 26 09:14:03.711347 2022] [perl:error] [pid 2565527] [client 192.168.13.1 ] Can't call method "rollback" on an undefined value at /usr/local/share/perl/5.30.0/Apache/Ocsinventory/Server/System.pm line 312.\n [Wed Oct 26 09:14:12.558945 2022] [perl:error] [pid 2565528] [client 192.168.1. ] Can't call method "rollback" on an undefined value at /usr/local/share/perl/5.30.0/Apache/Ocsinventory/Server/System.pm line 312.\n [Wed Oct 26 09:14:42.042467 2022] [perl:error] [pid 2565529] [client 192. 1] Can't call method "rollback" on an undefined value at /usr/local/share/perl/5.30.0/Apache/Ocsinventory/Server/System.pm line 312.\n [Wed Oct 26 09:14:53.520534 2022] [php7:warn] [pid 2565530] [client 172.28.7.2 ] PHP Warning: require(install.php): failed to open stream: No such file or directory in /usr/share/ocsinventory-reports/ocsreports/require/header.php on line 91 [Wed Oct 26 09:14:53.520577 2022] [php7:error] [pid 2565530] [client 172.28.7.2 ] PHP Fatal error: require(): Failed opening required 'install.php' (include_path='.:/usr/share/php') in /usr/share/ocsinventory-reports/ocsreports/require/header.php on line 91 [Wed Oct 26 09:15:04.313136 2022] [php7:warn] [pid 2565526] [client 172.28.7.2 ] PHP Warning: require(install.php): failed to open stream: No such file or directory in /usr/share/ocsinventory-reports/ocsreports/require/header.php on line 91 [Wed Oct 26 09:15:04.313164 2022] [php7:error] [pid 2565526] [client 172.28.7.2 ] PHP Fatal error: require(): Failed opening required 'install.php' (include_path='.:/usr/share/php') in /usr/share/ocsinventory-reports/ocsreports/require/header.php on line 91 [Wed Oct 26 09:15:10.255263 2022] [perl:error] [pid 2565534] [client 192. 7] Can't call method "rollback" on an undefined value at /usr/local/share/perl/5.30.0/Apache/Ocsinventory/Server/System.pm line 312.\n [Wed Oct 26 09:15:19.823328 2022] [perl:error] [pid 2565527] [client 192.168.21.1 ] Can't call method "rollback" on an undefined value at /usr/local/share/perl/5.30.0/Apache/Ocsinventory/Server/System.pm line 312.\n [Wed Oct 26 09:15:33.925326 2022] [perl:error] [pid 2565528] [client 192. 1] Can't call method "rollback" on an undefined value at /usr/local/share/perl/5.30.0/Apache/Ocsinventory/Server/System.pm line 312.\n [Wed Oct 26 09:15:56.899174 2022] [perl:error] [pid 2565529] [client 192.168.1. ] Can't call method "rollback" on an undefined value at /usr/local/share/perl/5.30.0/Apache/Ocsinventory/Server/System.pm line 312.\n [Wed Oct 26 09:16:04.563555 2022] [perl:error] [pid 2565530] [client 192.168.1. ] Can't call method "rollback" on an undefined value at /usr/local/share/perl/5.30.0/Apache/Ocsinventory/Server/System.pm line 312.\n [Wed Oct 26 09:17:16.050549 2022] [perl:error] [pid 2565526] [client 192.168.1. ] Can't call method "rollback" on an undefined value at /usr/local/share/perl/5.30.0/Apache/Ocsinventory/Server/System.pm line 312.\n [Wed Oct 26 09:17:41.334431 2022] [perl:error] [pid 2565534] [client 192.168.13. ] Can't call method "rollback" on an undefined value at /usr/local/share/perl/5.30.0/Apache/Ocsinventory/Server/System.pm line 312.\n [Wed Oct 26 09:18:04.962554 2022] [perl:error] [pid 2565527] [client 192.168.13. ] Can't call method "rollback" on an undefined value at /usr/local/share/perl/5.30.0/Apache/Ocsinventory/Server/System.pm line 312.\n [Wed Oct 26 09:18:45.853646 2022] [perl:error] [pid 2565528] [client 192. 9] Can't call method "rollback" on an undefined value at /usr/local/share/perl/5.30.0/Apache/Ocsinventory/Server/System.pm line 312.\n [Wed Oct 26 09:19:23.461263 2022] [perl:error] [pid 2565529] [client 192. 3] Can't call method "rollback" on an undefined value at /usr/local/share/perl/5.30.0/Apache/Ocsinventory/Server/System.pm line 312.\n [Wed Oct 26 09:20:04.944971 2022] [perl:error] [pid 2565530] [client 192. 4] Can't call method "rollback" on an undefined value at /usr/local/share/perl/5.30.0/Apache/Ocsinventory/Server/System.pm line 312.\n [Wed Oct 26 09:20:05.062269 2022] [perl:error] [pid 2565526] [client 192.168.1. ] Can't call method "rollback" on an undefined value at /usr/local/share/perl/5.30.0/Apache/Ocsinventory/Server/System.pm line 312.\n [Wed Oct 26 09:20:16.764681 2022] [php7:warn] [pid 2565534] [client 172.28.7.2 ] PHP Warning: require(install.php): failed to open stream: No such file or directory in /usr/share/ocsinventory-reports/ocsreports/require/header.php on line 91 [Wed Oct 26 09:20:16.764714 2022] [php7:error] [pid 2565534] [client 172.28.7.2 ] PHP Fatal error: require(): Failed opening required 'install.php' (include_path='.:/usr/share/php') in /usr/share/ocsinventory-reports/ocsreports/require/header.php on line 91 [Wed Oct 26 09:20:21.837024 2022] [perl:error] [pid 2565527] [client 192.168.5. ] Can't call method "rollback" on an undefined value at /usr/local/share/perl/5.30.0/Apache/Ocsinventory/Server/System.pm line 312.\n [Wed Oct 26 09:21:04.162733 2022] [perl:error] [pid 2565528] [client 192.168.25. ] Can't call method "rollback" on an undefined value at /usr/local/share/perl/5.30.0/Apache/Ocsinventory/Server/System.pm line 312.\n [Wed Oct 26 09:22:38.258161 2022] [perl:error] [pid 2565529] [client 192.168.13. ] Can't call method "rollback" on an undefined value at /usr/local/share/perl/5.30.0/Apache/Ocsinventory/Server/System.pm line 312.\n [Wed Oct 26 09:22:51.743241 2022] [perl:error] [pid 2565530] [client 192. 5] Can't call method "rollback" on an undefined value at /usr/local/share/perl/5.30.0/Apache/Ocsinventory/Server/System.pm line 312.\n [Wed Oct 26 09:23:50.682275 2022] [perl:error] [pid 2565526] [client 192.168.21.1 ] Can't call method "rollback" on an undefined value at /usr/local/share/perl/5.30.0/Apache/Ocsinventory/Server/System.pm line 312.\n [Wed Oct 26 09:25:23.650895 2022] [perl:error] [pid 2565534] [client 192.168.13. ] Can't call method "rollback" on an undefined value at /usr/local/share/perl/5.30.0/Apache/Ocsinventory/Server/System.pm line 312.\n [Wed Oct 26 09:26:06.372664 2022] [perl:error] [pid 2565527] [client 192. 6] Can't call method "rollback" on an undefined value at /usr/local/share/perl/5.30.0/Apache/Ocsinventory/Server/System.pm line 312.\n [Wed Oct 26 09:26:25.501296 2022] [perl:error] [pid 2565528] [client 192. 6] Can't call method "rollback" on an undefined value at /usr/local/share/perl/5.30.0/Apache/Ocsinventory/Server/System.pm line 312.\n [Wed Oct 26 09:26:42.175727 2022] [perl:error] [pid 2565529] [client 192.168.1. ] Can't call method "rollback" on an undefined value at /usr/local/share/perl/5.30.0/Apache/Ocsinventory/Server/System.pm line 312.\n [Wed Oct 26 09:26:42.663067 2022] [perl:error] [pid 2565530] [client 192. 8] Can't call method "rollback" on an undefined value at /usr/local/share/perl/5.30.0/Apache/Ocsinventory/Server/System.pm line 312.\n [Wed Oct 26 09:26:47.486952 2022] [perl:error] [pid 2565526] [client 192.168.1. ] Can't call method "rollback" on an undefined value at /usr/local/share/perl/5.30.0/Apache/Ocsinventory/Server/System.pm line 312.\n [Wed Oct 26 09:27:20.634335 2022] [perl:error] [pid 2565534] [client 192.168.5. ] Can't call method "rollback" on an undefined value at /usr/local/share/perl/5.30.0/Apache/Ocsinventory/Server/System.pm line 312.\n

i delete the IP´s ;)

i am not a professional as you can see. i have taken over the project from my predecessor and have to work my way in.

**Comment by gillesdubois** [comment]
Hi,

First of all, please try to format a little your text since in that case it is really hard to seen anything from that big text block :) 

I have a few questions : 
- Are you using docker ? you mention an unknown docker compose / docker version in your issue description
- Are you sure your database configuration is alright ? 

Most of the time, this line found in your log mean that the database credentials are not the correct one : 
`[Wed Oct 26 09:22:51.743241 2022] [perl:error] [pid 2565530] [client 192. 5] Can't call method "rollback" on an undefined value at /usr/local/share/perl/5.30.0/Apache/Ocsinventory/Server/System.pm line 312.`

Regards,
Gilles.

**Comment by charleneauger** [comment]
Hi,

Since there was no answer, I'll close this issue now.

Regards,
Charlene
