### ISSUE TITLE
[BUG] `http://check-version.ocsinventory-ng.org` is not up to date

### ISSUE THREAD

**Issue by fpotier** [OCSInventory-NG/OCSInventory-ocsreports#1449]
The `http://check-version.ocsinventory-ng.org/` endpoint has not been updated for more than 2 years and the release of version 2.8.
```
$ curl http://check-version.ocsinventory-ng.org
{
        "version": "2.8"
        "download": "https://ocsinventory-ng.org/?page_id=1548&lang=en"
}
```
Could you please update it each time a new release is created on github?

**Comment by charleneauger** [comment]
Hi @fpotier ,

Thanks for your report :-)
I updated the version number : 

```
$ curl http://check-version.ocsinventory-ng.org
{
        "version": "2.11.1"
        "download": "https://ocsinventory-ng.org/?page_id=1548&lang=en"
}
```

Best regards,
Charlene
