### ISSUE TITLE
[BUG] The table 'prolog_conntrack' is full

### ISSUE THREAD

**Issue by silvaguilherme** [OCSInventory-NG/OCSInventory-ocsreports#1452]
**OCS Inventory version**
Version : 2.9

My apache log is full of this message.
should i worry?

DBD::mysql::db do failed: The table 'prolog_conntrack' is full at /usr/local/share/perl5/Apache/Ocsinventory/Server/Communication/Session.pm line 46.

**Comment by Lea9250** [comment]
Hi @silvaguilherme,

Would it be possible for you to try and update to the 2.11.1 version ? If not, you can try manually deleting the entries in the prolog_conntrack table.

Regards,
Léa

**Comment by charleneauger** [comment]
Hi,

Since there was no answer, I'll close this issue now.

Regards,
Charlene
