### ISSUE TITLE
Error autenticacion LDAp

### ISSUE THREAD

**Issue by jgonzalez238** [OCSInventory-NG/OCSInventory-ocsreports#1454]
No puedo autenticarme con usuarios Ldap contra OCS 2.10
En el log de Apache:

[Mon Nov 14 19:36:10.766574 2022] [php:error] [pid 2538] [client 10.203.0.17:10458] PHP Fatal error:  Uncaught TypeError: ldap_search(): Argument #1 ($ldap) must be of type LDAP|array, bool given in /usr/share/ocsinventory-reports/ocsreports/backend/AUTH/methode/ldap.php:83\nStack trace:\n#0 /usr/share/ocsinventory-reports/ocsreports/backend/AUTH/methode/ldap.php(83): ldap_search()\n#1 /usr/share/ocsinventory-reports/ocsreports/backend/AUTH/methode/ldap.php(66): search_on_loginnt()\n#2 /usr/share/ocsinventory-reports/ocsreports/backend/AUTH/methode/ldap.php(45): verif_pw_ldap()\n#3 /usr/share/ocsinventory-reports/ocsreports/backend/AUTH/auth.php(92): require_once('...')\n#4 /usr/share/ocsinventory-reports/ocsreports/require/header.php(321): require_once('...')\n#5 /usr/share/ocsinventory-reports/ocsreports/index.php(44): require('...')\n#6 {main}\n  thrown in /usr/share/ocsinventory-reports/ocsreports/backend/AUTH/methode/ldap.php on line 83, referer: http://10.200.0.5/ocsreports/

Una parte de configuracion del identity.php:

// You don't have to change these variables anymore, see var.php
$list_methode = get_list_methode(true);
#$list_methode=array(0=>"ldap.php",1=>"local.php");
if (!isset($_SESSION['OCS']["lvluser"])) {
    $i = 0;
    //methode pour le calcul des droits
    while (isset($list_methode[$i]) && $list_methode[$i]) {
        require_once('methode/' . $list_methode[$i]);
        //on garde les erreurs présentes
        //entre chaque méthode
        if (isset($ERROR)) {
            $tab_error[$list_methode[$i]] = $ERROR;
            unset($ERROR);
        }
        //on garde les tags qu'a le droit de voir l'utilisateur
        if (isset($list_tag)) {
            $tab_tag[$list_methode[$i]] = $list_tag;
            unset($list_tag);
        }
        $i++;
    }

**Comment by Lea9250** [comment]
Hi @jgonzalez238,

Did you follow the documentation regarding setting up LDAP authentication ? Here is the link for reference : https://wiki.ocsinventory-ng.org/04.Management-console-and-its-advanced-features/Synchronization-between-OCS-and-LDAP/#manage-authentification-with-ldap

The logs you provided suggest OCS wasn't able to establish a connection to your LDAP server using the current configuration. You might want to double check it.

Regards,
Léa

**Comment by charleneauger** [comment]
Hi,

Since there was no answer, I'll close this issue now.

Regards,
Charlene
