### ISSUE TITLE
Update PHP min version

### ISSUE THREAD

**Issue by AnaelMobilia** [OCSInventory-NG/OCSInventory-ocsreports#146]
Hello,
As based on code, the actual PHP min version is 5.3.7

As PHP 5.3 branch is EOL since 14 August 2014, is it possible to target the 5.4 branch (or higher ?) now ?

A real plus is the short syntax for "<?= $var ?>" since 5.4 👍 

Note :
  - 5.3 EOL : 14 Aug 2014
  - 5.4 EOL : 03 Sep 2015
  - 5.5 EOL : 21 Jul 2016
  - 5.6 & 7 : actual

**Comment by gillesdubois** [comment]
Hi,

For the next version the minimum required version of php will be 5.4.

Thanks for your contribution.

Regards,
Gilles Dubois.
