### ISSUE TITLE
[BUG] Activate package with alternate port is not working

### ISSUE THREAD

**Issue by brizao** [OCSInventory-NG/OCSInventory-ocsreports#1466]
**OCS Inventory version**
Version : 2.11.1

**Describe the bug**
For example, I have a server which the HTTPS port is listening on 8443 port, when I create an agent through Windows Packager and then use build and activate feature, the HTTPS address is saved without the colon and being saved as " SERVER_IP8443/download". So if I use this way, of course the agent will not find the package and give me the error:  "Failed to download Metadata file".

If I correct the address inside mariadb/mysql table "download_enable", the address at activate page appears correct, but the agent on the other side gives me another error: "all package action failed during this session" when trying to update.

Now if omit the alternate port, the deployment works. Also the package created with the alternate port works too if I execute it directly on the agent machine.

I don't know if it's a bug but building the deployment package with an alternate port is not working and also removing the colon ":8443".

**To Reproduce**
1. Go to 'Deployment > Build > Windows > Install / Uninstall > Update Agent > Put the newly created package which contains the alternate HTTPS port and validate.'
2. Click on 'Deplyment > Activate > Click on the activate button of the new package > Insert the address IP:8443 (my alternate port) on Https and Fragments field and click OK.'

**Expected behavior**
The recent activated package HTTPS  and Fragments url should have the address I inserted and the machine being affected should find and install the package without problems.

**Comment by brizao** [comment]
Hi, I think I have found a solution for this, instead of changing the address/port when activating the package, make it permanent at configuration > deployment > DOWNLOAD_URI_FRAG/INFO and also checking DOWNLOAD_AUTO_ACTIVATE, this way the package will be activated automatically with the right address and alternative port and it will be installed normally.

**Comment by Lea9250** [comment]
Hi @brizao,

Glad to hear you managed to solve your problem. Modifying the DOWNLOAD_URI_FRAG/INFO option is currently the way to go to set up a custom address/port.

Since this is resolved, I'll close this issue.

Best regards,
Léa
