### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by eacoimbra** [OCSInventory-NG/OCSInventory-ocsreports#1467]
**OCS Inventory version**
Version : 2.11.1
PHP: 8.0.20
MariaDB Server: 10.5.1

**Describe the bug**
Add new layout function not working.

**To Reproduce**
Every time I click add new layout, I get the error message "ACESS DENIED".
The Manage/Layout menu in the manual is also not displayed.

**Screenshots**
![2022-12-24 (3)](https://user-images.githubusercontent.com/121232827/209451505-94fb5400-769d-496e-b7a4-861d84c1d516.jpg)

**Log file (optional)**
I didn't find anything in the Apache and OCS logs related to this error.

**Comment by eacoimbra** [comment]
Information that may be relevant.

We have an OCS 2.9.2 in production. What I did was duplicate the database, create a new VM with version 2.11.1 and run install.php on the new installation pointing to the new database.

We have updated the agents of some assets and they are communicating with the new OCS 2.11.1 server. At first everything is working perfectly, with the exception of this functionality that did not exist in version 2.9.2.

Could it be that there was some garbage from the previous installation in the database?

**Comment by charleneauger** [comment]
Hi @eacoimbra ,

The rights on the layouts are not set by default.
Go to `Configuration > Users > Profiles`, edit your profile and set the `Layout` right. Logout/Login and now you should be able to access the layouts page.

Best regards,
Charlene
