### ISSUE TITLE
[BUG] Administrative data - cannot change the field type

### ISSUE THREAD

**Issue by kvolk2git** [OCSInventory-NG/OCSInventory-ocsreports#1478]
**OCS Inventory version**
PHP Version : 7.4.33
Web Server : Apache/2.4.41 (Ubuntu)
Database Server : Ubuntu 20.04 version 10.3.37-MariaDB-0ubuntu0.20.04.1
Version OCSReports: 2.11.1

**Administrative data - cannot change the field type**
In the menu "Manage" -> "Administrative data" -> Data available -> Actions -> Edit if you try to change the field from "TEXT" to any other type and click the SEND button, the data will not change and you will see a change error "Field name is already used". 
![333301](https://user-images.githubusercontent.com/78740198/213427743-af305225-117f-4c15-94e8-72c290bc9165.jpg)

Also, if you initially create a field with the type "SELECT" or "CHECKBOX", it will be displayed incorrectly in the computer menu, the field name is there and there is no checkbox.
![333302](https://user-images.githubusercontent.com/78740198/213427792-24ee01c1-119b-4958-9e41-60ea2f2a1b03.jpg)
![333303](https://user-images.githubusercontent.com/78740198/213427813-58415f87-5f82-42f7-b00e-fa23cf9795aa.jpg)

**Comment by charleneauger** [comment]
Hi @kvolk2git ,

I managed to reproduce the problem of updating the type of an administrative data. I added it to our Roadmap to fix it.

Regarding the second part of your issue, it's not a bug. You must configure the values to display. To do this, click on the wheel to the right of the administrative data in the computer detail page.

![Screenshot_20230119_135544](https://user-images.githubusercontent.com/28924550/213449082-1900fc25-6364-439f-bb44-48f9bcc4e4e8.png)

Best regards,
Charlene

**Comment by kvolk2git** [comment]
> You must configure the values to display.
Thanks!

PS. It was not obvious, it might be worth taking out the filling of these fields in the administrative data settings menu. Another point in the page layout, the tag lies on top of the first field without indentation.
