### ISSUE TITLE
[BUG] Group filter in ldap connection not working 

### ISSUE THREAD

**Issue by CarlosAPCunha** [OCSInventory-NG/OCSInventory-ocsreports#1481]
**OCS Inventory version**
Version :  2.11.1

O.S. : Ubuntu 20.0.4 

**Describe the bug**

I configured the authentication with an ldap connection and configured the php to option 2, that is local and ldap, and it is working "correctly", that is, if you log in with a domain user, it logs in correctly, but I need to only allow a user of one specific group , and here's the problem, if I configure the filter for a group X, it ignores that and logs any user.

Even when I put a group that exists in the filter, it still lets login be done successfully.

So the problem that the "memberOf" filter is not working....

**To Reproduce**

Configure ldap authentication and test a filter with memberOf

**Expected behavior**

That only allows login from the informed group

**Screenshots**

**Log file (optional)**
Apache / PHP / System log if needed

**Comment by CarlosAPCunha** [comment]
![Captura de Tela_Área de Seleção_20230126170357](https://user-images.githubusercontent.com/65431346/214939179-e0dcc2ea-b43f-41c9-8d29-ab6ccae4ece9.png)

**Comment by CarlosAPCunha** [comment]
![Captura de Tela_Área de Seleção_20230126170701](https://user-images.githubusercontent.com/65431346/214939412-e9fd1101-6d41-489f-bedf-07889432deab.png)

**Comment by Parnoud** [comment]
Hello,

That is not a bug, You configure the CONEX_LDAP_CHECK_DEFAULT_ROLE with Super Administrateur, leave it to blank and it's ok !

Bye,
--

Salut,

je ne pense pas que c'est un bug, tu as choisi de mettre CONEX_LDAP_CHECK_DEFAULT_ROLE avec "Super Administrateur" , ça veut dire que n'importe quelle personne qui se connecte à ce role.
Dans ton cas de figure il te suffit juste de mettre "vide" pour que par défaut les personnes ne peuvent pas se connecter, et si ça passe ton filtre, hop ils ont le bon rôle !

Passe une bonne journée,
Pierre

**Comment by charleneauger** [comment]
Hi @CarlosAPCunha ,

As @Parnoud explained, the default role allows LDAP users to login with this profile even if they are not part of the memberOf filter.

Can you confirm that leaving this field empty corrects your problem ?

Best regards,
Charlene

**Comment by CarlosAPCunha** [comment]
Hi!!! Thanks for the answers :-D 
I will try again and report if it worked or no...

Regards!!!

**Comment by CarlosAPCunha** [comment]
HI!
Yes, now is ok, CONEX_LDAP_CHECK_DEFAULT_ROLE  is blank resolved my problem :-D
Thanks  your all
