### ISSUE TITLE
Win Agent : Access denied 'ocs'@'localhost' in activity.log

### ISSUE THREAD

**Issue by kashmax** [OCSInventory-NG/OCSInventory-ocsreports#1484]
Hi,

Recently I have installed the latest OCS version. Now when I install agent (OCS-Windows-Agent-2.10.1.0_x64.exe) on windows 10 then on OCS server in activity.log it shows this ERROR.
```
OCS-NG_WINDOWS_AGENT_v2.10.1.0;database_connect;Access denied for user 'ocs'@'localhost'

x.x.x.x;OCS-NG_WINDOWS_AGENT_v2.10.1.0;handler;Database connection
```
What could be wrong. Your guidance is appreciated.

Thanks

**Comment by kvolk2git** [comment]
May be need check config files?

 z-ocsinventory-server.conf:
`  # Name of database
  PerlSetEnv OCS_DB_NAME ocs
  PerlSetEnv OCS_DB_LOCAL ocs
  # User allowed to connect to database
  PerlSetEnv OCS_DB_USER ocs
  # Password for user
  PerlSetVar OCS_DB_PWD ************
`
and zz-ocsinventory-restapi.conf:
`  $ENV{OCS_DB_HOST} = 'localhost';
  $ENV{OCS_DB_PORT} = '3306';
  $ENV{OCS_DB_LOCAL} = 'ocs';
  $ENV{OCS_DB_USER} = 'ocs';
  $ENV{OCS_DB_PWD} = '*************';
`

**Comment by kashmax** [comment]
> May be need check config files?
> 
> z-ocsinventory-server.conf:
> 
> PerlSetEnv OCS_DB_HOST localhost PerlSetEnv OCS_DB_PORT 3306 PerlSetEnv OCS_DB_NAME ocs PerlSetEnv OCS_DB_LOCAL ocs PerlSetEnv OCS_DB_USER ocs PerlSetVar OCS_DB_PWD xxxxxxxxx
> 
> and zz-ocsinventory-restapi.conf:
> 
> $ENV{OCS_DB_HOST} = 'localhost'; $ENV{OCS_DB_PORT} = '3306'; $ENV{OCS_DB_LOCAL} = 'ocs'; $ENV{OCS_DB_USER} = 'ocs'; $ENV{OCS_DB_PWD} = 'xxxxxxxxx';

The change in restapi solved the error.
Thank you
