### ISSUE TITLE
[BUG] Find USB Devices

### ISSUE THREAD

**Issue by kvolk2git** [OCSInventory-NG/OCSInventory-ocsreports#1489]
**OCS Inventory version**
PHP Version : 7.4.33
Web Server : Apache/2.4.41 (Ubuntu)
Database Server : Ubuntu 20.04 version 10.3.37-MariaDB-0ubuntu0.20.04.1
Version OCSReports: 2.11.1

**Describe the bug**
I can't find information about USB devices present in the system. But in the search by criteria there is an option to select "USB devices", but the search result is always empty.

**To Reproduce**
1. Go to 'Inventory'
2. Click on 'Search with various criteria'
3. Select  'USB Devices'
4. Click on 'Add'
5. Select any criteria
6. Click on 'Send'
7. See an empty result

**Expected behavior**
Find any data

**Comment by charleneauger** [comment]
Hi @kvolk2git,

I added the USB devices table in the Devices tab of computer details. 
See #1503.

Indeed, this table was not displayed except in the multicriteria search.

Best regards,
Charlene
