### ISSUE TITLE
Save WebUI Settings

### ISSUE THREAD

**Issue by mbrinkmann** [OCSInventory-NG/OCSInventory-ocsreports#149]
Dear OCS-DEVs 

currently i plan to migrate from v2.1.2 to v2.2.1.
On my test-machine i realized, that settings (like number of shown systems, column-selection etc.) are not stored anymore.

It would be great, if this functionallity would be working again.
Cheers Marc

**Comment by gillesdubois** [comment]
Hi,

This problem has been fixed and will be available in the new version.
Coming soon ;)

Regards,
Gilles Dubois.
