### ISSUE TITLE
[BUG] CONEX_LDAP_FILTER size 200

### ISSUE THREAD

**Issue by Parnoud** [OCSInventory-NG/OCSInventory-ocsreports#1494]
**OCS Inventory version**
Version : 2.11.1

**Describe the bug**
le champ pour les filtre de de recherche est trop petit pour pouvoir faire des filtres. ca taille est de seulement 200.

**To Reproduce**
1. allez sur /index.php?function=admin_conf
2. clliquer sur configuration ldap
3. descender sur CONEX_LDAP_FILTER1
4. taper un filtre de plus de 200 charactere

**Expected behavior**
Ici nous aimerions faire un filtre mais nous avons du mal car la taille est limité par rapport au CN ldap.

**Comment by Parnoud** [comment]
Pourriez vous voir pour agrandir le champ a plus de 255 char ? Dans certain ca les CN sont tres long.

**Comment by charleneauger** [comment]
Bonjour,

Cette modification est prévue dans notre roadmap :-)

Cordialement,
Charlène
