### ISSUE TITLE
[BUG] SNMP Discovery not Working in 2.11

### ISSUE THREAD

**Issue by LinekerCalseverini** [OCSInventory-NG/OCSInventory-ocsreports#1495]
There was another issue already opened (#1367), but there was no response since last year, so I'm bumping this problem up again.

Using OCS Inventory Version 2.11. The agent configuration:

```
snmptimeout=3
snmp=1
basevardir=/var/lib/ocsinventory-agent
password=<password-hidden>
user=<user-hidden>
debug=1
nosoftware=0
server=http://192.168.99.112:8080/ocsinventory
snmpretry=2
logfile=/var/log/ocsinventory-agent
snmp_switch=on
snmp_network=192.168.99.0
```

In Configuration -> General Configuration:
- IpDiscover ON
- SNMP ON

In Configuration -> SNMP Configuration, I created:
- a Type named "Firewall", with the type condition being the OID 1.3.6.1.2.1.1.1 with the value \*FreeBSD\*
- a label FireWallDescription
- Associated the OID 1.3.6.1.2.1.1.1 to FireWall Description Label

In the Machine Configuration -> Network Scan, I set the IpDiscover as ON, the SNMP_SWITCH as ON, and the SNMP_NETWORK as 192.168.99.0

In Manage -> Network Scan, I set:
- Subnet 192.168.99.0
- Type Firewall
- SNMP Communities (they are correct, I checked with snmpwalk)

When I run the ocsinventory-agent command, it doesn't discover any devices. Is there something wrong with the configuration?

**Comment by charleneauger** [comment]
Hi @LinekerCalseverini ,

I allow myself to close this issue since I answered you in this one : #1367 

Best regards,
Charlene
