### ISSUE TITLE
LDAP Auth

### ISSUE THREAD

**Issue by mbrinkmann** [OCSInventory-NG/OCSInventory-ocsreports#150]
Dear OCS-Devs, 

Thanks for your fast answer to my last request :)

I would also like to point out, that LDAP auth is not working anymore in my 2.2.1 Server.
I updated from 2.1.2 where it was / is working properly.
Can i provide any logs, to solve this?

Thanks and best regards
Marc

**Comment by gillesdubois** [comment]
Hi,

I will check the ldap feature and give you a feedback asap :)

Regards,
Gilles Dubois.

**Comment by gillesdubois** [comment]
Update : i checked the ldap auth and everything look fine.

Could you provide more information on your configuration ?

Note : With update your changes in auth.php and identity.php have been erased.

Regards,
Gilles Dubois.
