### ISSUE TITLE
[BUG] Sample CVE file is not compliant

### ISSUE THREAD

**Issue by steph78630** [OCSInventory-NG/OCSInventory-ocsreports#1508]
**OCS Inventory version**
Version : All

**Describe the bug**
The CVE example file (csv_example.csv) is not compliant, the content of the 3rd column (NAME_RESULT) should be "chrome"

Like in CVE-Search server : [Vendor-List]/google/chrome)

**Comment by Cubitus06** [comment]
Hi,
Could you give-us a line to find Microsoft Windows vulns ?

I try this one without success : 

Microsoft*, Microsoft Corporation,Microsoft Windows Server 2016 Datacenter

Thanks

**Comment by steph78630** [comment]
Hi,

you can try : *Windows*,microsoft,windows_server_2016

**Comment by steph78630** [comment]
@Cubitus06 

result ?

**Comment by charleneauger** [comment]
Hi @steph78630 ,

Thanks for your report, we will fix it as soon as possible.

Hi @Cubitus06 ,

Microsoft Windows Server 2016 Datacenter is a Microsoft OS, the OCS CVE feature get only **software** vulnerabilities.

Best regards,
Charlene

**Comment by Cubitus06** [comment]
Hi 
@steph78630 ,
No, it's doesn't work ... None of Microsoft Product will be found ... 

@charleneauger 
I open another bug to announce that cve-search, which work by itself on port 5000, 
doesn't work with ocs-inventory. I've made a lot of test with different configuration, try to contact @gillesdubois but without result.

Could you say if ocs-inventory can scan any cve on inventory ?

Thanks All

**Comment by steph78630** [comment]
Hi @Cubitus06 

I made a mistake : CVE in OCS is based on the "**software**" table which does not include the version of the operating system, so to date we cannot trace Windows vulnerabilities in this way.
