### ISSUE TITLE
PHP Error Version 7010 (2.2.1) Software page

### ISSUE THREAD

**Issue by tsmr** [OCSInventory-NG/OCSInventory-ocsreports#151]
http://localhost/ocsreports/index.php?function=visu_all_soft

![image](https://cloud.githubusercontent.com/assets/13178158/19577181/624b65fc-9716-11e6-816e-608b2f78e698.png)

**Comment by gillesdubois** [comment]
Bonjour,

Nous sommes entrain de fixer le problème en interne un commit sera disponible des que possible.

Merci pour ta contribution,
Gilles Dubois.

**Comment by gillesdubois** [comment]
Le problème a été fix : 191dfb79bd12ab517f2dfa2da7c78f3c5929693c

Gilles Dubois.
