### ISSUE TITLE
[BUG] manage/duplicated the screen loads and does do not open.

### ISSUE THREAD

**Issue by FelipeSilveiraL** [OCSInventory-NG/OCSInventory-ocsreports#1511]
**OCS Inventory version**
Version : 2.11.1

**Describe the bug**
Trying to access manage/duplicated the screen loads and does do not open.

**To Reproduce**
1. Login
2. Clicked in the tab manage after duplicated

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/82624468/233987844-32e732b4-7fb0-48b9-9ba9-5a34887c0327.png)

**Log file (optional)**
Apache(2.4.52) / PHP( 8.1.2) /

**Comment by Lea9250** [comment]
Hi @FelipeSilveiraL ,

Do you have anything regarding this issue in your logs ? How many assets does your server manage ? 

Regards,
Léa

**Comment by charleneauger** [comment]
Hi @FelipeSilveiraL ,

Any news ?

Best regards,
Charlene

**Comment by Lea9250** [comment]
Hi @FelipeSilveiraL,

I'll close this issue since there was no answer. Feel free to reopen if needed.

Regards, 
Léa
