### ISSUE TITLE
[BUG] Server information line break

### ISSUE THREAD

**Issue by steffmeister** [OCSInventory-NG/OCSInventory-ocsreports#1514]
**OCS Inventory version**
Version : 2.11.1 (also previous)

**Describe the bug**
It bothers me quite some time now, in the menue select Information > Server information. Maybe this is only on my setup, but the line for Web Server gets too long ("Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips PHP/7.3.33 mod_perl/2.0.11 Perl/v5.16.3") so that it broken and it now says "Database server: Perl/v5.16.3, Version OCSReports: MariaDB Server version 10.1.48-MariaDB".

**To Reproduce**
1. Go to 'Information > Server information'
4. See error on the right side where it says Web server and following

**Expected behavior**
Too long lines should either not break or the label should be on the correct height

**Screenshots**
Current state:
![image](https://github.com/OCSInventory-NG/OCSInventory-ocsreports/assets/1689735/6e2c64af-c3a2-444b-a9fc-c0dc8f587773)

I would expect this:
![image](https://github.com/OCSInventory-NG/OCSInventory-ocsreports/assets/1689735/e8b7e8fb-e6b3-4bf5-9593-4ae52d739067)

**Log file (optional)**
n/a

**Possible fix**
ocsreports.css, around line 446,
add this rule:
white-space: nowrap;
to ".server-information-ul-li"

**Comment by charleneauger** [comment]
Hi @steffmeister ,

Thanks for your reports.
I created a PR with your fix.

Best regards,
Charlene
