### ISSUE TITLE
[BUG] LDAP Login

### ISSUE THREAD

**Issue by marc0mz** [OCSInventory-NG/OCSInventory-ocsreports#1515]
**OCS Inventory version**
Version : 2.11.1
AD level 2016, DC is windows server 2016.

**Describe the bug**
LDAP Login error with ActiveDirectory Account

**Expected behavior**

I configured ldap when I try to login with an active directory account I get the error "bad connextion" in the logs what is it about?

Log File when try to login with my ad account

![image](https://github.com/OCSInventory-NG/OCSInventory-ocsreports/assets/36813834/cc73d3eb-7e49-4c9b-8144-e56c5d431fef)

White Screen After login

![image](https://github.com/OCSInventory-NG/OCSInventory-ocsreports/assets/36813834/9dc11d51-0a0f-47a9-8035-5eaa160ed46e)

**Comment by charleneauger** [comment]
Hi @marc0mz ,

Did you update the `AUTH_TYPE` variable in the `/usr/share/ocsinventory-reports/ocsreports/var.php` file ?

If you want to be able to connect with a local or LDAP account, set it to `2`.
If you want to be able to connect only with an LDAP account, set it to `3`.

Best regards,
Charlene Auger

**Comment by Lea9250** [comment]
Hi @marc0mz ,

Any update on this issue ? 

Regards,
Léa

**Comment by charleneauger** [comment]
Hi,

Since there was no answer, I'll close this issue now.

Regards,
Charlene
