### ISSUE TITLE
CVE file consistency (cve_matching_mostknown.csv)

### ISSUE THREAD

**Issue by mattoussaint** [OCSInventory-NG/OCSInventory-ocsreports#1527]
**OCS Inventory version**
Version : Last

**Describe the bug**
**many duplicate entries** in the **cve_matching_mostknown.csv** file (x2 or x4!!!)

**To Reproduce**
Open the file, sort it by columns, see the damage

**Expected behavior**
A **coherent, well-thought-out file**, different from the result of the old **csv_example.csv** file

**Comment by charleneauger** [comment]
Hi @mattoussaint ,

The CSV file provided is generated automatically by a script that retrieves software information from the CVE-Search API. We have made this file available to facilitate the creation of regular expressions for CVE matches.

If you would like to contribute or propose an update to the file, we are open to your suggestions. Feel free to share your ideas and we'll be happy to collaborate.

Best regards,
Charlene
