### ISSUE TITLE
Statistics on currents installations

### ISSUE THREAD

**Issue by AnaelMobilia** [OCSInventory-NG/OCSInventory-ocsreports#153]
As an update checker function is added, couldn't we add a statistics plugins which should provide few informations (without personnal datas).
Eg :
- OCS Version
- PHP Version
- Web server name & version
- count of OCS Agent (by name and version)
- count of inventoried devices ?
- plugins installed ?

In order to have realistics datas and informations where to develop.
If this is made, datas should be send to an ocsinventory-ng.org subdomains (as statistics ?)

Also add a checkbox on the install / update and configuration menu to have user confirmation on data send (as for dokuwiki for example)

**Comment by gillesdubois** [comment]
This feature will be implemented soon but not in OCS Reports directly. With a dedicated platform that will also giove roadmap and current developpement informations
