### ISSUE TITLE
[BUG] Package builder (Custom - Command) first Character deleted (2.12.0)

### ISSUE THREAD

**Issue by LMS235** [OCSInventory-NG/OCSInventory-ocsreports#1536]
**OCS Inventory version**
Version : 2.12.0

**Describe the bug**
When a custom package is built, the command truncates the first character of the command. For example CPPRED.bat becomes PPRED.bat in the info file and the deploy does not work.

Example:
![image](https://github.com/OCSInventory-NG/OCSInventory-ocsreports/assets/8693550/67503ff7-ff38-444c-a8bf-8a51c9eeb109)

Info File:
![image](https://github.com/OCSInventory-NG/OCSInventory-ocsreports/assets/8693550/bf0e37ec-abac-4fa8-912b-be74710175c1)

**To Reproduce**
1. Go to "Deployment" => "Build" => "Windows" => "Others" => "Custom package" (probably also for all other types of packaging)
2. Store an appropriate command (e.g. 1234.bat)
3. Check the info File (or deployment) => "1234.bat" became "234.bat" and thus the command is not found of course

Currently, we can work around this by simply appending a character to the front, which is feasible as a workaround. But it must be fixed as soon as possible.

**Expected behavior**
The inputs must be adopted 1:1. This is clearly a bug in 2.12.0 (in 2.11.1 this still worked without problems).

**Screenshots**
see above

**Comment by LMS235** [comment]
Hi @charleneauger , thank you for the quick response

So far, I have only been able to recreate it with "Execute a file". However, I have not tested all possibilities. 

Here should be a 2.12.1 released as soon as possible!

**Comment by LMS235** [comment]
Or can you give me a "quick fix"?

**Comment by charleneauger** [comment]
Hi @LMS235 ,

I made some fixes related to your issues.
You will find them in the following PR : #1542 

Best regards,
Charlene

**Comment by LMS235** [comment]
@charleneauger thank you.
will this be a 2.12.1 then? Here I would have directly still a few adjustments of the German translation (https://github.com/OCSInventory-NG/OCSInventory-ocsreports/pull/1535).

**Comment by LMS235** [comment]
tested --> work
