### ISSUE TITLE
name of machine not displayed

### ISSUE THREAD

**Issue by StCyr** [OCSInventory-NG/OCSInventory-ocsreports#154]
**Steps to reproduce:**

1. From the "All softwares" screen (function=visu_all_soft), select a software (to display the list of computers running this software)
2. From the list of computers running this software, click one of the computer's cross icon (to delete it)

**Result:**

A pop-up opens with the following text "name_of_machine?" (see also screenshot)

![untitled](https://cloud.githubusercontent.com/assets/8179031/19716556/b7a4c54e-9b5c-11e6-9078-29b5a5b1e551.png)

**Expected result:**

The pop-up should at least contain the computer's name as text. Idealy, it should contain something like "Do you really want to delete computer <name_of_machine>?"

**Comment by MyTheValentinus** [comment]
Hello,
Patched in trunk.
Thanks
