### ISSUE TITLE
[BUG] SNMP scan read wrong value .incorrect  values read if contain the character  : 

### ISSUE THREAD

**Issue by bud4** [OCSInventory-NG/OCSInventory-ocsreports#1540]
**OCS Inventory version**
Version : 

SNMP scan read wrong value  .incorrect reading of the values if they contain the character **:**
snmp : reading the value of the value in the OID .1.3.6.1.2.1.2.2.1.6 (mac) is wrong , only the   substring of  MAC  which is after the first  :  is saved in the db 

**To Reproduce**
configure reading of oid  .1.3.6.1.2.1.2.2.1
the value stored in db is wrong 
test: output of snmpwalk 
snmpwalk -v 2c -On  -c public 172.30.41.16  .1.3.6.1.2.1.2.2.1.6
.1.3.6.1.2.1.2.2.1.6.1 = STRING: 9c:93:4e:bc:10:6d
.1.3.6.1.2.1.2.2.1.6.2 = STRING: 
.1.3.6.1.2.1.2.2.1.6.3 = STRING: 
value stored in db  93:4e:bc:10:6d

**Expected behavior**
show  the value   9c:93:4e:bc:10:6d

**Screenshots**
![Istantanea_2023-07-14_15-56-10](https://github.com/OCSInventory-NG/OCSInventory-ocsreports/assets/14982949/28b42fe9-da8d-4087-8ed6-2910249d1e89)

**Comment by Lea9250** [comment]
Hi @bud4,

I was able to reproduce the issue with the Unix agent. I proposed a fix for it (see https://github.com/OCSInventory-NG/UnixAgent/pull/451). You can apply the changes locally if you want to test this out before it is merged. 
The fix should be implemented in the next release of the Unix agent.

Regards,
Léa

**Comment by charleneauger** [comment]
Hi @bud4 ,

This issue has been fixed. 
The fix will be available in the next release of the Unix agent.

Best regards,
Charlene
