### ISSUE TITLE
[BUG] Install EXE - executable.exe is missing (2.12.0)

### ISSUE THREAD

**Issue by LMS235** [OCSInventory-NG/OCSInventory-ocsreports#1541]
**OCS Inventory version**
Version : 2.12.0

**Describe the bug**
In 2.11.1 build a normal EXE: `NAME="executable.exe /S /user=all"`
In 2.12.0 build a normal EXE: `NAME="/S /user=all"` => "executable.exe" is missing => deployment won't work

**To Reproduce**
1. Go to 'Deployment' => 'Build'
2. Click on 'Windows' => 'Install / Uninstall' => 'Execute an exe'
3. Create an EXE Install and see the info file....

**Expected behavior**
As of now, the whole deployment feature in 2.12.0 is not really functional (see also https://github.com/OCSInventory-NG/OCSInventory-ocsreports/issues/1536). This must change as soon as possible!

**Comment by charleneauger** [comment]
Hi @LMS235 ,

I made some fixes related to your issues.
You will find them in the following PR : #1542 

Best regards,
Charlene

**Comment by LMS235** [comment]
tested --> work
