### ISSUE TITLE
[BUG] Dynamic group is no longer filled (2.12.0 with https://github.com/OCSInventory-NG/OCSInventory-ocsreports/pull/1542)

### ISSUE THREAD

**Issue by LMS235** [OCSInventory-NG/OCSInventory-ocsreports#1544]
**OCS Inventory version**
Version : 2.12.0 with Fixes from https://github.com/OCSInventory-NG/OCSInventory-ocsreports/pull/1542

**Describe the bug**
Since the installation of the fixes from  https://github.com/OCSInventory-NG/OCSInventory-ocsreports/pull/1542 the dynamic groups are no longer filled cleanly and the deployment therefore no longer runs.

The cronjobs run clean and even after 1 day "All computers (cached)" remains empty.
"All computers (replay)" displays everything correctly.

**Expected behavior**
The data should be present in both views
Here unfortunately since 2.12.0 some things are no longer correct :(

**Screenshots**
All computers (replay):
![image](https://github.com/OCSInventory-NG/OCSInventory-ocsreports/assets/8693550/0708443c-1dfd-4640-9cf0-1718b266dd4e)

All computers (cached):
![image](https://github.com/OCSInventory-NG/OCSInventory-ocsreports/assets/8693550/1105f4f1-10f2-4be8-a675-e371e54f3b7d)

**Comment by LMS235** [comment]
Update: Old dynamic groups continue to function as usual. Only newly created ones have the problem

**Comment by Lea9250** [comment]
Hi @LMS235,

The PR https://github.com/OCSInventory-NG/OCSInventory-Server/pull/433 should fix the issue, could you try it and update us ?

As a side note, you mentioned a cron job, but the groups are not being populated by a cron script. Instead, a device gets added at the time of its inventory. OCS verifies whether it matches any dynamic group request, and if so, the device is added to the group.

Regards,
Léa

**Comment by LMS235** [comment]
@Lea9250 works now :)

**Comment by Lea9250** [comment]
@LMS235 thanks for the update ! Glad to hear it works. 
I'll close the issue now.

Have a nice day

**Comment by LMS235** [comment]
@Lea9250 thank you. 

There are some open issues just after 2.12.0 (also some already fixed by fixes like this one) - when will there be an update (i.e. a 2.12.1 or similar)? Think some will otherwise run into problems (and many patching not by hand individual files)
