### ISSUE TITLE
Network Scan frequency

### ISSUE THREAD

**Issue by micBona** [OCSInventory-NG/OCSInventory-ocsreports#1548]
Hello everyone,
I've tried to register to the OCS website but without success (no confirmation code received).
Is it possible to modify the network scan frequency of the agent?

Thank you in advance,
Michele

**Comment by Lea9250** [comment]
Hi @micBona 

What do you mean by registering into the OCS website ?

To answer your question, the network scan frequency is decided by the frequency of agents inventories (scans are executed at the time of the inventory). You won't be able to customize only the network scan frequency. 

Regards,
Léa

**Comment by micBona** [comment]
Hello Léa, 
thank you for the answer.
Because it's not a bug I've tried to ask the question on https://ask.ocsinventory-ng.org/ but I couldn't register myself.
Anyway, I'm going to close the issue.
Thank you again,

Best regards,
Michele
