### ISSUE TITLE
[BUG]  ​The list of activated packages is empty for some dynamic groups.

### ISSUE THREAD

**Issue by Schwenn2002** [OCSInventory-NG/OCSInventory-ocsreports#1552]
**OCS Inventory version**
Version : 2.12.0

**Describe the bug**
We distribute software packages via dynamic groups. After the update to version 2.12.0, the assigned packages are no longer displayed for various dynamic groups. The list of activated packages is empty (no display) for some dynamic groups. A status message "Processing..." remains

**To Reproduce**
1. Go to 'Inventory -> Groups -> Dynamic Gropus
2. Click on any existing group
3. Choose 'Activated packages'
4. See error "empty list" / stauts "processing..."

**Expected behavior**
The assigned packages are displayed as in version 2.11.1 and can be edited.

**Comment by charleneauger** [comment]
Hi @Schwenn2002 ,

Do you have PHP errors appearing in your apache error logs when you go to this tab ?

Regards,
Charlene

**Comment by Lea9250** [comment]
Hi @Schwenn2002 ,

#1554 has been merged into master and should fix your issue. Let us know if the issue persists after applying the changes.

Best regards,
Léa

**Comment by Schwenn2002** [comment]
Thank you very much, I implemented the source code change directly and it works again.
