### ISSUE TITLE
How to create columns search , 

### ISSUE THREAD

**Issue by keyone78** [OCSInventory-NG/OCSInventory-ocsreports#156]
I follow the Datatable  code  to  add columns search but was no hope.

https://datatables.net/examples/api/multi_filter.html

Is that any parameter I should take note of.
The ajax is working fine but not filter is make

![2016-10-31 20_00_01-ocs inventory](https://cloud.githubusercontent.com/assets/8408374/19853534/bcf2ae48-9fa4-11e6-977d-116c91df9981.png)

**Comment by gillesdubois** [comment]
Hi,

All the datatable processing and filtering is done trough server side.
You should check these link : 
https://datatables.net/examples/data_sources/server_side.html
https://datatables.net/examples/server_side/

If you want to add columns / filtering you need to edit the php file.

Regards,
Gilles Dubois.
