### ISSUE TITLE
[BUG] Agent HTTP Status Code #403

### ISSUE THREAD

**Issue by wsamirmr** [OCSInventory-NG/OCSInventory-ocsreports#1568]
**OCS Inventory version**
Version : 2.12.0, agent 2.10.1.0

**Describe the bug**
Starting OCS Inventory Agent on Tuesday, October 10, 2023 07:28:18.
AGENT => Running OCS Inventory Agent Version 2.10.1.0
AGENT => Using OCS Inventory FrameWork Version 2.10.1.0
AGENT => Loading plug-in(s)
	DLL PLUGIN => Searching for Plug-in DLL(s) in folder <C:\Program Files\OCS Inventory Agent\plugins>
	DLL PLUGIN => 0 DLL Plug-in(s) successfully loaded on 0 DLL(s) found
AGENT => Using network connection with Communication Server
	COM PROVIDER => Loading Communication Provider <C:\Program Files\OCS Inventory Agent\ComHTTP.dll>
AGENT => Using Communication Provider <OCS Inventory cURL Communication Provider> Version <2.10.1.0>
AGENT => Sending Prolog
	DID_CHECK => Read DeviceID <SAMIR-TI-2023-10-03-20-44-47> and MACs <18:56:80:9E:46:BA0A:00:27:00:00:0C40:B0:76:A5:2C:5340:B0:76:A5:2C:50> in file <ocsinventory.dat>
	COM SERVER => Initializing cURL library for sendRequest
	COM SERVER => Using cURL without server authentication
	COM SERVER => Disabling cURL proxy support
	COM SERVER => Enabling cURL SSL server validation support using CA Bundle <C:\ProgramData\OCS Inventory NG\Agent\cacert.pem>
	COM SERVER => Sending HTTP Post request to URL <http://192.168.1.251:83/ocsinventory>
	COM SERVER => HTTP Post response received <HTTP Status Code #403>
	COM SERVER => Cleaning cURL library
ERROR *** AGENT => Failed to send Prolog <HTTP Status Code #403>
AGENT => Unloading communication provider
AGENT => Unloading plug-in(s)
AGENT => Execution duration: 00:00:00.

**To Reproduce**
After installing the server and starting up the agents, they report well to the server, but the next day the server no longer receives inventory shipments from the agent.

The firewall is enabled on the server, with port 83 and 3306 open, it always works the first day, the next day, the connection between agent and server does not work.

**Comment by Lea9250** [comment]
Hi @wsamirmr,

Do you have any specific error in your server logs ? Check both the apache error log and the activity.log from the server. 
For the activity log, you'll need to enable the LOGLEVEL option in Configuration > General configuration > Server on your administration console.
What is the value of PROLOG_FREQ under Configuration > General configuration > Server ?

Regards, 
Léa

**Comment by Lea9250** [comment]
Hi @wsamirmr, 

Any update on this ? 

Regards,
Léa

**Comment by wsamirmr** [comment]
I'm sorry, but I couldn't wait that long, switch to another service for taking and managing inventories, I hope the app continues to grow, good day.
