### ISSUE TITLE
Possible to have autocomplete for search textbox

### ISSUE THREAD

**Issue by keyone78** [OCSInventory-NG/OCSInventory-ocsreports#157]
Using jquery UI autocomplete  can be integral in search textbox

**Comment by gillesdubois** [comment]
Hi,

Unfortunalty, this feature won't be added since a lot of feature are dynamic which make auto complete a bit hard.

Regards,
Gilles Dubois.

**Comment by keyone78** [comment]
understand, also found that not really good feature.
