### ISSUE TITLE
[BUG] Cut  first characters in the "command" field when creating the remote deployment

### ISSUE THREAD

**Issue by Gwadas** [OCSInventory-NG/OCSInventory-ocsreports#1572]
**OCS Inventory version**
Version : 2.12.0

**Describe the bug**
When create the new package on the builder remote deployment , the field "command' the first characters is ignored.
This causes an error, the first letter is cut off.

**To Reproduce**
1. Go to 'Deployment , Build , Custom Package, Action ->execute commande 
2. Example comand: opera.cmd
3. In info  file or Download.log : 

DOWNLOAD => Executing action <LAUNCH> for package <1697924101>
	PACKAGE => Launching command <pera.cmd> for package <1697924101> on <Saturday, October 21, 2023 23:37:57>
	PACKAGE => Package <1697924101> successfully launched. Command exit code is <1>. Package return code is <EXIT_CODE_1>
	PACKAGE => No post execution command provided for package <1697924101>
ERROR *** DOWNLOAD => Will not register package <1697924101> in history: result <EXIT_CODE_1> not a success
5. See error
To solve the problem, you need to add a space in the field. Is this normal?
[log.log](https://github.com/OCSInventory-NG/OCSInventory-ocsreports/files/13074390/log.log)

Thanks in advance

**Comment by charleneauger** [comment]
Hi @Gwadas ,

This bug has been fixed in 2.12.1.

Best regards,
Charlene
