### ISSUE TITLE
[BUG] REST API not working as it should

### ISSUE THREAD

**Issue by pchamorro2005** [OCSInventory-NG/OCSInventory-ocsreports#1575]
**OCS Inventory version**
Version : 2.12

**Describe the bug**
Some pages of REST API do work.
Some pages give we're sorry something went wrong
Some pages give raptor not found

**To Reproduce**
If I open https://ocs.sgc.gov.co/ocsapi/v1/my/routes it gives:
raptor not found

If I open https://ocs.sgc.gov.co/ocsapi/v1/computers/listID, it works but if I open https://ocs.sgc.gov.co/ocsapi/v1/computers?start=0&limit=10 it gives:

we're sorry something went wrong

Apache log shows:

```
DBD::mysql::db selectall_arrayref failed: Table 'ocsweb.eventlogs' doesn't exist at /usr/lib64/perl5/vendor_perl/Api/Ocsinventory/Restapi/ApiCommon.pm line 226.
[Thu Dec  7 12:03:59 2023] [error] DBD::mysql::db selectall_arrayref failed: Table 'ocsweb.eventlogs' doesn't exist at /usr/lib64/perl5/vendor_perl/Api/Ocsinventory/Restapi/ApiCommon.pm line 226.
```
So, I created table eventlogs and added HARDWARE_ID column, and it worked!

But /ocsapi/v1/my/routes gives raptor not found. So there are two bugs, one for eventlogs table not created and one for my/routes not found.

Software and snmp queries, work.

Thank you

**Comment by pchamorro2005** [comment]
Thank you very much for the answer. About myocsserver/ocsapi/v1/my/routes, it would be good clarify in the documentation about that because I wasn't not the only one who thougth that myocsserver/ocsapi/v1/my/routes should show the list of variables available to query through that API.

**Comment by gillesdubois** [comment]
Hello,

Thanks for your feedback.
I'll update the documentation to make sure it doesn't mislead other people :)

Regards,
Gilles DUBOIS.
