### ISSUE TITLE
Missing comma (,) causes sql to fail

### ISSUE THREAD

**Issue by tommo24** [OCSInventory-NG/OCSInventory-ocsreports#1585]
https://github.com/OCSInventory-NG/OCSInventory-ocsreports/blob/fd7926c9af211dfb1d3822d4809dca0f15584bb6/files/ocsbase_new.sql#L2465C1-L2491C57

Missing comma at line 2488 causes the create table 'software' to fail

**Comment by charleneauger** [comment]
Hi @tommo24 ,

Thanks for your report.
The fix has been merged, see https://github.com/OCSInventory-NG/OCSInventory-ocsreports/pull/1590

Best regards,
Charlene
