### ISSUE TITLE
[BUG] Database requirements mismatch at Wiki

### ISSUE THREAD

**Issue by RomBrz** [OCSInventory-NG/OCSInventory-ocsreports#1591]
**OCS Inventory version**
Version : Latest

**Describe the bug**
OCS documentation mismatch about database requirements with conflicting informations

**To Reproduce**
One page says that should be MySQL 4.1.0 or higher, BUT not work with 5.5 and upper:

"MySQL or MariaDB version 4.1.0 or higher with InnoDB engine active. Mysql version upper than 5.5 are not supported but may work."
https://wiki.ocsinventory-ng.org/01.Prerequisites/Libraries-version/

Another page says that should be MySQL 5.4 or higher:

"Database server currently can only be MySQL 5.4 or higher."
https://wiki.ocsinventory-ng.org/03.Basic-documentation/Deploying-database-server/

**Expected behavior**
The database requirements be the same at the documentation

**Comment by Lea9250** [comment]
Hi @RomBrz,

Thank you for bringing this to our attention. We fixed the requirements in the wiki, see https://github.com/OCSInventory-NG/Wiki/pull/185 .

Best regards,
Léa
