### ISSUE TITLE
[BUG] HTTPS loop after enabling SSL

### ISSUE THREAD

**Issue by SatanicGeek** [OCSInventory-NG/OCSInventory-ocsreports#1599]
**OCS Inventory version**
Version : 2.12.1

**Describe the bug**
I have an OCS server installation on Red Hat Enterprise Linux 9.3 (Plow). Everything is recent, no more than 2 weeks old.
Apache 2.4.57 and PHP 8.3.4 and a database on a different server.

I've just installed OCS on this server and everything worked fine until I enabled the SSL module.

When I try to access OCS Reports using https://a.domain.com/ocsreports/, a redirect loop is thrown and I end up with an error 404 with the following URL: https://a.domain.com/ocsreports//ocsreports/ocsreports/ocsreports/ocsreports/ocsreports/ocsreports/ocsreports/ocsreports/...
However, if I try to access it by typing https://b.domain.com/ocsreports/, everything works perfectly and there is no redirection.

The only way I can access OCS with a.domain.com is to specify index.php in the URL.

I've dug around in the Apache configuration files, the OCS configuration, I've disabled SELinux to test (and it doesn't work) and I've also tried creating .htaccess files everywhere but it doesn't work.

Every file I've modified, I've backed them up and restored them for testing, but nothing works.

My certificates (a.domain.com => alias b.domain.com and c.domain.com) are stored in a folder in /SCX/SSL/.

The necessary configuration for HTTPS is done via /etc/httpd/conf.d/ssl.conf.

I'm not sure what to do now ... Does anyone have any ideas or suggestions?

**To Reproduce**
1. I don't realy know what are the steps to reproduce this bug. Fresh install ?

**Expected behavior**
When I type https://a.domain.com/ocsreports, I should land on sign in page of OCS Reports

**Log file (optional)**
Apache logs
[access_log.log](https://github.com/OCSInventory-NG/OCSInventory-ocsreports/files/14947528/access_log.log)
[error_log.log](https://github.com/OCSInventory-NG/OCSInventory-ocsreports/files/14947529/error_log.log)
[ssl_access_log.log](https://github.com/OCSInventory-NG/OCSInventory-ocsreports/files/14947530/ssl_access_log.log)
[ssl_error_log.log](https://github.com/OCSInventory-NG/OCSInventory-ocsreports/files/14947531/ssl_error_log.log)
[ssl_request_log.log](https://github.com/OCSInventory-NG/OCSInventory-ocsreports/files/14947532/ssl_request_log.log)

**Comment by SatanicGeek** [comment]
Si j'ai bien compris, l'équipe de dev est FR mais j'ai créé l'issue en anglais dans le cas où quelqu'un d'autre a le même problème dans le futur.

**Comment by alacn1** [comment]
Looks like apache redirect rules misconfiguration.
You need post your apache site config, including all redirect rules.

**Comment by SatanicGeek** [comment]
I've completely redone it from scratch 0 'cause the error was very special.
It wasn't an Apache config error and I couldn't replicate the error.
