### ISSUE TITLE
[BUG] - Unable to bind to server: Invalid credentials

### ISSUE THREAD

**Issue by raimundoa** [OCSInventory-NG/OCSInventory-ocsreports#1607]
**OCS Inventory version**
Version : 2.8-2ubuntu1

**Describe the bug**
I need to change the ldap user configuration. But I can't access the web interface. Can I make these changes to the configuration file? If yes, which one?

**Log file (optional)**
Unable to bind to server: Invalid credentials in /usr/share/ocsinventory-reports/ocsreports/backend/AUTH/methode/ldap.php on line 143, referer: http://ip/ocsreports/

**Comment by raimundoa** [comment]
I found these settings in the ocsweb database in the config_ldap table.

tnks

**Comment by gillesdubois** [comment]
Hi,

I'm glad you found your issue solution.

Regards,
Gilles DUBOIS.
