### ISSUE TITLE
[BUG] Package validate remove colon from url with custom port when write data into download_enable table

### ISSUE THREAD

**Issue by cbuquet** [OCSInventory-NG/OCSInventory-ocsreports#1615]
**OCS Inventory version**
Version : 2.11.1

**Describe the bug**
/download with custom url and custom port not working.
Package validation remove colon from url  when write data into download_enable table

**To Reproduce**
1. Go to 'deployment - build' and build a simple msi package
2. Go to 'deployment - activate", chose new deployment and click on green mark 'activate'
3. Use url like fqdn:port/download for Fragments url and https url, and click ok
4. See url into database with select INFO_LOC, PACK_LOC from download_enable. ':' is missing between fqdn and port

**Expected behavior**
':' sould be conserved into download_enable for url with custom port

**Comment by charleneauger** [comment]
Hi @cbuquet ,

This bug has been fixed in 2.12.0 version (see PR https://github.com/OCSInventory-NG/OCSInventory-ocsreports/pull/1520).
Please update your server to fix it :-)

Best regards,
Charlene

**Comment by cbuquet** [comment]
Hi @charleneauger ,

Thank you for this quick reply.

Have a nice day,
Cyril
