### ISSUE TITLE
CVE DATA FOUND FOR MORE SOFTWARES BUT NOT DISPLAY ON CVE REPORTING

### ISSUE THREAD

**Issue by BEAR19931** [OCSInventory-NG/OCSInventory-ocsreports#1618]
OS: Ubuntu 22.04.4 LTS
OCS Version : 2.12.2
PHP: 8.2
APACHE: 2.4.52

CVE DATA FOUND FOR MORE SOFTWARES BUT NOT DISPLAY ON CVE REPORTING

![CVE OCS](https://github.com/user-attachments/assets/e7151c64-1258-4dd6-876a-b0579af0b857)

--------------------------------------------------------------------------------------------------------------------

I also attach the regex of Adobe

![REGEX](https://github.com/user-attachments/assets/e9bf540f-6a86-4543-9d26-e2803de61f64)

--------------------------------------------------------------------------------------------------------------------

Instead for other software it finds and lists the CVEs

Attach example:

![CVE FOUND](https://github.com/user-attachments/assets/c0da9164-2290-4eb9-aa9b-1e9bfc09356c)

Thanks

**Comment by LMS235** [comment]
can confirm the issue. CVEs are also found here, but are not displayed in the reporting.

Server Details:
PHP-Version : 8.1.2
Webserver : Apache/2.4.52 (Ubuntu)
Version OCSReports: 2.12.2

**Comment by LMS235** [comment]
Link https://github.com/OCSInventory-NG/OCSInventory-ocsreports/issues/1603

**Comment by charleneauger** [comment]
Hi @LMS235 @BEAR19931 ,

The log info "CVE data found" means that the API request to CVE Search returned a list of CVEs for this software.
From there, OCS will process the data and check if the versions match with the software present on OCS. If a CVE matches, then the log "CVE-[id] has been referenced" will be added and the entry will be added to the database.

I hope my explanation is understandable. :-)

Best regards,
Charlene

**Comment by blue-wq** [comment]
Hi @charleneauger,

Thanks for the explanation


Bye!
