### ISSUE TITLE
Possible to edit the "Add column:" drop down list from "All Computers"

### ISSUE THREAD

**Issue by SunnyKoya** [OCSInventory-NG/OCSInventory-ocsreports#162]
Hello, I was wondering if its possible to edit the "Add column:" drop down list from "All Computers" from OCSREPORTS.  Currently the drop down does not have video card as a option to display the video card of each computer that is on the list.   I would like to know if there is a easy way to add it to that list, or any solutions around this would be helpful... Would just like to know where I can see a list of all computers with the graphics card installed. 

Thanks.

**Comment by gillesdubois** [comment]
Hi,

Add graphics cards infos in the list can be a good idea.
Maybe this will be added in the 2.3 stable ;)

Regards,
Gilles Dubois.

**Comment by JasonZhang0320** [comment]
Hope ocsreport allow user add/remove the column from the drop down list. If support customize plugin info is better.

**Comment by TitanLV** [comment]
Indeed. IT Would be very useful if all parameters could be added to general Computer view.
I am in need of statistics from plugin osinstall (Operating system install date).
Currently  i have to export data from MySQL and then use excel "power".
