### ISSUE TITLE
synchronization of the OCS agent

### ISSUE THREAD

**Issue by fvhunter** [OCSInventory-NG/OCSInventory-ocsreports#1628]
**OCS Inventory version**
OCS Inventory Server 2.12.2

**Describe the bug**
I have had the problem with the synchronization of the OCS agent in Windows, it is not reflected in the OCS inventory platform, I install the agent in Windows and enter the IP of the server so that the packager connects with OCSreport but nothing is updated.

**Screenshots**
![Screenshot 2024-09-18 113804](https://github.com/user-attachments/assets/abca5f65-7da7-47fa-bcc4-b8e6c5928fae)

**Log file (optional)**
Apache / PHP / System log if needed
********************************************************
Starting OCS Inventory NG Agent 2.10.1.0 setup on 18/09/2024 at 10:03:09
Checking if setup not already running...OK.
Checking Operating System...OK, Windows 2000 or higher.
Command line is: "C:\Users\fvirgil\Downloads\OCS\OCS-Windows-Agent-Setup-x64.exe" 
Parsing command line arguments...OK.
Checking for silent mode...Disabled.
Checking for splash screen...Enabled.
Checking if logged in user has Administrator privileges...OK.
Creating directory <C:\ProgramData\OCS Inventory NG\Agent>...
SetACL allowing Users / Power users read/write permissions on <C:\ProgramData\OCS Inventory NG\Agent>...Result: 0
SetACL propagating inherited permissions on <C:\ProgramData\OCS Inventory NG\Agent\Download>...Result: 0
Trying to determine if service was previously installed...Yes.
Trying to stop service and kill processes...
Is Service <OCS Inventory Service> running...Yes.
Trying to stop Service <OCS Inventory Service>...Ok
Is Service <OCS Inventory Service> running...No - Waiting 1 second(s) for Service to stop...
Trying to find process OcsSystray.exe...Result: Yes
Trying to kill process OcsSystray.exe...Result: Yes
Trying to kill process OcsService.exe...Result: 603
Trying to kill process OCSInventory.exe...Result: 603
Trying to kill process download.exe...Result: 603
Trying to kill process inst32.exe...Result: 603
Waiting 10 seconds for processes to terminate...
Copying new files to directory <C:\Program Files\OCS Inventory Agent>...
Windows XP or higher detected, installing default cURL library and MS CRT/MFC 9.0...
Copying new files status is ;-)
Writing TAG <TI> into <C:\ProgramData\OCS Inventory NG\Agent\admininfo.conf> file...
Writing agent configuration file by launching ocsinventory.exe /SAVE_CONF...Result: 0
Windows Advanced Firewall is not available (Vista or higher). Skip adding custom rules.
[/NOW] used, so launching "C:\Program Files\OCS Inventory Agent\ocsinventory.exe"...Result: 0
Creating startup menu shortCut <C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Startup\OCS Inventory NG Systray.lnk> to start Systray applet...
Checking if service OCS Inventory Service is registered into Windows Service Manager...No
Service is installed, so unregistering OCS Inventory Service from Windows Service Manager...Result: 0.
Registering OCS Inventory Service into Windows Service Manager...Result: 0.
Starting OCS Inventory Service...Ok.
SUCCESS: OCS Inventory NG Agent 2.10.1.0 successfully installed on 18/09/2024 at 10:04:48
;-)

**Comment by Parnoud** [comment]
Hello, did you look you log on the server and agent ? 
Agent : ``C:\ProgramData\OCS Inventory NG\Agent\OCSInventory.log``
Serveur ``# less /var/log/ocsinventory-server/activity.log``

**Comment by fvhunter** [comment]
This is the log of the agent:
Starting OCS Inventory Agent on Thursday, September 19, 2024 20:29:39.
AGENT => Running OCS Inventory Agent Version 2.10.1.0
AGENT => Using OCS Inventory FrameWork Version 2.10.1.0
AGENT => Loading plug-in(s)
	DLL PLUGIN => Searching for Plug-in DLL(s) in folder <C:\Program Files\OCS Inventory Agent\plugins>
	DLL PLUGIN => 0 DLL Plug-in(s) successfully loaded on 0 DLL(s) found
AGENT => Using network connection with Communication Server
	COM PROVIDER => Loading Communication Provider <C:\Program Files\OCS Inventory Agent\ComHTTP.dll>
AGENT => Using Communication Provider <OCS Inventory cURL Communication Provider> Version <2.10.1.0>
AGENT => Sending Prolog
	DID_CHECK => Read DeviceID <SOPORTE-09-2024-09-18-15-01-18> and MACs <0A:00:27:00:00:0474:86:E2:1D:AF:1D00:15:5D:7D:DB:EE> in file <ocsinventory.dat>
	COM SERVER => Initializing cURL library for sendRequest
	COM SERVER => Using cURL without server authentication
	COM SERVER => Disabling cURL proxy support
	COM SERVER => Disabling cURL SSL server validation support
	COM SERVER => Sending HTTP Post request to URL <http://192.168.0.40:80/ocsinventory>
	COM SERVER => HTTP Post response received <HTTP Status Code #500>
	COM SERVER => Cleaning cURL library
ERROR *** AGENT => Failed to send Prolog <HTTP Status Code #500>
AGENT => Unloading communication provider
AGENT => Unloading plug-in(s)
AGENT => Execution duration: 00:00:00.

In the server i can't see the logs, or the logs are emptys, I see in the agent that error (ERROR *** AGENT => Failed to send Prolog <HTTP Status Code #500>), can you help me with this information?

**Comment by charleneauger** [comment]
@fvhunter, on your server, can you edit your communication conf file `/etc/apache2/conf-available/z-ocsinventory-server.conf`  and set `OCS_OPT_DBI_PRINT_ERROR` to `1`. Save and restart apache.
Launch your Windows agent.

Do you have errors that appear in your Apache log file `/var/log/apache2/error.log` ?

Regards,
Charlene

**Comment by fvhunter** [comment]
@charleneauger Thank You very much for your support, the issue was solved
