### ISSUE TITLE
format of date incorrent

### ISSUE THREAD

**Issue by keyone78** [OCSInventory-NG/OCSInventory-ocsreports#167]
1242 m/d/y <---plugins/language/english/english.text

should be 
1242 Y-m-d
where  generate format same was dateTime

**Comment by gillesdubois** [comment]
Hi, 

Which ocs version are you using ?

Regards,
Gilles Dubois

**Comment by keyone78** [comment]
Machines not seen in more than 15 day(s) the url  generate  date  11/8/16  <--- not working
![font1](https://cloud.githubusercontent.com/assets/8408374/20857906/41344fd4-b974-11e6-83c7-183ae63d2434.png)

![font3](https://cloud.githubusercontent.com/assets/8408374/20857972/b5d330ee-b974-11e6-80f4-5d43049275c0.png)

whereas the dataTimePicker generate 2016-11-01  <-- working
![font 2](https://cloud.githubusercontent.com/assets/8408374/20857971/a7a37c5e-b974-11e6-9db5-e5d4471a305d.png)

I am using 2.2 

Whereas in demo version is another way round.  So which to follow?  Kindy advise.

**Comment by gillesdubois** [comment]
Hi,

This bug has been fixed and will be available in the new version ( soon )

If you want more informations about this bug you can check this link : 
https://github.com/OCSInventory-NG/OCSInventory-ocsreports/issues/112

Regards,
Gilles Dubois.
