### ISSUE TITLE
ajouter la possibilité de planifier un WOL (wake on lan) réveil des postes

### ISSUE THREAD

**Issue by musklor** [OCSInventory-NG/OCSInventory-ocsreports#168]
FusionInventory, Updatengine etc... le permettent.

Ce serait parfait d'avoir cette possibilité dans OCS, c'est notre outil préféré et nous ne sommes pas prêts d'en changer.

Via le traitement par lots (sélection de postes), onglet Wake on Lan.

Merci à vous pour votre travail.

**Comment by gillesdubois** [comment]
Bonjour,

Merci pour votre soutien.

Votre proposition a bien été prise en compte. La team OCS reviendra vers vous pour vous informer du statut de votre demande.

Cordialement,
Gilles Dubois.

**Comment by zufflaur** [comment]
Bonjour,
Quel est l'avancée sur cette option de Wake-On-Lan ?
Merci d0avacne et excellente journée
Laurent Zufferey

**Comment by gillesdubois** [comment]
Bonjour,

Cette fonctionnalitée sera développée et bientôt disponible.

Coridalement,
Gilles Dubois.
