### ISSUE TITLE
AUTO_INCREMENT values are stored on sql files

### ISSUE THREAD

**Issue by AnaelMobilia** [OCSInventory-NG/OCSInventory-ocsreports#169]
On the files/ocsbase.sql & files/ocsbase_new.sql the current value of AUTO_INCREMENT is stored for some tables.

Theses files are provided to create table, no need to update the auto_increment counter (it will start from zero)

Regards

**Comment by gillesdubois** [comment]
Hi,

The sql file has been updated in our dev environement.
Pushing changes soon :)

Thanks for your contribution.
Regards,
Gilles Dubois.

**Comment by gillesdubois** [comment]
Fixed in https://github.com/OCSInventory-NG/OCSInventory-ocsreports/commit/d769421861f88a80675615ae66d95419d61c3c9e
