### ISSUE TITLE
Web interface function admin_ipdiscover

### ISSUE THREAD

**Issue by KallistiMan** [OCSInventory-NG/OCSInventory-ocsreports#17]
When trying to add a subnet there is no + button to add an ID.

**Comment by gillesdubois** [comment]
Already fixed, take a look at => https://github.com/OCSInventory-NG/OCSInventory-ocsreports/issues/11

Regards, Gilles Dubois

**Comment by KallistiMan** [comment]
sorry

**Comment by gillesdubois** [comment]
No problems, you just tried to help us !

Thanks you for contributing OCSInventory-ng
Regards, Gilles Dubois
