### ISSUE TITLE
Check for mbstring on install

### ISSUE THREAD

**Issue by ameurou** [OCSInventory-NG/OCSInventory-ocsreports#170]
Hello,

With PHP fpm, mbstring is not install by default on ubuntu (and so on debian ?) which can lead to a blank page when calling ocsreports/index.php for the first time and a "call to undefined function mb_strupper()" in apache log.

It could be usefull to check mbstring before loading page and inform admin that something is missing !

regards.

**Comment by MyTheValentinus** [comment]
Hello @ameurou and thanks for suggestion ! Have nice day
