### ISSUE TITLE
Unsorted show/hide columns in All computers

### ISSUE THREAD

**Issue by pchamo** [OCSInventory-NG/OCSInventory-ocsreports#171]
The "All computers, Show/hide, Select columns to show/hide" drop-down menu list is unsorted :( I think this is due to new ajax code in **ms_all_computers.php**, but I can't realize how to fix that. It seems, the line to fix is the one that contains **ajaxtab_entete_fixe**:

> if (is_defined($_SESSION['OCS']["mesmachines"])) {
>     $queryDetails .= "AND " . $_SESSION['OCS']["mesmachines"];
> }
> $queryDetails .= " group by h.id";
> $tab_options['LBL_POPUP']['SUP'] = 'name';
> $tab_options['LBL']['SUP'] = $l->g(122);
> $tab_options['TRI']['DATE']['e.bdate'] = "%m/%d/%Y"; // BIOS date format in database (varchar)
> 
> $entete = ajaxtab_entete_fixe($list_fields, $default_fields, $tab_options, $list_col_cant_del);

Previous non-ajax ocs reports versions, included this code:

> if (isset($_SESSION['OCS']["mesmachines"]) and $_SESSION['OCS']["mesmachines"] != '')
>         $queryDetails  .= "AND ".$_SESSION['OCS']["mesmachines"];
> $queryDetails  .=" group by h.id";
> $tab_options['LBL_POPUP']['SUP']='name';
> $tab_options['LBL']['SUP']=$l->g(122);
> $tab_options['TRI']['DATE']['e.bdate']="%m/%d/%Y";
> 
> $result_exist=tab_req($table_name,$list_fields,$default_fields,$list_col_cant_del,$queryDetails,$form_name,95,$tab_options);

Here the same question plus an image about this issue: http://ask.ocsinventory-ng.org/5568/unsorted-show-hide-columns-list-in-ajax-ocs-reports-versions

**Comment by pchamo** [comment]
![dropdown](https://cloud.githubusercontent.com/assets/14299138/21406464/cd8e4b6e-c799-11e6-9317-8d84142e9f9e.png)

**Comment by MyTheValentinus** [comment]
Hello,
Thanks for your report
Will be fixed soon

**Comment by gillesdubois** [comment]
Hi,
A fix will be available soon, see the screen below :)

![showhide](https://cloud.githubusercontent.com/assets/9396603/21450689/4ed14932-c8f9-11e6-91fc-a1254b068143.png)

Thanks for your report.
Regards,
Gilles Dubois.
