### ISSUE TITLE
Administrative data: Install Date

### ISSUE THREAD

**Issue by scifire91** [OCSInventory-NG/OCSInventory-ocsreports#178]
Hey,
i want to add a TAG field with the install date.

So i created a tag and chose the field type "date". The filed is added to the Administrative data but if i chose a date (future, past or today) and press the green "ok" button the date is resetted to 0000-00-00.

This also happens if i don´t press "ok"

We use OCS 2.3 on Ubuntu 16.04

**Comment by gillesdubois** [comment]
Hi,

Thanks for reporting this bug, you will be notified when an fix will be available :)

Regards,
Gilles Dubois.
