### ISSUE TITLE
[PLUGIN] Ms_Office

### ISSUE THREAD

**Issue by mickythekiller** [OCSInventory-NG/OCSInventory-ocsreports#18]
Une mise à jour du plugin permettant de remonter les 5 derniers caractères de la clé Office 2013 serait la bienvenue :) merci

cscript.exe "%ProgramFiles%\Microsoft Office\Office15\OSPP.VBS" /dstatus

**Comment by gillesdubois** [comment]
Bonjour,

Je suis déjà sur une mise a jour du plugin office, une version a jour sera bientôt disponible pour la 2.2RC

Gilles Dubois.

**Comment by gillesdubois** [comment]
Le plugin a été mise a jour pour la 2.2 RC.
Lien : https://github.com/OCSInventory-NG/Plugins/tree/Officepack
Malheureusement je n'ai pas le temps (En ce moment) de faire les modifications et améliorations nécessaire pour le rendre plus pertinent.

Je clos ton issue pour le moment et le met dans la liste des TODO :)

Merci pour ton rapport,
Cordialement, Gilles Dubois
