### ISSUE TITLE
Identified peripherals listed two times

### ISSUE THREAD

**Issue by scifire91** [OCSInventory-NG/OCSInventory-ocsreports#180]
Hello,
we use Server OCS 2.3 on Ubuntu 16.04.

when i identify a periperal from the ipscan thean each device is shown two times in the Identified peripherals list.
Also i can´t delete one or both of them cause nothing happen when i press the x for delete in the Actions Tab 
![grafik](https://cloud.githubusercontent.com/assets/17220258/21715465/f4de39b4-d404-11e6-8ab7-a96c667b9ff2.png)

**Comment by gillesdubois** [comment]
Hi,

Indeed there is a problem when creating a identified device. It appear twice and the delete query doesn't work.
Will commit a fix ASAP.

Thanks for your report.
