### ISSUE TITLE
Delete plugin via Webgui

### ISSUE THREAD

**Issue by scifire91** [OCSInventory-NG/OCSInventory-ocsreports#182]
Hey,
we use OCS 2.3RC on Ubuntu 16.04.

i noticed that if a plugin was deleted with the Web GUI (https://ocs/ocsreports/index.php?function=pluginsmanager) the plugin data is not deleted.
Especially the the .conf file in /etc/ocsinventory-server/plugins will prevent the apache server to start. (Or restart)
```
[Wed Jan 11 09:06:04.949219 2017] [perl:error] [pid 22059] $s->add_config() has failed: Can't locate Apache/Ocsinventory/Plugins/Runningprocess/Map.pm in @INC (you may need to install the Apache::Ocsinventory::Plugins::Runningprocess::Map module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.22.1 /usr/local/share/perl/5.22.1 /usr/lib/x86_64-linux-gnu/perl5/5.22 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.22 /usr/share/perl/5.22 /usr/local/lib/site_perl . /etc/apache2 /etc/ocsinventory-server/perl) at (eval 102) line 2.\nCompilation failed in require at (eval 99) line 2.\n
[Wed Jan 11 09:06:04.949255 2017] [perl:error] [pid 22059] Can't load Perl module Apache::Ocsinventory::Plugins for server ocs:0, exiting...
```
I think the button should do this or simply remind you to delete the files manually.
![grafik](https://cloud.githubusercontent.com/assets/17220258/21840883/22d03f00-d7e0-11e6-9c14-225b06cd225d.png)

**Comment by gillesdubois** [comment]
@scifire91 the setup is supposed to do it will investigate the problem.
