### ISSUE TITLE
PHP Fatal error:  Cannot redeclare return_bytes()

### ISSUE THREAD

**Issue by avsavchenko** [OCSInventory-NG/OCSInventory-ocsreports#183]
PHP Fatal error:  Cannot redeclare return_bytes() (previously declared in /usr/share/ocsinventory-reports/ocsreports/require/function_commun.php:704) in /usr/share/ocsinventory-reports/ocsreports/plugins/main_sections/ms_upload_file/ms_upload_file.php on line 29, referer: https://{censored}/ocsreports/?function=visu_computers

    PHP Version :
    Web Server :
    Database Server :
    Version OCSReports:

    7.0.13-0ubuntu0.16.04.1 (apache2handler)
    Apache/2.4.18 (Ubuntu)
    (Ubuntu) version 5.7.16-0ubuntu0.16.04.1
    2.3

**Comment by gillesdubois** [comment]
Hi,

We will investigate the issue and come back to you asap.

Regards,
Gilles Dubois.

**Comment by gitdevmod** [comment]
Hi,

I encountered this error too after upgrading to 2.3, the side effect is the config->agent page is empty. I renamed the function return_bytes() and line 84 in ms_upload_file.php and it worked as a workaround.

Thanks

**Comment by gillesdubois** [comment]
Indeed the function is declared twice ( in function_commun.php and in ms_upload_file.php )

We will fix the problem asap.
Thanks for your report.

Regards,
Gilles Dubois.
