### ISSUE TITLE
There's no network information in Hardware tab

### ISSUE THREAD

**Issue by drTr0jan** [OCSInventory-NG/OCSInventory-ocsreports#184]
There's no network information in Hardware tab on all computers in DB.
But the info exists in DB.
![screenshot](https://cloud.githubusercontent.com/assets/10733191/21929580/18286114-d9dd-11e6-8569-10db459f2c0e.PNG)

OCSInventory-ocsreports v.2.3 RELEASE

**Comment by gillesdubois** [comment]
Hi,

Can you send me your apache / php error log plz ?

Regards,
Gilles Dubois.

**Comment by drTr0jan** [comment]
What kind of log (params) have you interested?

**Comment by gillesdubois** [comment]
Can you send me these informations ? 

Php Version.
Ocs reports version 
Mysql version 
OS name / version ?

Thanks.

**Comment by drTr0jan** [comment]
PHP: _5.6.27_
OCSReports: _Source distribution version 5.7.15-log
2.3_
MySQL: _5.7.15_
OS: _FreeBSD 10.3-RELEASE-p11_

**Comment by gillesdubois** [comment]
Hi,

@drTr0jan, can you try to execute this query on your sql database ?

ALTER TABLE `networks` ADD `MTU` VARCHAR(255) NULL DEFAULT NULL AFTER `SPEED`;

Does this fix the network infos not displaying ?

Regards,
Gilles Dubois.

**Comment by drTr0jan** [comment]
Yeap. It works. Thx.
