### ISSUE TITLE
PHP Error after update

### ISSUE THREAD

**Issue by scifire91** [OCSInventory-NG/OCSInventory-ocsreports#185]
Hey,
after i updated my OCS Server from 2.3RC to 2.3 i get an PHP Fatal error:
From apache error log
` [:error] [pid 2022] [client 10.XX.XX.XX:52733] PHP Fatal error:  Uncaught Error: Call to undefined function curl_init() in /usr/share/ocsinventory-reports/ocsreports/require/function_commun.php:390\nStack trace:\n#0 /usr/share/ocsinventory-reports/ocsreports/require/html_header.php(121): get_update_json()\n#1 /usr/share/ocsinventory-reports/ocsreports/require/header.php(393): require_once('/usr/share/ocsi...')\n#2 /usr/share/ocsinventory-reports/ocsreports/index.php(44): require('/usr/share/ocsi...')\n#3 {main}\n  thrown in /usr/share/ocsinventory-reports/ocsreports/require/function_commun.php on line 390, referer: https://ocs/ocsreports/index.php?first`

**Comment by gillesdubois** [comment]
Hi,

You need to install php-curl

Regards,
Gilles Dubois.

**Comment by scifire91** [comment]
Thanks for this fast reply, this worked! 
Is it new that this package is needed? Maybe the requerments should be updated ;-)

**Comment by gillesdubois** [comment]
No problems :)
It should be checked in the update / install.php weird.
Will investigate the issue.
