### ISSUE TITLE
Plugins after update

### ISSUE THREAD

**Issue by scifire91** [OCSInventory-NG/OCSInventory-ocsreports#186]
Hey,
i have recently updated OCS Server from 2.3RC to 2.3.
Now the plugins didn´t work as they should. 
The plugins are showed unter the plugins tab as "Installed" so i can´t install them again.
But in the administrative data of a computer there´s no plugin anymore to see. 

Do i have to uninstall the plugins first and then reinstall them? (Manuall cause #182 still don´t work)

**Comment by gillesdubois** [comment]
Plugin need to be uninstalled prior the update.
That why you got problem :)

Just remove the entry in the plugin table and re-install your plugins.

**Comment by scifire91** [comment]
i´ve tried this, but unfortunately i crashed the hole Server :(
After a restart of Apache i have following output of the error.log

```
[Mon Jan 16 11:40:30.995908 2017] [perl:error] [pid 20878] $s->add_config() has failed: Invalid command 'PK\x03\x04\x14', perhaps misspelled or defined by a module not included in the server configuration at /usr/local/share/perl/5.22.1/Apache/Ocsinventory/Plugins.pm line 36.\nCompilation failed in require at (eval 99) line 2.\n
[Mon Jan 16 11:40:30.995948 2017] [perl:error] [pid 20878] Can't load Perl module Apache::Ocsinventory::Plugins for server rmvm052.domain.com:0, exiting...
```
I tried to reinstall ocs server, but theres still the same problem.
@gillesdubois you have any suggestions what i did wrong?
