### ISSUE TITLE
OCS 2.3 - Registry tab - RegValue wrong display

### ISSUE THREAD

**Issue by Laurent-1971** [OCSInventory-NG/OCSInventory-ocsreports#188]
With OCS 2.3 (CentOS 7), I have a problem with the Manage/Registry panel.

When editing an entry (or after creating a new one), the panel show the "Path of the key" as the "Name of the key that will be read".

It's just a display problem cause the inventory works and the the correct value is populated in the Computer inventory.

![image 1](https://cloud.githubusercontent.com/assets/13061511/21997563/444468ba-dc30-11e6-8601-3ba2e514736d.png)
![image 2](https://cloud.githubusercontent.com/assets/13061511/21997562/4440f0d6-dc30-11e6-8589-b2447e131c4d.png)

**Comment by gillesdubois** [comment]
Hi, 

the bug has been identified and will be fixed as soon as possible.
Thx for your contribution.

Regards,
Gilles Dubois

**Comment by Laurent-1971** [comment]
Thank you very much.
