### ISSUE TITLE
Typo in package build

### ISSUE THREAD

**Issue by StCyr** [OCSInventory-NG/OCSInventory-ocsreports#189]
I can see a typo in the demo, in "Deployment->Build" (http://demo.ocsinventory-ng.org/?function=tele_package):

`/var/lib/ocsinventory-reports/download/
It's not possible to create the packages creation directory.
The package creationis not possible so`

The last sentence is clearly not good English.

This would be better:

`Can't create the packages directory (/var/lib/ocsinventory-reports/download/).
Package creation is therefore not possible.`

**Comment by gillesdubois** [comment]
Hi,

You're right there is a typo error.
Will be fixed asap.

Regards,
Gilles Dubois.
