### ISSUE TITLE
dysfonctionnement de la recherche multicritère de logiciel sur la version française

### ISSUE THREAD

**Issue by tjaisson** [OCSInventory-NG/OCSInventory-ocsreports#190]
Lorsque l'interface est en français, les recherches multicritère sur "logiciel: nom" ou "logiciel: editeur" (et peut-être d'autres) ne fonctionnent pas. (par exemple "logiciel: nom ressemble \*firefox\*")
Pourtant cela fonctionne très bien en anglais, allemand. Je n'ai pas testé les autres langues.
Le dysfonctionnement se produit aussi sur la démo.

Je soupçonne qu'un nom de champ dans une requête a été localisé...

**Comment by gillesdubois** [comment]
Bonjour,

Merci pour votre retour, si le bug est confirmé sur nos environnements de devs un fix sera disponible sous peu.

Cordialement,
Gilles Dubois.

**Comment by gillesdubois** [comment]
Bonjour,

Le bug a été résolu. Celui-ci est dû à un problème d'échappement de caractère dans la requête sql.

Merci pour votre contribution.
Gilles Dubois.
