### ISSUE TITLE
Requete SQL version Française

### ISSUE THREAD

**Issue by julienm86** [OCSInventory-NG/OCSInventory-ocsreports#191]
Cette requete ne fonctionne pas

select distinct HARDWARE_ID,softwares.PUBLISHER as 'Logiciels: Société',softwares.NAME as 'Logiciels: Nom',softwares.VERSION as 'Logiciels: Version',softwares.FOLDER as 'Logiciels: Répertoire d'installation',softwares.COMMENTS as 'Logiciels: Commentaires' from softwares where ( ( NAME IN ('3CDaemon')))

**Comment by gillesdubois** [comment]
Bonjour,

Il me faut plus d'information pour pouvoir t'aider / résoudre le problème.
Voici les informations dont j'ai besoin : 
Version PHP
Version OCS
Version Mysql

Sur quel page le problème apparait ?

Merci d'avance,
Gilles Dubois.

**Comment by julienm86** [comment]
Bonjour,

Regardez sur votre version démo, le problème est le même quand vous voulez faire une recherche dans Tous les logiciels et quand vous cliquez sur un chiffre ou le logiciel est installé plusieurs fois.

De : Gilles Dubois [mailto:notifications@github.com]
Envoyé : mardi 17 janvier 2017 16:03
À : OCSInventory-NG/OCSInventory-ocsreports
Cc : Julien Morvan; Author
Objet : Re: [OCSInventory-NG/OCSInventory-ocsreports] Requete SQL version Française (#191)


Bonjour,

Il me faut plus d'information pour pouvoir t'aider / résoudre le problème.
Voici les informations dont j'ai besoin :
Version PHP
Version OCS
Version Mysql

Sur quel page le problème apparait ?

Merci d'avance,
Gilles Dubois.

**Comment by damienbelliard** [comment]
Bonjour, 

Je tiens à signaler que les issues Github sont gérées et renseignées par la communauté OCS Inventory. Il est donc important d'être précis sur votre demande pour qu'on puisse identifier les soucis éventuels, si c'est un problème de configuration ou bug au niveau du code.

Comme demandé par @gillesdubois , plusieurs informations relatives à votre installation sont nécessaire.

Concernant la démo, celle-ci permet d'avoir un aperçu du fonctionnement du logiciel OCS en version 2.3. Certaines corrections ont été réalisées ou sont déjà en cours de debug. D’où l'importance de la précision de votre demande pour éviter les doublons ou autres.

Cordialement

Damien Belliard

**Comment by gillesdubois** [comment]
Corrigé en même temps que le bug : https://github.com/OCSInventory-NG/OCSInventory-ocsreports/issues/190
