### ISSUE TITLE
Affectation de TAG sur utilisateur: Le caractère joker "*" ne fonctionne pas

### ISSUE THREAD

**Issue by lacroixbenoit5308** [OCSInventory-NG/OCSInventory-ocsreports#192]
Bonjour,

Dans Ocs Inventory NG, lorsque je clique sur un utilisateur afin de lui affecter les TAG et que je souhaite affecter toute une ruche de TAG (sous-arborescence) grâce au caractère joker *, OCS valide bien ma demande, mais n'exécute pas la commande...
                                                         Nouveau TAG: MON-ENTREPRISE/MA-VILLE/*
                                                          Jokers: ? pour un caractère et * pour plusieurs 
Exemple, je saisis: MON-ENTREPRISE/MA-VILLE/*
OCS va bien afficher MON-ENTREPRISE/MA-VILLE/* mais pas toute l'arborescence de TAG que contient MON-ENTREPRISE/MA-VILLE

Merci pour vos réponses.

Pour info:
Système
Nom du système :
Linux x86_64
Kernel :
3.2.0-4-amd64
RAM totale :
0.97
CPU :
AMD Opteron(tm) Processor 6344
Distribution :
PRETTY_NAME="Debian GNU/Linux 8 (jessie)" NAME="Debian GNU/Linux" VERSION_ID="8" VERSION="8 (jessie)" ID=debian HOME_URL="http://www.debian.org/" SUPPORT_URL="http://www.debian.org/support" BUG_REPORT_URL="https://bugs.debian.org/"
	
Logiciel
Version de PHP :
5.6.27-0+deb8u1 (apache2handler)
Serveur Web :
Apache/2.4.10 (Debian)
Serveur SQL :
(Debian) version 5.5.49-0+deb8u1

**Comment by gillesdubois** [comment]
Bonjour,

Merci pour votre retour, nous allons analyser le problème.

Cordialement,
Gilles Dubois.

**Comment by gillesdubois** [comment]
Bonjour, @lacroixbenoit5308,

Pourriez-vous essayer avec ce fix ? la gestion des wildcard devrait fonctionner correctement avec.

Merci pour votre contribution.
Gilles Dubois.
