### ISSUE TITLE
Problème de tri

### ISSUE THREAD

**Issue by SPCH-Info** [OCSInventory-NG/OCSInventory-ocsreports#193]
Sur la démo (v2.3), demander la liste des machines, ajouter le champ "Date BIOS", effectuer un tri croissant selon ce champ : Les 7 premiers enregistrements ne sont pas dans l'ordre ! 
Parmi ces 7 enregistrements 5 sont vides et 2 au format JJ/MM/AAAA alors que les enregistrements 8 à 40 sont au format anglo-saxon et correctement triés.

**Comment by gillesdubois** [comment]
Bonjour @SPCH-Info ,

Les infos de la démo viennent parfois de versions antérieur et certaines données peuvent apparaitre incorrecte.

Merci pour votre rapport, nous allons corriger le soucis dès que possible.

Cordialement,
Gilles Dubois.
