### ISSUE TITLE
Display ocsreports (DDMMYYY)

### ISSUE THREAD

**Issue by Unix-MTv** [OCSInventory-NG/OCSInventory-ocsreports#196]
HI =)
After a fresh install of OCS Invertery 2.3 incorrectly displayed:
Machines contacted today
Machines Inventoried today
Machines not seen in more than 15 day(s)

[default]
YYYYMMDD
index.php?function=visu_search&fields=HARDWARE-LASTCOME&comp=tall&values=2017-01-14&values2=&type_field=

[must]
DDMMYYY - OK
index.php?function=visu_search&fields=HARDWARE-LASTCOME&comp=tall&values=14/01/2017&values2=&type_field=

how to fix?
https://youtu.be/_fmmvb9lC_A

**Comment by gillesdubois** [comment]
Hi @Unix-MTv ,

You were right some date format where wrong depending on the language.

I tested all of them and changed the date format according the country one.

Here is the summary of the changed format : 

Japan format => MMDDYYYY ( %m/%d/%Y ) -> Date search working 
Turkish format => DDMMYYYY ( %d/%m/%Y ) -> Date search working 
Slovenian foramt => DDMMYYYY ( %d/%m/%Y ) -> Date search working 
Russian format => DDMMYYYY ( %d/%m/%Y ) -> Date search working
Portugal format => DDMMYYYY ( %d/%m/%Y ) -> Date search working
Hungarian format => YYYYMMDD ( %Y/%m/%d ) -> Date search working
Polish format => DDMMYYYY ( %d/%m/%Y ) -> Date search working
Brazilian format => DDMMYYYY ( %d/%m/%Y ) -> Date search working
Italian format => DDMMYYYY ( %d/%m/%Y ) -> Date search working
Spanish format => DDMMYYYY ( %d/%m/%Y ) -> Date search working
Dutch format => DDMMYYYY ( %d/%m/%Y ) -> Date search working

English and french format were already OK so i didn't do any change.

Thanks for your report and your contribution.

Regards,
Gilles Dubois.
