### ISSUE TITLE
Config -> Agent empty

### ISSUE THREAD

**Issue by scifire91** [OCSInventory-NG/OCSInventory-ocsreports#197]
Since OCS 2.3 is the site Config -> Agent empty.
Links on this URL:  /ocsreports/index.php?function=admin_upload

Version:
    PHP Version : 7.0.13-0ubuntu0.16.04.1 (apache2handler)
    Web Server : Apache/2.4.18 (Ubuntu)
    Database Server : (Ubuntu) version 5.7.16-0ubuntu0.16.04.1
    Version OCSReports: 2.3

**Comment by gillesdubois** [comment]
Hi,

We are already aware of the issue.
Check out this link : https://github.com/OCSInventory-NG/OCSInventory-ocsreports/issues/183

Thanks for your report.

Regards,
Gilles Dubois.
