### ISSUE TITLE
Le champ 'description' n'alimente plus la table 'download_available'

### ISSUE THREAD

**Issue by Laurent-1971** [OCSInventory-NG/OCSInventory-ocsreports#198]
Bonjour,

**Config**
OS Name : Linux x86_64
Version : 3.10.0-514.6.1.el7.x86_64
Distribution : CentOS Linux 7 (Core)
PHP Version : 5.4.16 (apache2handler)
Web Server : Apache/2.4.6 (CentOS) OpenSSL/1.0.1e-fips PHP/5.4.16 mod_perl/2.0.10 Perl/v5.16.3
Database Server : MariaDB Server version 5.5.52-MariaDB
Version OCSReports : 2.3

Quand on créé un package de déploiement, le champ "description" du formulaire n'alimente plus le champ "comment" de la table "download_available".

En mode debug, la requête qui apparaît lors de la création du package est

INSERT INTO download_available(FILEID, NAME, PRIORITY, FRAGMENTS, SIZE, OSNAME, COMMENT,ID_WK) VALUES ( '1485021344', 'Test Nom','5', '1','825438', 'WINDOWS', '','' )

**Comment by gillesdubois** [comment]
Hi,

We will try to reproduce the bug and fix asap.

Regards,
Gilles Dubois.
