### ISSUE TITLE
Table download links fails with error 'ERROR, the requested doesn't exists.'

### ISSUE THREAD

**Issue by ajeeth** [OCSInventory-NG/OCSInventory-ocsreports#199]
Whenever download link above a table in ocsreports is clicked, I get following error: 'ERROR, the requested doesn't exists.'. 
/var/log/apache2/error.log has multiple lines of following warning:
`[Mon Jan 23 00:40:02.084310 2017] [:error] [pid 27681] [client 10.18.127.2:37076] PHP Warning:  Invalid argument supplied for foreach() in /usr/share/ocsinventory-reports/ocsreports/plugins/main_sections/ms_export/ms_csv.php on line 46, referer: http://ocsinventory.alghurair.com/ocsreports/index.php?function=visu_all_soft`

I'm running:
    OCSReports Version:  2.3
    OS Name:                    Linux x86_64
    Kernel Version:            3.16.0-4-amd64
    Distribution:                 Debian GNU/Linux 8 (jessie)
    PHP Version:               5.6.29-0+deb8u1
    Web Server:                Apache/2.4.10
    Database Server:        MySQL 5.5.53-0+deb8u1

![ocsi1](https://cloud.githubusercontent.com/assets/531732/22186249/1de5296c-e10c-11e6-8c67-9cce44316b80.png)

![ocsi2](https://cloud.githubusercontent.com/assets/531732/22186250/258e5b52-e10c-11e6-99ca-50e860d0a1dc.png)

**Comment by gillesdubois** [comment]
Hi,

From which version did you updated to 2.3 ?
Thanks for your report.

Regards,
Gilles Dubois.

**Comment by ajeeth** [comment]
This is a fresh install.

Thanks.

**Comment by gillesdubois** [comment]
Hi,

We are currently investigation the issue.
You will be notified as soon as a fix will be available.

Regards,
Gilles Dubois.

**Comment by gillesdubois** [comment]
Hi @ajeeth,

CSV export should work with that fix.
Could you try and come back to me ?

Regards,
Gilles Dubois.

**Comment by ajeeth** [comment]
Passed all my tests.

Thank you.

**Comment by Raghav000** [comment]
Hii, 
Whenever i click download link above a table in ocsreports, i will get all the data in excel sheet except software:name coloumn. I will get software name coloumn as empty or tab.  How can i resolve this issue. Please help me .
My OCSReports Version: 2.3.1 and 
PHP Version :5.6.30
