### ISSUE TITLE
Hiding/showing columns not working as expected

### ISSUE THREAD

**Issue by pchamo** [OCSInventory-NG/OCSInventory-ocsreports#20]
I wanted to hide CPU and RAM columns, but it's not working as expected. I wanted to show some custom columns and always the first administrative column is shown, and I think is not working as expected. I recorded an uploaded a video here: https://youtu.be/QCpOlgSEnfA

**Comment by benkohler** [comment]
I see the same thing, been meaning to open an issue but his video describes it better than words alone.  Instead of applying the the selected change on the second click when you close the menu, it applies on    the first click to open AND the second click to close.

**Comment by pchamo** [comment]
It's far from expected! Impossible to work like that.

**Comment by pchamo** [comment]
I don't think that to remove the hide column feature with a single click is a good idea. Why to force to the admins/technicians/users to use a dropdown list to hide a column if you can do that with a single click?

Also, I don'tk know if in the personal preferences there is an option to select the columns that the user wants to be shown each time he/she logs on.

In mi opinion, the change in the hide columns feature in the RC version is not right, it's not sound. Thank you.

**Comment by gillesdubois** [comment]
Hello,

I've already encountered this bug.
This one happen on some browser because of the datatable configuration.
I'm on it, i will notice you when a fix will be available.

Thanks you for contributing to ocs inventory.
Regards, Gilles Dubois

**Comment by pchamo** [comment]
Thank you very much :)
