### ISSUE TITLE
Uptime field for Network SNMP Objects

### ISSUE THREAD

**Issue by tsmr** [OCSInventory-NG/OCSInventory-ocsreports#200]
Version 2.3.0
Into interface, on snmp objects : 

![image](https://cloud.githubusercontent.com/assets/13178158/22198815/8158dbb4-e158-11e6-88a7-621f416bbdb3.png)

The translation is not good & the showed value is not readable

Informations
Object SNMP : Wifi network access point
[UPTIME] => ARRAY(0xb8d43740)

**Comment by gillesdubois** [comment]
Salut @tsmr,

As-tu un xml de l'inventaire snmp sur ton agent ?

Merci d'avance,
Gilles Dubois.

**Comment by tsmr** [comment]
Agent version : OCS-NG_unified_unix_agent_v2.1.1

On GLPI : 
![image](https://cloud.githubusercontent.com/assets/13178158/22200094/f3d2caa6-e15d-11e6-973a-9cc98969a337.png)

**Comment by tsmr** [comment]
I upgraded agent to 2.3.0 for verification

**Comment by tsmr** [comment]
Same Problem with agent 2.3.0

Last SNMP Inventory 23-01-2017 14:06

[UPTIME] => ARRAY(0xb8d965a0)

**Comment by tsmr** [comment]
I upgrade my Linux agent to 2.3.0 and force inventory : 

Into XML : 
```
<COMMON>
        <CONTACT>test@test.com</CONTACT>
        <DESCRIPTION>ProCurve J9089A Switch 2610-48-PWR, revision R.11.119, ROM R.10.06 (/sw/code/build/nemo)</DESCRIPTION>
        <IPADDR>X.X.X.X</IPADDR>
        <LOCATION>PAris</LOCATION>
        <MACADDR>00:XX:XX:XX:XX</MACADDR>
        <NAME>Swith Name</NAME>
        <SNMPDEVICEID>2574f0ddad51c3d3211225134554e026</SNMPDEVICEID>
        <UPTIME>66 days, 23:22:38.45</UPTIME>
      </COMMON>
```

into ocsweb database : 

uptime field into snmp table : ARRAY(0xb8f5f804)
Lastdate field into snmp table : 2017-01-27 13:16:43

**Comment by tsmr** [comment]
And second request, i think it will be intersesting to add LastDate ccolumn into interface no ?

**Comment by tsmr** [comment]
Error  DBI : 
```
DBD::mysql::st execute failed: Table 'ocsweb.snmp_mibs' doesn't exist at /usr/share/perl5/vendor_perl/Apache/Ocsinventory/Server/Capacities/Snmp.pm line 181.
DBD::mysql::st fetchrow_hashref failed: fetch() without execute() at /usr/share/perl5/vendor_perl/Apache/Ocsinventory/Server/Capacities/Snmp.pm line 183.
```

After create this table : 
```
CREATE TABLE `snmp_mibs` (
`ID` INTEGER NOT NULL AUTO_INCREMENT,
`VENDOR` VARCHAR(255) DEFAULT NULL,
`URL` VARCHAR(255) DEFAULT NULL,
`CHECKSUM` VARCHAR(255) DEFAULT NULL,
`VERSION` VARCHAR(5) DEFAULT NULL,
`PARSER` VARCHAR(5) DEFAULT NULL,
PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8;
```

It's resolved 🥇
