### ISSUE TITLE
The communication server encountered the following error on install 

### ISSUE THREAD

**Issue by achebarev** [OCSInventory-NG/OCSInventory-ocsreports#201]
Good afternoon! Unknown error code. What is the problem? How to fix? The plugin does not work.
![image](https://cloud.githubusercontent.com/assets/25382199/22364366/0e959838-e482-11e6-8461-f51401d398f0.png)

**Comment by gillesdubois** [comment]
hi @achebarev,

Can you send me your error logs ?

Regards,
Gilles Dubois.

**Comment by achebarev** [comment]
Apache?

**Comment by gillesdubois** [comment]
yes, apache / php

**Comment by achebarev** [comment]
/var/log/apach2
[error.zip](https://github.com/OCSInventory-NG/OCSInventory-ocsreports/files/747824/error.zip)

**Comment by achebarev** [comment]
in debug lvl
[error.zip](https://github.com/OCSInventory-NG/OCSInventory-ocsreports/files/747985/error.zip)

**Comment by gillesdubois** [comment]
Hi @achebarev , 

From your error log, it look like your ocs is not installed correctly.
You should try re-installing it and try again.

Regards,
Gilles Dubois.
