### ISSUE TITLE
L'option SSLRequireSSL perturbe l'ajout des plugins

### ISSUE THREAD

**Issue by Laurent-1971** [OCSInventory-NG/OCSInventory-ocsreports#202]
Si on impose le SSL en décommentant SSLRequireSSL dans le fichier "/etc/httpd/conf.d/ocsinventory-reports.conf"

![sslrequiressl](https://cloud.githubusercontent.com/assets/13061511/22427316/fa65d4d0-e702-11e6-8883-1ba750c9624d.png)

quand on ajoute un plugin, on obtiens une erreur

**The communication server encountered the following error on install :  Err_02**

![err_02](https://cloud.githubusercontent.com/assets/13061511/22427350/232f34b0-e703-11e6-8187-9edc90961763.png)

et dans la log apache

**[Mon Jan 30 15:34:26.036895 2017] [ssl:error] [pid 3016] [client 127.0.0.1:54444] AH02219: access to /usr/share/ocsinventory-reports/ocsreports/upload/uptime.zip failed, reason: SSL connection required**

**Comment by gillesdubois** [comment]
Bonjour,

Merci pour votre retour, effectivement le SSL n'est pas géré par le moteur de plugin.
Je l'ajoute en bug et le met en priorité pour fix :)

Cordialement,
Gilles Dubois.

**Comment by MyTheValentinus** [comment]
Bonjour @Laurent-1971,
C'est fixé !
Merci
