### ISSUE TITLE
Le compte DFT_DB_CMPT est appelé quelque part

### ISSUE THREAD

**Issue by Laurent-1971** [OCSInventory-NG/OCSInventory-ocsreports#203]
Bonjour,

J'ai remarqué que j'avais des erreurs d'authentification SQL quand je navigue dans la console d'administration OCS.

![image](https://cloud.githubusercontent.com/assets/13061511/22468826/17e4d43a-e7ca-11e6-9a48-5a203effd062.png)

Pourtant, les fichiers /etc/httpd/conf.d/z-ocsinventory-server.conf et /usr/share/ocsinventory-reports/ocsreports/dbconfig.inc.php contiennent bien les bonnes info de connexion.

J'ai cherché partout un endroit où un mot de passe serait codé et j'ai trouvé le fichier **/usr/share/ocsinventory-reports/ocsreports/var.php** qui contient

```
//====================================================================================
// Demo mode config and defaults accounts logins
//====================================================================================
define('DEMO', false);
define('DEMO_LOGIN', 'demo');
define('DEMO_PASSWD', 'demo');
define('DFT_DB_CMPT', 'ocs');
define('DFT_DB_PSWD', 'ocs');
define('DFT_GUI_CMPT', 'admin');
define('DFT_GUI_PSWD', 'admin');
```

Si je remplace avec define('DFT_DB_CMPT', '**ocszz**'); dans ce fichier, les erreurs SQL suivent

![image](https://cloud.githubusercontent.com/assets/13061511/22468967/b00a5e24-e7ca-11e6-98fa-625be0b2c332.png)

ce qui signifie bien que ces variables sont utilisées.

Par **/usr/share/ocsinventory-reports/ocsreports/require/html_header.php** en fait.

Faut-il pas alors aussi modifier ce fichier si on change le couple cpt/pwd ocs/ocs ?
Ou c'est une erreur du fichier html_header.php

**Comment by TiVince** [comment]
j'avais également constaté  ce comportement,  c'est ce qui sert à tester que le compte par défaut a bien été modifié (changement du mot de passe). Si ce n'est pas le cas cela affiche un bandeau d'alerte en haut de la page. 
 //defaut user already exist on databases?
130     try {
**131         $link_read = mysqli_connect(SERVER_READ, DFT_DB_CMPT, DFT_DB_PSWD);
132         $link_write = mysqli_connect(SERVER_WRITE, DFT_DB_CMPT, DFT_DB_PSWD)**;
133         mysqli_select_db($link_read, DB_NAME);
134         mysqli_select_db($link_write, DB_NAME);
135         $msg_header_error[] = $l->g(2024) . ' ' . DB_NAME;
136         $msg_header_error_sol[] = $l->g(2025);
137     } catch (Exception $e) {

Le problème c'est que comme c'est  dans html header.php le test est fait à chaque  include de cette page, cela  génère énormément de message 'Acces denied for user ...'  comme on voit dans ton log.

Cela se voit également sous mysql, on a un incrément de 2 erreurs dans le compteur Aborted connect à chaque appel de page ( on fait 2 tests de connexion par page !!). A la fin de la journée sur mon serveur de production  cela se chiffre en milliers d'erreurs.

**Comment by Laurent-1971** [comment]
@TiVince : merci de l'info. Je n'avais pas pensé à ça. Comme je suis en train de migrer d'un serveur 2.1 sous Windows à un serveur 2.3 sous CentOS, je regarde un peu partout que tout va bien et je craignais que l'alerte soit plus grave que ça.

**Comment by gillesdubois** [comment]
Bonjour, @TiVince @Laurent-1971 

Merci pour votre feedback.
Effectivement cette portion de code est utilisée pour check si la connexion au compte par défaut fonctionne ( et afficher l'erreur de sécurité si c'est le cas )

Le message apparait dans les logs mysql si les options suivantes de verbosité sont renseignée dans le my.cnf : 
```
general_log             = 1
log_warnings            = 2
```

Un fix sera donc bientôt disponible et le check ne sera réalisé que lors de la connexion du client et non plus sur chaque page.
Néanmoins, le message de warning apparaitra au moins une fois a la connexion de l'utilisateur.

Cordialement,
Gilles Dubois.
