### ISSUE TITLE
delete deployment doesn't remove entry in DB

### ISSUE THREAD

**Issue by StCyr** [OCSInventory-NG/OCSInventory-ocsreports#206]
Si vous créez un déploiement "foobar" et que vous le supprimer par après (par exemple parcque vous avez fais une mauvaise manipulation lors du build), son entrée n'est pas supprimée de la DB avec pour résultat que si vous essayez de recréer un déploiement appellé "foobar" par après, le serveur vous en empêche en disant "This package name already exists".

Lancer la commande SQL `delete from download_available where FILEID='<package_timestamp>'` résoud le problème, mais on ne devrait pas avoir à lancer une commande SQL pour ce faire à mon sens.

Cyrille

**Comment by gillesdubois** [comment]
Bonjour @StCyr, 

En 2.3 les paquets ne sont pas directement supprimé mais passe en "archivage" 
Il faut donc aller dans l'onglet "Deleted packages" dans le menu "Deployment -> Activate"

![activate](https://cloud.githubusercontent.com/assets/9396603/22544624/ea4a45c4-e935-11e6-92b8-47a13dfa8dfe.png)

Cordialement,
Gilles Dubois.
