### ISSUE TITLE
L'utilisation des Options avancées de déploiement cause le reboot du client

### ISSUE THREAD

**Issue by Laurent-1971** [OCSInventory-NG/OCSInventory-ocsreports#209]
Avec la version 2.3, lors de l'ajout d'un package de déploiement aux machines, si on choisi d'utiliser les options avancées de déploiement (pour forcer un même déploiement par exemple), le choix du champ "Action" est sur **Reboot** et il n'est pas possible de l'enlever. On ne peut que laisser Reboot ou mettre Shutdown.

Résultat : la machine cliente redémarre automatiquement à la fin du déploiement !

![image](https://cloud.githubusercontent.com/assets/13061511/22587235/261e722a-ea01-11e6-84a9-e7b6e72c16a4.png)

![image](https://cloud.githubusercontent.com/assets/13061511/22587268/50df4d2c-ea01-11e6-8422-7eefb5155cbe.png)

**Comment by gillesdubois** [comment]
Hi @Laurent-1971 ,

Can you try with this fix ? Everything is ok on my installation.

Regards,
Gilles Dubois.

**Comment by Laurent-1971** [comment]
Seems good. A blank

![image](https://cloud.githubusercontent.com/assets/13061511/22599863/a0cc4312-ea38-11e6-94d3-d4ec79290ba3.png)

And in the agent log, action is now NONE

`<PARAM ID="1485878293" SCHEDULE="" CERT_FILE="INSTALL_PATH/cacert.pem" TYPE="PACK" INFO_LOC="ocs.domaine.tld/download" CERT_PATH="INSTALL_PATH" PACK_LOC="ocs.domaine.tld/download" FORCE="0" POSTCMD="NONE" />`

Thx.

**Comment by gillesdubois** [comment]
Thanks for your contribution !
Have a nice day
