### ISSUE TITLE
All it's blank when a make a search for Registry Data

### ISSUE THREAD

**Issue by orlaguitar** [OCSInventory-NG/OCSInventory-ocsreports#210]
### General informations
Operating system : Ubuntu 16.04.1 TLS

### Server informations
Php version : 7.0.13
Myqsl version : 14.14 
Apache version :  2.4.18

### OCS Inventory informations
Ocsreports version : 2.3 

### Problem's description
Hello guys, I have some trouble to search any computers when I use the "Registry: Key Name" criteria, the filed where I select the Registry entry is, like that:

![screen shot 2017-02-06 at 08 29 23](https://cloud.githubusercontent.com/assets/25581899/22643638/7e40105c-ec46-11e6-9133-48791b78132c.png)

I have three entries:

![screen shot 2017-02-06 at 08 34 23](https://cloud.githubusercontent.com/assets/25581899/22643769/16514b90-ec47-11e6-9543-a04718360afc.png)

I made too the adjust suggested on the Fix #188 , but even after that I can't search using this data.

Something more to do?

Tks,

Orlando

**Comment by gillesdubois** [comment]
Hi,

Are the registry keys active and actually inventoried on computers ?

Regards,
Gilles Dubois.

**Comment by orlaguitar** [comment]
Hello,

Look this example:

The target PC: WS001CX01

![image](https://cloud.githubusercontent.com/assets/25581899/22791845/d6f3b7f2-eed1-11e6-8523-e11b50be3807.png)

It seems ok, and the host is inventoried by OCS:

![image](https://cloud.githubusercontent.com/assets/25581899/22791881/f91cf30c-eed1-11e6-9fae-b3fc1ae056cc.png)

I make some changes in the Registry Key, including some dash "/", but without success:

![image](https://cloud.githubusercontent.com/assets/25581899/22791932/267936ee-eed2-11e6-953a-8cbd75e65713.png)

**Comment by gillesdubois** [comment]
Thx for the fast anwser.
Does the registry key appear in the machine detail ? ( In administrative data tab )

**Comment by orlaguitar** [comment]
Neither

![image](https://cloud.githubusercontent.com/assets/25581899/22792815/2b41d502-eed5-11e6-828a-717d1603be9d.png)

**Comment by gillesdubois** [comment]
Ok, did you activated the registry option in ( config -> config menu ) tab registry ?

**Comment by orlaguitar** [comment]
No.

I didn't watch that... :( 👎 

Sorry

**Comment by gillesdubois** [comment]
Haha no problems @orlaguitar. Glad to hear you fixed your problem :)

Have a nice day,
Gilles Dubois.
