### ISSUE TITLE
Accounts Info Computers don't show TAG info corretly

### ISSUE THREAD

**Issue by lfpzorro** [OCSInventory-NG/OCSInventory-ocsreports#212]
Hello!

Sorry for my bad English!!! Hehe

When I disable the option "may change accounts info computers" in user profile configuration, the TAG info is not shown correctly in computers details screen.

The TAG info should appear, and the modify button no. But nothing happen.

Someone has any idea about this issue!

Following bellow examples of the problem:

Option "may change accounts info computers" is ENABLE
![enable](https://cloud.githubusercontent.com/assets/25637654/22738700/97daf900-edef-11e6-95d7-af34d46757b0.png)

Option "may change accounts info computers" is DISABLE
![disable](https://cloud.githubusercontent.com/assets/25637654/22738704/9a21a330-edef-11e6-801d-940cdeee807f.png)

Thanks advance!

### General informations
Operating system : Debian GNU/Linux 8 (jessie)
Kernel: 3.16.0-4-686-pae

### Server informations
Php version : 5.6.29-0+deb8u1 (apache2handler)
Mysql / Mariadb / Percona version : MySQL Community Server (GPL) by Remi version 5.1.56
Apache version : Apache/2.4.10 (Debian)

### OCS Inventory informations
Ocsreports version : 2.3

**Comment by gillesdubois** [comment]
HI @lfpzorro ,

Your problem has been fixed.
Now disabled fields will be displayed instead of hidden one :) 

Thanks for your report.

Regards,
Gilles Dubois.

**Comment by lfpzorro** [comment]
Hello,

I tested and it's working.

Thanks a lot!
