### ISSUE TITLE
Analyze button [question] 

### ISSUE THREAD

**Issue by scifire91** [OCSInventory-NG/OCSInventory-ocsreports#213]
### General informations
Operating system : Ubuntu 16.04.1

### Server informations
Php version : 7.0.13-0ubuntu0.16.04.1 (apache2handler)
Mysql : (Ubuntu) version 5.7.17-0ubuntu0.16.04.1
Apache version : Apache/2.4.18 (Ubuntu)

### OCS Inventory informations
Ocsreports version : 2.3

### Problem's description
On the ipdiscover i have an Analyze button at the bottom page. If press a new window opens with only a button "clear cache". Does the "Analyze" button have any function (expect redirect to clear cache)? If not i think it would be a help remove or rename it

**Comment by gillesdubois** [comment]
Hi @scifire91,

Indeed the analyse problem just redirect to the clear cache view.
I will mark your issue as an enhancement but will not be a priority ( it's working fine it's just that can be a bit frustrating to click two times to do one action ).

Regards,
Gilles Dubois.
