### ISSUE TITLE
WOL fatal error

### ISSUE THREAD

**Issue by acg16** [OCSInventory-NG/OCSInventory-ocsreports#215]
### General informations
Operating system : W7

### Server informations
Php version : 5.4.3
Mysql / Mariadb / Percona version : Mysql 5.5.16
Apache version : 2.2.21 (Win32)

### OCS Inventory informations
Ocsreports version : 2.3RC

### Problem's description
*Describe your problem here*
If I click on "WOL" in the link close to IP address (ocsreports/index.php?function=computer&head=1&systemid=2) this message appear: "Fatal error: Call to undefined function socket_create() in xampp\htdocs\ocsreports\require\function_wol.php on line 40"
(Previously: "Do you want a Wake On Lan on this computer?")

Thanks for this software. It is really usefull.

**Comment by gillesdubois** [comment]
Hi,

Did you enabled your socket extension in your php.ini ?

Regards,
Gilles Dubois.

**Comment by acg16** [comment]
How fast! That was it
Thank you!

Regards
Alberto
