### ISSUE TITLE
No "delay" button for agent with OCS 2.3 Server

### ISSUE THREAD

**Issue by gillesdubois** [OCSInventory-NG/OCSInventory-ocsreports#216]
From : http://ask.ocsinventory-ng.org/6130/no-delay-button-for-agent-with-ocs-2-3-server

### General informations
Operating system : All

### Server informations
Php version : All
Mysql / Mariadb / Percona version : All
Apache version : All

### OCS Inventory informations
Ocsreports version : 2.3

### Problem's description
Hello,

We upgrade ocs server (linux) to 2.3 and agent to 2.3 Windows.

Since, when i configure a deployment package with "Delay" option for user, the button no more appear when notification pop on screen.

PS : make a test with windows agent 2.1.1.3 and 2.3 server : DELAY button not appear.

Upgrade to 2.3 broke this option.

Any solution?

regards.

**Comment by paullepetit** [comment]
Hi, 

I just make a test, here is the output I get:

<img width="629" alt="capture d ecran 2017-02-17 a 15 38 12" src="https://cloud.githubusercontent.com/assets/20063651/23069551/265758ec-f528-11e6-9a7c-b141c29217fb.png">

I got three button : 
"OK" to validate
"Plus tard" which is the delay button 
"Annuler" which is the cancel button

Are you sure you created your package and checked the right options ?

Regards,
Paul Lepetit
