### ISSUE TITLE
LDAP sadmin users can not create users

### ISSUE THREAD

**Issue by saep-es** [OCSInventory-NG/OCSInventory-ocsreports#218]
### General informations
CentOS Linux 7 (3.10.0-514.2.2.el7.x86_64)

### Server informations
5.4.16 (fpm-fcgi)
Apache/2.4.6 (CentOS) PHP/5.4.16 mod_perl/2.0.10 Perl/v5.16.3
MariaDB Server version 5.5.52-MariaDB 2.3

### OCS Inventory informations
Ocsreports version : 2.3.0.0

### Problem's description
A local sadmin user can create users, as expected but a LDAP sadmin user can not. The password field for the new user is not presented.

![ldap_sadmin_user](https://cloud.githubusercontent.com/assets/21181693/23067737/cd3df178-f507-11e6-811a-c220ec7a8c0d.png)
![local_sadmin_user](https://cloud.githubusercontent.com/assets/21181693/23067736/cd38e43a-f507-11e6-8bce-920c75324934.png)

**Comment by MyTheValentinus** [comment]
Hello,
Thanks for your report.
