### ISSUE TITLE
Email reports function

### ISSUE THREAD

**Issue by wulfansur** [OCSInventory-NG/OCSInventory-ocsreports#219]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General information
Operating system: Linux x86_64, Kernel: 2.6.32-504.30.3.el6.x86_64

### Server informations
Php version : 5.4.45 (apache2handler)
Mysql / Mariadb / Percona version : MySQL Community Server (GPL) by Remi version 5.5.46

Apache version : Apache/2.2.15 (CentOS)

### OCS Inventory information
OCS reports version: 2.2

### Problem's description
I would like to request adding an email reports function so that we email certain data sets from OCS to our alerts email to keep track of key data points that will assist our support methods.

Thanks,
Jaime

**Comment by gillesdubois** [comment]
Hi @wulfansur ,

Your idea might be interessting to generate simple automated report without the need to connect to the web interface.
I'll mark your issue as a new feature.  

Thanks for your contribution.

Regards,
Gilles Dubois.

**Comment by gillesdubois** [comment]
Hi,

The developpment has been started and is now in the following pullrequest : #411 
I will close this issue, all the related comments will be made in the PR.
Thx for your contribution.

Regards,
Gilles Dubois.
