### ISSUE TITLE
Useless warning when assigning a package from group distribution

### ISSUE THREAD

**Issue by ameurou** [OCSInventory-NG/OCSInventory-ocsreports#22]
Having 2 or more network cards on a computer, for example wired and wireless card, with one of them disabled raised a warning when we assign a package from group distribution with a matching rule on subnet.

As the package is assign thanks to the nework card whose match the subnet, the warning is not relevant and should not be raised.

Thanks

**Comment by gillesdubois** [comment]
Hello,

Can you provide me some additional informations please ?
Such as :
    - Which version of ocs inventory server you're running
    - (If you can) provide a screen of the group distribution page with the warning message

Thanks you for reporting this bug,
Regards, Gilles Dubois.

**Comment by arnaudmeurou** [comment]
I use the stable version 2.1.2.

Here are screenshots of the warning for one machine and the network card details.

![useless_warning1](https://cloud.githubusercontent.com/assets/11721263/10076883/fb6da86c-62dd-11e5-8d01-bc7d09034803.JPG)
![useless_warning2](https://cloud.githubusercontent.com/assets/11721263/10076884/fb6fa716-62dd-11e5-92e2-581d12272c13.JPG)

Regards

**Comment by gillesdubois** [comment]
Ok thanks you for the quick reply.
i'm on it i will notice you when a fix will be available.

Thanks you, have a nice day !

**Comment by gillesdubois** [comment]
Hello,

This useless warning has been fixed in 2.2
Thanks for contributing the ocs inventory project.

Regards,
Gilles Dubois.

**Comment by ameurou** [comment]
Hello,

I've update OCS to 2.2 version and i still got this warning raised.

Not a big issue, but this seems not being solved in 2.2.

regards
