### ISSUE TITLE
Parse error: syntax error, unexpected '['

### ISSUE THREAD

**Issue by zxtury** [OCSInventory-NG/OCSInventory-ocsreports#221]
Operating system : Windows 7 Pro 64bits
Php version : 5.3.8 under Xampp
Mysql / Mariadb / Percona version :  5.5.16
Apache version : 2.2.21
Ocsreports version : 2.3

like the title says
Parse error: syntax error, unexpected '[' in C:\xampp\htdocs\ocsreports\plugins\main_sections\ms_computer\ms_computer_views.php on line 41

line 41:         if ($protectedGet['cat'] == explode('=',$url)[1]) {

**Comment by gillesdubois** [comment]
Hi @zxtury ,

Your php version is not compatible with ocs 2.3 ( require 5.4, 5.5 + recommanded )
That why you got this error message, this php syntax is not compatible with your php version.

Regards,
Gilles Dubois.
