### ISSUE TITLE
activity.log only showing windows agents

### ISSUE THREAD

**Issue by phillip-white-sociomantic** [OCSInventory-NG/OCSInventory-ocsreports#222]
### General informations
Operating system : Ubuntu 14.04

### Server informations
Php version : 5.5.9
Mysql / Mariadb / Percona version : Mysql 5.7.17-11
Apache version : Apache/2.4.7

### OCS Inventory informations
Ocsreports version : 2.3

### Problem's description
Is there a reason why the Unix / Linux / OSX agent does not come up in `/var/log/ocsinventory-server/activity.log`

I can see only the Windows agents in the log file.

**Comment by gillesdubois** [comment]
Hi @phillip-white-sociomantic ,

You should use the apache access.log which is better and gives more informations than the activity.log.

Regards,
Gilles Dubois.

**Comment by phillip-white-sociomantic** [comment]
Hi @gillesdubois 

Thanks for the response. Is there a reason why `activity.log` only shows the Windows agents? Just wondering if we have an issue with our setup, or if it's been designed like that?

Thanks

**Comment by gillesdubois** [comment]
Hi @phillip-white-sociomantic, 

Sorry, i don't have a lot of information on this functionnality.
The only thingi know is that the activity file is quite old.
That could be why all informations aren't displayed in :)

Regards,
Gilles Dubois.
