### ISSUE TITLE
Missing rows in duplicates details in some cases

### ISSUE THREAD

**Issue by SylvieCozic** [OCSInventory-NG/OCSInventory-ocsreports#224]
Hello,

We recently discovered an issue with the display of details on the "duplicates" page.
This appears when one of the device has no network information.
In this case the device is not listed in the details table.

For example, let's say you want to display duplicates "by hostname".
The header tells "hostname only : 2".
but in the detail only one row is displayed because, for some reasons, one of the 2 devices has no network data inventoried.

We currently use OCS server 2.1.2 on Windows but checking for the current files on github, I see that the bug is still here.

I corrected this bug by modifying the way tables are "joined" in file "plugins\main_sections\ms_doubles\ms_doubles.php" :
```
303 -	$sql['SQL'] .= " from hardware h left join accountinfo a on h.id=a.hardware_id ";
304 -	$sql['SQL'] .= ",bios b, ";
305 -
306 -	$sql['SQL'] .= " networks n where  h.id=n.hardware_id ";
307 -	$sql['SQL'] .= " and h.id=b.hardware_id and  h.id in ";
```
```
303 +	$sql['SQL'] .= " from hardware h ";
304 +	$sql['SQL'] .= " left join accountinfo a on h.id=a.hardware_id ";
305 +	$sql['SQL'] .= " left join bios b on h.id=b.hardware_id ";
306 +	$sql['SQL'] .= " left join networks n on h.id=n.hardware_id ";
307 +	$sql['SQL'] .= "  where h.id in ";
```

Now all duplicates devices are displayed (with some blank data in somes cases...).

Keep it up ! :yum:

_Sylvie_

**Comment by gillesdubois** [comment]
Hi,

Thanks for your report.
I'm gonna investigate the issue and applicate your fix is necessary :)

Regards,
Gilles Dubois.
