### ISSUE TITLE
Inventory - All Softwares are blank

### ISSUE THREAD

**Issue by urys** [OCSInventory-NG/OCSInventory-ocsreports#225]
### General informations
Operating system : All

### Server informations
Php version : 7.1.2
Mysql / Mariadb / Percona version : 
Apache version : 2.4.5

### OCS Inventory informations
Ocsreports version : 2.3.0

### Problem's description
Menu Inventory - All Softwares - output is blank, no software is not visible

apache error.log
[Tue Feb 28 20:13:42.156837 2017] [php7:error] [pid 26467] [client 192.168.155.55:56293] PHP Fatal error:  Uncaught Error: [] operator not supported for strings in /usr/share/ocsinventory-reports/ocsreports/plugins/main_sections/ms_all_soft/ms_all_soft.php:155\nStack trace:\n#0 /usr/share/ocsinventory-reports/ocsreports/require/header.php(437): require()\n#1 /usr/share/ocsinventory-reports/ocsreports/index.php(44): require('/usr/share/ocsi...')\n#2 {main}\n  thrown in /usr/share/ocsinventory-reports/ocsreports/plugins/main_sections/ms_all_soft/ms_all_soft.php on line 155, referer: http://192.168.150.75/ocsreports/index.php?function=visu_all_soft

so the problem is in ms_all_soft.php on line 149
$list_soft = "";
must be
$list_soft = array();

thx

**Comment by paullepetit** [comment]
Hi,

Thanks for your report.
We are gonna investigate the issue.

Regards,
Paul LEPETIT

**Comment by paullepetit** [comment]
Hi,

After some test, i don't see any problem.
It might be fixed on the trunk take a look at this issue : #190 

Test effected on:
PHP Version : 7.0.15-0ubuntu0.16.04.2 (apache2handler)
Web Server : Apache/2.4.18 (Ubuntu)
Database Server :MySQL Community Server (GPL) version 5.7.17
Version OCSReports: 2.3

Regards,
Paul LEPETIT

**Comment by urys** [comment]
Sorry for this, but actual source ms_all_soft.php from github have still this error, imho. But now it's on line number 164.

$list_soft = "";
but $list_soft is array and than must be initialized as array, so corret typo is:
$list_soft=array();

because
$list_soft=""; //initialize variable
$list_soft="foo"; //OK
$list_soft[]="foo"; //ERROR

but

$list_soft=array(); //initialize variable as array
$list_soft[]="foo"; //OK


thx


Ivan

**Comment by MyTheValentinus** [comment]
Hello,
Thanks for your report is fixed in trunk.
Regards
