### ISSUE TITLE
Recherche de logiciels avec aucun résultat

### ISSUE THREAD

**Issue by mylanndupuy72** [OCSInventory-NG/OCSInventory-ocsreports#226]
Bonjour,

Je sais pas si c'est moi qui l'utilise mal ou si c'est un beug mais quant je suis en langue "Français" et que je regarde tout les logiciels présents via "Inventaire => Tout les logiciels", il me trouve aucun logiciels mais quand je le remet en "Anglais", cela fonctionne... Avez-vous une idée ?

**Version de PHP : 5.6.30-0+deb8u1 (apache2handler)
Serveur Web : Apache/2.4.10 (Debian)
Serveur SQL : (Debian) version 5.5.54-0+deb8u1
Version OCSReports: 2.3**

Cordialement.

**Comment by paullepetit** [comment]
Bonjour,

Ce problème nous a été remonté:
 https://github.com/OCSInventory-NG/OCSInventory-ocsreports/issues/190

Il a été fix dans le trunk.

Cordialement,
Paul LEPETIT

**Comment by mylanndupuy72** [comment]
Je n'avais pas vu, 

Merci et excusez-moi du double-post
