### ISSUE TITLE
Need to update the var.php with the database version

### ISSUE THREAD

**Issue by SquirrelAssassin** [OCSInventory-NG/OCSInventory-ocsreports#227]
Pulled source from Server and OCSreports, got a database version error needed to modify the below:

File: var.php

Change:
// GUI Options
//====================================================================================
/**
 * OCS' MySQL database version
 */
define('GUI_VER', '7011');
/**
 * GUI Version

**Comment by gillesdubois** [comment]
Hi @SquirrelAssassin ,

Look like i made a lil mistake :p 
Thanks for your report.

Regards,
Gilles Dubois.

**Comment by cobayashipl** [comment]
Thanx working ;)
