### ISSUE TITLE
Nothing is at the view of all software report 

### ISSUE THREAD

**Issue by sabochen** [OCSInventory-NG/OCSInventory-ocsreports#228]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system : CentOS Linux release 7.3.1611 (Core)

### Server informations
Php version : PHP 7.1.2 (cli) (built: Feb 15 2017 08:36:40)
Mysql / Mariadb / Percona version :  5.5.52-MariaDB 
Apache version : Apache/2.4.6 (CentOS)

### OCS Inventory informations
Ocsreports version : 2.3

PHP Version :
Web Server :
Database Server :
Version OCSReports:
7.1.2 (apache2handler)
Apache/2.4.6 (CentOS) OpenSSL/1.0.1e-fips mod_fcgid/2.3.9 mod_wsgi/3.4 Python/2.7.5 PHP/7.1.2 mod_perl/2.0.10 Perl/v5.16.3
MariaDB Server version 5.5.52-MariaDB

### Problem's description
*Describe your problem here*
When I view all software under inventory tab, I got nothing and found the error log from apache.
Please help me to find out the problem. Thank you.

 [php7:error] [pid 11697] [client 192.168.22.1:54980] PHP Fatal error:  Uncaught Error: [] operator not supported for strings in /usr/share/ocsinventory-reports/ocsreports/plugins/main_sections/ms_all_soft/ms_all_soft.php:170\nStack trace:\n#0 /usr/share/ocsinventory-reports/ocsreports/require/header.php(437): require()\n#1 /usr/share/ocsinventory-reports/ocsreports/index.php(44): require('/usr/share/ocsi...')\n#2 {main}\n  thrown in /usr/share/ocsinventory-reports/ocsreports/plugins/main_sections/ms_all_soft/ms_all_soft.php on line 170, referer: http://192.168.6.9/ocsreports/?function=visu_all_soft

**Comment by MyTheValentinus** [comment]
Hello,
Thanks for you report
Is fixed in trunk
Regards
