### ISSUE TITLE
bogue d'affichage dans function=computer cat=config

### ISSUE THREAD

**Issue by StCyr** [OCSInventory-NG/OCSInventory-ocsreports#23]
Lorsqu'on affiche la liste des paquets déployés sur une machine, si des paquets de cette liste ont été supprimés sur le serveur entretemps, le serveur affiche "<b><font color=red>Unknown (deleted package)</font></b>" au lieu de rendre proprement l'HTML

![untitled](https://cloud.githubusercontent.com/assets/8179031/10166274/8af83a36-66c3-11e5-9703-131940c01130.png)

**Comment by gillesdubois** [comment]
Bonjour,

J'avais déjà constaté ce bug ... je me met dessus dès que je suis dispo, j'enverrai une notif quand le problème sera résolu.

Merci de contribuer a ocs inventory
Cordialement, Gilles Dubois
