### ISSUE TITLE
Server information page with some data in wrong fields

### ISSUE THREAD

**Issue by saep-es** [OCSInventory-NG/OCSInventory-ocsreports#230]
### General informations
CentOS Linux 7 (3.10.0-514.2.2.el7.x86_64)

### Server informations
5.4.16 (fpm-fcgi)
Apache/2.4.6 (CentOS) PHP/5.4.16 mod_perl/2.0.10 Perl/v5.16.3
MariaDB Server version 5.5.52-MariaDB 2.3

### OCS Inventory informations
Ocsreports version : 2.3.0.0

### Problem's description
On the page with server information, some data is in wrong fields. Example 1: SQL server = Perl/v5.16.3. Example 2: Version OCSReports = MariaDB Server version 5.5.52-MariaDB 2.3

**Comment by gillesdubois** [comment]
Hi @saep-es,

I don't have this issue ( might be fixed in the trunk ) on my server do you have any log in your apache when going on the page ?

Regards,
Gilles Dubois.

**Comment by gillesdubois** [comment]
HI @saep-es ,

It was a display problem :)

Should be with this commit : 
https://github.com/OCSInventory-NG/OCSInventory-ocsreports/commit/4be193d778cfa097e8a6bd581275515e54d5bfbd

Regards,
Gilles Dubois.
