### ISSUE TITLE
LDAP support broken

### ISSUE THREAD

**Issue by kbabioch** [OCSInventory-NG/OCSInventory-ocsreports#231]
The LDAP support seems to be broken. I've configured it through the configuration page of the web interface. The authentication itself is working correctly (i.e. when providing invalid data, I'm not getting logged in). However, when I'm successfully logged in, I get an error message:

    NO RIGHTS LEVEL DEFINED TO YOUR PROFILE

There are also some PHP errors:

    [Thu Mar 09 15:40:03.140007 2017] [:error] [pid 8162] [client 192.168.253.254:40994] PHP Warning:  file_get_contents(config/profiles/.xml): failed to open stream: No such file or directory in /usr/share/ocsinventory-reports/ocsreports/require/header.php on line 386, referer: https://192.168.25.8/ocsreports/index.php
    [Thu Mar 09 15:40:03.140076 2017] [:error] [pid 8162] [client 192.168.253.254:40994] PHP Warning:  Invalid argument supplied for foreach() in /usr/share/ocsinventory-reports/ocsreports/require/config/XMLProfileSerializer.php on line 81, referer: https://192.168.25.8/ocsreports/index.php
    [Thu Mar 09 15:40:03.140087 2017] [:error] [pid 8162] [client 192.168.253.254:40994] PHP Warning:  Invalid argument supplied for foreach() in /usr/share/ocsinventory-reports/ocsreports/require/config/XMLProfileSerializer.php on line 87, referer: https://192.168.25.8/ocsreports/index.php
    [Thu Mar 09 15:40:03.140095 2017] [:error] [pid 8162] [client 192.168.253.254:40994] PHP Warning:  Invalid argument supplied for foreach() in /usr/share/ocsinventory-reports/ocsreports/require/config/XMLProfileSerializer.php on line 93, referer: https://192.168.25.8/ocsreports/index.php
    [Thu Mar 09 15:40:03.140102 2017] [:error] [pid 8162] [client 192.168.253.254:40994] PHP Warning:  Invalid argument supplied for foreach() in /usr/share/ocsinventory-reports/ocsreports/require/config/XMLProfileSerializer.php on line 97, referer: https://192.168.25.8/ocsreports/index.php
    [Thu Mar 09 15:40:03.141603 2017] [:error] [pid 8162] [client 192.168.253.254:40994] PHP Warning:  array_search() expects parameter 2 to be array, null given in /usr/share/ocsinventory-reports/ocsreports/require/html_header.php on line 199, referer: https://192.168.25.8/ocsreports/index.php

In `header.php` it seems that $_SESSION['OCS']['lvluser'] is not set:

    if (!isset($_SESSION['OCS']['profile'])) {
        $profile_config = 'config/profiles/' . $_SESSION['OCS']["lvluser"] . '.xml';
        $profile_serializer = new XMLProfileSerializer();
        $profile = $profile_serializer->unserialize($_SESSION['OCS']["lvluser"], file_get_contents($profile_config));
        $_SESSION['OCS']['profile'] = $profile;
    } else {
        $profile = $_SESSION['OCS']['profile'];
    }

### General informations
Operating system : Linux

### Server informations
Php version : 5.6.30
Mysql / Mariadb / Percona version : 5.5.54
Apache version : 2.4.10

### OCS Inventory informations
Ocsreports version : The one distributed with OCS 2.3.

**Comment by gillesdubois** [comment]
Hi @kbabioch ,

My ldap config is working fine did you set a default log profile on the web interface ?

Regards,
Gilles Dubois.

**Comment by kbabioch** [comment]
Hi,

Thank you for your reply @gillesdubois.

I got it working by now. I basically forgot to change the `identity.php` file in accordance to the `AUTH.php`. However I'm considering the LDAP support of OCS badly broken for a couple of reasons:

- Restrictions (USER_FIELD1 & USER_FIELD2) don't seem to be working properly. This leads to everyone in the LDAP is accepted. This has also been reported by others (see [here][1]).
- Users are imported into the local user DB. So you cannot use it in combination, since any user removed from the LDAP will still be able to login, since he is then considered to be a local user. Without local user support you cannot login with some kind of root account once the LDAP service is not available.
- There are a couple of security flaws in the code itself
- "Minor": The LDAP password in the LDAP configuration panel is visible (rather than only showing asterisks for privacy reasons, e.g. declaring the text field as password field).

Patches have been proposed a while back (see [here][1] but have not been incorporated).

I've written my own code for the time being (which is kind of specific to my domain), but all in all I'm stunned by the fact that something basic like LDAP is in such a bad shape. Is it planned to revisit this whole chapter?

[1]: http://www.miloszengel.com/ocs-ng-2-2rc1-server-complete-install-and-configuration-with-ldap/

**Comment by gillesdubois** [comment]
Hi @kbabioch ,

It's been a long time that LDAP implementation haven't been updated.
That might be why it is in such a bad shape.

I didn't know about this alternative implementation, i will take a look at it and merge it / improve it if everything look good.
If you are willing to help us and speed up the process you can help us by making a pull request. https://help.github.com/articles/about-pull-requests/

Regards,
Gilles Dubois.

**Comment by ncanqn** [comment]
Hi All,
I'm using 2.5 and getting the same error as of now. 
Have anyone know how to get arround this and make it works?
Regards,
Ken

**Comment by kbabioch** [comment]
@ncanqn Do you have the memberof attribute at all? Have you enabled the corresponding overlay? What LDAP server are you using?
