### ISSUE TITLE
Export data computer empty

### ISSUE THREAD

**Issue by llljackll** [OCSInventory-NG/OCSInventory-ocsreports#232]
### General informations
Operating system : Red Hat Enterprise Linux Server release 7.2 (Maipo)

### Server informations
Php version : 5.4.16
Mysql / Mariadb / Percona version : MariaDB Server version 5.5.44-MariaDB 2.3.1
Apache version : Apache/2.4.6 (Red Hat Enterprise Linux) OpenSSL/1.0.1e-fips

### OCS Inventory informations
Ocsreports version : OCSNG_UNIX_SERVER-2.3.1

### Problem's description
Hi,

I have a problem when I download the csv file, when I select the download button from the menu "Inventory -> Software search".

The information show correctly here, but when I download the csv the content of the field "computer" is missing. I have done some test and this problem only appear in this secction.

This failt appear when I update the Ocsreports version and when I do a fresh installation.

Thank so much.

Regards,

Víctor.

**Comment by gillesdubois** [comment]
Hi @llljackll ,

Thanks for your report.
We will investigate the issue and come back to you asap.

Regards,
Gilles Dubois.

**Comment by fedsib** [comment]
@gillesdubois Magliette subito, io ne prenoto 3
