### ISSUE TITLE
Possible security issue with location of dbconfig.inc.php

### ISSUE THREAD

**Issue by brianda78** [OCSInventory-NG/OCSInventory-ocsreports#233]
### General informations
Operating system : Red Hat Linux 7.3

### Server informations
Php version : 5.4.16
Mysql / Mariadb / Percona version : 15.1
Apache version : 2.4.6

### OCS Inventory informations
Ocsreports version : 2.3.1

### Problem's description
Let me first start of by saying I am new to Linux and Web Management, so if I am off the mark on this please let me know.  From what I have read it is not good security practice to include the database credentials in a PHP file that is contained within the web root directory.  If PHP fails to render the page correctly there is a possibility that this file could be displayed to a visitor exposing the database credentials.  The following PHP file is in the web root and defines the database connection and credentials, /usr/share/ocsinventory-reports/ocsreports/dbconfig.inc.php.  I have tested out a solution that I think remedies the security concern.

Make a directory /etc/ocsinventory-server/secure, give Apache ownership of it, and put dbconfig.inc.php here.  Then in /usr/share/ocsinventory-reports/ocsreports/dbconfig.inc.php just use an include that points to the new location.

<?php
include '/etc/ocsinventory-server/secure/dbconfig.inc.php';
?>

I also changed the permissions on /etc/ocsinventory-server/secure/dbconfig.inc.php to 664.  Not sure if this is necessary or not, but I wanted to match the permissions on the original dbconfig.inc.php.

**Comment by kapouik** [comment]
just look on var.php : there is at line 46 : 
define('CONF_MYSQL', CONF_MYSQL_DIR . '/dbconfig.inc.php');

It's not use by default on the install.php and it's not dramatic because only php can really read it.
We change the location on RPM file.

**Comment by brianda78** [comment]
Ahh...  Thank you.  I moved dbconfig.inc.php to /etc/ocsinventory-server/secure and edited the CONF_MYSQL value in var.php as follows and it worked.
define('CONF_MYSQL', '/etc/ocsinventory-server/secure/dbconfig.inc.php');
