### ISSUE TITLE
Probleme Affichage nombre résultats par défaut

### ISSUE THREAD

**Issue by cp61** [OCSInventory-NG/OCSInventory-ocsreports#234]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system : Debian 7

### Server informations
Php version : 5.4.45
Mysql / Mariadb / Percona version : 5.5.54
Apache version : 2.2.22

### OCS Inventory informations
Ocsreports version : 2.3.1

### Problem's description
Suite à l'installation du dernier package dispo sur Github, je n'arrive plus à modifier mon nombre de résultat à afficher lorsque je demande toutes les machines.

J'ai pourtant modifier le fichier jquery.dataTables.js dans /usr/share/ocsinventory-reports/ocsreports/libraries/datatable/media/js en indiquant une valeur à 1000 pour "iDisplayLength"

Le menu de choix reste toujours par défaut avec les valeurs 10,25,50,100

**Comment by MyTheValentinus** [comment]
Bonjour,
Il n'est pas nécessaire de modifier la librairie, un simple clique en haut à gauche sur le select du datatable suffit pour modifier la valeur par défaut.
Merci

**Comment by cp61** [comment]
Bonjour Valentin

Dans le select je n'ai le choix que de 10 25 50 100 or nous voulons afficher sur une meme page tous nos PC qui sont au nombre de 350.
