### ISSUE TITLE
Administrative Data CheckBox

### ISSUE THREAD

**Issue by scifire91** [OCSInventory-NG/OCSInventory-ocsreports#235]
### General informations
Operating system : Ubuntu 16.04

### Server informations
Php version : 7.0.15
Mysql  : (Ubuntu) version 5.7.17-0ubuntu0.16.04.1
Apache version : Apache/2.4.18 (Ubuntu)

### OCS Inventory informations
Ocsreports version : 2.3.1

### Problem's description
The Administrative data Checkbox won´t work. If i use it no Checkbox will shown.
![ocs inventory_checkbox](https://cloud.githubusercontent.com/assets/17220258/24147987/17dcf0f0-0e3d-11e7-8f79-3617fe18d477.jpg)

**Comment by MyTheValentinus** [comment]
Hello,
Thanks for your report this will be fixed in next version
