### ISSUE TITLE
Probleme Tag pour nouveau PC 

### ISSUE THREAD

**Issue by cp61** [OCSInventory-NG/OCSInventory-ocsreports#236]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system : Debian 7 

### Server informations
Php version : 5.4.45
Mysql / Mariadb / Percona version : 5.5.54
Apache version : 2.2.22

### OCS Inventory informations
Ocsreports version : 2.3.1

### Problem's description
Lorqu'un nouveau PC est detecté, OCS lui affecte un TAG automatiquement.
Dans les anciennes versions le TAG NA était affecté. Avec cette version ,il m'affecte un TAG que j'ai créé et qui ne sert en rien au nouveau PC or je ne vois pas où il est possible de lui dire de nous mettre le TAG NA comme par avant

**Comment by MyTheValentinus** [comment]
Bonjour,
En effet ceci à été modifié dans les dernières versions d'OCS et n'est plus possible. Si aucun tag n'est renseigné alors OCS donne un tag se rapprochant du nom de la machine.
Merci
