### ISSUE TITLE
InnoDB Cluster: Problems changing from MyISAM to InnoDB

### ISSUE THREAD

**Issue by linuxmail** [OCSInventory-NG/OCSInventory-ocsreports#24]
hi,
for high availability I use a Percona InnoDB MySQL Cluster. Percona supports only InnoDB as replication storage engine, but ocsbase.sql has a lot of MyISAM tables. Usually the most applications works without any problem, if I change all entries to "engine=InnoDB", but not ocs-reports:

If I try to push the SQL after the changes into the cluster, I get:

ERROR 1061 (42000) at line 530: Duplicate key name 'IVALUE'

That is the line:
ALTER TABLE devices ADD INDEX IVALUE (IVALUE);
[...]

If I use the ocsbase_new.sql,:

ERROR 1071 (42000) at line 485: Specified key was too long; max key length is 1000 bytes

CREATE TABLE `engine_mutex` (
  `NAME` varchar(255) NOT NULL DEFAULT '',
  `PID` int(11) DEFAULT NULL,
  `TAG` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`NAME`,`TAG`)
) ENGINE=MEMORY DEFAULT CHARSET=UTF8;

Maybe, I have the same problem with other tables too.

It would be very nice, If ocs-inventory uses InnoDB only, to get it on a MySQL InnoDB cluster working. :-)

Update: I used now ocsreports/files/ocsbase_new.sql, changed all MyISAM to InnoDB and the table "engine_mutex" to something lower than 255 (trying now 160).

**Comment by kapouik** [comment]
I some case, MyIsam have many advantage. If we use MyIsam and InnoDB, it's not for fun but for performance issue. 

There is native option to use replication in mysql if you want to have a cluster.
