### ISSUE TITLE
Page blanche lors de l'export de la liste logiciels (aucun téléchargement ne se lance)

### ISSUE THREAD

**Issue by optimumtracker** [OCSInventory-NG/OCSInventory-ocsreports#240]
### Problem's description

Bonjour,

J'ai un problème lors de l'export de la listes de logiciels complète ou installés sur une seule machine.

J'avais précédemment le problème de "File is missing" , j'ai donc appliqué le correctif 199. Je n'ai plus le message d'erreur, seulement une page web blanche qui apparaît mais le téléchargement de l'export ne se lance pas. 

Comment puis-je résoudre cela ?

Cordialement,

Rémy

### General informations
Operating system : Debian 8.7.1

### Server informations
Php version : 4.2.12
Mysql / Mariadb / Percona version : MySQL 5.5.54
Apache version : 2.4.10

### OCS Inventory informations
Ocsreports version : 2.3

**Comment by gillesdubois** [comment]
Bonjour,

Pouvez-vous mettre a jour votre serveur en 2.3.1 ? le CSV devrait fonctionner normalement sur la dernière version.

Cordialement,
Gilles Dubois.

**Comment by optimumtracker** [comment]
Bonjour,

J'ai fait la mise à jour en version 2.3.1. Effectivement, tout refonctionne. Merci beaucoup !

Cordialement,

Rémy
