### ISSUE TITLE
Deleting an activated package from a computer deletes all pending deployment informations

### ISSUE THREAD

**Issue by StCyr** [OCSInventory-NG/OCSInventory-ocsreports#241]
Bonjour,

J'ai remarqué cela plusieurs fois, et je pense que c'est en fait systématique: Lorsque vous supprimez un paquet activé sur un PC, toutes les informations relatives au déploiement de ce paquet sont supprimées. En fait, cette fonction semble se comporter exactement comme la fonction "validate all" de la page "pie chart" de déploiement d'un paquet.

C'est quand même assez ennuyant car en perdant les stats de déploiement, le paquet est également supprimé de tous les PC sur lequel il était en état "WAITING NOTIFICATION". Et, je dois donc après ré-assigner ce paquet à tous ces PC.

Cyrille

![untitled](https://cloud.githubusercontent.com/assets/8179031/24851341/9654b990-1dd3-11e7-8631-5f9a252c0df3.png)

![untitled](https://cloud.githubusercontent.com/assets/8179031/24851405/c62148c8-1dd3-11e7-9ad5-e0a4842388d2.png)

### General informations
Operating system : Ubuntu 16.04.2

### Server informations
Php version : 1:7.0+35ubuntu6
Mysql version :  5.7.17-0ubuntu0.16.04.2
Apache version : 2.4.18-2ubuntu3.1

### OCS Inventory informations
Ocsreports version : 2.3.1

**Comment by gillesdubois** [comment]
Bonjour @StCyr ,

Merci pour ton retour, une personne de notre équipe va tester ce que tu nous a reporté. Dans le cas ou le bug est avéré, nous le fixerons sous peu.

Cordialement,
Gilles Dubois.

**Comment by doudz** [comment]
Je confirme que j'ai exactement le même problème et c'est très contraignant, on ne peut pas supprimer un paquet d'un seul ordinateur sans tout supprimer les déploiements en cours sur les autres pc.
Cela fait des mois que ce bug existe, comment peut-on le contourner ?
Je vois qu'il est marqué pour la version 2.4 mais ne peut-on pas avoir une mise à jour 2.3.2 plus rapidement ?
