### ISSUE TITLE
Issue in the "software search" functionality

### ISSUE THREAD

**Issue by StCyr** [OCSInventory-NG/OCSInventory-ocsreports#244]
### General informations
Operating system :  Ubuntu 16.04.2

### Server informations
Php version :  7.0.15-0ubun
Mysql version :  5.7.17-0ubun
Apache version : 2.4.18-2ubun 

### OCS Inventory informations
Ocsreports version : 2.3.1

### Problem's description

In the "software search" functionality (function=search_soft), computers are not listed twice when they have several softwares installed matching the query. This aggregation is not necessary and hides results.

Example: 

Look for "*Flash*", most computers running "Flash Player" will have the "Flash Player ActiveX" and "Flash Player NPAPI" program installed. Though, the "software search" functionality will returns only 1 line per computer

The following screenshot shows a computer named "PC-ALEXANDRA" having both "Flash Player 25 ActiveX" and ""Flash Player 25 NPAPI" installed. Though, it is only listed once in the list returned by the "software search" functionality

![untitled](https://cloud.githubusercontent.com/assets/8179031/25188946/fa7fd728-2527-11e7-92d1-7619865f12f2.png)

**Comment by MyTheValentinus** [comment]
Hello @StCyr 
I need to test this bug report, thanks.
have nice day

**Comment by StCyr** [comment]
Hi,
Do you expect something from me?
Cyrille

**Comment by ggzengel** [comment]
1.
Think a little bit bigger.
I have multiple domains with same computer names.
If I have 3 "server1" with SQL Server installed I see it only once.
Same thing with searching for duplicate hosts. I would like to have host name+domain name

2.
If I sort column Software:name the results are gone.
