### ISSUE TITLE
Please add "Show/Hide" column functionality to the "software search" functionality

### ISSUE THREAD

**Issue by StCyr** [OCSInventory-NG/OCSInventory-ocsreports#245]
In the "software search" functionality, there's no way to customize columns. Though, I've a need were the "Last inventory" and "TAG" columns would be usefull.

Is it possible to plan adding a column customization feature in a future OCS release?

**Comment by gillesdubois** [comment]
Hi @StCyr ,

That an interesting idea, we will discuss about it and will decide if we can add it to the new release :)
Thanks for you contribution.

Reagrds,
Gilles Dubois.

**Comment by yafp** [comment]
Datatables already supports customizeable columns via 'Buttons' - formerly 'colviz'

* https://datatables.net/extensions/buttons/
* https://datatables.net/extensions/colvis/
