### ISSUE TITLE
Impossible de voir les packages

### ISSUE THREAD

**Issue by copam3** [OCSInventory-NG/OCSInventory-ocsreports#246]
### General informations
Operating system : CentOS 7.3 

### Server informations
Php version : 5.4.16
Mysql / Mariadb / Percona version : 5.7.18 / disable / ?
Apache version : 2.4.6

### OCS Inventory informations
Ocsreports version : 2.3.1 from Change file

### Problem's description
*Describe your problem here*

Bonjour,

Je ne vois pas les packages en cliquant sur Télédéploiement > activation de paquets
J'utilise un accès https.

Processus d'installation : 
OCG 2.2.1 sur nouveau serveur puis montée de version de la bdd issue de la version 2.0.4 puis installation OCS 2.3.1

En revanche j'arrive à activer le package manuellement puis a attribuer le package à un ordinateur en passant par la page de recherche de machine.

Compte utilisé : admin donc avec profil sadmin

En mode debug je ne vois pas la requête SQL qui permet normalement l'affichage de package activés et à activer.

**Comment by copam3** [comment]
Bonjour,

J'ai trouvé l'origine du problème en installant directement la 3.2.1 sur un nouveau serveur et sans reprendre une base de données existantes.

Le problème vient de la table "download_available".
- Le champs COMMENT est resté de type mediumtext alors qu'il est de type text sur une nouvelle bdd mais surtout
- Il manque le champs DELETED de type int(1) !

Après correction de la table, on voit bien les paquets disponibles sur OcsReports

Ce problème est donc à transmettre dans la partie OCSInventory Server afin de mettre à jour les scripts SQL de migration.

**Comment by MyTheValentinus** [comment]
Bonjour,
Merci de votre contribution nous recommandons cependant de monter en 2.2 avant la 2.3.1 pour éviter ce genre de soucis.
Merci
