### ISSUE TITLE
Administrative Data Date

### ISSUE THREAD

**Issue by JoergBehm** [OCSInventory-NG/OCSInventory-ocsreports#247]
### General informations
Operating system : Ubuntu 16.04

### Server informations
Php version : 7.0.15
Mysql: (Ubuntu) version 5.7.17-0ubuntu0.16.04.1
Apache version : Apache/2.4.18 (Ubuntu)

### OCS Inventory informations
Ocsreports version : 2.3.1

### Problem's description
The Administrative Data Date won't save. If i reenter the tab no date will shown
![2017-04-24_15h05_06](https://cloud.githubusercontent.com/assets/27763465/25338468/a05c589e-28ff-11e7-9d31-9ada3b5c56da.jpg)

**Comment by MyTheValentinus** [comment]
Hello @JoergBehm,
Thanks for your report. Can you specify me what language you use in web interface ?
This bug is due to the language, if you switch in english or french no problem i think ?
Thanks

**Comment by JoergBehm** [comment]
Hi,

you are right.  Problem is in german. If i switch to english i have no problem

**Comment by sokatra** [comment]
for me - the language change makes no difference - it does not work at all in 2.3.1

**Comment by dizaru** [comment]
I had the same problem in Russian in 2.6. I fixed it. In file **/var/lib/ocsinventory-reports/plugins/language/ru_RU.txt**, line 1270 changed to **dd/mm/yyyy hh:ii**  Also added lines in the function datePick in file **/usr/share/ocsinventory-reports/ocsreports/require/function_table_html.php**

```
function datePick($input, $checkOnClick = false) {
    global $l;
    $dateForm = $l->g(1270);
    if ($checkOnClick) {
        $cOn = ",'$checkOnClick'";
    }
    $lang = $_SESSION['OCS']['LANGUAGE'];                       //add line
    $ret = "<span class=\"glyphicon glyphicon-calendar\"></span>";
    $ret .= "<script type=\"text/javascript\">
              $(\".form_datetime\").datetimepicker({
                  format: \"".$dateForm."\",
                  autoclose: true,
                  todayBtn: true,
                  language:\"".$lang."\",                       //add line
                  pickerPosition: \"bottom-left\"
              });
            </script>";
    return $ret;
}
```
