### ISSUE TITLE
Security feature - access rights based on TAGS

### ISSUE THREAD

**Issue by Abraka** [OCSInventory-NG/OCSInventory-ocsreports#248]
Hello,
Im searching for solution in OCS, specifically how to restrict access for specific users to specific TAG-s.
Scenario: One OCS installation for 10 locations(every location have their own IT staff). All locations get audited their computers with specific tag for their location. How do I restrict access to audited computers in OCS web interface, so that IT staff from one specific location would see only computers from their own location? I didnt found this in latest 2.3.1. Any suggestion?

**Comment by Abraka** [comment]
cmon, nobody?

**Comment by gillesdubois** [comment]
Hi @Abraka,

In order to assign a specific tag to a user you just have to go in the user menu and  then click on the edit button in the tags column.
It will open a new page where you will be able to assign take to users.

Regards,
Gilles Dubois.

**Comment by Abraka** [comment]
thx. I will try that.
