### ISSUE TITLE
OCS inventory NG 2.3 cannot create/edit user profile

### ISSUE THREAD

**Issue by arthur-thebear** [OCSInventory-NG/OCSInventory-ocsreports#249]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system : CentOS 6.8

### Server informations
Php version : PHP 5.6.30
Mysql / Mariadb / Percona version : 5.5.54
Apache version : Apache/2.2.15

### OCS Inventory informations
Ocsreports version : 2.3

### Problem's description
Hi,

trying to add user profile got the error:

"An error occurred while submitting the form. Please check your internet connection."

I have created profile file manually in /usr/share/ocsinventory-reports/ocsreports/config/profiles/user.xml ,
gave it the apache:apache ownership, but still have the same error while trying to edit it using GUI.

Apache log have no errors related to this, the only error, appeared previously,  is: 

"ocsinventory-server: Can't load SOAP::Transport::HTTP* - Web service will be unavailable"

Any info on how this could be resolved is much appreciated.

**Comment by gillesdubois** [comment]
Hi @arthur-thebear,

Could you upgrade your server to 2.3.1 please ?

Regards,
Gilles Dubois.

**Comment by HassbergKliniken** [comment]
Hi gillesdubois,

under 2.3.1 we have no problems. Try it mintues ago.

Jörg
