### ISSUE TITLE
SNMP administrative data, selected value not work.

### ISSUE THREAD

**Issue by Kiko1985** [OCSInventory-NG/OCSInventory-ocsreports#252]
### OCS Inventory informations
Ocsreports version : 2.3

### Problem's description
When you enter into an snmp device page and it contains select list fields, those fields are not set with the appropiate value from the DB.
I've checked the code and it's missing the code where it should be made.

I am attaching the code that solves the problem.

Code i add in sd_admininfo.php
[sd_admininfo.zip](https://github.com/OCSInventory-NG/OCSInventory-ocsreports/files/1044969/sd_admininfo.zip)

:
`// If is a select get default data
        foreach($name_field as $key => $value){
            if($config['SELECT_DEFAULT'][$key] == 'YES'){
              $sql_selected_data = "SELECT ".$value." FROM `snmp_accountinfo` WHERE `SNMP_ID` = ".$protectedGet['id'];
              $result = mysql2_query_secure($sql_selected_data, $_SESSION['OCS']["readServer"]);
	        while ($admininfo_default_data = mysqli_fetch_array($result)) {
                      $config['SELECTED_VALUE'][$key] = $admininfo_default_data[$value];
                }
            }
        }`

**Comment by nohnaimer** [comment]
### General informations
Operating system : CentOS 7 x64

### Server installation method ( Only one choice )
- [ ] DEB Package
- [ ] RPM Package
- [x] Install SH
- [ ] Manual installation

### Server informations
Php version : 7.3.4
Mysql / Mariadb / Percona version : 5.7.25-28
Apache version : 2.4.6

### OCS Inventory informations
Ocsreports version : 2.5

### Problem's description
Does not work 
![Снимок экрана 2019-04-05 в 15 29 33](https://user-images.githubusercontent.com/8865830/55627782-afb4bc80-57b7-11e9-91c0-0e418e5f094a.png)
It took 2 days after changing the settings in the file
C:\ProgramData\OCS Inventory NG\Agent\snmplist.txt
10.128.50.66 6C:3B:E5:3A:24:87
10.128.50.68 6C:3B:E5:37:FE:28
10.128.50.69 40:A8:F0:66:7D:1F
10.128.50.70 2C:59:E5:D5:30:12
10.128.50.71 C4:34:6B:4E:13:E9
10.128.50.76 D8:24:BD:C8:C5:C3
10.128.50.67 C4:34:6B:4E:14:16
10.128.50.78 00:19:AA:37:B9:4F
this host is ipdiscover by the network 10.128.50.64/28, but networks 10.128.108.0/26,10.128.1.0/24 not Inventory by snmp

How to force the agent to inventory other networks by snmp?

**Comment by gillesdubois** [comment]
Hi,

SNMP has been reworked, next version won't have this problem anymore.

**Comment by nohnaimer** [comment]
> Hi,
> 
> SNMP has been reworked, next version won't have this problem anymore.

Hi,
Worked on version 2.6?
