### ISSUE TITLE
No device at Non-inventored

### ISSUE THREAD

**Issue by JoergBehm** [OCSInventory-NG/OCSInventory-ocsreports#253]
### General informations
Operating system : Ubuntu 16.04

### Server informations
Php version : 7.0.15
Mysql : (Ubuntu) version 5.7.17-0ubuntu0.16.04.1
Apache version : Apache/2.4.18 (Ubuntu)

### OCS Inventory informations
Ocsreports version : 2.3.1

### Problem's description

Under _Network(s) -> IpDiscover -> ---Show all subnets---_ i see one Non-inventoried item. If i now click on the item, the next screen has no device. See screenshots.

![2017-06-06_10h50_44](https://cloud.githubusercontent.com/assets/27763465/26821405/9677fe6e-4aa6-11e7-94d9-0311a133026c.jpg)
![2017-06-06_10h51_05](https://cloud.githubusercontent.com/assets/27763465/26821404/9670088a-4aa6-11e7-9620-957d8af26800.jpg)

**Comment by StCyr** [comment]
I was about to report the same issue :-)

And also rto eport the nice percentage values that we can see an example in your screenshot

**Comment by StCyr** [comment]
Hello @JoergBehm 

Do you have access to the DB?

If yes, could you confirm that the 1st following query does return 1 row while the second one returns no row:

```sql
SELECT DISTINCT mac AS c,
             'NON IDENTIFIE' AS TYPE,
             netid AS RSX
      FROM netmap n
      LEFT JOIN networks ns ON ns.macaddr=n.mac
      WHERE n.mac NOT IN
          (SELECT DISTINCT(macaddr)
           FROM network_devices)
        AND (ns.macaddr IS NULL
             OR ns.IPSUBNET <> n.netid)
        AND n.netid IN ('10.103.109.0');
```

```sql
SELECT SQL_CALC_FOUND_ROWS ip,
       mac,
       mask, date, name
FROM netmap n
LEFT JOIN networks ns ON ns.macaddr=n.mac
WHERE n.netid='10.103.109.0'
  AND (ns.macaddr IS NULL)
  AND mac NOT IN
    (SELECT DISTINCT(macaddr)
     FROM network_devices)
ORDER BY INET_ATON(ip) ASC
LIMIT 0,
      10;
```

Then, with the mac address found in the 1st query, could you run the following query and confirm that the mac address relates to an inventoried computer?

```sql
select * from netmap where MAC='<the_mac_address_you_found_in_query_1';
```

# Bottom line:

I believe this issue is due to the first query taking into account mac addresses related to inventoried computers.

**Comment by StCyr** [comment]
And, in my test here, changing query 1 above by the following will return the same number as the number of rows returned in query 2:

```sql
SELECT DISTINCT mac AS c,
             'NON IDENTIFIE' AS TYPE,
             netid AS RSX
      FROM netmap n
      LEFT JOIN networks ns ON ns.macaddr=n.mac
      WHERE n.mac NOT IN
          (SELECT DISTINCT(macaddr)
           FROM network_devices)
        AND (ns.macaddr IS NULL
             OR ns.IPSUBNET <> n.netid)
        AND n.netid IN ('10.103.109.0');
```

This might be enough information to fix the issue....

**Comment by JoergBehm** [comment]
Hi StCyr,

1. SQL-Result:
c                                 TYPE                        RSX 
60:A4:4C:AB:5F:33      NON IDENTIFIE       10.103.109.0

2. SQL-Result:
-

3. SQL-Result:
IP                          MAC                        MASK               NETID             DATE                           NAME 
10.103.109.206     60:A4:4C:AB:5F:33   255.255.255.0   10.103.109.0   2017-06-01 13:45:49  Befund-6

**Comment by StCyr** [comment]
Hi @JoergBehm 

Could you confirm that Befund-6 is an identified computer?

**Comment by StCyr** [comment]
https://github.com/OCSInventory-NG/OCSInventory-ocsreports/pull/255

**Comment by JoergBehm** [comment]
Hi @StCyr 

confirmed

![2017-06-08_11h15_53](https://user-images.githubusercontent.com/27763465/26921321-f74e81d6-4c3b-11e7-894b-ad78eeb0bd42.jpg)

**Comment by StCyr** [comment]
@JoergBehm you can try my patch in PR https://github.com/OCSInventory-NG/OCSInventory-ocsreports/pull/255

**Comment by JoergBehm** [comment]
@StCyr 
done and it works.
![2017-06-08_11h31_21](https://user-images.githubusercontent.com/27763465/26922046-3605d878-4c3e-11e7-80b4-180857fa0b55.jpg)

**Comment by StCyr** [comment]
not yet. First, I'll report an issue with the link behind the "ipdiscover" number :-)
