### ISSUE TITLE
duplicate IPDISCOVER in table devices

### ISSUE THREAD

**Issue by StCyr** [OCSInventory-NG/OCSInventory-ocsreports#254]
### Problem's description
J'ai l'impression que l'ipdiscover de mon subnet 10.4.0.0 ne fonctionne plus depuis le 8 mai.

En regardant dans la DB, je trouve:

```sql
mysql> select * from devices where NAME='IPDISCOVER' and TVALUE='10.4.0.0';
+-------------+------------+--------+----------+----------+
| HARDWARE_ID | NAME       | IVALUE | TVALUE   | COMMENTS |
+-------------+------------+--------+----------+----------+
|        4230 | IPDISCOVER |      1 | 10.4.0.0 |          |
|        4230 | IPDISCOVER |      1 | 10.4.0.0 |          |
+-------------+------------+--------+----------+----------+
2 rows in set (0.00 sec)
```

Est-ce-que cela est normal?

Est-ce-qu'il ne faudrait pas mettre une contrainte sur cette table pour éviter ce genre de doublon?

### General informations
Operating system : Ubuntu 16.04

### Server informations
Php version : 
Mysql / Mariadb / Percona version : 
Apache version : 

### OCS Inventory informations
Ocsreports version : 2.3.1

**Comment by StCyr** [comment]
J'ai effacé une des 2 lignes en double:

```sql
 delete * from devices here NAME='IPDISCOVER' and TVALUE='10.4.0.0' LIMIT 1;
```

et tout d'un coup voilà que ocsi me rapporte plein de nouveaux matériels non-identifiés dans mon sous-réseaux 10.4.0.0:

![image](https://user-images.githubusercontent.com/8179031/26931285-3716c16a-4c60-11e7-8e84-be0ba0752004.png)

Hier, j'avais 6 résultats et tous dataient du "2017-05-08 11:57:34"

**Comment by charleneauger** [comment]
Hi @StCyr ,

This bug has been fixed on recent version.

Best regards,
Charlene
