### ISSUE TITLE
Link to the list of elected ipdiscover agents for a subnet is not correct

### ISSUE THREAD

**Issue by StCyr** [OCSInventory-NG/OCSInventory-ocsreports#256]
When you click on the number of ipdiscover agents in a subnet in an ipdiscovery table, the page you are redirected to is not correct.

For example, you are redirected to https://ocsi.acme.org/ocsreports/index.php?function=visu_search&prov=ipdiscover1&value=10.4.0.0 which maps to the following screenshot:

![image](https://user-images.githubusercontent.com/8179031/26922407-56f036b8-4c3f-11e7-89dd-f306ebd8ad51.png)

under the hood, the list is generated with such a query:

```sql
select distinct HARDWARE_ID from devices where ( ( NAME = 'IPDISCOVER' AND IVALUE = '1' OR NAME = 'IPDISCOVER' AND IVALUE = '2')) AND HARDWARE_ID IN (4,8,11,13,15,17,18,21,22,32,44,45,52,160,210,461,589,775,1198,1245,1246,1255,1375,1376,1378,1379,1500,1597,1796,1962,2162,2195,2234,2304,2516,2595,2618,2626,2679,2681,2732,2920,2948,2958,2999,3179,3191,3311,3337,3338,3345,3390,3435,3465,3470,3496,3539,3561,3565,3576,3954,3974,3980,3987,4075,4175,4230,4267,4388,4595,4656,4702,4739,4874,4940,4942,5009,5075,5132,5133,5138,5155,5206,5216,5312,5354,5356,5411,5412,5414,5415,5438,5480,5515,5519,5522,5531,5551,5553,5615,5634,5681,5702,5710,5712,5714,5715,5735);
```

The above query returns 13 rows in my case (while it should only return 2 rows).

In fact, the 11 other rows relate to computers located both in the 10.4.0.0 subnet and in another subnet (virtual subnet for their virtual machines on their computer) and that have been elected as ipdiscover agent for that other subnet.

Look at the same query as above, but with the TVALUE field also displayed:

```sql
select distinct HARDWARE_ID,TVALUE from devices where ( ( NAME = 'IPDISCOVER' AND IVALUE = '1' OR NAME = 'IPDISCOVER' AND IVALUE = '2')) AND HARDWARE_ID IN (4,8,11,13,15,17,18,21,22,32,44,45,52,160,210,461,589,775,1198,1245,1246,1255,1375,1376,1378,1379,1500,1597,1796,1962,2162,2195,2234,2304,2516,2595,2618,2626,2679,2681,2732,2920,2948,2958,2999,3179,3191,3311,3337,3338,3345,3390,3435,3465,3470,3496,3539,3561,3565,3576,3954,3974,3980,3987,4075,4175,4230,4267,4388,4595,4656,4702,4739,4874,4940,4942,5009,5075,5132,5133,5138,5155,                                                                                                                                5);
+-------------+---------------+
| HARDWARE_ID | TVALUE        |
+-------------+---------------+
|         775 | 192.168.12.0  |
|        3345 | 192.168.56.0  |
|        5522 | 192.168.95.0  |
|        3496 | 192.168.28.0  |
|        3539 | 192.168.254.0 |
|        4388 | 10.6.0.0      |
|        5133 | 192.168.71.0  |
|        3980 | 192.168.56.0  |
|        5634 | 192.168.103.0 |
|        5216 | 192.168.181.0 |
|        5515 | 192.168.180.0 |
|        4175 | 10.4.0.0      |
|        3987 | 10.4.0.0      |
+-------------+---------------+
13 rows in set (0.00 sec)
```

I've located the part of the code responsible for this query to be located in ms_multi_search.php but it doesn't seem easy to be fixed.

# Possible solution

Since this ipdiscovery link uses OCSI' standard mutli_search criteria, I think that the correct solution consists of adding a new search criteria next to "Config:IpDisover" (which only allows to search for agents elected for IpDiscovery but doesn't allow search for agent elected for a particular subnet), and use that new criteria for this ipdiscover link.

OCSI would then use the "value" parameter in the URL (https://ocsi.acme.org/ocsreports/index.php?function=visu_search&prov=ipdiscover1&value=10.4.0.0) to filter the result of the above query based on the value of the TVALUE field. Example:

```sql
select distinct HARDWARE_ID from devices where ( ( NAME = 'IPDISCOVER' AND IVALUE = '1' OR NAME = 'IPDISCOVER' AND IVALUE = '2')) AND TVALUE = '10.4.0.0';)
```

**Comment by MyTheValentinus** [comment]
Hello,
Thanks for your report and solution ! We looking and come back here to post news !
Thanks

**Comment by charleneauger** [comment]
Hi @StCyr ,

Recently Ipdiscover feature has been reworked. Please download a nightly to fix the problem.

Best regards,
Charlene
