### ISSUE TITLE
Filtering displayed informations in lock mode

### ISSUE THREAD

**Issue by steph78630** [OCSInventory-NG/OCSInventory-ocsreports#257]
### General informations
Operating system : Debian GNU/Linux 8 (jessie)

### Server informations
Php version : 5.6.30
Mysql / Mariadb / Percona version : (Debian) version 5.5.54-0+deb8u1
Apache version : 2.4.10 (Debian)

### OCS Inventory informations
Ocsreports version : 2.3.1

### Problem's description

Hi, once the locked interface (lock) on a group of customers, the display does not always take into account the filtering and we find some information for ALL of the customers inventoried in the database, including :

  - Plugins > Office keys manager
  - Network(s) > IpDiscover and Snmp
  - Information > Statistics > Other (Top softs, Nb OS and agents)

> This is a problem when you want a precise view or allow restricted access to a user (to manage / supervise an entity / group of customers) and you do not want it (for example) consult the list of Microsoft Office keys for ALL clients inventoried by the OCS server.

Similarly, when this user accesses restricted access, he / she should not see the number of "Base machines" and "non-inventoried network interfaces" in ACTIVITY since he / she has a view on a limited perimeter (on the other hand , SOFTWARE, HARDWARE and OTHERS tab information is well aware of the limitation).

Regards, Stéphane

**Comment by steph78630** [comment]
Hi all, @gillesdubois 

do you have any news about this request ?

Kind regards, Stéphane

**Comment by gillesdubois** [comment]
Hi,

Lock has been rework with 2.6 and is no way better than it was.
However, the plugins may need some configuration / developpement to work using lock

Regards,
Gilles Dubois.
