### ISSUE TITLE
Affichage des détails d'un paquet de télédéploiement

### ISSUE THREAD

**Issue by steph78630** [OCSInventory-NG/OCSInventory-ocsreports#258]
### General informations
Operating system : Debian GNU/Linux 8 (jessie)

### Server informations
Php version : 5.6.30
Mysql / Mariadb / Percona version : (Debian) version 5.5.54-0+deb8u1
Apache version : 2.4.10 (Debian)

### OCS Inventory informations
Ocsreports version : 2.3.1

### Problem's description

Bonjour, une fois un paquet de télédéploiement créé, serait-il possible de pouvoir permettre l'affichage de ses détails (certaines valeurs de son fichier info : ID, PRI, ACT, PROTO, NAME, NOTIFY_USER) ?

Par exemple, aller dans Télédéploiement > Activation :
- Clic sur le nom d'un paquet et affichage de ses détails
ou
- Ajout d'une fonction "Détails" dans la colonne "Actions", clic sur ce nouvel icone et affichage de ses détails

Merci, Stéphane

**Comment by gillesdubois** [comment]
Bonjour,

La modification des paquets introduite en 2.6RC permet de voir les informations via un bouton détails dans 'inventaire -> activer'

Cordialement,
Gilles Dubois.
