### ISSUE TITLE
Scheduling tasks

### ISSUE THREAD

**Issue by kasperbaes** [OCSInventory-NG/OCSInventory-ocsreports#261]
Hi,

At our company we are looking to use this tool, but i have not found if it is possible to schedule some tasks like the deployment of agents or discover new clients. Is this possible or can this be added in a following release? Also, is it possible to send an email when a certain client is down?

**Comment by MyTheValentinus** [comment]
Hello,
Github issues is only for bugs reporting and ideas about the soft. You can ask your quesiton on the ask (https://ask.ocsinventory-ng.org/)

Thakns
