### ISSUE TITLE
Readonly AccountInfo Datas don't display if profile is autorized to change them

### ISSUE THREAD

**Issue by dubreido** [OCSInventory-NG/OCSInventory-ocsreports#262]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system : Centos 7

### Server informations
Php version : 5.4.45
Mysql / Mariadb / Percona version : Maria DB 10.1.19
Apache version : 5.5

### OCS Inventory informations
Ocsreports version : 2.3.1

### Problem's description
If your profile is autorized to change AccountInfo, and accountinfo are "readonly" type,  accouninfo datas are not displayed. 
Proposed solution to fix this problem : between //DUBREIL and //FDUBREIL
ocsreports\plugins\computer_detail\cd_admininfo\cd_admininfo.php : ligne 248 
             if ($_SESSION['OCS']['profile']->getConfigValue('CHANGE_ACCOUNTINFO') == "YES") {
				// DUBREIL - 03/07/17
				if ($val_admin_info['TYPE']==3)   
					array_push($type_field, 13);   
				else
				// FDUBREIL 				         
					array_push($type_field, $convert_type[$val_admin_info['TYPE']]);
            } else {
                //TODO : QRCode management
				 array_push($type_field, 13);      
            }

**Comment by gillesdubois** [comment]
Hi,

Can you give me more informations on how to reproduce step ? I don't have this bug ?
We already fixed account info bug recently, did you check if it not already fixed in the trunk ?

Regards,
Gilles Dubois.

**Comment by charleneauger** [comment]
Hi @dubreido ,
Your issue has been solved on the trunk branch.

Regards,
Charlene Auger
