### ISSUE TITLE
Question - Old WEB interface

### ISSUE THREAD

**Issue by ortizleo** [OCSInventory-NG/OCSInventory-ocsreports#264]
Hello.
Anyway to use older version of UI? It's more clean and easy to use.... 
I rly didn't updated to new version because this new UI. We are still using 2.0.5 version...

**Comment by mtbadi39** [comment]
am too !! [#59](https://github.com/OCSInventory-NG/OCSInventory-ocsreports/issues/59)

**Comment by gillesdubois** [comment]
Hi,

Thanks for your feedback.
The new UI only has one year, we are working hard on improving it.

Regards,
Gilles Dubois.
