### ISSUE TITLE
OCS Inventory  Report - Empty in CSV 

### ISSUE THREAD

**Issue by c-pradeepk** [OCSInventory-NG/OCSInventory-ocsreports#265]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system : Ubuntu

### Server informations
Php version : 7.0.18-0ubuntu0.16.04.1 (apache2handler)
Mysql / Mariadb / Percona version : (Ubuntu) version 5.7.18-0ubuntu0.16.04.1
Apache version : Apache/2.4.18 (Ubuntu)

### OCS Inventory information's
Ocsreports version : 2.2

### Problem's description
*Export Inventory report EMPTY IN CSV File
All Fields are empty 
[export (8).zip](https://github.com/OCSInventory-NG/OCSInventory-ocsreports/files/1127398/export.8.zip)
 *

**Comment by c-pradeepk** [comment]
Datas are show in screen but download the report all are empty

**Comment by gillesdubois** [comment]
HI @c-pradeepk ,

Every page have this behavior ?

Regards,
Gilles Dubois.

**Comment by gillesdubois** [comment]
It's been solved in a pull request from our contributors, the bug has been resolved.

Regards,
Gilles Dubois.
