### ISSUE TITLE
Adding mouseover informations for icons/images

### ISSUE THREAD

**Issue by yafp** [OCSInventory-NG/OCSInventory-ocsreports#266]
*Feature request*

### General informations
Operating system : Ubuntu 16.04

### Server informations
Php version : 7.x
Mysql / Mariadb / Percona version : 5.7.18
Apache version : 2.4.18

### OCS Inventory informations
Ocsreports version : 2.3.1

### Problem's description
It would be great if all images/icons used in the webinterface would feature a mouseover information string. Right now (without mouseover) its hard to guess in some cases what a click on an images might cause.

Example:
In 'Deployment' -> 'Activate' -> 'Available packages' -> 'Package activation'  exists a table which lists all available software packages. The column 'Actions' offers 4 functions, each represented via a small icon.

Having a small mouseover-text for each icon would help a lot.

**Comment by yafp** [comment]
See #264

**Comment by gillesdubois** [comment]
Hi,

It a good improvement on new UI visibility.
Added it as an enhancement.

Regards,
Gilles Dubois.

**Comment by yafp** [comment]
Either mouse-overs or images plus text. But i guess mouseover is the best solution. Gonna offer help for the german translations if needed.
