### ISSUE TITLE
Notifications about non existing or non-writable directories should show the actual path/dir

### ISSUE THREAD

**Issue by yafp** [OCSInventory-NG/OCSInventory-ocsreports#267]
*Feature request*

### General informations
Operating system : Ubuntu 16.04

### Server informations
Php version : 7.x
Mysql / Mariadb / Percona version :  5.7.18
Apache version : 2.4.18

### OCS Inventory informations
Ocsreports version : 2.3.1

### Problem's description
While configuring my OCS server instance i got several notifications in the WebUI telling me that some directory is not writeable or doesnt exists. It would help at that point to always include the actual path of the affected folder/dir in the notification.

Currently: Your logs directory is not writable
Better: Your logs directory (/usr/lib/ocsinventory-server/logs) is not writable

Right now i do see this error and don't understand how to debug it - as both:
* /var/log/ocsinventory-server/
* /var/lib/ocsinventory-reports/logs
are writeable, but the error is still displayed.

**Comment by gillesdubois** [comment]
Hi,

Indeed some directories are not properly listed.
We need to improve these messages.

Regards,
Gilles Dubois.

**Comment by gillesdubois** [comment]
Hi,

The check for the writables directory error has been fix in the last commit. ( see function_commun.php)
Some commit are coming with tips in the directory indications for basics warnings :)

Everything should be fixed in the next version.

Regards,
Gilles Dubois.

**Comment by silviosky** [comment]
This problem "Your logs directory (by default : /var/lib/ocsinventory-reports/logs) is not writable" is also here with version:
Software
    PHP Version: 7.3.33
    Web Server: Apache/2.4.6 (CentOS) PHP/7.3.33 mod_perl/2.0.11 Perl/v5.16.3
    Database Server: MariaDB Server version 5.5.68-MariaDB
    Version OCSReports: 2.9.2

Many problems which you say have been fixed years ago, I still find them in the year 2022 in versions 2.9.1 and 2.9.2. For example, the "search with various criteria" inventory problem, or the duplicates page, which returns the page blank and no debug information appears either.
Furthermore, no one has ever answered these problems on the wiki or on github, but the technicians who have had these problems are many.
