### ISSUE TITLE
Serveurs de redistribution - Déploiement sur groupes

### ISSUE THREAD

**Issue by githublivier** [OCSInventory-NG/OCSInventory-ocsreports#269]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system :  CentOS Linux 7

### Server informations
Php version : 5.4.16
Mysql / Mariadb / Percona version :
Apache version : MariaDB Server version 5.5.44

### OCS Inventory informations
Ocsreports version :  2.3

### Problem's description
Bonjour,

Lorsque j'essaie d'effectuer un déploiement via groupe de redistribution sur des groupes statiques ou dynamiques, je rencontre le message d'erreur suivant : 
"0 machines n'ont pas de serveurs de redistribution.
Il faut donc affecter ce paquet individuellement. Il est aussi possible que ce paquet ne soit pas affecté sur leur serveur de redistribution"

En revanche, lorsque je fais un télédéploiement en passant par une recherche multicritère sur le groupe, ça fonctionne bien. 

Un test non concluant a également été effectué sur la V2.3.1

D'avance merci.

**Comment by gillesdubois** [comment]
Bonjour,

Merci pour votre retour, vote demande e bien ete prise en compte.

Cordialement,
Gilles Dubois.
