### ISSUE TITLE
No function behind: Information -> Statistics 

### ISSUE THREAD

**Issue by yafp** [OCSInventory-NG/OCSInventory-ocsreports#270]
### General informations
Operating system :  Ubuntu 16.04

### Server informations
Php version : 7.0
Mysql version : 5.7.18
Apache version : 2.4.18

### OCS Inventory informations
Ocsreports version : 2.3.1

### Problem's description
If i select "Information" -> "statistics" from the main menu i get an almost empty page just showing "No Files"

Other users in IRC confirmed that issue.

**Comment by gillesdubois** [comment]
Hi,

Connection number by day tab use a file which is not activated by default.
However, you can click on the "OTHER" tab to get stats.

See screen below :
![deepinscreenshot_select-area_20170713150329](https://user-images.githubusercontent.com/9396603/28167694-c39627f6-67dc-11e7-8a83-65611991d775.png)
![deepinscreenshot_select-area_20170713150523](https://user-images.githubusercontent.com/9396603/28167695-c39c2034-67dc-11e7-9987-54ca0e0acef1.png)

Regards,
GilllesDubois.

**Comment by yafp** [comment]
Hi,

thanks for this answer. 
How can i enable the "Connection number by day" tab then? Via UI or commandline (if so in which file)?
