### ISSUE TITLE
No function behind: Information -> Log visualization

### ISSUE THREAD

**Issue by yafp** [OCSInventory-NG/OCSInventory-ocsreports#271]
### General informations
Operating system :  Ubuntu 16.04

### Server informations
Php version : 7.0
Mysql version : 5.7.18
Apache version : 2.4.18

### OCS Inventory informations
Ocsreports version : 2.3.1

### Problem's description
If i select "Information" -> "Log visualization" from the main menu i get an almost empty page just showing "NO RESULT"

Other users in IRC confirmed that issue.

This might be because _/var/lib/ocsinventory-reports/logs/_ is empty

**Comment by gillesdubois** [comment]
Hi,

You need to activate the log debugging feature.

Regards,
Gilles Dubois

**Comment by yafp** [comment]
Hi,

thanks for this answer. Where can i enable this function?
I already had configured "Loglevel" in "Config" -> "Server" to "ON" before posting this issue.

**Comment by yafp** [comment]
@gillesdubois 
before i opened this issue here, i posted at ask.ocsinventory-ng.org.

The post shows that the problem has another source, please check:

http://ask.ocsinventory-ng.org/7364/information-log-visualization-shows-no-result

The comment from Stéphane solves this issue for the user, while developers should check hwy it happens in the first place and how to handle it.

Best regards
florian
