### ISSUE TITLE
No function behind: Config -> Agent

### ISSUE THREAD

**Issue by yafp** [OCSInventory-NG/OCSInventory-ocsreports#272]
### General informations
Operating system :  Ubuntu 16.04

### Server informations
Php version : 7.0
Mysql version : 5.7.18
Apache version : 2.4.18

### OCS Inventory informations
Ocsreports version : 2.3.1

### Problem's description
If i select "Config" -> "Agent" from the main menu i get an almost empty page just showing an empty datatable with no records.

Other users in IRC confirmed that issue.

The server knows about around 20 clients running different operating systems and agents but tihs particular page shows just nothing from the available data.

**Comment by gillesdubois** [comment]
Can you send me your error log when you are accessing to this page ?

Regards,
Gilles Dubois.

**Comment by yafp** [comment]
Hi,

> Can you send me your error log when you are accessing to this page ?

For sure i could, but visiting Config" -> "Agent" results in no output in /var/log/apache2/error.log.

I've attached a screenshot of the related UI to avoid misunderstandings.

![20170714-081203---ocs](https://user-images.githubusercontent.com/67605/28200469-9bf22cbe-686c-11e7-82bb-37382731a5de.png)

> Note : this page is only used to upload agent executables

Ok, this might explain the situation. I expected to see some config informations about my agents on this page. I guess a misunderstand on my side. Feel free to close this issue then.

**Comment by gillesdubois** [comment]
No problems,
Agent configuration are in the computer itself in the configuration tab.

Regards,
Gilles Dubois.
