### ISSUE TITLE
Notification when inventory change

### ISSUE THREAD

**Issue by ortizleo** [OCSInventory-NG/OCSInventory-ocsreports#273]
Hello.
This is a great feature, you should think about it..
Send a notification mail, or syslog when inventory changes, hardware or software.
Thanks.

**Comment by yafp** [comment]
I would love to see email-notifications (see #219) in general as well ... and yes optional for inventory changes for sure would be great.

**Comment by thornnado** [comment]
Hi, is there a chance that this feature will be added to ocs inventory any soon ? 
Regards

**Comment by gillesdubois** [comment]
Hi,

Mail notifications has been added to OCS Inventory.
However, we don't plan on managing PC History. One of the most reliable solution would be to interconnect with a CMDB which will keep the history of the object.
GLPI and iTop already do that with there plugins.

Regards,
Gilles Dubois.
