### ISSUE TITLE
Traitement par lots - Gestion des télédéploiements

### ISSUE THREAD

**Issue by githublivier** [OCSInventory-NG/OCSInventory-ocsreports#274]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system : CentOS Linux 7

### Server informations
Php version : 5.4.16
Mysql / Mariadb / Percona version :
Apache version : MariaDB Server version 5.5.44

### OCS Inventory informations
Ocsreports version : 2.3

### Problem's description
Bonjour,

Il semblerait qu'il y ait un bug dans la fonctionnalité gestion des télédéploiements pour les traitements par lots ET pour **les paquets utilisant des groupes de redistribution**

Tests effectués : 
1- Affectation d'un paquet utilisant groupe de redistribution sur une machine
2- Recherche multicritère pour cibler la machine
3- Traitement par lots
4- Gestion des télédéploiements
5- Sélection du paquet
6- Désaffecter
--> J'ai bien un message m'indiquant que le paquet a été désaffecté sur les machines
--> Lorsque je vais sur la fiche de la machine - sous menu télédéployer, le paquet est toujours en attente de notification.
--> Lorsque je lance la remontée d'inventaire sur la machine, le paquet apparait bien dans le log comme étant un paquet à installer.

Remarque : si le paquet n'est pas **un paquet utilisant les serveurs de redistribution** la désaffection des paquets fonctionne bien

D'avance merci

**Comment by gillesdubois** [comment]
Bonjour @githublivier ,

D'autre personne on déjà remonté le problème. Merci pour le complément d'informations.
Le problème est en cours de traitement.

Cordialement,
Gilles dubois.

**Comment by gillesdubois** [comment]
Bonjour,

Ce problème à été fixé dans le trunk et sera bientôt disponible dans notre nouvelle release.

Cordialement,
Gilles Dubois.
