### ISSUE TITLE
no user/profile alteration (profile missing) after fresh install on CentOS 7

### ISSUE THREAD

**Issue by larieu** [OCSInventory-NG/OCSInventory-ocsreports#275]
### General informations
Operating system : 
    OS Name :    Linux x86_64
    Version :    3.10.0-514.26.2.el7.x86_64
    RAM installed :    1839 MB
    Free RAM :    1398 MB
    CPU :    Common KVM processor
    Distribution :    CentOS Linux 7 (Core)

### Server informations
Php version : 5.4.16
Mysql / Mariadb / Percona version : MariaDB Server version 5.5.52-MariaDB
Apache version : Apache/2.4.6 (CentOS) PHP/5.4.16 mod_perl/2.0.10 Perl/v5.16.3

### OCS Inventory informations
Ocsreports version : 2.3.1

### Problem's description
1. minimal install CentOS 7

2. update/install ocs as follows

2.1. basc 
```
yum update
reboot
```

2.2.  install wget and repo
```
yum install wget
mkdir ~/ocs
cd ~/ocs
wget https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
wget https://rpm.ocsinventory-ng.org/enterprise/7/x86_64/ocsinventory-release-7-4.el7.ocs.noarch.rpm
yum install ocsinventory-release-7-4.el7.ocs.noarch.rpm epel-release-latest-7.noarch.rpm
```

2.3. install ocsinventory
`yum install ocsinventory`

2.4. enable/start database/apache
```
systemctl enable httpd.service mariadb.service && systemctl start httpd.service mariadb.service && systemctl status httpd.service mariadb.service
```

2.5. initialise database
`mysql_secure_installation`
change root pass and accept defaults

2.6. poke a hole in firewall for webserver
```
firewall-cmd --permanent --zone=public --add-port=80/tcp
firewall-cmd --permanent --zone=public --add-port=443/tcp
firewall-cmd --reload

```
2.7. finish the install on web page
GO TO WEB PAGE 
http://YOUR.SERVER.IP./ocsreports/install.php

2.8. secure your install
2.8.1.
```
mv /usr/share/ocsinventory-reports/ocsreports/install.php /usr/share/ocsinventory-reports/ocsreports/install.php.whatever
```
2.8.2.
```
mysql -u root -p
```
create a new user and delete the old one
```
GRANT ALL PRIVILEGES ON `ocswebyourdb` .* TO 'ocswebyouruser'@'localhost' IDENTIFIED BY 'ocsyourwebpass' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `ocswebyourdb` .* TO 'ocswebyouruser'@'%' IDENTIFIED BY 'ocswebyourpass' WITH GRANT OPTION;
DROP USER 'ocs'@'localhost';
DROP USER 'ocs'@'%';
flush privileges;
SELECT User, Host, Password FROM mysql.user;
quit;
```
2.10. edit appropriate user/pass in following files and restart the web server
```
vi /etc/ocsinventory/ocsinventory-reports/dbconfig.inc.php
vi /etc/httpd/conf.d/ocsinventory-server.conf
```
```
systemctl restart httpd.service
```

logut / refresh (CTRL+F5) / relogin

### Issue

go to Config > Users > Profiles 

>  no profiles available

go to Config > Users > Create profile

> The config/profiles directory is not writable

go to Config > Config > Interface 
CONF_PROFILS_DIR  has value
By default (/usr/share/ocsinventory-reports/ocsreports//var/lib/ocsinventory-reports/plugins/main_sections/conf/)
and
OLD_CONF_DIR has value
By default (/usr/share/ocsinventory-reports/ocsreports//var/lib/ocsinventory-reports/plugins/main_sections/old_conf/)

both wrong
being straight install should be correct with correct write permissions

**Comment by kapouik** [comment]
commit b86a2aaaedfc25d3a91765aa9bfe51ff3ebb3251 correct the bug.

**Comment by kapouik** [comment]
All RPM have been updated.
