### ISSUE TITLE
Import file button in administrative zone (btn)

### ISSUE THREAD

**Issue by steph78630** [OCSInventory-NG/OCSInventory-ocsreports#277]
### General informations
Operating system : Debian GNU/Linux 8 (jessie)

### Server informations
Php version : 5.6.30
Mysql / Mariadb / Percona version : (Debian) version 5.5.55-0+deb8u1
Apache version : Apache/2.4.10 (Debian)

### OCS Inventory informations
Ocsreports version : 2.3.1

### Problem's description
Creating a button (BLOB) to embed a file in the administrative area of a computer does not work - Instead, a text is displayed: "btn" (admin profil) or "accountinfo" (read-only profil)

**Comment by gillesdubois** [comment]
Hi,

This problem has been solved in 2.6RC

Regards,
Gilles Dubois.
