### ISSUE TITLE
Add sort button by order of displayed plugins

### ISSUE THREAD

**Issue by steph78630** [OCSInventory-NG/OCSInventory-ocsreports#279]
### General informations
Operating system : Debian GNU/Linux 8 (jessie)

### Server informations
Php version : 5.6.30
Mysql / Mariadb / Percona version : (Debian) version 5.5.57-0+deb8u1
Apache version : Apache/2.4.10 (Debian)

### OCS Inventory informations
Ocsreports version : 2.3.1

### Problem's description
In particular in the MISCELLANEOUS section, the plugins appear in the order of installation ... Would it be possible to add a button to change the display order (as is already the case for the tags of the administrative area) ?

**Comment by gillesdubois** [comment]
Hi,

There is no plan on doing such a feature.
With the new extension engine you can change the used tab and thus change where the plugin data are located.

Regards,
Gilles Dubois.
