### ISSUE TITLE
Mac Address blacklist using wildcard character

### ISSUE THREAD

**Issue by correajl** [OCSInventory-NG/OCSInventory-ocsreports#28]
Hi! I would like to suggest a simple feature that could help a lot of users. When we need to create a blacklist, using Config -> Blacklist -> Add -> Mac Address, we should enter the complete mac address. But, if we can insert just a prefix (just part of mac address), this would facilitate management.

Two uses in which we would be benefited would be: (1) virtualbox hosts and (2) CARP (or VRRP) IPs. Both cases use the same mac address prefix and we could exclude these hosts from inventory. Another possibility with this feature would be exclude a vendor from inventory, just inserting the three first blocks of mac address.

Thanks!
:)

**Comment by gillesdubois** [comment]
Hello,

Your idea is really interessting, that would be a nice feature to add.
I will try to add it to the ocs road map as soon as possible :)

Thanks for contributing to ocsinventory-ng project !
Regards,
Gilles Dubois.

**Comment by gillesdubois** [comment]
Hi,

Your idea has been added to the 2.2 Roadmap.
This change will be done in a 2.2's minor version.

Thanks you very much for contributing ocsinventory project.
Regards, Gilles Dubois.
