### ISSUE TITLE
Add new section

### ISSUE THREAD

**Issue by steph78630** [OCSInventory-NG/OCSInventory-ocsreports#281]
### General informations
Operating system : Debian GNU/Linux 8 (jessie)

### Server informations
Php version : 5.6.30
Mysql / Mariadb / Percona version : (Debian) version 5.5.57-0+deb8u1
Apache version : Apache/2.4.10 (Debian)

### OCS Inventory informations
Ocsreports version : 2.3.1

### Problem's description
In the machine view and at the same level as "Administrative data", "Hardware", "Software", etc. add :

New "Network" section which would integrate the informations specific to the network as well as several existing plugins (and others to come ?).

Regards, Stéphane

**Comment by gillesdubois** [comment]
Fixed with last PR (#322)
Thx for your contribution.

Regards,
Gilles Dubois.
