### ISSUE TITLE
Window 10 not update infomation

### ISSUE THREAD

**Issue by nntu** [OCSInventory-NG/OCSInventory-ocsreports#284]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system : CentOS Linux 7 (Core)

### Server informations
Php version : 5.6.30
Mysql / Mariadb / Percona version : MariaDB Server version 10.1.26-MariaDB
2.3.1
Apache version : Apache/2.4.6 (CentOS) PHP/5.6.30 mod_perl/2.0.10 

### OCS Inventory informations
Ocsreports version : OCS Inventory NG Agent Version 2.3.0.0

### Problem's description
Starting OCS Inventory NG Agent on Friday, August 25, 2017 13:07:02.
AGENT => Running OCS Inventory NG Agent Version 2.3.0.0
AGENT => Using OCS Inventory NG FrameWork Version 2.3.0.0
AGENT => Loading plug-in(s)
	DLL PLUGIN => Searching for Plug-in DLL(s) in folder <c:\bidvct\ocs\plugins>
	DLL PLUGIN => 0 DLL Plug-in(s) successfully loaded on 0 DLL(s) found
AGENT => Using network connection with Communication Server
	COM PROVIDER => Loading Communication Provider <c:\bidvct\ocs\ComHTTP.dll>
AGENT => Using Communication Provider <OCS Inventory NG cURL Communication Provider> Version <2.3.0.0>
	AGENT => Sending getLabel request
	COM SERVER => Initializing cURL library for getFile
	COM SERVER => Using cURL without server authentication
	COM SERVER => Disabling cURL proxy support
	COM SERVER => Disabling cURL SSL server validation support
	COM SERVER => Sending fileGet request to URL <http://10.141.2.80/ocsinventory/deploy/label>
	COM SERVER => fileGet response received <HTTP Status Code #400>
	COM SERVER => Cleaning cURL library
	AGENT => Failed to retrieve Label <HTTP Status Code #400>
AGENT => Sending Prolog
	DID_CHECK => Read DeviceID <700DES45004-2017-08-24-18-53-44> and MACs <A0:8C:FD:CE:7C:55> in file <ocsinventory.dat>
	COM SERVER => Initializing cURL library for sendRequest
	COM SERVER => Using cURL without server authentication
	COM SERVER => Disabling cURL proxy support
	COM SERVER => Disabling cURL SSL server validation support
	COM SERVER => Sending HTTP Post request to URL <http://10.141.2.80/ocsinventory>
	COM SERVER => HTTP Post response received <HTTP Status Code #200>
	COM SERVER => Cleaning cURL library

09:11:20 2017;2413;311;741DES45004-2017-08-24-18-53-44;10.141.5.3;OCS-NG_WINDOWS_AGENT_v2.3.0.0;session;started
Fri Aug 25 09:25:59 2017;2363;511;NA;10.141.5.3;OCS-NG_WINDOWS_AGENT_v2.3.0.0;deploy;no_file
Fri Aug 25 09:25:59 2017;2363;515;NA;10.141.5.3;OCS-NG_WINDOWS_AGENT_v2.3.0.0;end;bad_request
Fri Aug 25 09:25:59 2017;2364;103;741DES45004-2017-08-24-18-53-44;10.141.5.3;OCS-NG_WINDOWS_AGENT_v2.3.0.0;prolog;new_deviceid
Fri Aug 25 09:25:59 2017;2364;103;741DES45004-2017-08-24-18-53-44;10.141.5.3;OCS-NG_WINDOWS_AGENT_v2.3.0.0;snmp;error: agent must communicate using https to be able to get SNMP communities (only affects OCS unix agent) !!
Fri Aug 25 09:25:59 2017;2364;100;741DES45004-2017-08-24-18-53-44;10.141.5.3;OCS-NG_WINDOWS_AGENT_v2.3.0.0;prolog;accepted
Fri Aug 25 09:25:59 2017;2364;311;741DES45004-2017-08-24-18-53-44;10.141.5.3;OCS-NG_WINDOWS_AGENT_v2.3.0.0;session;started
Fri Aug 25 09:28:59 2017;2344;511;NA;10.141.5.3;OCS-NG_WINDOWS_AGENT_v2.3.0.0;deploy;no_file
Fri Aug 25 09:28:59 2017;2344;515;NA;10.141.5.3;OCS-NG_WINDOWS_AGENT_v2.3.0.0;end;bad_request
Fri Aug 25 09:28:59 2017;2345;103;741DES45004-2017-08-24-18-53-44;10.141.5.3;OCS-NG_WINDOWS_AGENT_v2.3.0.0;prolog;new_deviceid
Fri Aug 25 09:28:59 2017;2345;103;741DES45004-2017-08-24-18-53-44;10.141.5.3;OCS-NG_WINDOWS_AGENT_v2.3.0.0;snmp;error: agent must communicate using https to be able to get SNMP communities (only affects OCS unix agent) !!
Fri Aug 25 09:28:59 2017;2345;100;741DES45004-2017-08-24-18-53-44;10.141.5.3;OCS-NG_WINDOWS_AGENT_v2.3.0.0;prolog;accepted
Fri Aug 25 09:28:59 2017;2345;311;741DES45004-2017-08-24-18-53-44;10.141.5.3;OCS-NG_WINDOWS_AGENT_v2.3.0.0;session;started

So it not update server

**Comment by gillesdubois** [comment]
Hi,

Can you send me what's in your error log ?
I will close your issue on windows agent since it's a duplicate.

Concerning the agent log, it throw a 200 status code so it's seem to be ok. Might be a server related issue.

Regards,
Gilles Dubois.

**Comment by gillesdubois** [comment]
Hi,

Did you try with the new agent version ? 2.3.1.1 has been release 2 weeks ago.

Regards,
Gilles Dubois.
