### ISSUE TITLE
Change language when logged in using single sign-on / (Set default language)

### ISSUE THREAD

**Issue by Gregger83** [OCSInventory-NG/OCSInventory-ocsreports#285]
### General informations
Operating system : Debian GNU/Linux 7.11 (wheezy)

### Server informations
Php version :  5.4.45
__Mysql__ / ~~Mariadb~~ / ~~Percona~~ version :  5.5.57-0+deb7u1
Apache version :  Apache/2.2.22 (Debian)

### OCS Inventory informations
Ocsreports version :  2.3.1

### Problem's description
How  to change / (set)  the (default) language when using single sign-on?

**Comment by gillesdubois** [comment]
Hi,

You need to update your var.php file located in /usr/share/ocsinventory-reports/ocsreports/var.php line 84.
Change the string to the desired default language.

Regards,
Gilles Dubois.
