### ISSUE TITLE
Cannot login, error "NO TAG AFFECTEID TO YOUR PROFILE"

### ISSUE THREAD

**Issue by Wraathz** [OCSInventory-NG/OCSInventory-ocsreports#286]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system :  Centos7

### Server informations
Php version :  5.4.16
Mysql / Mariadb / Percona version :  mysql Ver 15.1
Apache version :  httpd 2.4.6-45.el7.centos.4.x86_64

### OCS Inventory informations
Ocsreports version :  2.3.1

### Problem's description
Good evening,
So, I was "messing around" at the website, checking how to create users and deleting them to "learn how to do it" and checking how to give them priorities and I am almost sure I did something on the login part.
When I try to login now it gives me the message "NO TAG AFFECTEID TO YOUR PROFILE". I go to the "wheel" on the top right of the screen, it says "My account" and "logout" so I suppose I am logged in.
But I cannot click in anything else. Or at least I click it, (example, "inventory", "manage", etc) and it does absolutely anything.
Searched a lot of files configurations and I don't know what to do to fix this.
If anyone has any ideas, please let me know.
Best regards

**Comment by cesarac1994** [comment]
See my contrib, maybe it helps:
https://github.com/OCSInventory-NG/OCSInventory-ocsreports/issues/311#issuecomment-342746893

**Comment by gillesdubois** [comment]
Hi,

Your issue has been fixed in the trunk.
You will see it in the next version of our product.

Regards,
Gilles Dubois.
