### ISSUE TITLE
Registre HKEY_CURRENT_USER - pas de remontée d'inventaire

### ISSUE THREAD

**Issue by githublivier** [OCSInventory-NG/OCSInventory-ocsreports#287]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system : Centos 7

### Server informations
Php version : 5.4.16
Mysql / Mariadb / Percona version : 5.5.44
Apache version : 2.4.6

### OCS Inventory informations
Ocsreports version : 2.3

### Problem's description
Bonjour,

Les clés de registre ciblant la rush HKEY_CURRENT_USER ne remonte pas dans l'inventaire.
Pas de problème pour les clés ciblant la rush HKEY_LOCAL_MACHINE.

D'avance merci

**Comment by kapouik** [comment]
L'inventaire se fait via l'utilisateur system afin d'avoir les droits d'accès a l'ensemble des composant de windows et de ne pas être bloqué pour les télédéploiement. De ce fait il peut uniquement accéder à la rush HKEY_CURRENT_USER de l'utilisateur local system.

question traité sur le ask.
