### ISSUE TITLE
Duplicate computers 

### ISSUE THREAD

**Issue by ankitwaghela09** [OCSInventory-NG/OCSInventory-ocsreports#288]
### OCS Inventory informations
Ocsreports version : 2.3.1

### Problem's description
I have found duplicate computer create cause of change in CPU Current Speed.
please help to get it resolve.

**Comment by gillesdubois** [comment]
Hi,

Does this problem occur on all computers which get there current speed changed ?
Also, i need more informations on your installation since it can be related to your database.
Can you edit your issue with the default template ?

Regards,
Gilles Dubois.

**Comment by charleneauger** [comment]
Hi @ankitwaghela09 ,
Have you change your processor or just the current speed ?

Regards,
Charlene Auger.

**Comment by ankitwaghela09** [comment]
@gillesdubois 
Does this problem occur on all computers which get there current speed changed ? yes

Also, i need more informations on your installation since it can be related to your database.
Can you edit your issue with the default template ? sorry didn't get you but i have install OCS from scratch.

**Comment by ankitwaghela09** [comment]
@charleneauger 
Have you change your processor or just the current speed ? NO, its just current speed.
