### ISSUE TITLE
problème export account info type select

### ISSUE THREAD

**Issue by acsflorian** [OCSInventory-NG/OCSInventory-ocsreports#291]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system : Ubuntu 16.04.3 LTS

### Server informations
Php version : 7.0.22
Mysql / Mariadb / Percona version : Mysql (Ubuntu) version 5.7.19-0ubuntu0.16.04.1
Apache version : Apache/2.4.18 (Ubuntu)

### OCS Inventory informations
Ocsreports version : 2.3.1

### Problem's description

Depuis la migration du serveur de la 2.3 vers la 2.3.1, nous rencontrons un problème d'export.
En effet, lors de l'export, les colonnes accountinfo de type SELECT me renvoie un ID et non la valeur renseigner dans le champ.

Merci
![capture1](https://user-images.githubusercontent.com/32514407/31266603-d77f283c-aa74-11e7-82dc-40e6cea9fc4e.PNG)
![capture2](https://user-images.githubusercontent.com/32514407/31266604-d781fbe8-aa74-11e7-880e-7725195cf4e7.PNG)

**Comment by candaes** [comment]
![copie ocs](https://user-images.githubusercontent.com/32489889/31393941-41c987c6-addd-11e7-9170-8ab6bcb0b33a.JPG)

J'ai le même problème et cela concerne les données administratives ayant un champ "radio button"


![capture](https://user-images.githubusercontent.com/32489889/31394113-cccd0e06-addd-11e7-816c-8b84a28d7508.JPG)

![capture2](https://user-images.githubusercontent.com/32489889/31394301-43e49b6c-adde-11e7-8396-bcc747ca294d.JPG)

**Comment by acsflorian** [comment]
j'ai résolu le problème temporairement en remplacant le fichier OCSInventory-ocsreports/plugins/main_sections/ms_export/ms_csv.php de la version 2.3.1 par celui de la version 2.3 et cela fonctionne
A confirmer pour les tables radio button
