### ISSUE TITLE
Plugin installation issue

### ISSUE THREAD

**Issue by edimusrex** [OCSInventory-NG/OCSInventory-ocsreports#299]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General information
Operating system : Ubuntu 16.04.3 LTS

### Server information
Php version : 7.0.22

Mysql / Mariadb / Percona version : mysql (Ubuntu) version 5.7.19-0ubuntu0.16.04.1

Apache version : Apache/2.4.18 (Ubuntu)

### OCS Inventory information
Ocsreports version :  2.3.1

### Problem's description

I am unable to install ANY plugins, I get the following error message with no additional information

> The communication server encountered the following error on install :  

Underneath that message says that it has installed and I can get to the plugin section within ocsreports but it is unusable, seems to only partially install.  I saw a user with a similar problem but I never did see if there was a resolution to it.  My log files do not seem to be telling me anything useful either.

Thank you

**Comment by Nevahen** [comment]
Hi,

I did have same kind of problems, but did manage to get it working by manually moving few files

You check if you have anything in _/etc/ocsinventory-server/perl/Apache/Ocsinventory/Plugins/_

**If not you can move the .pm file manually to:**
_/etc/ocsinventory-server/perl/Apache/Ocsinventory/Plugins/plugin_name/_

**And the .conf to:**
_/etc/ocsinventory-server/plugins/plugin_name.conf_

Restart apache after, if it fails to start, plugin files are in wrong folder

I don't know why it doesn't allow server to move files there, I have tried to chmod permission and so on. Some plugins require php files moved manually too, but database commits **does** work when installing with plugin manager

**Comment by gillesdubois** [comment]
Hi, @Nevahen @edimusrex 

I will close this issue since a fix has been proposed. 
See https://github.com/OCSInventory-NG/OCSInventory-Server/pull/79 for more informations.

Regards,
Gilles Dubois.
