### ISSUE TITLE
Problème de sélection dans la table "search from various criteria"

### ISSUE THREAD

**Issue by StCyr** [OCSInventory-NG/OCSInventory-ocsreports#30]
Bonjour,

lorsqu'on sélectionne plusieurs ordinateurs dans la table "search from various criteria", __dans plusieurs onglets de la table__, la selection ne garde que les ordinateurs sélectionnés dans l'onglet en cours.

Exemple: si vous avez 20 ordinateurs et que vous affichez la table 10 entrées à la fois. Si vous sélectionnez l'ordinateur 1 et 3, puis passez à l'onglet suivant (pour voir les ordinateurs de 11 à 20), et sélectionnez l'ordinateur 15, seul l'ordinateur 15 sera sélectionné pour les options de déployement dans le dessous de la page.

Cyrille

**Comment by gillesdubois** [comment]
Bonjour,

Le problème a été en parti résolu avec cette issue : https://github.com/OCSInventory-NG/OCSInventory-ocsreports/issues/25

Le fait d’augmenter le nombre d'entrée dans le table permet d'éviter ce problème.
Pour ce qui es de la sauvegarde de la selection lors d'un changement de page je vais voir si il y a moyen de mettre en place un fix pour ce problème. (Je pense néanmoins que augmenter le nombre d'entrée est plus pratique.)

Cordialement,
Gilles Dubois.
