### ISSUE TITLE
OCS Agent v2.3.1.0 missing information

### ISSUE THREAD

**Issue by faxesystem** [OCSInventory-NG/OCSInventory-ocsreports#300]
### General informations
Operating system : DebianStretch (9.2)
Agents running on Windows 10 and macOS 10.12
### Server informations
Php version : 7.0.19
Mysql / Mariadb / Percona version : (Debian) version 5.5.54-0+deb7u2-log
Apache version : Apache/2.4.25 (Debian)

### OCS Inventory informations
Ocsreports version : 2.3.1

### Problem's description
So we set up a fresh Server 2.3.1 which is running fine. Now we have the problem that the Agent 2.3.1 for macOS and Windows is not reporting detailed memory information. When we use the 2.1.1 client everything gets reported fine.

See screenshots.

https://imgur.com/a/4yxRN

Is this a known bug?

**Comment by gillesdubois** [comment]
Hi,

Your screenshots are only showing Mac OS, it happen on windows too ? do you have an example plz ?

Regards,
Gilles Dubois.

**Comment by gillesdubois** [comment]
Ping @faxesystem ?

**Comment by helicrenz** [comment]
hello @gillesdubois ,

may macos agent wont work without certificate. Its working properly with windows agent.


Regards,

Romeo
