### ISSUE TITLE
"Teledeploy force" ignoré

### ISSUE THREAD

**Issue by Laurent-1971** [OCSInventory-NG/OCSInventory-ocsreports#303]
### General informations
Operating system : CentOS Linux 7 (Core) / Linux x86_64 / 3.10.0-693.2.2.el7.x86_64

### Server informations
Php version : 5.6.31
Mysql / Mariadb / Percona version : MySQL Community Server (GPL) version 5.7.19
Apache version : 

### OCS Inventory informations
Ocsreports version : 2.3.1

### Problem's description

"Use the advanced options of teledeploy" and checking "Teledeploy force" box does not work. The results is still "SUCCESS_ALREADY_IN_HISTORY".

**Comment by allandanton** [comment]
I can confirm this problem. Server ist running on Debian Stretch 64bit with PHP 7.0 and MariaDB from official repositories. Does not seem to effect all packages. I have two packages for Windows that I run frequently to install the most current version of Firefox, Thunderbird and Flash Player from a network drive. 
The Mozilla-Package runs just fine but the Flash Player Package suddenly stopped working with the error "SUCCESS_ALREADY_IN_HISTORY". Recreating the Flash Player Package did not help, it run for the first time but cannot be deployed again by selecting the "Teledeploy force" checkbox.
Server and ocsreports are running version 2.3.1, Agents for Windows and Unix have version 2.3 installed.

**Comment by jmiti4** [comment]
Same for me.
I want to use script for teledeploy last version of software with ftp download but the "Teledeploy force" checkbox is ignored.
Ocs server 2.3.1 on debian8 (php  5.6.30 & mysql 5.5.50)

**Comment by IOVT** [comment]
Same here!
I set it up and works pretty fine most times. But re-deploying doesn't work even with the force tick set.

**Comment by StCyr** [comment]
https://github.com/OCSInventory-NG/OCSInventory-ocsreports/pull/711

**Comment by StCyr** [comment]
Test report:

Tested with 2 packages on several machines => all downloaded and installed the packages successfully.

Though, I'm a little bit worried about these "hanging" "DOWNLOAD_FORCE" entries in the DB:

```
mysql> select * from devices where NAME='DOWNLOAD_FORCE';
+-------------+----------------+--------+--------+----------+
| HARDWARE_ID | NAME           | IVALUE | TVALUE | COMMENTS |
+-------------+----------------+--------+--------+----------+
|        9181 | DOWNLOAD_FORCE |    313 | 1      | NULL     |
|        8501 | DOWNLOAD_FORCE |    313 | 1      | NULL     |
|        8376 | DOWNLOAD_FORCE |    313 | 1      | NULL     |
|        9212 | DOWNLOAD_FORCE |    313 | 1      | NULL     |
|        9212 | DOWNLOAD_FORCE |    205 | 1      | NULL     |
|        9212 | DOWNLOAD_FORCE |    303 | 1      | NULL     |
|        9212 | DOWNLOAD_FORCE |    331 | 1      | NULL     |
|        9212 | DOWNLOAD_FORCE |    270 | 1      | NULL     |
|        9212 | DOWNLOAD_FORCE |    320 | 1      | NULL     |
|        9212 | DOWNLOAD_FORCE |    308 | 1      | NULL     |
|        9212 | DOWNLOAD_FORCE |    305 | 1      | NULL     |
|        9212 | DOWNLOAD_FORCE |    235 | 1      | NULL     |
|        9212 | DOWNLOAD_FORCE |    317 | 1      | NULL     |
|        9212 | DOWNLOAD_FORCE |    267 | 1      | NULL     |
|        9212 | DOWNLOAD_FORCE |    271 | 1      | NULL     |
|        9212 | DOWNLOAD_FORCE |    307 | 1      | NULL     |
+-------------+----------------+--------+--------+----------+
16 rows in set (0.00 sec)
```

Maybe ocsinventory-server should be patched to also remove these lines after successful installation of a package?
