### ISSUE TITLE
incompatibilité avec PHP 5.3.13

### ISSUE THREAD

**Issue by TiVince** [OCSInventory-NG/OCSInventory-ocsreports#305]
### General informations
Operating system :  Linux CentOs 6.4

### Server informations
Php version :  5.3.13
Mysql   version : 5.1 
Apache version :  2.2

### OCS Inventory informations
Ocsreports version : 2.3.1 

### Problem's description

la page d’accueil annonce une compatibilité avec PHP 5.3.7  mais un certain nombre de pages php utilise la notation des tableaux php [ ]  apparu en  PHP 5.4 qui génère des erreurs à l’exécution.

cf http://php.net/manual/fr/language.types.array.php 

> Depuis PHP 5.4, vous pouvez également utiliser la syntaxe courte, qui remplace array() par []. 

pendant nos tests de migration (à partir de la 2.05)  nous avons rencontré les problèmes suivants  

- function_commun.php  
 ligne 411 : function formGroup($inputType, $inputName, $name, $size, $maxlength, $inputValue = "", $class = "", $optionsSelect = [], $arrayDisplayValues = [], $attrBalise = "", $groupAddon = ""){

devrait être  écrite sous cette forme pour la compatibilité 5.3.7 +
function formGroup($inputType, $inputName, $name, $size, $maxlength, $inputValue = "", $class = "", $optionsSelect =array() , $arrayDisplayValues = array(), $attrBalise = "", $groupAddon = ""){

-ms_all_soft.php 👍 
ligne 164  : $list_soft = [];  
devrait être  $list_soft = array(); 

- ms_computer_views.php

ligne 44 :  if ($protectedGet['cat'] == explode('=',$url)[1]) {
la syntaxe  pose problème  à  PHP 5.3.13

remplacé par 
$tmp = explode('=',$url); 
 if ($protectedGet['cat'] == $tmp[1]) {

 - ms_tele_package.php

à partir de  la ligne 450 toutes les déclarations de tableaux  avec  $var = [ .... ]
 $arrayName
$config_input
$list_os
$list_proto
$list_action
$arrayDisplayValue

ligne 577 
formGroup('select', 'REDISTRIB_USE', $arrayName['redistribution'], $config_input['MAXLENGTH'], $config_input['MAXLENGTH'], $protectedPost['REDISTRIB_USE'], '', [0,1], [0 => 'No', 1 => 'Yes'], "onchange='redistributeUse()' ");

n'est pas compatible. 
version compatible PHP 5.3.X
formGroup('select', 'REDISTRIB_USE', $arrayName['redistribution'], $config_input['MAXLENGTH'], $config_input['MAXLENGTH'], $protectedPost['REDISTRIB_USE'], '', array(0,1), array(0 => 'No', 1 => 'Yes'), "onchange='redistributeUse()' ");

**Comment by gillesdubois** [comment]
Bonjour,

Nous ne supportons plus php 5.3.X c'est pourquoi vous ne pouvez pas utiliser OCS sur votre serveur.
Vous devez mettre à jour votre version de php.

Les pages qui parlent de compatbilités avec la 5.3 sont des résidus de code et seront bientot supprimer du logiciel.

Cordialement,
Gilles Dubois.

**Comment by TiVince** [comment]
'Your PHP installation is older than version 5.4 and will not be compatible with incoming versions (version :  5.3.3 )'

donc en théorie  la version 5.3.1 devrait être compatible. Je vais avoir du mal à l'expliquer à mon DSI
