### ISSUE TITLE
le footer permettant d'effectuer des actions en masse devrait se trouver dans d'autres vues

### ISSUE THREAD

**Issue by StCyr** [OCSInventory-NG/OCSInventory-ocsreports#31]
Pour le moment le footer permettant d'effectuer des actions en masse n'est disponible que dans la vue "visu_search" (search with various criteria").

Ce serait bien qu'il se trouve également  dans d'autres vues, comme la vue "all computers"

bien à vous,

Cyrille

**Comment by gillesdubois** [comment]
Les premiers tests d'intégration du mass processing dans all computer sont en cours.
Je metterai a jour l'issue en fonction de comment se déroule l'intégration :)

Cordialement,
Gilles Dubois.
