### ISSUE TITLE
User loging with message "NO TAG AFFECTEID TO YOUR PROFILE"

### ISSUE THREAD

**Issue by cesarac1994** [OCSInventory-NG/OCSInventory-ocsreports#311]
I resolved this, but I thought it was cool to say how to solve.

### General informations
Operating system : Centos 7

### Server informations
Php version :  5.4.45
Mysql / Mariadb / Percona version : mysql  Ver 15.1 Distrib 10.0.32-MariaDB, for Linux (x86_64) using readline 5.1
Apache version : 2.4.6-45

### OCS Inventory informations
Ocsreports version : 2.1.2

### Problem's description
Hi, I has the problem with user cassified as Local Admin. Loging in this user with message "NO TAG AFFECTEID TO YOUR PROFILE", but I resolved this seeing the configuration file nammed ladmin_config.txt, which the 6th line set with "GUI:YES", I set with "GUI:NO" and solved this.

**Comment by charleneauger** [comment]
Hi @cesarac1994 ,
Thank you for your contribution!
I have some questions:

- Your version is 2.1.2 ?

- Have you tried to reproduce this bug on a newer version ?

Regards,
Charlene Auger

**Comment by cesarac1994** [comment]
No :(
After the version 2.3.1, is there any stable version?

**Comment by charleneauger** [comment]
@cesarac1994, 
What is your version of ocsreports ? (On your issue you wrote 2.1.2 but you said no)
The version 2.3.1 is the last version stable available.

Regards,
Charlene Auger

**Comment by cesarac1994** [comment]
Excuse-me, i didn't see the two questions, only the second!
Your version is 2.1.2 ? - Yes
Have you tried to reproduce this bug on a newer version ? - No :(

How can I contribute to your wiki (have some issues in the text...)?

**Comment by gillesdubois** [comment]
Hi,

It's has already been fixed in the trunk.
You will see the fix in the new version.

Regards,
Gilles Dubois.

**Comment by DVS1617** [comment]
**OCS Inventory informations**
Ocsreports version : 2.4
Hi, I has the problem with user cassified as Super Admin. Loging in this user with message "NO TAG AFFECTEID TO YOUR PROFILE", but I resolved this seeing the configuration file nammed sadmin.xml (usr/share/ocsinventory-reports/ocsreports/config/profile), which the 4th line set with "GUI:YES", I set with "GUI:NO" and solved this.
