### ISSUE TITLE
Dynamic group bug: search with a static group is incorrect when the group is empty

### ISSUE THREAD

**Issue by daks** [OCSInventory-NG/OCSInventory-ocsreports#32]
Hello,

we are using OCSInventoryNG reports 2.0.5 (but also tested on 2.1.2) and we found a very weird bug on dynamic groups.

We created a static group (named StaticGroup) with 5 machines.
We then created a dynamic group (DynamicGroup) with the following search:
- Group:Name BELONG TO StaticGroup
- Software: Name DIFFERENT SoftwareX

When the static group has at least one machine, the dynamic group works well.

The problem appears when there is no machine in the static group. Then the dynamic group fills in with ALL the machines which corresponds to the second request (Software: name DIFFERENT).

We activated MySQL logs and saw that:
- in the first case the request looks like 
  
  SELECT .... AND ID IN ('1', '2', ...)

-> ('1', '2'...) being the list of machines ID in the StaticGroup
- but in the second case (empty static group) the request looks like
  
   SELECT ....

-> no filtering is done with the StaticGroup content.

It seems that the first request returns no value so it's removed from the second one. Which causes this bug.

I have not tested it but it this bug may also exists with another condition than a static group.

I can give more details if needed.

Thanks.

**Comment by gillesdubois** [comment]
Hello,

This bug has been fixed in the 2.2RC1.
We won't release a fix for earlier versions because it's not a major / security issue.

However if that still a major issue for you, you can still come to IRC in order to explain your problem, the ocs community will help you to fix it. :)

Thanks for contributing ocsinventory-ng project ;-)
Regards, Gilles Dubois.

**Comment by daks** [comment]
Hello,

I have migrated my actual 2.0.5 OCS server installation to 2.2RC1 to confirm that this bug is fixed.
I think it's not.

What I have done:
- create a static group 'static group' with 10 machines
- create a dynamic group 'dynamic group' based on the following rule: belongs to "static group" and TAG like %MYTAG%
- remove all computers from 'static group' so it's empty

After group cache invalidation and group recalculation, I now have 5900 machines which is the complete inventory park.
You can see here http://imgur.com/a/zXlOG two screenshots.

Can you verify again the state of this bug. I'm available to provide you with more information if needed. (I can go to IRC if needed).

Thanks

**Comment by MyTheValentinus** [comment]
Hello, can you update your OCS installation to 2.2, and try again ?
We cannot reproduce this bug on the current stable version.

Regards, Valentin.

**Comment by daks** [comment]
I'll but at the moment everytime I download the OCSNG_UNIX_SERVER-2.2.tar.gz file it seems corrupt

    gzip: stdin: not in gzip format

Can you verify that the file (download from https://github.com/OCSInventory-NG/OCSInventory-ocsreports/releases/download/2.2/OCSNG_UNIX_SERVER-2.2.tar.gz) is ok?

**Comment by daks** [comment]
I found why: it's a TAR archive not a TAR.GZ one!

**Comment by MyTheValentinus** [comment]
Hello @daks , sorry for this. Actual release file is not gzipped. Future releases will be gzipped. 
Waiting for your feedback on #32.

Regards, Valentin.

**Comment by daks** [comment]
I finally took some time this morning to test this bug on 2.2. I just upgraded my previous 2.2RC1 to 2.2 with the database coming from 2.0.5

At first, I tested with the previous groups created on Nov 15: the problem still exists, my dynamic group got filled with 5900 machines.

I then tested recreating all static and dynamic groups: one static group with one machine at first, and two dynamic groups.
You can see on this album screenshots https://imgur.com/a/ubWYG:
- static group with one machine
- dynamic groups: one which one verify appartenance to static group, the other one verify appartenance+verification on TAG
- each dynamic group has one machine, like expected
- here https://imgur.com/a/T8W7f you can see the description of each dynamic group

When I remove my machine from the static group, after group recalculation I got this strange behaviour:
- one groupe has no machine
- the other one has two!
Weird! https://imgur.com/knxfBMV

**Comment by gillesdubois** [comment]
Hi,

I just tested in the 2.3RC and the initial problem has been fixed with the multi search rework.

Tests : 
Done an empty static group
Make a multisearch belong to group and software name like = 7zip
Created a dynamic groupe => IS OK no machine in group

If the problem still persist this may come from your mysql version.

Thanks your helping us to solve this problem.

Regards,
Gilles Dubois.
