### ISSUE TITLE
Using a GUI Widgets Library for the presentation layer

### ISSUE THREAD

**Issue by mtbadi39** [OCSInventory-NG/OCSInventory-ocsreports#33]
Any roadmap for using a [GUI Widgets Library](http://jster.net/category/ui-frameworks) for the presentation layer (ex:[PrimeUI](http://www.primefaces.org/primeui/) and  [ZnetDK](http://www.znetdk.fr/en_bref))

**Comment by gillesdubois** [comment]
Hello,

Nothing like that is planned at the moment but the roadmap for the version 3.0 ( which is the next version after the 2.2 ) is not closed, so if you want to contribute you can propose this to the roadmap

Regards,
Gilles Dubois.

**Comment by lukBarros** [comment]
hey mans see #66
