### ISSUE TITLE
[OCS 2.4] Nombre de ligne par défaut

### ISSUE THREAD

**Issue by cp61** [OCSInventory-NG/OCSInventory-ocsreports#335]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system : Debian

### Server installation method ( Only one choice )
- [x] RPM Package

### Server informations
Php version :  5.6.31
Mysql / Mariadb / Percona version : 5.5.58
Apache version : 2.2.22

### OCS Inventory informations
Ocsreports version :  2.4

### Problem's description
Bonjour 

Je ne peux toujours pas mettre par defaut dans la page All Computer, le nombre de 1000 lignes plutôt que 10 lignes.

J'ai bien dans l'ascenseur le choix entre 10, 25,50,100,250,500, 1000 sauf que par défaut j'aimerai mettre 1000 lignes et non 10

J'ai changé la valeur "iDisplayLength" à 1000 dans jquery.dataTables.js de /usr/share/ocsinventory-reports/ocsreports/libraries/datatable/media/js

J'ai changé l'odre de "aLengthMenu": [[1000, 25, 50, 100, 250, 500, 1000, 2000, 5000, 10000, 99999999999], [1000, 25, 50, 100, 250, 500, 1000, 2000, 5000, 10000, "All"]],

Mais toujours pas mieux. L'ascensceur reste par défaut sur 10

**Comment by charleneauger** [comment]
Bonjour @cp61,

Je suis désolée de vous annoncer que votre demande ne peut pas être traitée pour un développement communautaire. Elle risquerait d'impacter les performances pour une partie des utilisateurs. 
La seule solution qui a été réalisée lors de la release 2.4 est la possibilité de pouvoir sélectionner 1000 machines à afficher dans le sélecteur. 

Cordialement,
Charlene AUGER
