### ISSUE TITLE
[OCS 2.4] Probleme remonté Informations après Update

### ISSUE THREAD

**Issue by cp61** [OCSInventory-NG/OCSInventory-ocsreports#338]
General informations

Operating system : Debian

    RPM Package

Server informations

Php version : 5.6.31
Mysql / Mariadb / Percona version : 5.5.58
Apache version : 2.2.22
OCS Inventory informations

Ocsreports version : 2.4

Problem's description

Bonjour 

Suite à la mise à jour en 2.4, je n'ai plus de remonté OCS.

Dans l'Error log j'ai bien un message d'erreur qui est le suivant

[Mon Dec 11 09:28:39 2017] [error] [client 10.61.4.8] Can't call method "do" on an undefined value at /usr/local/share/perl/5.14.2/Apache/Ocsinventory/Server/System.pm line 189.\n

J'ai vérifié les fichiers z-ocsinventory-server.conf et dbconfig.inc.php concercant les comptes et mot de passe et redemarré mon serveur Apache.

La line 189 concerne la commande suivante $dbh->do("SET sql_mode='NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION'");

**Comment by gillesdubois** [comment]
Bonjour,

Un nouveau fichier de configuration à été ajouté avec la version 2.4. L'avez-vous configuré ?
Il devrait s'appeller zz-ocsinventory-rest.conf

Gilles Dubois.

**Comment by steph78630** [comment]
Bonjour Gilles,

le fichier ne devrait pas plutôt s'appeler zz-ocsinventory-restapi.conf ?

Cordialement, Stéphane

**Comment by gillesdubois** [comment]
Oui , j'ai fais une petite erreur dans le nommage, c'est bien : zz-ocsinventory-restapi.conf
