### ISSUE TITLE
Save columns to display

### ISSUE THREAD

**Issue by pchamo** [OCSInventory-NG/OCSInventory-ocsreports#342]
### OCS Inventory informations
Ocsreports version : any

### Problem's description
I think there is an important option missing: the option to save the preferred columns to display. 

I mean, e.g. for me usually it's not useful to see the RAM and CPU columns in Ocsreports, so, I always have to hide those columns. And also, there are others columns that I always have to select to visualize them. 

I would be great to have an option to save not only one but several preferences of columns selected to be displayed. I consider that that's something simple but very useful.

Thank you.

**Comment by TiVince** [comment]
Would be interested too. Datatable with the buttons extension provides this features : you could choose the columns you want and your  choice is saved in your browser.s local storage

**Comment by gillesdubois** [comment]
Hi,

With the latest version its already the case.

Regards,
Gilles Dubois.

**Comment by pchamo** [comment]
Great!

**Comment by Fish-dev2** [comment]
I dont see it. There's no option anywhere to save the columns. Thanks.
