### ISSUE TITLE
video card search yields no results

### ISSUE THREAD

**Issue by grustinkerbel** [OCSInventory-NG/OCSInventory-ocsreports#343]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system : Debian 9.3

### Server installation method ( Only one choice )
- [ ] RPM Package
- [x] Install SH
- [] Manual installation

### Server informations
Php version : 7.0.19-1
Mysql / Mariadb / Percona version : mariadb-server-10.1                  10.1.26-0+deb9u1
Apache version :  2.4.25-3+deb9u3

### OCS Inventory informations
Ocsreports version : 2.4

### Problem's description
*Describe your problem here*
Video Card Search function returns no results.

Steps to reproduce the issue.
1.)Select Show Video Card Column
2.)Select Search In Column Video Card
3.)Select Search. Providing any search criteria yields no results.

**Comment by charleneauger** [comment]
Hi @grustinkerbel 

Thanks for your feedback but your issue has been already reported.
See : #333 

Regards,
Charlene AUGER
