### ISSUE TITLE
I would like to display on this page the main information of the computer

### ISSUE THREAD

**Issue by my4399** [OCSInventory-NG/OCSInventory-ocsreports#345]
http://demo.ocsinventory-ng.org/index.php?function=visu_computers

I would like to display on this page the main information of the computer

For example, in this page, the computer's hard drive, like ST1000DM003-1SB10C

And monitor model and display k serial number...

**Comment by gillesdubois** [comment]
Hi,

You can use the Show / Hide select to select the columns you want to see.
However, no rework have been planned on this part of the interface.

Regards,
Gilles Dubois.
