### ISSUE TITLE
Error 0 / Failed to parse address "localhost:80:80"

### ISSUE THREAD

**Issue by blinzler** [OCSInventory-NG/OCSInventory-ocsreports#347]
### General informations
Operating system :  container [OCSInventory-Docker-Image fork](https://github.com/blinzler/OCSInventory-Docker-Image)

### OCS Inventory informations
Ocsreports version : 2.4
OCSAgent version: 2.3.1.1

### Problem's description
I generated a offline ocs-inventory file and tried to upload the file, I get the error:

> Error 0 / Failed to parse address "localhost:80:80"

**Comment by eilkh** [comment]
Hello, (_I don't know if it's the right place to write this, but_) I've the same error on OCS 2.4.1 on a Debian 8 with Apache 2.4.10, PHP 5.6.33 and MySQL 5.5.60-0.
Tested with reports generated by Windows and Unix agents.
The Debian is a virtual "Proxmox container" machine.

**Comment by snlou** [comment]
Hello,
I have the same error "Error 0 / Failed to parse address "localhost:80:80".
Did you find a solution ?

Thank you for answer

**Comment by visay** [comment]
Same issue happening with the original stack https://github.com/OCSInventory-NG/OCSInventory-Docker-Stack.

**Comment by gillesdubois** [comment]
Hi,

Please open an issue in docker repository.

Regards,
Gilles Dubois.
