### ISSUE TITLE
Update to XAMPP 7

### ISSUE THREAD

**Issue by mtbadi39** [OCSInventory-NG/OCSInventory-ocsreports#35]
Hi;
XAMPP 7 is out with PHP 7 and MariaDB 10, please update the next release to be compatible.
Thanks.

**Comment by gillesdubois** [comment]
Hello,

This has been added to the ocs roadmap.
The next release is already in a testing state so this won't be fixed for the 2.2
However compatibility issues are on our priority list, a patch will take live soon after the release.

Thanks you for contributing to the ocsinventory project.

Regards, 
Gilles Dubois.
