### ISSUE TITLE
Cannot upload ocslogon.exe to ocsinventory web

### ISSUE THREAD

**Issue by evilars** [OCSInventory-NG/OCSInventory-ocsreports#350]
hi all, 

I have issue when i try to upload my ocslogon.exe to my administrative console.

When i access to Config > Agent the page is totally in blank
![image](https://user-images.githubusercontent.com/35523027/35034001-f976dcfc-fb6c-11e7-828a-2f630d6d8c1d.png)

I checked apache logs and i found this:

 PHP Fatal error:  Cannot redeclare return_bytes() (previously declared in /usr
/share/ocsinventory-reports/ocsreports/require/function_commun.php:704) in /usr/
share/ocsinventory-reports/ocsreports/plugins/main_sections/ms_upload_file/ms_up
load_file.php on line 29, referer: http://172.25.17.47/ocsreports/index.php?func
tion=server_infos

We need upload this file to deploy OCSLogon by GPO.

Please help us!

THANKS!!!

**Comment by gillesdubois** [comment]
Hi,

Please use the template provided when opening an issue ...
We can't help you without knowing basics informations like ocs versions or OS used.

Also, this issue has been already reported and has been solved in the newer versions.

Note : OcsLogon is deprecated consider to use an other way to deploy using GPO.

Regards,
Gilles Dubois.
