### ISSUE TITLE
video card

### ISSUE THREAD

**Issue by thanjiyappanm** [OCSInventory-NG/OCSInventory-ocsreports#352]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system : 

### Server installation method ( Only one choice )
- [ ] RPM Package
- [ ] Install SH
- [ ] Manual installation

### Server informations
Php version : 
Mysql / Mariadb / Percona version : 
Apache version : 

### OCS Inventory informations
Ocsreports version : 

### Problem's description
*Describe your problem here*

**Comment by charleneauger** [comment]
Hi @thanjiyappanm ,

Compared to your title I guess the problem comes from the search with the video card column. An issue already exists on this bug, so I invite you to take a look : #333 

Regards,
Charlene Auger
