### ISSUE TITLE
[OCS 2.4] certaines recherches multi critères font apparaitre les groupes

### ISSUE THREAD

**Issue by TiVince** [OCSInventory-NG/OCSInventory-ocsreports#355]
### General informations
Operating system : 

### Server installation method ( Only one choice )
- [ ] RPM Package
- [x] Install SH
- [ ] Manual installation

### Server informations
Php version :  5.4
Mysql / Mariadb / Percona version : 
Apache version :  2.2

### OCS Inventory informations
Ocsreports version :  2.4

### Problem's description

certaines recherches multi critères retournent en résultat les groupes alors qu il ne devrait y avoir que des machines dans le résultat:

essayer ces recherches sur le site de démo

![voila_capture 2018-01-20_06-40-34_pm](https://user-images.githubusercontent.com/2316483/35186262-a818965a-fe11-11e7-84e4-25ec0064e04c.jpg)

retourne le groupe 'serveurs' dans le résultat

![voila_capture 2018-01-20_06-44-28_pm](https://user-images.githubusercontent.com/2316483/35186299-31851fee-fe12-11e7-9a64-f5e868512d5b.jpg)

retourne le groupe 'serveurs' dans le résultat

![voila_capture 2018-01-20_06-48-53_pm](https://user-images.githubusercontent.com/2316483/35186332-ac389fb8-fe12-11e7-97b7-c52a9d961681.jpg)

retourne uniquement le groupe 'Serveurs'

![voila_capture 2018-01-20_07-09-12_pm](https://user-images.githubusercontent.com/2316483/35186499-7a575144-fe15-11e7-805b-bb3f234f5495.jpg)

retourne le groupe 'serveurs' dans le résultat

**Comment by charleneauger** [comment]
Bonjour @TiVince ,

Ce bug a été résolu avec la refonte de la multicritères :)

Cordialement,
Charlène Auger
