### ISSUE TITLE
Search problem when using Registry parameter

### ISSUE THREAD

**Issue by Laurent-1971** [OCSInventory-NG/OCSInventory-ocsreports#357]
### General informations
Operating system : CentOS Linux 7 (Core) 3.10.0-693.11.6.el7.x86_64

### Server installation method ( Only one choice )
- [ ] RPM Package
- [X] Install SH
- [ ] Manual installation

### Server informations
Php version : 5.6.33
Mysql / Mariadb / Percona version : MySQL Community Server (GPL) version 5.7.21
Apache version : ?

### OCS Inventory informations
Ocsreports version : 2.4

### Problem's description

- Inventory / Search with various criteria
- Choose "Registry Key Name" as the parameter
- When you clic in the value field, the calendar appears immediately and it's not possible to close it without having his date value inserted.

Issue is here with all browsers I tried (Chromium, Firefox, IE...).

**Comment by charleneauger** [comment]
Hi @Laurent-1971 ,

This bug is already reported in the issue #336 .  A correction has been proposed and is pending validation (see PR: #353 ).

Regards,
Charlene Auger
