### ISSUE TITLE
Download link problem when using Registry parameter

### ISSUE THREAD

**Issue by Laurent-1971** [OCSInventory-NG/OCSInventory-ocsreports#358]
### General informations
Operating system : CentOS Linux 7 (Core) 3.10.0-693.11.6.el7.x86_64

### Server installation method ( Only one choice )
- [ ] RPM Package
- [X] Install SH
- [ ] Manual installation

### Server informations
Php version : 5.6.33
Mysql / Mariadb / Percona version : MySQL Community Server (GPL) version 5.7.21
Apache version : ?

### OCS Inventory informations
Ocsreports version : 2.4

### Problem's description

- Inventory / Search with various criteria
- Choose "Registry Key Name" as the parameter
- Show the "Registry Key Name" and the "Registry Key Value" columns
- Clic one of the "Download" links
- The export.csv downloaded contains the columns but with wrong values

**Comment by gillesdubois** [comment]
Hi,

The multi seach has been completly reworked and is no longer impacted by this problem.
Thx for your contribution.

Regards,
Gilles Dubois.
