### ISSUE TITLE
PHP7 - installer warning

### ISSUE THREAD

**Issue by AnaelMobilia** [OCSInventory-NG/OCSInventory-ocsreports#36]
Hello,

During the installation on a centos 7 server / php-fpm 7 : for ocsinventory 2.1.2
 Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; language has a deprecated constructor in /usr/share/ocsinventory-reports/ocsreports/require/fichierConf.class.php on line 14

**Comment by gillesdubois** [comment]
Hi !

My awnser will be the same as your other issue.
https://github.com/OCSInventory-NG/OCSInventory-ocsreports/issues/37
Expect a fix within 3-4 week in order to have php 7 compatibility on OCS

Thanks for contributing to the project.
Regards, Gilles Dubois.

**Comment by gillesdubois** [comment]
Hi @AnaelMobilia, A lot of tests has been made on the 2.2 (which gonna be released soon) and this one work perfectly with php7.

So if you need ocsinventory and php 7 is a mandatory, i think you should upgrade to ocs 2.2
A news will be available soon with the download link.
