### ISSUE TITLE
OcsInventory 2.3.1 / Apache 2.4/ Debian 8 pas d'accès à l'interface web

### ISSUE THREAD

**Issue by yannisker** [OCSInventory-NG/OCSInventory-ocsreports#360]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system : Debian 8 / noyau 3.16.0.5

### Server installation method ( Only one choice )
- [ ] RPM Package
- [x] Install SH
- [ ] Manual installation

### Server informations
Php version : php 5.6.33
Mysql / Mariadb / Percona version : 5.5.59
Apache version : 2.4.10

### OCS Inventory informations
Ocsreports version : 2.3.1

### Problem's description
*Describe your problem here*
Bonjour
Alors voilà mon problème, j'ai depuis installer ocsinventory 2.3.1 sur ma debian 7 avec un apache 2.2,  puis par la suite j'ai upgrader ma debian en version 8 avec par la même occasion mon apache en 2.4 et depuis je n'ai plus d'accès à l'interface web d'ocsinventory-reports.

J'ai remarqué que la conf d'apache2 en version 2.2 est bien différente de la version 2.4, et donc que les redirections de liens ocsreports dans le fichier de configuration d'apache n'est pas fonctionnel.

merci de votre aide.

**Comment by gillesdubois** [comment]
Bonjour,

Je vous conseil d'installer la nouvelle version (2.4) et de relancer le setup sur votre machine.
L'assistant OCS s'occupera de la mise a jour du serveur et de la gestion des versions des services

Gilles Dubois.

**Comment by yannisker** [comment]
Je viens d'effectuer l'installation de la version 2.4 d'ocs mais j'ai toujours le même problème, le serveur est bien detecter a l'adresse 192.168.1.11, mais si j'entre sur le chemin d'ocs (192.168.1.11/ocsreports) je n'ai toujours pas d'accès.

La seul erreur que je constate durant l'installation est que le module Apache::SOAP est manquant (j'ai tenté plusieurs fois de l'installer mais au final durant l'installation il m'est toujours dit qu'il n'est pas installer "Apache2::SOAP is not installed). Je ne sais pas si ce module est obligatoire)

**Comment by gillesdubois** [comment]
Avez vous activer la configuration Apache en utilisant a2enconf ?

**Comment by yannisker** [comment]
Je ne saurais vous dire si la configuration Apache est correctement activer, pouvez-vous me donner la marche a suivre ?

**Comment by gillesdubois** [comment]
Ce problème n'est pas lié a OCS, je vous conseil de vous rapprocher de la documentation Debian :
https://manpages.debian.org/jessie/apache2/a2enconf.8.en.html

**Comment by yannisker** [comment]
Ok j'ai lu sur un autre sujet du forum comment résoudre le problème, il suffit simplement d'activer la configuration d'apache2 pour ocsinventory en entrant la commande : 
- a2enconf ocsinventory-reports.conf
- /etc/init.d/apache2 restart

et le problème est régler, je peux accéder à l'interface web

👍
