### ISSUE TITLE
Hitting Enter in "Search With Various Criteria" appears to cause the form to reset

### ISSUE THREAD

**Issue by PDolloff** [OCSInventory-NG/OCSInventory-ocsreports#365]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system : Centos 7

### Server installation method ( Only one choice )
- [ x] RPM Package
- [ ] Install SH
- [ ] Manual installation

### Server informations
Php version : 5.4.16
Mysql / Mariadb / Percona version : MariaDB Server version 5.5.56-MariaDB
Apache version : 2.4.6

### OCS Inventory informations
Ocsreports version : 2.3.1 and above

### Problem's description
Hello

Some of the users noticed that, if they went to "Search With Various Criteria" added a parameter, typed in a value and then pressed Enter on the keyboard, the form would reset and not perform the search.

The button that removes a parameter has not type specified, so when a user uses the enter key to submit the form, that button is used as the submit button, which removes the parameter.

Changing the file require/function_search.php fixes the problem:

Original: 

`echo "<button class='btn btn-danger btn-block' alt='".$l->g(41)."' onclick='pag(\"".$id_field."\",\"delfield\",\"".$form_name."\");'><span class='glyphicon glyphicon-remove delete-span delete-span-xs' style='color:white'></span></button>";
`

New:

`echo "<button type='button' class='btn btn-danger btn-block' alt='".$l->g(41)."' onclick='pag(\"".$id_field."\",\"delfield\",\"".$form_name."\");'><span class='glyphicon glyphicon-remove delete-span delete-span-xs' style='color:white'></span></button>";
`

**Comment by StCyr** [comment]
Je confirme que ça marche aussi pour moi avec Ocsreports 2.4 sous Ubuntu 16.04.3 et avec Firefox 58.0.2

**Comment by StCyr** [comment]
Merci pour la solution @PDolloff

**Comment by Adrianodl** [comment]
This bug still happens in version 2.4, but updating the line described by @PDolloff solves the problem. Thanks!

**Comment by TiVince** [comment]
works like a charm. thx you

**Comment by gillesdubois** [comment]
Hi,

This problem has been fixed with the issue referenced above.

Regards,
Gilles Dubois.

**Comment by PDolloff** [comment]
Thank You Gilles! Love this software
