### ISSUE TITLE
Administrative Data is not visible after upgrade

### ISSUE THREAD

**Issue by sokatra** [OCSInventory-NG/OCSInventory-ocsreports#366]
### General informations
Operating system : 
centos-release-6-9.el6.12.3.x86_64

### Server installation method ( Only one choice )
- [ ] RPM Package
- [ x] Install SH
- [ ] Manual installation

### Server informations
Php version : 5.5.38
Mysql / Mariadb / Percona version : 
5.5.59
Apache version : 
2.2.15

### OCS Inventory informations
2.3.1
Ocsreports version : 

### Problem's description
after upgrade from OCS-Inventory 2.2.1 to 2.3.1 - labeled  buttons are not labeled anymore after updgrade and the buttons which are checked before are not checked anymore

in 2.2
![github2](https://user-images.githubusercontent.com/17703360/36208507-7c69f3e6-1199-11e8-9730-1cf1fc7a0391.PNG)

in 2.3.1
![github1](https://user-images.githubusercontent.com/17703360/36208669-ea07faf6-1199-11e8-8e36-9fe873c3db11.PNG)

![github](https://user-images.githubusercontent.com/17703360/36208832-599a2f4c-119a-11e8-9fe4-3457f8834baa.PNG)

**Comment by gillesdubois** [comment]
Hi,

Can you upgrade to 2.4 to test if this bug still affect you on newer versions ?

Regards,
Gilles Dubois.

**Comment by sokatra** [comment]
Hy, i already tested this with version 2.4, but i it looks the same. in production environment i use version 2.1.2 because i can't migrate to newer version with this bug.

**Comment by sokatra** [comment]
Version 2.4
![2_4_0](https://user-images.githubusercontent.com/17703360/36373472-8de1f056-1568-11e8-8331-6f9a4cbe5ab4.PNG)
all the checkboxes are missing in this version - in 2.2 the checkboxes are visible

**Comment by sokatra** [comment]
all pictures are showing the same computer

**Comment by sokatra** [comment]
It is really frustrating to. Is there any easy way to keep the data ?
In version 2.2 (the last version where all checkboxes working) i tried to create new fields (Checkboxes) and with a search via various critera i tried to copy the information via mass processing to the newly created fields.

But mass processing does not work for my new checkboxes.
All new checkboxes are unchecked even after mass processing.
To verify that mass processing is working, i changed the TAG - form NA to something other. This works

**Comment by sokatra** [comment]
I installed ocs Inventory 2.3.1 in debian 8 and imported the 2.2 Database to verify that no perl component is the root cause.
But i musst confess that the problem is the same as reported. In 2.3.1 i also can't enable the unamed checkboxes.
2.4 also doesn't work right now
