### ISSUE TITLE
le critère "DIFFERENT" ne fonctionne pas correctement dans la fonction "search with various criteria"

### ISSUE THREAD

**Issue by StCyr** [OCSInventory-NG/OCSInventory-ocsreports#369]
### General informations

http://demo.ocsinventory-ng.org

### Problem's description

**Comportement observé:**

Sur le site http://demo.ocsinventory-ng.org, dans la fonctionnalité "search with various criteria", si vous cherchez, par exemple, les machines n'ayant pas  le logiciel "Mise à jour de sécurité pour Windows Server 2003 (article KB2115168)" vous trouvez 40 résultats. Mais, si vous cherchez les machines n'ayant pas  le logiciel "BLABLABLA", OCSI vous dit "NO SOFTWARE CORRESPONDING TO THE SEARCH" et ne vous retourne aucun résultat 

**Comportement attendu:**

OCSI ne devrait pas nous dire "NO SOFTWARE CORRESPONDING TO THE SEARCH" et devrait retourner l'ensemble des machines de l'inventaire, vu qu'aucune machine n'a le logiciel "BLABLABLA" 

**Informations complémentaires:**

L'exemple donné ci-dessus n'a pas beaucoup de sens. Mais il n'est là que pour illustrer le propos. Dans la vraie vie, le comportement observé pose problème lorsqu'on recherche par exemple les machines n'ayant ni le logiciel "Mise à jour de sécurité pour Windows Server 2003 (article KB2115168)" ni le logiciel "BLABLABLA". Dans ce cas, OCSI devrait au final nous retourner 12 résultats mais il en retourne en fait 40 (voir chapitre "Reproduction" ci-dessous).

**Reproduction:**

1. Sur le site http://demo.ocsinventory-ng.org, ouvrez la page "Search with various criteria"
2. Sélectionnez le critère de recherche suivant: "Software:Name" DIFFERENT "Mise à jour de sécurité pour Windows Server 2003 (article KB2296011)"
3. Cliquez sur "Search" et regardez OCSI vous retourner 12 résultats.
4. Ajouter le critère de recherche suivant: "Software:Name" DIFFERENT "BLABLA" avec un critère de combinaison avec le critère précédent "AND" 
5. Cliquez sur "Search" et regardez OCSI vous répondre "NO SOFTWARE CORRESPONDING TO THE SEARCH" et vous retourner 40 résultats.

**Observations complémentaires:**

Attention, l'ordre des critères est important!

Si "Software:Name" DIFFERENT "Mise à jour de sécurité pour Windows Server 2003 (article KB2296011)" est le premier critère et "Software:Name" DIFFERENT "BLABLA" le second, vous obtenez 40 résultats.

Si "Software:Name" DIFFERENT "BLABLA" est le premier critère et "Software:Name" DIFFERENT "Mise à jour de sécurité pour Windows Server 2003 (article KB2296011)" le second, vous obtenez 0 résultats.

Si vous exécutez les étapes décrites dans le chapitre "Reproduction" en mode DEBUG, vous verrez qu'à la fin de l'étape 5, OCSI semble avoir laissé tomber votre dernier critère: La requête relative au software "BLABLA" n'apparait pas du tout dans les messages de débogage.

Si vous ré-organisez vos critères de recherche en mettant le critère "Software:Name" DIFFERENT "BLABLA"  en premier, aucune requête n'apparait dans les messages de débogage.

**Comment by gillesdubois** [comment]
Bonjour,

Ce problème à été corrigé dans la pull request référencée ci-dessus.

Cordialement,
Gilles Dubois.
