### ISSUE TITLE
PHP7 - ocsreports compatibility issue

### ISSUE THREAD

**Issue by AnaelMobilia** [OCSInventory-NG/OCSInventory-ocsreports#37]
Hello,
Server : centos 7 / php-fpm 7
ocsinventory 2.1.2

On the main page :

Deprecated: mysql_connect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead in /usr/share/ocsinventory-reports/ocsreports/backend/require/connexion.php on line 10

**Comment by gillesdubois** [comment]
Hello,

We are aware of the situation with the new php 7 version.
As of now these deprecated function has not been removed ... you can still use ocs even with this warning. (or downgrade php to 5.X)

A patch will be commited for new version for php7 compatibility
A news on our web site will be available when the patch will come out.

Thanks for contributing to the project.
Regards, Gilles Dubois.

**Comment by gillesdubois** [comment]
Hi @AnaelMobilia, A lot of tests has been made on the 2.2 (which gonna be released soon) and this one work perfectly with php7.

So if you need ocsinventory and php 7 is a mandatory, i think you should upgrade to ocs 2.2
A news will be available soon with the download link.
