### ISSUE TITLE
search for a regkey which does exist, but different from xxx

### ISSUE THREAD

**Issue by sokatra** [OCSInventory-NG/OCSInventory-ocsreports#373]
### General informations
Operating system : 
CentOS 7
### Server installation method ( Only one choice )
- [ ] RPM Package
-  x Install SH
- [ ] Manual installation

If i search for a registry key which is different from for example "aaaaaa" - i will get results for all computers instead of only computers where this specific key exist.

**Comment by gillesdubois** [comment]
Hi,

Please follow the issue template provided.
We can't help you if you provide not all the informations.

Regards,
Gilles Dubois.
