### ISSUE TITLE
registry search for different than xxxx returns all computers

### ISSUE THREAD

**Issue by sokatra** [OCSInventory-NG/OCSInventory-ocsreports#375]
i now used you 2.4 demo to verify registry search 
![capture0](https://user-images.githubusercontent.com/17703360/36483411-550bbdde-1716-11e8-90e0-1019b3204a29.PNG)

if i search for example for

version de Filezilla different than 2222 - the various search return all 44 computers - should't it return only computers where this registry path exist, but with a key different to 2222 ?
I sometimes search for registry settings where i only want to now if this path exist, but only 1 of xxx computers has this specific registry key. So with various criteria search i am not able to to this.
![capture1](https://user-images.githubusercontent.com/17703360/36483359-2e92fb9a-1716-11e8-8b4f-313872fa52dd.PNG)
![capture2](https://user-images.githubusercontent.com/17703360/36483363-3089c9b0-1716-11e8-9d78-677ce9382b6b.PNG)

**Comment by gillesdubois** [comment]
Hi,

This issue has been resolved in the new multi search.
The pull request is referenced above.

Regards,
Gilles Dubois.
