### ISSUE TITLE
[OCS 2.4] problème de Recherche multicritère avec ENTRE sous certains navigateurs

### ISSUE THREAD

**Issue by TiVince** [OCSInventory-NG/OCSInventory-ocsreports#377]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system : 

### Server installation method ( Only one choice )
- [ ] RPM Package
- [X] Install SH
- [ ] Manual installation

### Server informations
Php version : 5.4 
Mysql / Mariadb / Percona version : 5.1 
Apache version : 2.2 

### OCS Inventory informations
Ocsreports version : 2.4

### Problem's description
Avec un navigateur **Chrome** ou **Safari**, lorsque l'on fait une recherche sur le critère **Processeur(s) (old): Vitesse CPU (MHz)** ou **Système: Mémoire** et que l'on sélectionne ENTRE dans la première zone de sélection , on a pas l'affichage de la seconde zone de saisie  pour saisir une plage.

![voila_capture 2018-03-02_11-35-35_am](https://user-images.githubusercontent.com/2316483/36895448-344c293a-1e0f-11e8-990c-a37e9b4f09d5.jpg)

cela provient du fait que les événements '**onClick**' dans les balises html **< option >** ne sont pas standards et non gérés par ces 2 navigateurs (et apparemment IE10 aussi ) : le gestionnaire on click de l'option séléctionnée n'est jamais exécuté, la deuxième zone de saisie n'apparait pas.
Pour une gestion compatible avec tous les navigateurs, il faudrait gérer l evenement ´change ‘ sur la balise < select >

dans cet exemple on voit tous les evenements on click au niveau des < option > 

`<select name="SelComp-HARDWARE-MEMORY-0" id="SelComp-HARDWARE-MEMORY-0" class="form-control"><option value="exact" onclick="document.getElementById(&quot;FieldInput2-HARDWARE-MEMORY-0&quot;).style.display=&quot;none&quot;;" class="down">EXACTEMENT</option><option value="ressemble" onclick="document.getElementById(&quot;FieldInput2-HARDWARE-MEMORY-0&quot;).style.display=&quot;none&quot;;" class="hi">RESSEMBLE</option><option value="diff" onclick="document.getElementById(&quot;FieldInput2-HARDWARE-MEMORY-0&quot;).style.display=&quot;none&quot;;" class="down">DIFFERENT</option><option value="small" onclick="document.getElementById(&quot;FieldInput2-HARDWARE-MEMORY-0&quot;).style.display=&quot;none&quot;;" class="hi">PLUS PETIT</option><option value="tall" onclick="document.getElementById(&quot;FieldInput2-HARDWARE-MEMORY-0&quot;).style.display=&quot;none&quot;;" class="down">PLUS GRAND</option><option value="between" onclick="document.getElementById(&quot;FieldInput2-HARDWARE-MEMORY-0&quot;).style.display=&quot;inline&quot;;" class="hi">ENTRE</option></select>`

**Comment by gillesdubois** [comment]
Hi,

This bug has been resolved with the multi search rework.

Regards,
Gilles Dubois.
