### ISSUE TITLE
[enhancement] recherche multicritère : afficher un critère de recherche sur une seule ligne

### ISSUE THREAD

**Issue by TiVince** [OCSInventory-NG/OCSInventory-ocsreports#378]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system : 

### Server installation method ( Only one choice )
- [ ] RPM Package
- [ ] Install SH
- [ ] Manual installation

### Server informations
Php version : 
Mysql / Mariadb / Percona version : 
Apache version : 

### OCS Inventory informations
Ocsreports version : 2.4

### Problem's description

les recherches multicritère prennent beaucoup de place à l'écran en raison de l'affichage d'une zone de saisie / bouton par ligne (soit de 3 à 6 lignes pour un seul critère).
Est il envisageable d'afficher un critère sur une seule ligne (comme sous ocs v2.0.5) ?

Cela semble réalisable avec bootstrap et pourrait ressembler aux copies d'écran ci dessous.

Les modifications seraient limitées à la modification de la fonction **show_ligne()** de **require/function_search.php** et à l'utilisation du composant Jquery/bootstrap  **boostrap-select** cf  
https://silviomoreto.github.io/bootstrap-select/

**Affichage écran desktop:**
![fireshot capture 001 - ocs inventory - http___192 168 1 26_ocsreports_index php_function visu_search](https://user-images.githubusercontent.com/2316483/36898224-2dc71c86-1e1a-11e8-99a5-a3c25ad562a7.png)

**Affichage écran  petite résolution:**

![fireshot capture 002 - ocs inventory - http___192 168 1 26_ocsreports_index php_function visu_search](https://user-images.githubusercontent.com/2316483/36898238-424f655a-1e1a-11e8-81fb-b97d53edf2e4.png)

**versus** 
![ocs inventory-10_153_219_182_ocsreports__function visu_search](https://user-images.githubusercontent.com/2316483/37454347-9aae9048-283a-11e8-9ebd-b3ef153146d1.jpg)

**Comment by TiVince** [comment]
Je tiens le code à votre disposition. Malheureusement etant sur une plateforme php 5.3 en production. Je ne peux pas contribuer via github.

**Comment by gillesdubois** [comment]
Bonjour @TiVince,

La PR référencée ci-dessus est un rework complet de la multi-crtière. Celle-ci n'était plus maintenable de manière efficiente. Nous en avons profité pour prendre en compte ta demande et les affichages sont désormais sur une ligne.

Malheureusement, les technologies utilisées ne te permettront pas une mise en prod en PHP 5.3 (php 5.4 mini, 5.6+ recommandé)

Cordialement,
Gilles Dubois.

**Comment by TiVince** [comment]
Bonjour @gillesdubois 
J'ai regardé et ça à l'air très sympa en effet et beaucoup plus évolutif .

Très honnêtement jusqu'à maintenant j'ai réussi à tout backporté en php 5.3.7 (y compris ce PR) :
99% des problèmes viennent de la déclaration des tableaux sous la forme  [ ] au lieu de array()
et 1 cas d accès aux index de tableaux en sortie de fonctions
d'où ma demande #305 (une sorte de compatibilité en 'best effort' sans autre contrainte)
sur un nombre trés limité de pages : 
plugins/main_sections/ms_teledeploy/ms_tele_package.php 
plugins/main_sections/ms_all_soft/ms_all_soft.php  
plugins/main_sections/ms_computer/ms_computer_views.php 
require/function_commun.php 
plugins/main_sections/ms_groups/ms_group_show.php

le seul problème que j'ai eu concerne l'utilisation de $this dans les closures sur les pages  
require/tables/ActionsColumn.php                          
require/tables/Column.php                                          
require/tables/CheckboxColumn.php 

que j'ai  contourné  en me basant sur 
http://us3.php.net/manual/en/functions.anonymous.php#98384[](http://us3.php.net/manual/en/functions.anonymous.php#98384)
mais là c'est plus contraignant.

cordialement
Vincent
