### ISSUE TITLE
[OCS 2.4] Upgrade from OCS 2.3  "write error"

### ISSUE THREAD

**Issue by jclesault** [OCSInventory-NG/OCSInventory-ocsreports#379]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system : Debain 9.1

### Server installation method ( Only one choice )
- [ ] RPM Package
- [X ] Install SH
- [ ] Manual installation

### Server informations
Php version : 7.0.19-1
Mariadb version : 10.1.26-MariaDB-0+deb9u1 - Debian 9.1 
Apache version : 2.4.25

2 Servers : 1 communication server and 1 Administration server

### OCS Inventory informations
Ocsreports version : 2.3

### Problem's description
Unable to upgrade the administration server from OCS 2.3 to OCS 2.4 with the setup.sh script

I have an error : *** ERROR: Unable to write /etc/apache2/conf-available/ocsinventory-reports.conf, please look at error in /tmp/OCSNG_UNIX_SERVER_2.4/ocs_server_setup.log and fix !

### Here the process : 

root@mtrv-ocs:/tmp/OCSNG_UNIX_SERVER_2.4# ./setup.sh

+----------------------------------------------------------+
|                                                          |
|  Welcome to OCS Inventory NG Management server setup !   |
|                                                          |
+----------------------------------------------------------+

Trying to determine which OS or Linux distribution you use
+----------------------------------------------------------+
| Checking for Apache web server binaries !                             |
+----------------------------------------------------------+

CAUTION: If upgrading Communication server from OCS Inventory NG 1.0 RC2 and
previous, please remove any Apache configuration for Communication Server!

Do you wish to continue ([y]/n)?y
Assuming Communication server 1.0 RC2 or previous is not installed
on this computer.

Starting OCS Inventory NG Management server setup from folder /tmp/OCSNG_UNIX_SERVER_2.4
Storing log in file /tmp/OCSNG_UNIX_SERVER_2.4/ocs_server_setup.log

+----------------------------------------------------------+
| Checking for database server properties...                      |
+----------------------------------------------------------+

Your MySQL client seems to be part of MySQL version 10.1.
Your computer seems to be running MySQL 4.1 or higher, good ;-)

Which host is running database server [localhost] ?
OK, database server is running on host localhost ;-)

On which port is running database server [3306] ?
OK, database server is running on port 3306 ;-)

+----------------------------------------------------------+
| Checking for Apache web server daemon...                              |
+----------------------------------------------------------+

Where is Apache daemon binary [/usr/sbin/apache2ctl] ?
OK, using Apache daemon /usr/sbin/apache2ctl ;-)

+----------------------------------------------------------+
| Checking for Apache main configuration file...                  |
+----------------------------------------------------------+

Where is Apache main configuration file [/etc/apache2/apache2.conf] ?
OK, using Apache main configuration file /etc/apache2/apache2.conf ;-)

+----------------------------------------------------------+
| Checking for Apache user account...                                    |
+----------------------------------------------------------+

Which user account is running Apache web server [www-data] ?
OK, Apache is running under user account www-data ;-)

+----------------------------------------------------------+
| Checking for Apache group...                                                  |
+----------------------------------------------------------+

Which user group is running Apache web server [www-data] ?
OK, Apache is running under users group www-data ;-)

+----------------------------------------------------------+
| Checking for Apache Include configuration directory...   |
+----------------------------------------------------------+

Setup found Apache Include configuration directory in
/etc/apache2/conf-available.
Setup will put OCS Inventory NG Apache configuration in this directory.
Where is Apache Include configuration directory [/etc/apache2/conf-available] ?
OK, Apache Include configuration directory /etc/apache2/conf-available found ;-)

+----------------------------------------------------------+
| Checking for PERL Interpreter...                                              |
+----------------------------------------------------------+

Found PERL interpreter at </usr/bin/perl> ;-)
Where is PERL interpreter binary [/usr/bin/perl] ?
OK, using PERL interpreter /usr/bin/perl ;-)

Do you wish to setup Communication server on this computer ([y]/n)?n

Do you wish to setup Administration Server (Web Administration Console)
on this computer ([y]/n)?y

+----------------------------------------------------------+
|    Checking for Administration Server directories...     |
+----------------------------------------------------------+

CAUTION: Setup now install files in accordance with Filesystem Hierarchy
Standard. So, no file is installed under Apache root document directory
(Refer to Apache configuration files to locate it).
If you're upgrading from OCS Inventory NG Server 1.01 and previous, YOU
MUST REMOVE (or move) directories 'ocsreports' and 'download' from Apache
root document directory.
If you choose to move directory, YOU MUST MOVE 'download' directory to
Administration Server writable/cache directory (by default
/var/lib/ocsinventory-reports), especially if you use deployment feature.

Do you wish to continue ([y]/n)?y
Assuming directories 'ocsreports' and 'download' removed from
Apache root document directory.

Where to copy Administration Server static files for PHP Web Console
[/usr/share/ocsinventory-reports] ?
OK, using directory /usr/share/ocsinventory-reports to install static files ;-)

Where to create writable/cache directories for deployment packages,
administration console logs, IPDiscover and SNMP [/var/lib/ocsinventory-reports] ?
OK, writable/cache directory is /var/lib/ocsinventory-reports ;-)

+----------------------------------------------------------+
|         Checking for required Perl Modules...            |
+----------------------------------------------------------+

Checking for DBI PERL module...
Found that PERL module DBI is available.
Checking for DBD::mysql PERL module...
Found that PERL module DBD::mysql is available.
Checking for XML::Simple PERL module...
Found that PERL module XML::Simple is available.
Checking for Net::IP PERL module...
Found that PERL module Net::IP is available.

+----------------------------------------------------------+
|      Installing files for Administration server...       |
+----------------------------------------------------------+

Creating PHP directory /usr/share/ocsinventory-reports/ocsreports.
Copying PHP files to /usr/share/ocsinventory-reports/ocsreports.
Fixing permissions on directory /usr/share/ocsinventory-reports/ocsreports.
Creating database configuration file /usr/share/ocsinventory-reports/ocsreports/dbconfig.inc.php.
Creating IPDiscover directory /var/lib/ocsinventory-reports/ipd.
Fixing permissions on directory /var/lib/ocsinventory-reports/ipd.
Creating packages directory /var/lib/ocsinventory-reports/download.
Fixing permissions on directory /var/lib/ocsinventory-reports/download.
Creating snmp mibs directory /var/lib/ocsinventory-reports/snmp.
Fixing permissions on directory /var/lib/ocsinventory-reports/snmp.
Creating Administration server log files directory /var/lib/ocsinventory-reports/logs.
Fixing permissions on directory /var/lib/ocsinventory-reports/logs.
Creating Administration server scripts log files directory /var/lib/ocsinventory-reports/scripts.
Fixing permissions on directory /var/lib/ocsinventory-reports/scripts.
Configuring IPDISCOVER-UTIL Perl script.
Installing IPDISCOVER-UTIL Perl script.
Fixing permissions on IPDISCOVER-UTIL Perl script.
Writing Administration server configuration to file /etc/apache2/conf-available/ocsinventory-reports.conf
chown: cannot access '/etc/ocsinventory-server/plugins': No such file or directory
chown: cannot access '/etc/ocsinventory-server/perl': No such file or directory
*** ERROR: Unable to write /etc/apache2/conf-available/ocsinventory-reports.conf, please look at error in /tmp/OCSNG_UNIX_SERVER_2.4/ocs_server_setup.log and fix !**

Installation aborted !
root@mtrv-ocs:/tmp/OCSNG_UNIX_SERVER_2.4#

### Here the log file : 

Starting OCS Inventory NG Management server setup on 2018-02-15-11-52-42
from folder /tmp/OCSNG_UNIX_SERVER_2.4
Storing log in file /tmp/OCSNG_UNIX_SERVER_2.4/ocs_server_setup.log

$============================================================
$Checking OCS Inventory NG Management Server requirements...
$============================================================
Checking for database server properties
MySQL client distribution version 10.1.
Computer seems to be running MySQL 4.1 or higher
Database server is running on host localhost
Database server is running on port 3306
Checking for Apache web server daemon
Found Apache daemon /usr/sbin/apache2ctl
Using Apache daemon /usr/sbin/apache2ctl
Checking for Apache main configuration file
Found Apache HTTPD_ROOT /etc/apache2
Found Apache SERVER_CONFIG_FILE apache2.conf
Found Apache main configuration file /etc/apache2/apache2.conf
Using Apache main configuration file /etc/apache2/apache2.conf
Checking for Apache user account
Found Apache user account www-data
Using Apache user account www-data
Checking for Apache group
Found Apache user group www-data
Using Apache user group www-data
Checking for Apache Include configuration directory
Found Apache Include configuration directory /etc/apache2/conf-available
Using Apache Include configuration directory /etc/apache2/conf-available
Checking for PERL Interpreter
Found PERL interpreter at </usr/bin/perl>
Using PERL interpreter /usr/bin/perl

$============================================================
$Installing Administration server
$============================================================
Checking for Administration Server directories...
Using directory /usr/share/ocsinventory-reports for static files
Using /var/lib/ocsinventory-reports as writable/cache directory
Checking for DBI PERL module
PERL module DBI is available
Checking for DBD::mysql PERL module
PERL module DBD::mysql is available
Checking for XML::Simple PERL module
PERL module XML::Simple is available
Checking for Net::IP PERL module
PERL module Net::IP is available
Creating PHP directory /usr/share/ocsinventory-reports/ocsreports
Copying PHP files to /usr/share/ocsinventory-reports/ocsreports
Fixing permissions on directory /usr/share/ocsinventory-reports/ocsreports
Creating database configuration file /usr/share/ocsinventory-reports/ocsreports/dbconfig.inc.php
Creating IPDiscover directory /var/lib/ocsinventory-reports/ipd
Fixing permissions on directory /var/lib/ocsinventory-reports/ipd
Creating packages directory /var/lib/ocsinventory-reports/download
Fixing permissions on directory /var/lib/ocsinventory-reports/download
Creating snmp mibs directory /var/lib/ocsinventory-reports/snmp
Fixing permissions on directory /var/lib/ocsinventory-reports/snmp
Creating Administration server log files directory /var/lib/ocsinventory-reports/logs
Fixing permissions on directory /var/lib/ocsinventory-reports/logs
Creating Administration server scripts log files directory /var/lib/ocsinventory-reports/scripts
Fixing permissions on directory /var/lib/ocsinventory-reports/scripts
Configuring IPDISCOVER-UTIL Perl script (ed ipdiscover-util.pl)
Installing IPDISCOVER-UTIL Perl script
Fixing permissions on IPDISCOVER-UTIL Perl script
Configuring Apache web server (file ocsinventory-reports.conf)
******** Begin updated ocsinventory-reports.conf.local ***********
$#############################################################################$###
$#
$# OCS Inventory NG Administration Server
$#
$# Copyleft 2008 OCS Inventory NG Team
$# Web: http://www.ocsinventory-ng.org
$#
$# This code is open source and may be copied and modified as long as the source
$# code is always made freely available.
$# Please refer to the General Public Licence http://www.gnu.org/ or Licence.txt
$#############################################################################$###

$#
$# ANY CHANGE ON THIS FILE REQUIRES APACHE RESTART TO TAKE EFFECT
$#

$#############################################################################$###
$# Administration console public pages
$# 
$# Alias used to put Administration Server static page (typically PHP) outside
$# Apache document root directory
$#
Alias /ocsreports /usr/share/ocsinventory-reports/ocsreports

<Directory /usr/share/ocsinventory-reports/ocsreports>
    $# By default, users can use console from everywhere
      <IfModule mod_authz_core.c>
        # Apache 2.4
        Require all granted
	  </IfModule>
	  <IfModule !mod_authz_core.c>
        Order deny,allow
        Allow from all
      </IfModule>
    Options Indexes FollowSymLinks
    DirectoryIndex index.php
    AllowOverride Options
    
    $# Uncomment following to force use of HTTPS in Administration Server
    $#SSLRequireSSL
    
    $# PHP tuning (not working on all distribution, use php.ini instead)
    <IfModule mod_php5.c>
        AddType application/x-httpd-php .php
        php_flag file_uploads           on
        $# Some PHP tuning for deployment feature up to 8 MB
        $# post_max_size must be greater than upload_max_filesize
        $# because of HTTP headers 
        php_value post_max_size         101m
        php_value upload_max_filesize   100m
        $# You may have to uncomment following on errors
        $#php_value max_execution_time -1
        $#php_value max_input_time -1
        
       $ # Uncomment following if you need to specify a mysql socket
    	$#php_value mysql.default_socket "path/to/mysql/unix/socket"

        $#!! Mandatory !! : set magic_quotes_gpc to off (to make ocsreports works correctly)
        php_flag magic_quotes_gpc      off
    </IfModule>
   $ # Duplicate for php7 compatibility
    <IfModule mod_php7.c>
        AddType application/x-httpd-php .php
        php_flag file_uploads           on
        $# Some PHP tuning for deployment feature up to 8 MB
        $# post_max_size must be greater than upload_max_filesize
        $# because of HTTP headers 
        php_value post_max_size         101m
        php_value upload_max_filesize   100m
        $# You may have to uncomment following on errors
        $#php_value max_execution_time -1
        $#php_value max_input_time -1
        
        $# Uncomment following if you need to specify a mysql socket
    	$#php_value mysql.default_socket "path/to/mysql/unix/socket"

        #!! Mandatory !! : set magic_quotes_gpc to off (to make ocsreports works correctly)
        php_flag magic_quotes_gpc      off
    </IfModule>

    # Uncomment following to allow HTTP body request up to 4 MB
    # instead default 512 KB
    #LimitRequestBody 4194304

</Directory>

$#############################################################################$###
$# Deployment packages download area
$# 
$# Alias to put Deployment package files outside Apache document root directory
$#
<Directory /var/lib/ocsinventory-reports/download>
   <IfModule mod_authz_core.c>
     $# Apache 2.4
     Require all granted
   </IfModule>
   <IfModule !mod_authz_core.c>
     Order deny,allow
     Allow from all
   </IfModule>
</Directory>
Alias /download /var/lib/ocsinventory-reports/download

$#############################################################################$###
$# Snmp communities area
$#
$# Alias to put Snmp custom Mibs files outside Apache document root directory
$#
<Directory /var/lib/ocsinventory-reports/snmp>
   <IfModule mod_authz_core.c>
     $# Apache 2.4
     Require all granted
   </IfModule>
   <IfModule !mod_authz_core.c>
     Order deny,allow
     Allow from all
   </IfModule>
</Directory>
Alias /snmp /var/lib/ocsinventory-reports/snmp
******** End updated ocsinventory-reports.conf.local ***********
Writing communication server configuration to file /etc/apache2/conf-available/ocsinventory-reports.conf

Thanks for your help :-)

**Comment by gillesdubois** [comment]
Hi,

This problem has been identified and fixed for the 2.6RC

Regards,
Gilles Dubois.

**Comment by ayaradio** [comment]
Presento este error, alguna solucion posible?

OCS-NG Inventory Installation

WARNING: You will not be able to build any deployment package with size greater than 100MB
You must raise both post_max_size and upload_max_filesize in your vhost configuration to increase this limit.

WARNING: If you change default database name (ocsweb) or user (ocs), don't forget to update the file 'z-ocsinventory-server.conf' in your Apache configuration directory
WARNING: XML for PHP is not properly installed, you will not be able to use ipdiscover-util.
WARNING: GD for PHP is not properly installed.
You will not be able to see any graphical display
Try uncommenting extension=php_gd2.dll (Windows) by removing the semicolon in file php.ini, or try installing the php5-gd package (Linux).
WARNING: CURL for PHP is not properly installed. Try installing the php-curl package (Linux).
ERROR: MySQL for PHP is not properly installed.
Try installing MySQL for php package (Debian: php5-mysql)
