### ISSUE TITLE
Administrative Data is not visible after upgrade (second try)

### ISSUE THREAD

**Issue by sokatra** [OCSInventory-NG/OCSInventory-ocsreports#380]
### General informations
centos-release-6-9.el6.12.3.x86_64
Operating system : 

### Server installation method ( Only one choice )
- [ ] RPM Package
- [ x] Install SH
- [ ] Manual installation

### Server informations
Php version : 5.5.38
Mysql / Mariadb / Percona version : 5.5.59
Apache version : 2.2.15

### OCS Inventory informations
Ocsreports version : 
2.3.1  and 2.4.0
### Problem's description
Hy i allready opended a ticket 
https://github.com/OCSInventory-NG/OCSInventory-ocsreports/issues/366
but it was closed - i don't know how to reopen the ticket - but the problem is preventing me from upgrading the ocs version - so my hope is that the next release 2.4.1 fix the bug.
Please reopen the ticket -. if you wan't further test from me - i am also able to do this.

**Comment by gillesdubois** [comment]
Hi,

Could you upgrade to 2.6 ?
Admin Data has been fixed.

Regards,
Gilles Dubois.
