### ISSUE TITLE
Affichage Adresse Mac

### ISSUE THREAD

**Issue by githublivier** [OCSInventory-NG/OCSInventory-ocsreports#381]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system : centos 7

### Server installation method ( Only one choice )
- [ ] RPM Package
- [ ] Install SH
- [X] Manual installation

### Server informations
Php version : 5.4.16 
 MariaDB 5.5.44Mysql / Mariadb / Percona version : 
Apache version : 2.4.6 

### OCS Inventory informations
Ocsreports version : 2.3 

### Problem's description
Bonjour,

Je rencontre un problème au niveau de l'affichage d'informations pour l'adresse mac
En effet, lorsque je suis sur "Toutes les machines" et que je souhaite afficher la colonne Adresse Mac, l'information ne s'affiche pas pour l'ensemble des machines.
Or, si je clique sur une machine et que je regarde dans l'onglet matériel, l'agent a bien remonté l'adresse mac.
D'avance merci

**Comment by githublivier** [comment]
Précision supplémentaire : il semblerait que dans l'onglet machine, l'application conserve l'adresse mac connue pour la première remontée d'inventaire en mémoire.
En effet, lors de ma première remontée d'inventaire, j'avais une adresse ip différente que maintenant. Lorsque je vais sur l'onglet matériel, j'ai la première adresse ip remontée associée avec la même carte réseau et donc la même adresse mac.
Serait ce un probleme au niveau du serveur ou de l'agent ?
Je suis en v2.3 côté serveur et en v2.0.5.0 côté agent
Savez vous s'il est possible d'installer deux agents différents sur un même ordinateur ?

**Comment by charleneauger** [comment]
Bonjour @githublivier ,

Il n'est pas possible d'installer deux agents différents sur un même oridnateur. 
Je vous conseille de mettre à jour votre agent car il y a eu de multiple modifications concernant la récupération des informations Réseau et adresse MAC.

Cordialement,
Charlène AUGER

**Comment by githublivier** [comment]
Bonjour,

Je vous remercie pour votre réponse.

**Comment by charleneauger** [comment]
Bonjour @githublivier ,

Votre problème est-il résolu ? :)

Cordialement,
CHarlène Auger

**Comment by githublivier** [comment]
Bonjour,

Nous évaluons la possibilité de mettre à jour l'agent sur notre parc.
Nous avons également remarqué que les numéros de séries  ne remontés plus pour certaines des machines.
Pour résoudre ce problème la seule solution que nous avions trouvé était de supprimer l'entrée sous OCS Inventory server et de refaire la remontée d'inventaire sur la machine mais nous perdions les données administratives saisies pour la machine et, utilisant GLPI, nous générions des doublons.

Cordialement

**Comment by gillesdubois** [comment]
Bonjour,

Ce problème de doublons à été corrigé avec OCS Inventory 2.4.0.0 (Win agent)

Gilles Dubois.
