### ISSUE TITLE
Unable to column search if that particular column is hide by default

### ISSUE THREAD

**Issue by keyoneplus** [OCSInventory-NG/OCSInventory-ocsreports#383]
also take note in change #348 might have some bug if this is fixed.

### OCS Inventory informations
Ocsreports version :  2.4

### Problem's description
*Describe your problem here*
default search in column " Select All" able to search as per normal.

![image](https://user-images.githubusercontent.com/5064672/37188497-616cf3da-2347-11e8-9806-c804d4bf0214.png)

However if the column is hide by default, user select "Account info: City"
and search "B" it will not work.

![image](https://user-images.githubusercontent.com/5064672/37188586-ddafab0e-2347-11e8-9420-f22d293f8946.png)

![image](https://user-images.githubusercontent.com/5064672/37188611-fd8923e2-2347-11e8-94b1-0ea319730269.png)

Kindly work on this as search by column is useful feature, thank in advance.

**Comment by charleneauger** [comment]
Hi @keyoneplus ,

This bug has been fixed recently. I advise you to update your reports via the trunk in order to have the latest corrections.

Regards,
Charlene Auger
