### ISSUE TITLE
Création / alimentation d'un groupe de machines à partir d'un fichier

### ISSUE THREAD

**Issue by githublivier** [OCSInventory-NG/OCSInventory-ocsreports#385]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system :  Centos 7

### Server installation method ( Only one choice )
- [ ] RPM Package
- [ ] Install SH
- [x] Manual installation

### Server informations
Php version : 5.4.16
Mysql / Mariadb / Percona version :  MariaDB 5.5.44
Apache version : 2.46

### OCS Inventory informations
Ocsreports version : 2.3

### Problem's description
*Describe your problem here*

Ocsinventory Q&A
Hello Livier

    My Updates Logout 

    Questions
    Unanswered
    Tags
    Categories
    Users
    Ask a Question

Welcome to OCS Inventory NG community support, where you can ask questions and receive answers from other members of the community.

Please ask questions only in English or French.

Release 2.4 available

The official documentation can be found on http://wiki.ocsinventory-ng.org. Read it before asking your question.
Categories

    All categories
    OCS Inventory NG server (1.4k)
        OCS Inventory NG server for Unix (1k)
        OCS Inventory NG server for Windows (258)
        Administrative console (174)
    OCS Inventory NG agent (944)
    Network features (79)
    Developers (92)

Groupe statique à partir d'un fichier

Bonjour,

Existe il un moyen de créer un groupe statique à partir d'un fichier qu'on uploaderait ?

En effet, à ma connaissance, un groupe statique peut être alimenté à partir d'une recherche multicritère ou en rajoutant manuellement une machine. Serait il possible de charger une liste de machine qui alimenterait ou créerait un groupe statique ?

Vous remerciant par avance

**Comment by gillesdubois** [comment]
Bonjour,

À l'heure actuelle, il n'est pas possible de générer des groupes statiques par upload de fichiers.
La création, alimentation, suppression de groupes statiques peux s'effectuer des manières suivantes

- Dans la page "all computers"
- Par recherche multi critère
- En utilisant la page du groupe (menu inventaire -> Groupe)

Cordialement,
Gilles Dubois.
