### ISSUE TITLE
Télédéploiement - Groupe de paquets et fonctionnalités avancées pour les paquets via serveurs relais

### ISSUE THREAD

**Issue by githublivier** [OCSInventory-NG/OCSInventory-ocsreports#386]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system :  Centos 7

### Server installation method ( Only one choice )
- [ ] RPM Package
- [ ] Install SH
- [x ] Manual installation

### Server informations
Php version : 5.4.16
Mysql / Mariadb / Percona version :  MariaDB 5.5.44
Apache version : 2.4.6

### OCS Inventory informations
Ocsreports version : 2.3

### Problem's description
*Describe your problem here*
Bonjour,

Savez-vous s'il y a un moyen de regrouper les paquets au sein d'un groupe de paquets.
L'idée serait de pouvoir regrouper des paquets dans un groupe afin de faciliter le télédéploiement.
De même, est il possible avec la V2.4 d'utiliser les fonctionnalités avancées pour le télédéploiement de paquet sous serveurs relais ?

Vous remerciant par avance pour votre aide

**Comment by gillesdubois** [comment]
Bonjour,

Pour la gestion des relais, nous recommandons l'utilisation de proxy cache plutôt que des serveurs relai intégré a OCS.
Dans le cas de l'utilisation de serveur proxy cache, il serait possible de regrouper des paquets via un système de groupe statique.

Cordialement,
Gilles Dubois.
