### ISSUE TITLE
Error in activating packages;  PHP Warning: in_array() expects 2 to be array, null given in /usr/share/ocsinventory-reports/ocsreports/require/function_telediff.php

### ISSUE THREAD

**Issue by tomJa99** [OCSInventory-NG/OCSInventory-ocsreports#387]
### General informations
Operating system : Centos 6.9

### Server installation method ( Only one choice )
- [ ] RPM Package
- [X] Install SH
- [ ] Manual installation

### Server informations
Php version : 5.4
Mysql / Mariadb / Percona version : 5.1.73
Apache version : 2.2.15

### OCS Inventory informations
Ocsreports version : 2.4

### Problem's description
Hi,
whenever I try to activate a deployment package for the first time, the webconsole says: 
"Your package was successfully created in the directory /var/lib/ocsinventory-reports/download/1522043016"
Despite that common success message, my Apache Error-log says the following:
"[Date] [error] [Client IP] PHP Warning: in_array() expects 2 to be array, null given in /usr/share/ocsinventory-reports/ocsreports/require/function_telediff.php on line 230, referer: http://SERVER-IP/ocsreports/index.php?function=tele_pactive&head=1&active=1522043016"

Can somebody help me remove that error message?

**Comment by charleneauger** [comment]
Hi @tomJa99 ,

This warning has been fixed with PR #532 !

Regards,
Charlene Auger
