### ISSUE TITLE
A Bug Report... 2.2 RC1

### ISSUE THREAD

**Issue by dougreed** [OCSInventory-NG/OCSInventory-ocsreports#39]
I Installed Release 2.2 RC1  Looks nice, but SNMP does not work because the little plus '+' is missing in:

Network(s)
->Administer
--->Add
------>ID

Without the little plus, it is not possible to add a new ID to a clean database, and therefore not able to save a new entry.

**Comment by gillesdubois** [comment]
Hi,

As you can see here, this bug has been already fixed and will be available in the 2.2 Release.
https://github.com/OCSInventory-NG/OCSInventory-ocsreports/issues/11

Thanks you for contributing to the ocs inventory project.
Regards, Gilles Dubois.
