### ISSUE TITLE
Ldap misworking

### ISSUE THREAD

**Issue by AlroneRhyn** [OCSInventory-NG/OCSInventory-ocsreports#391]
### General informations
Operating system : debian8

### Server installation method ( Only one choice )
- [ ] RPM Package
- [x] Install SH
- [ ] Manual installation

### Server informations
Php version : 5.6
Mysql / Mariadb / Percona version : 5.5
Apache version : 2.4.10

### OCS Inventory informations
Ocsreports version : 2.4.1

### Problem's description
Hi,
I'am strugguling with an issue with the ldap rights. I got too groups: A super admin and B admin. Toto is in group A and B and Tata is in group B only.

CONEX_LDAP_CHECK_FIELD1_NAME = memberOf
CONEX_LDAP_CHECK_FIELD1_VALUE = GroupA
CONEX_LDAP_CHECK_FIELD1_ROLE = Super Administrator 

CONEX_LDAP_CHECK_FIELD2_NAME = memberOf
CONEX_LDAP_CHECK_FIELD2_VALUE = GroupB
CONEX_LDAP_CHECK_FIELD2_ROLE = Administrator 

CONEX_LDAP_CHECK_DEFAULT_ROLE = Readonly

When Toto logs in, he got the Readonly Role.
When Tata logs in, he got the Readonly Role.

What ever i'm trying, if the user passes the authentication, he will ALWAYS got the default role.
This is not a ldap connexion issue.

Whyyyyyy ?

Thank you very much.

**Comment by tiagobortolini** [comment]
Hi, 
I had a similar issue... try input "memberof" all lowercase instead of "memberOf".
I think it isn't recognizing your groups, so, always uses default role.

Bug is in this file:

/usr/share/ocsinventory-reports/ocsreports/backend/AUTH/methode/ldap.php

```
    if ($info[0][$f1_name][0] != '') {
        //attribute name 'memberof' is for group searching
        //FIXME: casing? -> 'memberOf'
        if ($f1_name == "memberof") {    //this is to store the entire array instead of just the first string
```

Thanks

**Comment by AlroneRhyn** [comment]
Hi Tested with version 2.5 : Works perfectly well with "memberof".
Thx !
