### ISSUE TITLE
[enhancement] Datatables :n'afficher la pagination que si necessaire

### ISSUE THREAD

**Issue by TiVince** [OCSInventory-NG/OCSInventory-ocsreports#394]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system : 

### Server installation method ( Only one choice )
- [ ] RPM Package
- [ ] Install SH
- [ ] Manual installation

### Server informations
Php version : 
Mysql / Mariadb / Percona version : 
Apache version : 

### OCS Inventory informations
Ocsreports version : 

### Problem's description
beaucoup de datatables affiche moins de 10 items si bien que la pagination n'est pas nécessaire dans ce cas et permet de gagner de la place sur les longues pages ('Materiel'  par exemple)

Il existe un plugin pour datatables qui gére  l'affichage de la la pagination que si c'est nécessaire.

[dataTables.conditionalPaging.js](https://github.com/DataTables/Plugins/blob/master/features/conditionalPaging/dataTables.conditionalPaging.js) 

Dans **require/function_table_html.php** il faut modifier le squelette de datatable en rajoutant `"conditionalPaging": true`

Exemples avec ce plugin: 
quand la pagination n'est pas  nécessaire:

![fireshot capture 003 - ocs inventory](https://user-images.githubusercontent.com/2316483/38390454-a95ffbfc-3921-11e8-995e-9a0ef0f81d62.png)

quand la pagination devient  nécessaire
![fireshot capture 004 - ocs inventory_ - http___192 168 1 26_ocsreports_index php](https://user-images.githubusercontent.com/2316483/38390561-fb91f2c2-3921-11e8-9ca2-16c2ae610da8.png)

**Comment by charleneauger** [comment]
Bonjour @TiVince ,

Merci pour votre contribution ! L'affichage de la pagination que si nécessaire a bien été ajouté.

Cordialement,
Charlène Auger
