### ISSUE TITLE
[Enhancement] passer à JQuery 3.x pour les navigateurs compatibles

### ISSUE THREAD

**Issue by TiVince** [OCSInventory-NG/OCSInventory-ocsreports#399]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system : 

### Server installation method ( Only one choice )
- [ ] RPM Package
- [ ] Install SH
- [ ] Manual installation

### Server informations
Php version : 
Mysql / Mariadb / Percona version : 
Apache version : 

### OCS Inventory informations
Ocsreports version : 

### Problem's description
les Javascript Bootstrap et Datatables supportent Jquery 3.X qui apporte de meilleures performances

On peut garder la compatibilité avec IE6-8 en conservant Jquery1.X et faire un chargement conditionnel dans la fonction **header** de **require/function_commun.php**

remplacer 
```
<script src="libraries/jquery/jquery.js" type="text/javascript"></script>
```
par 
```
<!--[if lt IE 9]>  
        <script src="libraries/jquery/jquery.js" type="text/javascript"></script>
<![endif]-->  
<!--[if (gte IE 9) | (!IE)]><!-->  
    <script src="libraries/jquery/jquery.3.3.1.js"></script>  
<!--<![endif]--> 

```

Je n'ai pas constaté d'incompatibilité dans mes tests

**Comment by gillesdubois** [comment]
Bonjour @TiVince ,

Merci pour votre contribution.
En effet, ajouter JQuery 3.X.X  pour les navigateurs compatible est une bonne idée.
Nous avons l'ajouter des que possible.

Cordialement,
Gilles Dubois.
