### ISSUE TITLE
Call to undefined function pagesplugin()

### ISSUE THREAD

**Issue by nntu** [OCSInventory-NG/OCSInventory-ocsreports#4]
hi,
when run plugin manager show error 
 Fatal error: Call to undefined function pagesplugin() in /usr/share/ocsinventory-reports/ocsreports/plugins/main_sections/ms_config/ms_config.php on line 119
find fuction not found

**Comment by gillesdubois** [comment]
Hello nntu,

That not a bug, i just forgot to commit the new changes on the file ( "function_config_generale.php" ) which contain the pagesplugin function !

As you changes have been commited you can download them.
Sorry for the inconvenience you meet.

Regards, Gilles Dubois

**Comment by nntu** [comment]
Thanks..
