### ISSUE TITLE
OCS 2.2 - Software search: hostname displayed instead of software name

### ISSUE THREAD

**Issue by StCyr** [OCSInventory-NG/OCSInventory-ocsreports#40]
06:54:24 - mks_uts: Hi, yesterday I upgraded OCS from 2.1.2 to 2.2 and had no errors in logs or while upgrading process. All fine, but when I do search by software instead hostnames I see softname.

I confirm. 

Here's the screenshot

![untitled](https://cloud.githubusercontent.com/assets/8179031/12972895/1673e39a-d0a9-11e5-8acd-ac117be3f84d.png)

**Comment by benkohler** [comment]
And apparently if you use "search with various criteria" and search for some software, you see the opposite problem-- the "Computer" column has the software name rather than computer name.

**Comment by benkohler** [comment]
This is pretty similar to issue #47 I just opened, both of them seem to be data "bleeding" from h.NAME to a.NAME or vice versa

**Comment by gillesdubois** [comment]
Hi,

This issue has been fixed, a commit will be pushed will the fix for the https://github.com/OCSInventory-NG/OCSInventory-ocsreports/issues/47

Regards, Gilles Dubois.

**Comment by ronator** [comment]
Quick fix, nice community, much apppreciated.
