### ISSUE TITLE
No package list since update to 2.4.1

### ISSUE THREAD

**Issue by Blank-Vcf** [OCSInventory-NG/OCSInventory-ocsreports#404]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system : 

### Server installation method ( Only one choice )
- [ ] RPM Package
- [X ] Install SH
- [ ] Manual installation

### Server informations
Php version : 5.6.33
Mysql / Mariadb / Percona version : mysql  Ver 14.14 Distrib 5.5.59,
Apache version : 2.4.10

### OCS Inventory informations
Ocsreports version : 2.4.1

### Problem's description
Since update 2.4.1 no package are listing on activate page, deleted package are ok
query in db show all packages if i go on a computer or a group i can see available package.

Back to 2.4 and everything ok, in debug on 2.4.1 this query is not executed:

`SELECT SQL_CALC_FOUND_ROWS FILEID, from_unixtime(FILEID), NAME, PRIORITY, FRAGMENTS, round(SIZE/1024,2), OSNAME, COMMENT from download_available where (comment not like '[PACK REDISTRIBUTION%' or comment is null or comment = '') and DELETED = 0 and comment not like '%[VISIBLE=0]%' order by NAME asc limit 0 , 500 `

**Comment by TiVince** [comment]
same here.
the problems seems to come from  this line in **plugins/main_sections/ms_teledeploy/ms_tele_activate.php**

```$l->g(593) => 'CAST(from_unixtime(FILEID) AS DATETIME(0))',```

you can revert it back to 2.4.0 version 

 ``` $l->g(593) => 'from_unixtime(FILEID)',```

or just remove (0) at the end : 

```$l->g(593) => 'CAST(from_unixtime(FILEID) AS DATETIME)',``` 
it seems to work

I'm using a mysql 5.1.173 version on Cent OS)

**Comment by Blank-Vcf** [comment]
@TiVince 
USe: `$l->g(593) => 'CAST(from_unixtime(FILEID) AS DATETIME)',`
Working for me.

**Comment by mester1202** [comment]
I'm using OCS Inventory 2.5 on Debian 8 but I still has this problem. Maybe it's because the server uses hungarian Date/Time format?

**Comment by daCaPo** [comment]
Same issue here (OCS 2.5 on Ubuntu 18.04.2 LTS). Should I open a new report, or will someone reopen this one?
