### ISSUE TITLE
Allow to display every computer

### ISSUE THREAD

**Issue by headquaker** [OCSInventory-NG/OCSInventory-ocsreports#41]
It could be cool to be able to display every computers using the filter.

**Comment by gillesdubois** [comment]
Hi,

Can you please give me some more informations ?
For example which ocs version are you using ?
Are you using ocs on linux or on windows ?

As i can see you want to be able to display all computers in the all computer menu right ?
As far as i know you can already do this on the 2.1.X and the 2.2 Stable  (screen below is from 2.2 stable) :
![entries](https://cloud.githubusercontent.com/assets/9396603/13103892/fdfeab28-d559-11e5-87bd-b119972b8ff3.png)

Thanks for contributing to the ocs inventory project
Regards, Gilles Dubois.

**Comment by headquaker** [comment]
Oops sorry didn't have the last version :).

You can close that.
