### ISSUE TITLE
[enhancement] DataTables : style des icones dans la colonne Action des dataTables

### ISSUE THREAD

**Issue by TiVince** [OCSInventory-NG/OCSInventory-ocsreports#410]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system : 

### Server installation method ( Only one choice )
- [ ] RPM Package
- [ ] Install SH
- [ ] Manual installation

### Server informations
Php version : 
Mysql / Mariadb / Percona version : 
Apache version : 

### OCS Inventory informations
Ocsreports version : 2.4.1

### Problem's description
depuis #406 et la généralisation de l'utilisation des glyphicons, serait il possible de styler les icônes dans la colonne 'actions'  des Datatables et les liens ?

exemple sur la page d'activation des paquets qui en contient 4 différents 
![ocs inventory - mozilla firefox_2018-04-18_10-06-53](https://user-images.githubusercontent.com/2316483/38919750-c9a85e3e-42f1-11e8-9fd8-4d8ae0f15034.png)

cela pourrait être fait dans **dataTables-custom.css**  ( ou /themes/OCS/style.css ?)
en exemple:
```

table.dataTable .glyphicon-stats {
 color: #337ab7  !important;
    font-weight: bold;
}
table.dataTable .glyphicon-remove {
 color:#C12E2A  !important;
    font-weight: bold;
}

table.dataTable .glyphicon-share {
 color:#5cb85c  !important;
    font-weight: bold;
}

table.dataTable .glyphicon-download-alt {
 color:#6c757d  !important;
    font-weight: bold;
}

table.dataTable a {
    color: #337ab7!important;
    font-weight: bold;
}

```

**Comment by TiVince** [comment]
style pagination
```.pagination > li > a,
.pagination > li > span {

        color: #961b7e;
}
.pagination > .active > a, 
.pagination > .active > a:focus, 
.pagination > .active > a:hover, 
.pagination > .active > span, 
.pagination > .active > span:focus, 
.pagination > .active > span:hover {
        background-color: #961b7e;
        border-color: #961b7e;
}

.pagination>li>a:focus, 
.pagination>li>a:hover, 
.pagination>li>span:focus, 
.pagination>li>span:hover {
    color:  #71145F;
}
```

style navbar
```
.navbar-default .navbar-nav>li>a {
    color:  #961b7e;
}

.dropdown-menu>li>a {
    color: #961b7e;
}   
```

**Comment by charleneauger** [comment]
Salut @TiVince ,

J'ai fait le test sur tes propositions et le style de pagination est très bien ! Par contre pour la barre de menu c'est un peu trop ... Du coup je ne vais rajouter que le style pagination :-) 
Merci beaucoup pour tes contributions !

Cordialement,
Charlène Auger

**Comment by TiVince** [comment]
@charleneauger 
oui les 2 c'est peut être trop ... les goûts et les couleurs justement.
j'aurais une autre proposition:
rajouter une marge de d'environ 10 px autour de la barre de menu pour qu'on voit l'encadrement:
````
.navbar-default {
       margin-top: 10px;
    margin-left: 10px;
    margin-right: 10px;
}
````

**Comment by TiVince** [comment]
autre proposition : permettre de créer des thèmes avec une navbar en mode 'fixed' (reste présent à l'écran tout le temps comme le menu latéral)
je peux fournir un exemple
