### ISSUE TITLE
[bug] Button group don't work in uk_UA translation

### ISSUE THREAD

**Issue by Mant1kor** [OCSInventory-NG/OCSInventory-ocsreports#412]
### General informations
Operating system : CentOS Linux 7 (Core)

### Server installation method ( Only one choice )
- [x] Install SH

### Server informations
Php version : 7.1.16
Mysql / Mariadb / Percona version : MySQL Community Server (GPL) version 5.7.21
Apache version : Apache/2.4.6

### OCS Inventory informations
Ocsreports version : 2.4.1 and 2.4

### Problem's description
Button group(from "All computers" menu) don't react to any click actions.

![default](https://user-images.githubusercontent.com/5281753/38927254-d029cfc4-430d-11e8-9c32-96b852346093.png)

In console:
![default](https://user-images.githubusercontent.com/5281753/38974633-8a4f2f98-43b3-11e8-8f8d-dc6196821def.png)

**Comment by TiVince** [comment]
there is maybe another problem 
garde_check() is assigned to an onclick event handler without quote  https://github.com/OCSInventory-NG/OCSInventory-ocsreports/blob/58398fe598e6912093139b1b58c355ccd39515b8/require/function_search.php#L537

( IE10 warns for that syntax) 

should be something like that 

` echo '<button type="button" onclick=\'garde_check("' . $list_pag[$key] . '","' . $list_id . '","' . $comp . '")\' class="btn">' . $value . '</button>';`

check others onclick assignement for exemple in the same page:
 https://github.com/OCSInventory-NG/OCSInventory-ocsreports/blob/58398fe598e6912093139b1b58c355ccd39515b8/require/function_search.php#L490
