### ISSUE TITLE
Invalid search arguments

### ISSUE THREAD

**Issue by Mant1kor** [OCSInventory-NG/OCSInventory-ocsreports#413]
### General informations
Operating system : CentOS Linux 7 (Core)

### Server installation method ( Only one choice )
- [x] Install SH

### Server informations
Php version : 7.1.16
Mysql / Mariadb / Percona version : MySQL Community Server (GPL) version 5.7.21
Apache version : Apache/2.4.6

### OCS Inventory informations
Ocsreports version : 2.4.1

### Problem's description
I tried to search for networks that are different from 10.1.0.0, with no result. But different networks are present in my db.
![default](https://user-images.githubusercontent.com/5281753/38931018-7dfd7ac2-431a-11e8-90b6-abb16312ce4d.png)

Logs:
```
[Wed Apr 18 14:55:24.406667 2018] [php7:warn] [pid 1284] [client 10.1.1.154:14665] PHP Warning:  implode(): Invalid arguments passed in /usr/share/ocsinventory-reports/ocsreports/plugins/main_sections/ms_multi_search/ms_multi_search.php on line 753, referer: https://ocsinventory/index.php?function=visu_search
[Wed Apr 18 14:55:24.406800 2018] [php7:warn] [pid 1284] [client 10.1.1.154:14665] PHP Warning:  mysqli_fetch_object() expects parameter 1 to be mysqli_result, boolean given in /usr/share/ocsinventory-reports/ocsreports/plugins/main_sections/ms_multi_search/ms_multi_search.php on line 760, referer: https://ocsinventory/index.php?function=visu_search
```

**Comment by gillesdubois** [comment]
Hi,

The multi search has been reworked. This bug is no longer revelant.
Thx for your contribution.

Regards,
Gilles Dubois.
