### ISSUE TITLE
[OCS 2.4.1] message d'erreur de  bootstrap-formhelpers.js

### ISSUE THREAD

**Issue by TiVince** [OCSInventory-NG/OCSInventory-ocsreports#415]
### General informations
Operating system : 

### Server installation method ( Only one choice )
- [ ] RPM Package
- [ ] Install SH
- [ ] Manual installation

### Server informations
Php version : 
Mysql / Mariadb / Percona version : 
Apache version : 

### OCS Inventory informations
Ocsreports version : 2.4.1

### Problem's description
sur la page de connexion en console javascript:

**TypeError: languages[language] is undefined bootstrap-formhelpers.js:15826:1**
et le japonais n'est plus dans la liste et sélectionner la dernière langue proposée dans le menu (turque) n'a aucun effet.
![ocs inventory - mozilla firefox_2018-04-19_07-46-21](https://user-images.githubusercontent.com/2316483/38973396-e32e3a22-43a5-11e8-86cd-44bee0155105.png)

si on regarde le code html, on voit qu'il y a un problème sur la syntaxe de l'attribut 'data-available' tout à la fin .

 ```
<div class='bfh-selectbox bfh-languages'  data-language='fr_FR' 
data-available='fr_FR,en_GB,cs_CZ,de_DE,es_ES,it_IT,br_BR,pl_PL,ug_UY,pt_PT,ru_RU,si_SI,tr_TRja_JP,'
 data-flags='true' data-blank='false'>`

```

le problème est survenu à l'ajout de cs_CZ. 
La version 2.4.0 n'a pas le problème.

**Comment by TiVince** [comment]
proposition:
l'ajout d'une langue n'est pas dynamique car en plus de la déclaration dans  **ocsreports/plugins/language/ lang_config.txt**, il faut aller modifier une valeur codée en dur dans  **ocsreports/plugins/language/ language.php** qui vaut 12 dans la version 2.4.1 ( mais devrait valoir 13 en raison de l'ajout de cz_CZ et 14 maintenant avec l'ukrainien)

d'autre part la boucle while n'est plus nécessaire dans language.php  avec l'utilisation de bootstrap-formhelpers.

on peut modifier language.php pour n'avoir qu'a déclarer  une nouvelle  langue dans lang_config.txt
```
require_once('require/function_files.php');
$Directory = PLUGINS_DIR . 'language/';
$ms_cfg_file = $Directory . "/lang_config.txt";
//show only true sections
if (file_exists($ms_cfg_file)) {
    $search = array('ORDER' => 'MULTI2', 'LBL' => 'MULTI');
    $language_data = read_configuration($ms_cfg_file, $search);
    $list_plugins = $language_data['ORDER'];
    $list_lbl = $language_data['LBL'];
}

$protectedPost['LANG'] = $_SESSION["OCS"]["LANGUAGE"];
$select_lang=implode(',' , $list_plugins );

$show_lang = "<label for='LANGUAGE'>".$l->g(1012)."</label>
                <div class='bfh-selectbox bfh-languages'  data-language='".$protectedPost['LANG']."' data-available='" . $select_lang . "' data-flags='true' data-blank='false'>
                    <input type='hidden' value=''>
                    <a class='bfh-selectbox-toggle' role='button' data-toggle='bfh-selectbox' href='#'>
                        <span class='bfh-selectbox-option input-medium' data-option=''></span>
                        <b class='caret'></b>
                    </a>
                    <div class='bfh-selectbox-options'>
                        <div role='listbox'>
                            <ul role='option'>
                            </ul>
                        </div>
                    </div>
                </div>";

echo $show_lang;
?>

<script>
$('.bfh-selectbox').on('change.bfhselectbox', function() {
  var language = $(this).val();
  pag(language,'LANG','ACTION_CLIC');
});
</script>
```

**Comment by charleneauger** [comment]
Bonjour @TiVince ,

Merci beaucoup pour l'amélioration proposée ! Elle a été ajoutée au code :-)

Cordialement,
Charlène Auger
