### ISSUE TITLE
Cannot select Japanese at login.

### ISSUE THREAD

**Issue by matsuoki** [OCSInventory-NG/OCSInventory-ocsreports#416]
### General informations
Operating system : Debian 7.11

### Server installation method ( Only one choice )
- [*] Install SH

### Server informations
Php version : 5.4.45
Mysql / Mariadb / Percona version : 14.14
Apache version : 2.2.22

### OCS Inventory informations
Ocsreports version : 2.4.1

### Problem's description
Cannot select Japanese at login.

Souce code of In login screen below.
I think comma is missing between  "tr_TR"  and "ja_JP".

> &lt;div class='bfh-selectbox bfh-languages'  data-language='en_GB' 
  data-available='fr_FR,en_GB,cs_CZ,de_DE,es_ES,it_IT,br_BR,pl_PL,ug_UY,pt_PT,ru_RU,si_SI,tr_TRja_JP,' data-flags='true' data-blank='false'&gt;

Thanks.

**Comment by Mant1kor** [comment]
@matsuoki you need to change string in file _plugins\language\language.php_
`  if($i == 13){`
The number - is count of languages, starts from 0.
