### ISSUE TITLE
Erreur d'accès aux logs

### ISSUE THREAD

**Issue by xdelatour** [OCSInventory-NG/OCSInventory-ocsreports#427]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system : 

### Server installation method ( Only one choice )
- [ ] RPM Package
- [ ] Install SH
- [ ] Manual installation

### Server informations
Php version : 
Mysql / Mariadb / Percona version : 
Apache version : 

### OCS Inventory informations
Ocsreports version : 2.4 

### Problem's description
*Describe your problem here*
Sur le site demo : 
- dans le menu Information
- Visualisation des logs
- clic sur log.csv (du 23 avril 2018)
- une page s'affiche, contenant seulement le message d'erreur "**Fatal error:** Allowed memory size of 134217728 bytes exhausted (tried to allocate 56 bytes) in **/home/www/www_demo/html/plugins/main_sections/ms_export/ms_csv.php** on line **36**"

**Comment by kapouik** [comment]
J'ai trouvé le problème : le log actuel fait 31Mo et il ne devrait pas y avoir de problème pour le télécharger.
En lisant le code du fichier plugins/main_sections/ms_export/ms_csv.php, on lit le fichier en entier pour le réécrire : c'est complètement stupide.

**Comment by StCyr** [comment]
C'est toujours d'actualité dans la 2.6-RC tu penses?

pour moi dans la 2.6-RC il n'y a pas réécriture du fichier log:

```php
//log directory
if (isset($protectedGet['log']) && !preg_match("/([^A-Za-z0-9.])/", $protectedGet['log'])) {
    $Directory = $_SESSION['OCS']['LOG_DIR'] . "/";
}
if (isset($Directory) && file_exists($Directory . $protectedGet['log'])) {
    $tab = file($Directory . $protectedGet['log']);
    while (list($cle, $val) = each($tab)) {
        $toBeWritten .= $val . "\r\n";
    }
    $filename = $protectedGet['log'];
}
```

**Comment by StCyr** [comment]
bon ben j'ai rien dis: c'était texto dans mon extrait du code:

```php
    $tab = file($Directory . $protectedGet['log']);
    while (list($cle, $val) = each($tab)) {
        $toBeWritten .= $val . "\r\n";
    }
```

A priori il faut faire comme indiqué ici: https://stackoverflow.com/questions/6175533/how-to-return-a-file-in-php

**Comment by StCyr** [comment]
Fixed by https://github.com/OCSInventory-NG/OCSInventory-ocsreports/pull/675

**Comment by charleneauger** [comment]
Hi @xdelatour ,

This bug has been fixed by @StCyr and his PR #675 

Regards,
Charlene Auger
