### ISSUE TITLE
IpDiscover, liens incorrects dans la colonne Actions

### ISSUE THREAD

**Issue by xdelatour** [OCSInventory-NG/OCSInventory-ocsreports#428]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system : Ubuntu 16.04

### Server installation method ( Only one choice )
- [ ] RPM Package
- [x] Install SH
- [ ] Manual installation

### Server informations
Php version : 5.6
Mysql / Mariadb / Percona version : 
Apache version : 2.4.18 

### OCS Inventory informations
Ocsreports version : 2.4

### Problem's description
*Describe your problem here*

- Dans le menu Réseau(x)
- IpDiscover
- Afficher tous mes réseaux
- Sélection d'un réseau en cliquant sur son nom dans la colonne Réseaux:Description (exemple sur le site démo : inconnu, d'adresse IP 172.16.229.0, troisième de la liste)
- Clic sur Annuler pour quitter le formulaire et revenir au tableau précédent
- Dans le tableau, colonne Actions, le lien associé au bouton inclus le paramètre value=172.16.229.0. L'adresse IP est celle du réseau précédemment sélectionné mais cette même IP est répétée pour toutes les lignes du tableau.

**Comment by charleneauger** [comment]
Bonjour @xdelatour ,
Je n'arrive malheureusement pas à reproduire votre bug...

- Quelle est la version de votre navigateur ? 

Cordialement,
Charlène Auger

**Comment by xdelatour** [comment]
Bonjour,

J'utilise Mozilla Firefox ESR version 52.7.3 (64 bits) sous Debian testing.
![ocs_428](https://user-images.githubusercontent.com/4384945/39526693-dc3c8f00-4e1f-11e8-951f-fbdc651214d8.png)

Sur la capture, la souris pointe sur la ligne avec le réseau 192.168.4.0 mais dans la barre d'état le lien contient l'adresse 172.16.229.0 et quand je clique sur le bouton Modifier de la colonne Action, le champ Adresse IP est prérempli avec 172.16.229.0 en grisé.

Cordialement,
Xavier Delatour.

**Comment by charleneauger** [comment]
Bonjour @xdelatour,

Je viens de me rendre compte que le bug n'est pas sur les liens car normalement quand vous cliquez sur OK ou ANNULER après avoir modifié un réseau, la page est censée revenir sur le choix des réseaux IpDiscover.
C'est-à-dire celle-ci : 

![ipdiscover](https://user-images.githubusercontent.com/28924550/40007505-4768d2f8-579d-11e8-9e16-ffa0cece8e82.png)

Ce qui ici, n'est pas le cas...

Nous allons corriger ce bug au plus vite !

Cordialement,
Charlène Auger
