### ISSUE TITLE
"Search with various criteria" query aggregation hiding lines.

### ISSUE THREAD

**Issue by DevSnakes** [OCSInventory-NG/OCSInventory-ocsreports#429]
### General informations
Operating system : Linux x86_64

### Server installation method ( Only one choice )
- [X] RPM Package
- [ ] Install SH
- [ ] Manual installation

### Server informations
Php version : 5.5.9
Mysql / Mariadb / Percona version : (Ubuntu) version 5.5.49-0ubuntu0.14.04.1
Apache version : Apache/2.4.7 (Ubuntu)

### OCS Inventory informations
Ocsreports version : 2.4.1

### Problem's description
I'm trying to use the "Search with various criteria" function to list computers with "Adobe Systems Incorporated" as the Software Editor, but i'm getting only 1 line result per machine, even if it does have 2 or more Adobe Softwares installed, you can note the query is making an aggregation. 
I already searched for a similar problem here in the Issues board and found [this](https://github.com/OCSInventory-NG/OCSInventory-ocsreports/issues/244) issue post, it looks like the same issue, the only difference is the function itself, he's using (function=search_soft) while i'm having the same problem with (function=visu_search).

Thank you in advance, for the support.

**Comment by gillesdubois** [comment]
Hi,

The multi search has been completly reworked.
This behavior is no longer present in the reworked search.

Thx for your contribution.

Regards,
Gilles Dubois.
