### ISSUE TITLE
Problem creating administrative data items

### ISSUE THREAD

**Issue by vmlatorre** [OCSInventory-NG/OCSInventory-ocsreports#43]
I've recently installed OCS Inventory NG 2.2 Release and after invest some time,  I have verified that there is a bug in this release.

The  error is located in this file:
     **ocsreports\plugins\computer_detail\cd_admininfo\cd_admininfo.php** Line:144

( _"onclick=window.open()"_ is missing) 

In order to solve the error  we have to replace the line by:

`array_push($config['COMMENT_AFTER'],$up_png . "<a href=# onclick=window.open(\"index.php?".PAG_INDEX."=".$pages_refs['ms_adminvalues']."&head=1&tag=ACCOUNT_VALUE_" . $val_admin_info['NAME'] . "\")><img src=image/plus.png></a>");`

**Comment by gillesdubois** [comment]
Hi,

Thanks you very much for re-openning your issue on github.

I already take a look at this issue and your fix everything is fine for me.
I will try to push your changes as soon as possible.
This issue will be notified when a fix will be commited :-)

Thanks for contributing to the ocs inventory project
Regards, Gilles Dubois.
