### ISSUE TITLE
Database user/password not accepted

### ISSUE THREAD

**Issue by marciofoz** [OCSInventory-NG/OCSInventory-ocsreports#430]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system : Centos 7.4

### Server installation method ( Only one choice )
- [x] RPM Package
- [ ] Install SH
- [ ] Manual installation

### Server informations
Php version : 5.4
Mysql / Mariadb / Percona version : Tested with MariaDB and Percona XtraDB Cluster
Apache version : 2.4

### OCS Inventory informations
Ocsreports version : 2.4.1

### Problem's description
*Describe your problem here*

-Installed ocsinventory with default user/password, all working fine.
-Create a new user/password in database:
MariaDB [(none)]> CREATE USER 'ocsuser'@'%' IDENTIFIED BY 'test123'; GRANT ALL PRIVILEGES ON ocsweb.* TO 'ocsuser'@'%'; FLUSH PRIVILEGES; 
Query OK, 0 rows affected (0.01 sec)
Query OK, 0 rows affected (0.00 sec)
Query OK, 0 rows affected (0.00 sec)

-Restart Apache and/or server:
 
-Try access ocsinventory by web brower and the get error 1045;
-The connection attempt is being made by the default user, not by the new user;
ERROR: MySql connection problem 1045
Access denied for user 'ocs'@'srv1.trust' (using password: YES)
ERROR: MySql connection problem 1045
Access denied for user 'ocs'@'srv1.trust' (using password: YES)

If I reverse the settings using the default user / password, this works.

Feel free to ask for more information.
BR.

Other informations:
/etc/httpd/conf.d/ocsinventory-server.conf 
# Master Database settings
# Replace localhost by hostname or ip of MySQL server for WRITE
PerlSetEnv OCS_DB_HOST srv1.trust
# Replace 3306 by port where running MySQL server, generally 3306
PerlSetEnv OCS_DB_PORT 3306
# Name of database
PerlSetEnv OCS_DB_NAME ocsweb
PerlSetEnv OCS_DB_LOCAL ocsweb
# User allowed to connect to database
PerlSetEnv OCS_DB_USER ocsuser
# Password for user
PerlSetVar OCS_DB_PWD test123 

/usr/share/ocsinventory-reports/ocsreports/dbconfig.inc.php 
define("DB_NAME", "ocsweb");
define("SERVER_READ", "srv1.trust");
define("SERVER_WRITE", "srv1.trust");
define("COMPTE_BASE", "ocsuser");
define("PSWD_BASE", "test123");

###rpm -qa | grep -E 'ocsinventory|MariaDB' | sort
MariaDB-client-10.2.12-1.el7.centos.x86_64
MariaDB-common-10.2.12-1.el7.centos.x86_64
MariaDB-compat-10.2.12-1.el7.centos.x86_64
MariaDB-server-10.2.12-1.el7.centos.x86_64
ocsinventory-2.4.1-1.el7.ocs.noarch
ocsinventory-release-7-4.el7.ocs.noarch
ocsinventory-reports-2.4.1-1.el7.ocs.noarch
ocsinventory-server-2.4.1-1.el7.ocs.noarch

###rpm -qa | grep -i percona | sort
percona-release-0.1-5.noarch
percona-toolkit-3.0.8-1.el7.x86_64
percona-xtrabackup-24-2.4.10-1.el7.x86_64
Percona-XtraDB-Cluster-57-5.7.21-29.26.1.el7.x86_64
Percona-XtraDB-Cluster-client-57-5.7.21-29.26.1.el7.x86_64
Percona-XtraDB-Cluster-server-57-5.7.21-29.26.1.el7.x86_64
Percona-XtraDB-Cluster-shared-57-5.7.21-29.26.1.el7.x86_64
Percona-XtraDB-Cluster-shared-compat-57-5.7.21-29.26.1.el7.x86_64

**Comment by gillesdubois** [comment]
Hi,

You forgot to update the dbconfig.inc.php file located in : 
/usr/share/ocsinventory-reports/ocsreports/dbconfig.inc.php

Regards,
Gilles DUbois.

**Comment by marciofoz** [comment]
Hi .
I did it (see above again).

**Comment by Yannock73** [comment]
Bonjour,

Exactement le même probleme ...

**Comment by Rorkien** [comment]
I had this same problem, so I decided to investigate, and after tracing the database function calls, I found out that there's another configuration file located in:

`/etc/ocsinventory/ocsinventory-reports/dbconfig.inc.php`

I don't know if this is intended, but changing this file solved the MySQL access problem.
