### ISSUE TITLE
Invertory date is outdated

### ISSUE THREAD

**Issue by DragonZX** [OCSInventory-NG/OCSInventory-ocsreports#431]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system : Ubuntu 16.04

### Server installation method ( Only one choice )
- [ ] RPM Package
- [ +] Install SH
- [ ] Manual installation

### Server informations
Php version : 7.0
Mysql / Mariadb / Percona version : 5.7
Apache version : 2.4

### OCS Inventory informations
Ocsreports version : 2.4.1

### Problem's description
Can't invertorize hardware after upgrade to  2.4.1. 
FREQUENCY =1
Last contact 2018-04-27 10:43:07
Last inventory 2018-04-11 18:52:22

**Comment by gillesdubois** [comment]
Hi,

Can you send the log of the agent inventory ?

Regards,
Gilles Dubois.

**Comment by DragonZX** [comment]
This one [OCSInventory.log](https://github.com/OCSInventory-NG/OCSInventory-ocsreports/files/1973472/OCSInventory.log)

**Comment by gillesdubois** [comment]
Hi,

You got a : ERROR *** AGENT => Failed to send Inventory <HTTP Status Code #500>
There should be some server side log (/var/log/apache2/error.log)
Can you send me these logs ?

Regards,
Gilles Dubois.

**Comment by DragonZX** [comment]
I've reconfigured this one twice... Maybe I have to wait... But I have no Errors on connection using such credentials in OCSReports. Also I have this
[error.log](https://github.com/OCSInventory-NG/OCSInventory-ocsreports/files/1973694/error.log)
Other problem was during installation. Site hadn't working without copying conf.d/* configurations to conf-avaliable and a2enconf %it%...

**Comment by DragonZX** [comment]
As for new inventory:
Agent Log: [OCSInventory.log](https://github.com/OCSInventory-NG/OCSInventory-ocsreports/files/1973865/OCSInventory.log)
Activity log for session
`Fri May  4 12:31:59 2018;873;319;PC-890909-D-2018-05-03-12-30-13;192.168.0.139;OCS-NG_WINDOWS_AGENT_v2.3.1.1;session;found
Fri May  4 12:31:59 2018;873;104;PC-890909-D-2018-05-03-12-30-13;192.168.0.139;OCS-NG_WINDOWS_AGENT_v2.3.1.1;inventory;incoming
Fri May  4 12:31:59 2018;873;515;PC-890909-D-2018-05-03-12-30-13;192.168.0.139;OCS-NG_WINDOWS_AGENT_v2.3.1.1;end;error`

Tail of error.log
`[Fri May 04 12:18:05.937144 2018] [mpm_prefork:notice] [pid 375] AH00169: caught SIGTERM, shutting down
ocsinventory-server: Can't load SOAP::Transport::HTTP* - Web service will be unavailable
ocsinventory-server: Can't load SOAP::Transport::HTTP* - Web service will be unavailable
[Fri May 04 12:18:42.688488 2018] [mpm_prefork:notice] [pid 862] AH00163: Apache/2.4.18 (Ubuntu) mod_perl/2.0.9 Perl/v5.22.1 configured -- resuming normal operations
[Fri May 04 12:18:42.688573 2018] [core:notice] [pid 862] AH00094: Command line: '/usr/sbin/apache2'`

**Comment by DragonZX** [comment]
Completely reinstalled it using sh to the clean Debian system. 
1. After installation I had to manually exec a2enconf for new configurations
2. In the error.log
[Tue May 15 16:45:49.686920 2018] [mpm_prefork:notice] [pid 19482] AH00163: Apache/2.4.25 (Debian) mod_perl/2.0.10 Perl/v5.24.1 configured -- resuming normal operations
[Tue May 15 16:45:49.687064 2018] [core:notice] [pid 19482] AH00094: Command line: '/usr/sbin/apache2'
[Tue May 15 16:45:55.222317 2018] [perl:error] [pid 19483] [client 192.168.0.139:62085] Can't call method "do" on an undefined value at /usr/local/share/perl/5.24.1/Apache/Ocsinventory/Server/System.pm line 189.\n

**Comment by DragonZX** [comment]
I have completely reconfigured it on Debian
So Can't call method "do" on an undefined value at /usr/local/share/perl/5.22.1/Apache/Ocsinventory/Server/System.pm line 189.\n
I've checked z-ocsinventory-server.conf so i have
  # Master Database settings
  # Replace localhost by hostname or ip of MySQL server for WRITE
  PerlSetEnv OCS_DB_HOST localhost
  # Replace 3306 by port where running MySQL server, generally 3306
  PerlSetEnv OCS_DB_PORT 3306
  # Name of database
  PerlSetEnv OCS_DB_NAME mydb
  PerlSetEnv OCS_DB_LOCAL mydb
  # User allowed to connect to database
  PerlSetEnv OCS_DB_USER myuser
  # Password for user
  PerlSetVar OCS_DB_PWD mypassword
I have all permissons to mydb.* for user myuser@localhost identified by 'mypassword'
Is configuration right?

**Comment by DragonZX** [comment]
Closed. Nowhere told about database settings in zz-ocsinventory-restapi.conf
