### ISSUE TITLE
[QUESTION] set custom tags with the client config 

### ISSUE THREAD

**Issue by Scifire** [OCSInventory-NG/OCSInventory-ocsreports#432]
Hello,

is it possible to set custom tags which i defined for the computers with the client config?
![image](https://user-images.githubusercontent.com/17220258/39354975-2ea173ae-4a0c-11e8-8aaa-84762e27a926.png)

i know i could set "tag" in client config which is working fine, but i didn´t found information about my customs tags.
If yes what options i have to set?

Thanks

**Comment by mfuhrmann** [comment]
:+1:

**Comment by scifire91** [comment]
@charleneauger is anyone able to answer this question or is this more complex then it looks like?

**Comment by steph78630** [comment]
Hi,

you can do it with : 

"Manage" menu, "Administrative data", "New data" buttom (at left corner) > Set values
Here, you can also add a tab with the "+" at the right corner

Is this what you want ?

**Comment by mfuhrmann** [comment]
@steph78630 No. The question is, if it's possible to fill custom created fields within the OCS agent/client config.
But your comment starts another question: If the fields can be filled using the client config, do I have to create these customs before on OCS server (as you explained)?

**Comment by steph78630** [comment]
Indeed, good question : I confess myself having tried to do it but I did not succeed...

**Comment by Scifire** [comment]
Cause it was not possible to get an answer in about four months i assume that this is not possible.
