### ISSUE TITLE
Looping in install and desinstall Plugins

### ISSUE THREAD

**Issue by dioubernardo** [OCSInventory-NG/OCSInventory-ocsreports#436]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system : Ubuntu 14.04

### Server installation method ( Only one choice )
- [ ] RPM Package
- [x ] Install SH
- [ ] Manual installation

### Server informations
Php version : PHP 5.5.9-1ubuntu4.24 (cli) (built: Mar 16 2018 12:41:43)
Mysql / Mariadb / Percona version : mysqld 5.5.60-0ubuntu0.14.04.1
Apache version : Apache/2.4.7 (Ubuntu)

### OCS Inventory informations
Ocsreports version : Release 2.4.1

### Problem's description

When I try to uninstall / install plugins the following error is displayed and php goes into looping.

[Wed May 02 14:44:41.101536 2018] [:error] [pid 9907] [client 200.19.255.19:50167] PHP Warning:  fopen(/usr/share/ocsinventory-reports/ocsreports/plugins/language/english/english.txt): failed to open stream: No such file or directory in /usr/share/ocsinventory-reports/ocsreports/plugins/main_sections/ms_plugins/plugins.class.php on line 255, referer: http://inventario.furg.br/ocsreports/?function=pluginsmanager
[Wed May 02 14:44:41.101667 2018] [:error] [pid 9907] [client 200.19.255.19:50167] PHP Warning:  fopen(/usr/share/ocsinventory-reports/ocsreports/plugins/language/english/english.tmp): failed to open stream: No such file or directory in /usr/share/ocsinventory-reports/ocsreports/plugins/main_sections/ms_plugins/plugins.class.php on line 256, referer: http://inventario.furg.br/ocsreports/?function=pluginsmanager

**Comment by gillesdubois** [comment]
Hi,

Thx for your report but this bug has been already fixed in the trunk.

Regards,
Gilles Dubois.
