### ISSUE TITLE
Search with various criteria show wrong info with DIFFERENT param

### ISSUE THREAD

**Issue by Mant1kor** [OCSInventory-NG/OCSInventory-ocsreports#440]
### General informations
Operating system : CentOS Linux 7 (Core)

### Server installation method
- [x] Install SH

### Server informations
Php version : 7.1.16
Mysql version : 5.7.22
Apache version : 2.4.6

### OCS Inventory informations
Ocsreports version : 2.4.1 (latest changes from github)

### Problem's description
All PC in DB - 734

Search №1
Local / Network Gateways - Equal - 10.1.0.172
Result - 178 Result(s) _(Seems like OK)_

Search №2
Local / Network Gateways - DIFFERENT - 10.1.0.172
Result - 712 Result(s) _(What? 734-178 ≠ 712)_
And there is PC with gateway 10.1.0.172 in results.

**Comment by Mant1kor** [comment]
Update.
The problem occurs with DIFFERENT parameter.

All PC in DB - 744.
![default](https://user-images.githubusercontent.com/5281753/39624792-4890a2a2-4fa3-11e8-9bc3-caeb616f63d7.png)
![default](https://user-images.githubusercontent.com/5281753/39624833-780ef4ca-4fa3-11e8-82af-eb2bf373fb85.png)
![default](https://user-images.githubusercontent.com/5281753/39624745-1dcfc246-4fa3-11e8-82e8-845d5e4ee9de.png)

**Comment by charleneauger** [comment]
Hi @Mant1kor ,
Do you have multiple network cards on a computer ?

Regards,
Charlene Auger

**Comment by Mant1kor** [comment]
Hi @charleneauger ,
No, 90% PC on DB have only one network card. The rest 10% - is notebooks, with Wi-Fi module.
I can add more info, tell me what you need to resolve this problem.

**Comment by charleneauger** [comment]
OK, is it possible to have a screenshot of your search with the corresponding column display ? Because in your screenshot you haven't the column "Local/Network : Network: IP Adress".
Thank's

**Comment by Mant1kor** [comment]
@charleneauger , it's enought?
https://i.imgur.com/PsuLB65.png

**Comment by charleneauger** [comment]
Yes, if you use search in column with your search, does it give you results ?

**Comment by charleneauger** [comment]
Hi @Mant1kor ,

Since version 2.4 of the OCS agent, we manage the status of the computers' networks interface.
Which mean that all the network interface have a status "UP" or "DOWN".
To make your search valid, you need to add a criteria on the "Local / Networks: Status" field and set the value to "EQUAL" => "UP".

Regards,
Charlene Auger
