### ISSUE TITLE
The communication server encountered the following error on install :  Err_02

### ISSUE THREAD

**Issue by kefeto** [OCSInventory-NG/OCSInventory-ocsreports#444]
Hi, i install OCSInventory 2.4.1 on Centos7. I can collect info from agents,but can't install plugins from menu.
I read about the problem,but no one give a solution...

httpd log : 

192.168.15.20 - - [08/May/2018:13:33:10 +0300] "GET /ocsreports/favicon.ico HTTP/1.1" 200 370070 "http://192.168.15.253/ocsreports/index.php?function=pluginsmanager" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36"
192.168.15.20 - - [08/May/2018:13:33:13 +0300] "GET /ocsreports/index.php?function=pluginsmanager HTTP/1.1" 200 23908 "http://192.168.15.253/ocsreports/index.php?function=pluginsmanager" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36"
192.168.15.20 - - [08/May/2018:13:33:13 +0300] "POST /ocsreports/ajax.php?function=pluginsmanager&no_header=true&no_footer=true HTTP/1.1" 200 76 "http://192.168.15.253/ocsreports/index.php?function=pluginsmanager" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36"
127.0.0.1 - - [08/May/2018:13:33:14 +0300] "GET /ocsreports/upload/uptime.zip HTTP/1.1" 404 226 "-" "LWP::Simple/6.00 libwww-perl/6.05"
127.0.0.1 - - [08/May/2018:13:33:14 +0300] "POST /ocsplugins HTTP/1.1" 200 522 "-" "PHP-SOAP/5.4.16"
192.168.15.20 - - [08/May/2018:13:33:14 +0300] "POST /ocsreports/index.php?function=pluginsmanager HTTP/1.1" 200 24446 "http://192.168.15.253/ocsreports/index.php?function=pluginsmanager" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36"
192.168.15.20 - - [08/May/2018:13:33:15 +0300] "POST /ocsreports/ajax.php?function=pluginsmanager&no_header=true&no_footer=true HTTP/1.1" 200 666 "http://192.168.15.253/ocsreports/index.php?function=pluginsmanager" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36"

**Comment by Mant1kor** [comment]
SELinux status?

**Comment by kefeto** [comment]
It is disable !

**Comment by gillesdubois** [comment]
Hi,

This problem has been fixed with the 2.6RC version which introduce a brand new plugin engine.

Regards,
Gilles Dubois.
