### ISSUE TITLE
some deployement related queries count "DOWNLOADGROUP" devices as "real" devices

### ISSUE THREAD

**Issue by StCyr** [OCSInventory-NG/OCSInventory-ocsreports#446]
package "java jre 1.8.171" reports 8 computers "non notified":

![untitled](https://user-images.githubusercontent.com/8179031/39986788-0c88f5b2-5763-11e8-85bb-07a1347679c6.png)

But, when I click on the stat icon (pie chart icon on the right), I see only 7 computers non notified:
![untitled](https://user-images.githubusercontent.com/8179031/39986870-4892d398-5763-11e8-9623-06f91363d200.png)

And, if I click on the "7" in the "Number" column, I get again 8 computers:

![image](https://user-images.githubusercontent.com/8179031/39986971-9e1e2074-5763-11e8-9b42-e55220ff3806.png)

I'll send you a PR for that

**Comment by StCyr** [comment]
I'be a patch for the first query (ms_tele_activate.php).

But, the second query as changed between 2.4 (version I'm using) and "master". I need to investigate if the bug still applies there.

**Comment by StCyr** [comment]
hello @charleneauger 

Pour le patch de la 2eme query, j'ai un souci avec la branche master: Il semble que tu aies changé le fichier ms_multi_search.php. Mais, celui-ci est passé de 1297 lignes à 279 lignes, et je ne retrouve plus rien.

```
root@houdini:/home/support/OCSInventory-ocsreports/plugins/main_sections/ms_multi_search# wc -l ms_multi_search.php*
  279 ms_multi_search.php
 1297 ms_multi_search.php.back
 1576 total
root@houdini:/home/support/OCSInventory-ocsreports/plugins/main_sections/ms_multi_search# git status
On branch StCyr-Issue446
Your branch is ahead of 'master' by 1 commit.
  (use "git push" to publish your local commits)
nothing to commit, working directory clean
You have new mail in /var/mail/root
root@houdini:/home/support/OCSInventory-ocsreports/plugins/main_sections/ms_multi_search#
```

Tu es en train de travailller dessus?

Bàt,

Cyrille

**Comment by charleneauger** [comment]
Bonjour @StCyr ,

Il y a une nouvelle multi-search qui a été créée par @gillesdubois il y a peu. Le ms_multi_search.php.back correspond à l'ancienne multi-search. 
Avais-tu mis à jour ta branche master avec les nouvelles modifications ?

Cordialement,
Charlène Auger

**Comment by charleneauger** [comment]
Avec les modifications, toutes les requêtes ont été déplacées dans les différentes classes présentes dans require/search. 
Si tu pouvais me dire quelle requête tu recherches je pourrais peut-être te faire gagner un peu de temps :)

**Comment by StCyr** [comment]
Je cherche la requête qui permet d'avoir la liste des agents ayant un paquet spécifié dans un état spécifié.

Exemple, la requête suivante:

![image](https://user-images.githubusercontent.com/8179031/40004693-834d129a-5796-11e8-9edc-01da97307761.png)

**Comment by charleneauger** [comment]
D'après la capture que tu as envoyé, tu es toujours sur l'ancienne multicritère...

La nouvelle multicritère ressemble à ça : 
![multicritere](https://user-images.githubusercontent.com/28924550/40005062-68bcb7ae-5797-11e8-8cb7-cae70f1eb0bd.png)

**Comment by StCyr** [comment]
J’imagine que la version 2.4.1 utilise toujours l’ancienne version de la recherche multi-critères.

La question est donc « est-ce que je patches le bug présent sur cette (ancienne) version? Et, si oui, sur quelle branche dois-je baser ma PR? »

**Comment by charleneauger** [comment]
Bonjour @StCyr ,

Merci pour ta PR, je l'ai testé et mergé :)
