### ISSUE TITLE
Plugins Office

### ISSUE THREAD

**Issue by headquaker** [OCSInventory-NG/OCSInventory-ocsreports#45]
Améliorer le plugin Office afin :

1. D'avoir le nombre de poste par "office key"
2. D'avoir la liste des postes par "office key"
3. D'avoir le nom de licences par "office key"

**Comment by gillesdubois** [comment]
j'ai recréé ton issue ici : https://github.com/PluginsOCSInventory-NG/officepack/issues/1
Dans la mesure ou elle n'a rien a voir avec l'ocs reports.

**Comment by headquaker** [comment]
Ok désolé pour le mauvais poste
