### ISSUE TITLE
Noms des logiciels commençant par une lettre accentuée

### ISSUE THREAD

**Issue by xdelatour** [OCSInventory-NG/OCSInventory-ocsreports#450]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system : Ubuntu 16.04

### Server installation method ( Only one choice )
- [ ] RPM Package
- [x] Install SH
- [ ] Manual installation

### Server informations
Php version : 5.6.36
Mysql / Mariadb / Percona version : MySQL 5.7.22
Apache version : 2.4.18

### OCS Inventory informations
Ocsreports version : 2.4

### Problem's description
*Describe your problem here*

Bonjour,
Sur la page Inventaire/Tous les logiciels, les lettres E et É sont considérées comme différentes : 
![bug_ocs_e](https://user-images.githubusercontent.com/4384945/40042968-52adf504-5823-11e8-992f-99f8af051de8.png)

La liste des logiciels est par contre identique aussi bien pour E que pour É (49 logiciels commençant par E ou É).

**Comment by charleneauger** [comment]
Bonjour @xdelatour ,

Une refonte de la page "Tous les logiciels" a été effectuée et sera présente dans la release 2.6.
L'interface ayant totalement changé, ce bug n'est donc plus présent :)

Cordialement,
Charlène Auger
