### ISSUE TITLE
New Groups going always to "Static Groups"

### ISSUE THREAD

**Issue by tiagobortolini** [OCSInventory-NG/OCSInventory-ocsreports#452]
### General informations
Operating system : Centos 7 (3.10.0-693.21.1.el7.x86_64)

### Server installation method ( Only one choice )
- [ ] RPM Package
- [x] Install SH
- [ ] Manual installation

### Server informations
Php version : 7.0.30 mod_perl/2.0.10 
Mysql / Mariadb / Percona version : 5.7.22 MySQL Community Server
Apache version : 2.4.6

### OCS Inventory informations
Ocsreports version : 2.4.1 (Cloned from github)

### Problem's description

Hi,

When Ocsreports is installed from github, all new groups created based on "Search with various criteria" goes to "Static Groups" tab instead of "Dynamic Groups".

This does not happen when installed from 2.4.1 released on 3 Apr.

![screen_01](https://user-images.githubusercontent.com/28762958/40201777-736e60d8-59f6-11e8-965b-b005e238803b.png)

![screen_02](https://user-images.githubusercontent.com/28762958/40201779-73b8d514-59f6-11e8-904f-39a753fdcb27.png)

![screen_03](https://user-images.githubusercontent.com/28762958/40201778-7393b7d4-59f6-11e8-9e8b-9ac141f596f2.png)

Thanks a lot

**Comment by cristiy2007** [comment]
Same thing here

**Comment by dmoldovan123** [comment]
Same thing here

**Comment by charleneauger** [comment]
Hi @tiagobortolini, @cristiy2007, @dmoldovan123 ,

This bug has been fixed  with the PR #456 ! :)

Regards,
Charlene Auger
