### ISSUE TITLE
Multisearch with administrative date does not work

### ISSUE THREAD

**Issue by AndresUPC** [OCSInventory-NG/OCSInventory-ocsreports#454]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system : 
Centos 6.9
### Server installation method ( Only one choice )
- [ ] RPM Package
- [X] Install SH
- [ ] Manual installation

### Server informations
Php version : 5.5.38
Mysql / Mariadb / Percona version : MariaDB 10.1.25
Apache version : 2.2.15

### OCS Inventory informations
Ocsreports version : 2.4.1

### Problem's description
When we try to do a search with an administrative data field with purchase date, it never shows any result neither the criteria is after or before. It only shows incorrect results when choose EXACTLY, and shows the ones that have date 0000-00-00.
I've tried some solutions:
https://github.com/OCSInventory-NG/OCSInventory-ocsreports/issues/392
https://github.com/OCSInventory-NG/OCSInventory-ocsreports/issues/336
and revised other themes like:
https://github.com/OCSInventory-NG/OCSInventory-ocsreports/issues/112
Now calendars works in Spanish languaje and I can manage date format as well.
But the problem is that there's no result if we want to search befores a date in this administrative data date field.
Has anyone any suggestions or corrections about this?
Thanks in advance

**Comment by gillesdubois** [comment]
Hi,

A new version is available with a new multi criterias search.
All date system has been rework.

See : https://github.com/OCSInventory-NG/OCSInventory-ocsreports/releases/tag/2.5

Regards,
Gilles Dubois.
