### ISSUE TITLE
Add virtual host field to search and list view

### ISSUE THREAD

**Issue by mfuhrmann** [OCSInventory-NG/OCSInventory-ocsreports#455]
### OCS Inventory informations
Ocsreports version : 2.4.1

### Problem's description
It's not possible to search for:

* specifc nodes which are hosted from virtual host XY
* all nodes which are VMs and list them in the search result

These facts make this really handy feature (to see which VM is hosted where) useless.

**Comment by gillesdubois** [comment]
Hi,

This is possible using a plugin but there is no plugins like this available at the moment (apart from VMWare Vcenter inventory)

Regards,
Gilles Dubois.

**Comment by mfuhrmann** [comment]
@gillesdubois So do I understand your doings correct?
The enhancement is not worth to continue?

I mean, marking it as a question feels totally wrong from my point of view.. It was a enhancement request, since there is no chance to use the "VM is hosted where" information in a handy way.

Or is there a plan to publish the plugin you mentioned? Then a reference would be nice to have in this issue to be able to follow it.
