### ISSUE TITLE
Teledeploy only on HTTPS and Auth

### ISSUE THREAD

**Issue by lucaseraphin** [OCSInventory-NG/OCSInventory-ocsreports#457]
Hi,

Actually teledeploy is only in HTTP , is it possible to have it only on HTTPS and add an auth to /download 
This directory is not secure, I put the package of the agent on it , so anyone can download it and install it . 
( if i configure an auth , the agent will not be able to download any packages). 
Where can I find in the source code the way to change http for https , for the teledeploy ?

Thanks

**Comment by TiVince** [comment]
you can try to force redirection to https when a client want to download a fragment in http.
it works with curl when you  ask him to follow redirection (-L)  but I don't know if  the OCS Agent will do  the same 
use mod_rewrite and modify the  download directory for example

```
 <directory /var/www/html/download >
RewriteEngine On
RewriteCond %{HTTPS} !=on
RewriteRule ^/?(.*) https://%{SERVER_NAME}/download/$1 [R,L]
order allow,deny
allow from All
Options FollowSymLinks -Indexes
AllowOverride None
</directory>

```
