### ISSUE TITLE
Accents

### ISSUE THREAD

**Issue by headquaker** [OCSInventory-NG/OCSInventory-ocsreports#46]
Nous avons aussi un problème lié aux accents qui ne s'affichent pas.

Exemple: Microsoft WindowsÂ 7 Entreprise

**Comment by gillesdubois** [comment]
Bonjour,

Pourrait-tu être plus précis sur l'endroit ou tu rencontre le problème ?
Plugins ? Inventaire de machine ? Agent windows ? Quel version d'agent ?

Cordialement, Gilles Dubois.

**Comment by headquaker** [comment]
Dans All computers

Si je clique sur un ordinateur je n'ai pas de problème d'accent.

**Comment by gillesdubois** [comment]
Invalide, impossible de reproduire le bug.

**Comment by headquaker** [comment]
Je peux mettre un screen si besoin.
