### ISSUE TITLE
Ocsinventory reports export problem

### ISSUE THREAD

**Issue by naccey** [OCSInventory-NG/OCSInventory-ocsreports#464]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system : CentOS release 6.9 (Final)

### Server installation method ( Only one choice )
- [ ] RPM Package
- [x ] Install SH
- [ ] Manual installation

### Server informations
Php version : 5.4.45
Mysql / Mariadb / Percona version : SUSE MySQL RPM version 5.0.96 on remote server
Apache version : Apache/2.2.15 (CentOS)

### OCS Inventory informations
Ocsreports version : 2.3.1

### Problem's description
*Describe your problem here*
my ocsinventory server is entering to web intarface normally displaying all things but  reporting to excel no computer name column and other things wrong column picture-1 and picture-2
Thanks in advance for your help

![picture-1](https://user-images.githubusercontent.com/15703383/40773452-9b3d6ae8-64cb-11e8-8a42-04faa7828df0.JPG)
![picture-2](https://user-images.githubusercontent.com/15703383/40773471-a7532c00-64cb-11e8-8379-9596c82c8c5e.JPG)

**Comment by gillesdubois** [comment]
Hi,

This problem has already been adressed in 2.3.1 and has been fixed in the 2.4.1 release. Please upgrade your server to fix your issue.

Regards,
Gilles Dubois.
