### ISSUE TITLE
confusion between NAME and name (software name, computer name) in ms_multi_search.php

### ISSUE THREAD

**Issue by benkohler** [OCSInventory-NG/OCSInventory-ocsreports#47]
Commit 05a1420079429f9da8de1f6fc9f4918048fe694a changed line ~795 as follows, to attempt to fix the confusion between "Software Name" and "Computer Name":

-						'NAME'=>'h.NAME',
 +						//'NAME'=>'h.NAME',
 +						$l->g(23)=>'h.name',

The change from h.NAME to h.name fixed the confusion, but after this fix the "Computer" column entries do not have a hyperlink to the specific machine entry.

Then commit be601e97d66b83f4a7eb142ce3e2547471198647 changed the line as follows, to fix the hyperlinking:

 -						$l->g(23)=>'h.name',
 +						'NAME'=>'h.NAME',

..but this undid the NAME/name change from earlier.  I believe what this line needs to be, is:

'NAME'=>'h.name',

which is something of a combination of the previous 2 fixes.  I have tested this locally and it seems to give the desired result.

**Comment by benkohler** [comment]
I'm trying to figure out how changing h.NAME to h.name could possibly change the behavior like this-- is it possible that h.NAME is somehow getting replaced by the value of a.NAME somewhere else in this file?

**Comment by StCyr** [comment]
Hello @benkohler 

I've tried what you propose and just changed 'NAME'=>'h.NAME' to 'NAME'=>'h.name', and hyperlink still works indeed.

Also, the tables obtained when using the "All softwares" search seem also OK.

Thanks,

Cyrille

**Comment by xmun2k** [comment]
There is a similar issue with Software Search feature. If a search is executed for a specific software title, in the results, the entries for "Computers" and "Software: Name" both list the same thing i.e. the computer name. Not sure if this should be listed as a separate issue.
