### ISSUE TITLE
OCS 2.4.1 - Groupe Dynamique  et télédéploiement

### ISSUE THREAD

**Issue by githublivier** [OCSInventory-NG/OCSInventory-ocsreports#471]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system : Centos 7

### Server installation method ( Only one choice )
- [ ] RPM Package
- [ ] Install SH
- [x] Manual installation

### Server informations
Php version : 5.4.16
Mysql / Mariadb / Percona version : 5.5.52
Apache version : 2.4.6

### OCS Inventory informations
Ocsreports version : 2.4.1

### Problem's description
Bonjour,

Au lancement de la version serveur 2.4, il est indiqué que : "À partir de maintenant, vous pouvez affecter des paquets de redistribution aux machines à partir d’un groupe dynamique et de groupes statiques"

J'ai installé cette version pour la tester. La fonctionnalité qui vise à attribuer un paquet sur un groupe dynamique a particulièrement retenu mon attention.
Cependant, lorsque j'ajoute un paquet à un groupe, toutes les machines présentes dans le cache du groupe se voient affecter le paquet. Lorsque le cache est regénéré et que d'autres machines sont ajoutées automatiquement au groupe, ces machines ne bénéficient pas du paquet.

Est ce une mauvaise compréhension de ma part ou il y aurait il une configuration à faire en plus ?
Je pensais que l'attribution des paquets à un groupe dynamique était également dynamique pour toutes les machines qui sont rajoutées après que le cache n'expire et que la requête soit rejouée.

D'avance merci pour vos réponses

**Comment by gillesdubois** [comment]
Bonjour,

En 2.6 nightly, vous ne rencontrerez plus ce problème.

Cordialement,
Gilles Dubois.
