### ISSUE TITLE
How can i download the Windows Agent Setup?

### ISSUE THREAD

**Issue by SFreiheit** [OCSInventory-NG/OCSInventory-ocsreports#479]
How can i download the Windows Agent Setup?

**Comment by gillesdubois** [comment]
Hi @SFreiheit ,

You need to go on our website ...

Regards,
Gilles Dubois.

**Comment by SFreiheit** [comment]
okay i go on MY website to Download YOUR Agent .... 
sounds logical ...

**Comment by SFreiheit** [comment]
the answer is: https://github.com/OCSInventory-NG/WindowsAgent/releases/download/2.3.1.1/OCSNG-Windows-Agent-2.3.1.1.zip

**Comment by gillesdubois** [comment]
I think you didn't read my answer correctly ... "OUR" is not "YOUR".
See: http://www.wordreference.com/definition/our

The next time you post on our github, try to search by yourself before posting.
Also, aggressive answer are not tolerated. Most of people here are volunteer.
