### ISSUE TITLE
Software Search -> Ajout Colonne USER

### ISSUE THREAD

**Issue by cp61** [OCSInventory-NG/OCSInventory-ocsreports#48]
Bonjour 

Dans la page de résultat Software Search , est il possible d'y ajouter également le champs USER  après IP ou COMPUTERS.

Cordialement

**Comment by gillesdubois** [comment]
Bonjour,

Je prend votre demande en compte et vous fait un retour dès que possible.

Cordialement, 
Gilles Dubois.
