### ISSUE TITLE
 ocs inventory does not register the serials of all the monitors to which it owes?

### ISSUE THREAD

**Issue by Anemix-Otaq** [OCSInventory-NG/OCSInventory-ocsreports#483]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system : 

### Server installation method ( Only one choice )
- [ ] RPM Package
- [ ] Install SH
- [ ] Manual installation

### Server informations
Php version : 
Mysql / Mariadb / Percona version : 
Apache version : 

### OCS Inventory informations
Ocsreports version : 
2.1.1.1
### Problem's description

ocs inventory does not register the serials of all the monitors that are mostly of the brand LG and SAMSUNG

**Comment by gillesdubois** [comment]
Hi,

This agent version is really old, the newest version have major improvements on this side.

Regards,
Gilles Dubois.
