### ISSUE TITLE
Problème d'affichage de toutes les machines

### ISSUE THREAD

**Issue by mblegrand** [OCSInventory-NG/OCSInventory-ocsreports#487]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system : FreeBSD (11.1-STABLE)
Client: Windows 10 (version 1803)

### Server informations
Php version : 5.6.36
Mysql / Mariadb / Percona version : 5.7.22-log
Apache version : 2.4

### OCS Inventory informations
Ocsreports version : 2.4.1

### Problem's description

Depius l'installation de la version 2.4.1 d'ocs, nous n'arrivons plus à afficher toutes nos machines. Nous disposons de 713 machines, mais seulement 10 sont affichées. Quand on essaye de choisir " Afficher 50, 100, 500 ou 1000 résultats" le message "traitement en cours..." apparait et rien ne se passe. En plus il n'ya aucun message d'erreur qui se produit (pas au niveau SQL et non plus au niveau HTML).   Et aussi quand on essaie de passer d'une page de 10 résultats affichés à une autre, le scenario qui a été décris au paravant se reproduit ("traitement en cours..." apparait et rien ne se passe).

**Comment by gillesdubois** [comment]
Bonjour,

La 2.5 est sortie avec son lot d'amélioration sur la génération des tables pouvez-vous essayer avec cette version ?

Cordialement,
Gilles Dubois.

**Comment by charleneauger** [comment]
Bonjour @mblegrand ,

N'ayant pas de nouvelle de votre part, nous partons du principe que votre problème a été résolu.

Cordialement,
Charlène Auger
