### ISSUE TITLE
Vulnerability assessment of OCSNG 2.4.1

### ISSUE THREAD

**Issue by daniejstriata** [OCSInventory-NG/OCSInventory-ocsreports#494]
### General informations
Operating system : CentOS Linux 7 

### Server installation method ( Only one choice )
- [x] Install SH

### Server informations
PHP Version :5.6.36
Database Server : MariaDB Server version 10.3.8-MariaDB
Apache version : 

### OCS Inventory informations
Version OCSReports: 2.4.1

### Problem's description
Found issues in the index.php that needs to be investigated.
[9a8a7774-449a-464f-8262-1927d0c0686c.pdf](https://github.com/OCSInventory-NG/OCSInventory-ocsreports/files/2162123/9a8a7774-449a-464f-8262-1927d0c0686c.pdf)

Many items seems to be duplicated but are variants of the same finding.

**Comment by gillesdubois** [comment]
Hi, fixed from 2.5.1, re-tested for 2.6 release.
