### ISSUE TITLE
feature request - uptime statistics

### ISSUE THREAD

**Issue by sokatra** [OCSInventory-NG/OCSInventory-ocsreports#495]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system : 
Linux x86_64 3.10.0-327.18.2.el7.x86_64
http://demo.ocsinventory-ng.org/

### Server installation method ( Only one choice )
- [ ] RPM Package
- [ ] Install SH
- [ ] Manual installation
online demo
### Server informations
Php version :5.6.36
Mysql / Mariadb / Percona version : MariaDB Server version 5.5.56-MariaDB
Apache version : Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips

### OCS Inventory informations
Ocsreports version : 
2.4
### Problem's description
*Describe your problem here*
Feature request
It would be nice if ocs can report a statistic over the time a client was online.

This should be possible by calculating the uptime field changes in the mysql database
Without that feature i can only see the a specific client was online because some deployment packages were applied at a specific time

kind regards

**Comment by sokatra** [comment]
problem is that the statistics in ocs inventory can only be a "connected to ocs-server" statistic.
It would be better if the uptime plugin calculates something on the client and write this to a 16 bit value - and every bit in this 16 bit value is equivalent to a specific Day when the client is online.
The calculation will be done verytime the uptime plugin was started.
So even if the computer is at home and can't reach the ocs-inventory server the info that the computer was on will be logged.
This value will be evaluated on the ocs-inventory  server which display a statistics about all the last xxx days if the computer was online or not. But this solution works only if the uptime plugin will be adapted too

**Comment by gillesdubois** [comment]
Hi,

This query is more related to the uptime plugin.

Regards,
Gilles Dubois.
