### ISSUE TITLE
 The "Show / Hide" dropdown menu is missing items like storage or drives

### ISSUE THREAD

**Issue by guzval** [OCSInventory-NG/OCSInventory-ocsreports#497]
### General informations
Operating system : Ubuntu 18.04 LTS

### Server installation method ( Only one choice )
- [ ] RPM Package
- [x] Install SH
- [ ] Manual installation

### Server informations
Php version : 7.2.7
Mysql / Mariadb / Percona version : MySQL 5.7
Apache version : 2.4.29

### OCS Inventory informations
Ocsreports version : 2.4.1

### Problem's description
In the "**All computers**" tab, the "**Show / Hide**" dropdown menu is **missing items like storage or drives** (i tried to find hard disk info), the data for these items are being registered in the database throught the agent but i can´t see theme in the web console.    I tried in the demo version webpage but the same result.   Im new to OCS so i don´t know if this a problem or i am doing something wrong. I searched the forums but nothing related to solve this.

**Comment by charleneauger** [comment]
Hi @guzval ,

It's normal that storage and drives do not appear because they are just not on the list :)

Regards,
Charlene Auger
