### ISSUE TITLE
2.2RC1: Liens manquants dans visu_search 

### ISSUE THREAD

**Issue by StCyr** [OCSInventory-NG/OCSInventory-ocsreports#5]
Bonjour,

Il me semble avoir trouvé une régression dans la version 2.2RC1.

Quand on fait une recherche d'agents en utilisant la fonction visu_search, les listes d'agents affichées ne permettent pas de cliquer sur une entrée pour voir le détail de l'agent correspondant.

Ci-dessous un exemple d'une telle liste. Vous pouvez y voir que l'entrée "LAPTOP-YVES" que j'ai laissé visible n'est pas affichée en gras contrairement à ce qui se fait dans les autres listes: 

![untitled](https://cloud.githubusercontent.com/assets/8179031/8906710/100ba328-3471-11e5-8d0e-aa7ac5500f87.png)

Ci-dessous un exemple d'une liste obtenue avec function=visu_computers&filtre=a.TAG&value=ADMIN_LAPTOP, on voit que la même entrée est en gras (et, je peux cliquer dessus):

![untitled](https://cloud.githubusercontent.com/assets/8179031/8906754/63cd5330-3471-11e5-8002-d80eefdf920d.png)

Bien à vous,

Cyrille

**Comment by StCyr** [comment]
Bonjour @gillesdubois,

pour répondre à ta question sur l'irc, il s'agit de n'importe quelle recherche faite à partir de la fonctionalité "Search with various criteria" (recherche multi-critères).

PS: Si tu n'arrive pas à reproduire, je peux encore essayer de déboguer de mon côté. Tu as une idée de la fonction/méthode utilisée pour afficher cette liste?

Cyrille

**Comment by StCyr** [comment]
Petit update, j'ai le problème avec Firefox 39.0 et IE 11.0.9600.17914

**Comment by gillesdubois** [comment]
Salut,

Certaines recherches de bases peuvent être faite via la barre de recherche dans les différentes tables mais les liens manquant peut être génant pour les recherches plus avancés ..
Je regarde ça des que possible (En même temps que ton autre issue normalement).

Merci pour ton retour
Gilles Dubois.

**Comment by gillesdubois** [comment]
Bug fixed : https://github.com/OCSInventory-NG/OCSInventory-ocsreports/pull/7
Resolved.

**Comment by benkohler** [comment]
This fix undid the fix from https://github.com/OCSInventory-NG/OCSInventory-ocsreports/commit/05a1420079429f9da8de1f6fc9f4918048fe694a
