### ISSUE TITLE
ocsinventory over https

### ISSUE THREAD

**Issue by philthynz** [OCSInventory-NG/OCSInventory-ocsreports#50]
Hi All,

Is it possible to block port 80 in apcahe/ports.conf and still use package deployment over https? If port 80 is NOT blocked, any agent can communicate with the server over 80 and push an inventory otherwise.

Thats a big issue if any agent can push inventory over http.

Cheers

**Comment by kapouik** [comment]
That's why the agent support HTTP authentification.

You can set an htpasswd on the /ocsinventory alias and then define an user and password.

**Comment by philthynz** [comment]
Correct me if i am wrong. But that's not secure... Any traffic over http can be seen, and is un-encrypted. So the username and password would be seen in the tcp stack. We can use https for the agents. But then how to block agents over http and still use http for package deployment?

Or is there a way to use https for package deployment?

**Comment by gillesdubois** [comment]
Hi @philthynz ,

If you want you can configure you agent to use https for inventory and deployment ... you just have to set up a ssl ceritificate on the agent and use an "https://xxx/ocsinventory" url instead of "http://xxx/ocsinventory"

Regards, Gilles Dubois.

**Comment by philthynz** [comment]
Hi @gillesdubois 

I am using https and have an ssl cert setup. The inventory is working fine over https. However, because I have not blocked port 80 in `apache/ports.conf`. Any agent can still inventory over port 80 by setting http in the agent config. http is disabled when going to the web portal. The web portal is only on https.

My point is... port 80 still works, anyone is free to set that in the inventory config. So... how do i disable inventory over port 80? I imagine i can do this in the apache site config. And just block the `server/ocsinventory` alias.

The larger issue is. That package fragments for deployment are done over http. So i can't block port 80. Is there a way to use package fragments over https? Because as far as i can see. Package fragments over http is hard coded, and a big security risk.

![image](https://cloud.githubusercontent.com/assets/17504095/13373311/69564fa4-dd64-11e5-8ff4-8e9d3c30d0aa.png)

**Comment by gillesdubois** [comment]
Ok so you want to block the http port but you can't because fragments are still downloaded in http.

As you said you can change the hardcoded value in the source code and make the fragments download with https by default. If for you https is a mandatory you should modify the hardcoded value in the source code.

I've got a fix for this problems which add a choice (http / https) for the package activiation but i can't commit it at the moment because no test has been done on this.
However i can let this issue open and you will be notified when this commit will be pushed.

Regards,
Gilles Dubois.

**Comment by philthynz** [comment]
@gillesdubois Thanks for the response. Yes. https fragment downloads would be very nice.

Please do leave this issue open. I'll wait for you commit to implement this feature.

**Comment by kapouik** [comment]
It may need some adaptations but you may forbidden port 80 only on /ocsinventory with this rules in apache config on the correct alias :
RewriteCond %{SERVER_PORT} 80 
RewriteRule ^(.*) - [R=403,NC,L]

As it, you can have the agent in https only and having the download in http

**Comment by philthynz** [comment]
@kapouik Awesome! Thanks for the response and the config. Can you point me where the alias would resolve to? I am putting this into `ocsinventory-reports.conf`:

```
Alias /ocsinventory ??
<Directory ??>
RewriteEngine on
RewriteCond %{SERVER_PORT} 80
RewriteRule ^(.*) - [R=403,NC,L]
</Directory>
```

**Comment by philthynz** [comment]
Ok, this config works: Edit `z-ocsinventory-server.conf`, and  change the `<Location /ocsinventory>`entry like this:

```
  <Location /ocsinventory>
    <IfModule mod_authz_core.c>
      # Apache 2.4
      Require all granted
        </IfModule>
        <IfModule !mod_authz_core.c>
      # Apache 2.2
          order deny,allow
          allow from all
        </IfModule>
        RewriteEngine on
        RewriteCond %{SERVER_PORT} 80
        RewriteRule ^(.*) - [R=403,NC,L]
        # If you protect this area you have to deal with http_auth_* agent's parameters
        # AuthType Basic
        # AuthName "OCS Inventory agent area"
        # AuthUserFile /etc/apache2/.htpasswd"
        # require valid-user
        SetHandler perl-script
        PerlHandler Apache::Ocsinventory
  </Location>
```

Now inventory is blocked over http / 80. And package deployment still works.

**Comment by philthynz** [comment]
@gillesdubois I'd like to reopen this issue if i may. Regarding your comment 

> I've got a fix for this problems which add a choice (http / https) for the package activiation but i can't commit it at the moment because no test has been done on this.
However i can let this issue open and you will be notified when this commit will be pushed.

Did you manage to code up a fix to enable https for package fragments?

**Comment by ronator** [comment]
I am speaking for myself here. Based on how you described the attack vector, I would really question my business' IT rights management if my users were able to arbitrarily change important administrative tool or agent settings. This can cause trouble and sleepless nights. Of course, I do see your point about https and you are right. I hope you can see my point, too.
