### ISSUE TITLE
Question tri A à Z

### ISSUE THREAD

**Issue by lechardonneret** [OCSInventory-NG/OCSInventory-ocsreports#502]
Salut tout le monde, 
Je suis en version 2.4.1 sur linux ubuntu LTS 16.04 sur le site demo sous l'onglet localisation comment  faire un tri par ordre alphabétique des villes qui laisse la tache facile aux utilisateurs de se repérer facilement merci de me guider es ce que c'est au niveau de la base donnée ou au niveau configuration serveur.

**Comment by charleneauger** [comment]
Bonjour @lechardonneret ,

Le tri par ordre alphabétique des Select a été corrigé :)
Voici le lien vers le commit qui correspond : d4a8c2669792e7cf8694a3eeb95cd09f2aa68fd7

Cordialement,
Charlène Auger

**Comment by lechardonneret** [comment]
Bonjour @charleneauger  ,
c'est réglé je viens de mettre à jour mon fichier merci infiniment.
