### ISSUE TITLE
ERROR: MySql connection problem 1045

### ISSUE THREAD

**Issue by nohnaimer** [OCSInventory-NG/OCSInventory-ocsreports#507]
*ERROR: MySql connection problem 1045. Access denied for user 'ocsi'@'10.128.217.39' (using password: YES).*

### General informations
Operating system : CentOS 7.5 x64

### Server installation method ( Only one choice )
- [ ] RPM Package
- Install SH
- [ ] Manual installation

### Server informations
Php version : 7.2.8
Percona version : 5.7.22
Apache version : 2.4.6

### OCS Inventory informations
Ocsreports version : 2.4.1

### Problem's description
*ReOpen! https://github.com/OCSInventory-NG/OCSInventory-ocsreports/issues/164*
![2018-07-23 10 05 24](https://user-images.githubusercontent.com/8865830/43062149-851db43e-8e60-11e8-8c82-aad542e75904.png)

**Comment by gillesdubois** [comment]
Hi,

This issue has been fixed in the latest releases.

Regards,
Gilles Dubois.
