### ISSUE TITLE
login on the web console ocs inventory by default is french don't change

### ISSUE THREAD

**Issue by 4lfr3d7115** [OCSInventory-NG/OCSInventory-ocsreports#509]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system : 
CENTOS 7
### Server installation method ( Only one choice )
- [ ] RPM Package
- [ ] Install SH
- [X ] Manual installation

### Server informations
Php version : PHP 5.4.16
Mysql / Mariadb / Percona version : 5.5.56-MariaDB MariaDB Server
Apache version :  Apache/2.4.6

### OCS Inventory informations
Ocsreports version : 2.4.1

### Problem's description
After updating from 2.4.0 to 2.4.1, when I try access the web login, the French language is automatically presented. When Spanish is selected, it is not maintained and it is automatically re-entered into the French language.

![login_ocs](https://user-images.githubusercontent.com/8273076/43213417-3208c674-8ffc-11e8-86a3-bbc9b530afc4.png)

**Comment by charleneauger** [comment]
Hi @4lfr3d7115 ,

This bug has been fixed with the commit 19c6662086ac7a269721c5320bcb391980f02cb9 .

Regards,
Charlene Auger

**Comment by 4lfr3d7115** [comment]
It works well. tanks.
