### ISSUE TITLE
Update old account infos

### ISSUE THREAD

**Issue by 4lfr3d7115** [OCSInventory-NG/OCSInventory-ocsreports#511]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system : 
CENTOS 7
### Server installation method ( Only one choice )
- [ ] RPM Package
- [ ] Install SH
- [x] Manual installation

### Server informations
Php version : PHP 5.4.16
Mysql / Mariadb / Percona version : 5.5.56-MariaDB MariaDB Server
Apache version : Apache/2.4.6

### OCS Inventory informations
Ocsreports version : 
Ocsreports version : 2.4.1
### Problem's description

After updating from 2.4.0 to 2.4.1, I try to "Uddate old acount infos" , when I click the button send nothing happens
![script_new_tag](https://user-images.githubusercontent.com/8273076/43276670-181d5e30-90cb-11e8-9b63-ccc3b4b41a6a.png)

The log:
[26/Jul/2018:11:21:26 -0500] "POST /index.php?function=script_new_tag HTTP/1.1" 200 8183 "https://ocsinventory/index.php?function=script_new_tag" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36"

**Comment by charleneauger** [comment]
Hi @4lfr3d7115 ,

Update old account info was just for updating from 1.x to 2.x. This feature has been remove in PR #505 :)

Regards,
Charlene Auger
