### ISSUE TITLE
Matériel / Mémoire > Mauvais libellé

### ISSUE THREAD

**Issue by steph78630** [OCSInventory-NG/OCSInventory-ocsreports#515]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system : Debian 8

### Server installation method ( Only one choice )
- [ ] RPM Package
- [ X ] Install SH
- [ ] Manual installation

### Server informations
Php version : 5.6.36
Mysql / Mariadb / Percona version : 5.5.60-0+deb8u1
Apache version : 2.4.10 (Debian)

### OCS Inventory informations
Ocsreports version : 2.5
### Problem's description
En langue française, dans la section Matériel / Mémoire, l'intitulé de colonne concernant l'emplacement de la barrette ne devrait pas être "Nombre de slots" mais "Numéro de slot"
![ocs reports 2 5 - memoire vive](https://user-images.githubusercontent.com/26839124/43354961-86837a14-9254-11e8-8f63-7f8d896ae256.JPG)

**Comment by gillesdubois** [comment]
Bonjour,

Cette modification à été corrigée dans la PR ci-dessus.
Elle sera bientôt mergée.

Gilles Dubois.
