### ISSUE TITLE
Matériel / Bios > Déplacement des infos

### ISSUE THREAD

**Issue by steph78630** [OCSInventory-NG/OCSInventory-ocsreports#516]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system : Debian 8

### Server installation method ( Only one choice )
- [ ] RPM Package
- [ X ] Install SH
- [ ] Manual installation

### Server informations
Php version : 5.6.36
Mysql / Mariadb / Percona version : 5.5.60-0+deb8u1
Apache version : 2.4.10 (Debian)

### OCS Inventory informations
Ocsreports version : 2.5

### Problem's description
Dans la zone Matériel d'une fiche machine, les infos de BIOS devrait se trouver en début de liste (avant processeur, mémoire, stockage, etc.) car remontant des infos essentielles dans cette section (fabricant, modèle de machine, numéro de série, etc.) pour l'administrateur de parc.

**Comment by gillesdubois** [comment]
Bonjour,

Le problème va être fix avec la PR ci-dessus.

Cordialement,
Gilles Dubois.
