### ISSUE TITLE
Thème - personnalisation interface > Eléments non modifiés

### ISSUE THREAD

**Issue by steph78630** [OCSInventory-NG/OCSInventory-ocsreports#517]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system : Debian 8

### Server installation method ( Only one choice )
- [ ] RPM Package
- [ X ] Install SH
- [ ] Manual installation

### Server informations
Php version : 5.6.36
Mysql / Mariadb / Percona version : 5.5.60-0+deb8u1
Apache version : 2.4.10 (Debian)

### OCS Inventory informations
Ocsreports version : 2.5

### Problem's description
Lors de la personnalisation de l'interface (changement de thème), certains éléments ne sont pas pris en compte :

 - Icon et libellé du header (Favicon ?) > Permettre la reprise du logo (custom thème) et le changement de texte (par ex. : "Inventaire Ma_société")
![theme - header](https://user-images.githubusercontent.com/26839124/43355130-7f65040c-9257-11e8-9062-27aeb9b5484e.JPG)

 - Statistiques - Nombre de connexion > La couleur personnalisable du fichier css (thème) n'est pas repris dans cette zone (affichage de la courbe, du rectangle de la légende "Nombre" ainsi que du popup représentant la quantité pour la période sélectionnée)
![theme - statistiques - nb de connexions](https://user-images.githubusercontent.com/26839124/43355240-6ddbe636-9259-11e8-94d2-a7ffeba71f9a.JPG)

**Comment by gillesdubois** [comment]
Bonjour,

Effectivement la Favicon n'est pas prise en charge.
Les courbes de stats fonctionnant sur une librairie annexe, il est compliqué de modifier le CSS des stats sont grand développement.

La remontée est intéressant mais ne sera pas mise en prioritée.

Gilles Dubois.
