### ISSUE TITLE
Information / Server information > Add server activity graphs

### ISSUE THREAD

**Issue by steph78630** [OCSInventory-NG/OCSInventory-ocsreports#519]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system : Debian 8

### Server installation method ( Only one choice )
- [ ] RPM Package
- [ X ] Install SH
- [ ] Manual installation

### Server informations
Php version : 5.6.36
Mysql / Mariadb / Percona version : 5.5.60-0+deb8u1
Apache version : 2.4.10 (Debian)

### OCS Inventory informations
Ocsreports version : 2.5

### Problem's description
In OCS reports, information, server information > add server activity graphs (processor, RAM, storage, etc.)

**Comment by gillesdubois** [comment]
Hi,

This feature is more related to a monitoring server than OCS itself.

If you want statistiques on server usage, you should consider installing a monitoring platform like Zabbix or Centreon.

Also, it could be developped but as a plugin, not a core feature.

Regards,
Gilles Dubois.
