### ISSUE TITLE
Agent 2.1.1.3 isn't compatible with XP

### ISSUE THREAD

**Issue by sokatra** [OCSInventory-NG/OCSInventory-ocsreports#52]
Agent with Version 2.1.1.2 and 2.1.1.3 and 2.1.1.4 (2.2 alpha) arent compatible with Windows XP

Service can't be installed - 

if i start
ocsinventory.exe /SAVE_CONF

i will get immediatly a graphical windows with the following errorcode

C:\Program Files\Ocsinventory Agent\OCSInventory.exe is not a valid win32 application

**Comment by gillesdubois** [comment]
https://github.com/OCSInventory-NG/WindowsAgent/issues/12
