### ISSUE TITLE
Customization of the notification > not work

### ISSUE THREAD

**Issue by steph78630** [OCSInventory-NG/OCSInventory-ocsreports#520]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system : Debian 8

### Server installation method ( Only one choice )
- [ ] RPM Package
- [X] Install SH
- [ ] Manual installation

### Server informations
Php version : 5.6.36
Mysql / Mariadb / Percona version : 5.5.60-0+deb8u1
Apache version : 2.4.10 (Debian)

### OCS Inventory informations
Ocsreports version : 2.5

### Problem's description
When I want to download a customize template (html), it does not work

![email notification](https://user-images.githubusercontent.com/26839124/43355680-b220e47a-9260-11e8-805c-ac3fcffac15a.JPG)

**Comment by gillesdubois** [comment]
Hi,

I need more infos, APACHE error log for example.

Regards,
Gilles Dubois.

**Comment by steph78630** [comment]
[Wed Aug 01 20:34:41.510198 2018] [mpm_prefork:notice] [pid 1614] AH00169: caught SIGTERM, shutting down
Scalar value @part_query[...] better written as $part_query[...] at /usr/local/share/perl/5.20.2/Apache/Ocsinventory/Interface/AssetCategory.pm line 53.
Scalar value @args[...] better written as $args[...] at /usr/local/share/perl/5.20.2/Apache/Ocsinventory/Interface/AssetCategory.pm line 53.
Scalar value @part_query[...] better written as $part_query[...] at /usr/local/share/perl/5.20.2/Apache/Ocsinventory/Interface/AssetCategory.pm line 53.
Scalar value @args[...] better written as $args[...] at /usr/local/share/perl/5.20.2/Apache/Ocsinventory/Interface/AssetCategory.pm line 53.
[Wed Aug 01 20:34:42.987405 2018] [mpm_prefork:notice] [pid 1672] AH00163: Apache/2.4.10 (Debian) mod_perl/2.0.9dev Perl/v5.20.2 configured -- resuming normal operations
[Wed Aug 01 20:34:42.987452 2018] [core:notice] [pid 1672] AH00094: Command line: '/usr/sbin/apache2'

**Comment by charleneauger** [comment]
Hi @steph78630 ,
This bug has been fixed with the PR #661 
Regards,
Charlene
