### ISSUE TITLE
missing initialization in cd_repository.php

### ISSUE THREAD

**Issue by stromsoe** [OCSInventory-NG/OCSInventory-ocsreports#524]
In the file OCSInventory-ocsreports/plugins/computer_detail/cd_repository/cd_repository.php

line 57 calls

`ajaxtab_entete_fixe($list_fields, $default_fields, $tab_options, $list_col_cant_del);`

but $list_col_cant_del is never initialized.  line 51 should insert

`$list_col_cant_del = $list_fields;`

Fixing this silences php warnings to the apache error log.

**Comment by gillesdubois** [comment]
Hi,

Thanks for your report.
A pull request has been made.

Regards,
Gilles Dubois.
