### ISSUE TITLE
Can not perform searches with several criteria

### ISSUE THREAD

**Issue by 4lfr3d7115** [OCSInventory-NG/OCSInventory-ocsreports#528]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system :  Centos 7

### Server installation method ( Only one choice )
- [ ] RPM Package
- [ ] Install SH
- [x ] Manual installation

### Server informations
Php version : PHP 5.4.16
Mysql / Mariadb / Percona version : 5.5.56-MariaDB
Apache version : Apache/2.4.6

### OCS Inventory informations
Ocsreports version : 2.5

### Problem's description
*Describe your problem here*
I have read only profile users but can not perform searches with several criteria, 
![search_ocs](https://user-images.githubusercontent.com/8273076/43602167-c951cd38-9654-11e8-9c8f-3c8ee1a27b51.png)

presents a blank page and the following error when I try to change permissions in their profile

PHP Fatal error:  Class 'DOMDocument' not found in /usr/share/ocsinventory-reports/ocsreports/require/config/XMLProfileSerializer.php on line 30, referer: https://ocsinventary/index.php?function=admin_profile_details&profile_id=read-only

**Comment by charleneauger** [comment]
Hi @4lfr3d7115 ,

The multi-criteria search uses tables that need the minimum php 5.5 version. I advise you to update your php version to 5.5 or higher.

Regards,
Charlene

**Comment by 4lfr3d7115** [comment]
I update to php version 5.6.37 I got this error:
[Tue Aug 14 19:29:56.791221 2018] [:error] [pid 3053] [client HOSTIP:14534] PHP Fatal error:  Call to undefined function simplexml_load_string() in /usr/share/ocsinventory-reports/ocsreports/require/menu/XMLMenuSerializer.php on line 67

I install php-xml and everything is ok now

Thank you
