### ISSUE TITLE
Scalar values better written as at AssetCategory.pm line 54

### ISSUE THREAD

**Issue by pchamo** [OCSInventory-NG/OCSInventory-ocsreports#530]
### General informations
Operating system :  CentOS 7

### Server installation method ( Only one choice )
- [x ] Manual installation

### Server informations
PHP version : php-5.4.16
Apache version : 2.4.6

### OCS Inventory informations
Ocsreports version : 2.5

### Problem's description
I find this error messages in Apache logs:

> Scalar value @part_query[$i] better written as $part_query[$i] at /usr/local/share/perl5/Apache/Ocsinventory/Interface/AssetCategory.pm line 54.
> Scalar value @args[$i] better written as $args[$i] at /usr/local/share/perl5/Apache/Ocsinventory/Interface/AssetCategory.pm line 54.

I changed this:

        for (my $i = 0; $i < scalar @part_query; $i++){
            $query .= @part_query[$i] . @args[$i];
        }

for this:

        for (my $i = 0; $i < scalar @part_query; $i++){
            $query .= $part_query[$i] . $args[$i];
        }

Is it ok?

**Comment by RudyLaurent** [comment]
Hi @pchamo,
With which version of Perl the problem occurs ?

Regards,
Rudy Laurent

**Comment by pchamo** [comment]
Hi, it's perl v5.16.3. 

Thank you.
