### ISSUE TITLE
LDAP configuration option vansihed after update 

### ISSUE THREAD

**Issue by grigribou** [OCSInventory-NG/OCSInventory-ocsreports#537]
### General informations
Operating system : CentOS 7

### Server installation method ( Only one choice )
- [ ] RPM Package
- [X] Install SH
- [ ] Manual installation

### Server informations
Php version : 5.6.36
Mysql / Mariadb / Percona version : MariaDB Server version 10.2.16-MariaDB
Apache version : Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips PHP/5.6.36 

### OCS Inventory informations
Ocsreports version : 2.5

### Problem's description
After updating from 2.4 to 2.5 LDAP option in config menu is not available anymore.
My old LDAP configuration is still working, but i can't edit it through GUI (Only DB).

![image](https://user-images.githubusercontent.com/8124469/43822507-8f1acb64-9aec-11e8-978f-a641432347c4.png)

Regards,

**Comment by gillesdubois** [comment]
Hi,

From 2.5 simplified configuration had been enabled.
See : http://wiki.ocsinventory-ng.org/02.Basic-documentation/Administration-of-OCS-Inventory-NG/#simplified-configuration

Regards,
Gilles Dubois.
