### ISSUE TITLE
Problem unknown column category with agent 2.3.1.1

### ISSUE THREAD

**Issue by yanok45** [OCSInventory-NG/OCSInventory-ocsreports#538]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system : All Windows agent

### Server installation method ( Only one choice )
- [ ] RPM Package
- [ ] Install SH
- [X ] Manual installation

### Server informations
Php version : 7.0.30-0+deb9u1
Mysql / Mariadb / Percona version :  10.1.26-MariaDB-0+deb9u1
Apache version :  2.4.25-3+deb9u4

### OCS Inventory informations
Ocsreports version : server 2.5

### Problem's description
*Describe your problem here*

Problem ERROR *** AGENT => Failed to send Inventory <HTTP Status Code #500>
Error in apache/error.log  : DBD::mysql::st execute failed : Unknown column CATEGORY in 'field list' at /usr/local/share/perl/5.24.1/Apache/Ocsinventory/Server/inventory/Update.pm line 165

Manually add a field CATEGORY in the table Software. It seem to work....

**Comment by gillesdubois** [comment]
Hi,

This problem has been fixed with new versions.

Regards,
Gilles Dubois.
