### ISSUE TITLE
broken deploy stats links

### ISSUE THREAD

**Issue by alacn1** [OCSInventory-NG/OCSInventory-ocsreports#540]
### General informations
Operating system : Ubuntu

### Server installation method ( Only one choice )
- [x] Manual installation

### Server informations
Php version : 5.6.36
Mysql / Mariadb / Percona version : mysql-server 5.7.23
Apache version : 2.4.29

### OCS Inventory informations
Ocsreports version : 2.5

### Problem's description
Links from table on deploy stats page show empty search result.
And it only changes search form on first clicked link.

![deploy stats](https://user-images.githubusercontent.com/9846054/43842966-d25cbd82-9afc-11e8-9489-0aedd9a6ead7.png)

![deploy stats search](https://user-images.githubusercontent.com/9846054/43842986-db49e29e-9afc-11e8-8845-72f7fc9fd152.png)

**Comment by charleneauger** [comment]
Hi @alacn1 ,

Thank's for your fix bug ! 

Regards,
Charlene
