### ISSUE TITLE
Network adapters info - networks and hardware tables

### ISSUE THREAD

**Issue by pchamo** [OCSInventory-NG/OCSInventory-ocsreports#541]
### General informations
Operating system : CentOS 7

### Server installation method ( Only one choice )
- [X ] Install SH

### Server informations
Php version : 5.4.16
Apache version : 2.4.6

### OCS Inventory informations
Ocsreports version : 2.5

### Problem's description
Some few computers of my intranet are getting a blank ipaddress. So, I was looking the info recorded in the networks and hardware tables, and found more inconsistent data in other computers, e.g. ipconfig shows two ipaddress for a network adapter and only one ip address is recorded, etc.

- Table networks contains complete info, IP addresses, network address, gateway, name of  the adapters, etc.
- On the contrary, the table hardware only contains one IP address

Is the ip address recorded in hardware table taken from networks table? I mean, what is the logic of all the network info? Where and how is recorded the network info in those tables? (hardware, networks) And what network info is shown from the "All computers" vista? (after adding the ipaddress column to be shown). I mean, I need to clarify things to see if there are bugs to reports or just to get some help from you to determine what can I do to fix things in some of ocs entries of my computers that are having, in my concept, incomplete or wrong info recorded. Thank you.

**Comment by pchamo** [comment]
Please see bug or issue #543. That is one of the issues.

**Comment by pchamo** [comment]
As far as I can see, the ipaddr shown in All computers page is taken from the networks table. And the ip address shown from the computer details page (which is shown after clicking on the computer's name link) is taken from the hardware table. It's crazy :(

**Comment by gillesdubois** [comment]
Hi,

Since a lot of modification has been made to this feature, this issue is no longer reveleant.

Regards,
Gilles Dubois.
