### ISSUE TITLE
Ipaddress not shown (blank)

### ISSUE THREAD

**Issue by pchamo** [OCSInventory-NG/OCSInventory-ocsreports#543]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system : CentOS 7.4.1708

### Server installation method ( Only one choice )
- [X ] Install SH

### Server informations
Php version : 5.4.16
Apache version : 2.4.6

### OCS Inventory informations
Ocsreports version : 2.5

### Problem's description

Info shown in All computers page: http://prntscr.com/ki2o3y

Info from the hardware table: http://prntscr.com/ki39i8

Info from the networks table: http://prntscr.com/ki2u8p

**Comment by charleneauger** [comment]
Hi @pchamo ,

This bug occur on all your machines ?

Regards,
Charlene

**Comment by pchamo** [comment]
No, the ipaddress is not shown only in few machines.

**Comment by pchamo** [comment]
This one is ok: http://prntscr.com/ki3du2

**Comment by charleneauger** [comment]
Hi @pchamo ,

In your first example, in your networks table I saw that all your network cards were in status down, you haven't card in up for this machine?

Regards,
Charlene

**Comment by pchamo** [comment]
Of course, it has a network adapter, but its ipaddress is being registered in hardware table only. I suppose OCS registers all the networks adapters info in the networks table and the main adapter info is also written in hardware table. Is like that? Thank you.

**Comment by pchamo** [comment]
Well, I tried ocsinventory-agent 2.4 and solved the problem :)
