### ISSUE TITLE
Search with various criteria shows nothing (blank)

### ISSUE THREAD

**Issue by pchamo** [OCSInventory-NG/OCSInventory-ocsreports#544]
### General informations
Operating system : CentOS 7.4.1708

### Server installation method ( Only one choice )
- [x ] Install SH

### Server informations
Php version : 5.4.16
Apache version : 2.4.6

### OCS Inventory informations
Ocsreports version : 2.5

### Problem's description

I updated from ocs server 2.4 to 2.5 and when I select the option search with various criteria I got a blank page. The Apache error log shows:

> PHP Fatal error:  Can't use method return value in write context in /usr/share/ocsinventory-reports/ocsreports/require/search/TranslationSearch.php on line 224

Line 224: 

>         if(empty($l->g($this->translationArray[$name]))){

I think I found a solution here: https://stackoverflow.com/questions/17139264/cant-use-function-return-value-in-write-context:

>         $vacio=($l->g($this->translationArray[$name]));
>         if(empty($vacio)){
>             return $name;

similar for lines 245 and 253:

>         $vacio=($l->g($this->translationArray[$values[0]]));
>         if(!empty($vacio)){
>             $table = $l->g($this->translationArray[$values[0]]);

>         $vacio=($l->g($this->translationArray[$name]));
>         if(!empty($vacio)){
>             $name = $l->g($this->translationArray[$name]);

I haven't receive any feedback at this respect yet :(

**Comment by charleneauger** [comment]
Hi @pchamo ,

This bug occur on all your searches or on a particular search ?

Regards,
Charlene

**Comment by charleneauger** [comment]
Hi @pchamo ,

The multi-criteria search uses tables that need the minimum php 5.5 version. I advise you to update your php version to 5.5 or higher.

Regards,
Charlene
