### ISSUE TITLE
Licence violation

### ISSUE THREAD

**Issue by kapouik** [OCSInventory-NG/OCSInventory-ocsreports#547]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system : All

### Server installation method ( Only one choice )
- [ ] RPM Package
- [ ] Install SH
- [ ] Manual installation

### Server informations
Php version : 
Mysql / Mariadb / Percona version : 
Apache version : 

### OCS Inventory informations
Ocsreports version : latest

### Problem's description
In the library directory, two project must be remove due to licence incompatibility : phpcas and tclib. 

phpcas is release under apache licence wich is completly incompatible with GPLv2.
tclib is release under GPLv3 who modify licence of all ocsreports like a dictator.

**Comment by pchamo** [comment]
How about this? https://www.zdnet.com/article/gplv3-myth2-you-cant-mix-gpl-software-with-other-software/

**Comment by kapouik** [comment]
you can use software with different licences. But it's impossible to add software with incompatible licence in the git repository like this.

**Comment by gillesdubois** [comment]
Resolved because we are now using composer...
