### ISSUE TITLE
unused variable in ms_multi_search.php

### ISSUE THREAD

**Issue by StCyr** [OCSInventory-NG/OCSInventory-ocsreports#552]
in version 2.4.1, there's a variable `$sql_search=array();` in file `ms_multi_search.php` which doesn't seem to be used. 

What's also strange is that there's a variable called `$sql_seach` (note the missing 'r') used later in the file (for example: ` if (isset($sql_seach[$operation][$table[$i]])){`

Could you please have a look?

Cyrille

**Comment by gillesdubois** [comment]
Hi @StCyr ,

Could you upgrade to 2.5 ?

Regards,
Gilles Dubois.
