### ISSUE TITLE
bug in single package deployment statistic

### ISSUE THREAD

**Issue by StCyr** [OCSInventory-NG/OCSInventory-ocsreports#553]
### General informations
Operating system : Ubuntu 16.04

### Server installation method ( Only one choice )
- [ ] RPM Package
- [ ] Install SH
- [X ] Manual installation

### Server informations
Php version : 
Mysql / Mariadb / Percona version : 
Apache version : 

### OCS Inventory informations
Ocsreports version : 2.5

### Problem's description

When trying to see a package's deployment statistic (ie: over time), you get an empty page and the following line in Apache's error log:

```
PHP Fatal error:  Uncaught Error: Cannot use object of type stdClass as array in /usr/share/ocsinventory-rey/ms_speed_stat.php:100\nStack trace:\n#0 /usr/share/ocsinventory-reports/ocsreports/require/header.php(437): require()\n#1 /usr/share/ocsinventory-reports/ocsreports/index.php(44): requusr/share/ocsinventory-reports/ocsreports/plugins/main_sections/ms_teledeploy/ms_speed_stat.php on line 100
```

The following patch solves the issue:

```
ksort($nb_4_hour);
$i = 0;
+++$data = array();
foreach ($nb_4_hour as $key => $value) {
    $ancienne += $value;
    $data[$i] = round((($ancienne * 100) / $total_mach), 2);
    $legende[$i] = date("d/m/Y H:00", $key);
    $i++;
}
```

**Comment by charleneauger** [comment]
Hi @StCyr ,

Your PR has been merged ! Thank's for your contribution !

Regards,
Charlene
