### ISSUE TITLE
orphans found in accountinfo_config table (Inconsistency)

### ISSUE THREAD

**Issue by mtbadi39** [OCSInventory-NG/OCSInventory-ocsreports#56]
we have migrate OCS Server + Reports to 2.2, all work fine but when we try to **update old account infos** from **config menu**, ocs reports show this error :
*orphans found in accountinfo_config table (Inconsistency)*
![ocs](https://cloud.githubusercontent.com/assets/8750684/13771202/87b0b450-ea8c-11e5-90d1-b684059c0af8.png)

Here is **accountinfo_config table** :
![ocs_2](https://cloud.githubusercontent.com/assets/8750684/13771292/045d3b9a-ea8d-11e5-9215-0339623ca93d.png)

**Comment by gillesdubois** [comment]
Hi,

Are you upgrading ocs from 1.X to 2.2 ?

Regards, Gilles Dubois.

**Comment by mtbadi39** [comment]
we upgrade ocs from 2.1.2 to 2.2

**Comment by gillesdubois** [comment]
That why you got oprhan, you don't need to use this tool. You only need it when uprgading from ocs 1.X to 2.X

Regards, Gilles Dubois.

**Comment by djooberlee** [comment]
I have the same. This is normal? just ignore this message?

**Comment by gillesdubois** [comment]
@djooberlee this page is only available for ppl who upgrade from 1.X to 2.X if you upgrade from 2.X to an other 2.X version you don't have to use this page ( you can ignore all output from this page )

**Comment by djooberlee** [comment]
thnx
