### ISSUE TITLE
Bug - ipaddr from hardware table not found in networks table

### ISSUE THREAD

**Issue by pchamo** [OCSInventory-NG/OCSInventory-ocsreports#560]
### General informations
Operating system :  CentOS 7.4.1708

### Server installation method ( Only one choice )
- [x ] Running ./setup from tgz installer

### Server informations
Php version : 5.4.16
Mysql / Mariadb / Percona version : mysql-community-server-5.7.21
Apache version : 2.4.6

### OCS Inventory informations
Ocsreports version : 2.5

### Problem's description
Ip address shown in All computers page is different from the one that is shown when I click on the computers name hyperlink (administrative data). I mean, the ip address found in hardware table is diferrent from the one shown in networks table.

This issue is present in some 15  of 1550 computers of my network. I run this sql query to determine the number of affected computers:

> SELECT name,osname, macaddr,USERAGENT, lastdate FROM hardware, networks where ipaddr not in (SELECT ipaddress FROM networks where ipaddress like '%1%' ORDER BY ipaddress ASC) and name not like '%_M' and hardware.ID = networks.HARDWARE_ID group by name

Here a sample of the issue:

http://prntscr.com/kmjmyv

For that portable computer:

- Network info: only a bluetooth device info is shown, no IP address
- All computers page shows MAC addresss, no ip address and no gateway address
- Computer details page: it does show the ip address.

A screenshot:

http://prntscr.com/kmjsa5

The issue is not new as I can observe:

http://prntscr.com/kmvqxm

It seems updating the user agent makes no difference.

**Comment by pchamo** [comment]
I revised the Linux computer and found a MAC address diferent from the one in networks table. How can that be possible? I delete the wrong ocs entry from the ocs database and send a new inventory and that solved the issue por that computer. So for that case, my conclusion is that it was the linux agent fault. It's so demanding to have all the inventories ok :(

**Comment by pchamo** [comment]
I updated 2 ocs windows agent and that solved the issue for those computers, but I still have 2 windows computers with the last ocs agent. In any case, shouldn't the ocsinventory server show a warning of these inconsistences?

**Comment by charleneauger** [comment]
Hi @pchamo ,

It is not possible to put a warning on the server every time our agents are updated because for those who have an old version of the agents it will show them an immeasurable list of warning.
We therefore assume that the agent is updated by the users.

Regards,
Charlene Auger

**Comment by charleneauger** [comment]
@pchamo, however this information will be present in the OCS documentation :)
