### ISSUE TITLE
documentation issue

### ISSUE THREAD

**Issue by StCyr** [OCSInventory-NG/OCSInventory-ocsreports#569]
There's an error in https://wiki.ocsinventory-ng.org/03.Management-console-and-its-advanced-features/Using-computers-groups/#using-dynamic-groups 

> Now, you can view your new **static** group, as described before, by clicking "Groups" and "Dynamics groups" tab.

Should be "dynamic" obviously.

**Comment by Scifire** [comment]
I would say the correct place for this issue would be: https://github.com/OCSInventory-NG/Wiki/issues

**Comment by gillesdubois** [comment]
Hi, 

Thx for your report. 
Indeed @Scifire https://github.com/OCSInventory-NG/Wiki/issues is the good place.

I'm closing this issue. @StCyr please reopen it in the Wiki repo :) 

Regards,
Gilles Dubois.
