### ISSUE TITLE
"Search with various criteria broken"?

### ISSUE THREAD

**Issue by StCyr** [OCSInventory-NG/OCSInventory-ocsreports#570]
### General informations
Operating system :  Ubuntu 16.04

### Server installation method ( Only one choice )
- [ ] RPM Package
- [ ] Install SH
- [X] Manual installation

### Server informations
Php version : 
Mysql / Mariadb / Percona version : 
Apache version : 

### OCS Inventory informations
Ocsreports version : 2.5

### Problem's description

"Search with various criteria" feature seems badly broken in 2.5.

I've various problems, but the main one I want to report here is a problem finding computers affected by a deployment.

For example, if I come from the "package activation" page, via a package's deployment statistic, and clicking on the number corresponding to the number of computers with status "SUCCESS" for this package, I land onto such a page (which is hardly understandable)

![image](https://user-images.githubusercontent.com/8179031/44844347-f901c400-ac4a-11e8-9080-164558287a3d.png)

After such a search, I can click on any other package's deployment statistic, I'll always land to the same page as above; It seems like the query parameters aren't updated !?!

Also, i can't get the "Search with various criteria" feature working to directly look for computers having a particular package deployed.

For example, when I try to look for all computers with package "Java*" deployed, I get the following results though about 97 computers should be matching:

![image](https://user-images.githubusercontent.com/8179031/44844661-d15f2b80-ac4b-11e8-8ca8-3a9d60957a2f.png)

As always, I'm available for help if needed. 

Br,

Cyrille

**Comment by gillesdubois** [comment]
Hi @StCyr ,

Multi search has been completly rework and thus might be seen as "harded"
However, a lot of new functionnalities has been added such as the search on the entire database.

The mutli search has been fixed a lot recently, you can use the master trunk if you want to help us to improve it.

Regards,
Gilles Dubois.

**Comment by charleneauger** [comment]
Hi @StCyr ,

Would it be possible to have the query generated with the search for deployed packages?
Thank's !

Regards,
Charlene Auger

**Comment by StCyr** [comment]
Hi @charleneauger 

Here's a screenshot:

![image](https://user-images.githubusercontent.com/8179031/44899937-8a347180-ad03-11e8-9a50-0bb43c34c265.png)

And, here's the query in text

```
SELECT SQL_CALC_FOUND_ROWS hardware.ID AS hardwareID , hardware.DEVICEID AS hardwareDEVICEID , hardware.NAME AS hardwareNAME , hardware.WORKGROUP AS hardwareWORKGROUP , hardware.USERDOMAIN AS hardwareUSERDOMAIN , hardware.OSNAME AS hardwareOSNAME , hardware.OSVERSION AS hardwareOSVERSION , hardware.OSCOMMENTS AS hardwareOSCOMMENTS , hardware.PROCESSORT AS hardwarePROCESSORT , hardware.PROCESSORS AS hardwarePROCESSORS , hardware.PROCESSORN AS hardwarePROCESSORN , hardware.MEMORY AS hardwareMEMORY , hardware.SWAP AS hardwareSWAP , hardware.IPADDR AS hardwareIPADDR , hardware.DNS AS hardwareDNS , hardware.DEFAULTGATEWAY AS hardwareDEFAULTGATEWAY , hardware.ETIME AS hardwareETIME , hardware.LASTDATE AS hardwareLASTDATE , hardware.LASTCOME AS hardwareLASTCOME , hardware.QUALITY AS hardwareQUALITY , hardware.FIDELITY AS hardwareFIDELITY , hardware.USERID AS hardwareUSERID , hardware.TYPE AS hardwareTYPE , hardware.DESCRIPTION AS hardwareDESCRIPTION , hardware.WINCOMPANY AS hardwareWINCOMPANY , hardware.WINOWNER AS hardwareWINOWNER , hardware.WINPRODID AS hardwareWINPRODID , hardware.WINPRODKEY AS hardwareWINPRODKEY , hardware.USERAGENT AS hardwareUSERAGENT , hardware.CHECKSUM AS hardwareCHECKSUM , hardware.SSTATE AS hardwareSSTATE , hardware.IPSRC AS hardwareIPSRC , hardware.UUID AS hardwareUUID , hardware.ARCH AS hardwareARCH , hardware.CATEGORY_ID AS hardwareCATEGORY_ID , download_history.HARDWARE_ID AS download_historyHARDWARE_ID , download_history.PKG_ID AS download_historyPKG_ID , download_history.PKG_NAME AS download_historyPKG_NAME FROM hardware INNER JOIN download_history on hardware.id = download_history.hardware_id WHERE download_history.PKG_NAME LIKE '%Java*%' GROUP BY hardware.id order by hardwareDEVICEID asc limit 0 , 10 
```

**Comment by StCyr** [comment]
Also, PKG_NAME is always NULL here:

```
mysql> select * from download_history where PKG_NAME IS NOT NULL;
Empty set (0.00 sec)
```

```
mysql> select count(*) from download_history where PKG_NAME IS NULL;
+----------+
| count(*) |
+----------+
|     2576 |
+----------+
```
