### ISSUE TITLE
"All computers (replay)" doesn't work

### ISSUE THREAD

**Issue by StCyr** [OCSInventory-NG/OCSInventory-ocsreports#572]
When editing a dynamic group, the "All computers (replay)" button doesn't seem to work

### General informations
Operating system : Ubuntu 16.04

### Server installation method ( Only one choice )
- [ ] RPM Package
- [ ] Install SH
- [X] Manual installation

### Server informations
Php version : 
Mysql / Mariadb / Percona version : 
Apache version : 

### OCS Inventory informations
Ocsreports version : 2.5

### Problem's description

When editing a dynamic group, clicking the "All computers (replay)" button doesn't return any result.

I solved it by changing line 375 in file `ms_group_show.php` from
`$tab_id[] = $value["HARDWARE_ID"];` 
to
 `$tab_id[] = $value["ID"];`

However, this change might not work in some other cases (I think about cases when the user is restricted from viewing some computers) as the code seems to refer to HARDWARE_ID in some cases:

```
      $tab_list_sql = regeneration_sql($valGroup["xmldef"]);
        $i = 1;
        $tab_id = array();
        while ($tab_list_sql[$i]) {
            if ($tab_id != array()) {
                if (strtolower(substr($tab_list_sql[$i], 0, 19)) == "select distinct id ") {
                    $tab_list_sql[$i] .= " and id in (" . implode(",", $tab_id) . ")";
                } else {
                    $tab_list_sql[$i] .= " and hardware_id in (" . implode(",", $tab_id) . ")";
                                                          ^^^^^^ (REFERENCE TO HARDWARE_ID HERE)
                }
                unset($tab_id);
            }
            $result_value = mysqli_query($_SESSION['OCS']["readServer"], xml_decode($tab_list_sql[$i])) or die(mysqli_error($_SESSION['OCS']["readServer"]));
            while ($value = mysqli_fetch_array($result_value)) {
                $tab_id[] = $value["ID"];
                                          ^^^^^ (HERE IS THE LINE I'VE CHANGED)
            }
            $i++;
```

**Comment by gillesdubois** [comment]
Hi @StCyr ,

This bug has been already fixed in master.
Thanks for your report.

Regards,
Gilles Dubois.
