### ISSUE TITLE
Uninstall Linux agent

### ISSUE THREAD

**Issue by inferno66** [OCSInventory-NG/OCSInventory-ocsreports#573]
It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.

General informations
Operating system : Centos 7

Server installation method ( Only one choice )
  RPM Package
[ X] Install SH
  Manual installation
Server informations
Php version : 7.1
Mysql / Mariadb / Percona version : Mysql 507
Apache version : 2.4.27

OCS Inventory informations
Ocsreports version : 2.5

Problem's description :  

Hello,

I want to uninstall an old Linux Agent (installed with the Makefile procedure) in order to install the new agent (but from RPM this time).
The make uninstall is not working, so could you please tell me how to do it?
Or maybe just directly install the new agent from RPM?

Best regards

**Comment by charleneauger** [comment]
Hi @inferno66 ,

You're not in the right category to report this bug, please re-open this issue in the Unix agent : [Here](https://github.com/OCSInventory-NG/UnixAgent/issues)

Regards,
Charlene Auger
