### ISSUE TITLE
Getting the list of computers with a specific deployment state of a package only work once

### ISSUE THREAD

**Issue by StCyr** [OCSInventory-NG/OCSInventory-ocsreports#574]
### General informations
Operating system : 

### Server installation method ( Only one choice )
- [ ] RPM Package
- [ ] Install SH
- [X ] Manual installation

### Server informations
Php version : 
Mysql / Mariadb / Percona version : 
Apache version : 

### OCS Inventory informations
Ocsreports version : 2.5

### Problem's description

When viewing a package's deployment statistic (function "tele_stat"), 

![image](https://user-images.githubusercontent.com/8179031/44904836-9b37af80-ad10-11e8-8f5e-77c5833375ac.png)

and you click on a number in the table, you get redirected to the "visu_search" function with the corresponding parameters:

![image](https://user-images.githubusercontent.com/8179031/44904775-704d5b80-ad10-11e8-8354-81fef4392e95.png)

This functionality seems to work only once: After this call to the "visu_search" function, if you do the steps above for another package, you'll continue to call the "visu_search" function with the parameters corresponding to the 1st call you made.

### Possible solution

Adding an `unset($_SESSION['OCS']['multi_search']['devices']);` line in file ms_multi_search.php seems to solve the issue, but it's quite invasive and should be further tested.

```
if(isset($protectedGet['prov'])){
  if($protectedGet['prov'] == 'allsoft'){
    $search->link_multi($protectedGet['prov'], $protectedGet['value']);
  }elseif($protectedGet['prov'] == 'ipdiscover1'){
    $search->link_multi($protectedGet['prov'], $protectedGet['value']);
  }elseif($protectedGet['prov'] == 'stat'){
    $options['idPackage'] = $databaseSearch->get_package_id($protectedGet['id_pack']);
    $options['stat'] = $protectedGet['stat'];
    unset($_SESSION['OCS']['multi_search']['devices']);
    $search->link_multi($protectedGet['prov'], $protectedGet['value'], $options);
  }
}
```

This also requires to remove the test `if(!array_key_exists('stat',$_SESSION['OCS']['multi_search']['devices']))` from the `link_multi` function in file `Search.php`:

```
          case 'stat':
//            if(!array_key_exists('stat',$_SESSION['OCS']['multi_search']['devices'])){
              $_SESSION['OCS']['multi_search'] = array();
              $_SESSION['OCS']['multi_search']['devices']['stat'] = [
                  'fields' => 'NAME',
                  'value' => 'DOWNLOAD',
                  'operator' => 'EQUAL',
              ];
```

### Additionnal issue
The problem and the possible solution described here  don't seem to solve all issue with this functionality: It seems that calling the "visu_search" function for all computers having a package deployment in error never work. 

This seems related to the `link_multi()` function in file `Search.php` which doesn't seem able to handle other deployment state than `SUCCESS` and `WAITING NOTIFICATION`:

```
              if($option['stat'] == 'SUCCESS'){
                $value_stat = 'SUCCESS';
                $operator_stat = 'EQUAL';
              }elseif($option['stat'] == 'WAITING NOTIFICATION'){
                $value_stat = '';
                $operator_stat = 'ISNULL';
              }
```

Replacing the above test by the following works better:

```
              if($option['stat'] == 'WAITING NOTIFICATION'){
                $value_stat = '';
                $operator_stat = 'ISNULL';
              }elseif($option['stat'] == '***All the errors***'){
                $value_stat = 'ERR';
                $operator_stat = 'LIKE';
              }else{
                $value_stat = $option['stat'];
                $operator_stat = 'EQUAL';
```

Though, it's still not perfect as '***All the errors***' should probably be translated to `tvalue like 'EXIT_CODE%' or tvalue like 'ERR%'` rather than just `tvalue like 'ERR%'`

**Comment by charleneauger** [comment]
Hi @StCyr ,

A fix has already been made for this bug.
Can you try and tell me again if the bug is still present on your reports?
PR : #539 

Regards,
Charlene Auger

**Comment by StCyr** [comment]
Hi @charleneauger 

PR #539 fixes this issue.

Thanks 

Cyrille
