### ISSUE TITLE
Importing data from plugins is faulty

### ISSUE THREAD

**Issue by dannyl2912** [OCSInventory-NG/OCSInventory-ocsreports#575]
### General informations
Operating system : Centos 7

### Server installation method ( Only one choice )
- [x] RPM Package
- [ ] Install SH
- [ ] Manual installation

### Server informations
Php version : 5.4.16
Mariadb  : 5.5.60
Apache version :  2.4.6

### OCS Inventory informations
Ocsreports version : 2.5.0

### Problem's description

Hello I want to use OCS inventory to collect some data of pc's in our domain. That is working for standard settings and standard information.

But now there are some plugins like Teamviewer and MSOfficeKey. They doesn't work as I thing. I found the data in the XML-File, when I manually start the ocsinventory.exe on my Windows-client. The transfer by Windows Agent (2.4.0) or by perl-script on Centos-server doesn't fill the table in the database.

The logs doesn't help me, what's going wrong.

The map.pm-files and the .conf-files are on the correct path. The plugin is correctly installed.

What additional information are needed?

Thanks
dannyl2912

**Comment by charleneauger** [comment]
Hi @dannyl2912 ,

Did you restart your service Apache ?

Regards,
Charlene Auger

**Comment by dannyl2912** [comment]
Hello @Charlene,  

More than one time.

Regards 
dannyl2912

**Comment by dannyl2912** [comment]
Now it's working!

I disabled one line in z-ocsinventory-server.conf because some plugins create errors on loading httpd. So I had uninstalled these plugins (HPmgmt, scheduled Tasks and another one).

Regards
dannyl2912
