### ISSUE TITLE
dynamic groups funtionality broken?

### ISSUE THREAD

**Issue by StCyr** [OCSInventory-NG/OCSInventory-ocsreports#576]
### General informations
Operating system : Ubuntu 16.04

### Server installation method ( Only one choice )
- [ ] RPM Package
- [ ] Install SH
- [X] Manual installation

### Server informations
Php version : 
Mysql / Mariadb / Percona version : 
Apache version : 

### OCS Inventory informations
Ocsreports version : 2.5

### Problem's description
Once I've created a new dynamic group, new computers matching the criterias don't get automatically added to the group.

My group is really simple: The corresponding query is `SELECT DISTINCT hardware.ID FROM hardware INNER JOIN accountinfo on hardware.id = accountinfo.hardware_id WHERE accountinfo.TAG = 'INIT'`

New agents that are tagged "INIT" don't get added automatically to the group; I've to manually add them either 

1) by updating the group via the "Search with various criteria" funtionality 

![houdini](https://user-images.githubusercontent.com/8179031/45083314-c7ca3d80-b0fb-11e8-9da5-b9e84fd8971c.png)

or 

2) including computers statically via the "All computers (replay)" button of the "group_show" function:

![image](https://user-images.githubusercontent.com/8179031/45082808-7a999c00-b0fa-11e8-9ca1-ede1a3e696ea.png)
 
This isn't very dynamic; I don't see the added value compared to static groups. Is this a bug?

Cyrille

**Comment by StCyr** [comment]
Added from the web interface...

**Comment by StCyr** [comment]
hmmm, I'm just discovering the `OCS_OPT_GROUPS_CACHE_REVALIDATE` variable...

**Comment by StCyr** [comment]
The issue might just be a documentation issue in the end...

**Comment by charleneauger** [comment]
Okay, open an issue on the OCS Inventory wiki in this case :)

Regards,
Charlene Auger
