### ISSUE TITLE
Add a functionnality : "ARCHIVE" computer

### ISSUE THREAD

**Issue by AnaelMobilia** [OCSInventory-NG/OCSInventory-ocsreports#58]
Add a functionnality to archive computers.

For example a checkbox on the computer details.

If this checkbow is checked, the computer shouldn't be reported on "Computer unavailable for more than 30 days", nor in software searchs.
It add the ability to get the trace of olds computers no more longer on activity (but have informations on the computer).

Use case can be to get historic, get asset accounting, ability to manage computers put on stock and which are no longer up to date, ...

Regards,
Anael

**Comment by gillesdubois** [comment]
Hi,

Your idea is really interesting. The roadmap will be modified soon, i will submit your feature to the team.
If your idea is approved it will be added to the next release' roadmap (2.3 / 2.4).
You should be notified here in approximately 1 month.

Thanks for contributing to the ocs inventory project.
Regards,
Gilles Dubois.

**Comment by gillesdubois** [comment]
Hi,

FYI your idea has been added to the ocs roadmap :)
You will see it in the 2.3 / 2.4 

Regards, Gilles Dubois.

**Comment by AnaelMobilia** [comment]
Thanks @gillesdubois !
Question : where this roadmap can be found ? ([wiki appears to be outdated](http://wiki.ocsinventory-ng.org/index.php?title=Misc:Roadmap))
Regards,
Anael
