### ISSUE TITLE
Imcompatibilités avec les versions php antérieures à la 5.5

### ISSUE THREAD

**Issue by 3cirbaf** [OCSInventory-NG/OCSInventory-ocsreports#582]
### General informations
Operating system : CentOS 7

### Server installation method
- [X] Install SH

### Server informations
Php version : 5.4.16-45
Mariadb version : 10.1.12
Apache version : 2.4.6

### OCS Inventory informations
Ocsreports version : 2.5

### Problem's description
Problème de compatibilité avec les versions de PHP antérieures à la 5.5

Par exemple lorsque l'on souhaite accéder à la recherche multicritères :

> PHP Fatal error:  Can't use method return value in write context in /usr/share/ocsinventory-reports/ocsreports/require/search/TranslationSearch.php on line 224
>  PHP Fatal error:  Can't use method return value in write context in /usr/share/ocsinventory-reports/ocsreports/require/search/TranslationSearch.php on line 246
> PHP Fatal error:  Can't use method return value in write context in /usr/share/ocsinventory-reports/ocsreports/require/search/TranslationSearch.php on line 255

Les fonctions type `empty($l->g($this->translationArray[$name]))` renvoient une erreur d'analyse. Avant PHP 5.5, la fonction empty() ne supportait que les variables. Pour assurer une retro-compatibilité il faudrait préférer la notation `$l->g($this->translationArray[$name])==false`.

**Comment by gillesdubois** [comment]
Bonjour,

A partir de la 2.5 php5.5 est la minimum requis pour faire fonctionner OCS Inventory.

Cordialement,
Gilles Dubois.
