### ISSUE TITLE
Server configuration parameters not consistents

### ISSUE THREAD

**Issue by StCyr** [OCSInventory-NG/OCSInventory-ocsreports#584]
### General informations
Operating system : Ubuntu 16.04

### Server installation method ( Only one choice )
- [ ] RPM Package
- [ ] Install SH
- [X] Manual installation

### Server informations
Php version : 
Mysql / Mariadb / Percona version : 
Apache version : 

### OCS Inventory informations
Ocsreports version : 2.5

### Problem's description
I've recently updated my `GROUPS_CACHE_OFFSET` and `GROUPS_CACHE_OFFSET` in my apache's configuration file. But, now I see I can change these settings from the GUI also. 

The problem is that these settings are not synchronized between their value in the apache configuration file and what's shown in the GUI (coming from the database's config table).

I have now (after making the change in my apache configuration file) seen that there's a warning in the apache's configuration file about this issue:

```
##############################################################
# ===== OPTIONS BELOW ARE OVERLOADED IF YOU USE OCS GUI =====#
##############################################################

# NOTE: IF YOU WANT TO USE THIS CONFIG FILE INSTEAD, set OCS_OPT_OPTIONS_NOT_OVERLOADED to '1'
```

But, I feel like it is not enough. 

The best solution on the long-term might be to remove these options from the apache's configuration file (why not?).

In the short-middle term that could be good to have a reminder of this issue in the various configuration screens in the GUI.

In the short-term this issue should be better highlighted in the wiki.

**Comment by gillesdubois** [comment]
Hi,

Since the communication server can be a standalone application, i think its better to keep the 2 configuration possibilities.

Regards,
Gilles Dubois.
