### ISSUE TITLE
IP address column displays dash - before IP

### ISSUE THREAD

**Issue by ncanqn** [OCSInventory-NG/OCSInventory-ocsreports#585]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system :  Ubuntu 16.04

### Server installation method ( Only one choice )
- [ ] RPM Package
- [ ] Install SH
- [X] Manual installation

### Server informations
Php version : 7.0.30-0ubuntu0.16.04.1 
Mysql / Mariadb / Percona version : 5.7.23-0ubuntu0.16.04.1
Apache version : 2.4.18 (Ubuntu)

### OCS Inventory informations
Ocsreports version : 2.5

### Problem's description
*Describe your problem here*
If the machine has more than one network interfaces and only one of them has IP address, OCS IP address column displays a dash - before the ip as below:
![2018-08-30 09_59_51-ocs inventory](https://user-images.githubusercontent.com/42762025/45277943-11f15b80-b50e-11e8-8489-0140ab5469d0.png)

**Comment by charleneauger** [comment]
Hi @ncanqn ,

This bug has been fixed with the PR #542 

Regards,
Charlene Auger

**Comment by ncanqn** [comment]
Thanks charleneauger.
