### ISSUE TITLE
switch back to old GUI design

### ISSUE THREAD

**Issue by mtbadi39** [OCSInventory-NG/OCSInventory-ocsreports#59]
Sorry for that; but after 2 weeks of test we downgrade to 2.1 because of bugs, and we were not comfortable with the new look !!
We prefer to switch back to the old style (with icons, popups, ...).

**Comment by gillesdubois** [comment]
Hi,

In the first place thanks for your feedback however, a bug fix 2.2 is coming out soon to fix release related bugs.

Sorry for the inconvenance you meet using the new UI design, i hope newer version will be better for you ;-)

If you want to help us improving the new version you can send us your complete feedback on this issue or at contact@ocsinventory-ng.com

Regards,
Gilles Dubois
