### ISSUE TITLE
Please convert all table to InnoDB

### ISSUE THREAD

**Issue by remicollet** [OCSInventory-NG/OCSInventory-ocsreports#592]
Some tables are still using the old MyISAM format

Especially the deleted_equiv one.

This create issue when a rollback is done, as changes to these tables are NOT reverted.

So we can see, in deleted_equiv
* 123 => 456
* 124 => 456

Which is obviously wrong and breaks GLPI.

**Comment by remicollet** [comment]
@yllen FYI

**Comment by charleneauger** [comment]
Hi @remicollet ,

All table are converted to InnoDB with this fix https://github.com/OCSInventory-NG/OCSInventory-ocsreports/pull/597

Regards,
Charlene Auger
