### ISSUE TITLE
Individual columns search across all columns

### ISSUE THREAD

**Issue by keyone78** [OCSInventory-NG/OCSInventory-ocsreports#596]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### OCS Inventory informations
Ocsreports version :  2.5

### Problem's description
Allow only one specific column search at time .
Global search to wide
*Describe your problem here*
Global search is too wide , and search in column search is allow only one column at a time.
Both search is good but hard to drill down to specific detail.

solution:
remove search in column, and implement individual column search for all columns
allow combination of individual columns search this allow search more refine and specific.

![image](https://user-images.githubusercontent.com/8408374/46512232-67a6f280-c885-11e8-9296-931b1cbc8780.png)

**Comment by charleneauger** [comment]
Hi @keyone78 ,

Your feature is interesting and in the roadmap but is not considered as a high priority development.
But if you want to contribute for this feature, we will be glad to help you ! :)

Regards,
Charlene Auger
