### ISSUE TITLE
self-signed for commnucation between agent and server  and wilcard for gui

### ISSUE THREAD

**Issue by helicrenz** [OCSInventory-NG/OCSInventory-ocsreports#598]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system : Linux x86_64 Debian GNU/Linux 9 (stretch)

### Server installation method ( Only one choice )
- [ ] RPM Package
- [ ] Install SH
- [x] Manual installation

### Server informations
Php version : 7.2.9
Mysql / Mariadb / Percona version :  Debian 9.1 version 10.1.26-MariaDB-0+deb9u1
Apache version : Apache/2.4.25 (Debian

### OCS Inventory informations
Ocsreports version : 2.5

Question

Hello team,

Is it possible to have wildcard cert on gui and self-signed for communication between agent and server?
Since wildcard cert dont work i think this would be better setup if yes. Can someone help give me some guide how to do it.

Regards,

helicrenz

**Comment by Mant1kor** [comment]
@helicrenz use client config file to set client logging and cert usage.

**Comment by helicrenz** [comment]
Hello,

Im not using any cert. I just want to test it first http without cert but it doesnt work. 

Any idea??

**Comment by Mant1kor** [comment]
Use client log to determine problem.

**Comment by helicrenz** [comment]
@Mant1kor  i got this errror error CAnnot establish commnunication : 301 Moved Permanently.

**Comment by Mant1kor** [comment]
Show full log, please.

**Comment by gillesdubois** [comment]
Hi,

Since there is no answer I'm closing this issue.

Regards,
Gilles Dubois.
