### ISSUE TITLE
2.2RC1 la requête visu_computers ne retourne pas le nombre correct d'agents

### ISSUE THREAD

**Issue by StCyr** [OCSInventory-NG/OCSInventory-ocsreports#6]
En partant de la fonction "visu_repart_tag", je clique sur le nombre en regard d'un tag. Dans l'exemple ci-dessous, je clique sur le 24 en regard du tag "ADMIN-LAPTOP":

![untitled](https://cloud.githubusercontent.com/assets/8179031/8907673/dff479f6-3477-11e5-8c5f-32e38584ae5f.png)

J'arrive alors sur le lien function=visu_computers&filtre=a.TAG&value=ADMIN-LAPTOP, et, là, la liste d'agent ne semble plus rien filtrer, il m'affiche les 200 agents de mon inventaire:

![untitled](https://cloud.githubusercontent.com/assets/8179031/8907759/624b7198-3478-11e5-92a9-3eae61e31319.png)

Bàv,

Cyr

**Comment by gillesdubois** [comment]
Salut,

Il es vrai que le "computer per tag" ne remonte pas le nombre de l'argent.
On peux néanmoins utiliser la barre de recherche dans "All computers" pour trouver tous les ordinateurs avec un tag précis..
Je regarde ça des que possible !

Merci pour ton retour,
Gilles Dubois
