### ISSUE TITLE
OCS Inventory NG 2.2 : Profil utilisateur

### ISSUE THREAD

**Issue by ynlamy** [OCSInventory-NG/OCSInventory-ocsreports#60]
Bonjour,

Depuis la mise à niveau en version 2.2 du serveur OCS Inventory NG, il m'est impossible de créer un profil utilisateur. Aucune erreur n'apparaît lors de la validation du formulaire.

Le profil personnalisé créé auparavant, n'est pas répertorié dans la liste des profils disponibles.

Cordialement.

**Comment by gillesdubois** [comment]
Bonjour,

Merci pour votre retour ainsi que vos investissement pour le projet ocs.
La team ocs travail sur ce problème, vous serez notifié dès que le problème sera mise a jour ou résolu.

Cordialement,
Gilles Dubois.

**Comment by mgs-smue** [comment]
Hello,

our workaround is:
copy a profile in the folder /usr/share/ocsinventory-reports/ocsreports/config/profiles
change settings in this file

Greetings

**Comment by gillesdubois** [comment]
Bonjour,

Je n'arrive pas a reproduire votre bug. Apache a t-il les droits d'écriture sur config/profiles ?
La création / modification des profiles fonctionne très bien chez moi.

Cordialement, Gilles Dubois.

**Comment by Poliwhirl** [comment]
Apache a les droits d'écriture sur config/profiles.
Il peut être quelque chose de semblable à cet autre problème? http://ask.ocsinventory-ng.org/3647/problem-creating-administrative-data-items?show=3647#q3647

Merci.

**Comment by gillesdubois** [comment]
J'ai passé en revu le code, le bug a été fix en même temps que le bug des données administratives.
Commit : https://github.com/OCSInventory-NG/OCSInventory-ocsreports/commit/a71d20da202c1bc48ce8bed10307ae2d3f1c80bc

Merci d'avoir contribué au projet ocs :-)
Cordialement, Gilles Dubois

**Comment by mgs-smue** [comment]
I have changed this lines and restarted my server.
The folder /usr/share/ocsinventory-reports/ocsreports/config/profiles is writable by apache.
I´m still unable to create profiles in the web frontend.

Creating an new profile with the commit: a71d20d didn´t fix the issue.
There doesn´t appear a message, wether it was successful or not, debug mode shows nothing more to identify the problems root.

Wouldn´t it be better, to put profiles in the database too?

**Comment by gillesdubois** [comment]
Hi,

If the bug is still, i need more informations. On my dev platform i don't have this bug.
Can you attach some screens in DEBUG mode and your php error log when you create a profile ?

The profiles / ACL system is currently in rework, this won't stay as of now.

Regards,
Gilles Dubois.

**Comment by mgs-smue** [comment]
Hey,

if the profiles system is in rework, we would wait for the new system and update by time.

Filled formular:
![2016-04-19 11_52_26-ocs inventory](https://cloud.githubusercontent.com/assets/18459477/14635484/c9724f9c-0626-11e6-9a68-0d47d4b2e8da.png)

Formular sended:
![2016-04-19 11_53_30-ocs inventory](https://cloud.githubusercontent.com/assets/18459477/14635520/f689f87c-0626-11e6-8bbd-c7fb647c3da9.png)
There is nothing in the logs.

**Comment by Poliwhirl** [comment]
Hi,
I think there is a problem with ms_add_profile.php
At line 14 condition if(!AJAX) shows the form but create_profile is under else clause at line 29.

**Comment by ynlamy** [comment]
Bonjour,

Je vient de tester à mon tour avec la modification proposée le profil n'est pas créé.

Cordialement.

**Comment by gillesdubois** [comment]
Hi can you end me the php error log when you create a profile ?

Regards, Gilles Dubois

**Comment by ynlamy** [comment]
Bonjour,

Lorsque je souhaite créer un nouveau profil, j'obtiens 'erreur PHP suivante :

> Fatal error: Call to a member function getLabelTranslated() on null in /usr/share/ocsinventory-reports/ocsreports/plugins/main_sections/ms_users/views/profile_edit_form.php on line 20

Cordialement.
