### ISSUE TITLE
multisearch export csv missing hostname

### ISSUE THREAD

**Issue by alacn1** [OCSInventory-NG/OCSInventory-ocsreports#608]
### General informations
Operating system : Ubuntu 18.04

### Server installation method
- [x] Manual installation

### Server informations
Php version : 5.6.36
Mysql / Mariadb / Percona version : 5.7.23
Apache version : 2.4.29

### OCS Inventory informations
Ocsreports version : 2.5

### Problem's description
Computers Hostname is missing on csv Download link from MultiSearch.

**Comment by gillesdubois** [comment]
hi @alacn1,

Thx for your contribution, i'm merging your PR !

Regards,
Gilles Dubois.
