### ISSUE TITLE
Passwords can not be changed with php 5.4 because password_compat isn't properly included

### ISSUE THREAD

**Issue by sbraz** [OCSInventory-NG/OCSInventory-ocsreports#61]
`password_compat` is only imported if the user isn't logged in: https://github.com/OCSInventory-NG/OCSInventory-ocsreports/blob/master/require/header.php#L323
It should be imported when editing user credentials so that passwords can be changed.

**Comment by gillesdubois** [comment]
Hi,

Thanks for your contribution and reporting this bug, you will be notified when a fix will be available.

Regards, 
Gilles Dubois.

**Comment by stegfeld** [comment]
so right now with ocsng 2.2 we are not able to set a new admin password, am I right?

**Comment by sbraz** [comment]
If you happen to be using PHP 5.4. Any older or more recent version will work.
In order to change the password, I simply moved the `require` out of the `if` statement.

**Comment by stegfeld** [comment]
could you please provide me more information what to do?
I guess you mean to edit the header.php in part
```

if (!isset($_SESSION['OCS']["loggeduser"])){
        if (!AJAX && !((array_key_exists('HTTP_X_REQUESTED_WITH', $_SERVER) && strtolower($_SERVER['HTTP_X_REQUESTED_WITH']) == 'xmlhttprequest'))){
                if(version_compare(PHP_VERSION, '5.3.7') >= 0){

                        if(version_compare(PHP_VERSION, '5.5') < 0){
                                include_once(PASSWORD_COMPAT);
                        }
                        $values=look_config_default_values('PASSWORD_VERSION');
                        $_SESSION['OCS']['PASSWORD_VERSION'] = $values['ivalue']['PASSWORD_VERSION'];
                        $_SESSION['OCS']['PASSWORD_ENCRYPTION'] =  $values['tvalue']['PASSWORD_VERSION'];
                }else{
                        $_SESSION['OCS']['PASSWORD_VERSION'] = false;
                        $_SESSION['OCS']['PASSWORD_ENCRYPTION'] = false;
                }
                require_once(BACKEND.'AUTH/auth.php');
        }else{
                header($_SERVER["SERVER_PROTOCOL"]." 401 ". utf8_decode($l->g(1359)));
                die;
        }
}

```

**Comment by sbraz** [comment]
I think putting `include_once(PASSWORD_COMPAT);` before the `if` is enough.

**Comment by stegfeld** [comment]
i put the include_once(PASSWORD_COMPAT); before the first if 
apache error log when trying to change the password:
```
[Fri Apr 15 11:18:02 2016] [error] [client xxx] PHP Fatal error:  Call to undefined function password_hash() in /usr/share/ocsinventory-reports/ocsreports/require/function_users.php on line 102, referer: http://xxx/ocsreports/index.php?function=account_config&head=1
[Fri Apr 15 11:18:02 2016] [error] [client xxx] File does not exist: /var/www/usr, referer: http://xxx/ocsreports/index.php?function=account_config&head=1

```

**Comment by LordBat** [comment]
Hi!! i have a similar error when i try to modify the admin password or create a teledeploy user on 2.2 ver.

The apache log says this: 

`[Wed Apr 27 10:07:36 2016] [error] [client 127.0.0.1] File does not exist: /var/www, referer: http://localhost/ocsreports/index.php?function=admin_add_user`


I use Ubuntu 12.04 with PHP 5.3.10-1ubuntu3.22.

Regards!

**Comment by aleoncavallo** [comment]
Hello everybody, I'm using:
- PHP 5.4.45-0+deb7u2 
- Apache/2.2.22 (Debian)
- OCS Inventory server 2.2
on debian wheezy and while changing the password the apache2 error log showed:
Fatal error: Call to undefined function password_hash() in /usr/share/ocsinventory-reports/ocsreports/require/function_users.php on line 102

I didn't dare to upgrade php yet 'cause I'm not sure what it may broke, I solved the issue following sbraz recommendation over function_users.php file.
I wrote 
include_once(PASSWORD_COMPAT);
over line 102 of on file function_users.php

I think it is a sloppy solution, and I'm not sure if that was sbraz real suggestion but it worked for me and I think it could be helpful for stegfeld or another on the same circumstances.

Thanks for your help.
Greetings,
Andrea

**Comment by gnalawade** [comment]
My issues SOLVED: I had similar issues **"could not create new user"** and **"modify password of existing users"**. I have followed above recommendations to added  "**include_once(PASSWORD_COMPAT);** "  into **function_users.php** just above line #102 ( for password modify issues) and above line #126 ( for new user creation )

**Comment by Budzi** [comment]
I had the same issue with version OCS version 2.2.1 on Centos 6.8. I have PHP version 5.3.3 but it still raised the error: 
PHP Fatal error:  Call to undefined function password_hash() in /usr/share/ocsinventory-reports/ocsreports/require/function_users.php on line 104

So I opened the file /usr/share/ocsinventory-reports/ocsreports/require/function_users.php and at the bottom there is this function:


```
// Include password compat for odler php versions at user creation and user modification
function checkForPasswordCompat(){
                if(version_compare(PHP_VERSION, '5.3.7') >= 0){
                        if(version_compare(PHP_VERSION, '5.5') < 0){
                            include_once(PASSWORD_COMPAT);
                        }
                }
}
```

I changed the code of the function where it said '5.3.7' to '5.3.3'. 
Also, you need to change a similar line in file /usr/share/ocsinventory-reports/ocsreports/require/header.php (line 325):
	
```
	/*********************************************************gestion de l'authentification********************************************$

	if (!isset($_SESSION['OCS']["loggeduser"])){
			if (!AJAX && !((array_key_exists('HTTP_X_REQUESTED_WITH', $_SERVER) && strtolower($_SERVER['HTTP_X_REQUESTED_WITH']) == 'xm$
					if(version_compare(PHP_VERSION, '5.3.7') >= 0){
							if(version_compare(PHP_VERSION, '5.5') < 0){
									include_once(PASSWORD_COMPAT);
							}
```
	
Restart httpd after this change.
After this, password changes work as expected.
Hope this helps someone else.

**Comment by gillesdubois** [comment]
Hi, 
php 5.3 is not supported anymore.
Your work around is ok but you should think about upgrade your server.

Regards,
Gilles Dubois
