### ISSUE TITLE
Timeout of package installation is wrongly calculated

### ISSUE THREAD

**Issue by ictchanganeuropacom** [OCSInventory-NG/OCSInventory-ocsreports#610]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system : Debian 9

### Server installation method ( Only one choice )

- [X ] Install SH

### Server informations
Php version : 5.6.35
Mariadb  version :  10.1.26
Apache version : 2.4.25

### OCS Inventory informations
Ocsreports version : 2.4.1

### Problem's description

Hello, i'm tring to teledeploy installation of a big software (16Gb) that usually take over one hour to install, when files are already on computer.

to avoid overloading i've decided to use ocs to only launch a script, that launch the install from the main file server.

i've used from now teledeploy hundred of times without any issue.

this time installation has terminated about 10-15 minutes after starting with the log:

**EXIT_CODE 259

command execution timeout of 7200000 milliseconds reached.**

i've noticed that, an old story windows bugs, timing reported in task manager as cpu idle, take a second for each core, this system has 24 phisical core so each second is "viewed" as 24 seconds from task manager

This can explain why the reported timeout, 2 hours, is in the reality a fraction of this?
And, is possibile to increase this? i've searched for 7200 in every files in the OCS installation folder, and in the DB too, also on the agent computer, but find zero
How to increase the limit?
Thanks

**Comment by gillesdubois** [comment]
Hi,

Package timeout can be set in the configuration page of our webconsole in the deployment tab.

Regards,
Gilles Dubois.
