### ISSUE TITLE
Issue with plugin reporting

### ISSUE THREAD

**Issue by damirkasper** [OCSInventory-NG/OCSInventory-ocsreports#612]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system :  Debian 8 x64

### Server installation method ( Only one choice )
- [ ] RPM Package
- [X] Install SH
- [ ] Manual installation

### Server informations
Php version : 5.6.38
Mysql / Mariadb / Percona version :  (Debian) version 5.5.60-0+deb8u1
Apache version : Apache/2.4.10 (Debian)

### OCS Inventory informations
Ocsreports version : 2.5

### Problem's description
*Describe your problem here*

I'm trying to get the bitlocker plugin working. The VBS file gathers data just fine when i run the debug XML command i can see the contents in the XML. The plugin installs fine on the server, I see the bitlocker section under the computer object in the web ui but the entry stays blank. I see the table created in the DB for the plugin but there is 0 rows added to it. Obviously I'm not sure what is going on but it seems like the agent gathers the right data but it is not being sent or processed by the server?

As a quick test I upgraded to the latest version of the sever builds via the latest git repo contents, that did not fix the issue so I rolled back my server VM snapshot back to the official 2.5 release build.

Testing PC is Windows 10 with latest 2.4 agent.

**Comment by charleneauger** [comment]
Hi @damirkasper ,

Did you restart your apache server after installing the plugin?

Regards,
Charlene Auger

**Comment by damirkasper** [comment]
I didn't specifically restart apache while testing but since this server is only used for this app, I'd rebooted it while testing instead.

I assume there is no known issue with the BitLocker plugin and server? Something isolated most likely to my install?

Thanks!

**Comment by charleneauger** [comment]
Hi @damirkasper ,
The version 2.6 RC of OCS Inventory is available. There has been a complete rework of plugin management.
Can you try again and tell us if this problem is still persistent?

Documentation for the new plugin engine : 
[https://wiki.ocsinventory-ng.org/10.Plugin-engine/Using-plugins-installer/](url)

Plugin Bitlockerstatus rework for the new plugin engine: 
[https://github.com/PluginsOCSInventory-NG/bitlockerstatus/tree/rework](url)

Best regards,
Charlene Auger
