### ISSUE TITLE
jquery is not defined  for boostrap-datetimepicker.js 

### ISSUE THREAD

**Issue by keyone78** [OCSInventory-NG/OCSInventory-ocsreports#613]
![image](https://user-images.githubusercontent.com/8408374/47889935-6b7b6400-de87-11e8-9894-56ab906a1051.png)

### OCS Inventory informations
Ocsreports version : 2.4
is not define every time page load.
can update the boostrap-datetimepicker.js

**Comment by gillesdubois** [comment]
Hi,

This problem has been fixed in 2.6RC

Regards,
Gilles Dubois.
