### ISSUE TITLE
 WHO has deployed WHICH package

### ISSUE THREAD

**Issue by sokatra** [OCSInventory-NG/OCSInventory-ocsreports#614]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system : 
http://demo.ocsinventory-ng.org/index.php?function=server_infos

### Server installation method ( Only one choice )
demo from http://demo.ocsinventory-ng.org/index.php
- [ ] RPM Package
- [ ] Install SH
- [ ] Manual installation

### Server informations
Php version : 
5.6.38
Mysql / Mariadb / Percona version : 
Apache version : 
Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips
### OCS Inventory informations
Ocsreports version : 
2.5
### Problem's description
I can't see who has deployed a package - this information is mandatory, because i run into the issue that suddenly 1 package was deployed to many pc, but no person with admin rights on the server admitted that he has deployed a package to nearly all computers.

It would be nice if i can see WHO has deployed WHICH package

Kind regards sokatra

**Comment by gillesdubois** [comment]
Hi,

This feature will be developped along the new authentication / loggin system

Regards,
Gilles Dubois.

**Comment by sokatra** [comment]
but the data is already there when i search through the logfiles. 
Kind regards
