### ISSUE TITLE
update to 2.5 broke administrativ data

### ISSUE THREAD

**Issue by Scifire** [OCSInventory-NG/OCSInventory-ocsreports#615]
https://github.com/OCSInventory-NG/OCSInventory-ocsreports/issues/548 is closed but not resolved and nobody is answering. 
So this issue is still present.

**Comment by RudyLaurent** [comment]
Hi @Scifire,
Try to install the last nigthly at http://download.ocsinventory-ng.org/nightly/OCSNG_UNIX_SERVER_2.5-nightly-2018-11-28.zip.

Regards,
Rudy Laurent

**Comment by Scifire** [comment]
@RudyLaurent I assume that i should install this nightly to the last version correct?

**Comment by Scifire** [comment]
@RudyLaurent With this update administrative data is still there, looks good so far. 
Will this nightly going into a release?

**Comment by RudyLaurent** [comment]
Hi @Scifire, 
The nightly is build from the master of ocsreports. All functionnalities are here and all fix in this will be in the next release.

Regards,
Rudy Laurent

**Comment by Scifire** [comment]
@RudyLaurent okay should i wait for the next release or update our installation with this nightly?

**Comment by RudyLaurent** [comment]
Hi @Scifire, 
If you want the last functionnalities now and your issue is urgency, you can use the nightly. If you want something very stable, you can wait the next release.

Regards,
Rudy LAURENT

**Comment by pierre-guillot** [comment]
I confirm that work for me : upgrade from 2.4 to 2.5 and many admin infos disappeared. Then upgrade with OCSNG_UNIX_SERVER_2.5-nightly-2018-11-28.zip and admin infos are now available.
