### ISSUE TITLE
Notification email

### ISSUE THREAD

**Issue by adrianobarrosmba** [OCSInventory-NG/OCSInventory-ocsreports#617]
I have ocs-inventory server 2.5 installed on debian 9, I have configured an email notification according to this link http://ask.ocsinventory-ng.org/9931/how-to-use-the-new-notification-feature?show=10168 # a10168, but there is no email from any location!
Any tips on what I can do?

looking at the syslog log, the cron_mailer.php file is running every minute.

**Comment by gillesdubois** [comment]
Hi @adrianobarrosmba ,

I recommand you to take a look at our official documentation : 
http://wiki.ocsinventory-ng.org/03.Management-console-and-its-advanced-features/Configure-mail-notification/

Regards,
Gilles Dubois.

**Comment by azizbaghirov** [comment]
Hi, I am new to OCS and I want to know in which cases does OCS send email?
