### ISSUE TITLE
Search for Video Card

### ISSUE THREAD

**Issue by 0-d** [OCSInventory-NG/OCSInventory-ocsreports#62]
Related to this question: http://ask.ocsinventory-ng.org/2784/how-can-generate-list-machines-using-particular-video-card

"The option to search for a graphics card model search appears to be missing under the "search with various criteria" drop down menu."

**Comment by gillesdubois** [comment]
See https://github.com/OCSInventory-NG/OCSInventory-ocsreports/issues/162
