### ISSUE TITLE
OCS 2.2 : Number of displayed results and sorters not memorized

### ISSUE THREAD

**Issue by doudz** [OCSInventory-NG/OCSInventory-ocsreports#63]
Since OCS 2.2 the number of displayed results aren't memorized anymore (work good in OCS 2.1)
For example If I choose 50,  it's always set to 10 when refreshing the page.

The same problem with sorter, I always want to sort my computer by "last inventory date" but since OCS 2.2 when refreshing the page, the order is lost. 

Thoses bugs appear anywhere in OCS (computer list, deployment list, etc)

**Comment by gillesdubois** [comment]
Hi,

This save feature on table has already been requested, we are working on it (Saving number of entries, Sorting settings)

You will be notified when a fix will be available :-)

Thanks you for contributing ocs project.
Regards, Gilles Dubois.

**Comment by qforgeot** [comment]
Is there a way, to fix the default setting somewhere ? (database, php file ?)
I don't think it has been fixed in 2.2.1. Am I wrong ?

**Comment by cb58** [comment]
Hi,

Datatables can save last state in localStorage or in sessionStorage (page length, sort order, filter, page number, ...). 

For more information :

- https://datatables.net/reference/option/stateSave
- https://datatables.net/reference/option/stateDuration
- https://developer.mozilla.org/en-US/docs/Web/API/Web_Storage_API

A patch is attached to save last state in localStorage. The filter and page number are ignored due to side effects.

This fix is installed on our OCS server for testing.

Regards

**Comment by cb58** [comment]
[function_table_html.php.diff.txt](https://github.com/OCSInventory-NG/OCSInventory-ocsreports/files/401687/function_table_html.php.diff.txt)

**Comment by gillesdubois** [comment]
Hi,

thx for your contribution @cb58 i will try your fix and come back to you later.

Gilles Dubois.

**Comment by zufflaur** [comment]
Thx @cb58, i've make the update of the file but after that, we can't see the inventory (list of computer)
Laurent Zufferey

**Comment by cb58** [comment]
See apache error.log for a PHP error.

My **function_table_html.php** is attached :

[function_table_html.php.txt](https://github.com/OCSInventory-NG/OCSInventory-ocsreports/files/406910/function_table_html.php.txt)

**Comment by zufflaur** [comment]
It's perfect. I've forget a };
The system save a another configuration for each browser ?
I've make the test with firefox (always is ok). After that, i will use safari and the specific configuration was not saved for this browser (i make my configuration after and it's ok for this browser)

**Comment by cb58** [comment]
Yes. Each browser save its last configuration (localStorage).

For further explanation, see : https://developer.mozilla.org/en-US/docs/Web/API/Web_Storage_API
