### ISSUE TITLE
Bad header request

### ISSUE THREAD

**Issue by keyone78** [OCSInventory-NG/OCSInventory-ocsreports#631]
Bad request
Size of a request header field exceeds server limit.

### General informations
Operating system :  redhat

### Server informations
Php version : 5.6.7
Mysql / Mariadb / Percona version : 
Apache version : 2.2.15 red hat

### OCS Inventory informations
Ocsreports version : 2.4

### Problem's description
*Describe your problem here*
Frequently encounter bad request.
This is due to request header reach the limits
as more reports generate the more cookies appending to request header .
-- suggest remove set cookie <-- old code 
![image](https://user-images.githubusercontent.com/8408374/48927589-f80ec480-ef11-11e8-9609-d070657e7eae.png)

the datatable save columns via local storage so isrequire to set cookie.
thanks

**Comment by StCyr** [comment]
Hi,

Could you give me more information how you get this error? 

I can't reproduce it.

Cyrille

**Comment by keyone78** [comment]
in Apache httpd.conf 
created limited ,normally it work, error will not occur.  default is 8k.
LimitRequestFieldSize  1000
