### ISSUE TITLE
OCS Inventory 2.5 "Connected User" not appearing in the OCS Inventory Server

### ISSUE THREAD

**Issue by AliAzizAhmed** [OCSInventory-NG/OCSInventory-ocsreports#639]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system : Centos 7

### Server installation method ( Only one choice )
- [ ] RPM Package
- [x ] Install SH
- [ ] Manual installation

### Server informations
Php version : 7.0.32
Mysql / Mariadb / Percona version : 5.5.60-MariaD
Apache version : 2.4.6

### OCS Inventory informations
Ocsreports version : 2.5

### Problem's description
After installation of the Agent on the end user workstation I am facing 3 issues that requires a quick fix,
(1) for a while the end user name appeared in the "Connected User" details but after few hours it disappeared though the user is logged on and the Inventory shows new "last inventory" time.
(2) As IT we need to login as Admin for configuration of the workstations before handing it over to the users. If we login with our admin account and GPO pushes the policy down the OCS inventory takes the admin as connected user and if we logout and sign in with the end user the "connected user" tab remains blank  though the user is logged on and the Inventory shows new "last inventory" time.
(3) "Computer ID" are not displaying properly, missing numbers.

Please see attached snapshot for reference.

Thanks
![capture](https://user-images.githubusercontent.com/45642719/49555078-965b4b00-f952-11e8-8c0d-d09ab8ad473d.JPG)

**Comment by AliAzizAhmed** [comment]
@charleneauger @gillesdubois Appreciate your support. Thanks

**Comment by gillesdubois** [comment]
Hi,

The new windows agent version fix this behavior.
Thanks for your patience.

Regards,
Gilles Dubois.

**Comment by AliAzizAhmed** [comment]
Hi Gilles,

When is the new windows agent expected to be released? We are currently using 2.4.0

Thanks
Ali
