### ISSUE TITLE
various criteria search bug please fix before 2.6

### ISSUE THREAD

**Issue by sokatra** [OCSInventory-NG/OCSInventory-ocsreports#645]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system : 
http://demo.ocsinventory-ng.org
### Server installation method ( Only one choice )
- [ ] RPM Package
- [ ] Install SH
- [ ] Manual installation

### Server informations
http://demo.ocsinventory-ng.org
version 2.5.0
### OCS Inventory informations
Ocsreports version : 

    5.6.39
    Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips
    MariaDB Server version 5.5.60-MariaDB
    2.5

### Problem's description
various criteria search does not work as expected. empty result with various criteria search
For example i search for 
All Software Name LIKE Office
AND
All Software Name LIKE avira

OCS-Inventory returns nothing
but it should retun at least the computer with the name "ALINE-PC" which has Libeoffice AND
Avira Free Antivirus
Kind regards
Sokatra

**Comment by sokatra** [comment]
it also deosn't work in 2.6 RC - Please please fix it before releasing version 2.6

**Comment by gillesdubois** [comment]
Hi @sokatra ,

Our demo is not up to date atm, that why you may encounter some issues with this one.

Regards,
Gilles Dubois.

**Comment by sokatra** [comment]
Please reopen this ticket - i wrote explicitly that version 2.6 RC is affected and it would be really important if this bug is fixed before releasing a 2.6 final

**Comment by gillesdubois** [comment]
Hi @sokatra,

Indeed, the RC is impacted but one of the latest commit fixed it. If you try the nightly, this problem is no longed present.

Regards,
Gilles Dubois.

**Comment by sokatra** [comment]
Thanks - it works !!

**Comment by sokatra** [comment]
it works, but i closed this thread by accident
