### ISSUE TITLE
Arrays are not allowed in class constants in ExtensionManager.php

### ISSUE THREAD

**Issue by pchamo** [OCSInventory-NG/OCSInventory-ocsreports#646]
### General informations
Operating system : CentOS Linux release 7.6.1810 (Core)

### Server installation method ( Only one choice )
- [ ] RPM Package
- [ ] Install SH
- [X ] Manual installation (OCSNG_UNIX_SERVER_2.6_RC.tar.gz)

### Server informations
Php version :  php-5.4.16-46.el7.x86_64
Mysql / Mariadb / Percona version :  mysql-community-server-5.7.24-1.el7.x86_64
Apache version : httpd-2.4.6-88.el7.centos.x86_64

### OCS Inventory informations
Ocsreports version : 2.6 RC

### Problem's description
I had ocsserver 2.5 and run ./setup.sh to try the last 2.6 RC version. The install process finished ok but accessing to http://ocsserver/ocsreports/, fails with HTTP ERROR 500 and this error message in /var/log/httpd/ssl_error_log:

> PHP Fatal error:  Arrays are not allowed in class constants in /usr/share/ocsinventory-reports/ocsreports/require/extensions/ExtensionManager.php on line 52

The offending code is:

```
    const FORBIDEN_EXT_NAME = [
        ".",
        "..",
        "readme.md"
    ];   
```

So, as a workaround I removed those lines to try the new version. I wonder what is the purpose of those lines and what the risk is of not having those lines.

**Comment by joaofoltran** [comment]
I'm having the same issue, exactly.
Did the same workaround but my extension manager has stopped working after that. I'm considering going back to 2.5.

OS version: CentOS Linux release 7.6.1810 (Core)

Installation method: [X] Manual installation

Php version: php-5.4.16-46.el7.x86_64
Mariadb version: mariadb-server-5.5.60-1.el7_5.x86_64
Apache version: httpd-2.4.6-88.el7.centos.x86_64

OCS Reports version: 2.6 RC

**Comment by gillesdubois** [comment]
Hi,

Update your php to 5.5 and newer will also fix the problem.
5.4 is becoming quite old.

Regards,
Gilles Dubois.

**Comment by pchamo** [comment]
But php 5.4 is the version included in CentOS 7. CentOS 7 is not old. In my opinion that is something that should be considered.

**Comment by joaofoltran** [comment]
Still having the same issue on php 5.5.

[Fri Dec 28 12:14:17.860268 2018] [mpm_prefork:notice] [pid 16713] AH00163: Apache/2.4.6 (CentOS) PHP/5.5.38 mod_perl/2.0.10 Perl/v5.16.3 configured -- resuming normal operations
[Fri Dec 28 12:14:17.860300 2018] [core:notice] [pid 16713] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'
[Fri Dec 28 12:14:23.535820 2018] [:error] [pid 16715] [client xxx.xxx.xxx.xx:59884] PHP Fatal error:  Arrays are not allowed in class constants in /usr/share/ocsinventory-reports/ocsreports/require/extensions/ExtensionManager.php on line 52

**Comment by joaofoltran** [comment]
Another update.

Then i updated php to 5.6 and it works now!

[root@tcsvl1d245 ~]# php -v
PHP 5.6.39 (cli) (built: Dec  5 2018 15:31:03)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies

**Comment by pchamo** [comment]
Thank you :) Are extensions a synomym for plugins? I'm having this: "There is currently no extensions available for installation"

**Comment by joaofoltran** [comment]
Yes, extensions are the same as plugins. I'll try to install some plugins later, you have to get them externally and then add to your server.

**Comment by pchamo** [comment]
Thank you :)

**Comment by gillesdubois** [comment]
Hi,

Ok we will update our code so it will be compatible with 5.5

Regards,
Gilles Dubois.
