### ISSUE TITLE
Enhancement - Relative date in multicriteria searches

### ISSUE THREAD

**Issue by pchamo** [OCSInventory-NG/OCSInventory-ocsreports#649]
### General informations
Operating system : Any

### OCS Inventory informations
Ocsreports version : 2.5-2.6

### Problem's description
Is it possible to add an option to query the number of machines not seen in more than 30 days in Assets category? It seems to me that it is not possible anymore? Please, see: http://ask.ocsinventory-ng.org/10552/summary-info-lost-in-rc-2-6-version

Thank you.

**Comment by gillesdubois** [comment]
Hi @pchamo, 

Date intervals (i.e : -30 days) in Multi criteria is planned, we will introduce it in 2.6 stable or in 2.6.1 depending on the team's availability. 

Gilles Dubois.

**Comment by charleneauger** [comment]
Hi @pchamo ,

Date intervals has been implemented to ocsreports ! So, I close your issue.

Best regards,
Charlene Auger
