### ISSUE TITLE
various criteria search bug please fix before 2.6

### ISSUE THREAD

**Issue by sokatra** [OCSInventory-NG/OCSInventory-ocsreports#650]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system : 
Linux x86_64
4.9.0-8-amd64
Debian GNU/Linux 9 (stretch)
### Server installation method ( Only one choice )
- [ ] RPM Package
- [x ] Install SH
- [ ] Manual installation

### Server informations
Php version : 7.0.33
Mysql / Mariadb / Percona version : Debian 9.6 version 10.1.37-MariaDB-0+deb9u1
Apache version : Apache/2.4.25 (Debian)
### OCS Inventory informations
Ocsreports version : 
2.6RC

### Problem's description
i recreated the ticket, becuase it was closed without considering the real version which is described in the text in ticket (#645) - I am Using 2.6 RC  
various criteria search does not work as expected. empty result with various criteria search
For example i search for
All Software Name LIKE Office
AND
All Software Name LIKE avira

OCS-Inventory returns nothing
but it should retun at least the computer with the name "ALINE-PC" which has Libeoffice AND
Avira Free Antivirus
Kind regards
Sokatra

**Comment by sokatra** [comment]
i only refered to the demo because there it was easier to describe the problem. I have similar data in my test database with version 2.6 RC

**Comment by gillesdubois** [comment]
Hi @sokatra,

Your issue wasn't locked, there was no need to re-open a duplicate.
Closing and locking this one.

Your other issue will be re-opnened.

Regards,
Gilles Dubois.
