### ISSUE TITLE
Software categorization in 2.6 RC

### ISSUE THREAD

**Issue by pchamo** [OCSInventory-NG/OCSInventory-ocsreports#653]
### General informations
Operating system : CentOS 7.6.1810

### Server installation method ( Only one choice )
- [ ] RPM Package
- [ ] Install SH
- [X] Manual installation (OCSNG_UNIX_SERVER_2.6_RC.tar.gz)

### Server informations
Php version : php-5.6.39-1
Mysql / Mariadb / Percona version : mysql-community-server-5.7.24-1
Apache version : httpd-2.4.6-88

### OCS Inventory informations
Ocsreports version : 2.6 RC

### Problem's description
I created 3 test software categories: 

- Microsoft Office
- Test
- Test1

And added these software:

- 2007 Microsoft Office system to Microsoft Office Category
- Mozilla* to Test Category
- PuTTY* to Test1 Category

But nothing is shown:

http://prntscr.com/m2mx4d

Using advanced settings doesn't help:

http://prntscr.com/m2mypv

Under Inventory, All software, nothing is shown, except for All software:

http://prntscr.com/m2mzy8
http://prntscr.com/m2n0rw

Accessing to ocsweb database using phpMyAdmin, I can see this in software_categories table:

http://prntscr.com/m2n1ty

And this in software_category_exp table:

http://prntscr.com/m2n2ci

But in software table, any software has data in the Category column. All the software has a NULL value:

http://prntscr.com/m2n58p

And in the dashboard summary page I'm having this:

http://prntscr.com/m2ndt4

Is it a bug? What am I doing wrong? Thank you.

**Comment by charleneauger** [comment]
Hi @pchamo ,

Did you make an inventory of your machines after creating your software categories ?

Regards,
Charlene Auger

**Comment by pchamo** [comment]
How is that? please. I follow these instructions: https://wiki.ocsinventory-ng.org/03.Management-console-and-its-advanced-features/Using-Software-Categorization/. Thank you.

**Comment by charleneauger** [comment]
Hi @pchamo ,

The software categories are updated with each inventory of your computers.
I notice that this information is missing in our documentation, we will update it as soon as possible.

Best regards,
Charlene Auger

**Comment by pchamo** [comment]
Ok, thank you. I'm going to try updating some computers inventories. I didn't do that because I've been  trying 2.6 RC in a test environment.

**Comment by pchamo** [comment]
Well, I updated the inventory of only one computer, and have this summary result:

http://prntscr.com/m326zc

- Computers in category Test: 16
- Computers in category Test1: 160

For Test category I have these results:

http://prntscr.com/m328a7

But, look at this, please, only a few software was included in Test Category:

http://prntscr.com/m32b4u

And for Test1, these crazy results (filter PuTTY*):

http://prntscr.com/m3291l

Thank you.

**Comment by pchamo** [comment]
Ok, its working but it seems there is a bug if you delete a software category (!) Doing so, it seems category values from softwares table are still present. 

I mean, I deleted the PuTTY category (id 4) and recreated it, and it got id 5, but in the summary page, the number count in PuTTY category is 0. 

I enabled debug mode and see this SQL code:

`... WHERE s.CATEGORY = 5 ...`

So, that's the reason that is showing 0.  Please, look:

http://prntscr.com/m36307

Thank you

**Comment by pchamo** [comment]
Well, I reset all the category values assigning NULL for all of them, but now, nothing is registered. I send new inventories but all are still with NULL values. I wonder how it works of if I'm doing something wrong.

**Comment by gillesdubois** [comment]
Hi @pchamo, 

Categories entries are generated on the fly. Which mean you need to wait or trigger an inventory to have the categories set on a computer.

On a big asset number it might take sometime to have real data.

Regards,
Gilles Dubois.
