### ISSUE TITLE
multicriteria search for checkboxes (radio buttons)

### ISSUE THREAD

**Issue by sokatra** [OCSInventory-NG/OCSInventory-ocsreports#657]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system : 
Debian Linux x86_64
4.9.0-8-amd64
### Server installation method ( Only one choice )
- [ ] RPM Package
- [x ] Install SH
- [ ] Manual installation

### Server informations
Php version : 7.0.33
Mysql / Mariadb / Percona version : 
Debian 9.6 version 10.1.37-MariaDB-0+deb9u1
Apache version : 
Apache/2.4.25 (Debian)

### OCS Inventory informations
Ocsreports version : 2.6RC

### Problem's description
i upgraded from 2.1.2 to 2.6 RC - in 2.6RC i can't search for a administrative data checkbox.
version 2.1.2 has the function "having" - new version 2.6 RC has only 
equal, more than, less than, like, different, is null 

regardless from the fact that my checkboxes imported only as a field, but the chebox state wasn't shown in 2.6 RC.
you should notice that a haven't gone through all version in between 2.1.2 > 2.6

**Comment by sokatra** [comment]
i also recommend that you add checkboxes to the demo server - so it is easier to explain a bug - i don't see any checkbxes or radio button in the demo server 2.5

**Comment by charleneauger** [comment]
Hi @sokatra ,

Mulcriteria has been improved. Since version 2.6 you can search correctly on checkbox and radio button.

Regards,
Charlene Auger
