### ISSUE TITLE
Migrate Front-end UI to bootstrap

### ISSUE THREAD

**Issue by lukBarros** [OCSInventory-NG/OCSInventory-ocsreports#66]
**Migrate Front-end UI to bootstrap, aggregates features:**

- Modern UI
- Responsive for mobile devices
- Compatibility across-browsers: ie, ff, chrome and outhers
- User Experience
- Jquery legacy
- Amazing beautiful components: Panels, Buttons, Icons, Tabs, Msg Alerts...

**Comment by mtbadi39** [comment]
maybe it's duplicated to [#33](https://github.com/OCSInventory-NG/OCSInventory-ocsreports/issues/33)

**Comment by gillesdubois** [comment]
Hi,

Like i said in the other issue that would be a nice feature but nothing planned in the roadmap atm.
I will submit the idea when the new roadmap will be decided ;-)

Regards, Gilles Dubois.
