### ISSUE TITLE
Cannot Install To FreeBSD 12.0 with Mysql 8.0

### ISSUE THREAD

**Issue by matsuoki** [OCSInventory-NG/OCSInventory-ocsreports#665]
### General informations
Operating system :  FreeBSD sv67 12.0-RELEASE FreeBSD 12.0-RELEASE r341666 GENERIC  amd64

### Server installation method ( Only one choice )
- [x] Install SH
- [ ] RPM Package
- [ ] Manual installation

### Server informations
Php version : 7.3.0
Mysql / Mariadb / Percona version : mysql  Ver 8.0.12 for FreeBSD12.0 on amd64 (Source distribution)
Apache version : Apache/2.4.37 (FreeBSD)

### OCS Inventory informations
Ocsreports version : 2.6_RC

### Problem's description
Cannot install OCSInventory-NG by setup.sh.
Faild to check mysql version.

> +----------------------------------------------------------+
> | Checking for database server properties...                      |
> +----------------------------------------------------------+
> 
> Your MySQL client seems to be part of MySQL version FreeBSD12.0.
> [: FreeBSD12: bad number
> [: FreeBSD12: bad number
> Your computer does not seem to be compliant with MySQL 4.1 or higher.
> Do you wish to continue (y/[n])?
> Installation aborted !
> 

> # mysql -V
> mysql  Ver 8.0.12 for FreeBSD12.0 on amd64 (Source distribution)
> 
> # pkg version | grep mysql
> mysql80-client-8.0.12_1            =
> mysql80-server-8.0.12_3            =

Only for this time, i fixed setup.sh to install.

> 152: DB_CLIENT_MAJOR_VERSION=`eval mysql -V | cut -d' ' -f6 | cut -d'.' -f1` >> $SETUP_LOG 2>&1
> 153: DB_CLIENT_MINOR_VERSION=`eval mysql -V | cut -d' ' -f6 | cut -d'.' -f2` >> $SETUP_LOG 2>&1
 
 to 
 
> 152: DB_CLIENT_MAJOR_VERSION=`eval mysql -V | cut -d' ' -f4 | cut -d'.' -f1` >> $SETUP_LOG 2>&1
> 153: DB_CLIENT_MINOR_VERSION=`eval mysql -V | cut -d' ' -f4 | cut -d'.' -f2` >> $SETUP_LOG 2>&1

**Comment by StCyr** [comment]
with mariadb I have:

```
mysql -V
mysql  Ver 15.1 Distrib 10.1.37-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
```

and mith mysql:

```
mysql -V
mysql  Ver 14.14 Distrib 5.7.25, for Linux (x86_64) using  EditLine wrapper
```

**Comment by StCyr** [comment]
The `setup.sh` script that @matsuoki is talking about is in `OCSInventory-Server`

**Comment by StCyr** [comment]
Also, it doesn't look like updating the `setup.sh` script was needed as there's a prompt "Do you wish to continue (y/[n])?"

**Comment by gillesdubois** [comment]
Hi,

Indeed, our focus is more oriented on ""standard"" DEB / RPM Linux distros (like debian / ubuntu server / centos / redhat)
We don't test our setup on BSD like distro.

I think the most viable solution for theses situations is to install ocsinventory components manually.

Regards,
Gilles Dubois.
