### ISSUE TITLE
not possible to edit packages

### ISSUE THREAD

**Issue by StCyr** [OCSInventory-NG/OCSInventory-ocsreports#668]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system :  Ubuntu 18.04

### Server installation method ( Only one choice )
- [X] Debian package
- [ ] RPM Package
- [ ] Install SH
- [ ] Manual installation

### Server informations
Php version : 
Mysql / Mariadb / Percona version : 
Apache version : 

### OCS Inventory informations
Ocsreports version : 2.6-RC

### Problem's description

I believe editing packages from ocsreports, after they've been build and activated should be possible in version 2.6-RC.

Unfortunately, when I click the "edit" button for a package (from the "package activation" page) only a blank page is shown.

### Additional information

Clicking on the "edit" button should open a page like the following: https://ocsreports.acme.org/ocsreports/index.php?function=tele_package&head=1&package=1547548845

**Comment by StCyr** [comment]
I found the following apache error:

```
Wed Jan 23 11:28:11.137113 2019] [php7:error] [pid 14010] [client xxxxxx:51537] PHP Fatal error:  Uncaught Error: Class 'zipArchive' not found in /usr/share/ocsinventory-reports/ocsreports/require/teledeploy/Teledeploy.php:31\nStack trace:\n#0 /usr/share/ocsinventory-reports/ocsreports/plugins/main_sections/ms_teledeploy/ms_tele_package.php(148): Teledeploy->get_package('1548061101')\n#1 /usr/share/ocsinventory-reports/ocsreports/require/header.php(444): require('/usr/share/ocsi...')\n#2 /usr/share/ocsinventory-reports/ocsreports/index.php(44): require('/usr/share/ocsi...')\n#3 {main}\n  thrown in /usr/share/ocsinventory-reports/ocsreports/require/teledeploy/Teledeploy.php on line 31, referer: https://houdini.fw.belnet.be/ocsreports/index.php?function=tele_activate
```

It turns out I didn't had the `php-zip` package installed.

So, it's probably a debian packaging issue only.

I let you close this bug if you think it doesn't affect the source package.

Thanks for the help

Cyrille

**Comment by charleneauger** [comment]
Hi @StCyr ,

Thanks for your report.

Regards,
Charlene
