### ISSUE TITLE
ocs agent macos  2.3.1 wont work without ssl

### ISSUE THREAD

**Issue by helicrenz** [OCSInventory-NG/OCSInventory-ocsreports#674]
t's hard to solve a problem when important details are missing, that why we added this template, to help you and us.

General informations
Operating system :

Server installation method ( Only one choice )
  RPM Package
  Install SH
[X ] Manual installation
Server informations
Php version : 7.2.10
Mysql / Mariadb / Percona version : Debian 9.1 version 10.1.26-MariaDB-0+deb9u1
Apache version : Apache/2.4.25 (Debian)

OCS Inventory informations
Ocsreports version : 2.5

Problem's description
Describe your problem here

i got macos agent 2.3.1 stable version. im trying to make it work without ssl certifcate to connect to the server. 

here my **ocsinventory-agent.cfg**

server=http://XX.XXX.XXX.XX/ocsinventory
logfile=/var/log/ocsng.log
debug=1
lazy=0
ssl=0

im able to ping the server it works on windows agent without ssl cert but for mac im getting error 

**tail -f /var/log/ocsng.log**

Fri Jan 18 15:57:39 2019][debug] No modules will be used.
[Fri Jan 18 15:57:39 2019][debug] Compress::Zlib is not available! The data will be compressed with
             gzip instead but won't be accepted by server prior 1.02
[Fri Jan 18 15:57:39 2019][debug] sending XML
[Fri Jan 18 15:57:39 2019][debug] sending: <?xml version="1.0" encoding="UTF-8"?>
<REQUEST>
  <DEVICEID>BSOs-MacBook-Air-2019-01-18-15-44-01</DEVICEID>
  <QUERY>PROLOG</QUERY>
</REQUEST>
[Fri Jan 18 15:57:40 2019][error] Cannot establish communication : 301 Moved Permanently

anyone have this isse or can someone please assist me?

Regards,

Romeo

**Comment by helicrenz** [comment]
Yes, windows agent work perfectly fine with my ocs server.

**Comment by Oberleutnant20** [comment]
![ocs_macos](https://user-images.githubusercontent.com/18609126/53631368-abbed900-3c12-11e9-83a7-8b7e33be78db.png)

For me it works without problems.
