### ISSUE TITLE
Searches involving dates not working well

### ISSUE THREAD

**Issue by xmun2k** [OCSInventory-NG/OCSInventory-ocsreports#68]
Any sort of queries involving dates are not working well. A simple example, making a search for computers last inventoried before a certain date (in my test scenario 2016-01-01) yields no results - this despite there being ample results listing all machines. Similarly if I search for computers last inventoried after the same date, pretty much the entire inventory is dumped including those inventoried before the selected date.

**Comment by gillesdubois** [comment]
Hi,

Which version of ocs inventory are you using ?

Regards, Gilles Dubois.

**Comment by xmun2k** [comment]
OCS Inventory 2.2 (latest stable)

**Comment by gillesdubois** [comment]
Hi, the bug has been identified.
A fix will be be available asap.

Regards, Gilles Dubois.
