### ISSUE TITLE
Blank page when selecting the Quantity link of a software in Inventory > All software

### ISSUE THREAD

**Issue by adrianolabate** [OCSInventory-NG/OCSInventory-ocsreports#682]
### General informations
Operating system : 
CentOS Linux 7 (Core) / Linux x86_64 / 3.10.0-862.14.4.el7.x86_64 / 

### Server installation method ( Only one choice )
- [ ] DEB Package
- [ ] RPM Package
- [ ] Install SH
- [ ] Manual installation

### Server informations
Php version : 5.4.16
Mysql / Mariadb / Percona version : MariaDB Server version 5.5.60-MariaDB
Apache version : Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips PHP/5.4.16 

### OCS Inventory informations
Ocsreports version : 2.5

### Problem's description
A blank page always appears when I select the link located in the Inventory > All software page (in french: Inventaire > Tous les logiciels).

The link is located in the Quantity column (in french: Quantité) and corresponds to the number of times a software has been found.

Whatever the link and the software, the selection of this link displays a completely blank page.
![ocs-error](https://user-images.githubusercontent.com/4329464/51664938-e05bc700-1fba-11e9-9cca-cb53f3121873.png)

Link when displaying the All Software page : [(http://XXXXXX/ocsreports/index.php?function=visu_all_soft)]

Example of link of Quantity of a software ("NET Core SDK 1.1.0 (x64)") expected to display details of installation and displaying a blank page: [(http://XXXXXX/ocsreports/index.php?function=visu_search&prov=allsoft&value=.NET%20Core%20SDK%201.0.4%20(x64))]

**Comment by charleneauger** [comment]
Hi @adrianolabate ,

Your PHP version is too old. Update your PHP version and the problem will be fixed. 
Please, follow OCS Inventory documentation "Libraries and Modules versions" : 
http://wiki.ocsinventory-ng.org/01.Prerequisites/Libraries-version/

Best regards,
Charlene Auger

**Comment by adrianolabate** [comment]
Hello @charleneauger,

Thanks for the advice.
I confirm the issue is fixed after installation of PHP v7.1.26.

Kind regards,
Adriano Labate
