### ISSUE TITLE
Error with installation

### ISSUE THREAD

**Issue by kiayunan** [OCSInventory-NG/OCSInventory-ocsreports#683]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system : ubuntu-16.04.1-desktop-amd64

### Server installation method ( Only one choice )
- [ ] DEB Package
- [ ] RPM Package
- [ O ] Install SH
- [ ] Manual installation

### Server informations
Php version : PHP 7
Mysql / Mariadb / Percona version : Mysql 
Apache version : 2.4

### OCS Inventory informations
Ocsreports version : 2.4

### Problem's description

Unable to copy files in /usr/share/ocsinventory-reports/ocsreports

I have try to clone the server file direct from github and not working

![virtualbox_ta ocs_24_01_2019_17_02_27](https://user-images.githubusercontent.com/42923102/51670773-efae3500-1ff9-11e9-8a74-714dbd89e636.png)

**Comment by charleneauger** [comment]
Hi @kiayunan ,

Can you give us the logs of ocs_server_setup.log please ?

Regards,
Charlene Auger

**Comment by charleneauger** [comment]
Thanks @kiayunan. 

When installing the server, the ocsreports folder must be in the folder of the server you have cloned.

I advise you to download directly from release:
https://github.com/OCSInventory-NG/OCSInventory-ocsreports/releases
  Or a nightly:
http://download.ocsinventory-ng.org/nightly/

Best regards,
Charlene Auger

**Comment by kiayunan** [comment]
thanks a lot it works
