### ISSUE TITLE
Error in multicriteria search (machines not seen in more than)

### ISSUE THREAD

**Issue by tontonrico** [OCSInventory-NG/OCSInventory-ocsreports#684]
Système
•Linux x86_64
•4.9.0-8-amd64
•7987 Mo
•7223 Mo
•Intel(R) Xeon(R) CPU E5-2630 v3 @ 2.40GHz
•Debian GNU/Linux 9 (stretch)

Logiciel
•7.0.30
•Apache/2.4.25 (Debian)
•Debian 9.1 version 10.1.26-MariaDB-0+deb9u1
•2.5

Hi,
I have a problem with the multicriteria search "machines not seen in more than": no machines are displayed. Here after the error message I have :

`You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ')' at line 3`

**Comment by Yann-TCS** [comment]
Hello,

We have exactly the same issue.

Here is ou setup:

System:
Linux x86_64 3.10.0-957.1.3.el7.x86_64 CentOS Linux 7 (Core)

Software:
PHP Version : 7.2.14
Web Server : Apache/2.4.6 (CentOS) PHP/7.2.14 mod_perl/2.0.10 
Database Server : Perl/v5.16.3 MariaDB Server version 5.5.60-MariaDB
Version OCSReports: 2.5

Regards,
Yann

**Comment by gillesdubois** [comment]
Hi,

This problem has been fixed in 2.6RC.
The stable version will be available soon.

Regards,
Gilles Dubois.
