### ISSUE TITLE
problem to export CSV  in multicriteria search

### ISSUE THREAD

**Issue by tontonrico** [OCSInventory-NG/OCSInventory-ocsreports#685]
Système
•Linux x86_64
•4.9.0-8-amd64
•7987 Mo
•7223 Mo
•Intel(R) Xeon(R) CPU E5-2630 v3 @ 2.40GHz
•Debian GNU/Linux 9 (stretch)

Logiciel
•7.0.30
•Apache/2.4.25 (Debian)
•Debian 9.1 version 10.1.26-MariaDB-0+deb9u1
•OCSng 2.5

Problem : when I do a multicriteria search and want to export in CSV, the CSV created miss the "Machine" column even if I "lock" the result.

**Comment by charleneauger** [comment]
Hi @tontonrico ,

This bug has been fixed on 2.6RC.

Best Regards,
Charlene Auger
