### ISSUE TITLE
Permissions des fichiers contenus dans l'archive tgz

### ISSUE THREAD

**Issue by xdelatour** [OCSInventory-NG/OCSInventory-ocsreports#686]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system : Ubuntu Server 18.04 LTS

### Server installation method ( Only one choice )
- [ ] DEB Package
- [ ] RPM Package
- [X] Install SH
- [ ] Manual installation

### Server informations
Php version : 7.2
Mysql / Mariadb / Percona version : Mariadb 10.1
Apache version : 2.4.29

### OCS Inventory informations
Ocsreports version : 2.5

### Problem's description
*Describe your problem here*

Après extraction de l'archive OCSNG_UNIX_SERVER_2.5.tar.gz, on constate que de nombreux fichiers (dont le fichier texte Changes et des images .png) possèdent la permission 'execute' pour tous les utilisateurs.

**Comment by gillesdubois** [comment]
Bonjour,

Merci de votre retour, la 2.6 sortant cette semaine, nous allons veiller a ne pas ajouter les droits d'écriture aux fichiers de l'archive.

Cordialement,
Gilles Dubois.
