### ISSUE TITLE
Bug with Extensions manager and plugins

### ISSUE THREAD

**Issue by nExNihilo** [OCSInventory-NG/OCSInventory-ocsreports#687]
### General informations
Operating system : **Debian Linux Jessie**

### Server installation method ( Only one choice )

**- [ ] Install SH**

### Server informations
Php version : **7.2**
Mysql / Mariadb / Percona version : **10.1.37-MariaDB-0+deb9u1**
Apache version : **Apache2**

### OCS Inventory informations
Ocsreports version : **2.6RC**

### Problem's description
Hello !
My problem is :

After I tried to install officepack with the extension manager, logoff and logon, ocs became blank, only the ocs logo persist to the top left...

Try to reboot, reinstall the ocs, always the blank page. There is only this message in the web console " Erreur dans les liens source : request failed with status 404 URL de la ressource : http://192.168.1.240/libraries/bootstrap/css/bootstrap.min.css"

My server is on 2.6RC on a Debian linux  4.9.130-2

Thanks

**Comment by charleneauger** [comment]
Hi @nExNihilo ,

Do you have an error in your apache log ?

Regards,
Charlene Auger

**Comment by nExNihilo** [comment]
There is my apache2 error log after a restart

https://pastebin.com/raw/7yPfhhPL

Edit : I had to rename manually the "officepack.conf" in "/etc/ocsinventory-server/plugins/" because the name of the plugin had the first letter in uppercase

Now officepack.conf = PerlModule Apache::Ocsinventory::Plugins::officepack::Map

Something important : The web page became blank after I uploaded the plugin via the web and logout/login. Not after I run the python3 script

**Comment by charleneauger** [comment]
@nExNihilo, after the release of 2.6RC, fix have been made on the extension engine.
Can you install the latest OCS nightly? http://download.ocsinventory-ng.org/nightly/
Tell me if the bug still persists after.

Best regards,
Charlene Auger

**Comment by charleneauger** [comment]
@nExNihilo ,

Is your problem solved ?

Regards,
Charlene Auger

**Comment by nExNihilo** [comment]
Hi, I can't tell you.. Im in holidays, i'll try this next week

**Comment by nExNihilo** [comment]
Hello, its okay now with the nightly version ! Thanks
I have an other problem but now its with the plugin and not the ocsserver
Bye
