### ISSUE TITLE
User creation bug ldap

### ISSUE THREAD

**Issue by elsopapa** [OCSInventory-NG/OCSInventory-ocsreports#69]
When you create a ldap user ask for a password.

**Comment by elsopapa** [comment]
![mandatory](https://cloud.githubusercontent.com/assets/9828829/14509494/f215781c-01a2-11e6-8fd1-e842a8e79815.png)

**Comment by gillesdubois** [comment]
Hi,

This form is not used to connect an LDAP user but to create one on the database.

If you want to connect your ocs to your ldap to be able to connect from them on the ocsreports you need to do the following things : 
http://wiki.ocsinventory-ng.org/index.php/Documentation:OCSsynchroLDAP/fr

NB : Sorry the documentation hasn't been translated and is only available in french. However the screenshot are still accurate.

Regards, Gilles Dubois
