### ISSUE TITLE
Package will not be created

### ISSUE THREAD

**Issue by HassbergKliniken** [OCSInventory-NG/OCSInventory-ocsreports#691]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system : Ubuntu 16.04

### Server installation method ( Only one choice )
- [ ] DEB Package
- [ ] RPM Package
- [x] Install SH
- [ ] Manual installation

### Server informations
Php version : 7.0.32
Mysql / Mariadb / Percona version : 5.7.25-0ubuntu0.16.04.2
Apache version : 2.4.18

### OCS Inventory informations
Ocsreports version : 2.5 

### Problem's description
I want to add a software package under Deployment -> build. The package was libreoffice 6.2.0 with 280mb as a zip file (screenshot #1). On the next screen (screenshot #2) i click on send. Nothing happen, only a white screen. 

Under Package activation is see only my test (screenshot #3)

### Screenshots
![2019-02-11_14h10_38](https://user-images.githubusercontent.com/12759978/52565628-a76b8100-2e07-11e9-8a5f-6215d57825e7.jpg)
![2019-02-11_14h12_39](https://user-images.githubusercontent.com/12759978/52565640-ac303500-2e07-11e9-8f62-cf62169b8487.jpg)
![2019-02-11_14h14_35](https://user-images.githubusercontent.com/12759978/52565645-afc3bc00-2e07-11e9-9ac4-a3fc3a8784cf.jpg)

**Comment by charleneauger** [comment]
Hi @HassbergKliniken ,

Do you have errors in your apache error_log server?

Regards,
Charlene Auger

**Comment by HassbergKliniken** [comment]
Hi Charlene,

yes :)

`[Tue Feb 12 08:19:40.744356 2019] [:error] [pid 10215] [client 192.168.111.12:52307] PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 285877416 bytes) in /usr/share/ocsinventory-reports/ocsreports/require/function_telediff.php on line 396, referer: http://itsm/ocsreports/?function=tele_package
`

Jörg

**Comment by charleneauger** [comment]
Hi @HassbergKliniken ,

Some modifications have been made for the creation of a deployment package on 2.6RC. Can you install a nightly with the latest changes ?
http://download.ocsinventory-ng.org/nightly/
Tell me if the bug persists.

Best regards,
Charlene Auger

**Comment by HassbergKliniken** [comment]
Hello Charlene,

i fix the problem. I set memory_limit to 512M in my php.ini

Jörg

**Comment by charleneauger** [comment]
@HassbergKliniken ,
Ok good ! Thanks for your report ! :)

Best regards,
Charlene Auger
