### ISSUE TITLE
Updated german translation

### ISSUE THREAD

**Issue by steffmeister** [OCSInventory-NG/OCSInventory-ocsreports#696]
### General informations
Operating system : CentOS 7

### Server installation method ( Only one choice )
- [x] DEB Package
- [ ] RPM Package
- [ ] Install SH
- [ ] Manual installation

### Server informations
Php version : 7.3.2
Mysql / Mariadb / Percona version : MariaDB Server version 10.1.38-MariaDB
Apache version : Apache/2.4.6 (CentOS) PHP/7.3.2 mod_perl/2.0.10 

### OCS Inventory informations
Ocsreports version : 2.5

### Problem's description
I attached an updated german translation file, it fixes at least two very wrong strings, which was very annoying... it is not complete however, but please consider this attached file for the next version:
[de_DE.txt](https://github.com/OCSInventory-NG/OCSInventory-ocsreports/files/2899525/de_DE.txt)

**Comment by gillesdubois** [comment]
Hi,

Your translation has been added to the ocsreports master and will be available for the next version (1-2 months)

In the mean time, you can use the nightly builds.

Regards,
Gilles Dubois.
