### ISSUE TITLE
Feature Request - Local Import with CSV

### ISSUE THREAD

**Issue by Oberleutnant20** [OCSInventory-NG/OCSInventory-ocsreports#698]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system : 

### Server installation method ( Only one choice )
- [ ] DEB Package
- [ ] RPM Package
- [ ] Install SH
- [ ] Manual installation

### Server informations
Php version : 
Mysql / Mariadb / Percona version : 
Apache version : 

### OCS Inventory informations
Ocsreports version : 

### Problem's description
In the current version of OCS, it is only possible to import OCS or XML files.
But if you export an old database via OCS it is in CSV format and has to be converted first.
It would be nice if you could save the conversion and upload the file directly via CSV.

**Comment by gillesdubois** [comment]
Hi,

Unfortunatly we don't plan on developping this kind of feature.

Regards,
Gilles Dubois.
