### ISSUE TITLE
IN function=show_ipdiscover , search not working

### ISSUE THREAD

**Issue by keyone78** [OCSInventory-NG/OCSInventory-ocsreports#705]
IN function=show_ipdiscover , search not working

### General informations

Ocsreports version : version 2.5 

### Problem's description
*Describe your problem here*
When search number , no result return
http://demo.ocsinventory-ng.org/?function=show_ipdiscover

**Comment by gillesdubois** [comment]
Hi,

This bug has been resolved with OCSInventory 2.6 which will come out soon.

Regards,
Gilles Dubois.

**Comment by keyone78** [comment]
ok
