### ISSUE TITLE
Utilisateurs - contenu colonnes prénom et nom inversés

### ISSUE THREAD

**Issue by fbomj** [OCSInventory-NG/OCSInventory-ocsreports#707]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system :  CentOS 7.6.1810

### Server installation method ( Only one choice )
- [ ] DEB Package
- [ ] RPM Package
- [X] Install SH
- [ ] Manual installation

### Server informations
Php version : 7.2.12
Mysql / Mariadb / Percona version : 5.5.60
Apache version : 2.4.6

### OCS Inventory informations
Ocsreports version : 2.5

### Problem's description
*Describe your problem here*

Comme indiqué dans le titre de l'issue le contenu des colonnes prénom et nom dans le menu Configuration/Utilisateurs est inversé.

**Comment by gillesdubois** [comment]
Bonjour,

Ce problème à été résolu dans la version 2.6 d'OCS Inventory.

Cordialement,
Gilles Dubois.
