### ISSUE TITLE
access denied autres utilisateur mysql

### ISSUE THREAD

**Issue by Pitboulk** [OCSInventory-NG/OCSInventory-ocsreports#709]
Bonjour, 

j'ai un  soucis avec mes utilisateurs mysql lorsque que je change l'utilisateur je n'ai plus de remonté de données des agents avec l'erreur   ERROR *** AGENT => Failed to send Inventory <HTTP Status Code #500>

dbconfig.inc.php

define("DB_NAME", "ocsweb");
define("SERVER_READ","localhost");
define("SERVER_WRITE","localhost");
define("COMPTE_BASE","ocstest");
define("PSWD_BASE","ocstest");

z-ocsinventory-server.conf
  
Master Database settings
 Replace localhost by hostname or ip of MySQL serve$
  PerlSetEnv OCS_DB_HOST localhost
Replace 3306 by port where running MySQL server, g$
  PerlSetEnv OCS_DB_PORT 3306
Name of database
  PerlSetEnv OCS_DB_NAME ocsweb
  PerlSetEnv OCS_DB_LOCAL ocsweb
User allowed to connect to database
  PerlSetEnv OCS_DB_USER ocstest
Password for user
  PerlSetVar OCS_DB_PWD ocstest

Lorsque je repasse sur les identifiants par default pas de soucis ça fonctionne

version agent ocs : 2.4.0.0
version ocs : 2.6
système : debian 9.6
apache : 2.4.25

d'avance merci : )

**Comment by gillesdubois** [comment]
Bonjour,

Votre utilisateur MySQL a t-il les bons droits de connexion ?
Cela ressemble plus a un soucis d'autorisation lors de la création de l'utilisateur que a un soucis OCS.

Avez-vous des logs apache ?

Cordialement,
Gilles Dubois.

**Comment by Pitboulk** [comment]
Bonjour,

j'ai trouver la réponse, j'avais oublier de changer la configuration des agents.. mais merci d'avoir prit le temps de répondre !
