### ISSUE TITLE
PC change history

### ISSUE THREAD

**Issue by bigbroDOTpro** [OCSInventory-NG/OCSInventory-ocsreports#710]
### General informations
Operating system :  Centos7.4

### Server installation method ( Only one choice )
- [x] Manual installation

### Server informations
Php version :  7.3
 Mariadb / version : 10
Apache version :  

### OCS Inventory informations
Ocsreports version :  last

### Problem's description

The main task is inventory! BUT

I want to have a computer configuration change history

1. computer is inventory (record 1 computer name PC001)

2. RAM stolen from computer (record 2 computer name PC001)

OR

Mail Notification: Part (component) PC001 - added / disappeared

At a MINIMUM, I want a PC001 with a different configuration for hardware (not software) to be added as a duplicate! So, I can track in manual mode what has changed on this PC001.

**Comment by gillesdubois** [comment]
Hi,

This feature is in the roadmap.
However, we are focusing on releasing OCS Inventory 2.6 as a stable version.
It will come later.

Regards,
Gilles Dubois.

**Comment by gillesdubois** [comment]
Hi,

After having a long discussion with the team, we do not plan to do such feature.
However, with a third party soft such as a CMDB you will be able to get the history of a computer changes. (Look at GLPI and iTop product which permit these kind of process)

Regards,
Gilles Dubois.
