### ISSUE TITLE
OCSNG and PHP 7 issue

### ISSUE THREAD

**Issue by unixgate** [OCSInventory-NG/OCSInventory-ocsreports#712]
Dear all

we are running OCSNG on debian since ever but after an PHP upgrade to 7 we have a massive issue: after login we just get a blank page. Several updates to 2.5 and 2.6RC are not solving the issue at. Apache 2 error log just says:

 PHP Fatal error:  main(): The script tried to execute a method or access a property of an incomplete object. Please ensure that the class definition &quot;language&quot; of the object you are trying to operate on was loaded _before_ unserialize() gets called or provide an autoloader to load the class definition in /usr/share/ocsinventory-reports/ocsreports/install.php on line 82, referer: http://wbmon02.wbetalnet.int/ocsreports

Unfortunately we cannot go back to PHP 5.6 because of other apps running on this machine. Any help is highly appreciated

Thanks and best regards
-frank

**Comment by gillesdubois** [comment]
Hi,

Could you try with the master branch of OCSReports ?
This issue seem odd, we are actually developping on PHP 7.0 / 7.1 and 7.2

Regards,
Gilles Dubois.

**Comment by unixgate** [comment]
Hi Gilles

thanks for your reply! Unfortunately no success ... same as before
Anything else I can try?

BR, -frank

**Comment by Kleksiq** [comment]
Hi, 

For me (fresh install on ubuntu server with php 7.2) this helped: 
`apt-get install php-mysqlnd`
Read your apache2 logs to find why you have blank page. For me i had: 
`PHP Fatal error:  Uncaught Error: Call to undefined function mysqli_real_escape_string() `

**Comment by unixgate** [comment]
Sorry for the laty reply. didn't work - see my first posting to this topic. I guess I'll start a fresh install on a brand new machine and try to find the differences manually. Maybe that helps ...
-frank
