### ISSUE TITLE
How to deploy Agents to discovered PC

### ISSUE THREAD

**Issue by proyectotau** [OCSInventory-NG/OCSInventory-ocsreports#717]
Hi all!
Excuse me, if this is an silly question 

How to deploy Agent to hosts in Non-inventoried column?

We actually use GPO, but some hosts are out of AD

Thanks in advance!!

![Screenshot-IpDicover](https://user-images.githubusercontent.com/24544980/56575225-84a6d700-65c5-11e9-9562-5f341b7eb72f.png)

**Comment by proyectotau** [comment]
Hello? Anyone there? ;-)

**Comment by gillesdubois** [comment]
Hi @proyectotau,

In the case the computers aren't in a domain controller or connected to any tool capable of deployment there is basically two options :
- OCS Inventory's agent deployment tool => https://wiki.ocsinventory-ng.org/07.OCS-Tools/OCS-Inventory-NG-Agent-Deployement-Tool/ 
- Manual deployment of the agent => https://wiki.ocsinventory-ng.org/07.OCS-Tools/OCS-Packager/ create a package of the OCS Inventory agent pre-configured with the server and them deploy it manually to each computer

Regards,
Gilles Dubois.
