### ISSUE TITLE
Search computers with various criteria (OCS 2.6)

### ISSUE THREAD

**Issue by Bevito** [OCSInventory-NG/OCSInventory-ocsreports#718]
### General informations
Operating system : Debian Linux 9 Stretch

### Server installation method ( Only one choice )
- [ ] DEB Package
- [ ] RPM Package
- [X] Install SH
- [ ] Manual installation

### Server informations
Php version : 7.0.33-0+deb9u3
Mysql / Mariadb / Percona version : Mariadb 10.1.37-0+deb9u1
Apache version : 2.4.25-3+deb9u7

### OCS Inventory informations
Ocsreports version : 2.6

### Problem's description
Hi, 

I just updated OCS Server and OCS Reports to 2.6 version.
I tried to search computers with various criteria : search IP address '172.16' or '172.17' for example.

In debug mode, I had this : 

Unknown column 'hardware.HARDWARE_ID' in 'where clause'
You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ')' at line 3

The full sql query seems to be : 

SELECT DISTINCT hardware.ID FROM hardware WHERE ( EXISTS (SELECT 1 FROM hardware WHERE hardware.ID = hardware.HARDWARE_ID AND hardware.IPADDR LIKE &#039;%172.16%&#039;) OR ( EXISTS (SELECT 1 FROM hardware WHERE hardware.ID = hardware.HARDWARE_ID AND hardware.IPADDR LIKE &#039;%172.17%&#039;) 

In the table 'hardware', I can't find the field 'HARDWARE_ID'.

Thanks for your help

**Comment by StCyr** [comment]
Could you please be more specific in how you've performed the search.

I've tried the following with 2.6RC and it works nice:

![image](https://user-images.githubusercontent.com/8179031/56811560-46b1e900-6839-11e9-8936-deeb7905327a.png)

**Comment by Bevito** [comment]
Hi, 

I attached a screenshot from my interface. 

![Sélection_004](https://user-images.githubusercontent.com/4436403/56812028-6564af80-683a-11e9-94ab-9d7021587fa6.png)

I hope it can help you.
If you need any others informations, please, let me know.

**Comment by StCyr** [comment]
damned! works here

**Comment by Bevito** [comment]
Thanks for your test. 
Is it possible to test it in 'Debug' mode ? 
When i do, i had this : 
Unknown column 'hardware.HARDWARE_ID' in 'where clause'
You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ')' at line 3

At the end of the page, the SQL query is : 

SELECT DISTINCT hardware.ID FROM hardware WHERE EXISTS (SELECT 1 FROM hardware WHERE hardware.ID = hardware.HARDWARE_ID AND hardware.IPADDR LIKE &#039;%172.16%&#039;) AND EXISTS (SELECT 1 FROM hardware WHERE hardware.ID = hardware.HARDWARE_ID AND hardware.IPADDR LIKE &#039;%172.17%&#039;) 

Maybe there was a problem when upgrading my database from 2.5 to 2.6.

Thanks for your help.

**Comment by charleneauger** [comment]
Hi @Bevito ,

This bug has been fixed with the PR #748 , it was the same problem than #732 

Best Regards,
Charlene Auger
