### ISSUE TITLE
The release OCSNG_UNIX_SERVER-2.2.tar.gz is not Gziped

### ISSUE THREAD

**Issue by pyromanci** [OCSInventory-NG/OCSInventory-ocsreports#72]
I noticed the 
https://github.com/OCSInventory-NG/OCSInventory-ocsreports/releases/download/2.2/OCSNG_UNIX_SERVER-2.2.tar.gz

release file is not actually Gziped. This actualyl confused me a for a few minutes. I tired re-downloading the file a few times. Since I keep getting:

```
tar -zxvf OCSNG_UNIX_SERVER-2.2.tar.gz
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

For giggles I tired without the gzip argument and it worked.

**Comment by gillesdubois** [comment]
Hi,

Yeah the release file is not Gzip and can be confusing.
However we can't change the release file atm but we will gzip the newer release files.

Thanks you for reporting this, taking notes ;-)
Regards, Gilles Dubois.
