### ISSUE TITLE
extension installation - wrong path in manual

### ISSUE THREAD

**Issue by sokatra** [OCSInventory-NG/OCSInventory-ocsreports#720]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system : 

### Server installation method ( Only one choice )
- [ ] DEB Package
- [ ] RPM Package
- [x ] Install SH
- [ ] Manual installation

### Server informations
Php version : 7.0.33-0+deb9u3
Mysql / Mariadb / Percona version :  Mariadb 10.1.37-0+deb9u1
Apache version : deb9u7

### OCS Inventory informations
Ocsreports version : 2.6

### Problem's description
It looks like the the manual here is wrong because it tells us
"First step put your zip file into the ocs "download" folder by default in /usr/share/ocsinventory-reports/ocsreports"
source https://wiki.ocsinventory-ng.org/03.Management-console-and-its-advanced-features/Using-the-Plugins-feature/

the next link says
"Download the plugin, place it on the extensions folder on ocsreports and unzip it"
https://wiki.ocsinventory-ng.org/10.Plugin-engine/Using-plugins-installer/

Kind regards

**Comment by charleneauger** [comment]
Hi @sokatra ,

The first documentation's link has been removed. 

Best regards,
Charlene Auger
