### ISSUE TITLE
Cannot edit packages having text to be shown to the user after installation completion

### ISSUE THREAD

**Issue by StCyr** [OCSInventory-NG/OCSInventory-ocsreports#721]
### General informations
Operating system :  Ubuntu 18.04

### Server installation method ( Only one choice )
- [X] DEB Package
- [ ] RPM Package
- [ ] Install SH
- [ ] Manual installation

### Server informations
Php version : 
Mysql / Mariadb / Percona version : 
Apache version : 

### OCS Inventory informations
Ocsreports version : 2.6RC

### Problem's description
It seems that editing a package containing text to be shown to the user after installation completion doesn't work.

### Step to reproduce
1. Build a simple package and choose "YES" for "Installation completion need user action" and put some text in the Text field.
2. Save the package
3. Click on the package's edit button in the "Package Activation" page

### Actual Result

A blank page 

Following error in apache's error log:

```
[Fri Apr 26 15:25:57.225812 2019] [php7:warn] [pid 19418] [client 10.4.1.142:4052] PHP Warning:  simplexml_load_string(): Entity: line 2: parser error : Input is not proper UTF-8, indicate encoding !\nBytes: 0xE8 0x67 0x75 0x65 in /usr/share/ocsinventory-reports/require/teledeploy/Teledeploy.php on line 47, referer: https://houdini.fw.belnet.be/ocsreports/index.php?function=tele_activate
[Fri Apr 26 15:25:57.226387 2019] [php7:warn] [pid 19418] [client 10.4.1.142:4052] PHP Warning:  simplexml_load_string(): T=&quot;0&quot; NOTIFY_CAN_DELAY=&quot;0&quot; NEED_DONE_ACTION=&quot;1&quot; NEED_DONE_ACTION_TEXT=&quot;Cher coll in /usr/share/ocsinventory-reports/require/teledeploy/Teledeploy.php on line 47, referer: https://houdini.fw.belnet.be/ocsreports/index.php?function=tele_activate
[Fri Apr 26 15:25:57.226774 2019] [php7:warn] [pid 19418] [client 10.4.1.142:4052] PHP Warning:  simplexml_load_string():                                                                                ^ in /usr/share/ocsinventory-reports/require/teledeploy/Teledeploy.php on line 47, referer: https://houdini.fw.belnet.be/ocsreports/index.php?function=tele_activate
[Fri Apr 26 15:25:57.227551 2019] [php7:error] [pid 19418] [client 10.4.1.142:4052] PHP Fatal error:  Uncaught Error: Call to a member function attributes() on boolean in /usr/share/ocsinventory-reports/require/teledeploy/Teledeploy.php:50\nStack trace:\n#0 /usr/share/ocsinventory-reports/plugins/main_sections/ms_teledeploy/ms_tele_package.php(148): Teledeploy->get_package('1556280726')\n#1 /usr/share/ocsinventory-reports/require/header.php(444): require('/usr/share/ocsi...')\n#2 /usr/share/ocsinventory-reports/index.php(44): require('/usr/share/ocsi...')\n#3 {main}\n  thrown in /usr/share/ocsinventory-reports/require/teledeploy/Teledeploy.php on line 50, referer: https://houdini.fw.belnet.be/ocsreports/index.php?function=tele_activate
```

### Expected results

The normal edit page

No error in apache's logs

### Additional info

This is probably just because of special characters in my text.

The package exhibiting the problem here is the one for which the text can be see in https://github.com/OCSInventory-NG/WindowsAgent/issues/129

**Comment by sokatra** [comment]
it works without flaws in 2.6 when i use standard text, but with special characters like $ and ? it shows a blank page when i edit the ppackgae afterwards.
But of i use standard text - i must decativate "Installation completion need user action" and activate it again to edit the text again

**Comment by StCyr** [comment]
The problem seems to be the `fwrite($handinfo, utf8_encode($info));`

Changing it to `fwrite($handinfo, $info);` works

**Comment by StCyr** [comment]
($info should already be properly UTF-8 encoded at that time)
