### ISSUE TITLE
Feature request  scheduled WOL 

### ISSUE THREAD

**Issue by sokatra** [OCSInventory-NG/OCSInventory-ocsreports#724]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system : 
Debian 9.6 Linux x86_64
### Server installation method ( Only one choice )
- [ ] DEB Package
- [ ] RPM Package
- [ x] Install SH
- [ ] Manual installation

### Server informations
Php version : 7.0.33
Mysql / Mariadb / Percona version : Debian 9.6 version 10.1.37-MariaDB-0+deb9u1
Apache version : 2.4.25 (Debian)

### OCS Inventory informations
Ocsreports version : 2.6

### Problem's description
a scheduled wake on lan event for specific clients (perhaps gruped computers) which starts the computers by sending a WOL package - the client gets some packages - and the sever should be able to shutdown the client if nobody is logged in.
so the computer is upd to date if the user starts the computer next day.
problem is how to create all packages in a maner that no user interaction is needed, but the same package could interact with a user  if somebody is logged in.

Kind regards

Soktra

**Comment by charleneauger** [comment]
Hi @sokatra ,

This feature has been added with PR #770 ! :)
You can see the documentation here : [Using Wake On Lan](https://wiki.ocsinventory-ng.org/04.Management-console-and-its-advanced-features/Using-wake-on-lan-feature/) 

Best Regards,
Charlene Auger
