### ISSUE TITLE
Track computer connection Plugin?

### ISSUE THREAD

**Issue by sokatra** [OCSInventory-NG/OCSInventory-ocsreports#725]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system : 

### Server installation method ( Only one choice )
- [ ] DEB Package
- [ ] RPM Package
- [ x] Install SH
- [ ] Manual installation

### Server informations
Php version : 7.0.33
Mysql / Mariadb / Percona version : Debian 9.6 version 10.1.37-MariaDB-0+deb9u1
Apache version : 2.4.25 (Debian)

### OCS Inventory informations
2.6

### Problem's description
Hy ist it possible to show the entry for external IP like it was with an very old plugin?
http://ask.ocsinventory-ng.org/9775/track-computer-connection-plugin?show=9775#q9775
perhaps it is possible to create a Plugin which is compatible to Ocs-Inventory 2.6

Kind regards
Soktra

**Comment by gillesdubois** [comment]
Hi,

You can use the following plugin "last public ip"
http://plugins.ocsinventory-ng.org

Regards,
Gilles Dubois.
