### ISSUE TITLE
Adminstrative Data Checkboxes aren't imported correctly from 2.1.2

### ISSUE THREAD

**Issue by sokatra** [OCSInventory-NG/OCSInventory-ocsreports#727]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system : 

### Server installation method ( Only one choice )
- [ ] DEB Package
- [ ] RPM Package
- [ x] Install SH
- [ ] Manual installation

### Server informations
Php version : 7.0.33
Mysql / Mariadb / Percona version : Debian 9.6 version 10.1.37-MariaDB-0+deb9u1
Apache version : 2.4.25 (Debian

### OCS Inventory informations
Ocsreports version : 2.6

### Problem's description
Hy, i upgraded OCS-Inventory in a test environment step by step from 2.1.2 to 2.2 .....and so forth up to 2.6
Alle my checkboxes fields which were created in ocs 2.1.2 are available in 2.6, but 90 % of them aren't marked (checked)  as in 2.1.2.
If i mark a checkbox in Version 2.6 i am not able to save the check-mark. 
I think i have to recreate all check-marks.
I have so many checkboxes to migrate.
Location, department, owner and so forth
Kind regards

**Comment by gillesdubois** [comment]
Hi,

This problem has been resolved and won't happen with the latest version of OCS (nigthly)

Regards,
GIlles Dubois.
