### ISSUE TITLE
can't update users passwd : password_hash(): Unknown password hashing algorithm: 0

### ISSUE THREAD

**Issue by nomad-fr** [OCSInventory-NG/OCSInventory-ocsreports#728]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system : Debian 9.9

### Server installation method ( Only one choice )
- [ ] DEB Package
- [ ] RPM Package
- [ x ] Install SH
- [ ] Manual installation

### Server informations
Php version : php 7
Mysql / Mariadb / Percona version : Mysql
Apache version : 2.4.25

### OCS Inventory informations
Ocsreports version : 2.6

### Problem's description
*I've got trouble when trying to update users passwd. 
apache log says : 
PHP Warning:  constant(): Couldn't find constant
PHP Warning:  password_hash(): Unknown password hashing algorithm: 0*

**Comment by gillesdubois** [comment]
Hi,
This problem has been fixed with the composer integration.
It will be available in the nightly or in the next release.
Gilles Dubois.
