### ISSUE TITLE
Empty table Hardware, Network, Device

### ISSUE THREAD

**Issue by slawekdw** [OCSInventory-NG/OCSInventory-ocsreports#737]
After upgrade OcsInventory to version 2.6 table Hardware, Devices, Software, Network is empty, 
no data. Still message Processing. In xml file all fields fill data. In attachment screen from web gui.
All perl modules installed.

PHP:    5.6.32
Web Server:    Apache/2.2.24 (Unix) mod_ssl/2.2.24 OpenSSL/1.0.2o DAV/2 mod_fastcgi/2.4.6 PHP/5.6.32 mod_perl/2.0.10 Perl/v5.22.2

![Schowek03](https://user-images.githubusercontent.com/46574829/57778869-46fd2000-7725-11e9-8a71-b6945f316a1d.jpg)
regards

**Comment by gillesdubois** [comment]
Hi,

Latest versions of OCS doesn't have this bug anymore.

Regards,
Gilles Dubois.
