### ISSUE TITLE
[BUG] Cannot merge duplicate entries.

### ISSUE THREAD

**Issue by dytrip77** [OCSInventory-NG/OCSInventory-ocsreports#740]
**OCS Inventory version**
Version : 2.6

**Describe the bug**
Merging duplicate asset is not success. Error showing "Computer locked. Please retry in a few minutes."

**To Reproduce**
1. Go to OCS Inventory main page.
2. Click on Manage -> Duplicates. Click on number counter next to hostname+serial number.
3. Tick all entries or some of the duplicate entries. 
4. See error "Computer locked. Please retry in a few minutes."

**Expected behavior**
Duplicate entries merged successfully..

**Screenshots**
![Screenshot from 2019-05-17 09-52-29](https://user-images.githubusercontent.com/22068278/57897927-88a6db80-7889-11e9-9725-a5681f991d7d.png)

**Comment by gillesdubois** [comment]
Hi,

You should take a look in the locks table or in the mysql lock.
OCS is unable to perform merging in the case the entry is locked in the database.

Regards,
Gilles Dubois.
