### ISSUE TITLE
[BUG] Software to Category - Add Software - Limit to 10 to low

### ISSUE THREAD

**Issue by LMS235** [OCSInventory-NG/OCSInventory-ocsreports#746]
**OCS Inventory version**
Version : 2.6

**Describe the bug**
You cannot scroll through all software when adding software to a category. The filters are limited to 10.

In our example I want to make a category with SAP software, but here we have about 20 different versions in the inventory. But I can only see 10 in the list. The others I have to know and write by hand.

![image](https://user-images.githubusercontent.com/8693550/58020870-b8641680-7b09-11e9-81e2-05a6b39d7268.png)

You see that "SAP Secure Login Client..." is not shown for example.

I didn't find any configuration either.

**Expected behavior**
No limit to 10 Lines

**Comment by charleneauger** [comment]
Hi @LMS235 ,

No configuration is available to modify the software name limit number shown. The limit has been fixed to 10 and we don't have any reason to raise this limit...
We hope you will understand.

Best regards,
Charlene Auger

**Comment by LMS235** [comment]
I see what you mean. Can you at least tell me where the limit is set? Then I can change it myself locally.

**Comment by charleneauger** [comment]
Hi @LMS235 ,

Yes, you can. However OCS Inventory team won't provide any support if a bug appear due to this modification.
You can change the value on ```plugins > main_sections > ms_soft_cat > ms_options_soft_cat.php```. Modify **$MAX_RETURN = 10;**.

Best regards,
Charlene Auger

**Comment by LMS235** [comment]
Thanks, works as expected.
