### ISSUE TITLE
TAR.GZ is a TAR file

### ISSUE THREAD

**Issue by ozit** [OCSInventory-NG/OCSInventory-ocsreports#75]
Hi (same like the issue [n°72](https://github.com/OCSInventory-NG/OCSInventory-ocsreports/issues/72))
After downloading the last "OCS Inventory NG serveur pour Linux/Unix" [link](https://github.com/OCSInventory-NG/OCSInventory-ocsreports/releases/download/2.2/OCSNG_UNIX_SERVER-2.2.tar.gz)   I tryed to do a **tar zxvf** of the file.
But I have an `error

> gzip: stdin: not in gzip format
> tar: Child returned status 1
> tar: Error is not recoverable: exiting now

After minutes, I find that it was not a tar.gz file but only a .tar file
**tar xvf** works !!

**Comment by gillesdubois** [comment]
Hi,

As stated in the issue you referenced we will change this for the next release we can't change the release file now.
Thanks for your reporting.

Regards,
Gilles Dubois.
