### ISSUE TITLE
[BUG]  Uncaught Error: Call to a member function attributes() on boolean

### ISSUE THREAD

**Issue by LMS235** [OCSInventory-NG/OCSInventory-ocsreports#756]
**OCS Inventory version**
Version : 2.6.0

**Describe the bug**
Looks like the same in #721 , i have also implemented the corrections from #734 manualy but still get the following error:

`[Mon Jun 03 16:52:14.644107 2019] [php7:error] [pid 8859] [client <IP>:49177] PHP Fatal error:  Uncaught Error: Call to a member function attributes() on boolean in /usr/share/ocsinventory-reports/ocsreports/require/teledeploy/Teledeploy.php:50\nStack trace:\n#0 /usr/share/ocsinventory-reports/ocsreports/plugins/main_sections/ms_teledeploy/ms_tele_package.php(148): Teledeploy->get_package('1559551617')\n#1 /usr/share/ocsinventory-reports/ocsreports/require/header.php(444): require('/usr/share/ocsi...')\n#2 /usr/share/ocsinventory-reports/ocsreports/index.php(44): require('/usr/share/ocsi...')\n#3 {main}\n  thrown in /usr/share/ocsinventory-reports/ocsreports/require/teledeploy/Teledeploy.php on line 50, referer: https://<ocsserver>/ocsreports/index.php?function=tele_activate`

**Comment by LMS235** [comment]
Looks like the Problem in https://github.com/OCSInventory-NG/WindowsAgent/issues/129 because we use "ß" in our description (german)

**Comment by charleneauger** [comment]
Hi @LMS235 ,

Deployment feature has been reworked on 2.9 version. Please, install the latest version and reopen an issue if the problem persists.

Regards,
Charlene
