### ISSUE TITLE
Release 2.2: 'OCS Inventory NG serveur pour Linux/Unix' file format is wrong

### ISSUE THREAD

**Issue by daks** [OCSInventory-NG/OCSInventory-ocsreports#76]
Hello,
When downloading https://github.com/OCSInventory-NG/OCSInventory-ocsreports/releases/download/2.2/OCSNG_UNIX_SERVER-2.2.tar.gz the file is named as a TAR.GZ archive but it's a TAR archive.
You should use the correct format or change its name.

**Comment by gillesdubois** [comment]
Fixed in 2.2.1
