### ISSUE TITLE
[FEATURE] Multisearch do not return proper data

### ISSUE THREAD

**Issue by MyTheValentinus** [OCSInventory-NG/OCSInventory-ocsreports#778]
**OCS Inventory version**
Version : 2.6

**Describe the bug**
Multiple multisearch conditions do not work. No error in SQL with debug mode enable.

**Screenshots**
![image](https://user-images.githubusercontent.com/6104498/59761280-a7d3c700-9294-11e9-8564-6877e9983d42.png)

**Comment by charleneauger** [comment]
Hi @MyTheValentinus ,

"DIFFERENT" is not working like the way you are using it. However, we are planning to develop a new operator soon like "DOESN'T CONTAINS".

Best regards,
Charlene Auger
