### ISSUE TITLE
[BUG] Waiting notification number not correct

### ISSUE THREAD

**Issue by valouvaliavlo** [OCSInventory-NG/OCSInventory-ocsreports#779]
**OCS Inventory version**
Version : 2.6

**Describe the bug**
Waiting notification number is not correct when deploying package to a group

**To Reproduce**
1. Go to a group
2. Click on statistics for a package being deployed

**Screenshots**
![Capture du 2019-06-20 10-56-27](https://user-images.githubusercontent.com/28919459/59848477-8c84bc80-9365-11e9-913b-c069b3733bfe.png)

**Comment by gillesdubois** [comment]
Hi,

Master branch does not have this problem anymore.
Please update.

Regards,
Gilles.
