### ISSUE TITLE
Processor being incorrectly reported as Pentium II / III

### ISSUE THREAD

**Issue by PCManiacpt** [OCSInventory-NG/OCSInventory-ocsreports#780]
Greetings,

I started recently to use OCSInv./Reports on our computer network.
I have several computers with Core I3 being reported as pentium (II and III).

I have checked windows WMI and it reports the correct processor model.

Please, let me know what details do you need more to fix it.

OCS Inventory 2.6

Here is an example:
(yes, they are running windows XP still, and using the last compatible XP agent and we can't, just yet, upgrade these computers to an higher windows version)
The processor is an "Intel(R) Core(TM) i3 CPU         540  @ 3.07GHz"

[IMA-WSCAMCLARA-2019-06-18-16-31-44.xml.log](https://github.com/OCSInventory-NG/OCSInventory-ocsreports/files/3325124/IMA-WSCAMCLARA-2019-06-18-16-31-44.xml.log)
(please rename to xml)

**Comment by sokatra** [comment]
are you sure that you are not affected by a windows bug which can be solved as explained here?
https://www.itninja.com/blog/view/processor-type-is-reported-incorrectly-as-intel-pentium-iii-xeon-or-intel-pentium-ii-in-the-k1000-s-computer-inventory
plase report what this command will show
wmic path Win32_Processor where DeviceID='CPU0' get name
before and after beeing patched with the microsoft patches.
The patches which are described in the article are hard to find - and/or superseeded

**Comment by PCManiacpt** [comment]
> are you sure that you are not affected by a windows bug which can be solved as explained here?
> https://www.itninja.com/blog/view/processor-type-is-reported-incorrectly-as-intel-pentium-iii-xeon-or-intel-pentium-ii-in-the-k1000-s-computer-inventory
> plase report what this command will show
> wmic path Win32_Processor where DeviceID='CPU0' get name
> before and after beeing patched with the microsoft patches.
> The patches which are described in the article are hard to find - and/or superseded

It does look like the same.
Will check it out and report back. Thank you.

**Comment by charleneauger** [comment]
Hi @PCManiacpt ,

Your problem as been reported as invalid. We will now close this issue.

Best regards,
Charlene Auger
