### ISSUE TITLE
[BUG] searching agents with "Network: IP address" doesn't work 

### ISSUE THREAD

**Issue by StCyr** [OCSInventory-NG/OCSInventory-ocsreports#781]
**OCS Inventory version**
Version : 2.6

**Describe the bug**
I've an agent running Ubuntu 14.04 with both IPv4 and IPv6 addresses.

On its computer details page, ocsi reports the following IP addresses:

::1 / 1 / fe80::fadb:88ff:fe1c:de90 / /10.8.0.11 / <routable_ipv6_prefix>:8008::11 / /fe80::fadb:88ff:fe1c:de90 / /10.25.0.55 / fe80::fadb:88ff:fe1c:de90

If I search for agents with IP address "10.8.0.11", ocsreports doesn't find this agent.

**Expected behavior**
ocsreports should find my agent

**Screenshots**

![image](https://user-images.githubusercontent.com/8179031/60245517-0c0e1080-98bd-11e9-8865-769e33950d45.png)

![image](https://user-images.githubusercontent.com/8179031/60245535-14fee200-98bd-11e9-9bba-92cb417e17b9.png)

**Comment by charleneauger** [comment]
Hi @StCyr ,

Your bug has been fixed with PR [#210](https://github.com/OCSInventory-NG/UnixAgent/pull/210) on Unix Agent.

Best regards,
Charlene
