### ISSUE TITLE
PROBLEM WITH CVE SEARCH

### ISSUE THREAD

**Issue by furska23** [OCSInventory-NG/OCSInventory-ocsreports#782]
Hello , 
I have a problem in the cve search , when i run the cron_cve.php , there is no response from the file and he don't exit , he blocks at the line  `$soft = $cve->getSoftwareInformations();`
 I also tested  `curl_exec($curl); ` with a var_dump and i got a page HTML ...
Thank you..

**Comment by charleneauger** [comment]
Hi @furska23 ,

Please, read the CVE search documentation : [CVE Reporting](https://wiki.ocsinventory-ng.org/04.Management-console-and-its-advanced-features/CVE-Search-management/)
The cron_cve.php execution may be long. 

Regards,
Charlene Auger
