### ISSUE TITLE
[BUG] Missing /vendor/autoload.php file

### ISSUE THREAD

**Issue by jeanbruder** [OCSInventory-NG/OCSInventory-ocsreports#786]
**OCS Inventory version**
Version : ocsreports 2.6RC

**Describe the bug**
[Mon Jul 08 13:33:37.072607 2019] [php7:warn] [pid 1778] [client 10.40.81.1:49648] PHP Warning:  require_once(/usr/share/ocsinventory-reports/ocsreports/vendor/autoload.php): failed to open stream: No such file or directory in /usr/share/ocsinventory-reports/ocsreports/require/header.php on line 31
[Mon Jul 08 13:33:37.072674 2019] [php7:error] [pid 1778] [client 10.40.81.1:49648] PHP Fatal error:  require_once(): Failed opening required '/usr/share/ocsinventory-reports/ocsreports/vendor/autoload.php' (include_path='.:/usr/share/php') in /usr/share/ocsinventory-reports/ocsreports/require/header.php on line 31

**To Reproduce**
1. update using git pull
2. access the report page
3. Got a HTTP error 500

**Expected behavior**
OCS Report should be available

**Screenshots**
![image](https://user-images.githubusercontent.com/7450442/60807447-0ac6c880-a186-11e9-8575-a6017b339b55.png)

**Additional context**
None

**Log file (optional)**
See bug description

**Comment by gillesdubois** [comment]
Hi,

We are using composer now you need to run a composer install / update before accessing the page.
See this link for more infos : https://github.com/OCSInventory-NG/OCSInventory-Server/blob/master/binutils/create-release-tarball.sh 

Documentation will be updated soon.

Regards,
Gilles Dubois.

**Comment by jeanbruder** [comment]
@gillesdubois : Gilles, can You please provide a short howto in order to be abble to use OCS today (composer, scripts, etc ...) ? Regards.

**Comment by gillesdubois** [comment]
You need use to composer from ocsreports' root directory and run the following command : "composer install" 
Of course, you need to have composer installed and configured. (https://getcomposer.org/download/)

Note that you are not supposed to update your reports this way, we recommend to use the nightly releases.

Regards,
Gilles Dubois.

**Comment by jeanbruder** [comment]
@gillesdubois : Reading the bash script helped me, I can now access to the reports again, thanks for Your help.

Can you please explain the recommended way to update, using the nightly release ?

Regards, Jean
