### ISSUE TITLE
User connected collumn on dynamic groups [FEATURE]

### ISSUE THREAD

**Issue by Syl191** [OCSInventory-NG/OCSInventory-ocsreports#787]
**Is your feature request related to a problem? Please describe.**
When we show the request result of a dynamic group there is not the "Connected user" field available 

**Describe the solution you'd like**
Just see the connected user like various criteria research or software categories

**Describe alternatives you've considered**
It's possible to get the user connected but we have to make same request on the various criteria research manually (without dynamic group)

Thanks you very much for the considering.

**Comment by Syl191** [comment]
Hi,
By adding "$l->g(24) => "h.userid" at line 61 and $default_fields2 = array('NAME' => 'NAME', $l->g(46) => $l->g(46), $l->g(820) => $l->g(820), $l->g(34) => $l->g(34), $l->g(24)); at line 65 on the ms_group_show.php file this is working.

Can you add it ? 

Thanks you.

**Comment by charleneauger** [comment]
Hi @Syl191 ,

Your feature has been added. :-)

Best regards,
Charlene Auger
