### ISSUE TITLE
[BUG] Dynamic groups via search: Bad sql queries created 

### ISSUE THREAD

**Issue by StCyr** [OCSInventory-NG/OCSInventory-ocsreports#793]
**OCS Inventory version**
Version :  2.6 

**Describe the bug**
Create a search for 2 different tags:

![image](https://user-images.githubusercontent.com/8179031/61229758-00c63c00-a729-11e9-8b73-c5f60eb5e9f0.png)

And save as dynamic group. The group cannot be used because the query is wrong:

![image](https://user-images.githubusercontent.com/8179031/61229817-22272800-a729-11e9-89f8-3d6c846b469e.png)

**Expected behavior**
The correct SQL statement (eg: SELECT DISTINCT hardware.ID FROM hardware INNER JOIN accountinfo on hardware.id = accountinfo.hardware_id WHERE ( accountinfo.TAG = 'MANAGED_BY_ICT' OR  accountinfo.TAG = **'SELF_MANAGED');

**Comment by Cryzor** [comment]
We have exactly the same issue while searching for 4 different values of registry Keys in an OR statement. 

Error Message:
You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '' at line 1


This is the query we got: 

1) => SELECT DISTINCT hardware.ID 
FROM hardware INNER JOIN registry on hardware.id = registry.hardware_id 

WHERE 
( EXISTS (SELECT 1 FROM registry WHERE hardware.ID = registry.HARDWARE_ID AND registry.REGVALUE LIKE 'SOME_KEY_1') 

OR 

( EXISTS (SELECT 1 FROM registry WHERE hardware.ID = registry.HARDWARE_ID AND registry.REGVALUE LIKE 'SOME_KEY_2') 

OR 

( EXISTS (SELECT 1 FROM registry WHERE hardware.ID = registry.HARDWARE_ID AND registry.REGVALUE LIKE 'SOME_KEY_1') 

OR 

( EXISTS (SELECT 1 FROM registry WHERE hardware.ID = registry.HARDWARE_ID AND registry.REGVALUE LIKE 'SOME_KEY_4')


I`ve logged into the mariadb and could verify that this query is working (check the missing "(" ):

1) => SELECT DISTINCT hardware.ID 
FROM hardware INNER JOIN registry on hardware.id = registry.hardware_id 

WHERE 
( EXISTS SELECT 1 FROM registry WHERE hardware.ID = registry.HARDWARE_ID AND registry.REGVALUE LIKE 'SOME_KEY_1') 

OR 

( EXISTS SELECT 1 FROM registry WHERE hardware.ID = registry.HARDWARE_ID AND registry.REGVALUE LIKE 'SOME_KEY_2') 

OR 

( EXISTS SELECT 1 FROM registry WHERE hardware.ID = registry.HARDWARE_ID AND registry.REGVALUE LIKE 'SOME_KEY_1') 

OR 

( EXISTS SELECT 1 FROM registry WHERE hardware.ID = registry.HARDWARE_ID AND registry.REGVALUE LIKE 'SOME_KEY_4')

**Comment by Syl191** [comment]
Use the latest nighlty, i haved this bug too and i fixed by this.

**Comment by gillesdubois** [comment]
Hi,

Indeed, this problem has been fixe recently.

Regards,
Gilles Dubois.
