### ISSUE TITLE
[FEATURE] Possibility to have fragments deployed using HTTPS

### ISSUE THREAD

**Issue by gillesdubois** [OCSInventory-NG/OCSInventory-ocsreports#794]
**Is your feature request related to a problem? Please describe.**
Info file is retrived by HTTPS but fragments are retrieved by HTTP

**Describe the solution you'd like**
Add the possibility to have fully featured HTTPS deployment

**Comment by charleneauger** [comment]
Hi @gillesdubois ,

Your feature has been added with PR #807 !

Best regards,
Charlene
