### ISSUE TITLE
[BUG] EXT_DL_DIR incorrectly set in ocsinventory-reports-2.6.0-2.el7.ocs.noarch

### ISSUE THREAD

**Issue by sbraz** [OCSInventory-NG/OCSInventory-ocsreports#797]
Hello,
For some reason, in `ocsinventory-reports-2.6.0-2.el7.ocs.noarch`, the following is set in `/usr/share/ocsinventory-reports/ocsreports/var.php`:
```php
define('EXT_DL_DIR', '/var/lib/ocsinventory-reports/extensions/');
```
The problem is that the RPM created the following directory: `/var/lib/ocsinventory-reports/plugins/extensions`.
I don't event understand why `var.php` contains that line since it was reworked before 2.6: https://github.com/OCSInventory-NG/OCSInventory-ocsreports/commit/a0ca659c2cd6f7c841a9dc15d63fb1b4f31288a2

It would also be nice to mention the directory from the RPM in https://github.com/OCSInventory-NG/Wiki/blob/master/english/10.Plugin-engine/Using-plugins-installer.md since it differs from the default.

**Comment by sbraz** [comment]
@kapouik Any chance you could look into that? I just installed ocsreports on another server and the issue is still present.

I would file a pull request but I can't even do that because the `var.php` that you guys use in the RPM is not published on GitHub.

**Comment by whasf** [comment]
Thankfully Google pointed me to this issue, I was pulling my hair out trying to figure why my plugins weren't installing when I was following the documentation and putting them in the (supposed) correct place.

Was getting this message in Apache error_log:

`[Fri Dec 13 08:04:00.329007 2019] [php7:warn] [pid 5669] [client 192.168.4.51:55734] PHP Warning:  scandir(): (errno 2): No such file or directory in /usr/share/ocsinventory-reports/ocsreports/require/extensions/ExtensionManager.php on line 96, referer: http://redfox/ocsreports/index.php?function=extensionmanager`
where it was trying to find the path of "EXT_DL_DIR"

**Comment by gillesdubois** [comment]
Hi,

Last time I installed with RPM I didn't had any issue with the extension directory.
I think this issue is solved.

Regards,
Gilles.
