### ISSUE TITLE
[BUG] Conflicting / undocumented RPM requirements for OCS Inventory 2.6 (installed from repository)

### ISSUE THREAD

**Issue by jwkenney** [OCSInventory-NG/OCSInventory-ocsreports#798]
**OCS Inventory version**

Version : 2.4.1-1 , installed from RPM repository. Attempting upgrade to 2.6.0-2 via yum.

OS Version: Redhat Enterprise Linux 7.6, with RHEL-Optional, EPEL, and OCS Inventory repositories configured

**Describe the bug**

When attempting to perform a yum upgrade from OCS version 2.4.1 to 2.6.0, it throws errors about package dependencies- it says that **remi-release** (the repository) and **PHP 7.1+** are required. However, the Github [release page](https://github.com/OCSInventory-NG/OCSInventory-ocsreports/tree/2.6#dev-notes-) says that PHP 5.3 is the minimum required version, and the [installation guide](https://wiki.ocsinventory-ng.org/03.Basic-documentation/Setting-up-a-OCS-Inventory-Server/#installing-ocs-inventory-server-with-rpm) does not mention Remi repository or PHP 7.1+ as a requirement for the application.

Are these new requirements for OCS-Inventory 2.6? If so, could the documentation and release notes be updated to reflect this, or else could the package be updated to change the dependencies? Redhat only provides PHP v5.4 in their official repositories for RHEL 7, so updating PHP from third-party repositories is a big deal for many Enterprise Linux users.

> Error: Package: ocsinventory-reports-2.6.0-2.el7.ocs.noarch (ocsinventory)`
>            Requires: remi-release
> Error: Package: ocsinventory-reports-2.6.0-2.el7.ocs.noarch (ocsinventory)
>            Requires: php >= 7.1
>            Installed: php-5.4.16-46.el7.x86_64 (@rhel7_x86_64)
>                php = 5.4.16-46.el7
> Error: Package: ocsinventory-reports-2.6.0-2.el7.ocs.noarch (ocsinventory)
>            Requires: php-phpmailer6
> You could try using --skip-broken to work around the problem
> You could try running: rpm -Va --nofiles –nodigest

Below is the dependency list reported from the new package:
[deplist_ocs_2.6.0.txt](https://github.com/OCSInventory-NG/OCSInventory-ocsreports/files/3461792/deplist_ocs_2.6.0.txt)

**To Reproduce**
1. Using RHEL 7.6 (and maybe CentOS 7?) configure repository requirements as noted in [this section](https://wiki.ocsinventory-ng.org/03.Basic-documentation/Setting-up-a-OCS-Inventory-Server/#installing-ocs-inventory-server-with-rpm), then install ocsinventory-server and ocsinventory-reports version 2.4.x using yum
2. Perform a `yum upgrade` to ocsinventory v2.6.0

**Expected behavior**
ocsinventory-server and ocsinventory-reports should not require PHP 7.1+ or remi repository, according to documentation

**Comment by kapouik** [comment]
https://github.com/OCSInventory-NG/Wiki/pull/75

The documentation has been push in sames time than the RPM has been update.

OCSReport must have PHP 7.0 to work correctly now: I made the choice of PHP 7.1 according with PHP official release support.

What need to fix now: there is some references to php 5.5 mini on the wiki to correct and README.md to update too

**Comment by AlKosmos** [comment]
Hi, 
I have the same issue. 
CentOS 7 
Tried to uninstall php -5.4 and install PHP 7.1 the same problem with dependencies.

**Comment by aluiest** [comment]
Additionaly enable remi repo and solved.

**Comment by fourstepper** [comment]
I am upgrading from 2.5 to 2.7 using the rpm and am still getting the following error, despite having remi-repo enabled:
```
Error: Package: ocsinventory-reports-2.7.0-1.el7.ocs.noarch (ocsinventory)
           Requires: php-phpmailer6
```
If I try to manually install the package, I get the following:
```
yum install php-phpmailer6
Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
 * base: mirror.karneval.cz
 * epel: mirror.karneval.cz
 * extras: mirror.karneval.cz
 * remi-php73: remi.mirror.karneval.cz
 * remi-safe: remi.mirror.karneval.cz
 * updates: mirror.karneval.cz
No package php-phpmailer6 available.
Error: Nothing to do
```
The host is CentOS 7, updated
