### ISSUE TITLE
Archive::Zip est obligatoire pour le webservice mais setup.sh ne le dit pas

### ISSUE THREAD

**Issue by StCyr** [OCSInventory-NG/OCSInventory-ocsreports#8]
La directive dans setup.sh est "run "setup.sh" and follow the instructions. If you get a error / warning because of a missing module, install it and retry."

Si on fait confiance a cette directive, on a un système qui ne fonctionne pas pour le webservice (et donc les plugins).

il faudrait que setup.sh teste la présence de Archive::Zip

**Comment by StCyr** [comment]
j'encode vite 2 problèmes pour ne pas les oublier pendant mon we prolongé :-)

**Comment by gillesdubois** [comment]
Si on lis le fichier INSTALL_2.2.txt , celui-ci dit bien que Archive::Zip est nécessaire ...

Néanmoins, il es vrai que ce n'est pas très "user-friendly" que le setup ne prennent pas en charge ...
Je fais les modifs en même temps que : https://github.com/OCSInventory-NG/OCSInventory-ocsreports/issues/9

Merci de contribuer a OCS Inventory NG
Gilles Dubois.

**Comment by gillesdubois** [comment]
Fixed on the commit above :)
