### ISSUE TITLE
New log directories are not rotated

### ISSUE THREAD

**Issue by nirgal** [OCSInventory-NG/OCSInventory-ocsreports#80]
Hi

Version 2.2 introduced 2 directories:
VARLOG_DIR . 'logs'
VARLOG_DIR . 'scripts'

But there is no rotatelog installed by setup.sh. This will eventually fill the disk.

Please provide a way to limit logs size, like ocs-server do.

**Comment by kapouik** [comment]
Is it really usefull to keep this feature ?

This log only write an entry when someone connect in OCSreports and there is a nice page to look a chart to look connexion on time.
Apache allready log all connexion and do it better and there is many tools for visualisation. Only usefull log will be to log all action when you put debug mode (for debug purpose and must not be the normal state).

I prefer ask for remove this feature.

**Comment by gillesdubois** [comment]
:+1:  @kapouik ocs team has to dicuss about this functionnality, not really usefull to keep i think
