### ISSUE TITLE
Multi Step Deployment

### ISSUE THREAD

**Issue by sokatra** [OCSInventory-NG/OCSInventory-ocsreports#801]
**Is your feature request related to a problem? Please describe.**
I can't do real Multi Step Deployment - I can only use dynamic Groups to get similar results

**Describe the solution you'd like**
Some OCS-Inventory Package Creation like available in PDQ Deployment
Multi-Step Packages
https://www.youtube.com/watch?v=SHWl8_eQn_4
Some packages need a reeboot and need to run the bext step after reboot - so we need to have a mechanism which is able to accomplish this

**Describe alternatives you've considered**
A script which can be used to track every step to complete multiple installation steps
https://blogs.technet.microsoft.com/dsheehan/2018/06/10/tracking-and-controlling-powershell-script-execution-via-xml/

**Additional context**
I think this can be accomplished without reconfiguring the agent. It just needs a server logic which acts faster then the dynamic group feature. The success result of one step should immediately trigger the next step without being disturbed by other packages which perhaps will be applied by accident.
I mainly want the developers to think about this feature in future releases.

**Comment by gillesdubois** [comment]
Hi,

Your idea is nice but we decided to not develop it. Of course, you can develop it by your self and we will gladly help you to make it work but this feature was existing in the oldest versions of OCS but have been removed because it was not really used.

Regards,
Gilles Dubois.
