### ISSUE TITLE
pagination reports OCS 2.2RC 

### ISSUE THREAD

**Issue by tiptopnet** [OCSInventory-NG/OCSInventory-ocsreports#804]
Hi
I have installed OCS 2.2RC on Linux
I would like to change the default pagination and get all results in "all computers" page instead to get default result as 10 per page 
I changed in the /usr/share/ocsinventory-reports/ocsreports/libraries/datatable/media/js/jquery.dataTables.js
"aLengthMenu": [[5000], ["All"]],
The menu is updated but when I open the page the default is still showing 10 results
i would like the 331 results displayed without clicking
Thanks for your help
![image](https://user-images.githubusercontent.com/28688186/63596216-00884e80-c5bb-11e9-87f1-2136fe1e8f6e.png)

**Comment by gillesdubois** [comment]
Hi,

Please upgrade to the latest versions.
2.2 is not maintened for at least 2 years.

Regards,
Gilles Dubois.
