### ISSUE TITLE
[BUG] 403 forbidden when agent send inventory

### ISSUE THREAD

**Issue by amiltonjustino** [OCSInventory-NG/OCSInventory-ocsreports#805]
Good night people

I have an ocsinventory server running on Debian 9.9, Apache 2.4.25 and I have a problem on server configuration. The access to / ocsreports is ok, however, when an agent tries to communicate (windows or linux) I get 403 forbidden.

On the agent I execute:
$sudo ocsinventory-agent --server http://myserverip/ocsinventory --user=admin --password=adminpass
And return:
[error] Cannot establish communication : 403 Forbidden

On the server I get this return from access.log:
xxx.xxx.xxx.xxx - - [Aug 25, 2019: 20: 31: 39 -0300] "POST / ocsinventory HTTP / 1.1" 200 470 "-" "OCS-NG_unified_unix_agent_v2.4.2"
xxx.xxx.xxx.xxx - - [Aug 25, 2019: 20: 31: 45 -0300] "POST / ocsinventory HTTP / 1.1" 403 466 "-" "OCS-NG_unified_unix_agent_v2.4.2"

Any ideas what might be wrong?

**Comment by gillesdubois** [comment]
Hi,

Did you see a password on the OCS Inventory communication server (/ocsinventory) ?

Regards,
Gilles Dubois.

**Comment by amiltonjustino** [comment]
Hi, thank you for the response.
I did not put password on communication server /ocsinventory. Unless it comes by default. The .conf is:

  <Location /ocsinventory>
    <IfModule mod_authz_core.c>
      # Apache 2.4
      Require all granted
        </IfModule>
        <IfModule !mod_authz_core.c>
      # Apache 2.2
          order deny,allow
          allow from all
        </IfModule>
        # If you protect this area you have to deal with http_auth_* agent's parameters
        # AuthType Basic
        # AuthName "OCS Inventory agent area"
        # AuthUserFile "APACHE_AUTH_USER_FILE"
        # require valid-user
        SetHandler perl-script
        PerlHandler Apache::Ocsinventory
  </Location>
