### ISSUE TITLE
[BUG] Chevrons

### ISSUE THREAD

**Issue by Parnoud** [OCSInventory-NG/OCSInventory-ocsreports#811]
**OCS Inventory version**
Version : 2.6

**Describe the bug**
Certain caractère ne permette plus la recherche multicritère, exemple >, il est maintenant envoyé sous la forme `&gt;`. On ne peut plus supprimer les lignes via l'interface web qui contiennent &gt;

**BUG**
Il faut deja avoir dans un premier temps des postes avec un tag sous la forme suivante :
AAA
AAA>BBB
AAA>BBB>CCC
AAA>EEE
AAA>EEE>FFF

Maintenant dans inventaire -> machine par tag, nous retrouvons notre arboresence. mais la recherche en haut a droite ne fonctionne pas correctement lorsque nous tapons :
Search : AAA>
Result : None
Alors qu'on devrait avoir :
AAA>BBB
AAA>BBB>CCC
AAA>EEE
AAA>EEE>FFF

Étrangement la requête SQL créée et disponible en mode DEBUG donne le bon résultat via le sgbd.
Lors d'une cherche multicritère avec le choix "ressemble", les soucis est le même mais la requete sql est la bonne est donne le bon résultat sur le sgbd.

Pour finir lors de l'ajout de tags a un utilisateur, si un TAG comprend un ou plusieurs ">" ils seront remplacés par `&gt`; et la ligne ne pourra plus être supprimé par l’interface web.

**Log file (optional)**
Aucune information disponible dans les logs

**Comment by charleneauger** [comment]
Bonjour @Parnoud ,

L'utilisation des chevrons est fonctionnelle depuis la version 2.9.

Cordialement,
Charlène
