### ISSUE TITLE
[BUG] Impossible to compare software version with alpha on or with multiple dot

### ISSUE THREAD

**Issue by charleneauger** [OCSInventory-NG/OCSInventory-ocsreports#812]
**OCS Inventory version**
Version : 2.6

**Describe the bug**
it's impossible to compare software version with alpha on or with multiple dot (exemple : 14.2.56.35412) on dynamic group.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Log file (optional)**
Apache / PHP / System log if needed

**Comment by gillesdubois** [comment]
This issue is a duplicate : closing it : https://github.com/OCSInventory-NG/OCSInventory-ocsreports/issues/946
