### ISSUE TITLE
[BUG] SQL - Software

### ISSUE THREAD

**Issue by Parnoud** [OCSInventory-NG/OCSInventory-ocsreports#813]
**OCS Inventory version**
Version : 2.6

**Describe the bug**
"Inventaire" -> "Tout les logiciels" me un temps excessif a s'afficher >1min.

La requête directement exécuter sur le SGDB donne un résultat :
`6839 rows in set, 65535 warnings (1 min 22.228 sec)`
un show warnings donne cela :
+---------+------+---------------------------------------+
|  Level     | Code | Message                                            |
+---------+------+---------------------------------------+
| Warning | 1292 | Truncated incorrect INTEGER value: '' |
| Warning | 1292 | Truncated incorrect INTEGER value: '' |
| Warning | 1292 | Truncated incorrect INTEGER value: '' |
| Warning | 1292 | Truncated incorrect INTEGER value: '' |

Le requête ne travaille que sur un cœur CPU.

**Log file (optional)**
Time: 190912 10:39:55
User@Host: ocs[ocs] @ localhost [] 
Thread_id: 42  Schema: ocsweb  QC_hit: No
Query_time: 83.240868  Lock_time: 0.000123  Rows_sent: 10  Rows_examined: 2999019
Rows_affected: 0  Bytes_sent: 2922
SET timestamp=1568277595;
SELECT SQL_CALC_FOUND_ROWS  *, count(s.name) as nb, s.name id, sc.CATEGORY_NAME FROM softwares s LEFT JOIN software_categories AS sc ON sc.ID = s.CATEGORY GROUP BY s.NAME order by NAME asc limit 0 , 10;

**Comment by charleneauger** [comment]
Bonjour @Parnoud ,

L'inventaire de logiciel a été récemment entièrement repensé. Installer la dernière nightly corrige la lenteur de l'affichage des logiciels.

Cordialement,
Charlène Auger
