### ISSUE TITLE
[BUG] if software category have the same name of software it not showed at combobox

### ISSUE THREAD

**Issue by fgendorf** [OCSInventory-NG/OCSInventory-ocsreports#817]
**OCS Inventory version**
Version : 2.6

**Describe the bug**
create a category of software with the same name of a software, go to categories list and it will not appear in it

**Expected behavior**
if I create a category of software called Winzip and add software Winzip in it, the expected is the category appear on categories list.

**Additional context**
one SQL in plugins/main_sections/ms_dict/ms_dict.php get categories with criteria FORMATTED!=EXTRACTED

**Comment by charleneauger** [comment]
Hi @fgendorf ,

The dictionary feature will be removed from the OCS Inventory 2.7 version.
Software Category feature replace the dictionary.
Please, see the documentation for more informations : [Using software categorization](http://wiki.ocsinventory-ng.org/04.Management-console-and-its-advanced-features/Using-Software-Categorization/)

Best regards,
Charlene Auger

**Comment by fgendorf** [comment]
But, what about GLPI that use this dictionary? category is not more related with type?

**Comment by charleneauger** [comment]
@fgendorf, we don't do GLPI support. The categories are not related with GLPI and it's advisable to use the GLPI dictionary rather than the OCS dictionary.

Best regads,
Charlene Auger
