### ISSUE TITLE
[BUG]Unable to use alternate port for mysql DB

### ISSUE THREAD

**Issue by jcpunk** [OCSInventory-NG/OCSInventory-ocsreports#818]
**OCS Inventory version**
Version : 2.6.0

**Describe the bug**
My mysqld server is running on a non-standard port.  There is no place within OCSInventory Reports to set the port to an alternate value

**To Reproduce**
1. setup mysql server on non-standard port
2. try to connect to database on alternate port (for example /ocsreports/install.php)

**Expected behavior**
There should be a box to set the mysql port (have it default to the standard port).

**Screenshots**
None

**Additional context**
Doc should note use of non-standard port may require additional SELinux config.

**Log file (optional)**
Apache / PHP / System log if needed

**Comment by charleneauger** [comment]
Hi @jcpunk ,

I can close your issue because your PR has been merged !
Thankx for your contribution :-)

Regards,
Charlene Auger
