### ISSUE TITLE
[BUG] ocs server 2.6 hosts in the database not found in gui

### ISSUE THREAD

**Issue by mihai-satmarean** [OCSInventory-NG/OCSInventory-ocsreports#819]
**OCS Inventory version**
Version : 2.6

**Describe the bug**
We used ocs 2.4 and a few months ago we upgraded to 2.6
Our inventory: cca 25k hosts. We see random hosts are present in the database but cannot be found using the gui. Additionally the gui search is 50x slower than version 2.4

**To Reproduce**
we have a php function that reads the database, and this returns the hosts and details, when we search the same host using the GUI (/ocsreports/index.php?function=visu_search), a blank page is the result.

**Expected behavior**
/ocsreports/index.php?function=visu_search should return computer objects

**Screenshots**
![ocs_not_returns](https://user-images.githubusercontent.com/4729542/65758495-7c753980-e119-11e9-81a2-8f398afb7b03.png)

**Additional context**

**Log file (optional)**
not available, but we can provide it on request

**Comment by gillesdubois** [comment]
Hi @mihai-satmarean ,

Your bug has been resolved in this version : http://download.ocsinventory-ng.org/nightly/OCSNG_UNIX_SERVER_2.6-nightly-2019-10-04.tar.gz

Could you try with this one ?

Regards,
Gilles Dubois.

**Comment by mihai-satmarean** [comment]
thanks!
we will try it asap

În vin., 4 oct. 2019 la 15:08, Gilles Dubois <notifications@github.com> a
scris:

**Comment by mihai-satmarean** [comment]
Hello, we have used http://download.ocsinventory-ng.org/nightly/OCSNG_UNIX_SERVER_2.6-nightly-2019-10-17.tar.gz and the visual search page is still empty.

**Comment by charleneauger** [comment]
Hi @mihai-satmarean ,

Can you give us your apache error log file please ?

Best regards,
Charlene Auger

**Comment by mihai-satmarean** [comment]
Hi, sorry for the delay, 

by using the nighly recommended, 
on accessing 
http://REDACTEDHOST.com/ocsreports/index.php?function=visu_search

we get the error

```
> 
> [Wed Dec 04 09:33:34.094760 2019] [:error] [pid 10438] [client 10.81.213.12:57203] PHP Fatal error:  Can't use method return value in write context in /usr/share/ocsinventory-reports/ocsreports/require/search/TranslationSearch.php on line 238
> 
> ==> /var/log/httpd/access_log <==
> 10.81.213.12 - user [04/Dec/2019:09:33:34 +0100] "GET /ocsreports/index.php?function=visu_search HTTP/1.1" 200 8758 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36"
> 10.81.213.12 - - [04/Dec/2019:09:33:34 +0100] "GET /ocsreports/favicon.ico HTTP/1.1" 200 370070 "http://REDACTEDHOST.com/ocsreports/index.php?function=visu_search" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36"
```

**Comment by gillesdubois** [comment]
Hi @mihai-satmarean ,

PHP 7.X is required for newer versions of OCS Inventory.
Also this behavior has been improved in the latest nightly.

Regards,
Gilles Dubois.
