### ISSUE TITLE
Please do not append /logs to the log directory

### ISSUE THREAD

**Issue by nirgal** [OCSInventory-NG/OCSInventory-ocsreports#82]
I set VARLOG_DIR `/var/log/ocsinventory-reports` in var.php
but logs are written in `/var/log/ocsinventory-reports/logs/`

Please do not append /logs

**Comment by gillesdubois** [comment]
Hi,

I close this issue : https://github.com/OCSInventory-NG/OCSInventory-ocsreports/issues/80
( See kapouik's comment )

Regards,
Gilles Dubois.
