### ISSUE TITLE
[HELP] Problem is Connect OCS Inventory server in Active Directory (port 636 (ldaps))

### ISSUE THREAD

**Issue by LucasBarrosDosSantos** [OCSInventory-NG/OCSInventory-ocsreports#823]
Hi, I need help to connect Active Directory with OCS Inventory, the configuration was a success when defining port 389 (without SSL), however, when defining a configuration for port 636 (With SSL) the application cannot authenticate in Active Directory.  I believe that the OCS Inventory server does not recognize my SSL implemented in Active Directory.

**Comment by gillesdubois** [comment]
Hi,

Latest LDAP rework should fix you problem, please see the documentation.

Regards,
Gilles Dubois.

**Comment by LucasBarrosDosSantos** [comment]
Nice, thank you.
