### ISSUE TITLE
[BUG] WOL doesn't work

### ISSUE THREAD

**Issue by StCyr** [OCSInventory-NG/OCSInventory-ocsreports#824]
**OCS Inventory version**
Version : 2.6

**Describe the bug**
WOL doesn't work

**Expected behavior**
WOL should work

**Additional context**
When we hit the WOL link, we can see ARP WHO-HAS requests. But, eventualy, nobody answers as the agent is down for long.

For this reason, I think the WOL packet isn't send.

**Possible cause**
The problem seems coming from the following line in file `require/function_wol.php`:

`socket_sendto($s, $this->pacquet($mac), strlen($this->pacquet($mac)), 0, $ip, $v);`

This tries to send the packet to a specific IP address. Therefore the ARP WHO-HAS request.

**Proposed solution**
Rather than trying to send the WOL packet to the agent's IP address we should send a broadcast packet to the subnet of this IP address.

So, I propose to do the following (pseudo-code):

```php
for all agent_IP_addresses:
    if server.hasIPaddressInSubnet(agent_IP_address) then
        sendBroadcastPacketToSubnet()
    else 
        // skip this agent ip address because we don't have any direct connection to it
        next 
```

**Comment by charleneauger** [comment]
Hi @StCyr ,

In 2.7 version WOL feature has been reworked.

Best regards,
Charlene
