### ISSUE TITLE
[HELP] : Installation error ubuntu 18.04

### ISSUE THREAD

**Issue by chazkame** [OCSInventory-NG/OCSInventory-ocsreports#829]
Hi,

I'm having trouble installing OCS Inventory server on my ubuntu 18.04, here below is the error message in the log:

> Installing Communication server Perl modules (make install)
Appending installation info to /usr/local/lib/x86_64-linux-gnu/perl/5.26.1/perllocal.pod
Creating Communication server log directory /var/log/ocsinventory-server
Fixing Communication server log directory permissions
chown: changing ownership of '/var/log/ocsinventory-server': Operation not permitted

Help please. 
Many thanks to everyone.

Regards

**Comment by gillesdubois** [comment]
Hi,

You need to use a privileged user to launch the setup.

Regards,
Gilles Dubois.
