### ISSUE TITLE
[BUG] "Linux (ALL)" filter does not work

### ISSUE THREAD

**Issue by schplurtz** [OCSInventory-NG/OCSInventory-ocsreports#841]
**OCS Inventory version**
Version :  server 2.4.1

**Describe the bug**
In the web console, Try to get all linux clients with "inventory" "search with various criteria" fails. Only a subset of linux clients are reported.

**To Reproduce**
1. http...../ocsreports/
2. Click on inventory, then "search with various criteria"
![image](https://user-images.githubusercontent.com/1008292/67830743-20b51c00-fadc-11e9-95b6-253410f0fef7.png)
3. Set "Choose a parameter" to "Computers: Operating System" 
![image](https://user-images.githubusercontent.com/1008292/67830806-61ad3080-fadc-11e9-939b-8518ca70ed1c.png)
4. Wait for the screen to refresh
5. Set "Computers: Operating System" to "Linux (ALL)" 
<img width="645" alt="image" src="https://user-images.githubusercontent.com/1008292/67830905-ccf70280-fadc-11e9-96f2-121099a18bc8.png">

**Expected behavior**
I expect to get the list of all registered Linux clients.

**What happens instead**
I get only a subset of Linux clients.

**Additional context**
It is hard not to notice that listed clients all have the word «Linux» in their «Machine(s): Operating system» field as shown on the screenshot below. Similarly, cients that happen to not have the word «Linux» in this field are not listed by the «Linux (ALL)» filter.

In my case, listed clients are all running outdated version of the client on outdated Debian boxes, as can be seen. 
![image](https://user-images.githubusercontent.com/1008292/67831186-a6859700-fadd-11e9-85d1-a3c3215b1391.png). Oudated clients on outdated ubuntu boxes do not have the word Linux in the Os field. (no screenshot, sorry, tired...)

Now, clients running more recent version of the client do not show «Linux» in their «Machine(s): Operating system» field, but only «Debian» or «Ubuntu». This [was discussed](https://ask.ocsinventory-ng.org/9899/ocsagent-2-4-2-shows-no-os-version-in-ubuntu-18-04?show=9899#q9899) on the forum. BTW, I appreciate that the OS version is now really the OS version and not the kernel version, but these clients do not appear in «Linux (ALL)» filter.
![image](https://user-images.githubusercontent.com/1008292/67832019-97541880-fae0-11e9-94d0-341ea8510be4.png)

**Summary**
Filter "Linux (ALL)" does not show all linux clients.

Apparently, «Linux (ALL)» filter select clients having the word «Linux» in «Machine(s): Operating system». This does not select all Linux clients.

Moreover, modern agent do not include the word «Linux» in this field, as discussed [here](https://ask.ocsinventory-ng.org/9899/ocsagent-2-4-2-shows-no-os-version-in-ubuntu-18-04?show=9899#q9899) on the forum.

**Comment by charleneauger** [comment]
Hi @schplurtz ,

Since version 2.5, the search with various criteria has been reworked. 
Please download the nightly at here [](http://download.ocsinventory-ng.org/nightly/) and update your server to fix this bug.

Regards,
Charlene Auger

**Comment by schplurtz** [comment]
Hi @charleneauger,
Thanks for the reply. Unfortunately, this is not my server. Just a server I have to use. Admin will probably laugh if I suggest he use a nightly build.
I'll suggest he update/upgrades his OS package instead.
I'm closing this bug request now as there are now 2 newer ocsreports versions, 2.5 and 2.6, and you suggest I should try at least 2.5.

Thanks again
