### ISSUE TITLE
[HELP]  Upgrade from version 2.2.1 to 2.6

### ISSUE THREAD

**Issue by zJeanMiliodas** [OCSInventory-NG/OCSInventory-ocsreports#844]
Hello, I am using version 2.2.1 and would like to upgrade to 2.6. What is the correct method of updating. Update as previous versions before, such  2.3.2.3.1,2.4, 2.4.1,2.5 and finally 2.6? Or simply install version 2.6 directly?

**Comment by charleneauger** [comment]
Hi @zJeanMiliodas ,

We advise you to update step by step (just major versions) because between version 2.2.1 and 2.6, there is a lot of features, enhancements and fix bug.

Best regards,
Charlene Auger

**Comment by fourstepper** [comment]
@charleneauger Sorry to interrupt this thread, may I ask if the best way to update between 2.5 and 2.7 would be to go between major versions as well?

What would be the best way to update on CentOS? Are there any "beware" notes somewhere?

**Comment by charleneauger** [comment]
Hi @fourstepper ,

Our recommendations remain the same as with any other Operating Systems. There aren't any specificities with CentOS.

Please, check the following link : [http://wiki.ocsinventory-ng.org/03.Basic-documentation/Updating-the-server/](http://wiki.ocsinventory-ng.org/03.Basic-documentation/Updating-the-server/)

Note : for the 2.7 version we recommend using the setup and not cp the dbconfig.inc.php file

Best regards,
Charlene Auger

**Comment by fourstepper** [comment]
So I would just ommit copying the dbconfig.inc.php completely and let the setup.sh do all the job, copying only cp z-ocsinventory-server.conf
zz-ocsinventory-restapi.conf ocsinventory-reports.conf, right?

Thanks for the help.
