### ISSUE TITLE
[BUG] Search by column not working

### ISSUE THREAD

**Issue by charleneauger** [OCSInventory-NG/OCSInventory-ocsreports#848]
**OCS Inventory version**
Version : 2.6

**Describe the bug**
Search by column not working

**To Reproduce**
1. Go to all computer
2. Select search by column
3. The search bar search on all column and not on the column selected

**Expected behavior**

**Screenshots**

**Additional context**

**Log file (optional)**
Apache / PHP / System log if needed

**Comment by gillesdubois** [comment]
This feature has been disabled and thus this issue is no longer reveleant.
