### ISSUE TITLE
I can't hide ms_vmware_vcenter page

### ISSUE THREAD

**Issue by pchamo** [OCSInventory-NG/OCSInventory-ocsreports#866]
I installed the vmware vcenter plugin and finally it's working. I disabled the ms_vmware_vcenter page for admins but it's not working, it's still accesible (http://prntscr.com/q2z433). What else is need to disable that access? Could you please help me? I have ocsinventory server 2.6 on centos 7.

**Comment by pchamo** [comment]
Even more, if I login using a teledeploy requester account the vmware vcenter page is the only one shown, besides the help menu! How can it be possible?

http://prntscr.com/q30clx

**Comment by pchamo** [comment]
I think it's a bug.

**Comment by charleneauger** [comment]
Hi @pchamo ,

OCS Inventory doesn't have a configuration for plugin pages and no profile management. This mean that you won't be able to add permission for a specific user.

Regards,
Charlene Auger
