### ISSUE TITLE
CVE ne fonctionne pas

### ISSUE THREAD

**Issue by steph78630** [OCSInventory-NG/OCSInventory-ocsreports#867]
**OCS Inventory version**
Version : 2.6

**Describe the bug**
La remontée des CVE dans la BdD du serveur ne se fait pas

**To Reproduce**
Pour toutes les vulnérabilités testées :

PHP Warning:  Invalid argument supplied for foreach() in /usr/share/ocsinventory-reports/ocsreports/require/cve/Cve.php on line 165

**Comment by jmesa** [comment]
**OCS Inventory version**
Version : 2.6

**Describe the bug**
Manually launching **cron_cve.php** gives that error.

**To Reproduce**
```
root@:/usr/share/ocsinventory-reports/ocsreports/crontab# php cron_cve.php
PHP Warning:  Invalid argument supplied for foreach() in /usr/share/ocsinventory-reports/ocsreports/require/cve/Cve.php on line 165
```
