### ISSUE TITLE
[BUG] creation de package: fichier info pas encoder en utf8

### ISSUE THREAD

**Issue by thenamelessthing** [OCSInventory-NG/OCSInventory-ocsreports#869]
Bonjour, depuis que nous avons réinstaller notre serveur avec une version plus récente. Lorsque nous créons un package pour télédéploiement, nous avons un message d'erreur indiquant qu'il ne trouve pas le fichier info en lien avec le package. Si je me rend dans le répertoire je vois bien celui-ci mais en l'analysant, on voit qu'il n'est pas encoder correctement en UTF8. Je dois alors en command line le convertir (iconv -f ISO-8859-1 -t UTF-8//TRANSLIT info -o info.1) et corriger le texte qui à été tronqué.  Comment pouvons-nous résoudre cette situation? Merci

Notre serveur:

Nom du système : Linux x86_64
Version :3.10.0-957.10.1.el7.x86_64
RAM totale :3789 Mo
RAM disponible :1803 Mo
CPU :Intel(R) Xeon(R) CPU E5-2670 v3 @ 2.30GHz
Distribution : CentOS Linux 7 (Core)
Logiciel
Version de PHP : 7.3.4
Serveur Web : Apache
Serveur SQL : MariaDB Server version 10.2.23-MariaDB
Version OCSReports: 2.5

**Comment by thenamelessthing** [comment]
up?

**Comment by charleneauger** [comment]
Bonjour @thenamelessthing ,

Le bug d'encodage en UTF-8 du fichier info est corrigé dans la version 2.6.
Nous vous conseillons donc de passer à cette version :-)

Cordialement,
Charlène Auger
