### ISSUE TITLE
Please stop screaming if /var/www/html/logs is not writable

### ISSUE THREAD

**Issue by nirgal** [OCSInventory-NG/OCSInventory-ocsreports#87]
... in install.php when I have VARLOG_DIR set to /var/log/ocsinventory-reports

Defines from var.php should be used.

**Comment by gillesdubois** [comment]
Hi,

Look here to see the fix : https://github.com/OCSInventory-NG/OCSInventory-ocsreports/pull/89

Regards, 
Gilles Dubois

**Comment by nirgal** [comment]
Gilles Dubois wrote:
> Look here to see the fix : https://github.com/OCSInventory-NG/OCSInventory-ocsreports/pull/89

It is a bit better, but still wrong: Please have a look #88

Please enforce Filesystem Hierarchy Standard.

Basically, if you can write to /var/www/html then you attempt to create
directory /var/log/ocsinventory-reports. The two are not related!

Better try a recursive mkdir and catch exceptions...

Please do not use $_SERVER['DOCUMENT_ROOT'] but for code location (read
only).
