### ISSUE TITLE
[BUG] aucun résultat affiché pour les statistiques de télédéploiement

### ISSUE THREAD

**Issue by thenamelessthing** [OCSInventory-NG/OCSInventory-ocsreports#870]
Lorsque je tente de consulter les résultats de télé-déploiement, je vois bien que j'ai par exemple 22 succès, 2 erreurs, etc. Si je clique sur ceux en erreurs, je devrais voir la liste des postes en erreur. cependant ce n'est pas ça qui s'affiche mais plutôt aucun résultat!

![image](https://user-images.githubusercontent.com/10235448/70080343-5b770c00-15d4-11ea-9dbc-5ca0670cfcf6.png)

Même chose pour les autres états de déploiement.

Notre serveur:

Nom du système : Linux x86_64
Version :3.10.0-957.10.1.el7.x86_64
RAM totale :3789 Mo
RAM disponible :1803 Mo
CPU :Intel(R) Xeon(R) CPU E5-2670 v3 @ 2.30GHz
Distribution : CentOS Linux 7 (Core)
Logiciel
Version de PHP : 7.3.4
Serveur Web : Apache
Serveur SQL : MariaDB Server version 10.2.23-MariaDB
Version OCSReports: 2.5

**Comment by thenamelessthing** [comment]
up?

**Comment by charleneauger** [comment]
Bonjour @thenamelessthing ,

Ce bug est corrigé dans la version 2.6. 
Nous vous conseillons de mettre à jour votre serveur vers cette dernière :-)

Cordialement,
Charlène Auger
