### ISSUE TITLE
[BUG] Groupe dynamique => opérateur "ne contient pas"

### ISSUE THREAD

**Issue by orcustPA** [OCSInventory-NG/OCSInventory-ocsreports#871]
**OCS Inventory version**
Version : 2.6
Bonjour à tous,

Si je fais une requête multicritères en prenant « tous les logiciels » et « nom » et que je choisis l’opérateur « ne contient pas » avec le nom de mon logiciel. Le résultat de la requête est correct.

Avec ce résultat, je crée un groupe dynamique, jusque-là tout va bien mais si je retourne interroger le groupe dynamique et que je clique sur le bouton « toutes les machines (rejouer) », alors, j’obtiens l’erreur :

You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'DOESNTCONTAIN 'ESET'' at line 1.

Le résultat en cache ne s’affiche plus. Mon groupe dynamique est maintenant vide.

Mes autres groupes fonctionnent correctement. L’erreur se produit seulement avec l’opérateur « ne contient pas ». Cet opérateur ne semble pas présent dans la version 2.5.

S’agit-il d’un bug lié à ma configuration ou d’OCS.

Ci-dessous, vous trouverez els informations du serveur :

Version de PHP : 7.2.24
Serveur Web : Apache/2.4.29 (Ubuntu)     
Serveur SQL :  Ubuntu 18.04 version 10.1.43-MariaDB-0ubuntu0.18.04.1
Version OCSReports: 2.6

Je vous remercie pour votre aide et bon week-end à tous.

**Comment by charleneauger** [comment]
Bonjour @orcustPA ,

Merci pour votre retour, Il s'agit bien d'un bug OCS. Il est actuellement en cours de correction :)

Cordialement,
Charlène Auger
