### ISSUE TITLE
Cant see any software under inventory>All Software

### ISSUE THREAD

**Issue by thoracicoldend** [OCSInventory-NG/OCSInventory-ocsreports#872]
Hello
Im working on deploying OCSinventory, but im having issues with one of the requirements, which is the ability to see all inventoried software under inventory>all software.
I have created a category named Software, which makes me able to see "all software" from the date of creation of that category... 
That category also shows under inventory>all software but not with the same software as manage>software category>Software??

**Comment by gillesdubois** [comment]
Hi @thoracicoldend ,

2.7 and latest nightlies correct this bug.

Regards,
Gilles Dubois.
