### ISSUE TITLE
[BUG] Underline character gets ripped-of of login form

### ISSUE THREAD

**Issue by nwildner** [OCSInventory-NG/OCSInventory-ocsreports#878]
**OCS Inventory version**
Version : 2.6

**Describe the bug**
Underline gets removed from User field after trying to login

**To Reproduce**
1. Try to login with an user that have underline
2. Get the "User not registered" message
3. See that the underline gets removed

**Expected behavior**
Login

### Browsers Tested
Firefox:  72.0
Chrome: 79.0.39

### Problem's description
Whenever i try to login on OCS with a login that has underline, that character gets ripped after clicking "Send". Problem is, we have IT admin users on AD and every login has its "admin_" counterpart ("nicolas" - regular login ; "admin_nicolas" - IT operator).

Also, since we are dealing with LDAP groups, it would be interested to keep access to OCS only to those logins, that are part of the "IT Operators" ldap group.

Step 1 - Credentials and click Send:

![image](https://user-images.githubusercontent.com/11742211/71977957-ea40ff00-31f8-11ea-8d73-d0d216e13470.png)

Step 2 - Form answers with "User not registered" and it refreshes removing the underline:

![image](https://user-images.githubusercontent.com/11742211/71977993-047add00-31f9-11ea-97fd-13f67b07ebf9.png)

Is this an expected behavior?

**Comment by nwildner** [comment]
Just a quick update on this issue: After upgrading OCS to 2.8, issue still reproduces.

If i try to login with `admin_nicolas`, the underscore character gets removed from my login.

![image](https://user-images.githubusercontent.com/11742211/99067914-4a779e80-258a-11eb-8a14-ea30e4645013.png)

**Comment by charleneauger** [comment]
Hi @nwildner ,

This bug has been fixed on 2.9 version.

Best regards,
Charlene

**Comment by nwildner** [comment]
> Hi @nwildner ,
> 
> This bug has been fixed on 2.9 version.
> 
> Best regards,
> Charlene

Thanks for the feedback @charleneauger .

I would gladly test those changes but, I've changed positions starting this year so, I don't have that AD + OCS environment ready for testing :(

All the Best,
nwildner
