### ISSUE TITLE
[BUG]Default SQL login error message 

### ISSUE THREAD

**Issue by interceptor49** [OCSInventory-NG/OCSInventory-ocsreports#879]
**OCS Inventory version**
Version : 2.6 nightly 2020/01/08
running on Debian stretch
Database mariadb with ssl support

**Describe the bug**
Since the release of the ssl support for mysql on ocsreports (thanks for that) the error message about default SQL password always appears. Wrong login has been set for check. 
See screenshot.

**To Reproduce**
Install the nightly and use a deployment with a mysql/mariadb having ssl.
Might also appear in a regular usage.

**Expected behavior**
If users can reach the interface and haven't set up the default login/password for SQL, the message shouldn't appear

**Screenshots**
![ocserror](https://user-images.githubusercontent.com/2764839/71980566-a3ff9600-3220-11ea-8777-6c8c648daca7.png)

**Additional context**
Please see the PR for resolution.

**Comment by charleneauger** [comment]
Hi @interceptor49 ,

Thanks for your report ! Your PR has been merged :)

Best regards,
Charlene Auger
