### ISSUE TITLE
Please reorganise var.php

### ISSUE THREAD

**Issue by nirgal** [OCSInventory-NG/OCSInventory-ocsreports#88]
`ETC_DIR`, `VARLIB_DIR` and `VARLOG_DIR` should be near the top of the file.

Most of the other values should be based on these:
configuration -> `ETC_DIR`
data (r/w area) ->`VARLIB_DIR`
log -> `VARLOG_DIR`

For example, default value of "/download/" should be based on `VARLIB_DIR` and not `__DIR__`.

The repositories relative to `__DIR__` (the code) can be expected to be *read only*.

Do *not* use `DOCUMENT_ROOT`. This is irrelevant. Aliases do take care of exposing the relevant part of `VARLIB_DIR` (see etc/ocsinventory/ocsinventory-reports.conf )

Keeping the same default values as previous version would make sense ( /var/lib/ocsinventory-reports  for example).
Now many of this values also are in the database ( table `config` key `DOWNLOAD_PACK_DIR` contains `/var/lib/ocsinventory-reports` for example ). This make the code very difficult to review...

**Comment by gillesdubois** [comment]
Hi,

This var.php has been improved and is easier to read.
Some var has been adjusted in order to be compliant with default installation
However, there might be some more modification to make on it

Regards,
Gilles Dubois.
