### ISSUE TITLE
[BUG] Menu header disappear

### ISSUE THREAD

**Issue by Rayzilt** [OCSInventory-NG/OCSInventory-ocsreports#891]
**OCS Inventory version**
Version : master (28-01-2020)

**Describe the bug**
After deleting a linked package in an (Dynamic|Static) group the top menu header disappears.

**To Reproduce**
1. Create, Activate and Link a package to a group;
2. Go tot the group and press 'Delete' at the package row;
3. Top menu header will dissapear.

**Expected behavior**
Top menu header should stay

**Screenshots**
![image](https://user-images.githubusercontent.com/3105311/73361513-60d79680-42a5-11ea-8ece-1f9f8879332d.png)

**Log file (optional)**
![image](https://user-images.githubusercontent.com/3105311/73361591-84024600-42a5-11ea-8319-a8144bdba3a5.png)

**Comment by charleneauger** [comment]
Hi @Rayzilt ,
Thank you for your issue however an issue is already opened for this bug #884 . :-)

Best regards,
Charlene Auger

**Comment by Rayzilt** [comment]
Ah great, I don't speak that language, I had searched the Issues.

**Comment by charleneauger** [comment]
@Rayzilt , the bug has been fixed, see #893 :-)
Best regards,
Charlene
