### ISSUE TITLE
[FEATURE] Change bios.BDATE to a 'datetime' type

### ISSUE THREAD

**Issue by Rayzilt** [OCSInventory-NG/OCSInventory-ocsreports#894]
It would be nice to use 'Less than/More than' on the 'Bios Date' column when using 'Search with various criteria'. I'm creating a dynamic group to update existing and future machines to a specific bios version. I'm unable to match on 'Bios Version' because that field contains more info like the word "Ver".

The current solution for me is, match on specific 'Bios Model' and that the 'Bios Version' doesn't contain a specific string. This also means that newer bios versions will get downgraded.

In the database the bios.BDATE is a 'varchar(255)' type and would be nice to have that changed to 'datetime' type. I understand that it's more than changing the type in the database.

Or if somebody can explain to me how to 'Less than' a sting? Like check if string "P06 Ver. 021" is less than "P06 Ver. 02.31".

Current filter:
![image](https://user-images.githubusercontent.com/3105311/73491624-54d7fb80-43af-11ea-9dfc-6a152bc8e795.png)

Would be nice to have filter:
![image](https://user-images.githubusercontent.com/3105311/73491693-76d17e00-43af-11ea-89e3-0d5fff2da59a.png)

Thanks

**Comment by charleneauger** [comment]
Hi @Rayzilt ,

Unfortunately, we can't realize this feature. Changing Bios date to datetime is too complex due to the different date format returned by the different BIOS.

Best regards,
Charlene Auger
