### ISSUE TITLE
autodeploy - based on ??

### ISSUE THREAD

**Issue by sokatra** [OCSInventory-NG/OCSInventory-ocsreports#896]
Hy, i don't know how i can solve the follwing with ocs-inventory.
I wan't to autodeploy a package to all computers which has a error number larger then xxxx.
you might ask why anybody want to this.
Answer is easy. I deploy a package which counts the uptime in days. This packages returns the uptime count plus 4000. So for example the errorlevel 4007 means that the computer has a uptime of 7 days.
For every person who has a uptime(errrorlevel >4005) greater then 5 days i want to send a package which alerts the user to restart.
I affect the package manually - it works - but how to automate this with ocs?
an universal mechanism which can do this would be great - i know that the errorlevel isn't the right way to solve this - but is there another way without doing the logic on client with a task ?
perhaps i was possible that future agents can write more return values.
Otherwise i have to write saome values to the registry - read out the registry via ocs - and do something(deploy) based on that registry value. I think the registry trick ist the best way to accomplish what i want?

I also want to solve something like this 
Deploy a package if client hasn't been seen for more then x days.
What do you think ?
Kind regards

**Comment by gillesdubois** [comment]
Hi @sokatra,

To deploy based on dynamic criteria we recommend to use the dynamic group system.
You will be able to create dynamic group and deploy package on this group. All computer entering in the group will have the package affected.

Regards,
Gilles Dubois.

**Comment by sokatra** [comment]
dynamic groups does't work here . because if i create a dynamic group the clients and add a apckage they are only affected once. the don't get the package again and again which i need for triggering the update message.
https://github.com/OCSInventory-NG/OCSInventory-ocsreports/issues/947
kind regards
