### ISSUE TITLE
Blacklist ne fonctionne pas [BUG]

### ISSUE THREAD

**Issue by jlb5980** [OCSInventory-NG/OCSInventory-ocsreports#897]
**OCS Inventory version**
serveur Version : 2.3.1 et agent v 2.3.1

La blacklist ne fct pas , nous avons essayé avec le numéro de série , l'adresse mac mais les machines continuent  de remontées dans ocsng .  
Ce qui est particulièrement gênant.
Merci   pour vos réponses

 Apache/2.4.6
 PHP/5.4.16
 mod_perl/2.0.10
 Perl/v5.16.3
  MySQL Community Server (GPL) version 5.5.52
 ocsNGv  2.3.1

**Comment by masutomo** [comment]
Hi, I have some virtual network interfaces with mac addr 00:00:00:00:00:00, it is still show up in inventory, so the blacklist is not working too? I am running OCS v2.6 server. Thanks.

**Comment by alacn1** [comment]
I think blacklist is for automatic merging duplicates.
Not for removing it from inventory.

**Comment by Lea9250** [comment]
Hi @jlb5980,
Blacklist feature doesn't serve this kind of purpose, it is intended to help manage duplicates.

Regards,
Léa
