### ISSUE TITLE
SOAP::Transport::HTTP2 required when using mod_perl > 1.999_21

### ISSUE THREAD

**Issue by StCyr** [OCSInventory-NG/OCSInventory-ocsreports#9]
When OCS_MODPERL_VERSION=2, the webservice / plugin engine needs SOAP::Transport::HTTP2 (see package Apache::Ocsinventory::SOAP).

This is nowhere explained.

**Comment by gillesdubois** [comment]
SOAP::Transport::HTTP2 is a part of SOAP package...

This is explained in the INSTALL_2.2.txt file but this is not indicated in the setup.sh
I will fix the setup soon in order to improve the user's installation experience.

Thanks you contributing to ocs inventory NG
Regards, Gilles Dubois

**Comment by StCyr** [comment]
I'm sorry bu on Ubuntu, package SOAP::Lite doesn't ship SOAP::Transport::HTTP2:

`root@houdini:/home/support/OCSNG_UNIX_SERVER-master# dpkg -l libsoap-lite-perl
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                                       Version                    Architecture               Description
+++-==========================================-==========================-==========================-==========================================================================================
ii  libsoap-lite-perl                          1.09-1                     all                        Perl implementation of a SOAP client and server

root@houdini:/home/support/OCSNG_UNIX_SERVER-master# cat /etc/issue
Ubuntu 14.04.2 LTS \n \l

root@houdini:/home/support/OCSNG_UNIX_SERVER-master# perl -mSOAP::Transport::HTTP
^C

root@houdini:/home/support/OCSNG_UNIX_SERVER-master# perl -mSOAP::Transport::HTTP2
Can't locate SOAP/Transport/HTTP2.pm in @INC (you may need to install the SOAP::Transport::HTTP2 module) (@INC contains: /etc/perl /usr/local/lib/perl/5.18.2 /usr/local/share/perl/5.18.2 /usr/lib/perl5 /usr/share/perl5 /usr/lib/perl/5.18 /usr/share/perl/5.18 /usr/local/lib/site_perl .).
BEGIN failed--compilation aborted.
root@houdini:/home/support/OCSNG_UNIX_SERVER-master#`

Br,

Cyrille

**Comment by gillesdubois** [comment]
Hello,

i think there is a mis-understanding

The plugin engine need this "http://search.cpan.org/~phred/SOAP-Lite-1.17/lib/SOAP/Transport.pod" .. as you can see is ship with SOAP::Lite ...

SOAP::Transport::HTTP2 is needed for the optional webservice service for OCS Inventory and is not used by default in OCS Inventory.

Even if SOAP::Transport::HTTP2 isn't installed your ocs inventory should work well.

Regards,
Gilles Dubois
