### ISSUE TITLE
CA Certificates

### ISSUE THREAD

**Issue by Silente** [OCSInventory-NG/OCSInventory-ocsreports#90]
good morning,
I noticed something using ocsinventory with the certificate. If the SSL field = 0 in the configuration file, then everything works fine. Instead if the SSL field = 1 I get the error below.

`Failed to send Prolog <Peer certificate cannot be authenticated with given CA certificates>`

So what if this parameter is 0? The client does not communicate with the server using the ssl?

**Comment by MyTheValentinus** [comment]
Hello @silente, on OCS agent setting ssl=0 is equal to disable. When you put this value to 1, you need valid certificate file, ssl is on.

Regards, Valentin.

**Comment by Silente** [comment]
Perfect, how can I solve the problem that I get from activating the SSL?

**Comment by MyTheValentinus** [comment]
If you use windows agent:
Stop service Ocs inventory,
Edit config file and turn ssl to 0,
Restart service.

If you use unix agent: 
Edit config in /etc/ocsinventory-ng
And launch inventory

Regards, Valentin

**Comment by Silente** [comment]
I explained myself badly, for ssl activation in the configuration file is ok.
But if it is activated, I get the error 

`Failed to send Prolog <Peer certificate can not be authenticated with certificates given CA>`

How do I solve this problem?

**Comment by MyTheValentinus** [comment]
Ok, do you have indicate path of certificate on configuration file ?

Can you verify the path is correct ?

Your server have ssl with IP or domain as common name during certificate generation ?

**Comment by Silente** [comment]
Path is correct
It was generated directly using the dns

**Comment by MyTheValentinus** [comment]
Hello,
Please, regenerate SSL certificat on server with IP or domain as common name of your server, export .ca  to agent and test again.
Problem is not with OCS but your configuration.
Regards, Valentin.
