### ISSUE TITLE
[BUG] Use of undefined constant key - assumed 'key' (this will throw an Error in a future version of PHP)

### ISSUE THREAD

**Issue by mika1K** [OCSInventory-NG/OCSInventory-ocsreports#902]
**OCS Inventory version**
Version : 2.6

**Describe the bug**
Use of undefined constant key - assumed 'key' (this will throw an Error in a future version of PHP)

**To Reproduce**
1. Go to Web Interface.
2. Activate in |Configuration >General Options >|Registry >Turn "ON" Registry key gathering functionality.
3. Check apache logs. 

**Log file (optional)**
Apache / PHP / System log :
[Mon Feb 17 15:10:29.202397 2020] [php7:warn] [pid 26031] [client 185.230.76.161:22719] PHP Warning:  Use of undefined constant key - assumed 'key' (this will throw an Error in a future version of PHP) in /usr/share/ocsinventory-reports/ocsreports/require/function_config_generale.php on line 137, referer: https://ocs.xxx.com/ocsreports/index.php?function=admin_conf

**Comment by charleneauger** [comment]
Hi @mika1K ,

This bug has been already fixed with PR #832 :-)

Best regards,
Charlene Auger
