### ISSUE TITLE
[BUG] UPGRADE option in Windows Client never send SUCCESS to Deployment server.

### ISSUE THREAD

**Issue by jorensanbar** [OCSInventory-NG/OCSInventory-ocsreports#904]
Version: Server 2.6, Clients: 2.4 / 2.6

If a client update is sent through Deployment, it never notifies the server that it has finished launching the installer.

1. Install client 2.4 in Windows.
2. Create a deployment package of 2.6 Agent with parameters: /s /nosplash /upgrade /ssl=1 /now /server=https://ocsng.xxxxxxx.com/ocsinventory /tag="TEST"
3. Sent package to a PC.
4. The Agent, never send the SUCCESS command to Deployment Server.
5. Wait for infinite bucle.
6. New client, run over and over the setup and Inventory.

**Expected behavior**
When the package is finished installing, read the last line of the Log, and return a SUCCESS to the server, and exit the infinite loop of installations.

**Log file (optional)**
==============================================================================
Starting OCS Inventory NG Package Download and Setup Tool on Wednesday, February 19, 2020 11:12:35.
DOWNLOAD => Running OCS Inventory NG Download Version 2.4.0.0
DOWNLOAD => Using OCS Inventory NG FrameWork Version 2.4.0.0
DOWNLOAD => Using network connection with Communication Server
DOWNLOAD => Using Communication Provider <OCS Inventory NG cURL Communication Provider> Version <2.4.0.0>
DOWNLOAD => Starting new period of 10 cycles
DOWNLOAD => Parsing directory <C:\ProgramData\OCS Inventory NG\Agent\download> for packages
DOWNLOAD => Package <1582128264> verified and added to process queue
DOWNLOAD => Downloading package fragment <1582128264-1>
DOWNLOAD => Building package <1582128264>
DOWNLOAD => Executing action <LAUNCH> for package <1582128264>
==============================================================================
Starting OCS Inventory NG Package Download and Setup Tool on Wednesday, February 19, 2020 11:16:55.
DOWNLOAD => Running OCS Inventory NG Download Version 2.6.0.0
DOWNLOAD => Using OCS Inventory NG FrameWork Version 2.6.0.0
DOWNLOAD => Using network connection with Communication Server
DOWNLOAD => Using Communication Provider <OCS Inventory NG cURL Communication Provider> Version <2.6.0.0>
DOWNLOAD => Starting new period of 10 cycles
DOWNLOAD => Parsing directory <C:\ProgramData\OCS Inventory NG\Agent\download> for packages
DOWNLOAD => Package <1582128264> verified and added to process queue
DOWNLOAD => Downloading package fragment <1582128264-1>
DOWNLOAD => Building package <1582128264>
DOWNLOAD => Executing action <LAUNCH> for package <1582128264>
==============================================================================
Starting OCS Inventory NG Package Download and Setup Tool on Wednesday, February 19, 2020 11:20:58.
DOWNLOAD => Running OCS Inventory NG Download Version 2.6.0.0
DOWNLOAD => Using OCS Inventory NG FrameWork Version 2.6.0.0
DOWNLOAD => Using network connection with Communication Server
DOWNLOAD => Using Communication Provider <OCS Inventory NG cURL Communication Provider> Version <2.6.0.0>
DOWNLOAD => Starting new period of 10 cycles
DOWNLOAD => Parsing directory <C:\ProgramData\OCS Inventory NG\Agent\download> for packages
DOWNLOAD => Package <1582128264> verified and added to process queue
DOWNLOAD => Downloading package fragment <1582128264-1>
DOWNLOAD => Building package <1582128264>
DOWNLOAD => Executing action <LAUNCH> for package <1582128264>
==============================================================================
Starting OCS Inventory NG Package Download and Setup Tool on Wednesday, February 19, 2020 11:24:59.
DOWNLOAD => Running OCS Inventory NG Download Version 2.6.0.0
DOWNLOAD => Using OCS Inventory NG FrameWork Version 2.6.0.0
DOWNLOAD => Using network connection with Communication Server
DOWNLOAD => Using Communication Provider <OCS Inventory NG cURL Communication Provider> Version <2.6.0.0>
DOWNLOAD => Starting new period of 10 cycles
DOWNLOAD => Parsing directory <C:\ProgramData\OCS Inventory NG\Agent\download> for packages
DOWNLOAD => Package <1582128264> verified and added to process queue
DOWNLOAD => Downloading package fragment <1582128264-1>
DOWNLOAD => Building package <1582128264>
DOWNLOAD => Executing action <LAUNCH> for package <1582128264>
==============================================================================
Starting OCS Inventory NG Package Download and Setup Tool on Wednesday, February 19, 2020 11:29:00.
DOWNLOAD => Running OCS Inventory NG Download Version 2.6.0.0
DOWNLOAD => Using OCS Inventory NG FrameWork Version 2.6.0.0
DOWNLOAD => Using network connection with Communication Server
DOWNLOAD => Using Communication Provider <OCS Inventory NG cURL Communication Provider> Version <2.6.0.0>
DOWNLOAD => Starting new period of 10 cycles
DOWNLOAD => Parsing directory <C:\ProgramData\OCS Inventory NG\Agent\download> for packages
DOWNLOAD => Package <1582128264> verified and added to process queue
DOWNLOAD => Downloading package fragment <1582128264-1>
DOWNLOAD => Building package <1582128264>
DOWNLOAD => Executing action <LAUNCH> for package <1582128264>
==============================================================================
Starting OCS Inventory NG Package Download and Setup Tool on Wednesday, February 19, 2020 11:33:04.
DOWNLOAD => Running OCS Inventory NG Download Version 2.6.0.0
DOWNLOAD => Using OCS Inventory NG FrameWork Version 2.6.0.0
DOWNLOAD => Using network connection with Communication Server
DOWNLOAD => Using Communication Provider <OCS Inventory NG cURL Communication Provider> Version <2.6.0.0>
DOWNLOAD => Starting new period of 10 cycles
DOWNLOAD => Parsing directory <C:\ProgramData\OCS Inventory NG\Agent\download> for packages
DOWNLOAD => Package <1582128264> verified and added to process queue
DOWNLOAD => Downloading package fragment <1582128264-1>
DOWNLOAD => Building package <1582128264>
DOWNLOAD => Executing action <LAUNCH> for package <1582128264>
==============================================================================
Starting OCS Inventory NG Package Download and Setup Tool on Wednesday, February 19, 2020 11:37:00.
DOWNLOAD => Running OCS Inventory NG Download Version 2.6.0.0
DOWNLOAD => Using OCS Inventory NG FrameWork Version 2.6.0.0
DOWNLOAD => Using network connection with Communication Server
DOWNLOAD => Using Communication Provider <OCS Inventory NG cURL Communication Provider> Version <2.6.0.0>
DOWNLOAD => Starting new period of 10 cycles
DOWNLOAD => Parsing directory <C:\ProgramData\OCS Inventory NG\Agent\download> for packages
DOWNLOAD => Package <1582128264> verified and added to process queue
DOWNLOAD => Downloading package fragment <1582128264-1>
DOWNLOAD => Building package <1582128264>
DOWNLOAD => Executing action <LAUNCH> for package <1582128264>
==============================================================================
Starting OCS Inventory NG Package Download and Setup Tool on Wednesday, February 19, 2020 11:41:05.
DOWNLOAD => Running OCS Inventory NG Download Version 2.6.0.0
DOWNLOAD => Using OCS Inventory NG FrameWork Version 2.6.0.0
DOWNLOAD => Using network connection with Communication Server
DOWNLOAD => Using Communication Provider <OCS Inventory NG cURL Communication Provider> Version <2.6.0.0>
DOWNLOAD => Starting new period of 10 cycles
DOWNLOAD => Parsing directory <C:\ProgramData\OCS Inventory NG\Agent\download> for packages
DOWNLOAD => Package <1582128264> verified and added to process queue
DOWNLOAD => Downloading package fragment <1582128264-1>
DOWNLOAD => Building package <1582128264>
DOWNLOAD => Executing action <LAUNCH> for package <1582128264>
==============================================================================
Starting OCS Inventory NG Package Download and Setup Tool on Wednesday, February 19, 2020 11:45:07.
DOWNLOAD => Running OCS Inventory NG Download Version 2.6.0.0
DOWNLOAD => Using OCS Inventory NG FrameWork Version 2.6.0.0
DOWNLOAD => Using network connection with Communication Server
DOWNLOAD => Using Communication Provider <OCS Inventory NG cURL Communication Provider> Version <2.6.0.0>
DOWNLOAD => Starting new period of 10 cycles
DOWNLOAD => Parsing directory <C:\ProgramData\OCS Inventory NG\Agent\download> for packages
DOWNLOAD => Package <1582128264> verified and added to process queue
DOWNLOAD => Downloading package fragment <1582128264-1>

**Comment by charleneauger** [comment]
Hi @jorensanbar ,

In 2.9 version, the deployment has been reworked.
You can find the documentation below : 
http://wiki.ocsinventory-ng.org/05.Deployment/Windows/Summary/#update-windows-agent

Best regards,
Charlene

**Comment by jorensanbar** [comment]
Hi @charleneauger ,

Thank you very much
