### ISSUE TITLE
[BUG] database name with _ mysqli error

### ISSUE THREAD

**Issue by thesvr** [OCSInventory-NG/OCSInventory-ocsreports#912]
**OCS Inventory version**
Version : 2.6

**Describe the bug**
database name with _ mysqli error

**To Reproduce**
set database name with _ 

**Expected behavior**
Escape database name everywhere.

**Comment by charleneauger** [comment]
Hi,

After several tests, we were unable to reproduce your problem. Please verify your mysql configuration.

Regards,
Charlene
