### ISSUE TITLE
[BUG] text field for info file truncated when creating teledeploy package

### ISSUE THREAD

**Issue by thenamelessthing** [OCSInventory-NG/OCSInventory-ocsreports#913]
**OCS Inventory version**
Version : 2.6 (bug exist almost since 2.5)

**Describe the bug**
Text field of info file is truncated for teledeploy package with wrong encoding type
**To Reproduce**
1. Create package
2. Enable user notification
3. In the text field, write words with french character
4. Submit the package
5. Look into the info file were the package is saved. Something like: /var/lib/ocsinventory-reports/download/1583333693
6. A part of the field text in the file is truncated.

**Expected behavior**
When we submit the package. The info file located in the same folder of the package contain all french characters in the text field.

**Screenshots**
![2020-03-04_11-00-48](https://user-images.githubusercontent.com/10235448/75898501-22834900-5e08-11ea-8825-9f276acf0746.gif)

**Additional context**

**Log file (optional)**
Apache / PHP / System log if needed

**Comment by thenamelessthing** [comment]
Je parle français aussi. Si vous voulez me parler directement, je suis sur freenode sous le pseudo namelessthing dans le canal ocsinventory-ng

**Comment by charleneauger** [comment]
Bonjour @thenamelessthing ,

Pour utiliser les apostrophes dans les messages texte de déploiement, il suffit d'utiliser le code ASCII ( &#39; ).

Cordialement,
Charlène Auger
