### ISSUE TITLE
[BUG]Missing qr code option

### ISSUE THREAD

**Issue by somzoli** [OCSInventory-NG/OCSInventory-ocsreports#914]
**OCS Inventory version**
Version : 2.6 stable

**Describe the bug**
Missing qr code option in administrative data and computers info page. Not generating QR code.

**To Reproduce**
1. Go to 'Manage/Administrative data/New data, and missing qr code in field type'

**Expected behavior**
From 2.1 in the feature list contain qr code generation.

**Screenshots**
Screenshot attached

![Screenshot 2020-03-11 at 17 22 49](https://user-images.githubusercontent.com/34423715/76439693-10cc1380-63bd-11ea-828e-f033052d08ea.png)
![Screenshot 2020-03-11 at 17 24 14](https://user-images.githubusercontent.com/34423715/76439743-26413d80-63bd-11ea-8110-068bfe313d86.png)

**Comment by gillesdubois** [comment]
Hi @somzoli ,

QRCode has been removed from the newest releases, it was using a deprecated library.

We plan on developping a plugin to re-introduce QRCode along with BarCode but its on a low priority on the roadmap. 

If this feature is really important for you, you can contact OCS Professional services to get more informations / sponsor the feature.

Regards,
Gilles Dubois.
