### ISSUE TITLE
|| [HELP] Installing files for Administration server. ||

### ISSUE THREAD

**Issue by neilkamulkar** [OCSInventory-NG/OCSInventory-ocsreports#915]
Dear Team,
Facing below problem while installation of OCSNG Administration Server please help 

+----------------------------------------------------------+
|      Installing files for Administration server...       |
+----------------------------------------------------------+

Creating PHP directory /usr/share/ocsinventory-reports/ocsreports.
Copying PHP files to /usr/share/ocsinventory-reports/ocsreports.
*** ERROR: Unable to copy files in /usr/share/ocsinventory-reports/ocsreports, please look at error in /opt/OCSInventory-Server/ocs_server_setup.log and fix !

Installation aborted !

Please assist

**Comment by gillesdubois** [comment]
Hi,

OCS Setup need to be launched as root.
Also our issue creation come with templates, please use them.

Regards,
Gilles Dubois.
