### ISSUE TITLE
[HELP] CentOS missing plugins after update from RC

### ISSUE THREAD

**Issue by bajlek** [OCSInventory-NG/OCSInventory-ocsreports#916]
Hello, I dont see any plugin/extension after update ocsinventory server from 2.6RC to 2.6 on my CentOS 7 server. I see them in extension menu, but for example Officepack dont show menu in extension, and also another plugins is not showing in All computers > Software. I suse about 15 plugins. Can you help me?

**Comment by gillesdubois** [comment]
Hi,

Since OCS contains several component, every release mean re-installing all the plugins.
We also recommend to remove them before upgrading.

Regards,
Gilles Dubois.
