### ISSUE TITLE
[FEATURE] Liste de CVE machine

### ISSUE THREAD

**Issue by steph78630** [OCSInventory-NG/OCSInventory-ocsreports#918]
**Is your feature request related to a problem? Please describe.**
Actuellement, la vérification de la compatibilité CVE d'une machine n'est pas pratique (on n'a qu'une vue générale à moins de cliquer sur chaque CVE remontée)

**Describe the solution you'd like**
Ajouter une section spécifique dans la fiche machine (par ex. section Logiciel) avec la liste des éventuelles CVE la concernant.

**Comment by gillesdubois** [comment]
Bonjour,

Le nouveau  reporting CVE dans la nightly permet une vue plus détaillée et par ordinateur.

Cordialement,
Gilles Dubois.
