### ISSUE TITLE
Request Features Software License Managers

### ISSUE THREAD

**Issue by Silente** [OCSInventory-NG/OCSInventory-ocsreports#92]
Good morning,

I wanted to know if it is possible to implement even with the next release or beta, of the additional features in my opinion very useful: For example, you can insert a page that handles the licenses purchased as Autodesk, Adobe, and other manufacturers, assign a number and availability to assign them to specific computers within the inventory with the ability to see a historian of where this license is assigned, it is changed or canceled. So you have all the software that you can not manage with plugins via ocs inventory directly! Thank you!!!

**Comment by damienbelliard** [comment]
Hi, 
It's an interesting feature. 
We will add this on the 2.3 roadmap. 
Thanks for your contribution
