### ISSUE TITLE
[FEATURE] CVE matérielles

### ISSUE THREAD

**Issue by steph78630** [OCSInventory-NG/OCSInventory-ocsreports#920]
**Is your feature request related to a problem? Please describe.**
Les CVE matérielles ne sont actuellement pas remontées

**Describe the solution you'd like**
De la même façon que les CVE logicielles, interroger les fiches machines (section Matériel) et remonter les CVE (par ex. sur les proc. Intel, etc.)

**Comment by gillesdubois** [comment]
Bonjour,

C'est une très bonne idée, malheureusement l'outil tier que nous utilisons ne gère uniquement que les failles softwares.

Cordialement,
Gilles Dubois.
