### ISSUE TITLE
[FEATURE] Message de fin d'exécution CVE

### ISSUE THREAD

**Issue by steph78630** [OCSInventory-NG/OCSInventory-ocsreports#922]
**Is your feature request related to a problem? Please describe.**
La fin d'exécution CVE n'est pas notifiée dans l'interface

**Describe the solution you'd like**
A la fin d'une exécution CVE avec mise à jour, afficher un message du genre "Les CVE ont été mis à jour, veuillez consulter les rapports" dans l'interface d'OCS

**Comment by gillesdubois** [comment]
Bonjour,

L'historique de CVE est désormais disponible permettant d'avoir une vision sur les actions réalisés par le moteur de CVE.

Cordialement,
Gilles Dubois.
