### ISSUE TITLE
[BUG] 2.7.0 release looking for vendor/autoload.php which doesn't exist

### ISSUE THREAD

**Issue by benkohler** [OCSInventory-NG/OCSInventory-ocsreports#924]
**OCS Inventory version**
Version : 2.7.0

**Describe the bug**
500 internal server error

[Tue Mar 17 08:19:27.256549 2020] [php7:error] [pid 8556] [client 192.168.228.128:59867] PHP Fatal error:  require_once(): Failed
                opening required '/usr/share/ocsinventory-reports/ocsreports/vendor/autoload.php'
                (include_path='.:/usr/share/php7:/usr/share/php') in /usr/share/ocsinventory-reports/ocsreports/require/header.php on line 31

**Comment by benkohler** [comment]
I did see issue #786 which is related, but I think that the info there is for packagers or people not using a release tarball, right?  That "composer install" should have been done as part of the 2.7.0 tarball creation, right?

**Comment by gillesdubois** [comment]
Hi @benkohler, 

Release upload went wrong i re-uploaded a proper release. Could you try by re-downloading the release from github ?

Regards,
Gilles Dubois.

**Comment by benkohler** [comment]
Yep, new tarball does work, thanks!  (I realize I did download the new one very early, I just happened to notice the new release a few hours after it hit)
