### ISSUE TITLE
[BUG] CAS error

### ISSUE THREAD

**Issue by fjcobo** [OCSInventory-NG/OCSInventory-ocsreports#925]
Version : 2.7

When CAS login is configured, the following error is obtained:

 PHP Fatal error:  Uncaught Error: Class 'phpCas' not found in /usr/share/ocsinventory-reports/ocsreports/backend/AUTH/methode/cas.php:24\nStack trace:\n#0 /usr/share/ocsinventory-reports/ocsreports/backend/AUTH/auth.php(59): require_once()\n#1 /usr/share/ocsinventory-reports/ocsreports/require/header.php(319): require_once('/usr/share/ocsi...')\n#2 /usr/share/ocsinventory-reports/ocsreports/index.php(44): require('/usr/share/ocsi...')\n#3 {main}\n  thrown in /usr/share/ocsinventory-reports/ocsreports/backend/AUTH/methode/cas.php on line 24

To reproduce:
- $affich_method = 'CAS';
- $list_methode = array(0 => "always_ok.php");
- And edit cas.config.php

**Comment by fjcobo** [comment]
I was able to solve it by adding some missing references.

**Comment by LANFDETROY** [comment]
Hello,

I have the same problem. How did you solve the problem?

**Comment by fjcobo** [comment]
Hi,

In ocsreports/var.php:
define('PHPCAS', __DIR__ . '/vendor/jasig/phpcas/CAS.php');

In ocsreports/backend/AUTH/methode/cas.php
require_once(PHPCAS);

The rest are configured the same as in previous versions.

**Comment by LANFDETROY** [comment]
ok thank you

**Comment by Blank-Vcf** [comment]
did you use cas + ldap ?
i'm looking for a working configuration since many years; ldap is currently working but cannot combine with cas.

**Comment by fjcobo** [comment]
> did you use cas + ldap ?
> i'm looking for a working configuration since many years; ldap is currently working but cannot combine with cas.

No, I'm using LDAP on CAS server side.

**Comment by gillesdubois** [comment]
Hi,

The method you were using is not used anymore since we reworked the auth methods.
Php-CAS is not bundled anymore in OCS and need to be installed on the system.

Regards,
Gilles.
