### ISSUE TITLE
[BUG] The Dashboard displays irrelevant counter in master/slave configuration.

### ISSUE THREAD

**Issue by Bexounet** [OCSInventory-NG/OCSInventory-ocsreports#927]
**OCS Inventory version**
Version : 2.7

**Describe the bug**
The Dashboard displays irrelevant counter in master/slave configuration.

**To Reproduce**
when inventory are injected with the "injector" script, the machine is not count.

**Expected behavior**
machines injected with the "injector" script should be counted.  

**Screenshots**
on my test infrastructure, I have 2 agents on virtual machines and I have imported 31381 computers with the "injector" script.
![Décompte machine 2](https://user-images.githubusercontent.com/15346653/77674732-50355b00-6f8c-11ea-8fc0-0367df1b1c4a.JPG)
If useragent is used to count windows/Unix/android computers, the machine counter, at least should be correct.
![Décompte machine](https://user-images.githubusercontent.com/15346653/77674735-50cdf180-6f8c-11ea-8d81-971de5ee6ad4.JPG)

**Log file (optional)**
Ubuntu 18.04.3 LTS

**Comment by gillesdubois** [comment]
Hi @Bexounet,

Your problem has been fixed by the PR mentionned above, you can use our nightly to try out this fix.

Regards,
Gilles Dubois.
