### ISSUE TITLE
Allowed memory size of 134217728 bytes exhausted

### ISSUE THREAD

**Issue by lucu1086** [OCSInventory-NG/OCSInventory-ocsreports#934]
**OCS Inventory version**
Version : 2.7

**Describe the bug**
When I run the cron_cve.php script it doesn't end correctly.
The PHP error is: "PHP fatal error: allowed memory size of 134217728 bytes exhausted (tried to allocate 23072768 bytes) in /usr/share/ocsinventory-reports/ocsreports/require/cve/Cve.php on line 210"
Modify the php.ini file in the "memory_limit" parameter, allocating 512M. Restart httpd, run "php73 cron_cve.php" again and the problem persists.

**To Reproduce**
1. Go to '/usr/share/ocsinventory-reports/ocsreports/crontab/'
2. Execute 'php73 cron_cve.php'

**Expected behavior**
Correct completion of results cve.

**Comment by gillesdubois** [comment]
Hi @lucu1086 ,

PHP CLI Execution shall not be restricted.
CVE is also a really intenstive process, 512M won't be enough.

Regards,
Gilles Dubois.

**Comment by lucu1086** [comment]
Hi @gillesdubois , 
Do you think it is convenient to configure memory_limit = -1?
Regards.

**Comment by gillesdubois** [comment]
Hi @lucu1086 

Sorry i didn't see your anwser.
Don't put "-1" but you can raise the 512M value a bit :)

Gilles Dubois.
