### ISSUE TITLE
[BUG] The OCS website does not load the content of the plugins' database

### ISSUE THREAD

**Issue by Eikondata** [OCSInventory-NG/OCSInventory-ocsreports#938]
**OCS Inventory version**
Version : 2.7

**Describe the bug**

OCS Plugins not work (OCS Server 2.7)

[http://ask.ocsinventory-ng.org/11988/ocs-plugins-not-work-ocs-server-2-7](url)

Bonsoir,

Nous rencontrons des problèmes avec les plugins.

Pouvez-vous nous aider?

Je vous remercie

Salutations.

**Comment by gillesdubois** [comment]
Bonjour,

D'après votre post sur le ASK vous avez installé Winusers en version 2.0.
Pouvez-vous utiliser la nouvelle version ? https://github.com/PluginsOCSInventory-NG/winusers/releases/tag/2.2
L'erreur dans vos fichiers log a l'air de faire référence a un vieux bug de ce plugin.

Cordialement,
Gilles Dubois.

**Comment by Eikondata** [comment]
Bonjour 

J’ai effectué l’installation des nouveaux plugins WinUser 2.2, mais il ne signale rien sur le site WEB OCS, dans le mysql il ya des données, la même chose se produit avec les 9 autres plugins installés. 

Il ressemble à une erreur PHP sur la page OCS qui n’appelle pas la requête qui correspond aux plugins. Dans le forum OCS, j’ai rempli plus de données. 

Je vous remercie.

**Comment by gillesdubois** [comment]
Bonjour,

J'ai tenté d'installé votre liste de plugin et je n'ai rencontré aucun problème.
Centos 8 -> OCS 2.7 Stable
Je pense que vous avez des résidu venant de l'ancienne version (dans cas ou vous venez d'une ancienne version).

Ce que je peux vous conseiller : 
- Vérifier que tous les plugins sont en dernières versions 
- Dé-installer tous les plugins et vérifier que les tables des plugins soivent bien purgée
- Ré-installer les plugins un par un et tester ET chaque plugin indépendamment. 
- Si vous rencontrez un soucis sur un plugin en particulier, faire une issue sur celui-ci.

Si jamais vous souhaitez avoir un support plus poussé ou une pris en main a distance, je vous conseil de vérifier nos offres OCS Pro si notre site web.

Cordialement,
Gilles Dubois.

**Comment by Eikondata** [comment]
![image](https://user-images.githubusercontent.com/64212881/80691491-a2f4bc00-8ad0-11ea-8915-3fd79929363c.png)
![image](https://user-images.githubusercontent.com/64212881/80691543-b3a53200-8ad0-11ea-8fe4-6362edd510c2.png)
Bonjour,

Nous avons fait ce que vous nous dites et nous avons supprimé tous les plugins, ne laissant qu'un seul (winuser) à tester.

Nous ne venons pas d'une version antérieure.

Nous avons observé que le webgui (ocs web) donne une erreur jquery datatable, car il n'obtient pas les données de l'appel ajax.php? ...

J'attache des images pour qu'elles puissent voir l'erreur.

Cela vous vient-il à l'esprit parce que cet appel ajax ne renvoie pas les données?

Je vous remercie

**Comment by gillesdubois** [comment]
Bonjour,

Ce problème est resolu dans les dernières nightly.

Cordialement,
Gilles Dubois.
