### ISSUE TITLE
[BUG] total equipment fails on my dashboard

### ISSUE THREAD

**Issue by paquin28** [OCSInventory-NG/OCSInventory-ocsreports#939]
**OCS Inventory version**
Version : 2.7

The dashboard shows the equipment summary, 126 machines, there are actually 227.

The same goes for the total of Machines contacted today, total 24 but when entering there are 41 at the moment.

I use ubuntu 17.10 and OCS Inventory 2.7
![my dash](https://user-images.githubusercontent.com/34493898/80509788-19f64d00-8937-11ea-8800-05bf65216383.JPG)
![total](https://user-images.githubusercontent.com/34493898/80509814-21b5f180-8937-11ea-896c-76ae035963c3.JPG)
![contacted today](https://user-images.githubusercontent.com/34493898/80509837-2aa6c300-8937-11ea-9e0f-eb11d25a3594.JPG)
![total contacted today](https://user-images.githubusercontent.com/34493898/80509852-2f6b7700-8937-11ea-8054-1d9f6a8145ed.JPG)
Cheers

**Comment by charleneauger** [comment]
Hi @paquin28 ,

We recently improved the dashboard, could you try with the nightly ?

Regards,
Charlene Auger
