### ISSUE TITLE
[BUG] Software counts always 1

### ISSUE THREAD

**Issue by sokatra** [OCSInventory-NG/OCSInventory-ocsreports#941]
**OCS Inventory version**
Version : 2.7

**Describe the bug**
Software counts always 1

**To Reproduce**
1. Go to '...' Inventory 
2. Click on '....'all software
3. count for software is allways 1

**Expected behavior**
difente counts for the software

**Screenshots**

**Additional context**
http://ask.ocsinventory-ng.org/12054/2-7-server-software-all-software-counts-1-one

**Log file (optional)**
Apache / PHP / System log if needed

**Comment by gillesdubois** [comment]
Hi @sokatra ,

We recently changed the way we manage software, could you try this with the nightly ?

Note : it could wipe your software inventory in the place but it will come back on the next inventories.

Regards,
Gilles DUbois.
