### ISSUE TITLE
[BUG] version number search doesn't work as expected

### ISSUE THREAD

**Issue by sokatra** [OCSInventory-NG/OCSInventory-ocsreports#946]
**OCS Inventory version**
Version : 2.7

**Describe the bug**
When i search for a software version for example "more than" 1000 i will get results which for example
contains version 6.00

I don't know how ocs exactly compares more than and less than values, but for me it looks like that ocs-inventory does not consider points

**To Reproduce**
![Capture0](https://user-images.githubusercontent.com/17703360/81076312-cf9f3e00-8eeb-11ea-9908-ccc1bc2c03dd.PNG)

![Capture](https://user-images.githubusercontent.com/17703360/81077123-d7abad80-8eec-11ea-9ed0-a0fe2f1978e6.PNG)

1. Go to '...' search with various criteria
2. Click on '....' all software.. 
3. clock on more than 
4. type in 1000
5. click on send
6. See results which aren't expected

**Expected behavior**
the result should only contain software which has a version number higher than 1000 for example 1000.9.2

**Additional context**
here is an explanation how to compare version numbers
You cannot simply remove the commas (node delimiters) and compare a single number - it may not give the correct result.
https://stackoverflow.com/questions/15807762/compare-version-numbers-in-batch-file

How to compare version numbers in Perl and for CPAN modules
https://perlmaven.com/how-to-compare-version-numbers-in-perl-and-for-cpan-modules

Perl compare version numbers 5.1 < 5.10
https://stackoverflow.com/questions/19973852/perl-compare-version-numbers-5-1-5-10

Compare two Version numbers
https://www.geeksforgeeks.org/compare-two-version-numbers/

**Log file (optional)**
Apache / PHP / System log if needed

**Comment by gillesdubois** [comment]
Hi @sokatra ,

Thx for your report, we had a long debate in the team about this subject.
Managing versions while all publishers do pretty whatever they want is really hard.

However, we found a solution on this problem, it will most likely come in 2.8 version.
We will send you a message when this feature will be available if you want to try it out :)

Regards,
Gilles Dubois.
