### ISSUE TITLE
ARMADITO ANTIVIRUS INTEGRATION

### ISSUE THREAD

**Issue by lexcorp** [OCSInventory-NG/OCSInventory-ocsreports#948]
Many organizations require extra protection against antivirus, in the market there are few free options Armadito antivirus and ClamAV for example. However, these free requests do not have any mechanism to manage virus definition database updates and distribute the software on client stations.

An ideal solution would be a web console from which you can manage the installation of the client software, update the virus definition databases, update the client versions, show alerts for infected or outdated stations, etc.

The development team for the Armadito Antivirus solution is the same development team for GLPI.

https://github.com/armadito

**Comment by sokatra** [comment]
hy it is a very interesting project .. but i think the main ocs-inventory team should concentrate on general features.

For example .. with ocs-inventory it is possible to deploy any exe or msi file. What we are missing is perhaps a "Software distribution Channel" which updates exisiting software the clients.
It principle something like a really free variant of Chocolatey or Homebrew or ketarin in OCS-Inventory.
Then you can also update update Armadito. perhaps only a plugin for Armadito is necessary.

Kind regards

Sokatra

**Comment by gillesdubois** [comment]
Hi @lexcorp ,

We don't intend to interconnect with Armadito.
As @sokatra said we prefer to focus on our main domain which is already quite big and stay in a specific / known scope.

We do provide additional service, if you really need this connector, our professional services might be able to help you on this matter.

Regards,
Gilles Dubois.
