### ISSUE TITLE
How to prevent OCSI to ipdiscover specific subnets?

### ISSUE THREAD

**Issue by StCyr** [OCSInventory-NG/OCSInventory-ocsreports#95]
Bonjour,

On a le problème suivant dans notre DB:

```sql
mysql> select count(ip) from netmap;
+-----------+
| count(ip) |
+-----------+
|    201172 |
+-----------+
```

Cela est du au fait que certains de nos ordinateurs portables tournant l'agent OCSI se trouvent de temps en temps sur un de nos réseau "public" (sur lesquels ils lancent des ipdiscover):

```sql
mysql> select count(ip) from netmap where ip like '10.5.%';
+-----------+
| count(ip) |
+-----------+
|     65723 |
+-----------+
```

Cela pollue évidemment notre DB, et je n'ai toujours pas trouvé comment empêcher cela. 

Est-ce possible d'empêcher l'ipdiscover sur certains subnet?

Bien à vous,

Cyrille

**Comment by gillesdubois** [comment]
Bonjour,

Vous pouvez blacklister des réseaux depuis le menu "Config->Blacklist" 
Il suffit ensuite d'aller dans l'onglet "add" et de sélectionner subnet.

Cordialement,
Gilles Dubois.

**Comment by StCyr** [comment]
Bonjour Gilles,

Merci pour ta réponse.

J'ai déjà essayé de blacklister les réseaux problématiques. Mais, ça n'a jamais fait aucune différence...

![untitled](https://cloud.githubusercontent.com/assets/8179031/15848247/1a56527e-2c8c-11e6-826d-4323e028cf18.png)

Tout ce qu'il se passe est que les réseaux blacklistés n'apparaissent plus dans la liste ipdiscover générale:

![untitled](https://cloud.githubusercontent.com/assets/8179031/15848313/8a83ef02-2c8c-11e6-96d5-833303f8db11.png)

Les scans ipdiscover sur ces réseaux eux continuent:

![untitled](https://cloud.githubusercontent.com/assets/8179031/15848360/d37cd462-2c8c-11e6-8fce-a176d5cb4903.png)

Bàt,

Cyr

**Comment by gillesdubois** [comment]
Si le problème est présent seulement sur quelques poste il es possible de désactiver l'élection ipdiscover sur ceux-ci.
Cela aura pour effet de les empêcher de lancer des scan ipdiscover.

Il faut aller dans computer / configuration et cliquer sur l'icone edit.

<img width="1431" alt="capture d ecran 2016-06-07 a 11 13 02" src="https://cloud.githubusercontent.com/assets/9396603/15852411/1f5a7556-2ca1-11e6-9cbd-e2a631ee5b55.png">

Gilles Dubois.

**Comment by StCyr** [comment]
hmmm je devrais désactiver l'election ipdiscover sur tous nos portables.

Maintenant, on vit avec cette situation depuis des années. Donc, est-ce-que je vais faire cette modif...?

Ceci dit, du coup, à quoi sert le blacklistage des subnets? Ça n'a pas l'air très utile.

**Comment by gillesdubois** [comment]
Les données sont remonté mais non affiché dans l'affichage global des réseaux ipdiscover.
ça permet juste de "masquer" les données.

Après il es possible de faire une action de masse pour désactiver l'ipdiscover sur tout le ordi portable si jamais ceux-ci sont clairement identifié sur ocs. (via le bouton config dans la recherche multi critère)

**Comment by gillesdubois** [comment]
Bonjour,

Je ferme l'issue dans la mesure ou la question est résolue.
Si néanmoins vous avez des retours sur le fonctionnement de cette feature vous pouvez nous faire un retour et nous expliquer ce qui pourrait être amélioré. (via mail ou issue git hub)

Cordialement,
Gilles Dubois.
