### ISSUE TITLE
[HELP] What are "invisible packages" ?

### ISSUE THREAD

**Issue by sokatra** [OCSInventory-NG/OCSInventory-ocsreports#950]
Hy i can't find any information about "invisible" packages
the wiki only shows this
https://wiki.ocsinventory-ng.org/04.Management-console-and-its-advanced-features/Managing-users-profiles-of-the-web-interface/

i don't know what is meant by invisible packages ?
can you please help?

Kind regards
Sokatra

**Comment by gillesdubois** [comment]
Hi @sokatra ,

This part of the wiki is really old and it seem more like a typo / mis-interpretation than a real information.

Regards,
Gilles Dubois.
