### ISSUE TITLE
[BUG] LDAP/LDAPs vs Active Directory

### ISSUE THREAD

**Issue by krovaxpc** [OCSInventory-NG/OCSInventory-ocsreports#956]
**OCS Inventory version**
Version : 2.7
    Version :    4.18.0-147.8.1.el8_1.x86_64
    RAM installed :    3780 MB
    Free RAM :    3047 MB
    Distribution :    CentOS Linux 8 (Core)
    PHP Version :    7.3.18
    Web Server :    Apache/2.4.37 (centos) OpenSSL/1.1.1c mod_perl/2.0.11 Perl/v5.26.3
    Database Server :    MariaDB Server version 10.3.17-MariaDB
    Version OCSReports:    2.7
installed from repository: https://wiki.ocsinventory-ng.org/03.Basic-documentation/Setting-up-a-OCS-Inventory-Server-with-rpm/

AD level 2016, DC is windows server 2016.
Win CA, certificate on DC are from win CA.

**Describe the bug**
I have problem with auth against LDAP (AD). On different system Centos 7 OCS 2.6 i have no problem with LDAPS against AD. Error i same even if settings are good or wrong.
With telnet and ldapsearch i can connect to AD.
this search work: ( ldapsearch -v -x -H "ldaps://dc.ad.example.com:636" -b "DC=ad,DC=example,DC=com" -D ocs -W "(&(objectclass=group)(cn=G LAW *))" cn dn member > completegroup.ldif )

Even ldap with port 389 not working same error, IP address, server name nothing make different.
With ldapsearch i see in security log in windows DC successful login etc..
With OCS ldap login i don't see any logs in A DC security log, failure or success.

CA of AD is added to trusted CAs.
Setup in OCS:
CONEX_LDAP_SERVEUR: ldaps://dc.ad.example.com
CONEX_ROOT_DN: CN=ocs,OU=UtilsUsers,DC=ad,DC=example,DC=com
CONEX_ROOT_PW: passwordofuserocs
CONEX_LDAP_PORT: 636
CONEX_DN_BASE_LDAP: OU=DomainUsers,DC=ad,DC=example,DC=com
CONEX_LOGIN_FIELD: samaccountname
CONEX_LDAP_PROTOCOL_VERSION: 3
CONEX_LDAP_CHECK_FIELD1_NAME: memberof
CN=OCSadmin,OU=OCS,OU=DomainGroups,DC=ad,DC=example,DC=com
CONEX_LDAP_CHECK_FIELD1_ROLE: Superadministrators
CONEX_LDAP_CHECK_FIELD2_NAME: CN=OCSuser,OU=OCS,OU=DomainGroups,DC=ad,DC=example,DC=com
CONEX_LDAP_CHECK_FIELD2_ROLE: RO
CONEX_LDAP_CHECK_DEFAULT_ROLE: "blank"

I edited two files in: /usr/share/ocsinventory-reports/ocsreports/backend/AUTH
/backend/AUTH/auth.php
/backend/identity/identity.php

$list_methode=array(0=>"local.php");
and the line below in
$list_methode=array(0=>"ldap.php");

It is also possible to use both, ldap and local authentication:
$list_methode=array(0=>"ldap.php",1=>"local.php"); 

**Log file (optional)**
Apache / PHP / System log if needed

error in php-fpm log:
PHP Warning:  ldap_bind(): Unable to bind to server: Can't contact LDAP server in /usr/share/ocsinventory-reports/ocsreports/backend/AUTH/methode/ldap.php on line 130
PHP Warning:  ldap_search(): supplied argument is not a valid ldap link resource in /usr/share/ocsinventory-reports/ocsreports/backend/AUTH/methode/ldap.php on line 76
PHP Warning:  ldap_count_entries() expects parameter 1 to be resource, bool given in /usr/share/ocsinventory-reports/ocsreports/backend/AUTH/methode/ldap.php on line 77
PHP Warning:  ldap_get_entries() expects parameter 1 to be resource, bool given in /usr/share/ocsinventory-reports/ocsreports/backend/AUTH/methode/ldap.php on line 78
PHP Warning:  ldap_close() expects parameter 1 to be resource, bool given in /usr/share/ocsinventory-reports/ocsreports/backend/AUTH/methode/ldap.php on line 79

**Comment by gillesdubois** [comment]
Hi @krovaxpc, 

Our product doesn't support LDAPs at the moment.
Please use standard LDAP. 

Regards,
Gilles Dubois.

**Comment by diegonferreira** [comment]
Good afternoon,
We are using version 2.10.0 and having difficulty configuring the integration with LDAP authentication.
Is there any documentation to assist in this process?

Muito obrigado!!
