### ISSUE TITLE
[HELP]

### ISSUE THREAD

**Issue by fourstepper** [OCSInventory-NG/OCSInventory-ocsreports#957]
Hi,

Is it possible to hide the dashboard (full overview of all the computers and software visible) per-user? I haven't found any option to configure this.

Thank you for the software!

**Comment by gillesdubois** [comment]
Hi @fourstepper, 

Unfortunately, there is no way to disable / hide the dashboard.
If you have an idea on how we could implement more customizable dashboard, please open a feature request.

Regards,
Gilles Dubois.

**Comment by fourstepper** [comment]
Thanks for the very quick response. I suppose we will configure this somehow else
