### ISSUE TITLE
[HELP] Missing data in admin_info columns

### ISSUE THREAD

**Issue by fourstepper** [OCSInventory-NG/OCSInventory-ocsreports#958]
Hello,

Earlier, we have defined custom data columns at exampledomain.com/ocsreports/index.php?function=admin_info

After an upgrade, some of the data from the columns disappeared under exampledomain.com/ocsreports/index.php?function=visu_computers

As the upgrades don't touch the DB, is it possible that something broke along the way? Where should I search for this data in mysql?

Thank you!

**Comment by gillesdubois** [comment]
Hi,

Depending on the version you are coming from, we reworked admin data and removed some data types. (such as QRCode for example).

I think there is a detailed list in releases notes.

Regards,
Gilles Dubois.

**Comment by fourstepper** [comment]
We are coming from 2.5 to 2.7, the data type was just plain text.

Interestingly, if one tries to search via the search box under exampledomain.com/ocsreports/index.php?function=visu_computers, the data is sorted according to the search, but the results are still not visually shown in the columns
