### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by keyone78** [OCSInventory-NG/OCSInventory-ocsreports#959]
**Is your feature request related to a problem? Please describe.**
Currently save as .csv file for download.

**Describe the solution you'd like**
To be able to download as .xlsx file. 

**Describe alternatives you've considered**
Use PhpSpreadsheet

**Comment by sokatra** [comment]
whats is wrong with csv? .. i think this isn't really a problem. If they have to develop such a feature their time is consumed and won't help many people i think

**Comment by gillesdubois** [comment]
Hi @keyone78 

Indeed, CSV format can easily be injected inside excel without having to do complex manipulations.
We spoke of this matter with the Team and we don't want to invest time doing this.

Regards,
Gilles Dubois.
