### ISSUE TITLE
[FEATURE] Active Directory LDAPs support

### ISSUE THREAD

**Issue by krovaxpc** [OCSInventory-NG/OCSInventory-ocsreports#960]
Please consider support LDAPs against Active Directory. 
Microsoft in new updates ditch LDAP simple auth. Its security problem using LDAP with simple auth without SSL or TLS. 
2FA as TOTP, etc... would by nice too.

Maybe add Azure AD authentication.

**Comment by gillesdubois** [comment]
Hi @krovaxpc ,

LDAPS rework is nearly done, it will permit to use LDAPS auth.
However, we don't intend to implement 2FA / TOTP anytime soon.

Regards,
Gilles Dubois.

**Comment by krovaxpc** [comment]
Hi Gilles Dubois,

thank you very much. 
I install OCS from repository, will be this update distributed by repository?
Or through manual edit?

**Comment by gillesdubois** [comment]
It will take some times but it will be on the repository in few months I think.
You can always install a server from the nightly.

Regards,
Gilles Dubois.

**Comment by gillesdubois** [comment]
Since the feature is now working, i'm closing this issue.
Don't hesistate to send us a feedback on this feature.

Regards,
Gilles Dubois.

**Comment by krovaxpc** [comment]
LDAPS against MS DC its working, thank you very much.
