### ISSUE TITLE
[BUG] WOL function not working in 2.7

### ISSUE THREAD

**Issue by ajavor** [OCSInventory-NG/OCSInventory-ocsreports#961]
**OCS Inventory version**
Version : 2.7

**Describe the bug**
In the latest version 2.7 the WOL function does not work - it does not send the wake up signal to the station.

**Comment by gillesdubois** [comment]
Hi,

I use WOL on multiples OCS infrastructure without any problems on 2.7.
Are you sure your network is properly configured to let Magic Packet go trough, be broadcasted ?

Regards,
Gilles Dubois.

**Comment by ajavor** [comment]
The WOL function only works until the ARP buffer is emptied, even for stations that have permanently assigned IP addresses. In the previous version of OCS Inventory (2.6), the WOL function worked all the time for stations with a fixed IP address.

The Magic Pockets and Broadcast configurations have not been modified and have been the same since several updates backwards.

**Comment by gitdevmod** [comment]
Hello,

I can reproduce similar problem. If I sent WOL from "Administrative data" tab 3 wol packet is sent but nothing if I sent WOL from "Network" tab. Command used to capture packets tcpdump -ni eth0 -X  udp port 9

**Comment by gitdevmod** [comment]
From Console browser, there is an error :
`function.js:93 Uncaught TypeError: Cannot set property 'value' of null
    at garde_valeur (function.js:93)
    at confirme (function.js:88)
    at HTMLButtonElement.onclick (index.php?function=computer&head=1&systemid=2436&cat=hardware:72)
garde_valeur @ function.js:93
confirme @ function.js:88
onclick @ index.php?function=computer&head=1&systemid=2436&cat=hardware:72`
