### ISSUE TITLE
Problème avec le caractère É dans la DB

### ISSUE THREAD

**Issue by freestorm** [OCSInventory-NG/OCSInventory-ocsreports#963]
**OCS Inventory version**
Version : 2.7 

**Describe the bug**
J'ai remarqué que lorsque le caractère 'É' était utilisé dans la base de donnée d'OCS-Inventory,certaines machines ou la liste des logiciels n'apparaissaient plus.

Une partie de nos postes de travail sont sous "Microsoft Windows 10 Éducation"
L'OS apparait bien sur le dashboard principal dans la liste des OS, et le décompte du nombre de poste est juste
 
Cependant, losrque je cherche une machine dont l'OS est "Windows 10 Éducation" depuis l'onglet [All computer] , elle n'apparait pas.

Si je modfie le champ "`hardware`.`OSNAME`" dans la DB en "Windows 10 Education", les postes W10Edu  apparaissent de nouveau dans OCS.

Le même genre problème apparait dans onglet [Inventory] => [All Software],
mais cette fois-ci le caractère "É" possera problèmes dans le champs "`softwares`.`LANGUAGE`" de la DB.  par example: "Anglais (États-Unis)"

La page restera en mode "proccessing" à l'infini.

**To Reproduce**
Il suffit de mettre un caractère 'É' dans le champs `hardware`.`OSNAME` d'une machine , par exemple:
"Microsoft Windows 10 Éducation"

Et de mettre un 'É' dans le champs `softwares`.`LANGUAGE` , par exemple:  "Anglais (États-Unis)"

**Server information** 

OS Name:        Linux x86_64
Version:        4.9.0-12-amd64
RAM installed:  7987 MB
Free RAM:       6446 MB
CPU:            Intel(R) Xeon(R) Silver 4116 CPU @ 2.10GHz
Distribution:   Debian GNU/Linux 9 (stretch)

PHP Version:        7.0.33
Web Server:         Apache/2.4.25 (Debian)
Database Server:    MySQL Community Server (GPL) version 5.7.30
Version OCSReports: 2.7 (problème identique avec la version 2.6)

# locale
LANG=en_US.UTF-8
LANGUAGE=en_US:en
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"

**Comment by charleneauger** [comment]
Bonjour @freestorm ,

Je n'arrive pas reproduire votre problème.  Avez-vous fais plusieurs update d'OCS ou est-ce une première installation avec une base de données clean ?

Cordialement,
Charlène Auger

**Comment by freestorm** [comment]
Bonjour @charleneauger,

J'ai fais plusieurs migration de la base de données (depuis la version 21.2)

Comme vous n'arrivez pas a reproduire le BUG, je vais essayer de repartir sur une base de données vierge.
Je vous tient au courant.

Meilleures salutations
Frédéric

**Comment by freestorm** [comment]
Bonjour @charleneauger,

J'ai réinstallé un seul PC sur une DB vierge et j'ai toujours le problème.
Donc ça ne vient pas de la migration anciennes versions d'OCS

J'ai attaché le dump SQL ci-dessous:
[ocsweb_2020-07-13_06h25m.Monday.TXT](https://github.com/OCSInventory-NG/OCSInventory-ocsreports/files/4912797/ocsweb_2020-07-13_06h25m.Monday.TXT)

Est-ce qu'avec ces données vous arrivez à reproduire mon BUG?

Meilleures salutations
Frédéric

**Comment by gillesdubois** [comment]
Bonjour,

J'ai essayé avec plusieurs serveurs SQL Ainsi qu'avec votre dump sans aucun soucis.
Tous les serveurs étaient avec des configurations différentes.

![Capture](https://user-images.githubusercontent.com/9396603/90373055-a5742500-e071-11ea-82ee-51d99d11fbe9.PNG)

Cordialement,
Gilles Dubois.

**Comment by freestorm** [comment]
Bonjour,

Merci pour votre réponse.

Je dois avoir un problème de configuration d'apache ou de ma distribution Linux.

Est ce que vous pouvez me dire sous quel distribution vous avez testé et aussi quelles sont vos paramètres de langue système (commande locale) ainsi que le charset d'apache. (UTF-8 , ISO-8859-15)

Salutations
Frédéric

**Comment by charleneauger** [comment]
Bonjour,

Pour ma part j'ai testé sur un serveur Ubuntu 18.04.5 avec comme paramètres de langue système par défaut : 
LANG=C
LANGUAGE=
LC_CTYPE="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_COLLATE="C"
LC_MONETARY="C"
LC_MESSAGES="C"
LC_PAPER="C"
LC_NAME="C"
LC_ADDRESS="C"
LC_TELEPHONE="C"
LC_MEASUREMENT="C"
LC_IDENTIFICATION="C"
LC_ALL=

Apache en charset UTF-8

J'espère que ces informations vous aideront.

Codiralement,
Charlène

**Comment by freestorm** [comment]
Bonjour,

J'ai enfin trouvé d’où venais mon problème.

A un moment donné, j'ai changé la variable "default_charset" dans le fichier /etc/php/7.0/apache2/php.ini
J'avais mis "iso-8859-1" à la place de la valeurs par défaut "UTF-8"

Voila pourquoi le moteur php d'Apache2 n'arrivait pas a afficher certains caractères spéciaux, dont le 'É' 

Mille fois merci d'avoir passé du temps sur ce problème.

Je clôture ce BUG qui n'en était pas un.

Salutations
Frédéric
