### ISSUE TITLE
Lost valuable function of the export script.

### ISSUE THREAD

**Issue by fireboltgp** [OCSInventory-NG/OCSInventory-ocsreports#97]
In the OCS NG Version 2.1 was very useful function. There was an ability to export list of all computers with specific columns on the "All computers" web-page. The ability to export data which I choose and see on the web-page. Now in version 2.2 I can export all computers only with full information, with all columns. 50% of functionality is lost at this moment.

**Comment by gillesdubois** [comment]
Hi,

Thanks you for reporting this enhancement.
We will investigate the issue and will try to fix it / make a return asap.

Regards,
Gilles Dubois.

**Comment by beber38** [comment]
Salut,

Je viens de faire la MAJ en 2.2.1 est toujours d'actualité, (same problem with new version 2.2.1)

Merci pour tout au top OCS,

Bernard

**Comment by gillesdubois** [comment]
Hi,

All update on this issue will be made on this link : https://github.com/OCSInventory-NG/OCSInventory-ocsreports/issues/97

Regards,
Gilles Dubois.
