### ISSUE TITLE
Inventory -> All software - Count always 1

### ISSUE THREAD

**Issue by 90er** [OCSInventory-NG/OCSInventory-ocsreports#972]
Hi,

i recently updated to OCS Inventory NG 2.7 (CentOS 7, PHP 3, MariaDB 5).

I often use List Inventory -> All software (/ocsreports/index.php?function=visu_all_soft).
Since version 2.7 (i guess), the column "Count" always has the number "1" instead of the correct number of related computers, which is confusing. I would really like to get the correct number of related computers like before.

Thanks for your work.

Wolfgang, Germany

**Comment by Parnoud** [comment]
Same problem on a fresh install, and the "all a software" on the startup page seem to be wrong too (Value diefference between index and all software total rows)

**Comment by gillesdubois** [comment]
Hi,

Please can you try with our nightly ?
download.ocsinventory-ng.org/nightly

Regards,
Gilles Dubois.

**Comment by Blank-Vcf** [comment]
i have same problem, update to 03/07 daily
software table is empty
got 500 error in agent log


> 	INVENTORY => XML Update 2 Printer(s)
> 	INVENTORY => XML Update 421 Software
> 	INVENTORY => XML Update 0 Registry Value(s)
> 	INVENTORY => XML Update Administrative Information(s)
> 	INVENTORY => XML Update common Device properties
> 	COM SERVER => Initializing cURL library for sendRequest
> 	COM SERVER => Using cURL without server authentication
> 	COM SERVER => Disabling cURL proxy support
> 	COM SERVER => Enabling cURL SSL server validation support using CA Bundle <xxxpem>
> 	COM SERVER => Sending HTTP Post request to URL <https://xxxxx/ocsinventory>
> 	COM SERVER => HTTP Post response received <HTTP Status Code #500>
> 	COM SERVER => Cleaning cURL library


and in oscinventory server log: all agent in error


Fri Jul  3 10:35:10 2020;24930;318;xxxxxx-2020-01-24-12-01-01;xxx.xxx.xxx.xxx;OCS-NG_WINDOWS_AGENT_v2.4.0.0;session;missing
Fri Jul  3 10:35:10 2020;24930;114;xxxxxxx-2020-01-24-12-01-01;;xxx.xxx.xxx.xxx;OCS-NG_WINDOWS_AGENT_v2.4.0.0;inventory;no_session
Fri Jul  3 10:35:10 2020;24930;104;5PARU1674-2020-01-24-12-01-01;;xxx.xxx.xxx.xxx;OCS-NG_WINDOWS_AGENT_v2.4.0.0;inventory;incoming
Fri Jul  3 10:35:10 2020;24930;113;xxxxxx4-2020-01-24-12-01-01;xxx.xxx.xxx.xxx;OCS-NG_WINDOWS_AGENT_v2.4.0.0;inventory;u:drives
Fri Jul  3 10:35:10 2020;24930;113;xxxxxx4-2020-01-24-12-01-01;10.224.202.169;OCS-NG_WINDOWS_AGENT_v2.4.0.0;inventory;u:softwares
Fri Jul  3 10:35:10 2020;24930;515;xxxxxx-2020-01-24-12-01-01;;xxx.xxx.xxx.xxx;;OCS-NG_WINDOWS_AGENT_v2.4.0.0;end;error

**Comment by Blank-Vcf** [comment]
in 7030.sql think it missing "s" in table name should be softwares ?
have reverted to 7029 with deletion of all software* table agent and recreating them based on of ocsbase.sql; now the agents are correctly inventoring

**Comment by gillesdubois** [comment]
Hi @Blank-Vcf 

We made a rework of the software implementation, the missing "s" is intended.
The 500 error is not related to this change since the communication server has also been updated.
You should check if your server has been properly updated.

Regards,
Gilles Dubois.

**Comment by charleneauger** [comment]
Hi @Blank-Vcf @90er @Parnoud ,

Recently we fixed software inventory on server. Can you try we the latest nigthly ?

Best regards
Charlene Auger

**Comment by 90er** [comment]
Hi @charleneauger ,

i updated from 2.7 to 2.7-nightly-2020-07-07 and i lost all my already inventarized software (Administative data, Hardware, Network, Devices is ok but Software is empty on all computers). Seems like a bug for me. I restore my latest backup, because i need these informations.

I can confirm, that with the nightly 2020-07-07 the count is fixed.

Wolfgang

**Comment by charleneauger** [comment]
@90er ,

Like @gillesdubois said, software feature has been entirely reworked. The table schema has been changed and thus we had to wipe the old software entries. But they will come back with the next inventory. 

Regards,
Charlene Auger

**Comment by charleneauger** [comment]
I close this issue because the initial bug is fixed.
