### ISSUE TITLE
[FEATURE] stats en fonction des droits 

### ISSUE THREAD

**Issue by Parnoud** [OCSInventory-NG/OCSInventory-ocsreports#974]
**Is your feature request related to a problem? Please describe.**
Dans mon cas je donne un accès à OCS en lecture à des agents, mais la page d'accueil (ocsreports/index.php?first)  affiche toujours les stats totaux du serveur OCS et non ceux dont le compte à la visibilité.

**Describe the solution you'd like**
Il serait intéressant de pouvoir avoir la page d'accueil qui donne les stats en fonction des machines que le compte peut voir.

**Comment by gillesdubois** [comment]
Bonjour,

Merci pour votre retour, nous voyons comment intégrer ça.

Cordialement,
Gilles Dubois.
