### ISSUE TITLE
Error in Dashboard "A problem of OCS news data recovery has occurred"

### ISSUE THREAD

**Issue by silvaguilherme** [OCSInventory-NG/OCSInventory-ocsreports#977]
**Version- 2.7.0.0**

Hello
When I log in and open my dashboard, the message "A problem of OCS news data recovery has occurred" appears

I did the installation a few days ago, at the beginning it was normal, now that I applied the GPO to install the agent. In total I have 250 devices inventoried.
Another thing I noticed is the slowness to open the dashboard, it takes around 30 seconds to open, while other pages take the normal time, 3-5 seconds.
Thanks for the help.

**Comment by gillesdubois** [comment]
HI @silvaguilherme 

We have a service that query our central server on internet to retrieve the OCS News so you can has access to them from your instance.
When the instance is restricted it can lead to these problem. 

You have to disable the news system : 
- Go to configuration -> General configuration menu
- Go on interface tab
- Disable "WARN_UPDATE" and "ACTIVE_NEWS"

Regards,
Gilles Dubois.

**Comment by silvaguilherme** [comment]
Thanks

**Comment by fpotier** [comment]
I have the same problem when I turn on the news, I think it is because it doesn't use my proxy. Is there a way to specify a proxy ?
