### ISSUE TITLE
[HELP] Stable Version OCS Server

### ISSUE THREAD

**Issue by massinlaaouaj** [OCSInventory-NG/OCSInventory-ocsreports#979]
Hello, I would like to implement OCS on a Linux server, but I really have the question of whether the latest versions are stable, as well as whether they can support the plugin that imports from OCS to GLPI.

The one I would like to know is that the current version is stable and I can use the GLPI plugin without giving me any kind of problem.

Thanks!

**Comment by gillesdubois** [comment]
Hi,

You will have to use the 2.7 stable version in order to have full compatibility with GLPI.

https://github.com/OCSInventory-NG/OCSInventory-ocsreports/releases/tag/2.7

Regards,
Gilles Dubois.

**Comment by massinlaaouaj** [comment]
Hi, thanks for your response. This is the last version they have, is it really tested to be stable ?, since I am going to implement it in a real environment.
And do you know which version of GLPI is compatible with OCS version 2.7?

Regards.

**Comment by gillesdubois** [comment]
Yes, this is an official release which mean its stable.
You can take the latest version of GLPI with the latest version of the OCS connector plugin.

Regards.
