### ISSUE TITLE
Plugin Manager: installation page remains white when certain php-lib is missing

### ISSUE THREAD

**Issue by ronator** [OCSInventory-NG/OCSInventory-ocsreports#98]
I tried to install a plugin.zip over the web ui. I clicked on install and it obviously did nothing and showed me a white page (menu was still available). No error was shown. The apache/error.log was quite helpful though:

PHP Fatal error:  Uncaught Error: Class 'ZipArchive' not found in /usr/share/ocsinventory-reports/ocsreports/plugins/main_sections/ms_plugins/functions_check.php:20

I use php7 so I had to install php7.0-zip (and libzip4) and after that the plugin installation worked flawlessly. I wonder if it would be possible to show such fatal php errors in the web ui if - apparently - some packages seem to be missing so that you do not need to search in the webserver logs for errors. For me, this is a minor issue, but I assume in such situations any error displayed is better than just a white, empty page.

**Comment by gillesdubois** [comment]
Hi,

Fixed : https://github.com/OCSInventory-NG/OCSInventory-ocsreports/commit/a1c2d65a053b3efce06b091c9e041584492a3a83

Thanks you very much for reporting this :)

Regards,
Gilles Dubois.
