### ISSUE TITLE
OCS Inventory NG 2.2.1 : Profil utilisateur

### ISSUE THREAD

**Issue by ynlamy** [OCSInventory-NG/OCSInventory-ocsreports#99]
Bonjour,

Je viens d'installer la mise à niveau du serveur OCS Inventory NG en version 2.2.1, il m'est toujours impossible de créer un profil utilisateur.Cette fois-ci, j'obtiens l'erreur : 

> An error occurred while submitting the form. Please check your internet connection.

Le profil personnalisé créé auparavant, n'est pas répertorié dans la liste des profils disponibles.

Cordialement.

**Comment by MyTheValentinus** [comment]
Hello @ynlamy 
Le soucis n'est plus présent dans la version 2.2 de l'OCS report.
![bf39a01102fa5be3cc5d3b557d74da89](https://cloud.githubusercontent.com/assets/6104498/16407816/f38af7d6-3d15-11e6-8e00-a46e5bf65dc1.png)
 J'ai pu créer sans soucis des utilisateurs
Bonne journée !

**Comment by zufflaur** [comment]
En fait, il faut passer à la version 2.2.1 pour régler le souci des profils utilisateurs
Excellente journée

**Comment by ynlamy** [comment]
Bonjour,

J'ai bien le problème avec la version 2.2.1 suite à une mise à niveau depuis la 2.1.2.
Le profil créé précédemment n'est pas récupéré après le passage en 2.2.1 et impossible de créer un nouveau profil.

Cordialement.

**Comment by MyTheValentinus** [comment]
Bonjour, 
Je viens de faire une install propre sur un serveur, aucun soucis de création de profil sur la dernière version stable la 2.2.1.
![image](https://cloud.githubusercontent.com/assets/6104498/16482797/d244c262-3eb1-11e6-9cbc-af0446f9e778.png)
