### ISSUE TITLE
Cannot view computer in OCS WebGUI 

### ISSUE THREAD

**Issue by ameyangne** [OCSInventory-NG/OCSInventory-ocsreports#990]
Hi,
I have installed OCS inventory NG server 2.7 onto CentOS 8 and successful.

But when i go to WebGui i can see some computer is reporting to new server but i can not view detail always processing.

Please help.

![2020-07-21_15-13-52](https://user-images.githubusercontent.com/68585938/88039299-fe30ca80-cb64-11ea-97dd-6eb6ae7f2ab0.png)
![2020-07-21_15-14-09](https://user-images.githubusercontent.com/68585938/88039300-ff61f780-cb64-11ea-972c-eea3598dd78d.png)

**Comment by gillesdubois** [comment]
Hi @ameyangne, 

Could you provide us your javascript console when performing this action ?
Also, can you confirm us that you are not using private navigation nor any script blocker extension on your browser ?

If you don't see any visible error in the console log, could you try with our nightlies ? download.ocsinventory-ng.org/nightly

Regards,
Gilles Dubois.

**Comment by ameyangne** [comment]
Dear Gilles,

Here are the answers for your questions.

Could you provide us your javascript console when performing this action ?
-> 

Also, can you confirm us that you are not using private navigation nor any 
script blocker extension on your browser ?
-> There in no blocker, I have checked with all browsers.
If you don't see any visible error in the console log, could you try with 
our nightlies ? download.ocsinventory-ng.org/nightly
->Installed nightlies but no success same issue.


Freundliche Grüße / Kind regards

Amey Angne
Sr. Consultant-Corporate IT-Infra
Corporate IT

Hettich Competence Services Pvt. Ltd.  |  Platinum Techno Park, 12th Floor  |  IT/ITES Office No: 1201-1202  |  Sector 30A, Plot No 17 & 18  |  Vashi, Navi Mumbai-400705  |  Maharashtra  |  India
Phone: +91 22 67670 941  |  Mobile: +91 90040 91559  |  Fax: +91 22 2756 5668  |  amey.angne@hettich.com  |  https://www.hettich.com
Registered office Vashi, Navi Mumbai  |  U74990MH2009PTC191535
Director: Daniel Giesselmann (DIN: 08617746), Pankaj Mahajan (DIN: 02634580)

**Comment by ameyangne** [comment]
Any updates on reported issue.

**Comment by gillesdubois** [comment]
Hi @ameyangne 

Sorry, I didn't saw you message.
In my opinion, It is an ajax / content policy error thing.
Is there any proxy / policy that could block ajax ?

Can you try to install OCS outside your office network just to be sure that no external services could block OCS behavior ?

Regards,
Gilles Dubois.

**Comment by gillesdubois** [comment]
Hi,

Any news on this ? 
Can you try to update to the 2.8 ?

Regards,
Gilles.
