### ISSUE TITLE
Dynamic groups affected by softwares table dropped

### ISSUE THREAD

**Issue by pchamo** [OCSInventory-NG/OCSInventory-ocsreports#991]
I tried the ocsinventory server last daily build from July 20th. I realized that the softwares table was dropped so the queries as dynamic groups need to be updated by hand.

I had queries like this one in dynamic groups:

`1) => SELECT DISTINCT hardware.ID FROM hardware INNER JOIN softwares on hardware.id = softwares.hardware_id WHERE softwares.NAME LIKE '%Microsoft Office Professional Plus 2019%' GROUP BY hardware.id`

The updated query is:

`1) => SELECT DISTINCT hardware.ID FROM hardware INNER JOIN software on hardware.id = software.hardware_id LEFT JOIN software_name on software_name.id = software.name_id LEFT JOIN software_publisher on software_publisher.id = software.publisher_id LEFT JOIN software_version on software_version.id = software.version_id WHERE software_name.NAME LIKE '%Microsoft Office Professional Plus 2019%' GROUP BY hardware.id`

I have no problem updating these queries, but wouldn't be possible to provide an option to update those dynamic groups queries automatically? That would be more useful for people who have a lot of dynamic groups.

On the other hand, the software installed data for old inventoried computers is lost until the computers inventories are updated. That was not so good but perhaps it was a change needed for improving OCS.

**Comment by gillesdubois** [comment]
Hi,

Indeed, with the nightly with don't have any release / upgrade notes, they will comes along with the 2.8 release that will come fall 2020 (september / october).

However, we won't update the dynamic groups automatically since it would require too much work to have a work script.

Regards,
Gilles Dubois.
