### ISSUE TITLE
[BUG] Deployment doesn't work

### ISSUE THREAD

**Issue by pintyoke** [OCSInventory-NG/OCSInventory-ocsreports#992]
**OCS Inventory version**
Version : 2.7

OS version: Debian 10.4.0

**Describe the bug**
Deployment does not work on the (v2.7) new server. 

**To Reproduce**
1. Add deployment package (zip)
2. Deploy to client machine
3. Feedback: notify
4. The package does not install

**Expected behavior**
I tried agent versions 2.6.1.0 and 2.7.0.0. Same mistake. The cacert.pem file is good!

/var/lib/ocsinventory-reports/
drwxrwxr-x root www-data download

Package parameters:

<DOWNLOAD ID="1595077848" PRI="5" ACT="EXECUTE" DIGEST="af0348a5933c0e4c7eb54efb0d190b78" PROTO="HTTP" FRAGS="1" DIGEST_ALGO="MD5" DIGEST_ENCODE="Hexa" COMMAND="firefox.exe /ms" NOTIFY_USER="0" NOTIFY_TEXT="" NOTIFY_COUNTDOWN="" NOTIFY_CAN_ABORT="0" NOTIFY_CAN_DELAY="0" NEED_DONE_ACTION="0" NEED_DONE_ACTION_TEXT="" GARDEFOU="rien"

**Log file (optional)**
Agents log:

DOWNLOAD => Package <1595077848> verified and added to process queue
    DOWNLOAD => Processing packages for cycle 1 on Sunday, July 19, 2020 20:27:20
    DOWNLOAD => Pausing for cycle latency (1 seconds)
    DOWNLOAD => Pausing for period latency (1 seconds)
DOWNLOAD => Starting new period of 1 cycles
    DOWNLOAD => Flushing package queue
DOWNLOAD => Parsing directory <C:\ProgramData\OCS Inventory NG\Agent\download> for packages
    DOWNLOAD => Verifying package <C:\ProgramData\OCS Inventory NG\Agent\download\1595077848>
DOWNLOAD => Package <1595077848> verified and added to process queue
    DOWNLOAD => Processing packages for cycle 1 on Sunday, July 19, 2020 20:27:23
    DOWNLOAD => Pausing for cycle latency (1 seconds)
    DOWNLOAD => Pausing for period latency (1 seconds)
DOWNLOAD => Starting new period of 1 cycles
    DOWNLOAD => Flushing package queue
DOWNLOAD => Parsing directory <C:\ProgramData\OCS Inventory NG\Agent\download> for packages
    DOWNLOAD => Verifying package <C:\ProgramData\OCS Inventory NG\Agent\download\1595077848>
DOWNLOAD => Package <1595077848> verified and added to process queue
    DOWNLOAD => Processing packages for cycle 1 on Sunday, July 19, 2020 20:27:26
    DOWNLOAD => Pausing for cycle latency (1 seconds)

and

AGENT =>  Communication Server asked for Package Download
    DOWNLOAD => Found OCS Inventory Agent Setup result file <C:\ProgramData\OCS Inventory NG\Agent\download\OCSNG-Windows-Agent-Setup_done>
ERROR *** DOWNLOAD => Found result code <SUCCESS> for OCS Inventory Agent Setup package but no package ID specified, so remove all packages to avoid running Agent setup in loop !
    DOWNLOAD => Package history file successfully cleaned for duplicate IDs
    DOWNLOAD => Metadata file <info> for package <1595077848> is located at <https://ocs.otthon.local/download/1595077848/info>
    COM SERVER => Initializing cURL library for getFile
    COM SERVER => Using cURL without server authentication
    COM SERVER => Disabling cURL proxy support
    COM SERVER => Enabling cURL SSL server validation support using CA Bundle <cacert.pem>
    COM SERVER => Sending fileGet request to URL <https://ocs.otthon.local/download/1595077848/info>
    COM SERVER => fileGet response received <HTTP Status Code #200>
    COM SERVER => Cleaning cURL library
    DOWNLOAD => Unloading communication provider
    DOWNLOAD => Retrieve info file...OK (pack 1595077848)
DOWNLOAD => Package <1595077848> added to download queue
DOWNLOAD => Download and setup tool successfully started
AGENT => Unloading communication provider
AGENT => Unloading plug-in(s)
AGENT => Execution duration: 00:01:06.

Please help me. Thank you!

**Comment by gillesdubois** [comment]
Hi @pintyoke, 

The only thing that could cause this behavior is : 
```
ERROR *** DOWNLOAD => Found result code for OCS Inventory Agent Setup package but no package ID specified, so remove all packages to avoid running Agent setup in loop !
```

You should try to stop the service, remove history and download folder content (keep ocsinventory.ini inside that folder).

But seeing your log file : 
```
DOWNLOAD => Retrieve info file...OK (pack 1595077848)
DOWNLOAD => Package <1595077848> added to download queue
DOWNLOAD => Download and setup tool successfully started
```

It seems that your package, is executed succesfully, you should check the package content. 
FYI, firefox.exe /ms is not used anymore please use firefox.exe /S ...

Regards,
Gilles Dubois.

**Comment by pintyoke** [comment]
Dear Gilles Dubois,

I did what you described. Unfortunately, the same phenomenon. :(

Best regards,
pintyoke

**Comment by pintyoke** [comment]
Dear Gilles Dubois,

I started all over again. New server, new agent. The problem persists. 

Best regards,
pintyoke

**Comment by HillGnur** [comment]
Hi all, I'm having the same issue, checked the info files, no useful info, just a XML header with the timestamp and some other labels all with a `0` in its values
