### ISSUE TITLE
Connected User is blank on some stations.

### ISSUE THREAD

**Issue by silvaguilherme** [OCSInventory-NG/OCSInventory-ocsreports#993]
Hi

I looked in some forums, but I couldn't find a solution that would help me.
I have an error where some machines do not return the "Connected User" and others it appears as "SYSTEM" user
I would like to know if it is something that must be configured or something else.
Thank you very much.

![erro-ocs](https://user-images.githubusercontent.com/18178268/88588726-6d5b6280-d02e-11ea-8a16-d04fccfd82e6.png)

**Comment by charleneauger** [comment]
Hi @silvaguilherme ,
The connected user is empty or system if the Windows agent sends inventory when no one is logged on the machine.

Regards,
Charlene Auger
