### ISSUE TITLE
[BUG] mysql 8.0  reserved word conflict with table name  column name

### ISSUE THREAD

**Issue by keyone78** [OCSInventory-NG/OCSInventory-ocsreports#996]
**OCS Inventory version**
Version :  2.6 and above

**Describe the bug**
if mysql 8.0 is install , the group page unable to load.
Due to table name groups is an reserved name in mysql 8.0
so best practice it will be great for all table name to add backtick  for all table name.

Apache / PHP / System log if needed

**Comment by gillesdubois** [comment]
HI @keyone78 

I'm currently checking this, there is a lot of modifications due to this new reserved word.
I will crate a pull request for the server and the webconsole soon.

Regards,
Gilles Dubois.
