### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by lble44** [OCSInventory-NG/OCSInventory-ocsreports#997]
**OCS Inventory version**
Version : 2.7

Hi,
I have an issue to import softwares in my GLPI with the plugin ocsinventory ng. When I try to import new computers with software option enabled, it doesn't work.
Here is the sql-errors_log, it seems like the table ocs.softwares is missing :
[2020-07-31 13:07:32] glpisqllog.ERROR: DBmysql::query() in /var/www/html/glpi/inc/dbmysql.class.php line 188
*** MySQL query error:
SQL: SELECT
softwares.NAME,
softwares.VERSION,
softwares.PUBLISHER,
softwares.COMMENTS,
softwares.FOLDER,
softwares.FILENAME,
softwares.FILESIZE,
softwares.SOURCE,
softwares.HARDWARE_ID,softwares.GUID,
softwares.LANGUAGE,
softwares.INSTALLDATE,
softwares.BITSWIDTHFROM softwares
WHERE softwares.HARDWARE_ID IN (1)ORDER BY id DESC
Error: Table 'ocs.softwares' doesn't exist
Backtrace :
...ns/ocsinventoryng/inc/ocsdbclient.class.php:340
...s/ocsinventoryng/inc/ocsdbclient.class.php:1008 PluginOcsinventoryngOcsDbClient->getComputerSections()
plugins/ocsinventoryng/inc/ocsclient.class.php:374 PluginOcsinventoryngOcsDbClient->getComputers()
...ns/ocsinventoryng/inc/ocsprocess.class.php:1159 PluginOcsinventoryngOcsClient->getComputer()
plugins/ocsinventoryng/front/ocsng.sync.php:52 PluginOcsinventoryngOcsProcess::synchronizeComputer()
{"user":"9@PAH-FUSION01"}

Thank's in advance for your answers.

Version :
    OCS Server : 2.7
    plugin ocs : 1.6.1
    GLPI : 9.4.4

**Comment by charleneauger** [comment]
Hi @lble44 ,

Since 2.7 nightly, the software datamodel has been changed. We opened an issue on ocsinventoryng GLPI plugin, [here](https://github.com/pluginsGLPI/ocsinventoryng/issues/243). We are not responsible for the plugin, so we can't do anymore for you.

Best regards,
Charlene Auger
